### ISSUE TITLE
Activity_Model_Exception on user posts to another user's profile (Redmine Bug #2662)

### ISSUE THREAD

**Issue by shivani2910** [SocialEngine/phpv4-issues#1]
## Bug:

Activity feed posts are now throwing this exception on posts a user has posted to a non-friend user's activity feed:
```
exception 'Activity_Model_Exception' with message 'No attachment to link comments to' in G:\www\py\application\modules\Activity\Model\Action.php:434
Stack trace:
#0 G:\www\py\application\modules\Activity\views\scripts_activityText.tpl(179): Activity_Model_Action->likes()
#1 G:\www\py\application\libraries\Zend\View.php(108): include('G:\www\py\a...')
#2 G:\www\py\application\libraries\Zend\View\Abstract.php(890): Zend_View->run('G:\www\py\a...')
#3 G:\www\py\application\libraries\Zend\View\Helper\Partial.php(109): Zend_View_Abstract->render('_activityText.t...')
#4 [internal function]: Zend_View_Helper_Partial->partial('_activityText.t...', 'activity', Array)
#5 G:\www\py\application\libraries\Zend\View\Abstract.php(350): call_user_func_array(Array, Array)
#6 G:\www\py\application\modules\Activity\View\Helper\ActivityLoop.php(65): Zend_View_Abstract->_call('partial', Array)....
```
posts are successfully recorded in the database

## Solution:

Looking at the log error quoted, it seems that the problem is being caused due to a 3rd party plugin installed on your website.

There is a feature of Likes and Comments synchronization which we've included in our recent release of SE PHP 4.8.7. Now, you seem to be using a 3rd party plugin on your website (like 3rd party videos, music or any content based plugin in which content would be getting added as an attachment via activity feed) and these issues would be coming because of any of the below mentioned reasons:

1) The corresponding 3rd party developer has not yet made their plugin compatible with this Likes and Comments synchronization feature.
2) A content in that 3rd party plugin on your website is deleted but the activity feed still exists in database because of which this error is coming.

This issue can be resolved by doing a quick fix. Please copy the contents of the file [Action.php] (https://gist.githubusercontent.com/shivani2910/c4d0548d1fb72e5a156e/raw/a2d202411b0e5c4e2333468d399e4bd6e6043e0e/Action.php) and replace the one at ```/application/modules/Activity/Model/Action.php```.

**Comment by smazurov** [comment]
fixed in [4.8.8](http://blog.socialengine.com/2015/03/23/socialengine-php-4-8-8-released/)
