### ISSUE TITLE
General Settings' Head Scripts/Styles are not output on mobile site

### ISSUE THREAD

**Issue by CLG-Brainstorm** [SocialEngine/phpv4-issues#10]
I have a custom font being loaded via stylesheet referenced in General Settings but it does not appear in the mobile site HTML output on version 4.8.6 or 4.8.7

**Comment by shivani2910** [comment]
Hi @CLG-Brainstorm, 

If you're using our core Mobi Plugin and add some script from the admin panel's General Settings section then that script will work for both full site and our mobi plugin. If you're using a 3rd party mobile plugin and having some issue in that 3rd party plugin then please contact the respective developer for support.

If you're having any issues with our core modules, please feel free to contact our support team.

Best Regards,
Shivani
