### ISSUE TITLE
Choose Default Profile Image

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#100]
This ability doesn't exist, it should.

**Comment by smazurov** [comment]
Its really really simple to do manually. seTweaks helped out a member very recently with that same issue. http://community.onsocialengine.com/post/3359731/how-to-change-default-profile-photo

**Comment by Elshara** [comment]
I see. Cool. Could this be perhaps made available I'm thinking under
member level settings. It'd be cool to upload images right from the
control panel some day.
