### ISSUE TITLE
Let Members Choose Their Own Theme And Profile Layout Including Widgets And Permissions

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#101]
This should exist for people to have a better control over what theme they want not just in css, but in a theme design studio. Allow people to choose their own profile layout and add any widget they like, assuming you can control what type of things members can add to their profile page. It would be nice to see links for members specific archived content, not just as a widget, but as something they can click on perhaps under information setting or as its own widget. This type of control should also be available for content creators, especially groups and events while still being able to choose a default layout for such things.

**Comment by shivani2910** [comment]
@Elshara, we've already provided basic feature of "Edit Style" under "Edit Profile" section using which users can add styles to their profile, change background color, etc. For more advanced features in this direction, admins can go for 3rd party plugins.

Thanks
