### ISSUE TITLE
Quick Add Response Feature

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#102]
When members receive updates, they currently only have the option to view where the update is located. Giving members the ability to respond to it as well as view it from the same window, as well as choosing how many updates they want to see within that window, will allow members to easily respond to things they have subscribed to. A quick add box would give members the ability to add something in a pop up box without leaving the page they are on. Similarly, comments could appear in such windows.

**Comment by shivani2910** [comment]
@Elshara, could you please elaborate this one more using some screenshots so that we're able to understand your perspective in a better manner.

Thanks

**Comment by Elshara** [comment]
Some software uses shortcuts to quickly add or jump to the ability to
respond to posts.
