### ISSUE TITLE
Custom Member Sorting Options

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#103]
A few pages on social engine allow members to custom sort items based on category, search and popular view. This should be expanded some for all modules, getting rid of the ability to have a set number of results per page, but instead making that a global default, allowing members to enter any number they wish or choosing from a set of predefined choices.

**Comment by shivani2910** [comment]
Hi @Elshara,

Thanks for your feedback. But since we've already provided well defined pagination on all the browse pages, users can easily navigate through different pages. So, we feel that there is no need to add additional field.

Thanks
