### ISSUE TITLE
SE Creates a new album for every photo added to the forum

### ISSUE THREAD

**Issue by tbermudas** [SocialEngine/phpv4-issues#105]
It's confusing. Maybe its better to insert all the user photos added to the forum in one album.

**Comment by Anshuse** [comment]
Hi @tbermudas ,

Thanks for bringing this issue to our notice.

We've added this issue in our internal bug tracker for our team to have discussion over this.

Best Regards,
Anshu

**Comment by smazurov** [comment]
GbX9tT98m@6Nq?
