### ISSUE TITLE
Profile forum topics and post block and Ning imported data

### ISSUE THREAD

**Issue by tbermudas** [SocialEngine/phpv4-issues#106]
The Ning imported posts and topics are not listed on the member profile blocks for topics and post.

**Comment by smazurov** [comment]
We actually have a fix for this, unfortunately it didn't make it in time for 4.8.9. It will be updated in the next version. You can download the fix [here](https://www.dropbox.com/s/vcis3vekv9aegz3/ning_forum_import_fixes.zip?dl=0). Extract the folder and overwrite the files at the path that they're at.

**Comment by tbermudas** [comment]
Thanks!
