### ISSUE TITLE
Group-Topic_discussion uploaded photos creates a new album on every each photo.

### ISSUE THREAD

**Issue by happycoder1337** [SocialEngine/phpv4-issues#107]
Can we make groups and other modules's uploaded photos to upload only to a single album?

-And group's photo lacks a proper way to manage multiple photos. people have to reload the page to edit or remove each single photo.

**Comment by smazurov** [comment]
This can be done by contacting 3rd party developers, its not currently on our roadmap to improve.

**Comment by shivani2910** [comment]
@happycoder1337: 1st part of this issue is similar to the one you've reported here: https://github.com/SocialEngine/phpv4-issues/issues/105
We've already noted it down at our end and will work on this further. Thanks.

**Comment by happycoder1337** [comment]
the blogs module works this way why cant the rest?

**Comment by smazurov** [comment]
We'll look into ensuring no new photo albums are created for groups, forums, and events.

**Comment by happycoder1337** [comment]
great, thanks hope to see them fix on 4.9

**Comment by Elshara** [comment]
A solution would be to have the option to include photo albums in groups and events, not required.
