### ISSUE TITLE
Storage Quotas doesn't work for Members

### ISSUE THREAD

**Issue by happycoder1337** [SocialEngine/phpv4-issues#110]
File calculation and Storage Quotas for members dont work.

**Comment by Anshuse** [comment]
Hi @happycoder1337 ,

Thanks for bringing this to our notice.

We've reported this issue in our internal bug tracker and our development will take required action on this after analyzing the case.

Best Regards,
Anshu

**Comment by DonnaScriptTechs** [comment]
This is fixed for our 4.9 release once it is released.

**Comment by Elshara** [comment]
Awesome.
