### ISSUE TITLE
Forum attachments 

### ISSUE THREAD

**Issue by tbermudas** [SocialEngine/phpv4-issues#111]
The possibility to add attachments to forum topics and replies. (images, pdf...)
Enhancement.

**Comment by Anshuse** [comment]
Hello @tbermudas ,

There's already an option in the Tinymce Editor in Forums section to upload/insert an image in the Forum topic and replies but we don't have any plan to add the option to attach pdf files.

Best Regards,
Anshu

**Comment by Elshara** [comment]
Maybe social engine doesn't, but radcodes has a solution for this called file sharing.
