### ISSUE TITLE
Spam and Banning Settings resets after refresh

### ISSUE THREAD

**Issue by happycoder1337** [SocialEngine/phpv4-issues#112]
The settings for spam and banning page resets after you re-hit the URL and press Go.

**Comment by smazurov** [comment]
Please see guidelines on how to submit [bug reports](https://github.com/SocialEngine/phpv4-issues/blob/master/CONTRIBUTING.md#bug-reports)

**Comment by happycoder1337** [comment]
why call this place bug tracking if we cant submit any bugs?
"A while ago, we moved our public bug tracker from Redmine to GitHub. Most of you have already been filing requests / suggestions over the new bug tracker, which is great!"

**Comment by smazurov** [comment]
Because you haven't answered my question, I can't help you if I don't know how to experience the same issue.  Since you're active elsewhere in these issues, we've assumed you were unable to provide us with more information.  Since we can't help you and you can't give us more info, this issue can be closed.

**Comment by happycoder1337** [comment]
this is what you responded the 1st time:
"Please see guidelines on how to submit bug reports"
you never asked me for more information.

do you have trouble understanding my sentence?
"The settings for spam and banning page resets after you re-hit the URL and press Go."

**Comment by Elshara** [comment]
Hi. This is because database settings don't save when saving changes in this area.

**Comment by shivani2910** [comment]
@Elshara and @happycoder1337 : We've been able to reproduce the issue and forwarded this to our team. We'll resolve this in next version. Thanks.

**Comment by Elshara** [comment]
Awesome!
