### ISSUE TITLE
Forum layout editor

### ISSUE THREAD

**Issue by tbermudas** [SocialEngine/phpv4-issues#113]
Add the possibility to edit columns in Topic view page.

**Comment by Anshuse** [comment]
Hello @tbermudas ,

Thanks for your suggestion. We already have a plan to improve the pages in the "Layout Editor" section of Admin Panel in near future.

Best Regards,
Anshu

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#4

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
