### ISSUE TITLE
Adding "Ukrainian Hryvnia" as currency

### ISSUE THREAD

**Issue by meetgerry** [SocialEngine/phpv4-issues#114]
I am using my SE Site in Ukraine targeting Ukraine users. I do not see the option to select "Ukrainian Hryvnia" currency.

Kindly treat this important and assist me, please.

**Comment by Anshuse** [comment]
Hi @meetgerry ,

We have provided a particular set of currencies in SocialEngine and if you need to add any other currencies on your site then you can customize the code at your end.

Best Regards,
Anshu

**Comment by meetgerry** [comment]
I understand and I am fine with it. I used Text Crawler to find the currencies, but did not manage to find which file is used to add additional currency. Kindly help me with the files that has to be edited.

**Comment by Anshuse** [comment]
Hello @meetgerry ,

You will need to make changes in below 3 files:

1) ```application/libraries/Engine/Payment/Gateway/PayPal.php```

2) ```"application/libraries/Engine/Payment/Gateway/2Checkout.php"```

3) ```application/libraries/Engine/Payment/Gateway/Testing.php```

But we're not sure that if Paypal and 2Checkout support Ukraine currency and so, please make sure this at your end first and then edit the code accordingly.

Best Regards,
Anshu
