### ISSUE TITLE
Shout Out To Host Iso

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#115]
Awesome, outstanding company with so much to say is seriously worth hosting with them.
I recommend featuring them somehow in an article. Services like Arvixe may have extensive help documentation for social engine features, but their hosting doesn't at all make arvixe and other hosts like them, worth a penny of your money since they never pay attention to any problems, debugging or otherwise and have lots of error database queries, page errors and other memory leaks. Bad but not important, introducing Host Iso and the reasons why they're the top of the line.
1. Social Engine optimization, they know what they're doing. One Semi-dedicated server with them with default social engine settings makes Amazon AWS look cheap in comparison quality wise.
2. They may not have a cloud, but what they do have is beyond phenomenal support and are as good as 2 minute response times whether your server is temporary down or whether you have any questions, queries or anything else.
3. Works great with CometChat and other livestream applications with native support for all video requirements and caching applications from memcake, to ffmpeg to red5 to apc, modrewrite and lots more. If you ask it, chances are its either available as an add on or is already added by default to all servers.
4. Flexible payment plan. They work with you no matter your budget, no contracts either and they make you really feel welcome with quality phone, email and live chat support any time.
5. My experience with them is still supreme. Surprisingly enough they don't use the best hardware for their service, but if and when they do upgrade, it's extremely stable and I've not had any errors with them at all. Only down side is if you prefer to manage your own, they're more of a sit back and let us take care of it for you kind of company, but if you insist on knowing specific details, they won't intrude unless you ask. You get the best of both worlds if they know you're a pro and you say that in support tickets, otherwise, they optimize everything for you, including installing any paid for scripts for free if necessary.
They don't automatically send your site out to search engines either. Use a service like pingdom.com to do this automatically on your own terms if and when you feel the need to do so. Keep in mind they use go daddy domains for everything. If you aren't a fan of go daddy, you can always switch to name cheap which is much better and flexible if you have to separate your domain from your host at any time.
Speaking of hosts, security and permissions, Host Iso also gives you default cloud flare integration features so that you don't have to worry about anyone dos attacking your name server with flood requests. This way, any load at all gets transferred to the script itself, which means, only the script you put up on your site will load. Faster site and more secure as a result. Just remember to keep out the spam bots if you find they are a bit much. With social engine login history, you can just blacklist their ip in spam banning tools under settings, so you can set and forget.
Yeah, great company, excellent support and best social engine host out there. If that's not enough, a special thank you to Hire Experts for teaming up with them. A constantly improving hosting provider who is more than willing to help you out no matter your experience level and give free security and speed tips two.

**Comment by Anshuse** [comment]
@Elshara , As the content is not related to any feature and bug regarding SocialEngine PHP so, we're closing this one. Thanks!

**Comment by smazurov** [comment]
you can instead post this on community.onsocialengine.com (you can get invited through your customer dashboard on socialengine.com)
