### ISSUE TITLE
Serious Bug! Error Inviting Members To Group

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#116]
Since 4.8.9 was released, social engine has trouble when selecting members to a group.
1. Members selected do not appear in the order of "join date" as they did in 4.8.8. They appear alphabetically. This makes it harder to invite new members to a popular group such as a welcome or support center.
2. More importantly, when selecting members to join the group, the number of members being selected stays the same regardless of whether they have been invited or not. This is a serious problem because when trying to invite a member who has been invited but you don't know who has been or is already a member, social engine throws a nasty error message detailing a member has already been invited. Not only do you not know who, but you have to go into developer mode just to find this out as it isn't displayed within the error log.
3. Selecting an uninvited member is successful but the member still shows up after they've been invited to invite for someone else who has that member on their friends list. The error reappears for that member and where ever the error appears, no member gets an invite at all. This also is the case for members who have pending invitations. On large sites, you may not be able to see who has been invited and who isn't due to so many members if invited being on who ever has them on their friends list. In other words, group invitations only work if you know preemptively which members have not been invited, have a pending invitation or are already members for the only person who can see this activity is the group creator and other admins.
This is a serious bug.

**Comment by DonnaScriptTechs** [comment]
Can you please recheck this on latest version? I've tested and am unable to reproduce this issue.

**Comment by Elshara** [comment]
IT works on latest version. Sometimes rendering times out and you get
a token time out error, but the database query usually holds at a 50%
chance of success of failure depending on the operation.

**Comment by Elshara** [comment]
:)
