### ISSUE TITLE
Desktop Notifications

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#117]
In social engine, desktop notifications (member updates) cannot be changed from its current position at the top of the site when using either the mini menu layout editor or the site layout editor along with search bar.

**Comment by Anshuse** [comment]
Hi @Elshara ,

Thanks for your suggestion. We've reported this suggestion in our to do list along with the issue https://github.com/SocialEngine/phpv4-issues/issues/97

Best Regards,
Anshu

**Comment by poeticjustice** [comment]
Implemented niiiiiiiiiiiiiiiiiiiiiiiice

**Comment by Elshara** [comment]
lol
