### ISSUE TITLE
Deleting User Photo Thumbnail Error

### ISSUE THREAD

**Issue by happycoder1337** [SocialEngine/phpv4-issues#118]
When you upload a photo, and edit its thumbnail, then delete the photo.
you get php server error:
Fatal error: Call to a member function getStorageService() on null in
.../application/modules/User/controllers/EditController.php on line 181

Fresh install of SE: 4.8.9

**Comment by Anshuse** [comment]
Hello @happycoder1337 ,

Thanks for bringing this issue to our notice.

We've reported this issue in our internal bug tracker for our team to resolve this issue in near future release.

Best Regards,
Anshu

**Comment by meetgerry** [comment]
I would like to point out something which every other SN on the Earth follow and which SE is behind.

During sign or profile edit, when uploading photos it only prompts you for thumbnail to be trimmed and applies a neat square photos only to thumbnails. Its highly recommended that the main photo or all PROFILE PHOTOS which gets added during signup or during profile photo edit should by default get trimmed and stored as square.

The simple reason being, users could use any dimension photo and if they are not trimmed and stored with equal dimension, SE site loses its uniform layout.

I know this can be achieved
![2015-07-593](https://cloud.githubusercontent.com/assets/8540750/8508307/eabdd8d4-2273-11e5-9ba1-c9ecc3918d59.png)
 by custom modification, but this is a core feature which needs to be incorporated to SE by default.

**Comment by meetgerry** [comment]
Refer profile view screenshot below on your demo site:
![2015-07-594](https://cloud.githubusercontent.com/assets/8540750/8508311/0d616068-2274-11e5-8e06-a22760af24a1.png)

**Comment by smazurov** [comment]
@meetgerry please open an new issue for your request as its separate from the error being reported.

**Comment by meetgerry** [comment]
Will do!

**Comment by happycoder1337** [comment]
hey gerry, i'm pretty used to se4, if you have any questions you can ask me. I can also help you develop your site. =p i might need a RU expert later on. =p

**Comment by meetgerry** [comment]
Sure, please Skype me business.today

**Comment by DonnaScriptTechs** [comment]
This is fixed for 4.9 when it is released.

**Comment by Elshara** [comment]
Awesome.
