### ISSUE TITLE
Invitations

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#119]
In social engine, it is only possible to send 10 invites per round of people by default. This should be increased to an unlimited number or to whatever number desired. Sometimes, messages aren't fully flushed from mail cue.

**Comment by Anshuse** [comment]
Hi @Elshara ,

We have noted down your suggestion in our internal suggestion tracker and will discuss with our team to take appropriate action on this.

Best Regards
Anshu

**Comment by Elshara** [comment]
Awesome. This will be a serious help.

**Comment by Elshara** [comment]
Can the number of invites max sent be changed?
