### ISSUE TITLE
Problem On Turkish language

### ISSUE THREAD

**Issue by akilivan** [SocialEngine/phpv4-issues#12]
When I switch to Turkish language then I can't see the counts of commands, views, like and other messages. There shows only commans but not the counts. 

For example;

On English Language:   5 Comments, 12 Views,  8 Like
On Turkish Language: ,, (only 2 commas)

Can anybody help me to fix this problem?

**Comment by shivani2910** [comment]
Hi @akilivan, 

This is not a known issue in our core module. Such issue might appear due to incorrect translations in Turkish language pack on your website. To verify this, please check ```"/application/languages/tr/custom.csv"``` file and then check if these phrases are translated properly or not.

If you still have any further queries, please feel free to contact our support team.

Best Regards,
Shivani

**Comment by akilivan** [comment]
Hi Shivani,

Thank you for your reply. 
All the phrases was translated and was working before Upgrade.
But after upgrade I get this problem. I dont have any problem on English language as I told you. But on "Turkish" language it is problem on show the phrases when have a counting. It dont shows the phrases when have a number (count) to show.

If you need I can send you my FTP informaiton.

Best Regards,
Ahmet

**Comment by shivani2910** [comment]
Hi Ahmet,

For us to look deeper into this issue on your website, we'll need you to file a support ticket from your account along with the admin login and FTP credentials of your website so that our support team can look into this issue further.

Best Regards,
Shivani

**Comment by akilivan** [comment]
Hi Shivan,

Sorry, I dont understand. From where need to create a Support ticket? 
Can you send me a link please?

Thanks,
Ahmet

**Comment by shivani2910** [comment]
Hi Ahmet,

You can open a support ticket from here: https://www.socialengine.com/client/ticket/create.
If your support coverage has expired then you'll need to purchase support extension from here: https://www.socialengine.com/client/store

Best Regards,
Shivani
