### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#120]
In social engine, some settings cannot be changed such as the global pagination for forums, members, groups and other plugins. When pagination or number of posts is selected in the activity feed, it doesn't always take effect when viewing your own items.

**Comment by Anshuse** [comment]
Hi @Elshara ,

1) Regarding "In social engine, some settings cannot be changed such as the global pagination for":
We have noted down this suggestion at our end for our internal team discussion.

2) Regarding "When pagination or number of posts is selected in the activity feed":
If you're referring to "Overall Feed Length" field then it works perfectly in SocialEngine, you may check the same on your demo site: http://demo.socialengine.com/. If you're facing this issue specifically on your installation then you may contact our support staff along with your site details and they will be happy to help you out.

Best Regards,
Anshu

**Comment by Elshara** [comment]
Only issue seems to be with pagination in global settings for now.

**Comment by shivani2910** [comment]
@Elshara We rechecked this pagination thing at our end and found that we already have "Listings per page" setting in the Global Settings section of all the modules on our website (except Events that we've already noted down to our features list). Based on this setting, list of items is displayed on the browse content page of all the modules. If you're talking about something else, please specify more using screenshot.

**Comment by Elshara** [comment]
You got it right, that is what I'm talking about. Members page doesn't
have this option.

**Comment by DonnaScriptTechs** [comment]
This is improved in 4.9.
