### ISSUE TITLE
Appoint Network Creators

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#122]
Super admins should have the option of choosing custom rolls for people designed to be network creators, in charge of certain features and master updates for the site.

**Comment by Anshuse** [comment]
Hi @Elshara , Thanks for your feedback. We've provided 3 Member Levels i.e Admin, Super Admin and Moderators who have access to the admin settings. You can customize the code at your end as per your requirements.
Thanks!
