### ISSUE TITLE
Autoplay Option For Playlists

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#123]
Members should be able to edit the widgets that appear on their profile. If they edit things like how many posts can be displayed or how photos appear either as a slideshow or how posts appear such as newest or most popular, they should be able to add a music player to their page two and be able to control weather or not it will autoplay.

**Comment by Anshuse** [comment]
Hi @Elshara ,

Thanks for your feedback. This feature will make the things more complex and so, we can't consider this feature for SocialEngine but if you want to have this feature on your site then you can customize the code at your end as per your requirements.

Best Regards,
Anshu

**Comment by Elshara** [comment]
Well actually, I'm not letting this one go just yet. Videos autoplay
by default when ever they load, I don't see why playlists can't as an
optional checkbox in admin settings.
