### ISSUE TITLE
Video Controls

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#124]
Currently members do not have many controls for videos They can only enter titles descriptions and tags. They should be able to put their videos into custom playlists and control how videos appear including whether they autoplay or not.

**Comment by Anshuse** [comment]
Hi @Elshara ,

We're sorry but we don't have any such plan to implement this feature in our Module.

Best Regards,
Anshu

**Comment by Elshara** [comment]
I'd have thought since youtube was such a problem for people as of
late, keeping in mind that your script is the only one effected with
this change upon further review, compared  to phpfox, dolphin and many
others including wordpress, you'd take videos a little more of a
priority as per core functionality of Social Engine since they are a
lot of communities main attraction, including mine.

**Comment by shivani2910** [comment]
@Elshara We understand what you're trying to say. There are multiple 3rd party plugins available on the following page of our website that could be useful for you to get such advanced features on your website:
http://www.socialengine.com/customize/se4/plugins

**Comment by Elshara** [comment]
I've looked at this, I'd have bought one if I could find what I'm
looking for. Just something simple really. Video playlists and an
autoplay feature.
