### ISSUE TITLE
More Options For Groups

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#125]
The ability to add videos, blogs and custom information doesn't currently exist for groups. this is important as it signifies members ability to design their own group if they so choose and should be able to make it their own space as apart of a network.

**Comment by Anshuse** [comment]
Hi @Elshara ,

We're sorry but we don't have any such plan to implement this feature in our Module.

Best Regards,
Anshu

**Comment by Elshara** [comment]
I'll move to phpfox that has had this for years if it isn't considered soon.

**Comment by socialengineaddons** [comment]
Hi @Elshara,

Thanks for showing your interest in SocialEngine. We have gone through the various issues filed by you here. 

Many of the features required by you can be fulfilled well by [our plugins] (http://www.socialengineaddons.com/catalog/1/plugins). Please have a look at [our demo website] (http://demo.socialengineaddons.com/) once.

Regarding your query above specific to Groups, our [Groups / Communities Plugin] (http://www.socialengineaddons.com/socialengine-groups-communities-plugin) can be suitable for you as it has the advanced features mentioned by you. We even compared it with PHPfox groups, and it is more robust and advanced compared to that as well. To check out the demo of this plugin, please [visit here] (http://demo.socialengineaddons.com/groups).

For any queries regarding this or our other plugins, please [contact us] (http://www.socialengineaddons.com/contact).

**Comment by Elshara** [comment]
Thanks for the info. I do like your script better, I wouldn't be
nearly as dedicated if I didn't believe in its future. I am 100%
committed to improving social engine, this is the only reason why I'm
this interested in making sure it is as good as what us, the customers
and users wish to support as our main and production line of work as a
platform.
Thanks for the links will check them out. Being an ex phpfox users, I
know this market is much better and so having said that, I know it can
be improved better if we only had one thing going for us, a solid team
working on updates real customers and users commit to sharing. Sorry
if this offends you, it isn't meant this way. I truly believe once a
php roadmap is rolled out, this will all become more clear over time,
and it is one of the most fascinating things we see in social engine
at least for now, is just to know people are working on some things,
instead of things never being done, as is the case with other scrips.
I took the original "not planned" comment wrongly and I apologize for
that, you are doing a great job. I just would hate to see this product
collect dust such as Ning and other scripts, working out the bugs
before a major release happens would be ideal as a possible
improvement so having feature suggestions looking into potential bugs,
is in my opinion, one of the best ways to make sure this is known so
that as each potential fix is suggested for a reported feature, we can
test it before it is made live to all users, as what has happened with
the youtube video issue. I love how this was handled btw.
You rock.

**Comment by smazurov** [comment]
We appreciate your activity here and thank you for kind words!

As @socialengineaddons mentioned, they have a great solution to your immediate issue. We are a small outfit, having to create and constantly update all different features is something we do not have time for.

Our philosophy is to give users the best platform first, allowing 3rd party developers to fill in missing functionality. This means having a stable script that works on vast majority of servers, having a great website to showcase and make it easier to find those plugins for users, and having support and infrastructure in place to offer best in class integration solutions that tie it all together.  

With the new marketplace and its certification system, we'll be bringing such comparisons front and center and we'll allow developers to showcase their creations. Your feedback will be incorporated to ensure our users are well educated on all options (including those from certified 3rd party developers).

**Comment by meetgerry** [comment]
You should not be even comparing PhpFox with SE. If you are behind setting up a serious community you should be going with SE. I have tested and tried many CMS, I landed here with SE and since then I am here. One best thing is SE has tons of addons and you can build almost anything you want. Take a look at http://bolfox.com

You may choose modules from SocialEngineAddons, Webhive or HireExperts. Their support is awesome.

Do not ever think of buying any modules from YouNetCo, they have plenty of good looking modules, but they have plenty of bugs and they give a damn to you when asking for help.

**Comment by Elshara** [comment]
No offense meant, but I am exactly the opposite to you in this regard.
I've always bought from younet since they are really the only phpfox
developer that has made a lot towards the community. I've never had a
problem with their code and I find their licensing feature to be very
speedy, up to date and more importantly, secure and bugless. Phpfox
has always had a secure and fast, stable and reliable code base. No
hidden limits, no resolve through editing code files issues, no
outrageous costs.
Social Engine Add Ons is okay, but I know many who has experienced a
problem with them. Web Hive I know from the phpfox community as well,
they are okay and make some good ideas possible.
Hire Experts makes good plugins two, I've also heard of Ipregmatic for
social engine, I'm checking them out, seems pricey though.
All in all, doesn't matter about layout as much. If something is fast,
stable and reliable, it's got my vote for a good community. To be
honest, no end user wants to spend time on a dead or poorly
functioning site. Sites built on such platforms are about the users as
much as they are about what people unite for. Members want something
to do on a site, whether it's posting content or connecting with
others. Don't go plugin ritch in my experience. I've been trying to
get social engine to put outbound rss feeds for native content just as
inbound rss feeds existing for third party content, one of the reasons
why phpfox is better in this regard, but it seems nobody wants this.
You have to stay plugged into the community. Phpfox has a much better
design in proving just how much you can customize at least through its
native script, the ins and outs of functional ways in which
communities can be kept clean. Yes it is more like facebook than
anything else, social engine has a far superior layout editor than
phpfox and so customizing is easier, however phpfox you can do a lot
more things with menus and navigation as well as posting seems much
easier. I plan to use both scripts for a joint project right now I'm
sticking with social engine, I do like it better.

**Comment by meetgerry** [comment]
Either you must be a rep from YouNetco or you must one out of the thousand lot.

I have 10 to 12 tickets stinking always. They reply to tickets once in 3 days and the replies have nothing in it. You give a development environment to bug fix, they say no and only want to work on live site.

You pick 5 out of their 10 modules and scroll down the reviews part, you will find many crying stocks like me who paid, and when started using them, come across so many issues. Its been months, no updates, no bug fixes and finally felt like throwing them into the garbage.

**Comment by Elshara** [comment]
Luckily, I don't bother with support via third party mods. I use the
bare minimum necessities, it either works or it doesn't no questions
asked I'm just happy with what does and remove what doesn't through
the database if at all necessary.
I don't work for younet at all. I've used them because they make 3
plugins I really enjoy. Inviter, advanced notification and menu
system. I'm considering the wall plugin. Only problem I ever had with
them is their minify plugin. I did purchase a profile styler from them
and it works great. I don't know what problems you've had, I've been
on sites where their advanced forum, members, groups and events
plugins were installed and have used them as a member, without any
problems. Unless you buying nulled plugins from some third party site,
I recommend a fresh update. I get newsletter updates about their
latest stuff and so I can't say they don't update their products.
Perhaps their support is a little bad, I don't know I never tried it.
I suggest putting up a review on the social engine add ons page if you
want to share your opinion, like I said before not all developers will
make a good product. In fact, I like less than half the products
offered whether they do their job or not. I just want a simple,
functional, fast loading, easy to manage site members find works for
them. I said before, I'm not one to go all out and install hundreds of
mods because it offers features that can be reappropriated within
something that already exists functionality wise. As for the little
things, avatar tools and advanced messaging editor and fancy menu and
other widgets, yeah, they're cool and all, but what gets me going, is
an organic need to keep updated on the things the community is about.
I'm talking core functionality here, whether its invites, posting
content, finding direct ways to interact with existing content and or
making sure that said content is essentially accessible, the main area
of the site comes first and so having said that, I just don't see what
a custom mobile app or some weird tagging widget or advanced search or
contest or badges or whatever has anything to do with ensuring people
enjoy the site as much as they get something out of it. If people
spend a lot of time with tools they don't need, perhaps it's just the
market I'm targeting, but from a business perspective, less is more
and what all is there is and should be available at all times.
Activity feed, its great but not essential. I'd say blogs, photos,
groups and videos are used most out of all the sites. What people can
easily access right from where they are at, they will click on, access
is the key, especially when it comes to them knowing where to look in
advance. It shouldn't take 3 months of browsing a site, to figure it
out. This is why many sites that are successful like facebook and
twitter, already know this, and have implemented ways for content and
people to find each other and make such a trend, as viral as it is
today.
I got to tell you, phpfox in this regard is much better at this, user
engagement. Social engine is just as well for its design functionality
can all be customized per page, yet still, I can't stress enough the
importance of core quality modules. Who cares about credits or making
money, people will use what they have to if they want it bad enough,
doesn't mean platform users have to suffer, keeping in mind,
everything has its purpose, and having say more than 12 modules on a
site makes little sense considering the truth of the matter remains
that unless a module is used for something specific, if it has to be
contained within a long menu to get at it, it isn't as visible as it
should be. All that to say this. Younet is very good at providing core
functional modules, buggy or not, I'd trust them as opposed to hire
experts or even Web Hive, if a provider takes years to update, perhaps
they're going to have some overlapping ideals put forth by other
developers. Hey, at least they put an effort in to making something,
no matter what, that has to count for something regardless of how it
works, if people can use it, chances are, it will stay as is. I'll say
this, if anyone could develop a bookmarks feature, that would be
essential for members. No I'm not talking about likes, but bookmarks,
a global favorites system members can manage with one click that
autoscrolls so people can easily manage pages they like, that prevents
all the unnecessary menus and ads on other pages, I tell you search,
favorites and probably feeds or notifications of some sort are the 3
most used tools on the web. For a social site, it involves getting the
word out there to non members and inviting existing members to
participate in an ever growing conversation, ideally. Otherwise, well,
you are faced with the inability to reshare something important to you
and suggesting things to people, is very good. Again I say this,
younet has provided all this within their modules, I know, it has a
purpose somewhere.

**Comment by shivani2910** [comment]
Hi everyone (@Elshara and @meetgerry ) , we can see that discussions are getting off the subject in this thread. Since the core purpose of this bug tracker is to get your valuable feedback (any bugs you might be experiencing or features you want to suggest), I request you to stay on the topic.
If you have any issues with the services or plugins of any 3rd party developers that you would have used on your website, you can always leave your reviews on that developer's / plugin's profile based on your experiences.

Clean and organized communications in these issues helps us better consolidate your feedback. Thanks.

**Comment by Elshara** [comment]
Re: Younet. I see what you mean. Younet obviously coded much better
for phpfox, I've checked out some of their latest plugins for social
engine, and it appears you're right. Lazy code job I'm surprised since
I get monthly updates from them. Having used them with phpfox for
ever, I've always recommended them. Funny thin was, I just never liked
the name, something off about it, so yeah I see your point and think
they could improve.
Having said that, their advanced notification, advanced layout editor,
profile styler and advanced activity feed work pretty good. I
recommend those plugins for sure. As for the others however, on the
surface it looks doable, the functions work, but the coding is very
sloppy. Yeah, trial tested, shoot me.
Link me to the profile page, I'll post my feedback. Sorry about being
off topic, Younet has good ideas for modules that should work but
aren't as functional as they really should be. They get a lot more
activity in phpfox that's for sure. Everything from their advanced
music to their contact importer to every other module you can think
of, has a bug or two in it. I still swear they just copied phpfox
menus to their advanced menu plugin, it works way too familiar to be
their own code.
Yeah, I didn't want to believe they were that bad, but having seen it
personally, wishing I could just dump all the files I installed cause
when I access layout editor, I see their pages even after disabling
their plugins, hmm. No need to be angry, like I said before. It either
works or it doesn't. If something doesn't work right like for example
with their advanced groups, you aren't able to view previous and next
items or switch between modes, even their advanced search and advanced
events have bugs. I don't know what happened to forums blogs are okay
but too complex, way too many extra widgets also. Lol and here I was
thinking they were streamlined, no that was just phpfox and its
ability to probably solve half the bugs it faced with due to caching
of some sort, you realize their caching system is primitive and a
little over enforced but it does the trick quite well. Just wished it
improved its ajax functionality.

**Comment by meetgerry** [comment]
Apologies & noted!
