### ISSUE TITLE
Cloudflare

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#126]
Social engine should support cloudflare's infamous redirection problem. When ever cloudflare tries to redirect someone from posting something, social engine should keep the post in the editor unless the person moves to another page if redirected or they go elsewhere on the site.

**Comment by Anshuse** [comment]
Hi @Elshara ,

We're not sure if you're trying to say that if there're some unsaved changes on current page of site and member mistakenly/unknowingly try to navigate/close that page then a pop-up regarding warning for unsaved changes being lost should appear on site. Please confirm.

Best Regards,
Anshu

**Comment by Elshara** [comment]
I'm saying that if a member tries to save their changes, they are lost
when cloud flare redirects them. Not just that, but after personally
using it, it appears that cloud flare is not compatible with mobile.
