### ISSUE TITLE
Categories For Polls

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#127]
Polls should support more things than just a title and a description and the possible answers they hold. They should support categories, people should be able to answer polls right from the poll home page and categorize polls based on the kinds of things people may show an interest in.

**Comment by Elshara** [comment]
Polls should support being attached to other posts.

**Comment by Anshuse** [comment]
Hi @Elshara , Thanks for your feedback but we're sorry as currently, we don't have any such plan to implement categories in Polls plugin. 
Thanks!
