### ISSUE TITLE
Simple Uploader With Link To Switch

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#128]
Social Engine should support a simple uploader, browser based which could be used as an alternative to flash uploader. It should be easy to implement.

**Comment by Anshuse** [comment]
Hi @Elshara ,

We have reported this issue at our end for our development team to work on this in near future.

Best Regards,
Anshu

**Comment by Elshara** [comment]
Thanks! This will be a huge help.

**Comment by DonnaScriptTechs** [comment]
This is fixed for 4.9 when it is released.

**Comment by Elshara** [comment]
Awesome! This is one of those issues I've really truly been looking forward to.
