### ISSUE TITLE
HTML5

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#129]
Social engine should support HTML5 and css3 by default.

**Comment by Anshuse** [comment]
Hi @Elshara ,

Regarding "HTML 5": 
HTML5 is already supported in our Videos module, where else do you want HTML 5 to be supported.

Regarding "Css3":
We have noted down your suggestion in our internal bug tracker for our internal team discussion.

Best Regards,
Anshu

**Comment by Elshara** [comment]
I'm thinking music player and text editor.

**Comment by DonnaScriptTechs** [comment]
I'm closing this one and keeping #686 open as other clients are already in that one and both of these are the same.

**Comment by Elshara** [comment]
Thanks Donna.
