### ISSUE TITLE
Cannot register to the website after upgrade to 4.8.7 when anti-spamming is enabled for email at signup

### ISSUE THREAD

**Issue by huseyin-cakmak** [SocialEngine/phpv4-issues#13]
Hi, 

When the option "Enable anti-spamming technique in signup form?" is set to yes from admin panel (http://MyDomain/admin/core/settings/spam) then the signup form keeps throwing an error saying that the email provided is not valid. 

If the option is not enabled (set to "No") then it seems to work. 

Here is the error message : 

		2015-02-24T15:05:48+00:00 CRIT (2): 
		Error Code: 467bc9
		exception 'Zend_Form_Exception' with message 'Invalid name provided; must contain only valid variable characters and be non-empty' in  /application/libraries/Zend/Form/Element.php:497
		Stack trace:
		#0  /application/libraries/Zend/Form/Element.php(245): Zend_Form_Element->setName('')
		#1  /application/libraries/Zend/Form.php(1125): Zend_Form_Element->__construct('', Array)
		#2  /application/libraries/Engine/Form.php(231): Zend_Form->createElement('Text', '', Array)
		#3  /application/libraries/Zend/Form.php(1035): Engine_Form->createElement('Text', '', Array)
		#4  /application/libraries/Engine/Form.php(218): Zend_Form->addElement('Text', '', Array)
		#5  /application/libraries/Engine/Form/Email.php(41): Engine_Form->addElement('Text', '', Array)
		#6  /application/modules/User/Form/Signup/Account.php(64): Engine_Form_Email->addEmailElement(Array)
		#7  /application/libraries/Zend/Form.php(240): User_Form_Signup_Account->init()
		#8  /application/libraries/Engine/Form.php(117): Zend_Form->__construct(NULL)
		#9  /application/modules/Core/Plugin/FormSequence/Abstract.php(71): Engine_Form->__construct()
		#10  /application/modules/Core/Plugin/FormSequence/Abstract.php(162): Core_Plugin_FormSequence_Abstract->getForm()
		#11  /application/modules/Core/Controller/Action/Helper/FormSequence.php(145): Core_Plugin_FormSequence_Abstract->onSubmit(Object(Zend_Controller_Request_Http))
		#12  /application/modules/Core/Controller/Action/Helper/FormSequence.php(43): Core_Controller_Action_Helper_FormSequence->doSubmit()
		#13 [internal function]: Core_Controller_Action_Helper_FormSequence->direct()
		#14  /application/libraries/Zend/Controller/Action/HelperBroker.php(328): call_user_func_array(Array, Array)
		#15  /application/modules/User/controllers/SignupController.php(50): Zend_Controller_Action_HelperBroker->__call('formSequence', Array)
		#16  /application/modules/User/controllers/SignupController.php(50): Zend_Controller_Action_HelperBroker->formSequence()
		#17  /application/libraries/Zend/Controller/Action.php(516): User_SignupController->indexAction()
		#18  /application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('indexAction')
		#19  /application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
		#20  /application/modules/Core/Bootstrap.php(80): Zend_Controller_Front->dispatch()
		#21  /application/libraries/Engine/Application.php(160): Core_Bootstrap->run()
		#22  /application/index.php(205): Engine_Application->run()
		#23  /index.php(25): include(' /app...')
		#24 {main}

I've investigated a bit and the issue might be with the email field name attribution ; see # 5 in error information above where it looks like the second argument (email field name) is empty altough it seems that the random name (when anti-spamm option is enabled) is generated properly. 

Any idea on what to do to be able to use the anti-spam option without issue ? 

Thanks

**Comment by shivani2910** [comment]
Hi @huseyin-cakmak, 

This is not a known issue in our core module. It seems that you're using a 3rd party signup widget on your Landing Page.

To verify this, please enable anti-spamming technique in signup form and then open URL http://yourdomain.com/signup and then check doing signup from this url and if everything works fine then there must be some issue with the 3rd party login / signup widget that you're having placed on your landing page because of which signup is not being done successfully when initiated from Landing Page and for this you'll need to contact the respective developer.

If you still have any further queries, please feel free to contact our support team.

Best Regards,
Shivani

**Comment by huseyin-cakmak** [comment]
Hi @shivani2910,

Thank you for your reply.
I tought the issue might be as you suggest. However, I did the tests on the http://yourdomain.com/signup page and the issue still remains. This happens right after upgrading from 4.8.6 to 4.8.7.

Thanks

**Comment by shivani2910** [comment]
Hi @huseyin-cakmak, 

Thanks for your response. We've no done any work regarding Anti-Spamming setting or signup in our last upgrade. So basically, this is not a known issue in our default SocialEngine modules. Please open a support ticket along with the details of your website and steps to reproduce this problem to enable us look into this issue in your SocialEngine installation.

We appreciate your support and cooperation.

Best Regards,
Shivani

**Comment by poeticjustice** [comment]
A member just contacted me, regards to Error Code: 565ddd
Which happened about 5 mins ago, checked error log and its EXACTLY the same Stack trace: 0 to 24 and all same files, but Error Code: 565ddd , strange as its only happened once and no other member experienced it 2 months of being up and running

**Comment by dc1177** [comment]
Is this fixed or not? I have the same issue on 4.9.2p1 !
