### ISSUE TITLE
HTML Text Editor

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#130]
Social engine should have a fully simple based html text editor on hand for cut and paste code to appear exactly as how html renders it whether its a sentence in a paragraph tag or a complicated script, it should be available on hand like the one found in the core widget gallery, but for all posts. Instead of not allowing html by default, social engine should give the option for each plugin to include it or not or as a global text editor setting, give the option to use just an html text editor, the tinymce editor, both or a custom editor script.

**Comment by Anshuse** [comment]
Hello @Elshara ,

Thanks for your feedback but currently, we don't have any such plan to include this feature in SocialEngine.

Best Regards,
Anshu

**Comment by Elshara** [comment]
Another reason to want an alternative. It doesn't exist. This is not
good news since I can assure you blogs with a specific format aren't
able to be designed as such despite a blog styler, the global editor
needs an update it is way overdue.
