### ISSUE TITLE
Auto-mapping of users based on SE language for multilingual sites

### ISSUE THREAD

**Issue by meetgerry** [SocialEngine/phpv4-issues#131]
If a SE site has multiple language, then the LANGUAGE dropdown field is not shown here to auto map the users to respective network.

Logically, a network is primarily based on language of users.

![2015-07-567](https://cloud.githubusercontent.com/assets/8540750/8446331/79b7c858-1fb1-11e5-807c-9f33eba884d8.png)

**Comment by Anshuse** [comment]
Hi @meetgerry ,

Thanks for bringing this issue to our notice.

We have reported this issue in our internal bug tracker for our development team to work on this in near future.

Best Regards,
Anshu

**Comment by meetgerry** [comment]
Thanks Anshu, you guys are great!

**Comment by DonnaScriptTechs** [comment]
Just a note. Not all use Networks for regions. I use Networks for genres for books for my authors. As such, languages won't apply. We should have a checkbox for admin to choose to map to languages for this to avoid issues for those that use Networks creatively.

**Comment by gsf00001** [comment]
@DonnaScriptTechs That is correct.  My plan is to use Networks for something other than regions in the world, so a checkbox would be better.  Part of using any script is always remembering what other uses there could possibly be and the ramifications of a new feature (or how it functions).  Thanks for noticing this particular tix.

**Comment by Elshara** [comment]
I also agree. I'd like to use networks to be used as categories for
different types of jobs or businesses people are into.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#5

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
