### ISSUE TITLE
Delete a photo from group DELETE all attachments from engine4_activity_attachments

### ISSUE THREAD

**Issue by happycoder1337** [SocialEngine/phpv4-issues#132]
When you have a group and uploads say 20 photos, these 20 photos get INSERT ed into engine4_activity_attachments table, but when you delete one of the photo, all 20 attachments get DELETE ed from engine4_activity_attachments table. 
Now, not that those images needed to be attached as attachments in the first place. 
I don't think this is a big concern, but its nice to not query the database for useless information. 

FRESH -install SE.4.8.9

**Comment by meetgerry** [comment]
Its not only with the case of images. SE should have options when you disable a module, uninstall a module while it removes all traces of any element which is currently not in use.

Take my word, if this is in place there is nothing better than SE in the market and word of mouth will boost your business big time.

The above reason adds on to why SE always performs slow.

**Comment by Anshuse** [comment]
Hello @happycoder1337 ,

Thanks for reaching out.

We have noted down this issue at our end and our development will look into it and will take appropriate action.

Best Regards,
Anshu

**Comment by happycoder1337** [comment]
Yes gerry, it bothers me as I'm extremely neat when it comes to databases, one fault i can write a code to clean it up, two ok, three sure, but but when it gets overwhelming, I rather wait for developers to re-group their thinking about keeping large amount of data, especially for years to come. As of this point I don't know if i should start my site, because I know years later, I will have a database that looks like "cheese " with incremented data missing here and there because I have to delete those useless queries to compensate for storage.

**Comment by happycoder1337** [comment]
why cant the activity just fetch photos from that group album, instead of fetching the separately attached sql table? 
maybe i'm missing something...

**Comment by DonnaScriptTechs** [comment]
This is fixed for 4.9.0 when it is released. If you still have this issue after we release, please open a new bug report.

**Comment by Elshara** [comment]
Awesome!
