### ISSUE TITLE
Uploading photos to album attaches part of all photos to engine4_activity_attachments

### ISSUE THREAD

**Issue by happycoder1337** [SocialEngine/phpv4-issues#133]
When I upload 10 photos to an album only 8 of those photos gets attached to engine4_activity_attachments TABLE.
Again, not those photos needed to be attachments in the first place, 
would be nice if SE can remove attachment for unnecessary files.

**Comment by happycoder1337** [comment]
I see this is to list 8 photos on activity feed, why is it necessary to have a separate table of attachment? why cant it just fetch the album uploaded and limit the number to 8 to show? Maybe i'm missing something.

**Comment by Anshuse** [comment]
Hi @happycoder1337 ,

Thanks for reaching out.

This issue is already reported in our to-do list and we'll resolve this in near future upgrade.

Best Regards,
Anshu

**Comment by DonnaScriptTechs** [comment]
This is fixed for 4.9 when it is released.

**Comment by Elshara** [comment]
Awesome.
