### ISSUE TITLE
How come socialengine.com blogs gets nested comments but not social engine it self?

### ISSUE THREAD

**Issue by happycoder1337** [SocialEngine/phpv4-issues#134]
This is unfair...

**Comment by Vaibhavagarwal0807** [comment]
@happycoder1337 : This is because on the socialengine.com blogs SocialEngine is using Disqus Comments. If you want you can also use this free service from here: https://disqus.com/ .

**Comment by seaddons** [comment]
Hi @happycoder1337 ,

We have a plugin ["Advanced Comments Plugin - Nested Comments, Replies, Voting & Attachments"] (http://www.socialengineaddons.com/socialengine-advanced-comments-plugin-nested-comments-replies-voting-attachments) that will fulfill your requirements.

It has multiple features like **replying to comments**, **nested / threaded comments**, voting for comments, photo & link attachments in comments, tagging friends & content in comments, filtering comments, etc. I'm sure that you'll like it. Let us know if you've any queries.

Best Regards

**Comment by happycoder1337** [comment]
thanks, its nice seeing all you guys are checking for bug reports =).

**Comment by jim55** [comment]
Greetings @happycoder1337 give a try to 

http://www.socialengine.com/customize/se4/mod-page?mod_id=1411
http://www.socialengine.com/customize/se4/mod-page?mod_id=1440

plugins as well.

**Comment by meetgerry** [comment]
You may choose modules from SocialEngineAddons, Webhive or HireExperts. Their support is awesome.

Do not ever think of buying any modules from YouNetCo, they have plenty of good looking modules, but they have plenty of bugs and they give a damn to you when asking for help.
