### ISSUE TITLE
reCAPTCHA V2

### ISSUE THREAD

**Issue by alx2bgx** [SocialEngine/phpv4-issues#135]
Google launched in dec 2014 the new reCAPTCHA V2. 

Is there a way to use it for new members instead of the old one with letters and numbers ??? 
https://developers.google.com/recaptcha/intro

Thanks ! 

Alex

**Comment by shivani2910** [comment]
Hi Alex, Thanks for your feedback. We're glad to tell you that we've already added this to our features list for upcoming versions. You can follow up on this here: https://github.com/SocialEngine/phpv4-issues/issues/49
