### ISSUE TITLE
Comment Post Length

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#138]
It seems in social engine there's a problem with a comment post length. There is an existing post length it should be removed. People can only post up to about 1000 characters in comments and updates. HTML doesn't show in such places even after adding in the tags.

**Comment by shivani2910** [comment]
@Elshara we use a ```viewmore()``` function to display content (like comments, posts, etc) with more/less links in case of long text. You can modify the maximum length being set in this function by editing the value of ```$_maxLength``` in this file ```/application/libraries/Engine/View/Helper/ViewMore.php```.

**Comment by Elshara** [comment]
Can I change these to whatever or is there a dependency I must be
aware of? This is excellent!

**Comment by shivani2910** [comment]
@Elshara you can change it to whatever suits you. There is no dependency as such.

**Comment by Elshara** [comment]
I just did. It fixed a little issue I was having where comments would
fully show beyond 1k characters. Now it does, I changed every number
in there to 1000000 and it's awesome! Thanks for the tip!
