### ISSUE TITLE
User Photo Dimension

### ISSUE THREAD

**Issue by meetgerry** [SocialEngine/phpv4-issues#139]
<h4>REFER ISSUE:<font color="#3366FF"> DELETING USER PHOTO THUMBNAIL ERROR #118</font></h4>

I would like to point out something which every other SN sites on the Earth follow and which SE is behind.

During signup or profile edit, when uploading photos it only prompts you for thumbnail to be trimmed and applies a neat square photos only to thumbnails. Its highly recommended that the main photo or all PROFILE PHOTOS which gets added during signup or during profile photo edit should by default get trimmed and stored as square.

The simple reason being, users could use any dimension photo and if they are not trimmed and stored with equal dimension, SE site loses its uniform layout.

I know this can be achieved  by custom modification, but this is a core feature which needs to be incorporated to SE by default.

![2015-07-593](https://cloud.githubusercontent.com/assets/8540750/8508307/eabdd8d4-2273-11e5-9ba1-c9ecc3918d59.png)

Refer profile view screenshot below on your demo site:

![2015-07-594](https://cloud.githubusercontent.com/assets/8540750/8508311/0d616068-2274-11e5-8e06-a22760af24a1.png)

**Comment by meetgerry** [comment]
Its been 10 days, I have not heard any response to this issue.

**Comment by smazurov** [comment]
We have not had time to consider this, but we will certainly be looking closer at thumbnail/profile picture issues in 4.9.0. 

Also, reporting such issues to us is done on a voluntary basis and we make no assertions of fixing or even responding (although we try to!). We greatly appreciate the work that you and others have been putting in on these boards as I know you guys have fantastic intentions and I want to thank you for continuing to do it. We listen to all feedback, even if we can't always respond. 

If you need immediate assistance with this issue, please contact one of our 3rd party developers and they would be able to implement this for you.

**Comment by meetgerry** [comment]
I would certainly contact third party developers wherever required. Since this is a problem with the core, I am writing to you here. The screenshot above is shown from your demo site and that's the problem. Since you guys are already working on the responsive template, I am sure the profile images used across the sites could be fixed simultaneously.

**Comment by meetgerry** [comment]
I have not heard anyone seeing this as important inspite of showing screenshots about the screwup right in your demo site.

**Comment by nizhnyk** [comment]
I would also like to see profile pictures improved. Admins should have more control over the size of the thumbnail and the profile picture on user page. Also would be nice to be able to crop a picture for profile page same way as it is done for thumbnails. When clicking on profile picture from user page should open it from albums, hovering on the profile picture should bring the menu to edit or delete picture.

**Comment by poeticjustice** [comment]
This is one issue I really dislike on SE, some added a super long profile pic and it looks soooo bad

**Comment by DonnaScriptTechs** [comment]
This is improved for 4.9.2 when it is released.

**Comment by poeticjustice** [comment]
Is there a way to control the aspect ratio of the trimmer, so its locked... ie 1x1 for square
but if you deal in photo sizes of 8x10.... is there a way to log the crop tool
