### ISSUE TITLE
Integration with iframely

### ISSUE THREAD

**Issue by shivani2910** [SocialEngine/phpv4-issues#141]
Currently, content shared from external websites like Twitter, YouTube, Flickr, etc. doesn't display with an appealing UI in SocialEngine. We want to implement integration with https://iframely.com/. This allows you to host its API on your server and enables your users to share and **embed rich content from over 1700 domains** on your site. You'll also be able to choose between hosting it on SocialEngine (for free),on iframely (and pay them directly), or on your own server using the open source version.

**Comment by DonnaScriptTechs** [comment]
This is implemented for 4.9.0 when it is released.

**Comment by Elshara** [comment]
Awesome!
