### ISSUE TITLE
Uploading Multiple Photos

### ISSUE THREAD

**Issue by shivani2910** [SocialEngine/phpv4-issues#142]
Currently, users can only select and upload one image at a time via the Activity Feed's Post Something section. We want to allow the upload of multiple images via the news feed to promote more content sharing and activity on websites.

**Comment by meetgerry** [comment]
Once again, you guys are awesome.

**Comment by keshavmd** [comment]
It's much required feature, so here are some more suggestions for the same, 
Please refer to google+ activity feed and photo upload feature, it is fast and unique.:

-Option to drag photo from computer in an html area to upload (refer google+)
- Allow multiple uploads at a time.
- Option to remove/delete one or more photo from multiple uploads while upload.
- Option to add title to each photo separately while upload
- option to add photos to a new album or existing album while uploading
Addons:
- Option to add location to images while upload.
- Option to Tag friends in photo while upload. 

![google plus photo upload process](https://cloud.githubusercontent.com/assets/13297013/8637788/28357660-28c1-11e5-9182-c2efec2aa0e3.png)
![google plus photo upload detailed process without any markation](https://cloud.githubusercontent.com/assets/13297013/8637789/283ea0e6-28c1-11e5-86c1-70f7990d564c.png)
![google plus photo upload simple process without any markation](https://cloud.githubusercontent.com/assets/13297013/8637790/28436fc2-28c1-11e5-8117-ac53229b75ab.png)
![google plus wall status update](https://cloud.githubusercontent.com/assets/13297013/8637791/28480b22-28c1-11e5-8cd2-e6248b4d3247.png)

**Comment by keshavmd** [comment]
one more request please fix the maximum image, audio, video file limit
If possible allow this feature to be edited by SE site admin to avoid miss use, and keep server and site healthy.
Also can you provide a separate feature of allowing the Photo/Image, Audio and Visual/Video Files to be uploaded on another server/ cloud or Amazon so to offload the load from server and keeping the site fast, saving bandwidth.

**Comment by smazurov** [comment]
I might be wrong on this, be we do not impose any upload limits, its controlled directly by your php settings. The way php handles it, there is no way for us to implement the feature in the admin.

**Comment by keshavmd** [comment]
So what I am able to understand it we cannot control the upload and storage of image/audio/video files.
And SE PHP cannot impose any such feature in future builds as well.

**Comment by smazurov** [comment]
No, what I am saying is that socialengine does not impose any upload limits of it own, its entirely controlled by php. You can most certainly control the limit, as you, as an admin of a PHP community, have access to change your php settings.

But yes, there is no good way for us to impose that limit that does not have drawbacks which cannot be worked around.

**Comment by keshavmd** [comment]
hmm that's fine, one last querry, can we transfer images/audio/video files being uploaded by the user, to be transferred to a separate server like cloud or amazon server. 
Just to speed up main site and to call the files from different server whenver required, saving resources and speed optimization

**Comment by shivani2910** [comment]
@keshavmd: You can certainly do that. If you want to utilize a cloud service to store all your member's files such as photos, videos, etc for safer and/or faster page seeking, you can use our Storage System feature provided at Admin > Settings section. For more details on how to do that, you can check below KB articles:
http://support.socialengine.com/php/customer/portal/articles/1662398?b_id=4311
http://support.socialengine.com/php/customer/portal/articles/1636682?b_id=4311

**Comment by DonnaScriptTechs** [comment]
This is implemented for 4.9.0 when it is released.

**Comment by Elshara** [comment]
Awesome!
