### ISSUE TITLE
Feeds ordering based on popularity

### ISSUE THREAD

**Issue by shivani2910** [SocialEngine/phpv4-issues#144]
Currently, activity feeds are displayed on the wall in the order of their creation date (from newest to oldest). This makes it hard for users to view popular feeds. We want to provide the option to view feeds so that **posts that receive new comments or likes are moved to the top**. The admin will be able to enable/disable this option.

**Comment by DonnaScriptTechs** [comment]
This is implemented in 4.9.0 when it is released but is changed to add an item for comments or links via a setting that admin controls.

**Comment by Elshara** [comment]
Awesome!
