### ISSUE TITLE
New Activity Feed Items for likes on content

### ISSUE THREAD

**Issue by shivani2910** [SocialEngine/phpv4-issues#146]
Currently, new "likes" on content do not show up in the activity feed. We want people to be notified in the activity feed whenever a user likes something. This way, posts and content will get more popularity and gain visibility for people who didn't notice them before.

**Comment by DonnaScriptTechs** [comment]
This is implemented for 4.9.0 when it is released.

**Comment by Elshara** [comment]
Awesome!
