### ISSUE TITLE
Improve the way description meta tag of Member profile Page is being set

### ISSUE THREAD

**Issue by shivani2910** [SocialEngine/phpv4-issues#147]
We want to use the content entered in a user's “About Us” profile field as the description meta tag for the Member Profile Page (like how “First name” gets displayed in Title tag). This will make Member Profile Pages in SE more search engine optimized.

**Comment by DonnaScriptTechs** [comment]
This cannot be achieved at this time.

**Comment by Elshara** [comment]
Radcodes achieved this functionality years ago. They're the only
developer who has, but it's definitely possible. It's been done on my
site. It's even possible to pipe RSS feed functionality dynamically to
such fields.
