### ISSUE TITLE
Improve the order of meta title and description tags on all the pages

### ISSUE THREAD

**Issue by shivani2910** [SocialEngine/phpv4-issues#148]
We want to use the content entered in a user's “About Us” profile field as the description meta tag for the Member Profile Page (like how “First name” gets displayed in Title tag). This will make Member Profile Pages in SE more search engine optimized.

**Comment by DonnaScriptTechs** [comment]
This is implemented for 4.9.0 when it is released.

**Comment by Elshara** [comment]
Awesome!
