### ISSUE TITLE
SEO friendly content URLs with Slugs

### ISSUE THREAD

**Issue by shivani2910** [SocialEngine/phpv4-issues#149]
Currently, the URLs of content created in many SocialEngine modules (like Albums, Groups, Events, etc) are not SEO friendly and just have an ID pointing to the content. We want to change this so that the content in all modules have URLs with slugs at the end. (like this: http://example.com/groups/1/test-group instead of http://example.com/group/1/ )

**Comment by meetgerry** [comment]
Thanks Shivani, while doing this please make sure it works with the Non-English characters as shown in the attachment. The screenshot is a reference from on of the modules by SEAO.

![2015-07-645](https://cloud.githubusercontent.com/assets/8540750/8598117/c75b98ee-2661-11e5-991d-fe24e5dc5d0d.png)

**Comment by shivani2910** [comment]
Yes, @meetgerry we'll make sure it works well on multi-lingual websites. Thanks for the feedback.

**Comment by meetgerry** [comment]
Thanks

**Comment by DonnaScriptTechs** [comment]
This is implemented for 4.9.0 when it is released.

**Comment by Elshara** [comment]
Awesome!
