### ISSUE TITLE
Brand New Responsive Theme

### ISSUE THREAD

**Issue by shivani2910** [SocialEngine/phpv4-issues#150]
We want to create a new default responsive theme so that your users can easily browse content in an optimal viewing experience across **multiple devices with varied screen sizes**. This will be the default theme when you’ve installed a fresh copy of SocialEngine. It will be compatible with all core modules and will ensure an excellent browsing experience for everyone. Admins will also be able to **customize the theme’s color** to provide for individuality and creativity.

**Comment by DonnaScriptTechs** [comment]
This is implemented for 4.9.0 when it is released.

**Comment by Elshara** [comment]
Awesome!
