### ISSUE TITLE
More robust License system

### ISSUE THREAD

**Issue by shivani2910** [SocialEngine/phpv4-issues#151]
We want to improve the current license system and make it more robust, ensuring that our product as well as third party developers' work is protected. It will also encourage more developers get involved with the SocialEngine platform with the full confidence that their work is protected and valued.

**Comment by happycoder1337** [comment]
Why dont you guys fix the XSS Injections on Social Engine first!
Right now, I can sit here and inject things into my site, idk if I should laugh or cry...

**Comment by shivani2910** [comment]
Hi @happycoder1337, There are 2 XSS vulnerabilities related issues reported so far that we've already taken into consideration: https://github.com/SocialEngine/phpv4-issues/issues/57 and https://github.com/SocialEngine/phpv4-issues/issues/56
If you feel there are more then please feel free to report them along with the details and we'll accordingly look into them. Thanks.

**Comment by DonnaScriptTechs** [comment]
This is being improved. As it's a license issue, I'll close this as we have the issue open internally.

**Comment by Elshara** [comment]
Awesome!
A suggestion to consider. Cloud licensing.

**Comment by gsf00001** [comment]
(is this Issue related to #327, i.e. should they be merged or are they completely different?)

**Comment by Elshara** [comment]
Maybe.
