### ISSUE TITLE
Integrate Marketplace with Package Manager

### ISSUE THREAD

**Issue by shivani2910** [SocialEngine/phpv4-issues#152]
We want to make installing and managing third party plugins less complex. We will do this by integrating the package manager with the marketplace (which is under development currently). Then you can browse, install and upgrade third party modules via the package manager.

**Comment by meetgerry** [comment]
Would this have an option to uninstall and remove old traces of files that were uploaded and drop contents from SQL?

**Comment by smazurov** [comment]
Uninstalling is a bit more difficult, but we do have some planned improvements to disabling.  Once we get disabling fully cleaned up we'll take a look at uninstalling.

**Comment by happycoder1337** [comment]
yay, you guys should make the system more like joomla, but with socialengine's taste

**Comment by gustavo40** [comment]
hello when he leaves this super SocialEngine 4.9

**Comment by DonnaScriptTechs** [comment]
We are improving this process. As this is more a marketplace improvement and internal improvements, we'll close this and keep the internal issue open.

**Comment by Elshara** [comment]
Awesome!
Word Press has integration done like this through Automatic. I figured
something similar could be set up via a cloud api for se.
