### ISSUE TITLE
Disable YouTube and Vimeo Upload Options

### ISSUE THREAD

**Issue by shivani2910** [SocialEngine/phpv4-issues#155]
Currently, there is no option to disable YouTube/Vimeo upload options in the Videos plugin. We want to provide this option in the admin panel.

**Comment by pulsatemedia** [comment]
If possible, please add the ability to post facebook embeds.
Also I feel the order of the form used to submit videos is odd. Video URL should be before details and  additionally, it would be beneficial to pull-in the metadata of the video form the source (Title, details etc)

Lastly, is it truly necessary to have to our community manually select the source of the video when its a website like vimeo or youtube? The source, if it its from the web is implied by the URL and seems strange to ask the user if the video is from youtube or vimeo.

For manual upload I can understand

**Comment by Elshara** [comment]
:)
