### ISSUE TITLE
Make video thumbnail available for selection when a video profile page url is shared

### ISSUE THREAD

**Issue by shivani2910** [SocialEngine/phpv4-issues#156]
Currently, when a video's profile page link is shared in the news feed on SE or external websites (like Facebook), thumbnail images from other videos appear in the preview instead of thumbnails from the original video. We want to make the main video's thumbnail available as a selection. The user can then choose their desired thumbnail using the arrow keys before sharing the link.

**Comment by BikersPost** [comment]
Will this apply to YouTube & Vimeo videos? or just uploaded videos?

**Comment by Voxitt** [comment]
Hi, just checking if work on this functionality has been completed. Will users be able to post links to videos irrespective of whether they are Youtube or Vimeo and have the thumbnail to the video in the preview. 

Please kindly let me know.

**Comment by Elshara** [comment]
:)
