### ISSUE TITLE
Sort Plug­ins alphabetically

### ISSUE THREAD

**Issue by shivani2910** [SocialEngine/phpv4-issues#157]
Currently, plugins are not sorted. We want to make the plugin menu in the admin section alphabetical to help you find your plugin quickly and easily.

**Comment by carlomagno83** [comment]
Datatables is great:

https://www.datatables.net/

**Comment by smazurov** [comment]
this is for the dropdown menu, primarily, so datatables is a bit overkill.

**Comment by DonnaScriptTechs** [comment]
This is implemented for 4.9.0 when it is released.

**Comment by gsf00001** [comment]
@DonnaScriptTechs Will there be a requirement for 3rd-Party Devs to include their company name (or abbreviation) at the beginning of the Plugin Name?  Some Devs do this, other's don't.  One that I'm aware of does it for some of their Plugins but not others.

**Comment by Elshara** [comment]
Awesome!
I think it should be a strict requirement for developers to add
required information se can monitor from afar to ensure real plugins
once installed aren't malicious.
