### ISSUE TITLE
Ability to change position of Updates and search bar in mini menu

### ISSUE THREAD

**Issue by shivani2910** [SocialEngine/phpv4-issues#159]
Currently, the Mini Navigation Menu editor does not have an updates link or search bar, so admins cannot change the position of those elements in the mini menu. We're planning to add these to the Menu editor so that you can customize them in the Mini Navigation Menu.

**Comment by DonnaScriptTechs** [comment]
This is implemented for 4.9.0 when it is released.

**Comment by Elshara** [comment]
Awesome!
