### ISSUE TITLE
Potential bug with SE version 4.8.7. that is not displaying saved description in layout page.

### ISSUE THREAD

**Issue by simon01100001** [SocialEngine/phpv4-issues#16]
I have an issue with SE not displaying the sites Description and Keywords when searched by search engines

![capture-error](https://cloud.githubusercontent.com/assets/11245255/6426432/7027c6d6-bf52-11e4-8032-533047883a13.JPG)

**Comment by simon01100001** [comment]
To elaborate. If you edit the page Description and Keywords and hit save the details are not saving hence no Description or Keywords. Not good for my SEO. 

![capture-edit](https://cloud.githubusercontent.com/assets/11245255/6431803/4bdeeab0-c034-11e4-8067-095811c2c079.JPG)

**Comment by shivani2910** [comment]
Hi @simon01100001, 

Thanks for reaching out!

After you save changes in "Edit Page Info" pop-up, please make sure that you also click "Save Changes" at the top of the page in Layout Editor as otherwise changes will not be saved for the particular page.

So, please check doing this again at your end and hope you'll not face this issue again.

Best Regards,
Shivani

**Comment by simon01100001** [comment]
Hi Shivani,

Thanks for your help here.

I have tried this many times with many pages still not working. Also same issue for the Site Description and Site Keywords in admin General Settings section.

I have had my host check and confirm issue and they have indicated also as a potential SE bug.

Thanks

**Comment by shivani2910** [comment]
Hi @simon01100001, 

This is not a known issue in our core module and we're unable to reproduce this. To enable us look deeper into this problem specifically on your website, please open a support ticket along with the details of your website and our support team will help you further.

We appreciate your support and cooperation.

Best Regards,
Shivani
