### ISSUE TITLE
New widget: Column width modifier

### ISSUE THREAD

**Issue by shivani2910** [SocialEngine/phpv4-issues#160]
If you use the Layout Editor to put a new widget on a page, it sometimes results in a poor UI because there's insufficient column width to accommodate the new content. We plan to resolve this by **allowing you to modify a particular column's width** individually on any page.

**Comment by sergeng** [comment]
<div class="generic_layout_container layout_top">
<div class="generic_layout_container layout_middle">
<div class="generic_layout_container layout_bottom">

will this be accomodate this layout?
BOTH Top & Bottom Full-Width Block on the SAME Page!
This should be core.

**Comment by BikersPost** [comment]
This is already available in SocialEngineAddOns Core Plugin (Free)

**Comment by DonnaScriptTechs** [comment]
This is implemented for 4.9.0 when it is released.

**Comment by Elshara** [comment]
Awesome!
