### ISSUE TITLE
Ability to set different titles of multiple HTML Blocks placed on a page

### ISSUE THREAD

**Issue by shivani2910** [SocialEngine/phpv4-issues#161]
If you use the Layout editor to place multiple HTML blocks on the same page, and they have the same name, it's difficult for the admin to identify which block is which. We want you to be able to set custom titles for HTML blocks so they are easier to identify.

**Comment by DonnaScriptTechs** [comment]
This is implemented for 4.9.0 when it is released.

**Comment by Elshara** [comment]
Awesome!
