### ISSUE TITLE
New widget: Social Sharing buttons

### ISSUE THREAD

**Issue by shivani2910** [SocialEngine/phpv4-issues#162]
Social sharing is a key element for socialization of any project. We’re planning to add a new widget called “Social Share Buttons” wherein your users can share content to other popular websites through attractive buttons.

**Comment by meetgerry** [comment]
Is this like having AddThis code added to every activity Item?

**Comment by meetgerry** [comment]
Is this like having AddThis code added to every activity Item?

Someone please confirm!

**Comment by meetgerry** [comment]
Its a pity nobody has the courtesy to reply here...

**Comment by shivani2910** [comment]
@meetgerry We're sorry for the delay in responding to you. Regarding your query: Yes, we're planning to add a widget with default AddThis code that you'll be able to place on content's profile page via Layout Editor to display share options on front end.

**Comment by meetgerry** [comment]
Shivani, I do not understood why should we have it as a widget. There are already many third parties who are already providing this is a compliment widget along with their modules.

What was stressed in previous references and here is that AddThis social sharing or any sharing codes should be added to every activity item. See screenshot below.
![screensocialsharing](https://cloud.githubusercontent.com/assets/8540750/9126278/2a8117b0-3cb4-11e5-8243-536777ff758d.png)

**Comment by meetgerry** [comment]
Hello Shivani, could you please confirm if we are on the same page?

**Comment by meetgerry** [comment]
So slow and careless!

**Comment by shivani2910** [comment]
Hi @meetgerry,

I'm so sorry about the delay in responding back to you here. I've already incorporated your suggestion for discussion with team but somehow missed responding back to you here. 

As I said, it's a good suggestion, I'll discuss this with team for possibilities when we'll be working on sharing feature and accordingly update you.

Thanks & Regards,
Shivani

**Comment by meetgerry** [comment]
Thanks

**Comment by troydbertrand** [comment]
I would love to see social sharing buttons included as standard in SocialEngine PHP but more importantly I'd like to see the integration of Open Graph Protocol. I'm not sure if this is being considered but it should. Excluding the Open Graph Protocol from the social share buttons integration process will be a huge mistake. 

Please confirm whether or not this is part of the plan.

Best Regards
TDB
[Ex Creators](http://excreators.com/community/)

**Comment by Elshara** [comment]
:)
