### ISSUE TITLE
Improvements in Pagination

### ISSUE THREAD

**Issue by shivani2910** [SocialEngine/phpv4-issues#164]
Currently, up to ten page numbers are displayed in the pagination bar. If there are more than ten pages, there is no way to jump directly to the first or last page. We want to improve the current pagination system, **enabling users to directly access the first and last pages**.

**Comment by keshavmd** [comment]
@shivani2910 What is the tentative date for SEPHP 4.9 release, please at least disclose the month.
It has already been more than a month since the announcement.

**Comment by smazurov** [comment]
4.9.0 is still a few months away. We have to release our new website first :)

**Comment by keshavmd** [comment]
Few Months away, I guess it mean around November or so.
It would have been great if just wall feed update would have been released :).

**Comment by meetgerry** [comment]
November is coming to an end.

**Comment by qoutas** [comment]
Great, can't wait for the fix

**Comment by Elshara** [comment]
:)
