### ISSUE TITLE
Animated GIF support

### ISSUE THREAD

**Issue by shivani2910** [SocialEngine/phpv4-issues#165]
Currently, animated .gif images are not supported in SocialEngine PHP. When uploaded by users, our system converts them to non-animated images. We want to implement support for animated .gif images so that they are displayed in their original form.

**Comment by Hidekikun** [comment]
Amazing, this issue has been brought up since 2011, for years the developers said it was on the list, however it looks like its NOW just being noted? Dev crew is full of crap.

**Comment by fire228** [comment]
This needs to happen ASAP!!!
