### ISSUE TITLE
Mentions

### ISSUE THREAD

**Issue by TheGreatAlexander** [SocialEngine/phpv4-issues#167]
There should be a setting to enable mentions and allow users to mention anyone who is part of the social network, rather than only their friends.

**Comment by shivani2910** [comment]
Hi @TheGreatAlexander, please specify exactly that which feature of SocialEngine PHP's core modules are you referring to so that we can get back to you accordingly. Thanks.

**Comment by shivani2910** [comment]
Hi @TheGreatAlexander, we're closing this issue since we didn't get your response.

**Comment by Elshara** [comment]
He wants to be able to tag people in posts.

**Comment by shivani2910** [comment]
@Elshara and @TheGreatAlexander If you're talking about the ability for users to tag their friends in status posts, then we have a plan to implement this feature in future and it's already mentioned in our To-Do list. Thanks.

**Comment by TheGreatAlexander** [comment]
Could you provide a link to your to do list?  The feature I request is the ability of an administrator to set tags so that any user can mention another/tag another one without the requirement of being friends.

**Comment by Elshara** [comment]
Unfortunately it seems the only way to mention anyone whether it be an
invitation, tagging or messaging is through friendship.

**Comment by TheGreatAlexander** [comment]
That is exactly what needs to be enhanced. So it works like Twitter does.  You can mention anyone!

**Comment by Elshara** [comment]
Should be able to do so by display name or username.

**Comment by shivani2910** [comment]
@Elshara and @TheGreatAlexander Currently we do not have any "mentions" related feature where users can mention other users (friends). Can you please clarify which section of SocialEngine core modules are you talking about using screenshots?

**Comment by Elshara** [comment]
Tagging people. It isn't possible to do this in posts.

**Comment by TheGreatAlexander** [comment]
@shivani2910 That is what I am requesting as a feature enhancement.  Mention whoever you want inside the social network... just as you do in Twitter.

**Comment by shivani2910** [comment]
@TheGreatAlexander Ok, I get your point now. Thanks for the clarification. I'll forward your suggestion to our team.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#6

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
