### ISSUE TITLE
Comments As An Activity Feed Item

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#169]
Currently, if a new comment is posted, it will not show up in the activity feed. Comments are essential to what members are doing, therefore comments should appear as their own item in the activity feed. This includes replies to discussions in forum and groups.

**Comment by shivani2910** [comment]
@Elshara We've already provided activity feeds for comments posted on Albums, photos, Blog, etc. These feeds are by default disabled to be displayed in "Main Feed" and only enabled for "Subject's profile feed". You can change the settings and enable these feeds for Main Feed from Admin > Settings > Activity Feed Settings section by choosing the corresponding feed items.
