### ISSUE TITLE
Sticky Categories

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#170]
The original idea of categories is to provide easy functionality for posts that are considered organized based on predefined keywords, such as sports, recreation, science and other topics.
Some sites, in place of categories have what's called an announcements section, or featured area, where good articles get noticed in a form of spotlight material. Ideally, merging such features together would make the web a birth place for new modern categories to be made available in which they show up first, before all others are mentioned. Featured categories, or sticky categories is the answer to such a solution, you can have as many as you want while still having other categories for people to post in. Featured categories could be based on an algorithm such as latest activity, newest posts by date, popular posts and so on, or they could simply be manually attended to as would regular categories with the extra permission of who can post in them.
Ideally, featured topics would revolutionize social engine sites if made available, expanding categories to be available to all content items plus all members and profiles, this would be very useful to attach or change the way profile types appear, so that either in members profile questions or in other search indexing options, categories like keywords could function in a way that would better organize both top and specifically interesting members and their content, if relatively available.

**Comment by shivani2910** [comment]
Hi @Elshara, thanks for your feedback. But we're currently focussing on providing the most necessary things in SocialEngine PHP in the order of their priority. Also, current category system is simple and clean which is good for core plugins. If you want to have more advanced listing based systems for your website, there are multiple 3rd party plugins available that can be used.
