### ISSUE TITLE
Cannot Like Member Profiles

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#171]
Currently , social engine does not allow the ability to like member profiles. Let alone share them. Members should have the ability to do this as they can with all other content items.

**Comment by smazurov** [comment]
Sorry, we won't be doing this one. Perhaps there is a 3rd party plugin that will allow for this functionality.

**Comment by socialengineaddons** [comment]
Hi @Elshara,

We have a **Free plugin** [Likes Plugin and Widgets] (http://www.socialengineaddons.com/socialengine-likes-plugin-and-widgets) that will fulfill your above requirement. Using this plugin, users can like content in multiple **'Content Types'** and **'Member Profiles'**.

**Comment by Elshara** [comment]
I'll look into it, but I'd prefer this be apart of the core functionality.
It's funny. There are things that seem so important that nobody is
going to budge on, and yet the little suggestions at random get
featured in releases even though this one seems like what I figured
would be quite popular. It's one button on a profile page, I mean
really. Ning 2 had this, phpfox has this, facebook has this, why not
social engine? Is it like the outbound rss feeds? No can do approach
even though it would be so helpful to us? Guess content is more
important than who is posting or sharing it.
I take it in the roadmap, social buttons aren't going to appear on
member profiles either? Why not a like button? What about a quick
access menu involving quick actions members can do, I know add as
friend and send message is there, but the ability to jump to a comment
or search their profile might make it on the list, this like button
must have you real stumped. Can't find a coder to write a like button
for profiles.
Thanks social engine add ons, I can see how you're being played into
this here. If social engine officially won't roll out a feature, any
third party developer can keep their status as it being the only
provider to have a feature that may never get shared in official
releases. Even though, feature requests and bug reports are more than
welcome and encouraged, if a third party mod has this available, dev
team can't be bothered with making such a  popular item apart of the
next release.
At least based on my experience, I'm noticing a trend here. Anything
involving member to member communication is either a work around at
best, or perhaps social engine isn't as social as it likes to appear.
That's fine, I just thought member priorities were a little higher on
the list.
I do really appreciate the activity feed updates, likes being one of
the things being added this is excellent news. Plus add in the other
improvements and status feeds are a huge help, they will be very ideal
actually and I love this product and will support it in any and all
directions. All I'm trying to do here is get a little more inbound
features available. Sharing is a huge step forward, I'll be happy with
that and can work without a like button, I'm just you could say
realizing the scope of what is ahead. Maybe in future this can make it
on the list, not a big deal, I just like to have things a little more
core based if I can get things to a place where they are much more
easier and functional from a direct, member to member perspective.
Love the updates keep them coming. I'll check out your plugin social
engine add ons, I could really use you right now.
