### ISSUE TITLE
Browse Members Page

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#173]
Does not currently show members in the order of newest first. It'd be nice to have new and popular view as all other modules support this, accept for a few which don't.

**Comment by shivani2910** [comment]
@Elshara currently, we display results on browse Members page in the decreasing order of their last login date by default (with an intention to give priority to recently active users on website) and if viewer filter results using search form, then we display results in alphabetical order.
If you still want to modify this feature, then you can customize the code under function ```php_executeSearch()``` in file ```/application/modules/User/controllers/IndexController.php```. Thanks.

**Comment by Elshara** [comment]
I will do this. Thanks.
