### ISSUE TITLE
Choose Where Members Status Appears

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#174]
Every time a member is referenced somewhere, the first thing that appears is their status feed. No matter the list, their status feed can get a little long and spammy since some members do not realize html has been stripped from their posts, so it not only appears out of place, but appears in multiple lists automatically, instead of more preferable information or simply a list of straight members. When members are referenced, their lists contain their profile photo and their name, so it shows up twice. This also happens with post title regarding duplicate entries, however more importantly, long status updates in lists cannot be changed or blocked which doesn't encourage the use of modules such as the ones belonging on profiles, the browse members page and other areas to display as they should. A prime example of a good members list, is the members online module for reference compared to all other lists where members appear, including friends, new and popular members and the activity feed itself.

**Comment by keshavmd** [comment]
To work on advanced member search option is what you might be justing.
Refer to younetco - http://socialengine.younetco.com/advanced-members.html

I would like to suggest something like this as a part of SE core.

**Comment by meetgerry** [comment]
This has bugs and its not fixed for months now, do not buy this.

**Comment by keshavmd** [comment]
thanx for the suggestion, but can you address what exact bugs we are talking over here,
Also there is another problem with SE php 3rd party developers, they don't develop there products to work or integrate with plugins of another developer, that is the main reason I am suggesting SE Core to execute this part, as it is much required.

**Comment by meetgerry** [comment]
Basically I bought approx 7 to 8 modules from them and all have problems are not in good use. I do not want to use this channel to discuss any issues that are not related to SE core.

**Comment by Elshara** [comment]
Keshavmd is correct. Core issues is why we bother posting in this
forum and it's why I started this thread, I don't care what third
party has it out for being hero, its the core we pay for as does third
party developers themselves.

**Comment by meetgerry** [comment]
I would suggest SE to have its own modules that can be sold as add-ons and that does similar jobs. At least we would be sure that they are well integrated with SE core and that it all works with all other core modules.

**Comment by smazurov** [comment]
With our new certification program and a certified marketplace we will be bringing up the quality. The certification process will basically be installing the plugin into a vanilla (and fully loaded by 3rd party plugins) SE install and ensure that all documented features are working as expected.  We will also inspect the code base and ensure it is of high quality. 

Our goal is to only sell and showcase 3rd party plugins of highest quality. We want to provide SEPHP customers with security in knowing that purchasing a plugin on socialengine.com will 100% work.

**Comment by smazurov** [comment]
As such issues like this will need to be revisited once we can determine whether or not 3rd party developers can fulfill this feature request with a certified plugin, so I am closing this for now.
