### ISSUE TITLE
Merdge Edit Profile With Account Settings

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#175]
Social engine has always had a separate edit profile menu from account settings. It is becoming more popular to have all user management features under one control panel or menu. Having this process streamlined also helps drive more engagement because members have fewer places to go to in order to manage their content. Quick access is always a good thing to keep in mind, if someone is to learn the layout of a site that is both design and user friendly, in a functional way, especially if the website is a place a member may wish to spend a lot more time on.
One of the most common problems people have, especially on social engine sites, among others, is the ability to update their name. There are times, where people want to quickly edit their name, change their photo, change their password and update their privacy settings. Notifications are also important, having this on easy access preferably on one page as content items, would greatly help improve users navigation when it comes to what they can do with their own profile and account. It is not just about preferences, it is about members knowing where to find things in a comfortable, accessible and secure manner as is their right to privacy and depending on the site, customization of their profile.
Perhaps expanding a global quick access menu may be a solution.

**Comment by shivani2910** [comment]
@Elshara, in SocialEngine PHP, we've provided a Menu Editor at Admin > Layout section using which you can easily customize the multiple menu navigations on your website and add / remove items from them. For ex, if you want Settings and Edit My Profile section to be at the same place, you can easily edit "Member Edit Profile Navigation Menu" at http://example.com/admin/menus?name=user_edit and add a new menu item "Settings" along with its URL and similarly you can customize Settings navigation bar too.

**Comment by Elshara** [comment]
Awesome! This is exactly what I was looking for!
