### ISSUE TITLE
Feed content for PUBLIC level

### ISSUE THREAD

**Issue by meetgerry** [SocialEngine/phpv4-issues#178]
If there is a network created based on SE language for sites that run multiple languages, activity feed does not show for public member level.

Example: A network is chosen based on language. Any visitor who is a public should be able to see all activity feeds based on the language selected (My Friends & Networks is the feed content type being selected in Activity Feed Settings).

Kindly consider fixing this issue. Currently there is no option to create network based on SE languages and display feed contents for public.

![2015-07-652](https://cloud.githubusercontent.com/assets/8540750/8634936/d6b31e8c-2816-11e5-94ef-db5bd2d936e4.png)

**Comment by Anshuse** [comment]
Hi @meetgerry , We haven't provided any option to choose the language while creating a network so, It would be great if you can send us step wise instructions to reproduce this issue at our end. Thanks!

**Comment by Anshuse** [comment]
Hi @meetgerry , We haven't provided any option to map a network with Languages (created from Layout > Language Manager > Language packs) in the Network creation form and if you've created a custom Profile Question with title "Language" then that's just a normal field and can not be mapped with Languages created via Language Manager. The language packs created by site admin are only displayed in the language selection drop-down field in the footer to viewer. So, this custom profile question "Language" and Language packs created on site are not related in any way.
If you're pointing to something else then please explain step wise using screenshots.
Thanks!

**Comment by meetgerry** [comment]
I am surprised how could you even think that Language and Language packs could be related. Its obvious they cant be the same and I do understand custom fields are entirely different.

Firstly, a Network in a social site should server the purpose of forming a community targeting specific interest or people who communicate the same language at least. Currently SE only support networking of people who speak only one language though you have multilingual options.

In order to have network based on language, the list of core languages should be an option to choose while creating a network in MANAGE > NETWORKS > ADD NETWORK. I remember you guys already agreed to work on this in your forthcoming updates.

The actual issue I pointed above is that when a public visitor who choose Russian language as the site interface, should be able to see only Russian feeds and public visitors who choose English as site interface should see only English feeds because a network was created based on core language. This applies when "My Friends & Networks" option is selected.

**Comment by shivani2910** [comment]
Hi @meetgerry, we're sorry for the mis-communication happened above.

Regarding "``` I remember you guys already agreed to work on this in one of the tickets here...```" : 
if you're talking about this issue : https://github.com/SocialEngine/phpv4-issues/issues/131 then yes, we've forwarded this feature to our internal development team for discussion so that they can look into the possibilities of its implementation.

Regarding "```because a network was created based on core language in "Related Profile Question"...```"
Now, since we don't have a Language dropdown field while creating a network, we didn't understand how can one select a language while creating a network. If this issue depends on whether or not we implement above feature, then that's fine. If not, then it would be great if you could send us screenshots to explain your use case better. Thanks.

**Comment by meetgerry** [comment]
Yes, the language dropdown field should be listed in the "Related Profile Question", thats what I meant. If this is there, then we can have the feed content to be displayed based on language selected for public level.

**Comment by shivani2910** [comment]
Ok, we've added it to our list and we'll consider it if we decide to implement above feature. Thanks.
