### ISSUE TITLE
Allowing users to add new network and sub networks

### ISSUE THREAD

**Issue by keshavmd** [SocialEngine/phpv4-issues#179]
During sign up process, while selecting network, users should be allowed to add new network, if it is not there in the list.
Than that network should be put in the halt list to be approved by admin ( to avoid repetition of networks). Once approved should be made public and a separate page for network to be created by default containing the basic info , display picture/icon option for displaying the info of what it is all about.

It should be based on open graph or fast search.
This will ease out the work of admin in creating all the network by themselves.

Other signup feature required:
- Option of others in gender.
- Option of verifying the users. (Get verified) - For creating verified and authenticated user base.

And giving options to site admin for creating more field in user bio like - add your present location and your hometown and last places you have been to or moved from
- option for adding workplace and school / colleges.
All this to be made in detail to avoid repetition and large database.

**Comment by Anshuse** [comment]
Hi @keshavmd ,

1) Regarding "Allowing users to add new network and sub networks":
If users will be allowed to create new networks on their own then system and database will get very complex and will create many complexities on site and, if any network required by user is not available on site then user can contact the site admin to create a new one for him.

2) Regarding "Option of others in gender.":
Site admin can add as many choices as they want in "Gender" field simply by clicking on the "edit choices" link just below the respective profile field from "Admin" > "Settings" > "Profile Questions" section.

3) Regarding "Option of verifying the users. (Get verified) - For creating verified and authenticated...":
You can enable this feature of whether you want your site users to get verified automatically or you should approve them first then after that they should be able to login to site. You can enable this setting from "Admin" > "Settings" > "Signup Process"  and from there, go to "Create account" link from the left side and there you can enable the automatic approval of user from "Auto-approve Members" field.

If you want to enable the email address verification of users before they are able to login to your site then you may enable the "Verify Email Address?" field from  "Admin" > "Settings" > "Signup Process" > "Create Account" section.

4) Regarding "And giving options to site admin for creating more field in user bio like - add your...":
We have provided some basic profile questions that displays under the "Edit My Profile" section. Now, you can create as many "Profile Questions" as you want on your site from "Admin" > "Settings" > "Profile Questions" section based upon your site and your choice about what all information you want your site users to fill out.

5) Regarding "option for adding workplace and school / colleges.":
You can create a new profile question/profile field as mentioned in #4

Best Regards,
Anshu

**Comment by keshavmd** [comment]
Thank you for the brief reply

1) Regarding sub network: If it is going to create complexities, then can you allow a option or simple form where user can submit name and purpose for creating new network, and later admin can review which new network to be created and what all to be avoided.

3) Verifying part: What your are suggesting is right and I am well aware of that, But what I want to convey over here is, it would be better to display verified sign over user profile and in user bio incase it has been verified user, increasing trust among community.

**Comment by Anshuse** [comment]
Hi @keshavmd , 

1) Regarding sub network":
You can place "HTML Block" on the Landing Page of your site from Layout Editor section and in that block, you may provide the link for the 'contact form' following with a message like "If the network you belongs to is not available on site then request here!" or anything. This is just a tip.

2) Regarding "Verifying part":
If "verify Email Address" setting of enabled on site then the only members who have verified their email addresses will be active on site and all other users, who haven't verified their email addresses will be in-active and will not be displayed anywhere on the site except the "Admin" > "Manage" > "Members" section. Therefore, all the active members on site will be verified ones if "verify Email Address" setting is enabled on site and there is no such need to show them as verified on the site.

Best Regards,
Anshu

**Comment by Elshara** [comment]
I'm wondering if networks could be integrated with groups somehow. this would be a huge solution to such problems.
