### ISSUE TITLE
FR: Prevent search engines from indexing the site in maintenance mode

### ISSUE THREAD

**Issue by rwetzlmayr** [SocialEngine/phpv4-issues#18]
I'd propose to repel search engine bots when the site is in maintenance mode.

A common measure to accomplish this is to send a '503 Service unavailable' HTTP code instead of the regular '200 OK':

```
--- a/application/index.php
+++ b/application/index.php
@@ -102,6 +102,8 @@
         setcookie('en4_maint_code', $code, time() + (86400 * 7), '/');
       }
     } else {
+      header('Status: 503 Service Unavailable');
+      header('HTTP/1.1 503 Service Unavailable');
       echo file_get_contents(dirname(__FILE__) . DS . 'maintenance.html');
       exit();
     }
```

**Comment by shivani2910** [comment]
Hi @rwetzlmayr, 

We're sorry for the delay in responding to you. Thanks for the suggestion.
We'll discuss this with our team and accordingly add it to our list to be added in future upgrades.

Best Regards,
Shivani

**Comment by myetter37** [comment]
SocialEngine PHP version 4.8.9 has been released, and this issue has been fixed in that release.
