### ISSUE TITLE
Features for Se core : Imporved Share box / members search / emoticons / comments box.

### ISSUE THREAD

**Issue by keshavmd** [SocialEngine/phpv4-issues#180]
Hello would like to suggest some much required SE core features:
- Share box need to be improved:

refer to images for more detail.

![fb share a post option](https://cloud.githubusercontent.com/assets/13297013/8638046/aa12c3c8-28ca-11e5-805f-3530e36da5f0.png)
![he share box suggestions](https://cloud.githubusercontent.com/assets/13297013/8638047/aa197696-28ca-11e5-8fa5-5bc52c85ef1e.png)
![sharing various forms of post with option to add how u r feeling and what u r doing](https://cloud.githubusercontent.com/assets/13297013/8638048/aa23dd20-28ca-11e5-83e2-949fe8008647.png)
- Members search page:
  Please improve members search option refer to 
  http://socialengine.younetco.com/advanced-members.html
- Please include emoticons and stickers in Social Engine core.
- Improve comment box:
  -Comment box should be displayed by default below the post, it has been noted if you give the option  for comment than more user engagement has been noticed as per study.
  -Give option in admin panel weather to display comment box by default below the posts or weather user need to click on the comment link for the box below.
  -Improve comment box for that refer to google and facebook both:
  That is include option of adding photo and emoticons in comment box, 
  -also to display option of both post comment and cancel button beneath comment box.
- option in admin panel for weather to allow posting comment just by hitting "Enter" button or user need to click on post button for the action to be completed.
  ![box below posts to allow users to comment over](https://cloud.githubusercontent.com/assets/13297013/8638082/4501e9bc-28cc-11e5-8ecf-35b71782d823.png)
- improved UI of activity feeds by displaying icons for like, share delete, comment option with there statics in front instead of just giving text/link option for all of the above.

![improved wall feeds](https://cloud.githubusercontent.com/assets/13297013/8638077/18370444-28cc-11e5-9aa9-3d0a69dc792c.png)

Another refer image:
![tsu co feed wall](https://cloud.githubusercontent.com/assets/13297013/8638094/7228ffac-28cc-11e5-8608-07269f59b9d5.png)

**Comment by shivani2910** [comment]
Hi @keshavmd, we've gone through all the suggestions you've provided and appreciate your intentions. 
We intend to provide our users with the best platform first, allowing 3rd party developers to fill in missing advanced features. So basically our 1st priority is to provide you with a robust and stable SocialEngine PHP core script that works on vast majority of servers and provide good scalability.
Among the features that you've suggested, I feel that except share-box, there are 3rd party plugins available for almost all of these that you may consider using on your website. Thanks.

**Comment by Elshara** [comment]
I also agree with your suggestions and cast my opinions here.
1. Comments should display below the post.
2. Sharing should display above comments.
3. Comments should use full content width and open by default.
4. Share pop up should at least include send to email option.

**Comment by keshavmd** [comment]
HI @shivani2910 Yes I agree that advacned member is already there with 3rd party, but look problem here is one cannot use different 3rd party plugins as they don't develop in such a way that it supports inter 3rd party plugins.

But still few things need to be provided by SEPHP like having emoticons/stickers to be displayed in SEcore itself, as 3rd party developers tell me that it is core team work. 

2) Advanced share is much needed and the way suggested above is the best one, I do hope you might consider it in future development.

3) advanced comment has not been provided by any 3rd party, major problems are:
  - they are ugly in UI part design need to be improved, have shared how we can work over that, by giving icons and stats(Numbers) instead of plain text.
-  Admin should able to define how many comments will be displayed by defualt in case of more than 3 comments, at present all comment get displayed which leads to long new feed leading to user bounce.

4) Improve UI of news feed needs to be done by SEPHP itself as it's main core.

**Comment by Elshara** [comment]
I agree about the icon in comments thing for sure.
Perhaps an alternative would be show a specific number of comments by
default as a new setting in specific module global settings, then
define whether comments should load automatically or better yet,
create a share menu that is used to position the order of what comes
first, comments, likes or sharing.

**Comment by DonnaScriptTechs** [comment]
Please check our 4.9 release once it is available as we've made a lot of improvements. If you still see the same issues that need improvement, please submit them one at a time.

Please note that we can only accept one item per github issue raised as we put revision numbers for each one and cannot do that if multiple items are in one report.

**Comment by Elshara** [comment]
Awesome!
