### ISSUE TITLE
Translation Issue

### ISSUE THREAD

**Issue by Spielmitmir2003** [SocialEngine/phpv4-issues#181]
Goog morning,

I have encountered an issue a few days ago I´m still unable to solve. On the first tab of the¨Edit my profile¨ page,  when members don´t select a day or month, an error message appears saying ¨Birthdays must include a month and a date¨, a phrase that I´m not able to get it translated into Spanish. I have added the phrase on the language manager as well as directly on the custom.csv file but  is still not working. Can you tell me how I can manually get it translated?.
![image](https://cloud.githubusercontent.com/assets/13316106/8652039/0319a4ba-2942-11e5-9e15-849be3183865.png)

Thank you,

Alex

**Comment by smazurov** [comment]
Hi, we have a catch-all issue tracking such problems here: #5.  We have added yours to the list.  Thank you for reporting this problem.
