### ISSUE TITLE
SE automatic upgrade

### ISSUE THREAD

**Issue by Hostiso** [SocialEngine/phpv4-issues#182]
We would recommend to consider developing option for automatic SE upgrade, maybe something similar like with WP ... even some developers like Hire-Experts offer this for their plugins.

For example, you can add notification that there is new SE version or SE plugin upgrade, and client can then choose to automatically upgrade or manually (by downloading package from your site)

It would be easier and faster for clients to have this option.

**Comment by Anshuse** [comment]
Hi @Hostiso ,

In the Roadmap of SE 4.8.9 http://blog.socialengine.com/2015/07/09/introducing-the-se-php-4-9-0-roadmap/ , we've mentioned the improvement of "Licensing and Marketplace" and this feature of automatic upgrade will covered there.

Best Regards,
Anshu

**Comment by smazurov** [comment]
see #152

**Comment by Elshara** [comment]
Awesome feature for a roadmap of any kind!
