### ISSUE TITLE
Invitation emails: Sign up link goes to Sign in Required Page

### ISSUE THREAD

**Issue by personian** [SocialEngine/phpv4-issues#183]
For some reason, the embedded link in the invite email takes the user to the Sign In Required page instead of the Sign Up Page. Nothing has changed since it worked very recently except applying all of the most recent upgrades.

Currently have all upgrades installed as published from SE.

**Comment by Anshuse** [comment]
Hi @personian ,

We're not able to reproduce this issue at our end and as this issue exists specifically in your installation  so, we suggest you to open a support ticket along with your site details and our support staff will be happy to help you out.

Best Regards,
Anshu
