### ISSUE TITLE
Membership Plan Bug

### ISSUE THREAD

**Issue by meetgerry** [SocialEngine/phpv4-issues#184]
The new plan created is not displayed in user settings page. See screenshot below for Admin side and Frontend side:

Admin Plan Settings
![2015-07-714](https://cloud.githubusercontent.com/assets/8540750/8698370/34b6f71e-2b06-11e5-931a-983f807f6f5e.png)

Users Subscription Settings
![2015-07-715](https://cloud.githubusercontent.com/assets/8540750/8698368/2b24c17c-2b06-11e5-9113-fac01d9926d6.png)

**Comment by Anshuse** [comment]
Hi @meetgerry ,

It is because you have set the fields "Shown on Signup" and "Show after signup" to "No". Change the settings of these two fields accordingly and then check the issue.

Best Regards,
Anshu

**Comment by meetgerry** [comment]
Thats weird. I do not want members to see this membership during the signup because I do not want them to be scared of any kind of membership during signups.

If they want to upgrade to this membership, they can choose it by going to settings.

**Comment by smazurov** [comment]
Basically the 2 are exclusive, our admin simply does not prevent you from choosing no on both.  If the paid memberships enabled you do have to pick either signup or profile to display a paid membership level.

**Comment by meetgerry** [comment]
Thats the whole problem. Why do we force to choose a membership type while we set a default membership level already?

**Comment by smazurov** [comment]
based on your first screenshot, its not the default.

**Comment by meetgerry** [comment]
I refer to the following as was being set as default.

![2015-07-726](https://cloud.githubusercontent.com/assets/8540750/8734244/75b5430e-2c11-11e5-8c8f-3739cebcf41b.png)

**Comment by meetgerry** [comment]
Waiting for someone to treat this issue important. Request you not to ignore this issue.

**Comment by smazurov** [comment]
Im still not certain what the problem is. Please provide more information. Provide the settings for both your member levels and subscription plans, how they're interacting now with signup/after signup process and how you feel they should interact.

**Comment by meetgerry** [comment]
I really do not how to explain this further if my screenshots and explanations did not help.

**Comment by shivani2910** [comment]
Hi @meetgerry, the value set in the "Show after signup?" decides that whether or not that plan will be displayed in Settings > Subscriptions section of user. If you do not want to display the Paid plan during signup, just disable the "Show on signup?" and enable the "Show after signup?" setting. I've also attached these screenshots to explain you better after creating 2 plans (Free and Paid). I made the free plan default and set the value of "Show after signup?" to "Yes" for Paid plan and then it was displayed in Settings > Subscriptions section.

Please check doing this at your end too and then let us know if you still have any doubts. Thanks.
![test_plan](https://cloud.githubusercontent.com/assets/7815961/9128740/1ba01552-3ceb-11e5-9e1c-90c5a0d28040.png)

![test_plan2](https://cloud.githubusercontent.com/assets/7815961/9128744/22b51180-3ceb-11e5-9879-5ffbbabe6f7d.png)

**Comment by shannonlmann** [comment]
I am having an issue... the Subscriptions TAB is not showing up on my member profile page. At all... basically I'm using the same settings as above.

**Comment by smarty005** [comment]
I have the same issue. My subscription tab is not visible. How I can change it?

**Comment by Khushboo016** [comment]
Hi @shannonlmann, @smarty005, I've replied to your queries in the github issue https://github.com/SocialEngine/phpv4-issues/issues/541. So, please check there.

Thanks!
