### ISSUE TITLE
PHP 7 support

### ISSUE THREAD

**Issue by nizhnyk** [SocialEngine/phpv4-issues#186]
With PHP 7 coming in a few months and it being the big thing with performance improvements, it would be nice if PHPv4 would run on it and I'm excited to see the speed improvement on SE PHPv4.

**Comment by happycoder1337** [comment]
thats alot to ask for since SE doesnt even support 5.6

**Comment by smazurov** [comment]
We have people who run SEPHP on 5.6, and we'll be making improvements in that area in 4.9. As the release of PHP 7 comes closer, we will certainly look into supporting it.

**Comment by happycoder1337** [comment]
iconv is deprecated in 5.6.

**Comment by Elshara** [comment]
Problem is most host companies don't even allow v5.5 on their server installations so you will need to install it manually.

**Comment by nizhnyk** [comment]
Elshara, why would someone run socialengine on a shared hosting anyways? And on a dedicated server/VPS it's not up to a hosting company to decide which version of PHP you're running.
I already have SEPHP running on v7 but would just want official support.

**Comment by Elshara** [comment]
That's interesting. The hosts dedicated and vps I've always dealt with
wouldn't change  stuff like that saying it is stable for what you get.
I just don't feel like giving companies the run around so long as we
have a site to work with I could care less. By the time I find one
that is decent, all I care about is getting hooked up so I usually
never bothered with asking for latest updates. I'd actually expect the
hosting company to approach me with a concern about them wanting to
inform me there ought to be new updates present. I never knew there
was a php 7, I know companies that still use php 5.2 so if they won't
upgrade their hardware, it isn't like I can really know for sure
unless I have the physical server and a public internet connection
physically in hand.
I'm on php 5.3 I think. It works for what we use it for if it is a
little slow. Host iso may have upgraded to 5.4 but I'm not sure. No
way to really tell. Its not like Arvixe to up a server installation
for the life of them.

**Comment by nizhnyk** [comment]
Elshara, what is interesting is that you don't even know which version of PHP you have installed and commenting on an issue named "PHP7 support", so please move to a more relevant issue that will actually apply to you and stop flooding this one. Thank you.

**Comment by Elshara** [comment]
Just remember what I said about server companies who use older
software. Not everyone gets updated all the time, you don't need to
come at me like I don't know what I'm talking about. This discussion
is about php7 and I'm trying to make a point here, and my solution is
I'm finding a way to install it. It wasn't a crime to point out I
never heard of it until now but I was curious so I joined in.
BTW I work with my server and work on it every day so if I find a
problem, I look for an update. Otherwise, I suggest leaving it to work
as it is unless there's something you need to be installed. Php 5.5 is
what I actually have and it works just fine. I' am happy to have a
server and a working site, my needs are simple and I shouldn't have to
point that out so I won't.
They're working on php 7 for you I hope you like it. You can tell us
how it goes. I'm keeping my opinions, private from now on unless I
have an issue. I'll make my own topic about it and leave you alone on
the matter. It is what it is.

**Comment by pulsatemedia** [comment]
My concern would be stability with php7 being relatively new. Sometimes its better the devil you know, especially if you have a large community relying on your SE install. 
For sure we would need backwards compatibility with 5.x if 7 support was to be implemented. 
I'd also like to see real world performance figures with SE comparing both when leveraging opcode caching.

**Comment by smazurov** [comment]
we plan to maintain as much backwards compatibility as possible, we might bump minimum version to 5.3 or 5.4, but 5.x will continue to be supported.

**Comment by pulsatemedia** [comment]
Which version of SE do you plan implementing PHP 7 smazurov?

**Comment by smazurov** [comment]
no solid version in mind at the moment.

**Comment by stewfoxdev** [comment]
php7 should help, but the bigger boost might come from ZF2.
I had asked about php7+ZF2 just last week.. Response from support:

"I spoke with the development staff and it looks like there are no plans to upgrade to ZF2 at this time. We are currently working on a few other projects right now that are taking priority and while we are still developing for SE PHP, upgrading the framework would be a major product overhaul that we aren’t quite ready to take on. This is something we will certainly be doing in the future but aren’t quite ready for at this time."

From that answer I can't tell if they ignored the php7 part of the question, or the answer also applies to php7.  In any case I can see ZF2 would be a mighty big change and don't hope to see it any time soon. But for php7 it should be easy enough for the adventurous to "try it and see".

**Comment by Elshara** [comment]
Update. I switched hosts and tried switching to php 7 and social engine doesn't support it at all. It's a static we're sorry page.

**Comment by wadkins** [comment]
Have tried a clean installing on PHP7 with SE 4.8.10.  The first thing you are greeted with is the following fatal error

**Step 1: Enter License Key
Fatal error: 'break' not in the 'loop' or 'switch' context in C:\vhosts\_domainname.edu_\htdocs\SE\application\libraries\Engine\View\Helper\HtmlLink.php on line 79**

It hits another break on line 87.  If you modify the code to ignore the breaks, the install seems to continue but the pages render without theme.css support.

It also looks like SE uses deprecated or removed PHP features as well.  I would like to get an ETA on when PHP 7 is expected to be supported. I'm seeing about a 60% performance gain on similar applications.

**Comment by Elshara** [comment]
IT does this because it cannot connect to a database, specifically
mysql. I don't think it would work with mariadb. PHP7 is way under
developed in my opinion. It runs fast, but nothing can use it to work
as it should. So go figure. If code can't even work properly, I say,
it's a security risk.

**Comment by wadkins** [comment]
It is able to connect to the database (mysql) in this case.  As noted, if the breaks are commented out, it does access the database and renders the page - but without css support.

**Comment by Elshara** [comment]
I think it fails entirely using cloud linux.

**Comment by wadkins** [comment]
Fair enough.  I did not specify that I was using hosts I control.  In this case, it is a Win 2012 R2 server.

**Comment by Elshara** [comment]
Yeah I'm on Linux. It's incompatible.

**Comment by coder4web** [comment]
I running 2 big SE sites on PHP 5.6 with some minor patches, and I think SE can run on the PHP 7 without massive code refactoring, core is very compatible with PHP 7, just need be properly tested before release. But with 3rd party modules it can be longer run... We have 1 site with standard modules only, so I vote for release after core will be ready :)
Well, so I tried run this site on PHP 7 and found and fixed "Fatal error: 'break' not in the 'loop' or 'switch' context in" and several errors with obsolete CSScaffold (come on)... work in progress... but I think, I will wait for official release, cant test whole site by myself.

**Comment by Elshara** [comment]
It is a work in progress.

**Comment by nviitala** [comment]
The 6 year old Scaffold doesn't also work among many other things.

If the scaffold is still a must keep you need to escape it's content like
`function sanitize_for_xml($input) {
  // Convert input to UTF-8.
  $old_setting = ini_set('mbstring.substitute_character', '"none"');
  $input = mb_convert_encoding($input, 'UTF-8', 'auto');
  ini_set('mbstring.substitute_character', $old_setting);

  // Use fast preg_replace. If failure, use slower chr => int => chr conversion.
  $output = preg_replace('/[^\x{0009}\x{000a}\x{000d}\x{0020}-\x{D7FF}\x{E000}-\x{FFFD}]+/u', '', $input);
  if (is_null($output)) {
    // Convert to ints.
    // Convert ints back into a string.
    $output = ords_to_utfstring(utfstring_to_ords($input), TRUE);
  }
  return $output;
}`
@ http://stackoverflow.com/questions/3466035/how-to-skip-invalid-characters-in-xml-file-using-php

PHP 7 has been released half a year ago so it would be great to get SocialEngine working on it asap.

**Comment by Elshara** [comment]
I think it would be a good idea for social engine add on module providers to start looking into the compatibility of php7. This is because the site will fail if they don't support it including but not limited to how modules use bootstrap and connect to the database where social engine is installed.

**Comment by Hostile** [comment]
still no php7 support

**Comment by Elshara** [comment]
That's right.
We're up to 4.8.12 and Zend Framework needs to be updated as well as
php7. When switching to php7 causes all the menus that are pull down
menus to malfunction and the site looks like utter crap. I don't even
think php 5.6 is supported anymore.

**Comment by gsf00001** [comment]
Interesting reply about 4.8.9 and PHP7 
http://community.onsocialengine.com/post/5712869/socialengine-runs-only-with-php-5-3

So, supposedly PHP 5.6 is supported (I haven't tested - I'm on v5.5.29).  Also, PHP7 should be fully supported in 4.8.9 as per the above link.   As of a text chat 2 days ago w/SE, it seems there is still no ETA for 4.8.9 (not even vague like a year or 2017, 2018, etc.).

**Comment by smazurov** [comment]
Early testing suggests we'll be supporting 7.1 as well.

**Comment by DonnaScriptTechs** [comment]
This is implemented for 4.9.0 when it is released.

**Comment by Elshara** [comment]
Awesome!
I do believe 4.9 will fully support it and its required extensions.
