### ISSUE TITLE
Banned IP Problem

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#187]
This may or may not be a problem for other fields within the spam and banning settings of social engine. When an ip is banned, reloading the page displays all banned ips alphabetically, not from the order of last banned. If you wish to remove an ip, deleting it doesn't do so from the database. This has to be done manually so having a banned ip listed there by mistake or temporarily does not fix the issue. It may also be true for other fields within the page such as banned usernames, emails, words.

**Comment by Anshuse** [comment]
Hello @Elshara , We're able to reproduce this issue at our end and so, we're reporting this issue in our internal bug tracker for  our internal team discussion. Thanks!

**Comment by Elshara** [comment]
Awesome.

**Comment by DonnaScriptTechs** [comment]
This is fixed for our 4.9.3 version once it's released.
