### ISSUE TITLE
Super Admin 1 Can Be Un-Approved

### ISSUE THREAD

**Issue by BikersPost** [SocialEngine/phpv4-issues#192]
Super Admin 1 can be un-approved by another super admin restricting access to the site for Super Admin 1 

I would suggest "stats", "edit", and delete buttons only be avaible for Super Admin 1 by  Super Admin 1

**Comment by Elshara** [comment]
That's existed for years. Super admins have always had this access because they have the ability to edit any members content, kind of like the equivalent to network creator on ning. Admin levels below that do not have this access.

**Comment by BikersPost** [comment]
In /application/modules/User/views/scripts/admin-manage/index.tpl file, serach for the below code near line number: 181: 

    |
      <a class='smoothbox' href='<?php echo $this->url(array('action' => 'edit', 'id' => $item->user_id));?>'>
             <?php echo $this->translate("edit") ?>
       </a>

And, replace above code with below one:

    <?php if($item->user_id != 1) { ?> |
                  <a class='smoothbox' href='<?php echo $this->url(array('action' => 'edit', 'id' => $item->user_id));?>'>
                   <?php echo $this->translate("edit") ?>
                  </a>
    <?php } ?>

none of the user, except the user with ID=1 will be able to edit/unapprove the super-admin

**Comment by Elshara** [comment]
That's exactly what Ning had their setting to. One admin level one
network creator level and one moderator level. Mods couldn't touch
admins and admins couldn't touch network creator.

**Comment by shivani2910** [comment]
@BikersPost Thanks for pointing that out. We'll forward this to our team for internal discussion.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#7

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
