### ISSUE TITLE
Member Listings

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#195]
Members do not currently have the ability to group their content based on custom lists. This isn't like a social sharing feature, it is more of a custom list members can put on their profile page that lists content they posted as well as content they follow. Just like you can follow other members, which by the way is not independent of friendships, members should be able to have a custom list of followed content that they like or have participated in by content type.

**Comment by Anshuse** [comment]
Hi @Elshara , when you say "followed content", we didn't understand what are you referring to here because we haven't provided any option to follow the content. Also, when you say "participated in by content type.", are you referring to the content that members have liked or commented on. Please clarify.

**Comment by Elshara** [comment]
I'm talking about a module in which members can put content they have
posted or shared inside it and have it display as a list, but I guess
that's not possible because there is no archive of their content.
Everything is all divided up by module so they couldn't say have both
blog and forum post content displayed as a list, or photos and videos
as a list.
Regarding the follow feature, I thought when someone follows a user,
it means they could be notified of what that user has posted. But
that's only true if they comment on something someone else comments on
so the follow feature doesn't really make much sense. Right now  all
it does is display someone's friends list. I'm not sure if the only
way for it to be activated is if friends have verified requirements or
what it is supposed to do. But I'm trying to find an alternative list
for the follow feature and I was thinking it could be customized by
the person themselves, what does followers and following display on
someone's profile.

**Comment by Anshuse** [comment]
Hi @Elshara , 

1) Regrading "I'm talking about a module in which members can put content they have":
You may go for third party plugins "Likes" and "Advanced Comments" and using these plugins, your purpose of displaying all the content in one place will be achieved to some extent.

2) Regarding "Regarding the follow feature, I thought when someone follows a user,":
As we've mentioned previously, we haven't provided any such feature in core module of SocialEngine.

Thanks!

**Comment by Elshara** [comment]
I understand.
