### ISSUE TITLE
Member Content Manager

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#196]
Members do not have their own content manager to edit, update or remove their posts. Members should be able to manage everything they have shared on one page or at least have archives to things they have posted in they can click on. The only alternative is a profile widget which may or may not display links to all of their recent entries. Being able to see a members post archive may help others to find content they may or may not like about a member and would bring people together better, not just by searching public archives of module posts. It would be easier for users to get a quick glance of the things they have personally shared while being able to look at the activity feed of things they have commented on perhaps by a list of things they have contributed to on other peoples posts.

**Comment by Anshuse** [comment]
Hi @Elshara , thanks for your suggestion but we don't have any plan to implement this in our module. Thanks!

**Comment by Elshara** [comment]
That's okay.
