### ISSUE TITLE
Media Slideshow

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#198]
It would be nice if members could put on their profiles a media slideshow or custom playlist of things liked by them or even under member lists of content they could just click on in a pop up window for it to play. Could be a photo, audio or video.

**Comment by Anshuse** [comment]
Hi @Elshara , thanks for your suggestion. We're sorry but we don't have any plan to implement this in core module. Thanks!

**Comment by Elshara** [comment]
That's okay. It would be cool but perhaps a third party module could
do so one day if the core base could be set to allow individual photos
to have an index of some sort not just in albums but site wide.
