### ISSUE TITLE
Profile Page not working after update (Redmine Bug: #2663)

### ISSUE THREAD

**Issue by shivani2910** [SocialEngine/phpv4-issues#2]
## Bug:

Since I've upgraded from 4.8.6 to 4.8.7, I can no longer access member profile pages. I receive the following error:
```
Fatal error: Call to a member function toValue() on a non-object in
/home/allbowli/public_html/application/modules/Fields/View/Helper/FieldBirthdate.php on line 45
```

## Solution:

This problem is coming because of a possible bug in Zend Framework's "Zend_Date" class.

This issue can be resolved by doing a quick fix. Please copy the contents of [FieldBirthdate.php] (https://gist.githubusercontent.com/shivani2910/46bef32e3b07f17f5118/raw/a1a4a9a163eba6d7effb54507244a68dac24870a/FieldBirthdate.php) and replace the one at ```application/modules/Fields/View/Helper/FieldBirthdate.php``` on your server.

**Comment by smazurov** [comment]
fixed in [4.8.8](http://blog.socialengine.com/2015/03/23/socialengine-php-4-8-8-released/)
