### ISSUE TITLE
Profile Page Comment

### ISSUE THREAD

**Issue by nk45** [SocialEngine/phpv4-issues#20]
Profile Page comment is not working after going to 4.8.7 can you please fix this bug.

**Comment by shivani2910** [comment]
Hi @nk45, 

Thanks for reaching out!
 
To resolve this issue on your website, you will need to do the changes mentioned in this issue https://github.com/SocialEngine/phpv4-issues/issues/7#issuecomment-75711522

Once done, please re-check the issues at your end once and drop us a line in case the issue still persists.

Best Regards,
Shivani

**Comment by nk45** [comment]
The issue was still with me and I'm adding the Error Log list, please check it. 



2015-03-10T08:54:13+00:00 NOTICE (5): [8] main(): ArrayIterator::next(): Array was modified outside object and internal position is no longer valid (/home/haicom/public_html/UserName/application/modules/Core/layouts/scripts/default.tpl) [190]
Error Code: 4b6eb5
Stack trace:
#0 /home/haicom/public_html/UserName/application/libraries/Zend/View.php(108): include('/home/haicom/public_html/User...')
#1 /home/haicom/public_html/UserName/application/libraries/Zend/View/Abstract.php(890): Zend_View->_run('/home/haicom/public_html/User...')
#2 /home/haicom/public_html/UserName/application/libraries/Zend/Layout.php(796): Zend_View_Abstract->render('default.tpl')
#3 /home/haicom/public_html/UserName/application/libraries/Zend/Layout/Controller/Plugin/Layout.php(143): Zend_Layout->render()
#4 /home/haicom/public_html/UserName/application/libraries/Zend/Controller/Plugin/Broker.php(333): Zend_Layout_Controller_Plugin_Layout->postDispatch(Zend_Controller_Request_Http)
#5 /home/haicom/public_html/UserName/application/libraries/Zend/Controller/Front.php(965): Zend_Controller_Plugin_Broker->postDispatch(Zend_Controller_Request_Http)
#6 /home/haicom/public_html/UserName/application/modules/Core/Bootstrap.php(80): Zend_Controller_Front->dispatch()
#7 /home/haicom/public_html/UserName/application/libraries/Engine/Application.php(160): Core_Bootstrap->run()
#8 /home/haicom/public_html/UserName/application/index.php(205): Engine_Application->run()
#9 /home/haicom/public_html/UserName/index.php(24): include('/home/haicom/public_html/User...')
#10 {main}

**Comment by shivani2910** [comment]
Hi @nk45,

Above fix should have resolved the original issue you've pointed.
If some issue still persists after doing the above changes then please open a support ticket along with the details of your website to enable us look into this issue in your SocialEngine installation.

We appreciate your support and cooperation.

Best Regards,
Shivani

**Comment by nk45** [comment]
The above problem was not resolved that's why I given error log. When I comment to user it was not showing.

**Comment by shivani2910** [comment]
Hi,

yes, I got your point that so I mentioned that if the problem still persists after doing the above changes then please open a support ticket along with the details of your website to enable us look into this issue in your SocialEngine installation.

We appreciate your support and cooperation.

Best Regards,
Shivani
