### ISSUE TITLE
Optional WWW Redirection

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#201]
Some seo sites report social engine as not resolving the www or the ip of the domain name to its prefered url. Every social engine site doesn't have a www in front of it, and it seems there is a fix via .htaccess however it doesn't work because too many .htaccess files are being served. Not only that, but if you want to install some other software in public html directory, social engine won't let you view that software page unless you have a .htaccess file with the words rewrite engine on inside it. Even then there is a big problem with social engine serving files from a preferred url placement.

**Comment by smazurov** [comment]
`.htaccess` should be enough for redirection.  If its not, its most likely misconfigured `.htaccess`, not fault of SocialEngine.

**Comment by Elshara** [comment]
That's what I thought two but perhaps it could be looked into to
change things by default to www.

**Comment by shivani2910** [comment]
@Elshara If you want that your site should always open with "www" prefix, then we already have a KB article existing for this. You can modify your .htaccess file following the instructions mentioned here: http://support.socialengine.com/php/customer/portal/articles/2036045?b_id=4311 under "Adding the “www” subdomain to your site URL" section. Hope that helps!

**Comment by Elshara** [comment]
It is brilliant and well written!
Thank you!
