### ISSUE TITLE
Make Forms Pop Up Via Ajax

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#202]
Wouldn't it be nice if members could sort items and create new things all on one page? It would be nice if we had a widget that could do that, so if they still want to browse blogs, or simply create something write on the home page and post it, they could by adding the form via ajax or a pop up window so when they hit submit, instead of it taking them to their manage page, it takes them right to the thing they submitted via short cut.

**Comment by smazurov** [comment]
While some ajax improvements are coming (and are documented), the rest is really out of scope.  Thank you for suggestion.

**Comment by Elshara** [comment]
You're very welcome I think it would help.
