### ISSUE TITLE
Phpfox Integration

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#203]
Everyone knows the biggest competitor to social engine is probably phpfox and it being v3.8. IT would be nice to have an importer designed to move from one community to another. Phpfox has one for social engine, but not to social engine from phpfox.
It would be nice to be able to export a database from phpfox and perhaps just change the phpfox data core to something social engine can understand to import everything over. Many people go to phpfox because of speed improvements and many people go to social engine because of customization. Why not have both available.

**Comment by Elshara** [comment]
I myself have both available to see what people like to explore better. Total database integration shouldn't be that much of a problem. Everything else is already set up to read from what gets posted in a database before the files even are carried over. Once a directory structure is set, it should be easy to implement. Even though some things from social engine cannot be imported over to phpfox, it would still be really nice to have both available just in case say maintenance wise something were to happen. Matter of fact, you cannot even import a social engine database from one social engine site to another, having said that if you could, that would be great.

**Comment by smazurov** [comment]
We are working with 3rd party developer to have a phpfox importer available (for a small fee).  It should be out soon, we'll certainly mention in our blog.

**Comment by Elshara** [comment]
That is killer news it makes me so happy I work with both platforms
every day! Thank you thank you thank you!

**Comment by socialengineaddons** [comment]
Hi @Elshara , 

The [PHPfox importer script for SocialEngine PHP]  (http://www.socialengineaddons.com/phpfox-importer-socialengine) is out now. You may go through this [blog post] (http://blog.socialengine.com/2015/08/28/easily-import-a-phpfox-community-to-socialengine-php/) for the importer tool. 

Thank You.
