### ISSUE TITLE
Profile Attachments

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#205]
Every type of content should have attachment functionality be it a photo, music or video. Something new for social engine would be profile attachments. You could post on someones profile and add or attach stuff to your posts be it a blog, a tag,  reference or anything else including files, perhaps even the transfer of a particular post in admin settings  and a new feature allowing people to specifically lock certain features of their profile from displaying to people.

**Comment by Anshuse** [comment]
Hi @Elshara ,  this is not possible using default settings of SocialEngine but there're some third party plugins using which you may achieve this functionality. Thanks!

**Comment by Elshara** [comment]
I will keep watch thanks.
