### ISSUE TITLE
Merdging Profile Types

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#206]
Social engine has the ability to merge users to a profile type, however it doesn't yet have the ability to merge profile types to users if more than one is created. Merging profile types would have the effect of bringing together distinct groups of people who would otherwise be separated by profile user group.

**Comment by Anshuse** [comment]
Hi @Elshara , If you mean to say that if one member can be mapped to multiple "Profile Types" then we're sorry, but this is not possible using default settings of SocialEngine. Also, we don't have any plan to implement this feature in our core module and if you want then you can implement this on your site by doing code level customizations.

If you meant to say something else then please clarify.

**Comment by Elshara** [comment]
No no this is what I'm getting at. Tell me how this code can be
customized. I wish there was a way to have multiple imported sites on
one basic profile type. Each profile type could have a site on it, but
the problem is the importer only works when the social engine site is
empty. It'd be a lot easier to manage such things based on profile
types  so if they can't be merged, then they could remain compatible
with each other.

**Comment by Anshuse** [comment]
Hi @Elshara , this is not possible using default settings of SocialEngine and if you want this feature on your site then you may do code customizations at your end. Thanks!

**Comment by Elshara** [comment]
Okay.
