### ISSUE TITLE
Merge Content Types

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#207]
This would become social engines biggest and most powerful content posting platform of its kind. Allowing people to choose what kind of plugin, essentially would be possible by adding custom fields to a blank posting style.
Essentially this is how it would work. You have your basic forum board, which usually has lots of widgets around it. You have blogs, that does the exact same thing as a forum. Both gather comments and a main topic title, description and keywords using categories to organize posts. Merging posts would give people the ability to add existing comments into a main post while giving the main post itself either a transfer over to another feature, or even if it remained in the same feature say from forum category to forum category or from group to group, event to event, you would still have the ability to transfer the location of the comments posted. Allowing members to edit where their comments are displayed would also greatly help with this as it would truly bring about a change in how social structure is made possible. If you follow a member and get email updates on what they are doing, then you would be able to follow where they post, essentially putting users first.
I believe this is very possible using social engine. For example. Say a forum topic gets very active. Or a blog post, a photo, anything. You should be able to do things with each post, as well as based on member type, put posts not only into categories, but user customizable categories giving the actual categories purpose a face lift allowing people to choose more permissions of their posts as they become subject matter for engagement.
Example. I post in a forum that has maybe 20 replies. My post is very popular, and so people keep trying to reference my post, but since it is very popular, moving comments around to a specific topic would be easier. We'd just add a field that would turn the original comment into a post, then migrate the other comments into that post. If that forum becomes active, we could migrate that into a group, and then the group would become very active. We could migrate groups into forums, and then just edit the original title and description. We could add other fields, whether forums or blogs displays what members are participating in each topic kind of like how it is displayed here. That would also serve as the purpose of a group. People could add any attachments they want and still be able to post and share what they like as well as comment and share on each post that is available.
I know it sounds complicated, but it isn't. The structure is totally here, and I think this could really turn social engine into not only a premium platform, but a very useful premium platform.
Please, consider what I've said. This will totally be the best thing this business could ever become! It is already possible with member profiles, why not content types? Merging member profiles could work in a similar way especially if people need to create a new account for whatever reason.

**Comment by Anshuse** [comment]
Hi @Elshara , merging content of one module with another will make the system very complex so, we don't have plan to implement this feature in  our core module but there're some third party "Advanced" events/groups etc plugin using which you may achieve this so, you may go for these plugins. Thanks!

**Comment by Elshara** [comment]
Thanks for your consideration.
I still think the idea of a module builder could achieve this same
thing given the right set up so people know what fields they need,
rather than having set modules needing to be integrated with each
other to achieve the same idea. That way people could build comment
areas rather than having them listed per set of specific fields to
fill out, just a place to put thoughts down and hit post, they could
add other fields to make it spam proof like a check box and an
attachment area just by building on a module core base.
