### ISSUE TITLE
Better Filter Options

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#209]
Social engine doesn't have good filter options for widgets. AS in, displaying post titles only, titles with descriptions, how many characters per description or other custom fields that belong to a post such as how many people participating in a blog or forum, how many members are in a group, instead we are faced with only specific widgets that show one thing. Instead, we should be able to choose what is shown so only one instance of a particular widget gets displayed but right underneath one thing, could be another how ever we wish to show it. Making things item based not display based is better anyways.

**Comment by Anshuse** [comment]
Hi @Elshara , Thanks for your feedback but currently we don't have any plan to implement such feature in SocialEngine. Thanks!

**Comment by Elshara** [comment]
I understand.
