### ISSUE TITLE
Posts on Groups aren't displayed

### ISSUE THREAD

**Issue by eugene-wh** [SocialEngine/phpv4-issues#21]
When user posts on Groups tab 'Update' posts arent' visible, but stored in the database

How to reproduce

1. Make clean SE 4.8.7 installation
2. Install standard Groups 4.8.7
3. Create a new group 'My Group' (I'm using admin account)
4. Post anything on Update tab, click Share.

Result: post isn't visible 

Note, if you include a link to post - it will be displayed.

**Comment by eugene-wh** [comment]
It's looks like there is a fix already
https://github.com/SocialEngine/phpv4-issues/issues/7#issuecomment-75711522

Why isn't it released as a patch?

**Comment by shivani2910** [comment]
Hi @eugene-wh, 

We understand your concern here. We would like to tell you that we've already pipelined a release fixing all such issues so that it does not happen again in future. 

Best Regards,
Shivani

**Comment by smazurov** [comment]
fixed in [4.8.8](http://blog.socialengine.com/2015/03/23/socialengine-php-4-8-8-released/)
