### ISSUE TITLE
File Control

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#210]
We don't know where social engine positions each file, as in where every music file is placed, where every photo or video or attachment is placed, all we know is they are on the server somewhere within a social engine directory or database. If things weren't so database dependent where everything was just loading from files, this would make it easier to load and also easier to update entries by using the source files as a result. If the file is gone, the database won't recognize it, yet if the file is there, the database won't recognize it. It is better to know where the files are belonging to a better organized structure of the directory than having to do everything via database. Just a suggestion. Use files for user specific preferences then make a copy within the database so the database can write to the files where text information is stored.

**Comment by shivani2910** [comment]
@Elshara all the user uploaded content (photos, videos, music files, etc) gets saved in "/public/" directory   of SocialEngine. Thanks for your suggestions. We'll forward these to our team to look into the possibilities.

**Comment by Elshara** [comment]
That's really useful and may even help speed things up a bit. Thanks
very much. This will help for sure and I appreciate you forwarding
this.
