### ISSUE TITLE
Replacing Lists With Dropdown Menus

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#212]
In pages where lists can be tediously long, such as the pages list or a list of members, people may find it easier to just search through titles in a drop down menu to find what they are looking for. Currently the pages menu doesn't list itself in alphabetical order, it lists itself by latest entry. This may make it harder to find things, even though it can be done, drop downs with custom sorting options would make it a little easier to change things on the spot.

**Comment by shivani2910** [comment]
@Elshara It would be great if you could explain this use case using screenshots since we'tre not sure which section of SocialEngine PHP are you exactly talking about. Thanks.

**Comment by Elshara** [comment]
Mainly layout and menu editor.

**Comment by shivani2910** [comment]
@Elshara : Currently, we display pages listing in Layout Editor in the order of their entries to the system. This makes pages of a particular plugin display together which is fine. If you want to search for a particular page, you can simply use Ctrl+F and enter the string. Hope that helps!

**Comment by Elshara** [comment]
It does thanks.
