### ISSUE TITLE
Pop Up Box

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#215]
Social engine has a pop up box when confirmation messages and other items appear on the same page. If an existing box is open, if clicking on something else that would open up the box, it won't open. It closes the already open box and you have to click twice to get the one you want to open, instead of it already opening in the actual box itself.

**Comment by nizhnyk** [comment]
This is by design I'm pretty sure, when pop up box is opens the rest of the website is greyed out, showing that it is inactive, you have to click out of the pop up to view the website and be able to click on links again. Not a bug.

**Comment by Anshuse** [comment]
Hi @Elshara , We didn't understand what exactly you're trying to say here but if you mean to say that if one pop-up box is already opened in the site and when clicking on some other link that too will open a new pop-up then, the first pop-up window gets closed first and then clicking again on the other link opens a new pop-window then please note that, this is the way how the pop-up windows work i.e to open a new child window, parent window should be opened first and for that old child window needs to be closed. Hope you've understood our point.

**Comment by Elshara** [comment]
I understand. I'm wondering if there's a way to customize that somehow
to where you could have more than one box opened. Sort of, like a
moveable virtual browser within the page itself. This would allow you
to do other things based on one item that you'd otherwise have to rely
on the same box for different functions to accomplish. For example,
commenting or friending or messaging members or replying to things
people post. If we had a virtual browser, we could set up actions
related to the item being viewed, say for example, if it is a photo,
it could be resized or saved or edited in this manner if you were the
owner, or if a video were being shown, it could be edited right from
within a virtual browser box. I think it would make it a lot easier to
edit items on site, from both an admin and user perspective rather
than just having to go through a separate control panel.

**Comment by Anshuse** [comment]
Hi @Elshara , this is not possible using default settings of SocialEngine but if you wan to customize this feature as per your needs, then you may contact any developer who may implement/customize this feature for you.

**Comment by Elshara** [comment]
Thanks for the consideration.
