### ISSUE TITLE
Untranslatable string '(you)' in \User_FriendsController::suggestAction()

### ISSUE THREAD

**Issue by rwetzlmayr** [SocialEngine/phpv4-issues#216]
In ``application/modules/User/controllers/FriendsController.php`` around line 737:
``'label' => $viewer->getTitle() . ' (you)',``

``(you)`` should be translatable.

**Comment by Anshuse** [comment]
Hi @rwetzlmayr , Thanks for reporting this issue! We've merged this in issue #5 so, we're closing this. Thanks!
