### ISSUE TITLE
need a better upload system

### ISSUE THREAD

**Issue by alex2211** [SocialEngine/phpv4-issues#217]
I think you should get rid of that old flash based upload and move to a more modern ajax/jquery based one. Plupload is just one of the many they could use

**Comment by smazurov** [comment]
we only use flash based upload on the desktop for backwards compatibility reasons, on ipad and flash-disabled browsers we use html5 upload.

**Comment by Elshara** [comment]
Get rid of flash altogether and use html5 on desktop as well.
