### ISSUE TITLE
Attachments

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#219]
There's no way in social engine for someone to attach a file to anything. Not in comments, messages, posts. You know this sucks I was doing a results survey via Google Forms and ideally was just going to attach a pdf file to a post. Won't work in blogs, forums, comments, activity feed. Seriously this may be a deal breaker if there is no way to even embed a file I didn't see that option either so I take it iframe support won't work in comments either. There goes my idea of building a library on social engine. Guess what, phpfox has this as native support. I just might switch over there if I am unable to add files anywhere in social engine. I'm not going to take advantage of the file manager as an admin either, members have to be able to upload files it's that simple. Where are we on file attachments? 2070?

**Comment by Elshara** [comment]
The only way to send a file to someone is through comet chat messaging system. If I have to I'll spend $500 on comet chat just to send a file? I don't want people just having an archive of every file being uploaded, which is why the only files plugin by younet that is available, isn't on social engine. Files must be organized, and the way to do this is through attachments. What must be done to get attachments on social engine posts. I don't care if I have to hard code it myself. At this point, files are getting more and more popular and its like I said, switching to phpfox and sacrificing a custom layout is kind of sounding more and more like a good idea in exchange for a file and attachment manager, rss feeds, better loading website. Lack of rss in this day and age two is bothering me to say the least, but you know something, files are just as useful and I'll do what it takes to even break social engine and tell people its down for maintenance until we have the ability to upload files somewhere. Seriously this is beyond crazy.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#10

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
