### ISSUE TITLE
Feature Request - Facebook compatible meta-tags

### ISSUE THREAD

**Issue by AgtOrange** [SocialEngine/phpv4-issues#22]
I have experienced difficulties when sharing content from my SE page to facebook as their script isn't smart enough to detect image, description, etc. tags. They recommend that developers use the open-graph protocol to explicitly tell FB about the details of the images present in posts, articles, forums, etc. etc.

It would be useful if this could be embedded into SE somehow to help direct traffic to our community when sharing content.

Thanks

Jonathan

**Comment by shivani2910** [comment]
Hi Jonathan,

Thanks for your feedback. We've considered your suggestion to be discussed among team and will work on this accordingly. Till then, you may browse for various 3rd party plugins that provide such feature available on the following page of our website:
http://www.socialengine.com/customize/se4/plugins

Best Regards,
Shivani
