### ISSUE TITLE
User always listed as "Regular Member" in User Profile

### ISSUE THREAD

**Issue by mbwalsh** [SocialEngine/phpv4-issues#223]
![issue with member info](https://cloud.githubusercontent.com/assets/13633521/9050884/53a3c006-3a21-11e5-980c-7a55bef4db18.PNG)

If you view a user profile, he is always listed as a Regular Member in the Member Info area, even if he is an Administrator or Moderator.  I am using SE PHP 4.8.9.

**Comment by shivani2910** [comment]
Hi @mbwalsh,

In SocialEngine, "Profile Types" and "Member Levels" are 2 different things. Profile Type is something that is created / managed from Admin > Settings > Profile Questions section. This has to be chosen by user at the 1st step during signup and based on the type, further profile fields are displayed on next step to be filled by user.  While Member Levels are managed at Admin > Manage > Member Levels section by admin based on which admin decides that which member level users will have access to a particular feature on site. Admin can assign member levels to users from Admin > Manage Members section by clicking on "edit" link.

So, when we've mentioned this "Member Type" on user profile page, that points to "Profile type" of that member as chosen by him/her during signup.

Profile Types are completely different from member levels. If you want to assign member levels to users automatically based on the profile type chosen by them, then there is no default tool for this mapping of member levels and Profile types in SocialEngine currently. But yes there is a 3rd party free plugin "Profile Types & Member Level Mapping plugin" available that can be used at your end.

Please drop us a line in case of any further queries.

Regards,
Shivani

**Comment by Elshara** [comment]
You just have to rename profile type from regular member to something default until you install the plugin best solution for now.
