### ISSUE TITLE
How to translate "Choose File" button and "No file chosen" text?

### ISSUE THREAD

**Issue by ErikHP** [SocialEngine/phpv4-issues#225]
![choose_file_button](https://cloud.githubusercontent.com/assets/5085445/9154433/b25edbec-3e42-11e5-9438-ae1e2045d07d.png)

**Comment by ErikHP** [comment]
![choose_file_button](https://cloud.githubusercontent.com/assets/5085445/9154428/86b7a398-3e42-11e5-83af-84758d5de255.png)

**Comment by Elshara** [comment]
Describe the issue.

**Comment by shivani2910** [comment]
Hi @ErikHP, the text "Choose File" and "No File Chosen" that you've described above, belongs to the "File" type of input field that we're using in form. So, this text has not been written separately in code. It just comes automatically by using input type: "File" and the language in which it gets displayed, depends on the default language chosen by you in your browser. So, these phrases can not be translated from within SocialEngine's Language Manager. Hope you got our point. Thanks.

**Comment by ErikHP** [comment]
Thanks @shivani2910 for respond!
