### ISSUE TITLE
Add More Embedded Service Options

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#227]
Social Engine is introducing iframe.ly to the activity feed, apparently with some perks. Although we do not know yet whether or not it will be a requirement to have it installed, I do wish to point out some alternatives.
Embed.ly is popular for media based sites and I really wish it could be integrated as an alternative to iframe.ly since you can place text and or comments in as well. Native preview functionality should also be available. If you would like to use an alternative media pop up box, try integrating vid.ly into being available. Both embed.ly and vid.ly are available in phpfox v3.8 and work very well.
I believe both youtube and soundcloud use embed.ly for their integrations though I'm not sure.

**Comment by Anshuse** [comment]
Hello @Elshara , Our development team has done research on both i.e. iframe.ly  & Embed.ly and then decided to implement iframe.ly but we''ll bring your point to their notice and they will take required action accordingly. Thanks!
