### ISSUE TITLE
Forum Widgets Cannot Be Positioned

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#228]
In Social Engine the layout editor doesn't allow forum widgets to be positioned or controlled. For example forum categories, forum menus, forum search and other forum related areas. It's existing widgets are not present on the pages either, the only one that is labeled Content includes several widgets at once which unlike the other modules, cannot be altered through the layout editor.
We need the ability to be able to move or change widgets around on forum pages.

**Comment by shivani2910** [comment]
Hi @Elshara, we already have a plan to work on this in future and it's mentioned in our enhancements list. Thanks for your suggestion.

**Comment by Elshara** [comment]
Your  very welcome! This will help tremendously!
