### ISSUE TITLE
Layout Editor Improvements

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#229]
Currently Social Engine does not allow the positioning of widgets that fall inside of groups or events. It only allows to position widgets that represent group or event home pages or the groups or events themselves, but not the content from within it. This would be very useful for forums and photos area. It would be nice to have videos and blogs and music added to events and groups also.

**Comment by shivani2910** [comment]
Hi @Elshara your explanation is not that clear. Please explain to us a bit more using examples so that we may get back to you accordingly. Thanks.

**Comment by Elshara** [comment]
1. Create a group.
2. Look at the discussion forum or photos page.
3. Go to admin panel click on edit site layout.
4. Navigate to the photos (albums) section since forums cannot be
altered much. Try view photo page or album browse page since albums
cannot be uploaded to groups.
5. You will notice the same layout. Add a few other blocks to that
page and click save changes.
6. Go to your group photos page or upload a photo. Refresh it. Notice
the layout didn't carry over.
Layout of specific groups and events inside modules is different from
main site modules.

**Comment by Elshara** [comment]
What I'm trying to do is be able to change how module pages appear
when they are located within a parent in this case group or event.

**Comment by Anshuse** [comment]
Hi @Elshara , Thanks for clarifying your query! "Photos" tab in the "Groups" plugin is an extension of "Groups" module and is different from the "Albums" module, so, any changes made in the Albums' pages from "Layout Editor" section will affect the Album modules' respective page and these changes will not make any change in  the "Photos" tab in the "Groups" module. Thanks!

**Comment by Elshara** [comment]
Thanks for clarifying this.
