### ISSUE TITLE
Comments ON Profiles

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#230]
One thing you may notice, particularly with social engine, is that its comments are separate from its activity feed. Though activity feed items can be changed to allow the display of comments, it could be integrated better.
One way this will be very noticeable, is when importing a Ning site, no profile comments are displayed on any user. That is, until you add the comments widget somewhere on profiles, something not there in the default social engine installation.
Comments do get imported but aren't visible. The activity feed won't record any comments on profiles because it never had the module there to start with. This is also true because when you view the activity feed of someone on their profile, you can post to it making profile comments as a stand alone feature, sort of redundant.
Comments should either be integrated into the activity feed or the activity feed shouldn't allow posting to other profiles from other users. Nobody tends to use the comments feature on profiles anyways, but yet when a Ning site is imported, that's the only way to reach the comments on profiles is through the comments feature. If posts are made through the activity feed and then commented on, they don't show up in the comments feature so having two comment walls separate from one another on profiles makes it very hard to keep track of things. It also makes it confusing because one you can reply to, the other you cannot.
Besides, people don't get notified when something is commented on anyways through the activity feed, but they do if they comment on something where the comments feature is displayed. What makes this very problematic is that in either case, members cannot edit their posts or comments so if you did get notified about a comment, you as a member cannot delete the comment posted by someone else on your own profile or or that matter, on anything you post.

**Comment by DonnaScriptTechs** [comment]
Would you please check this once we release 4.9.0? We've improved comments and activity feed items.

**Comment by Elshara** [comment]
Sure.
Awesome!

**Comment by DonnaScriptTechs** [comment]
Have you tested this yet with the new comment settings?
