### ISSUE TITLE
Problems With Groups And Events

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#231]
Groups and events have no way of notifying their members when new items are added. The only way people can post things is through the activity feed or discussions or photos. There is no way to track by email when new members join a group or event or post anything. There is no way to set up or follow in group and in event modules like photos or discussions. People don't get notified when something happens within a group or event where they should because they are a member and because they have responded to join it. Members cannot leave a group or event once they join or respond to it. Members cannot edit their posts within groups or events. Group owners are the only one who have admin control over their group, it makes no difference if anyone else is promoted to officer they cannot manage it at all. Events make everyone grouped together as guests instead of separating who is a member and whether or not they are attending, maybe attending, haven't responded, invited, awaiting approval or not attending in which case they should be removed but aren't. Groups have this problem as well where invited members and members awaiting approval are grouped together making it harder to approve them or even manage who has been invited. You cannot do anything with invited members of an event or group. There is no way to customize the field display of what information is recorded for groups and events.

**Comment by Anshuse** [comment]
Hi @Elshara , 

1) Regarding notifications for Events and Groups, we've provided an option to enable/disable the Notifications regarding Groups and Events. Admin can control which all notifications should be enabled by default to the site members, from "Admin" > "Settings" > "Default Email Notifications" section. Site Members can also control which all notifications they want to receive, from Settings > Notifications section on their own. 

2) Regarding " it makes no difference if anyone else is promoted to officer they cannot manage it at al":
When a group member is promoted to Officer then the promoted member i.e Officer gets all the rights that a Group Owner selects while creating group as shown in below image:

![group](https://cloud.githubusercontent.com/assets/11085507/9224893/7b544e46-4123-11e5-8b30-9cf4262470aa.png)

Regarding other Events and Groups issues, currently, in core modules, members are displayed this way by default and for enhanced features, you can have a look at the third party plugins like "Advanced Events" and "Advanced Groups".

**Comment by Elshara** [comment]
Thanks for the feedback. I checked out the advanced events and groups,
they have a bad interface especially on the group and event browse
pages so I prefer the original module a lot better.

**Comment by socialengineaddons** [comment]
Hi @Elshara,

This is Ritu from SocialEngineAddOns. 
We are not sure of that whether you have checked our 'SocialEngineAddOns' [Advanced Events] (http://www.socialengineaddons.com/socialengine-advanced-events-plugin) and [Group/Communities Plugin] (http://www.socialengineaddons.com/socialengine-groups-communities-plugin) as interface of our plugins is liked by most of our clients. 

Please check the below demo links once and we hope you will like them.
http://demo.socialengineaddons.com/groups
http://demo.socialengineaddons.com/events

Best Regards, 
SocialEngineAddOns

**Comment by Elshara** [comment]
I was looking at the ones from younet I think. I'll check those ones
out I didn't know you made them also. I thought hire experts had
something of the sort but I get confused so many module providers to
remember. Thanks!
