### ISSUE TITLE
Attach One Module To Another

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#232]
Members should be able to attach a post to another. A great example of this would be to attach a poll to a blog, a poll to a forum post, a photo album to a video, a music track to an album, a playlist to a video, a photo to more than one album etc.
This could be done through a tagging system.

**Comment by shivani2910** [comment]
@Elshara, We don't have any plan to provide such integrations. We provide basic features for each module and if you need all the modules to be integrated with eqach other this way then there are already different 3rd party plugins existing in market like Advanced Albums, Advanced Videos, etc which allows you to attach other type of content with them. Thanks.

**Comment by Elshara** [comment]
Okay.
