### ISSUE TITLE
Adding Admin Pages To Layout And Menu Editors

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#233]
The front pages and design of the site can be easily implemented, however the back of the site cannot.
We should be able to move dashboard widgets around in the admin areas as well, change the menus and make it more functional if at all possible.

**Comment by Anshuse** [comment]
Hi @Elshara , As the Admin Panel is accessible only to the Super-admins and Admins so, we or any of our other clients didn't ever feel the need to edit the UI of Admin Panel. Also, to make the Admin Panel editable, we'll need to customize the script and add a lot more source code which will make script heavy but if you want to make the Admin Panel editable then you can customize the code accordingly at your end. Hope you understand the point here! Thanks!

**Comment by Elshara** [comment]
I do. I was mainly wanting to target dashboard widgets.
