### ISSUE TITLE
Let Members Send A Message Upon Friend Request

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#234]
Currently when members add another member as a friend, they cannot send a message to them which could display in their inbox or during some kind of global notification place like member updates. It would be nice if members could send a message or leave a comment upon adding them as friends.

**Comment by Anshuse** [comment]
Hi @Elshara , We've noted down your suggestion in our internal suggestion tracker for our internal team discussion. Thanks!

**Comment by Elshara** [comment]
Cool!
