### ISSUE TITLE
Following

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#235]
The follow feature is a weird one. I'm not sure what its purpose is but it doesn't work. Usually when you follow someone, you receive email updates on what they are doing. It doesn't do anything accept display your friends list in the order of oldest member joined the site first.
What it should do is provide a button on which if members click it, they could follow along with email updates on what someone is doing and have it be separate from the friends list. Mutual friends should show up in other places as well like for example on the browse members page along with the follow feature if you are following them. Friends lists should also give the option to follow by email.

**Comment by Anshuse** [comment]
Hello @Elshara , we've made 'one way friendship' just like 'two way friendship'. Same like 'two way friendship', we don't send any email notification regarding what my friends are doing in 'one way friendship'.

**Comment by Elshara** [comment]
Our community uses 2 way friendships.
