### ISSUE TITLE
Notification Lists

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#236]
Members should be able to split their notifications into lists and customize where such lists appear either in layout editor or in menu editor.
For example. Friend requests. Perhaps members want to separate that from group and or event invites. Comment notifications, perhaps members want to separate those from likes. Maybe members wish to divide things by feature, or things they comment on versus things they post. Maybe they want to combine those into lists, either way, members should be able to take these things into consideration so they can easily access what they care about.

**Comment by Anshuse** [comment]
HI @Elshara , Please be noted that "Layout Editor" and "Menu Editor" are the features of Admin Panel thus, both of these are accessible only to the site admins and, site members don't have access to any of these. Now, regarding your query, we've noted down your suggestion at our end for our internal team discussion. Thanks!

**Comment by Elshara** [comment]
I understand. This is awesome!
