### ISSUE TITLE
Somewhere To Put Google Translate Box

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#237]
We need an ideal place to put a Google Translate box so members can switch between languages. I know it isn't a perfect translation, but it is better than paying a price for a language you cannot speak just to have to either put the whole site in it to serve a majority vote who doesn't know English.

**Comment by Anshuse** [comment]
Hi @Elshara , thanks for your suggestion but implementing Google Translate box to translate or switch between languages will not give appropriate results so, we don't have any plan to implement this feature in SocialEngine PHP. Thanks!

**Comment by Elshara** [comment]
Sorry about that. I wasn't sure if it would even work.
