### ISSUE TITLE
Change Name Of Like Button Add Own Icon

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#238]
We should be able to change the name of the like button, have a dislike feature and add a customized icon for it.

**Comment by socialengineaddons** [comment]
Hi @Elshara, 

There is a plugin ['Advanced Comments Plugin - Nested Comments, Replies, Voting & Attachments'] (http://www.socialengineaddons.com/socialengine-advanced-comments-plugin-nested-comments-replies-voting-attachments) in our current [plugin catalog] (http://www.socialengineaddons.com/catalog/1/plugins), site Admin can choose to have either only 'Like' or both 'Like' and 'Dislike' [actions] (http://dmymvgkp4fkjt.cloudfront.net/cdn/farfuture/K0dlvt4_5PaV9IXif_vFxXC0St8F9jmS704rY3j3Hxc/mtime:1422854591/sites/default/files/slide5.png) on the website. You may visit the [demo] (http://demo.socialengineaddons.com/property/339/home-with-overlooking-lake/tab/3809) for more features.

You can easily add a customized icon by replacing the existing image in the directory at your end. 

Best Regards, 
SocialEngineAddOns

**Comment by Elshara** [comment]
Thanks! It seems I'll be checking out a lot of your plugins.

**Comment by socialengineaddons** [comment]
Hi @Elshara ,

You're always welcome. 

We have setup below 4 demos to showcase the various possibilities of our plugins:
- Main Demo: http://demo.socialengineaddons.com/
- Location  Based Demo: http://demo.city-search.socialengineaddons.com/
- Event/Ticket Selling Demo: https://demo.sell-tickets.socialengineaddons.com
- Social Commerce Demo: http://socialcommerce.socialengineaddons.com/

You may do a test signup at any of these to explore the endless functionalities. 

Thank You.

**Comment by Elshara** [comment]
I love your work and will definitely do this.
