### ISSUE TITLE
Manage Content You Like

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#239]
There's no way to view all the things you like. There should be through perhaps a link. This may have been brought up before but I cannot remember.

**Comment by shivani2910** [comment]
Hi @Elshara There is already a Free 3rd party plugin: "Likes Plugin & widgets" that you may use for this purpose on your website.

**Comment by Elshara** [comment]
Thanks for informing me. Looks cool.

**Comment by socialengineaddons** [comment]
Hi @Elshara , 

We have a Free plugin: [Likes Plugin and Widgets] (http://www.socialengineaddons.com/socialengine-likes-plugin-and-widgets) that will fulfill your requirements.

You can have a widgetized page: ['Browse Liked Items'] (http://demo.socialengineaddons.com/likes), this page shows recent, popular and random liked items in different tabs. Users would also be able to view the content liked by them under ['My Likes'] (http://demo.socialengineaddons.com/likes/mylikes). 

Best Regards
SocialEngineAddOns

**Comment by Elshara** [comment]
Do I have to buy something else to download it?

**Comment by socialengineaddons** [comment]
Hi @Elshara , 

Thanks for showing your interest in our [Likes Plugin and Widgets] (http://www.socialengineaddons.com/socialengine-likes-plugin-and-widgets). We will create your account for free, please [contact us] (http://www.socialengineaddons.com/contact) directly for this. 

Thank You.
