### ISSUE TITLE
Browse Members Page Search Widget

### ISSUE THREAD

**Issue by javatech20** [SocialEngine/phpv4-issues#24]
The search filter on the member search page http://networkname.com/members is not working properly as when a profile question is set to show in member browse page, the profile question doesn't show on the search widget. Please you fix this bug.

**Comment by Anshuse** [comment]
Hi @javatech20 , 

This is not a known issue in SocialEngine PHP and if you're facing this issue on your site then we suggest you to contact our support team to look into this issue in your installation specifically. They will assist you accordingly.

Best Regards,
Anshu

**Comment by Elshara** [comment]
Actually, this is a known issue. It doesn't work and I can confirm this. If profile links are available, searching for it will not pick it up at all. It just displays 0 results found even though you can click on the link itself that takes you to the search results page.

**Comment by shivani2910** [comment]
@Elshara Please send to us exact steps to reproduce the issue along with screenshot of each step.

**Comment by Elshara** [comment]
The profile questions show on the browse page but it doesn't complete the search. It says 0 results found. Even though the link may be there. And as I said in another issue, profile links do not display where ever the question type is shown to have them appear.

**Comment by Elshara** [comment]
Additionally browse members search area doesn't display any sorting
results for members. The browse all members with photos and browse
only online members also returns 0 results. It is as if the search for
members area doesn't work. This can be reproduced in control panel
when trying to search for display names or emails under member
management.
