### ISSUE TITLE
Archive Of Posts You Made In Profile Info Area

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#240]
On a members profile, you have 2 information sections. One is profile fields, the other is some kind of stat area. That's the area I would like to expand with archived links of members posts per module. For example, 16 blogs, 20 discussions, 32 albums, 5 videos, that sort of thing. Have it display in links the number of things you post per module per what you posted in.
Alternatively, make member stats with links possible.

**Comment by shivani2910** [comment]
Hi @Elshara, We're sorry to say but we don't have any plan to work on this. You may get this customized on your site if you need to have this feature. Thanks.

**Comment by Elshara** [comment]
I understand. Thanks for the feedback.
