### ISSUE TITLE
Leaderboards

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#241]
Top members and content would give social engine sites a very unique live statistic on what people are commenting on the most or viewing the most per day, week, month or any number of time.
Ning used to have this feature and it is something I miss a lot about it. We should have this available to us somehow.

**Comment by socialengineaddons** [comment]
Hi @Elshara,

We have a plugin [Advanced Members Plugin - Better Browse & Search, User Reviews, Ratings & Location] (http://www.socialengineaddons.com/socialengine-advanced-members-plugin-better-browse-search-user-reviews-ratings-location) in which there is an Attractive and Flexible ["Popular Members"] (http://dmymvgkp4fkjt.cloudfront.net/cdn/farfuture/lodRuvc5obSm7E5Caa76kxql4ZzWyUpuvdwfIjWW9UU/mtime:1406019070/sites/default/files/User_Mem_11.png) widget that can be placed on any widgetized page of your website.  

For viewing the 'Top Content' we have filtering based on many popularity criteria's like 'Most Viewed', 'Most Commented', 'Most Liked' etc. in our content based plugins like ['Advanced Events Plugin'] (http://www.socialengineaddons.com/socialengine-advanced-events-plugin), [Directory / Pages Plugin] (http://www.socialengineaddons.com/socialengine-directory-pages-plugin), [Groups / Communities Plugin] (http://www.socialengineaddons.com/socialengine-groups-communities-plugin) etc. 

Best Regards,
SocialEngineAddOns

**Comment by Elshara** [comment]
That seems really cool!

**Comment by socialengineaddons** [comment]
Hi @Elshara ,

In case you have any kind of queries regarding our plugins then you may directly [contact us] (http://www.socialengineaddons.com/contact). 

Thank You.

**Comment by Elshara** [comment]
Thanks! That's really helpful!
