### ISSUE TITLE
Build Your Own Module

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#242]
When it comes to functionality, members should be able to have an alternative to an app or api interface allowing us to build our own modules.
Call it what we want, add custom fields and make it published, live to all members. Probably an admin only feature, but still worth it, social engine would be an ideal platform for this since if everything had an easy to use interface, it would be possible to rename blogs to articles and add featured photos or other things through field options that blogs don't already have for example.
Another example would be to turn a video gallery into a media gallery through playlists, allowing us to turn media into what it should be properly used for in this day and age. A mixture of files readable on a site that you can browse through without issue attaching or removing or changing posts to whatever they could be most used for.
A module builder would give us the tools to make unlimited customization on simple things that we wish could only be done. Need an attachment? No problem, just add it in field manager for a particular module. You wouldn't have to sell core modules separately like groups and events, forums and blogs, music, photos and videos, just use the module builder and create your own duplicate modules for whatever purpose you need them for. You could even merge it with existing ones and edit the fields if you wanted to or move posts around to where ever you need them to be placed replacing the need for categories altogether.
IT doesn't stop there. With a module builder, you could replace widgets with list items and build upon new ways in which lists can be created. Newly created, most popular, oldest or newest first, replace any id system with a custom naming system if you wanted since members would be classified as a base. Replace any framework requirements for a simple reliance on javascript and an optional over hall interface for ajax. The possibilities would be much easier to build upon since the core itself would be all you need to expand on things that are already there.
Say goodbye to old templates. You could be able to use a responsive template for everything then just add in your own css otherwise use html where you need it to make things happen through a global editor. I think this would be much more efficient for social engine as a whole.
With a module builder, attachment manager and a template modifier, we could turn social engine into something undreamed of making every site have instead of a cookie cutter core script look and feel, a true fluid network of custom needs. All you'd have to do is use one language phrase and specifying the context where plurals would occur based on actions that could be customized as well. Want a dislike feature, just add another action. Want a comments area, just add a text field and let the database take care of the rest. Want to message all friends, just use a global variable indicating where all users in what list should be addressed and let the context speak for itself.
The technology is there and I've seen it be used in some third party modules for social engine.
We could start small, working with forums or one module, then add more things from an entirely fresh core base. I think even as a stand alone module, the core builder could replace all other modules and let the template editor and action manager or attachment manager come with it.

**Comment by Anshuse** [comment]
Hi @Elshara , Thanks for your feedback! Currently we don't have any plan to implement any such module but we've added this in our internal suggestion tracker and will discuss with our team to take appropriate action. Thanks!

**Comment by Elshara** [comment]
Seriously? The one feature suggestion I never thought you'd make or
consider. This just made my day!
Thank you!
