### ISSUE TITLE
Social Engine 4 Import

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#244]
It would be nice to import custom data into a social engine installation if such data could be extracted from an existing database or file directory. It would also be nice if we could export social engine data like members and posts, to have as a back up.

**Comment by shivani2910** [comment]
Hi @Elshara, we don't have any plan to work on this currently. There are a few 3rd party Profile Import/Export plugins available in market that can be used for this purpose. Thanks.
