### ISSUE TITLE
Importing From Wordpress

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#245]
It would be nice to import wordpress data into a social engine site, mainly blogs and comments.

**Comment by shivani2910** [comment]
@Elshara, We do have a plan to integrate SocialEngine in a few aspects with Wordpress. But as far as importing blogs is considered, there is already a 3rd party "Blog Importer" plugin existing for SocialEngine. You may check this for more details. Hope that helps!

**Comment by Elshara** [comment]
I'm really looking forward to this!
