### ISSUE TITLE
Verification

### ISSUE THREAD

**Issue by wtoalabi** [SocialEngine/phpv4-issues#248]
Would it be possible to add a user-verification feature like Facebook, twitter, etc with cute check-up sign!?
I know there is a third-party plugin for this but we all know that they are not cross-usable.
To be specific, I use Timeline and Wall plugins from Hire-Experts...great guys! But they are not offering the feature. The guys that are, ask me to use their own Wall feature for it to work!
Here lies the problem.
I think this feature, though looks trivial, will increase user engagement tremendously!
I want it (and I believe every community owner out there do too).
Thanks!!!

**Comment by wtoalabi** [comment]
#Core

**Comment by DonnaScriptTechs** [comment]
Do you have a screenshot of what you had in mind?

**Comment by gsf00001** [comment]
Donna - as always, optional please.  I use SEAO and their Member Verification system is fantastic.  Allows you to configure how many User Verifications are required before the Check-Verification-Icon appears, and allows actual reviews too.  More ADMINs expecting more from SE out-of-the-box is great, as long as it doesn't interfere with what 3rd-Party Devs have added for years while features were sparse in SE.

**Comment by DonnaScriptTechs** [comment]
Hi @gsf00001 yes optional is better. I'm just going through this entire Github to try to get it organized. I am labelling Bugs or Enhancements so our core developers have an easier time looking through for bugs to fix as that's more pressing. None of the things I'm marking as Enhancements have been accepted. This is only for sorting purposes. :)

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#12

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
