### ISSUE TITLE
Typo in title tag on search results page.

### ISSUE THREAD

**Issue by pulsatemedia** [SocialEngine/phpv4-issues#251]
I think this was reported in the old bug tracker, I'm on 4.8.9 and still see this issue with the text "searc" appearing in the title tag on the search results page.

**Comment by shivani2910** [comment]
Hi @pulsatemedia, thanks for pointing this issue. We'll report this to our development team. For now, you can resolve this at your end by going to the Admin > Layout > Layout Editor section and opening "Search Page" and then click on "Edit Info" link to edit the title tag where you can replace the value of "PAGE TITLE" field with the correct text and save changes. Hope that helps!

**Comment by pulsatemedia** [comment]
Ah, yes I didnt think to look in the layout editor for this page.

**Comment by smazurov** [comment]
Fixed in [4.8.10](http://blog.socialengine.com/2016/01/20/socialengine-php-4-8-10-is-released/)
