### ISSUE TITLE
4.8.9 Blocking issue.

### ISSUE THREAD

**Issue by SpiritWolfie** [SocialEngine/phpv4-issues#253]
I checked the pages for this and didn't see it anywhere

This has been a "Huge" issue for my community, Blocking does not work correctly like it should

If user A blocks User B, User B can not see their profile, -however- User b can still comment on user A's stuff etc..

The way it should work is, if user A blocks User b, User b should not be able to see their stuff.

I really look forward to seeing this resolved, please please let me know if I can do anything to assist in this matter.

**Comment by shivani2910** [comment]
Hi @SpiritWolfie yes, we already have a plan to improve blocking feature in the script. We'll be doing such improvements in near future. Communication regarding this is already going on here: https://github.com/SocialEngine/phpv4-issues/issues/221

**Comment by SpiritWolfie** [comment]
ah ok Shiv, thank you for that, 

I know this is not related to the topic at hand but most of the time when I attempt to respond to the blog updates you guys release the system keeps denying my comments, no idea why.

Feel free to close this, I must have overlooked the issue for this one.

**Comment by shivani2910** [comment]
@SpiritWolfie thanks for your response. Regarding comments on blog posts: Those comments appear a few hours after you post them on blog post. Currently, I don't find any un-approved comment posted by you on blog post.

**Comment by shivani2910** [comment]
This is implemented for 4.9.0 when it is released.

**Comment by Elshara** [comment]
Awesome!
