### ISSUE TITLE
Personal Messages

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#254]
Personal messages are a bit basic. They lack the ability to invite other people to a message, or being able to forward a message to someone else. They also lack the ability for folder creations to archive messages. All you have is the ability to reply or delete to the person who sent you a message. If you were copied on a message sent to multiple people, there is no way to customize who you can send a reply to.

**Comment by Anshuse** [comment]
Hi @Elshara , we've noted down your suggestion in our suggestion tracker and will take appropriate action on this. Thanks!

**Comment by Elshara** [comment]
Oh wow thank you! How about threaded conversations? would be really nice to see.

**Comment by Elshara** [comment]
Also when viewing a message, there's no way to view newest first, you
have to scroll for ever until you come to the latest message.

**Comment by meetgerry** [comment]
Personnel message what SE now has is absolutely useless. Its so lousy and its like a usual inbox. It does not thread messages from specific users, which is a bare minimum. Usually, when users messages, they pick up the user to message and in that case all message of a users should show up as one message like who you have in Skype and Facebook.

**Comment by Elshara** [comment]
I know. Emails should just have this by default.
