### ISSUE TITLE
Forum title is not translated in post-create.tpl

### ISSUE THREAD

**Issue by rwetzlmayr** [SocialEngine/phpv4-issues#255]
The l10n of forum titles is inconsistent.

The forum title **is localized** when a new topic is created, see line 24 in ``application/modules/Forum/views/scripts/forum/topic-create.tpl``:

``
  &#187; <?php echo $this->htmlLink(array('route'=>'forum_forum', 'forum_id'=>$this->forum->getIdentity()), $this->translate($this->forum->getTitle()));?>
``

The forum title **is not localized** when a new post in an existing topic is created, see line 22 in ``application/modules/Forum/views/scripts/topic/post-create.tpl``:

``
  &#187; <?php echo $this->htmlLink(array('route'=>'forum_forum', 'forum_id'=>$this->forum->getIdentity()), $this->forum->getTitle());?>
``

I'd suggest to choose consistent l10n of forum titles and stick with it.

**Comment by Anshuse** [comment]
Hi @rwetzlmayr , We've added this issue in our internal bug tracker to resolve this in near future release. Thanks!

**Comment by smazurov** [comment]
Fixed in [4.8.10](http://blog.socialengine.com/2016/01/20/socialengine-php-4-8-10-is-released/)
