### ISSUE TITLE
Date format is change when i choose different language from footer drop down.

### ISSUE THREAD

**Issue by vjgarg2** [SocialEngine/phpv4-issues#256]
I have created two language from admin panel. When i create a event in french language the below format is show:

![fr](https://cloud.githubusercontent.com/assets/6785287/9354291/f14e3a26-468c-11e5-8e20-245f8dd5d7ba.png)

When I create event in english language, date format show like below:

![en](https://cloud.githubusercontent.com/assets/6785287/9354306/0f8834d8-468d-11e5-8635-2a8f7965dc0f.png)

**Comment by Anshuse** [comment]
Hi @vjgarg2 , As every locale has it's own specific format for date, and If there're multiple languages on site and if you select any particular language, from the drop-down present in the footer, at your end then that particular language becomes Locale of your site so, dates on your site will be displayed according to the specific format of that Locale. For ex. if you choose English language from the drop-down at your end then the Locale value in the "Settings" section will be set as English and  dates & calendar on your site will get displayed in the format specified for English language. Hope you've understood the point here!

**Comment by vjgarg2** [comment]
Hi @Anshuse, thank you for your fast reply!!

**Comment by meetgerry** [comment]
OK, I am not sure if this holds value to anyone. A link to toggle between languages have to be ideally placed somewhere in the header. If it was a CMS or a site where features like activity feed wasn't there where you have length long scrolling, then it was OK. But SE has activity feed which scrolls on forever and in that case the user can never reach the footer to switch language.
