### ISSUE TITLE
Personal Message From Member Profile

### ISSUE THREAD

**Issue by dave1966uk** [SocialEngine/phpv4-issues#257]
Hi
Would be nice if a message option in the member profile to send a message?  It would be quicker than the present search method which is not exactly obvious.

**Comment by Elshara** [comment]
I agree. I wish it would show up under browse members.

**Comment by Anshuse** [comment]
Hi @dave1966uk , Please be noted that if site admin set "Allow Messaging" field to "Friends Only" or "Everyone" (from "Admin" > "Manage" > "Member Level" section), then option of "Send Message" gets displayed on the Members Profile:

![allow_messaging](https://cloud.githubusercontent.com/assets/11085507/9435368/db67b378-4a64-11e5-9711-be46a7b6784b.png)


![send_message](https://cloud.githubusercontent.com/assets/11085507/9435369/db90b2aa-4a64-11e5-80e8-7eb4ffd35a9c.png)
