### ISSUE TITLE
Manage Site Invitations

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#258]
Currently there's no way to manage who has been invited to a social engine website. You can only invite up to 10 people at a time, and it can only be done by email. Although there probably is a third party plugin to have the ability to invite people via other services, it would be nice if social engine could build something that is a little more advanced than 1 email per line.
Even if there was a third party plug in for invites, there's no guarantee they have been received. I don't think you are able to track the status of an invite, but neither are you able to remove one also. Unlike groups and events, where the creator can manage such things to a certain extent, this isn't possible in social engine for member invitations. Also unlike groups and events, only 10 people can be invited. If that number is greater, more invites cannot be received until the original 10 have been accepted.

**Comment by Anshuse** [comment]
Hi @Elshara ,

Regarding "it would be nice if social engine could build something that is a little":
For Advanced features in the core Invite feature, you may go for third party plugins.

Regarding "groups and events, only 10 people can be invited. If that number is greater":
Invite can be sent to more than 10 members, please check this at your end by sending an invite to 10+ members and you will see that invite is being sent successfully. Also, yes, we've written that "Enter up to 10 email addresses..." to avoid the chances of missing an email but email can be sent to more than 10 members.

Thanks!

**Comment by Elshara** [comment]
I still think it should be greater than 10. The emails do not send.
