### ISSUE TITLE
Text area editors: Display blinking I-beam cursor at first click in area

### ISSUE THREAD

**Issue by auntialias** [SocialEngine/phpv4-issues#260]
The WSYWYG text areas in SocialEngine break a very-well-established User Interface convention. 

**Normal behavior:**
1. Click mouse inside text area.
2. Blinking I-beam appears. (User knows that app/site/software/everything is ready to accept typing.)
3. User begins typing.

**SocialEngine behavior:**
- **Text Input** (single line of text) works as expected.
- **Text Area (Plain, without any WSYWYG tools at top)** works as expected.
- **Text Area (WSYWYG)** No blinking I-beam appears upon click in Text Area.
  1. User double-take, disorientation ("Wait. Where am I? I _thought_ I clicked in the box. I saw the blinking thing up there when I wrote the title for this item.")
  2. Hesitation. ("Is something wrong here?")
  3. Tentative attempt to begin typing. ("I _hope_ this works.")
  4. Success. Uneasy success ("Huh! That's weird. It never works _that_ way before. Oh well, Okay. I'll keep typing")
  5. User is now thinking more about the tool than about whatever she or he intended to write in that text box. 
  6. Fail.

**Comment by Anshuse** [comment]
Hello @auntialias , We're reporting this issue in our internal bug tracker to work on this in near future release. Thanks!

**Comment by pulsatemedia** [comment]
+1 on this. The tinymce implementation in SE currently leaves a lot to be desired for user experience.

**Comment by mbwalsh** [comment]
Yes, I discovered in Chrome that the only way to get the cursor in the Rich Text Editor box is to enter "Tab" from the keyboard.  This is a problem for my users.

**Comment by DonnaScriptTechs** [comment]
This is fixed for 4.9 when it is released.

**Comment by Elshara** [comment]
Awesome.
