### ISSUE TITLE
Review of Video Upload v.4.89 (FFMPEG INSTALLATION PROBLEM)

### ISSUE THREAD

**Issue by princeade** [SocialEngine/phpv4-issues#261]
SUMMARY CONCLUSION:
This member believes that if small videos are successfully uploaded to a website  then one should be able to RECONFIRM UPLOAD LIMIT AND EXECUTION TIME LIMIT too. This is lacking in the Social Engine update.

PROBLEM:
Social Engine Addons Team recently installed FFMPEG to my website on (August 17, 2015)  at www.onibokun.com and discovered that the maximum video upload length that can be loaded in a single upload is about 7min. 53sec. Any upload over that will fail upload.

I reported the problem to Social Engine Technical Support Team on August 21st 20015, but were unable to resolve the problem. The support staff uploaded video clips up to 3min 25 secs MAX. but was unable to upload a 9 min. video clip. And still could not explain why this was not possible.

In my own example. I tried several times to upload an "mp4" video clip of about 6min. 53 secs. In each attempt, I received an "UPLOAD FAIL ERROR: Server returned HTTP Status - #500. 
*********************************
<?xml version="1.0" encoding="UTF-8"?>
-<Error>
<Code>AccessDenied</Code>
<Message>Request has expired</Message>
<Expires>2015-08-22T06:10:24Z</Expires>
<ServerTime>2015-08-22T06:20:35Z</ServerTime>
<RequestId>5218A37D4222C0C3</RequestId>
<HostId>izlAta4bSV6N0eU5OhwaQ/WhSvYQqBiNQRqpdz1katrKjaJaio4CEBuasodyypwYapRTwzDo4CU=</HostId>
</Error>
********************************

Another error message was found also found at /var/log/ of my PLESK SERVER: 
 "sh: 1: ffmpeg/ffmpeg: Permission denied"

 The Social Engine Support staff was unable to upload a 9 mins and could not even provide an explanation why this was impossible to upload more so that the maximum video clip the support staff could upload was a maximum of 4 minutes.video clip.

This member believes that if small videos are successfully uploaded to a website  then one should be able to RECONFIRM UPLOAD LIMIT AND EXECUTION TIME LIMIT too. This is lacking in the Social Engine update.

![upload failed](https://cloud.githubusercontent.com/assets/8850267/9422843/85671bc2-4874-11e5-81ba-655494030924.png)

**Comment by Anshuse** [comment]
Hi @princeade ,

As we've replied to your open support ticket that this issue is because of some server configuration settings so, we suggest you to contact your hosting company regarding same. For any further comments on the same issue, please reply to the respective support ticket. Thanks!

**Comment by smazurov** [comment]
I should mention that we do not maintain provide any support for FFMPEG, its an open source video transcoding application that is entirely separate from SocialEngine. We simply leverage it to encode videos.

**Comment by Elshara** [comment]
It's a server uploading problem not a social engine problem.
