### ISSUE TITLE
All the pages available in Layout Editor are not searchable in Global Search.

### ISSUE THREAD

**Issue by Anshuse** [SocialEngine/phpv4-issues#266]
***Description:***
There’s a checkbox “Show this page in search results?” under “Edit Info” form of each page in the Layout Editor section,  and even if this checkbox is checked for a page then also the respective page is not searchable in the Global Search. So, we should either remove this checkbox or fix this search issue.

**Comment by Elshara** [comment]
Social engine search feature doesn't pull up accurate results even if you use the database you have to sift through all the code just to find what you are looking for what you know is there but just cannot find. I doubt this is an issue where the checkbox is concerned, it has to do with the poor search algorithmsocial has. It can search only the basic fields of some areas, search as a global site tool must be drastically improved for this to have any effect.
