### ISSUE TITLE
FR: Introduce a "onFieldsValuesSaveBefore" event in \Fields_Form_Standard::saveValues().

### ISSUE THREAD

**Issue by rwetzlmayr** [SocialEngine/phpv4-issues#268]
I'd propose to add an event named  "onFieldsValuesSaveBefore" to ``\Fields_Form_Standard::saveValues()`` which is fired before the new field values are saved. This event would complement the existing "onFieldsValuesSave" event nicely.

Thus it would allow applications to catch both old and new values for a field, enabling them to enforce business rules or start custom workflows depending on the changes of field values.

Here's a diff with the suggested code change:

```diff
--- application/modules/Fields/Form/Standard.php	(date 1425107434000)
+++ application/modules/Fields/Form/Standard.php	(revision )
@@ -228,6 +228,12 @@
     // Iterate over values
     $values = Engine_Api::_()->fields()->getFieldsValues($this->getItem());
 
+    // Fire pre save hook
+    Engine_Hooks_Dispatcher::getInstance()->callEvent('onFieldsValuesSaveBefore', array(
+        'item' => $this->getItem(),
+        'values' => $values
+    ));
+
     $fVals = $this->getValues();
     if( $this->_elementsBelongTo ) {
       if( isset($fVals[$this->_elementsBelongTo]) ) {
```

**Comment by smazurov** [comment]
thanks for the patch, we'll incorporate it into the next version. As a side-note, we want to support as many extension points as possible, so suggests like this are highly encouraged.

**Comment by smazurov** [comment]
Added in [4.8.12](http://blog.socialengine.com/2016/07/07/socialengine-php-4-8-12-is-here/)
