### ISSUE TITLE
Tiny Mce Editor is not working fine.

### ISSUE THREAD

**Issue by vjgarg2** [SocialEngine/phpv4-issues#269]
I have created a blog on: http://demo.socialengine.com/ 

with photos and lines breaks in content.

But, when I see this blog all is mixed up.

Go to URL: http://demo.socialengine.com/blogs/138/60/test-blogs
![screenshot from 2015-09-07 16 15 28](https://cloud.githubusercontent.com/assets/6785287/9715214/e75546d8-557b-11e5-9423-ddda31f12a09.png)

I have attached the SS fro edit blog page.

**Comment by Anshuse** [comment]
Hi @vjgarg2 , It's a property of Tinymce Editor that when you hit "Enter" then a new <p> tag gets created i.e new line gets started. To be able to create space between two lines, you need to hit "Shift+Enter". With "Shift+Enter", new <br> gets created and space will be created there. Thanks!
