### ISSUE TITLE
How To Export Social Engine Database

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#270]
Not so much an issue, but a need. Social engine has a lot of import tools available, however converting or exporting such data including member profiles is not well discussed. We need a way to export member data without having to delve into the tables of the database or the html of blogs and forums or the ftp of the site just to get a copy of the content and try to match it up with the member who posted it. That's not to mention attachments if they are posted in third party plugins.

**Comment by Anshuse** [comment]
Hi @Elshara , to know the steps to export the database of your SocialEngine site, you may go through  point 3 and 4 of "Exporting your database and.." section of our article http://support.socialengine.com/php/customer/portal/articles/2019547?b_id=4311
Thanks!
