### ISSUE TITLE
Static URL Issue

### ISSUE THREAD

**Issue by meetgerry** [SocialEngine/phpv4-issues#271]
SE CMS generates static URLs like https://website.com/?c=2514 and URLs like this makes the SE site dead slow.

I do not know what is causing this, does anyone know what is this and why is it pushing the site very slow and why speed testing sites like GTMetrix or Pingdom are rating SE sites very low?

**Comment by shivani2910** [comment]
Hi @meetgerry,

Thanks for reaching out!

The URL format that you've mentioned seems to be of static CSS and JS files that are rendered on any SocialEngine PHP website. If you feel that your website's speed is getting affected by such static files, we suggest you to store your static files such as Javascript and CSS files on a CDN hosting site such as MaxCDN. For this, you will need to enter the temporary address to the CDN site at Admin > Settings > General Settings > Static File Base URL field. For more details, you may also check this article: http://support.socialengine.com/php/customer/portal/articles/1645737 to know how to enter that url and set-up a CDN to store your static files. This will definitely improve your website's speed to a great extent.

Hope that helps! Thanks.

**Comment by meetgerry** [comment]
Thank you for replying Shivani. I have already been using MaxCDN and the problem I mentioned is shown even while on CDN. There are tons of URLs that are followed by /?x=2514 kinda.

MaxCDN guys have given up on this saying that SE platform itself is terrible. See the screenshot and that will show you there is some URL like this that takes 65% of the site loading time.
![screenshot2015-09-1218](https://cloud.githubusercontent.com/assets/8540750/9908636/3fd4cc34-5c9d-11e5-8f6d-8f6bc4337c37.png)

**Comment by meetgerry** [comment]
Sending you the the URL overview.
![screenshot2015-09-1221](https://cloud.githubusercontent.com/assets/8540750/9908892/62b1b108-5c9e-11e5-9e37-902695d8bb2c.png)

**Comment by pulsatemedia** [comment]
I do WPO consulting and just checked your site. The slowness is nothing to to with the URL format IMO, I would throw what MaxCDN have mentioned out the window.

I see SE get flack for being slow very often, but in my experience its nearly always down to how it has been (mis)configured. Server and database optimization, correct leveraging of caching and being selective about the plugins you use, along with the widgets you select for a given page is crucial. The way I explain it is that you cant put three tonnes of sand in your stationwagon and expect it perform well. Sure, the sand fits in there, but that doesn't make it a good plan right?

Keep in mind, benchmark websites are based around best practices for semi-dynamic content on CMS. Wordpress, joomla etc etc. A social network platform like SE is a different ballgame. they are much more complex and customizable than your typical blog-esque CMS. Run a speed test against your facebook homepage. It aint pretty!
I'm not suggesting for one minute that you shouldn't benchmark and make sure your site is fast, but just be cognizant that some of the suggestions are best practices that you will not be able to leverage.

Off the cuff you need to correct three things on the homepage:
1 TTFB on the homepage is three seconds. That is huge. It's also the most common slowdown with with SE and its often a mismatch between your server/database capability (including its configuration) along with how the socialengine website is configured.
Your server hardware needs to be in ballpark for the unique mix of plugins you have installed and your database need to be configured to perform optimally to match your SE config and server hardware.
2 Number of objects is too high at 117
3 Your static assets are not being cached, you need to find out why this is the case.

There's a bunch of other things you can look into, but you need to get that TTFB down before anything else. The URLs are not the issue. You have third party plugins on the homepage, so I'd be chatting with the developers of those as well.

http://www.webpagetest.org/result/150916_47_WDH/1/details/

**Comment by meetgerry** [comment]
Thank you pulsatemedia, your information is very helpful.

The tech from my hosting company informed me that around 5060 PHP calls are being made to the server due to invalid file path or file not existing.

When they narrowed down they assumed that this could be because of the statis URL issue. There is one URL that consumes more than half of the site load time (https://bolfox-westsiders1.netdna-ssl.com/?c=2514)

Yes, the TTFB is also high and the server guys do not know whats causing this.

I am not sure how could the TTFB be rectified.

**Comment by pulsatemedia** [comment]
When and from where is that URL being called by browsers?
Have you tested by bypassing the CDN? My experience with MaxCDN as been less than great with SE. I dont think it's the cure here but if I was digging into this, I would bypass the CDN totally, change DNS if needed and then start a deep dive into whats happening.

The php calls that are failing, what plugins are they related to? Find that out and talk with the developers.

Also, that URL is https, whereas your site is being called over http that's an issue too. Won't hurt your TTFB though but another thing to consider.

If you cant get the TTFB down at the server end, you can alleivate it to the end user with some judicious, tactical caching of pages and objext, I'd reccomend cloudflare for that.

**Comment by meetgerry** [comment]
I am copy/pasting the followup done by the hosting tech below regarding the PHP calls for files that do not exist or invalid path. There are over 5060 such calls.

============================================
Thank you for your patience. After some investigation, I have a better idea of what is going on. The problem with the _Invalid PHP Requests_ is that the configuration for something, either the Zend Framework, or one of the modules, or even the code calling the modules, is wrong. From what the strace showed, something is prepending the _library path_ and the _module path_ when looking for BaseUrl.php. The only **BaseUrl.php** is located at _/home/bolfox/public_html/application/libraries/Zend/View/Helper/BaseUrl.php_ and files that want to use it should be looking at the path relative to the Zend install, not the current module path.

An example of the strace you showed shows the path as:

```
/home/bolfox/public_html/application/libraries/PEAR//home/bolfox/public_html/application/modules/Sitestoreoffer/View/Helper/BaseUrl.php
```
This path appears the be the _path to the library_ + _path of current module_ + _path to BaseUrl.php relative to the Zend directory_. I'm guessing that for some reason, the modules that are throwing errors, like Sitestoreoffer, do not have the correct include paths when using functions from other files.

This is an issue with either the Zend Framework installation, or the Modules that are installed. Unfortunately, we do not support 3rd party software and installations. We do always try to assist with any issue though, under our "best effort support" policy. Unfortunately, with the amount of unfamiliar code and configurations of the Zend Framework and Modules, this is appearing to be beyond what we can offer for "best effort support".

I would suggest that you have a developer check over the code to find where the include paths are mis-configured. I will continue to see if I can find anything regarding the mis-configured paths but I cannot guarantee any results. If you have any questions, comments, or concerns, please feel free to let me know.

Trevor Kulhanek
Linux Support Admin
=================================================

**Comment by pulsatemedia** [comment]
Maybe you can start with the development group of the site offer plugin (I can't recall who it is) and go from there?

In my experience, QC (or near total lack of) with third SE developers is frustrating to say the least. I'd rather they charged more and just put out quality, well tested code. So my guess is that its a third party plugin issue, question is which one(s)

**Comment by meetgerry** [comment]
Would you be able to help me align everything if yes, how do I reach you?

**Comment by pulsatemedia** [comment]
Just open a ticket with SEAO, say you're having problems and ask them to look at that php file and go from there.

**Comment by meetgerry** [comment]
Thanks, done!
