### ISSUE TITLE
Static File Base URL - Does Not Read All URLs

### ISSUE THREAD

**Issue by meetgerry** [SocialEngine/phpv4-issues#272]
My CDN company has reported that SocialEngine CMS does not support "Static File Base URL" fully. All third party plugins and folders like the following are not served through the Static File Base URL:

https://website.com/application/modules/third-party-module-files
https://website.com/public/
https://website.com/widget/

Why is this left unattended?

P.S. And please do not close issues without flagging to work or a solution.

**Comment by meetgerry** [comment]
Some of the example files are listed below. All thrid-party modules files are not being served.

https://bolfox.com/application/modules/Hebadge/externals/scripts/core.js?c=2568
https://bolfox.com/application/modules/Hecore/externals/font/fontawesome-webfont.woff?v=3.2.1
https://bolfox.com/application/modules/Inviter/externals/scripts/core.js?c=2568
https://bolfox.com/application/modules/Vklogin/externals/scripts/vkcore.js?c=2568
https://bolfox.com/application/modules/Ynbusinesspages/externals/images/nophoto_business_thumb_profile.png
https://bolfox.com/application/modules/Ynbusinesspages/externals/scripts/wookmark/jquery-1.7.1.min.js
https://bolfox.com/application/modules/Ynbusinesspages/externals/scripts/wookmark/jquery.wookmark.min.js
https://bolfox.com/application/modules/Ynbusinesspages/externals/styles/font-awesome.css?c=2568
https://bolfox.com/application/modules/Yncontest/externals/scripts/core.js?c=2568
https://bolfox.com/application/modules/Ynmember/externals/styles/font-awesome.css?c=2568
https://bolfox.com/application/modules/Ynvideo/externals/scripts/iscroll.js?c=2568
https://bolfox.com/chat/cometchat_check.php?callback=jqcc17100021531989332288504_1442506771657&init=1&basedata=null
https://bolfox.com/chat/cometchatcss.php
https://bolfox.com/chat/mp3/beep.mp3
https://bolfox.com/public/admin/Fox.png
https://bolfox.com/public/intro/css/common.css
https://bolfox.com/public/intro/css/styleen.css
https://bolfox.com/public/intro/css/styleintroen.css
https://bolfox.com/public/intro/css/styleintroru.css
https://bolfox.com/public/intro/css/styleru.css
https://bolfox.com/public/intro/js/modernizr.custom.79639.js

**Comment by pulsatemedia** [comment]
Re /public, I think you might have a plugin problem with "intro"

My SE filesystem is configured to use S3+ Cloudfront which points to a subdomain of static.domain.com. Everything in /public that ive noticed, gets pulled from a url  of static.domain.com/public as it should

I wonder if the "intro" plugin is not setup to use the SE storage path, and is programmed to expressly use the URL if site/public/intro
I've seen this with a couple of third party plugins where they weren't developed to use your SE storage location.

On application and other folders, a CDN should be able to cache these files on their edge servers anyway, without requiring a specific url or subdomain.

Sidenote.... I've found cloudflare to be the most effective CDN with SE over the last couple of years. I have no affiliation with them, just calling it as I have experienced it.

**Comment by meetgerry** [comment]
Thanks, since I am targetting users from CIS, Russia & Ukraine these guys have plenty POPs around these areas.

I do not have any plugin by the name "Intro" installed. "Intro" is an independent folder. I am not worried about the Intro folder or files.

What worried me the most is everything that is in /application/modules/ and the /public folders are not being  served.

**Comment by meetgerry** [comment]
Could some explain why do I have an URL like this always which slows 50% of the site loading?

https://website.com/?c=2624?c=2624

**Comment by Anshuse** [comment]
Hi @meetgerry , 

Please be noted that "CDN" and "Cloudfront" are two different features. Using CDN, that you've implemented on your site, only static files i.e css, js etc. of website get stored on cloud server. And using "Cloudfront", user uploaded content i.e photos, music, videos etc. of website get stored on cloud server.

Now, as you've implemented CDN on your site but css and js files of your sites' third party plugins are not getting stored on cloud, so you should contact the corresponding developer of those plugins to make sure that they have included their plugins' css, js files as per the default standards of SocialEngine.

If any css/js files of our core modules are not getting stored on cloud then please let us know.

Thanks!

**Comment by meetgerry** [comment]
I am sorry Anshu, I mispelt. It is not Cloudfront, it is Cloudflare.

**Comment by pulsatemedia** [comment]
@meetgerry, can you explain the rationale behind those URLs causing a severe performance hit?

**Comment by pulsatemedia** [comment]
Cloudfront IS a CDN, however it only caches content that you have stored on Amazon S3

**Comment by meetgerry** [comment]
Please see the 2 screenshots. That link is adding on to the delay.

![screenshot2015-09-1283](https://cloud.githubusercontent.com/assets/8540750/10021125/163f5b44-614f-11e5-9a41-8b598ded66a2.png)
![screenshot2015-09-1282](https://cloud.githubusercontent.com/assets/8540750/10021124/1637f570-614f-11e5-91ac-cfb5a633e9bb.png)

**Comment by pulsatemedia** [comment]
Are you sure it's from SE core?

**Comment by pulsatemedia** [comment]
I just ran a test from Prague, I think that's the closest point for your demographic, even though it's not close perse.

http://www.webpagetest.org/result/150922_S2_WFR/

Looks like you have moved to cloudflare? 

Regarding request #100, https://bolfox.com/?c=2624

It's basically re-calling your root again url, which has a 3second TTFB.
Why this is happening or what is calling it is anyone's guess, but its very strange.
Its important to know that the slowdown is not related to the actual form of the URL with the number at the end, rather the address the URL is calling.
The good news is that it is not a "blocking" object, the other object for the page continue to load when you look at the waterfall.

You'll need to take a systematic approach to get to the bottom of the slowdown.
Start off by turning off your CDN.
Disable/Re-enable plugins, and add/removing widgets in a controlled manner and documenting the results will give you some ideas on where the problem might lie. Ultimately is the 3second TTFB on your homepage is the main killer, its anything from 30%-50% of the total load time for your homepage.

Some good news, I also tested "find courses": http://www.webpagetest.org/result/150922_GP_YJN/1/details/
The TTFB was better at 1.7s, thats still pretty bad, but it's a clue that there is something on your homepage that magnifying issues. 

You could make a copy of your homepage in SE admin panel and experiment with widgets to see if one in particular is causing problems by observing your TTFB

Normally I'd say OpCode caching could throw your figures off, but with the TTFB being so stable around 3 seconds I think you can rely on your results.

This is of course, assuming your server is up to the job of hosting SE successfully.

**Comment by meetgerry** [comment]
Thanks all! I identified the problem. Its being created by the Younetco's Business Page module.

I have notified them of the issue.

**Comment by pulsatemedia** [comment]
Nice job. Glad you found the source of the issue. Keep us posted on the response from YN and the outcome.
