### ISSUE TITLE
Translate is not working in Core plugin js file.

### ISSUE THREAD

**Issue by vjgarg2** [SocialEngine/phpv4-issues#273]
I have added below code in js file at file path: /application/modules/Core/externals/scripts/core.js

alert(en4.core.language.translate("THIS IS FOR TEST ONLY.")); around line 576

I have added "THIS IS FOR TEST ONLY." text on core.csv file, but it is not working.

![image](https://cloud.githubusercontent.com/assets/6785287/9957460/dafbc4d4-5e1d-11e5-8a44-81f2e217f9cb.png)

**Comment by Anshuse** [comment]
Hi @vjgarg2 ,

The way using which you've used translate function works fine if used in .tpl file and php file but to use the translate function in .js file, you need to define the code in the corresponding .tpl file also.

For example,  in file ```/application/modules/Core/externals/scripts/core.js```, we've used translate function for the phrase "Are you sure you want to delete this?" ((line no. 619), as below:

```
deleteComment : function(type, id, comment_id) {
    if( !confirm(en4.core.language.translate('Are you sure you want to delete this?')) ) {
      return;
    }
```

and we've also defined this phrase in corresponding .tpl file i.e 
```/application/modules/Core/widgets/comments/index.tpl```  in following way:

```
<?php $this->headTranslate(array(
  'Are you sure you want to delete this?',
)); ?>
```

Thanks!

**Comment by vjgarg2** [comment]
Thanks
