### ISSUE TITLE
File & Media Manager and Layout Manager Improvements

### ISSUE THREAD

**Issue by inkyj** [SocialEngine/phpv4-issues#276]
I've noticed a couple other people have mentioned this in threads, but I wanted to put out a specific request for an enhancement to the File and Media Manager.  We've been using SocialEngine for a couple of yeas now, and now that we have a lot of files in there the file manager is just an absolute nightmare to use.  

We have hundreds of files in ours and there is absolutely no way to find anything in there.  Even immediately after I upload something, I'm still unable to easily do something extremely simple, like get the URL for the file I just uploaded. It immediately puts the file in alphabetical order so after I've uploaded something new, I have to manually click through dozens of pages to try to find a file that I just uploaded.

As you might imageine, when you need to do this with multiple images, it's extremely frustrating. We waste so much with this.

It's not even convenient enough to properly put things in order alphabetically. It'll list some of our files alphabetically, and then once it gets to Z, it starts at A again with new files that weren't in the list the first time I looked through the files.  Why would it have multiple alphabets? 

Making things even more difficult, there is no pagination.  If I upload a file that starts with z, I have to click through 15 pages of files before I can get my link.  And then if I miss it, 
I can't even jump back to the 1st page of results.  Instead I need to manually go back through every single page, one by one. It's an absolute nightmare of a process when all you want to do is upload something, and then get a link for it.

Some way to more quickly sort through the files and search through them is needed quite badly.

Also, an improvement to the Layout Manager is also needed... specifically the portion where you choose which page to edit. We have a ton of pages, and again, there's no way to search through them.  It's not nearly as bad as the File & Media Manager since you can at least scroll through all of the files at once, but you can't easily see what the content is once you've opened a page. I've literally spent hours looking for a single file to see where I needed to go to make a change.  Again, it's a frustrating experience to have to waste hours on something that should be extremely simple.

I've been hoping to see an improvement to both of these issues ever since I started using SocialEngine, but nothing has changed. Hopefully it'll be possible to get these changes in line for a future update.

Thanks!!

**Comment by Anshuse** [comment]
Hello @inkyj ,

We've a list of improvements that we're going to do in our future release and some of those improvements are for the Admin site as well. We're going to work on some of those implements in next version and others are planned for later versions. We're forwarding your suggestions to our team and will try if those can be included in coming upgrade. Thanks!

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#14

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
