### ISSUE TITLE
Enable Follow Only Feature

### ISSUE THREAD

**Issue by TheGreatAlexander** [SocialEngine/phpv4-issues#277]
What I understand following is:

 when you want to see a person's updates but you aren't actually friends. You see their posts, but they don't see yours. It's an easy way for fans to follow celebrities or public figures, without that person needing to respond in kind.

Could you develop such feature?

**Comment by Anshuse** [comment]
Hi @TheGreatAlexander , We've provided one such feature where you can follow any member of your site and you will see all of their activity feeds, without being friend with him and that such feature is "One-way friendship". You may enable one-way friendship can from "Admin" > "Settings" > "Friendship Settings" section of your site.

![friendship_settings](https://cloud.githubusercontent.com/assets/11085507/10193005/e796a6ee-679d-11e5-9009-b8b2d23f5623.png)

Thanks & Regards,
Anshu
