### ISSUE TITLE
Static File Base URL - Not Working

### ISSUE THREAD

**Issue by meetgerry** [SocialEngine/phpv4-issues#279]
Static File Base URL does not read all the files in public folder, and all third party modules.

Why is that?

**Comment by Anshuse** [comment]
Hi @meetgerry , Please be noted that if you've implemented CDN on your site so only static files like css and js files get stored on cloud front. If you want to store user uploaded content i.e. images, music etc. of your site on cloud server then you will need to implement S3 Storage service on your site. 
Thanks!

**Comment by meetgerry** [comment]
I understand and agree with what you meant. I am only referring to the static files like JS or CSS files which serve from third party modules are not being served from the CDN. See screenshot below:

![screenshot2015-10-1366](https://cloud.githubusercontent.com/assets/8540750/10370248/a412e3b6-6de6-11e5-8091-03758ac08124.png)

**Comment by meetgerry** [comment]
No reply yet?

**Comment by Anshuse** [comment]
Hi @meetgerry ,

Please accept our sincere apologies for the delay in responding back to you!

As we've mentioned in issue #272 that "as you've implemented CDN on your site and if css and js files of your sites' third party plugins are not getting stored on cloud, then you should contact the corresponding developer of those plugins to make sure that they have included their plugins' css, js files as per the default standards of SocialEngine.

If any css/js files of our core modules are not getting stored on cloud then please let us know."

Thanks!

**Comment by meetgerry** [comment]
Why do allow such modules which do not meet the bare standards of SE be promoted on your website?

**Comment by Anshuse** [comment]
Hi @meetgerry ,

We understand your concerns. As you must be knowing that we're soon going to launch a new website along with marketplace. With that new website, we're putting strict certification in place and such plugins would not be able to pass the quality check. I'm sure that would help SocialEngine site admins choose and use right plugins on their websites.

Thanks!
