### ISSUE TITLE
VigLink Won't Verify in 4.8.8

### ISSUE THREAD

**Issue by MiamiShade** [SocialEngine/phpv4-issues#28]
VigLink won't verify in settings as per tutorial/instructions in 4.8.8.  Required meta tag in scripts to verify - worked in 4.8.7

**Comment by smazurov** [comment]
both this and #27 sound very odd, nothing changed between those 2 versions to affect either functionality, it takes a bit to verify, can you verify analytics code and viglink id are missing in "view source" of a 4.8.8 install but are present on 4.8.7?

**Comment by MiamiShade** [comment]
Will do update soon

**Comment by MiamiShade** [comment]
View Source Code shows the VigLink ID # it just wont verify at VigLink should I consider this a VigLink issues then? As well as Google ID

**Comment by smazurov** [comment]
Yup, sounds like a problem with GA/VL configuration on their end.
