### ISSUE TITLE
Who is online - Ehancement

### ISSUE THREAD

**Issue by SpiritWolfie** [SocialEngine/phpv4-issues#282]
After testing this over and over and over, I can say that I believe the who is online function should be re-designed to work allot easier..

As it stands the way it functions is based on the both the server time/and the time on php info/ and the time on the server box (From what I can tell/has been explained to me by a few coders)

because of this, it keeps breaking on both my main website and our fresh install website, and most of the time we can't get it to show users online correctly, 

A example would be, I'm logged in and so is my staff team, but its only showing 3 people, (even know we have the option to allow your stuff to be hidden turned off), yet I know theirs more then 3 people online because they are sitting on the page at the wall feed, including myself and my staff team

I have tested this without any plugins installed and always have a issue with it not wanting to function correctly no matter what we do.

My suggestion is simple, Take out the requirements for this function to work based on correct time zone set ups and what not, Just have it pull from the online list and list the users.

(And yes our timezones match the php/serverbox/and social engines time and this still happens)

The picture with the tab container is the one from the members home page
The picture with the tabs shows the online tab is missing.

![members home page blocks](https://cloud.githubusercontent.com/assets/9712738/10564703/2b020338-7572-11e5-8fff-137bfd5ae0d3.JPG)
![no tab display of online users](https://cloud.githubusercontent.com/assets/9712738/10564704/2b033a00-7572-11e5-9e7c-b3a00e9c336e.JPG)
![online users block](https://cloud.githubusercontent.com/assets/9712738/10564705/2b03fdbe-7572-11e5-99cf-3c1331ea6132.JPG)

**Comment by Anshuse** [comment]
Hi @SpiritWolfie , Chat function works well in SocialEngine, we suggest you to check this issueon your site by following the steps mentioned here: http://support.socialengine.com/php/customer/portal/articles/2170953-online-friends-are-not-being-shown-in-chat-bar

Thanks!

**Comment by SpiritWolfie** [comment]
Howdy Anshuse, I'm not talking about the chat tab, or the chat function at all, if you re-read my thread

I am referring to the "Who is online tab" the block that shows you a list of all the users online at the moment. even on my fresh dev site I can't get it to work correctly. it will show a couple people up to like 3 even know I have 10 selected.

**Comment by Anshuse** [comment]
Hello @SpiritWolfie ,

Apologies for the delayed response. We've checked this issue on our [Demo](http://demo.socialengine.com/) site and found that all the users that are online at a time get listed under this widget. Screenshot from our Demo site:

![online_members](https://cloud.githubusercontent.com/assets/11085507/11240462/0ba6e494-8e19-11e5-98be-f29f4d9e29be.png)


You may also check this on our  [Demo](http://demo.socialengine.com/) site. Also, we've discussed with our development team and server time/phpifo time etc. is not considered while displaying online users. As this issue exists specifically in your installation so, you may file a support ticket and our support team will guide you.

Thanks!

**Comment by SpiritWolfie** [comment]
I'm going to re-open this, I have installed multiple Dev copy's of social engine, without any plugins etc installed and still having issues with with the "Online user" tab not working correctly

I have followed every guide you have to a T from settings to how to install it etc, I own the server box it is on, so I'm not going though some hosting company that got restricted settings or options

As it stands, it will not show most people online, including myself, it shows 2 people when I have it set to 15, out of the 2 people it shows , it refuses to list I'm online even know I'm staring at the page, refreshing it does not make it show me ether

If you still insist its something wrong with my configuration can you please tell me what I'm doing wrong, or how it needs to be display all people, cause even on the newest update that social engine just released I'm still having this problem
