### ISSUE TITLE
Category & sub-category selection

### ISSUE THREAD

**Issue by meetgerry** [SocialEngine/phpv4-issues#283]
Have you guys thought how could an user select from one single dropdown that lists both the categories and subcategories and at the same time when the count of them are in hundreds and thousands?

If you look at some of the SEAO modules, when you add an item, they have the option of selecting categories first and based on the first-level categories selected, the second level categories are auto-populated and listed as a separate dropdown menu.

This should be part of the core feature when it comes to your videos, groups, events or so called any modules.

As of now if you add a long list of categories and subcategories, it looks like a garbage bin.

**Comment by Anshuse** [comment]
Hi @meetgerry , Thanks for your feedback, I've added your suggestion in our internal suggestion tracker and our team will take required action on this to implement in our core modules. Thanks!

**Comment by meetgerry** [comment]
Is this assigned for the next release?
