### ISSUE TITLE
File & Media Manager Links Issue

### ISSUE THREAD

**Issue by GarfieldS** [SocialEngine/phpv4-issues#284]
I have a social engine client who uploads images in the "File & Media Manager" so she can post them in her "Rich Text Block". She has had issues with the images not displaying. It was a little tricky troubleshooting this issue but I think we discovered what the bug is. 

She would upload a photo for instance called  "2015-10-09-aeiknatphzcu.jpg" (it would be a computer generated name)

She would then want to rename it to something meaningful for her to identify and name it something like "featured member on my site" (there would be spaces in the name) and save it. 

Social Engine would rename the image "featured member on my site.jpg" and render it for her but sometimes not for people visiting on the site because of the spaces in the URL. Sometimes it would work with spaces and sometimes it would not. 

I initially contacted the host because I thought it was an issue with them not saving the picture but they confirmed and said the following: 

> "Hi, problem is in SE, when you upload images with space, SE will not convert these spaces to anything and when you use image browsers in most cases will try to recognize spaces and load image but this is not case always."

I would classify this as a bug as Social Engine should reject renaming images when the name has a space. I also understand this is a bit of user error as well as admins should know image names should not have a space but Social Engine should prevent it for those who might be unaware or forget. 

The window that pops up gives no warning and makes it look like you could write whatever you want. 
The name title might also be a bit misleading in case users might think of "Page title" or "Alt" when it is probably better called "image name" and I understand this is a convention of these types of pop up boxes. 

![image issue](http://i778.photobucket.com/albums/yy64/capaquarius/Social%20Engine/imageissue.jpg)

**Comment by DonnaScriptTechs** [comment]
I've tested this in 4.9.0 and we've made some changes. Please test when we release that version and if you still have the issue, please open a new bug report.

**Comment by Elshara** [comment]
Awesome!
