### ISSUE TITLE
Signup Process does not notify SuperAdmin that Member Must Be Approved

### ISSUE THREAD

**Issue by auntialias** [SocialEngine/phpv4-issues#286]
SE 4.8.9 — When the site's signup process is configured so that New Member must be approved (and notify Site Admin), the site does NOT notify the admin that there is the need to approve new members.

When signup settings are set up so that these two conditions exist, there is failure:
AutoApprove = NO 
Notify Admin = YES
(see screenshot, at bottom)
## Built to fail.

The workflow, as is, IS BUILT TO FAIL. 
- There is no dedicated email notification to tell Admin/SuperAdmin "You must approve this member." 
- The only message template is a "you got a new member, click link to welcome them." template. (And hey, doesn't that sound like it's optional? We think welcoming a new member is a good idea. Not OMG go there now or else you're going to LOSE a new member)
### You are forcing new admins to become deep experts before they can begin.

You are requiring that a brand new administrator of your site must know far too much about how everything works, and multiple detailed consequences of what to do. 
1. New Admin MUST KNOW to edit **Admin Signup Notification** template. 
2. New Admin MUST KNOW how to edit a template to ensure success on ongoing basis. 
   From "Go here to welcome them"  
   To "You must approve this member for that person to be able to use the site."
3. New Admin MUST KNOW where to navigate to on an individual Member Profile page in order to do approval there. 
   OR
4. New Admin MUST KNOW how to write a different URL in order to go to Member Management area.
   http://[host]/admin/user/manage  
   Or wait. Should that slash be there after [host]?  _edited to add: **YES!**_  
   ~~Maybe it MUST be this:~~  
   ~~http://[host]admin/user/manage~~  
   Yes, in order to create a template that actually works, your New Admin must know even more!!!
5. Later on, suppose for some reason the Admin decides to change the signup process to NOT require approval but to YES notify the administrator. Now the ADMIN MUST KNOW how to revert all that text back to its original form. 
## HOW TO FIX

Fix the missing template so that there is a Dedicated mail template that is sent to Admin when New People Sign Up and Need To Be Approved. 
## Screenshot depicting conditions set the site up for failure.

![signup-process-se-bugreport](https://cloud.githubusercontent.com/assets/1919971/10720500/135e5d38-7b55-11e5-8e46-d2d245683dc8.png)

**Comment by GarfieldS** [comment]
You explained this clearly.

**Comment by Elshara** [comment]
Yeah this is something that we need.

**Comment by Anshuse** [comment]
Hi @auntialias , We've added your point in internal bug tracker for our internal team discussion.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#15

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
