### ISSUE TITLE
BUG - Deleting member

### ISSUE THREAD

**Issue by swishemart** [SocialEngine/phpv4-issues#288]
Fatal error: Call to a member function getNextCollectible() on a non-object in /home/USER/public_html/application/modules/Core/Model/Item/Collectible.php on line 54

Ideas? (Running 4.8.9)

**Comment by Anshuse** [comment]
Hi @swishemart ,

If you're getting this error while attempting to delete a particular member then issue might be that an album for that user is deleted, however a photo for that album is not deleted, which might be causing this  issue. If you've knowledge of database then you need to delete the photo from database manually and if not, then you may open a support ticket and our support staff will help you!
Thanks!
