### ISSUE TITLE
Support HTML Player

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#289]
It would be nice to support a responsive html5 music and video player and or photo slideshow area.

**Comment by Anshuse** [comment]
HI @Elshara, 

- Regarding "html5 video player":
"html5 video player" is already supported in SocialEngine.

- Regarding " html5 Music Player":
We've forwarded your suggestion regarding html5 Music Player to team for internal discussion.

- Regarding "photo slideshow":
There're some third party plugins based on Slideshows so, you may check out such plugins from http://www.socialengine.com/customize/se4/plugins

Thanks!

**Comment by socialengineaddons** [comment]
Hi @Elshara, 

You may have a look at [Advanced Slideshow Plugin - Multiple Slideshows](http://www.socialengineaddons.com/socialengine-advanced-slideshow-plugin-multiple-slideshows) this plugin enables creation of multiple, different, rich slideshows on your website, that can be used for various things like content highlighting, feature introductions, advertisements, etc. All slideshows created with this plugin look perfect on all screens sizes, and work well on all mobile and desktop browsers.

**Comment by Elshara** [comment]
Thanks for the information. HTML5 music player would definitely be
useful for social engine. Speaking of which, default social engine
chat uses a flash player, it would be nice to update that.
