### ISSUE TITLE
Unable to change page URLS 

### ISSUE THREAD

**Issue by MiamiShade** [SocialEngine/phpv4-issues#29]
Every time I attempt to change in layout editor edit page info URL I get different errors. Error Code: 1f8485 or 58b694 referring to this, I know it says duplicate entry however what ever URL I
Select will not work. 
We're sorry!

We are currently experiencing some technical issues. Please try again or report this to your site administrator using the contact form.

Administrator: Please check the error log in your admin panel for more information regarding this error.

Error Code: 9b81b4

exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Duplicate entry 'Playground' for key 'url'' in /home/fetdaddy/public_html/application/libraries/Zend/Db/Statement/Mysqli.php:214
Stack trace:
#0 /home/fetdaddy/public_html/application/libraries/Zend/Db/Statement.php(323): Zend_Db_Statement_Mysqli->_execute(Array)
#1 /home/fetdaddy/public_html/application/libraries/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 /home/fetdaddy/public_html/application/libraries/Zend/Db/Adapter/Abstract.php(635): Zend_Db_Adapter_Abstract->query('UPDATE `engine4...', Array)
#3 /home/fetdaddy/public_html/application/libraries/Zend/Db/Table/Abstract.php(1133): Zend_Db_Adapter_Abstract->update('engine4_core_pa...', Array, Array)
#4 /home/fetdaddy/public_html/application/libraries/Engine/Db/Table.php(161): Zend_Db_Table_Abstract->update(Array, Array)
#5 /home/fetdaddy/public_html/application/libraries/Zend/Db/Table/Row/Abstract.php(573): Engine_Db_Table->update(Array, Array)
#6 /home/fetdaddy/public_html/application/libraries/Zend/Db/Table/Row/Abstract.php(448): Zend_Db_Table_Row_Abstract->_doUpdate()
#7 /home/fetdaddy/public_html/application/modules/Core/controllers/AdminContentController.php(403): Zend_Db_Table_Row_Abstract->save()
#8 /home/fetdaddy/public_html/application/libraries/Zend/Controller/Action.php(516): Core_AdminContentController->saveAction()
#9 /home/fetdaddy/public_html/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('saveAction')
#10 /home/fetdaddy/public_html/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 /home/fetdaddy/public_html/application/modules/Core/Bootstrap.php(83): Zend_Controller_Front->dispatch()
#12 /home/fetdaddy/public_html/application/libraries/Engine/Application.php(160): Core_Bootstrap->run()
#13 /home/fetdaddy/public_html/application/index.php(211): Engine_Application->run()
#14 /home/fetdaddy/public_html/index.php(24): include('/home/fetdaddy/...')
#15 {main}

**Comment by Anshuse** [comment]
Hello @MiamiShade ,

This is not a known issue in our core module. To enable us look deeper into this problem specifically on your website, please open a support ticket along with the details of your website and our support team will help you further.

Best Regards,
Anshu
