### ISSUE TITLE
Add More File Formats

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#290]
Add more file formats to the music and video section example mkv avi flac m4a m4b ogg.

**Comment by Anshuse** [comment]
Hi @Elshara , we would like to tell you that when a video with any format is uploaded on site then that video gets converted into MP4 so, doesn't matter which format of video you upload on your site, all will be supported as it will get converted into mp4. If you need any further features in Video plugin then there're some third party plugin related to advanced videos and you can check out those plugins. Thanks!

**Comment by socialengineaddons** [comment]
Hi @Elshara, 

We will be releasing **Advanced Videos / Channels / Playlists Plugin** in the coming days. Using this plugin users will be able to upload/embed videos on the website from multiple sources like: YouTube, Vimeo, Dailymotion, My Computer, etc. You may go through this blog post link for more info: http://www.socialengineaddons.com/content/upcoming-release-november-advanced-videos-channels-playlists-plugin

**Comment by Elshara** [comment]
sounds like a really cool idea. I'll take a look at that.
