### ISSUE TITLE
Easier Sign Up Routine

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#292]
For years social engine has had a multiple step process for members to sign up and complete all steps before creating their account. It would be nice to have all such steps on custom pages, where admins can define what pages are included based on the need of the site. For example, making a wrong choice such as putting profile photo first or invite friends instead of create account, will return an error. It would be better to have everything either listed on 1, 2, 3, 4, 5 or 6 and more pages depending on the site need. For example, having profile photo and user information on one page, or create account and user information on one page, would be easier than having it all be done separately. For a site that only has a few profile questions, a user photo and account creation, may only want one page of forms to be filled out. It would be ideal to include a redirection manager on sign up as well so if someone signed up during the middle of performing an action, they would be able to complete it once finished.

**Comment by auntialias** [comment]
+1 for being able to identify the page for creating profile and place help text on it. Esp the first go-round.

> _possible Create a Profile help text (that appears ONLY during signup)_: Yes, we know. You're _already_ a member of this organization, and now you have to fill out a profile? What, again? We get it. We do. The questions here will help identify you to other members of [name of organization]. Sorry to make you go through this kind of thing again. We made it as quick as possible. Promise!

A feature like the one @Elshara described would help to make a social network act, you know, more **social**. More **human**. Please give us the technical ability to make our network more human.

**Comment by Elshara** [comment]
I think simple solution for this would be to choose the order on one page of what gets added to the create your account page, one form, one page and you're in.

**Comment by Elshara** [comment]
I also like what you've described adding custom widgets to the create an account page.

**Comment by auntialias** [comment]
I recently changed the layout of the Signup Page (there is a Page Layout for that) so I could add some help text at the bottom to guide new users through choosing different Profile Types (I've had the experience of being a bit confused at the very! beginning! of! signing! up! for a SE site w/ pop-up menu to select one Profile Type. Someone who's on the fence between going forward or bailing might bail in a situation like that where the significance of the choices aren't clear.)

**Comment by Elshara** [comment]
I find the most troublesome part for users to fill out is profile
address. I can't get rid of it so they can actually put their name in
that field with space support for multiple world like John Smyth
instead of johnsmyth123.

**Comment by Elshara** [comment]
I mean if there was actually a way to make the profile information
appear on the same page as the email and password then you'd think
it'd be easier to just add name changes there. The whole concept of
profile address is so very outdated because it acts not only as a
username, but also as a secondary id. If members could connect using
their profile id but change their profile address later, that would be
the best compromise. right now however, they can't even put a space in
their name and a particular name can only be used once unless they
fill out their display name under profile information.

**Comment by Elshara** [comment]
There may be a way to get around this using a core file code edit.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#16

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
