### ISSUE TITLE
Add HTML To Status Updates

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#293]
Currently status updates do not display html.

**Comment by Anshuse** [comment]
Hi @Elshara, currently when HTML tags are used in the Activity Feed then tags get stripped off and it's because if we allow HTML tags then Layout of Activity Feed/ Wall will get uncertain.

**Comment by Elshara** [comment]
I thought there was a setting to allow html in activity feed. If so,
status updates should follow but they do not.

**Comment by Elshara** [comment]
Besides it's academic. When ever people posts links, they always
appear in the status update area. Links that are posted appear as raw
code in other areas where the status updates are displayed. There is
no independent way to sort links from updates, and more importantly
there is no way to add a link posted as an update to any of the
following areas. Photos, videos or blogs. If someone posts a status
update, there should be an archive of where that update entry is
found. Unfortunately there is not, and what with links only appearing
in the activity feed that actually work correctly, allowing html
displayed in a status update effects more than just the feed, it
effects the member browse section, friends and profile pages, a lot of
group pages like the member management page and events same idea.
People need more control when they post to the feed, they must have a
clear direction where their posts go if they want to access them
later. Currently this isn't possible.

**Comment by Elshara** [comment]
Feed updates require a better layout. I suggest adding a feed layout
manager to the activity feed settings page which members can customize
what gets put in the feed along with how it displays, time first,
content title or description first, liking and sharing if available
first and whether or not the feed can be grouped into custom tabs like
members, friends, status updates.

**Comment by DonnaScriptTechs** [comment]
HTML in the activity feed could be a security concern. I had my own site with another script injected from html in the feed when I didn't realize it was enabled. Please have a developer do this for you.
