### ISSUE TITLE
Add Custom Fields For Modules

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#294]
Add custom fields for blogs, forum discussions, comments, groups and other areas. Currently only the classifieds and profile information have this functionality. This would be useful for attaching files or adding more information to blogs. It would also make it that much harder for spammers to create blogs if they are automated because they would have to if set up to do so, fill in required fields like a check box or correct information to post. This way for example, if you added a check box to a user status field, members could be required to click it in order to post.

**Comment by Anshuse** [comment]
Hi @Elshara, thanks for the suggestion, we've forwarded it to our team our internal discussion on this.

Thanks!

**Comment by socialengineaddons** [comment]
Hi @Elshara  We have a "Profile Fields" section in our various content plugins like [Advanced Events Plugin](http://www.socialengineaddons.com/socialengine-advanced-events-plugin), [Directory / Pages Plugin](http://www.socialengineaddons.com/socialengine-directory-pages-plugin), [Groups / Communities Plugin](http://www.socialengineaddons.com/socialengine-groups-communities-plugin) using which additional info can be added to the content.
User can create custom profile fields for pages/groups/events etc. and they can also associate mappings between categories and page profile types from the "Category-Page Profile Mapping" section, such that profile fields are available to pages based on their categories. 

Best Regards,
SocialEngineAddOns

**Comment by Elshara** [comment]
That's cool, but that isn't the feature I'm looking for. I'm looking
for the ability to add extra profile types and fields to all default
social engine modules that support an archive of content like
comments, statuses, forums, blogs, photos, videos, groups, events and
classifieds. Classifieds already supports this idea. I'd like to ask
for an improvement in being able to add the ability to upload a file
as apart of an option to add data not just text.
