### ISSUE TITLE
Add Modules To Registration And Login Page

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#296]
Currently there is no way to customize the registration or login page apart from css. It would be nice to add html blocks to such pages or perhaps have ads placed there very useful for site branding.

**Comment by Anshuse** [comment]
HI @Elshara , "Sign-in" and "Sign-up" pages are already available in "Admin"> "Layout" > "Layout Editor" section and you can edit these pages at your end as per your requirement. Thanks!
![layout](https://cloud.githubusercontent.com/assets/11085507/10813452/355f45a8-7e45-11e5-8fa2-b6338673d54b.png)
