### ISSUE TITLE
Customize Content Areas

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#297]
When ever you view the layout editor, often times you'll come across something labeled content. IT would be nice to edit such things as perhaps its title or the fields contained within. For example, on the browse members page, there is no way to sort members by anything other than last login but if you go to a template file, you can customize everything about how they are displayed. IT would be nice to do the same in such a setting option for content areas.

**Comment by Anshuse** [comment]
Hi @Elshara, this feature is already added in the improvements' list at our end and we'll work on this near future upgrades.
