### ISSUE TITLE
Add Custom Tabs To Activity Feed

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#298]
The activity feed should show tabs for whatever you want to place there. It would be nice if members could sort tabbed feeds into their own lists if they want to. That way members could customize what settings they want to look at when ever they view the feed if it is enabled under admincp for them to change such settings.

**Comment by Anshuse** [comment]
Hi @Elshara, currently we don't have any plan to implement custom tabs in the core Activity Feed but there are some Advanced Activity feed based plugins so, you can check out those plugins if they meet your requirements.
Thanks!

**Comment by socialengineaddons** [comment]
Hi @Elshara,

We have [Advanced Activity Feeds / Wall Plugin](http://www.socialengineaddons.com/socialengine-advanced-activity-feeds-wall-plugin)  using which users can create custom lists for filtering activity feeds on their wall. You may check this at our demo: https://demo.socialengineaddons.com/ by logging-in to any of the test accounts. 

Best Regards,
SocialEngineAddOns

**Comment by Elshara** [comment]
Thanks for the information. I'm not looking for something with lots of
features, I'm simply looking for a basic idea that allows lists to be
created so people can quickly browse things important to them such as
their own content from main content or friends content.

**Comment by socialengineaddons** [comment]
@Elshara, We're not sure of that whether you had a look at our demo for this or not. But, using [Advanced Activity Feeds / Wall Plugin](http://www.socialengineaddons.com/socialengine-advanced-activity-feeds-wall-plugin) users can create their own custom lists by choosing content items and friends. For example: You can create a list containing Friend A, Friend B, Page A, Group A, Event A which are your work related items and call this list: Work.
![screenshot from 2015-11-03 18 28 32](https://cloud.githubusercontent.com/assets/5629155/10908573/b619b3a6-8258-11e5-98c0-09639e977cbf.png)

**Comment by Elshara** [comment]
I'll take a look thanks!
