### ISSUE TITLE
Add Content To Create Account Page

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#299]
Login and account creation pages don't actually have the ability to add widgets. It would be nice if this was possible.

**Comment by auntialias** [comment]
au contraire. The Signup Page _**does**_ allow addition of widgets. I just did that a day or so ago. Search the Page Layout menu for Sign-Up Page template.

**Comment by Elshara** [comment]
That's awesome! Thanks for the update I didn't see it there.

**Comment by shivani2910** [comment]
Hi @Elshara,

Yes, both "Sign-In" and "Sign-Up" pages are available for editing in Layout Editor. You can edit their layout from there.

Thanks,
Shivani
