### ISSUE TITLE
After Update to SE 4.8.7 Notice: Use of undefined constant E_DEPRECATED - assumed 'E_DEPRECATED'.. (Redmine Bug: #2665)

### ISSUE THREAD

**Issue by shivani2910** [SocialEngine/phpv4-issues#3]
## Bug: 

After SocialEngine is updated to Socialengine to 4.8.7, below  error message appears on website:

```
Notice: Use of undefined constant E_DEPRECATED - assumed 'E_DEPRECATED' in
/var/www/web57/html/Haustiercom/application/modules/Core/Bootstrap.php on line 40
What can i do?
```

## Solution:

This problem is coming because you're having a version of PHP less than 5.3.0.

This issue can be resolved by doing a quick fix. Please copy the contents of the files [Bootstrap.php] ( https://gist.githubusercontent.com/shivani2910/04d235f338d945326826/raw/7c95a47d1ef42e367f0ea86283a1b866e6739866/Bootstrap.php ) and [Scaffold.php] ( https://gist.githubusercontent.com/shivani2910/585faf2d66bc8a4651ff/raw/0c6ba5d51631d80d05371dbf8f1337cf9b5b6a8f/Scaffold.php ) and replace the existing files on your server at the below paths with these new files:

```
application/modules/Core/Bootstrap.php
application/libraries/Scaffold/libraries/Scaffold/Scaffold.php
```

Then, please check this issue again on your website and drop us a line in case the issue still persists.

**Comment by smazurov** [comment]
fixed in [4.8.8](http://blog.socialengine.com/2015/03/23/socialengine-php-4-8-8-released/)
