### ISSUE TITLE
Allow Members To Keep Their Content When Leaving Network

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#301]
When a member leaves, everything they have posted leaves with them including groups, forum activity, blogs, photos, music, videos, comments and their profile page. Members need the ability to optionally keep their content deciding what they should and should not take with them. If an active member leaves, anything they have contributed to or started gets removed automatically. There is no way to really set in permission settings whether or not their content can remain if they leave the site. Permissions settings do not offer the ability to customize how members can interact with content. What is needed is the ability to allow members to customize this so that it does not effect seo and other members.

**Comment by Anshuse** [comment]
Hi @Elshara, we don't have any plan to implement this particular feature but we do have a plan to implement a feature where user can deactivate his account instead of deleting it permanently. Using deactivate feature, your purpose will be accomplished to some extent.
Thanks!

**Comment by Elshara** [comment]
Excellent news.
