### ISSUE TITLE
Change Content Ownership

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#302]
When someone posts an item, it is always posted by its creator. Nobody else can manage it. True you can edit video titles, blog titles, comments on items, however when it comes to things such as groups, events and other items, they can only be managed by one person. Yes you can have admins, but you cannot have multiple owners. IT would be ideal to have an ownership manager for content that may require a change in future such as the ability to mange an inactive group or event. Such permissions would give administrators and or select members easier access to keep alive something already active, rather than having to start a new item. I think administrators of a site should have just as much access as a group or event creator does of that particular item, but as currently, we do not. Regular and administrative members alike have the ability to have ore control when it comes to update their content than administrators do when it comes to managing it on the spot. We need such access to regulate how our community functions because if a member needs to manage something and is having trouble and we cannot manage it from our end, that means someone who isn't allowed to manage something exclusively like someone on a potential ban list could easily ensure they have exclusive rights to such content by for example suspending an administrator from posting or viewing it. This is most noticeable in groups and events, but can also be seen in the blogs, photos, music, videos and forum sections along with polls and classifieds.

**Comment by Anshuse** [comment]
Hi @Elshara , this feature to change the content ownership already exists in some third party plugins like Advanced Groups and Advanced Events plugins but we're noting down your suggestion at our end to discuss with our team if we can add this feature in core modules also.

Also, for now we're closing all your suggestions related tickets and will re-open them again once we start working on them if they get approved.

**Comment by Elshara** [comment]
Okay that's cool. I do my best to bring life in new ideas to the platform.
