### ISSUE TITLE
View Private Messages

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#304]
IT would be nice to view private messages.

**Comment by Anshuse** [comment]
Hi @Elshara , we didn't exactly understand your point here. It would be great if you explain the point in a bit more detail. Thanks!

**Comment by Elshara** [comment]
Social engine doesn't have the ability for an administrator to view
private messages members send to each other.

**Comment by Anshuse** [comment]
@Elshara , we don't have any plan to implement this feature in our module and if you need this on your site then you may do code customizations at your end. Thanks!
