### ISSUE TITLE
Import Content Via Embed.ly

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#308]
Social Engine sometimes has problems importing content. Videos are a great example of this. Instead of pasting a url for youtube, it requires you to paste the full title and description and tags. If you wish to import content via a link, the same idea happens. Embed.ly vid.ly and other such services would solve this entirely.

**Comment by Anshuse** [comment]
Hi @Elshara , we've already replied to you regarding same query in #313 so, we're closing this one.
Thanks!
