### ISSUE TITLE
Add Support For HTML Uploader

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#309]
Currently you require flash player to upload anything. I think something like uploadify would work a lot better for social engine.

**Comment by Anshuse** [comment]
Hi @Elshara , we've a plan to improve HTML Uploader in a way that if Flash Player is not installed in browser then members should be able to upload a single photo at least but we will forward your suggestion to use Uploadify to our team for internal discussion.

Thanks!

**Comment by Elshara** [comment]
Thank you so very much! This would help in mobile when adding music
and videos as well. Also it helps when uploading packages.
