### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by ernie003** [SocialEngine/phpv4-issues#31]
We have been using SocialEngine for a little over three months now and we went live with it last month. The response has been tremendous since switching from Ning. I just have a few feature requests that I wish were in SocialEngine. 

1.	Email notification to all Super Admin notifying of a new sign up. Currently, email only goes to the “admin” user who I have deleted, so I don’t know where those emails are going now. Also, I’m pretty certain that the email comes after the new user has been approved and not when a user asks to sign up. I could be wrong about this, but in any case it would be great to get an email with a link to “Manage Members” that filters the not approved members. 
2.	Email testing for “Email All Members.” It would be wonderful to be able to see what an email looks like before it goes out. Right now, I had to create a separate membership level to do testing. 
3.	Ability to export the member list. I had to recently go through our list of 1,000 members and copy and paste their information into an excel sheet. It would be great to have an export button like how we have an “Approve Selected” and “Delete Selected.” If it could also include the stats for each member that would also be helpful!
4.	Ability to preview a Forum Post before it gets published. 
5.	Display profile updates on mobile site. I manually included Updates as a tab on our Mobile site so that users can approve friendships and see the activity pertinent to them, but how it renders is a little wonky. The icons are multiplied and covering the text. 
![mobile updates](https://cloud.githubusercontent.com/assets/11579371/7145663/c820a61e-e2a2-11e4-8d89-c15701d255ef.png)

6.	Ability for users to opt out of all emails in Settings>Notifications. This way they will not receive emails when we “Email All Members.” Again, I have created a separate membership level to exclude those wanting to be excluded. 
7.	Videos tab within an Event. We currently have a Photos tab but not one for videos.

**Comment by ernie003** [comment]
8. Ability to search and/or filter through the File and Media Manager. I have over 70 files currently and I have to go page by page to find what I need.

**Comment by shivani2910** [comment]
Hi @ernie003, 

Thanks for reaching out. Please find below our response regarding your queries:

1) An email is sent to the super admin (whose id is 1) when a member signs up on website. And since you can not delete Super admin, please check in Admin > Manage > Members section the email address of super admin (ID =1) and you'll be getting emails on that account. If you still have any issues, please feel free to contact our support team.

2) Thanks a lot for your suggestion. We've already mentioned in suggestion in out feature list for upcoming upgrades.

3) Thanks for this suggestion too. We've forwarded this to our team for internal discussion.

4) As you can see that we've provided a rich TinyMCE editor for compiling topics and posts in forums and there is already an option (an eye shaped icon) in the Editor tool bar to preview the content.

5), 6), 7), 8) and 9) Thanks for your suggestions. Forwarded these also to be considered in upcoming upgrades.

Please drop us a line in case of any further queries.

Regards,
SocialEngine Support

**Comment by ernie003** [comment]
Thanks @shivani2910! I was able to get #1 working and passed on #4 to the member who requested that. I have more suggestions :)

10. It would be nice to be able to label HTML and Rich text blocks, as well as Ad Campaign blocks. I stack a lot of these together and I have to open up a tab to edit the layout and a tab showing the actual page where it is displayed to make sure I am editing the right block. If I were able to edit the title of these blocks then there wouldn't be any second guessing. 

11. Being able to "favorite" pages in the Layout Editor would make it easier to find the pages I want to edit. I feel like there are only 4 that I really edit constantly. So if after "favoriting" them, ideally they would show up at the top of the list of pages.

12. More column layouts in the layout editor would be nice!

**Comment by maxx24** [comment]
+1 on the ability to export member email addresses.  I have 6500 members, and copying and pasting 10 at a time is laborious.

Also, in the manage members area, would like to see members who have deactivated their accounts.

**Comment by meetgerry** [comment]
I am not sure how many of you would want this, could you please provide us a way where we can choose how many members could be displayed per page while viewing members in the Admin page?

Currently its set to 10 and I have close to 1000 members and for some reason if I have to browse through members by page, its very tiring.

Could you please provide some quick fix as to how I could increase the count from 10 to 100?

**Comment by Anshuse** [comment]
Hello @meetgerry ,

To increase the number of Members being displayed per page in the ``` "Admin" > "Manage" > "Members" ```, you may do below changes at your end:

```In /application/modules/User/controllers/AdminManageController.php``` file, search below line (around line 78 approx):
```
$this->view->paginator = $paginator = Zend_Paginator::factory($select);
```

and add below line just above the code mentioned above:

```
$paginator->setItemCountPerPage('100');
```

Best Regards,
Anshu

**Comment by meetgerry** [comment]
Hello Anshu,

Thank you for replying. I followed your instruction and have attached the change in this ticket.

The admin page went blank.

![2015-06-518](https://cloud.githubusercontent.com/assets/8540750/8290237/4cf1aeac-192a-11e5-9b78-260bacf13a7a.png)

Thanks
Gerry

**Comment by maxx24** [comment]
Changing the number of viewable members did not work for me either. I got a fatal error when I clicked on manage members.

**Comment by Anshuse** [comment]
Hi @meetgerry , @maxx24 ,

I'm sorry, there was little mistake in my last response. You need to add the code just below the above line i.e :

In ```/application/modules/User/controllers/AdminManageController.php``` file, search below line (around line 78 approx):
```
$this->view->paginator = $paginator = Zend_Paginator::factory($select);
```
and add below line just below the code mentioned above:

```
$paginator->setItemCountPerPage('100');
```

Best Regards,
Anshu

**Comment by meetgerry** [comment]
Thanks Anshu, it worked!
