### ISSUE TITLE
Create Custom Settings Pages

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#310]
It would be very useful for members to be able to have custom settings pages. Currently we have your basic pages for privacy, notifications, edit profile, add profile photo, general settings etc. It would be nice to add custom settings pages for different items or simply add them all on one page either using a tab container or perhaps even a column based structure. A new design to settings manager would be awesome to keep track of and add new settings and profile information on the spot without much effort. This way members could for example edit their profile name and privacy settings on one page, or have their time zone on a separate page or have change password and email settings on its own page.

**Comment by Anshuse** [comment]
Hi @Elshara , thanks for your suggestion but we don't have any plan to implement this feature in our module. Thanks!
