### ISSUE TITLE
Replace ID System With Custom Names

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#312]
ID system works when adding member profiles and content to a database. However it would be much easier to replace both its urls and settings with custom names, such as its profile title rather than having it be its own separate column.

**Comment by Anshuse** [comment]
Hi @Elshara , this feature is already listed in our improvements doc and we have plan to implement this feature in near future upgrade.

**Comment by Elshara** [comment]
Awesome!
