### ISSUE TITLE
Add Content By URL

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#313]
It would be really awesome to add posts by url, replacing the need to upload links in status updates. The way this would work is instead of having to just type in a blog, forum post, poll etc, it could be imported by url. This would especially be useful for media, music for example does not have this support. To add music by youtube for example would be very useful, along with facebook, twitter, soundclick, soundcloud, grooveshark and others. Photos from facebook, flickr, photobucket etc would work similarly. Videos from facebook, twitter and other sites could also be imported. I know people from tumblr, instagram, pinterist would love this especially wordpress.

**Comment by Anshuse** [comment]
Hi @Elshara , our team has done some research on embedly & iframely and we're going to implement integration with https://iframely.com/. For more details you may refer #141 

Thanks!

**Comment by Elshara** [comment]
Can iframe.ly import videos? That's why I suggested embed.ly.

**Comment by Elshara** [comment]
That's how phpfox got around the requirement for people to have to use
google's api for youtube videos. We were asked to install a fix using
code that redirected all api requests to embed.ly. It worked great
while I was working with phpfox before they switched to neutron and I
gave up on it. It was free with embed.ly. Now we will have to probably
still sign up for google api directly which is why I love embed.ly so
much. I hope iframe.ly is just as good. I've never heard of it before.
