### ISSUE TITLE
Add Share buttons

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#314]
It would be nice to export content to other sites by its url. Similarly it would be ideal to import its url onto other sites like facebook, twitter, google and others.

**Comment by Anshuse** [comment]
Hi @Elshara , we've already provided Facebook and Twitter integration feature using which you can share your site's content to Facebook and Twitter. Once you integrate your site to Facebook then you'll need to get respective permission approved from Facebook.

Similarly, you can import your site's content to external sites simply by posting the respective URL of content. When you post the URL of your site's content on any external site like Facebook etc. then all the meta-information of content gets displayed there (based on which all meta-tags that external site can fetch).

Thanks!
