### ISSUE TITLE
Add Embeds And Email Support For Sharing Content

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#315]
IT would be nice to share content by an embed url and email. IT would be nice to email in content and add attachments which automatically show up as photos, music, videos depending on file type.

**Comment by Anshuse** [comment]
Hello @Elshara , currently we don't have any plan to implement this feature in our module but if you upload URL of your site or your site's content on any external site then all the meta-tags, keywords and description etc. get fetched & displayed there (if that external site is well developed to fetch meta-tags). You can check this by pasting the URL of your site to our [Demo](http://demo.socialengine.com/) and you'll see that system will display keywords and description of your site accordingly.

Thanks!
