### ISSUE TITLE
Allow Likes In Forum

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#316]
Forum discussions do not have the ability to be liked.

**Comment by Anshuse** [comment]
Hi @Elshara , that's a good suggestion and I'm forwarding this to our team for internal discussion.
Thanks!

**Comment by Elshara** [comment]
You're very welcome. Glad to help.

**Comment by Elshara** [comment]
IT also would be nice to have forum widgets appear in layout editor on
forum pages just like the blogs and other modules do.

**Comment by Anshuse** [comment]
Hello @Elshara , thanks for your feedback, this is something that is already added in our improvements doc and we're gonna work on this in near future upgrades.
