### ISSUE TITLE
Failure integration with facebook

### ISSUE THREAD

**Issue by pacodrums** [SocialEngine/phpv4-issues#318]
Integration with facebook fails when a user needs to change their facebook account.
For example, a user who has linked her facebook., But later decide to re-link your account, this is no longer possible.
This does not happen with twitter
![screenshot_1](https://cloud.githubusercontent.com/assets/12755773/10925734/56207f40-8256-11e5-8300-0d3217175df5.png)

The following image shows how the screen looks when a user removes the check marks related to the integration with their accounts.
You can see how the twitter button is ready to be used again if the user decides to connect their account again, But not Facebook button
![screenshot_2](https://cloud.githubusercontent.com/assets/12755773/10926020/d2df8ff6-8258-11e5-9ba5-58e535ea83ac.png)

I think it's a bug and I hope we find a solution.
Reconnect functionality accounts and linked accounts to update if necessary is very important.
![screenshot_3](https://cloud.githubusercontent.com/assets/12755773/10926056/214f1620-8259-11e5-888f-b17ee002b388.png)

**Comment by Anshuse** [comment]
Hi @pacodrums , We've added this issue in internal bug tracker and will resolve in near future release.
Thanks!

**Comment by pacodrums** [comment]
@Anshuse  Thanks for the help, I wonder if there is any way to solve this temporary and manually. If social Engine team found a way to fix it I would be very grateful that you shared with me. future release.It can be long and have 15 users awaiting solution.

**Comment by smazurov** [comment]
This has been addressed in [4.8.11](http://blog.socialengine.com/2016/05/26/socialengine-php-4-8-11-is-released/)
