### ISSUE TITLE
Improve Activity Feed Integration With Comments And Likes

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#319]
Comments and likes that are created from the activity feed do not appear on host items. Example, if someone likes a comment someone made on a post, that like isn't included in the post itself meaning they don't actually have a record of the post being liked or commented on from the host item itself such as a blog, photo, playlist, video, group, event, forum topic especially, poll and classified, only the activity feed item displays it was even made usually only in the main activity feed section. I think if someone likes a comment belonging to the post, if the comment belongs to someone connected with the post the post itself should be liked if comments do not support likes directly on the post itself which could be something to work on in future. Allowing people to like comments other people post and being able to display such likes both in the activity feed and the post and have it appear on both. Similarly, if someone posts a comment in the activity feed, their comment is not carried over to the post. It would be nice if posts allowed comments to be replied to otherwise the comment they made from the activity feed could get added in a chronological or reverse chronological order depending on individual comment settings.

**Comment by Anshuse** [comment]
Hi @Elshara, If I understand you correctly, you meant to say that when any photo(s) etc. is posted via Activity Feed and if any user comments on that photo and then if any other user likes that comment then that like doesn't get displayed on the profile of photo. If so, then we're sorry but we were not able to reproduce this at our end. If you meant to say something else then it would be great if you can explain using example and screenshots.
Thanks!

**Comment by Elshara** [comment]
What I'm saying is likes and comments aren't displayed universally
across the activity feed. When someone posts a comment in the activity
feed or likes a post, some posts are feed specific relating to items
about a post made elsewhere such as in the photos or videos sections.
As such they don't get posted there. I think a worthwhile fix would be
to include new comments as apart of an existing activity feed item
moving it up as someone else comments on it. So for example, when
someone posts a photo or comments on something within the activity
feed, if they write a comment in the activity feed, it won't display
as the latest item of the activity feed. But if they go to the post to
make a comment, it displays there, but when they like a post, they are
liking two separate items if they like it from the activity feed and
the post itself. A fix for this would be to republish or rather move
up the last known item relating to such a post so the end result would
be something like this.
User a Wrote a new blog entry
Blog description
15 minutes ago like comment delete share
If someone comments on the blog, either through the activity feed,
likes it either through the activity feed or on the post, the post
above would include the number of comments and likes made about the
blog and have permalinks to the content displayed after the post. This
way people would see the post at the top of the feed if it is the
latest item, followed by comments the same way user statuses work, but
the comments would be recorded differently.
User a wrote a new entry.
20 minutes ago unlike  comment  delete share
this post has seven comments and three likes
you and two other people like this three people have commented on this
seven comments total
or
you and three others like this you and two others have commented on
this seven comments total
Hope that explains things a bit better.

**Comment by DonnaScriptTechs** [comment]
We've improved this for 4.9.0 when it is released. If it still needs improvement after, please open a new issue.

**Comment by Elshara** [comment]
Awesome!
