### ISSUE TITLE
Enabling VigLink with SSL - Security Warnings

### ISSUE THREAD

**Issue by MiamiShade** [SocialEngine/phpv4-issues#32]
This causes a security warning in browsers when using VigLink in enabled mode with SSL.  Is there a way to resolve this.

**Comment by Anshuse** [comment]
Hello @MiamiShade ,

Thanks for reaching out.

We've reported this issue in our internal bug tracker for our development team to have discussion over this to resolve it in near future upgrades.

Best Regards,
Anshu

**Comment by MiamiShade** [comment]
I cant imagine this requires future upgrades.  The temporary for anyone else fix is to load your site URL at VigLink and then paste the VigLink Code into settings head scipts - it works thus far.  SE will not get its sub affiliate commision.

**Comment by smazurov** [comment]
Fixed in [4.8.10](http://blog.socialengine.com/2016/01/20/socialengine-php-4-8-10-is-released/)
