### ISSUE TITLE
Improve Layout Widgets

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#320]
In social engine, you have the ability in layout editor to define things like comments, content and their positions. The forum module doesn't have this what so ever. It would be ideal to specify how content is displayed by default under layout editor by replacing content with its appropriate sub modules. For example, new blogs core module on browse blogs page. This way each page can be entirely redefined. On the blog view page, the module could be called current blog post. On the blog manage page and listing page, it could be called, my blogs. Under comments, it could be its own item and you could have the comments, likes and share modules all separate modules for people to reposition if they wish. That way if people want to share the page before the content of whatever they are viewing is displayed, for example, the rating part of the videos section or the comments part of the blog section, they can do this. Blogs usually come in separate parts, the link for users categories, similar blogs and other items aren't able to be positioned using layout editor as they are not separate widgets. It would be a lot easier for such things to be their own modules in the blog section and other sections for content and comments areas. This would be useful if you want to show photos and music songs rather than their respective albums or playlists for example, you could just replace the modules under layout editor. Every single part of your website could be redefined, for example, if you wanted to reorganize events by birthday, you could just do that on the events browse section. If you want members to be sorted by last activity, not last login, the framework is there, the modules aren't. If you want members to e able to search for members and filter members rather than just have advanced questions be displayed, you could do that. If you wanted to have a particular blog home page list a particular category you could do that. The layout editor is the answer to all these problems because it gives us a lot more control over what is positioned as a module, rather than having the module to be redefined. You could therefore create a subsection of the layout editor if you wanted to for the sorting of blogs, forums, and their listings such as what comes first in a table, what gets shown under the title, and how many characters gets shown under the description or title and you could reorganize its html if you anted to. Having the ability to edit core content and place it under its own modules under layout editor would be a really valuable addition to social engine.

**Comment by Anshuse** [comment]
Hello @Elshara , We already have plan to improve the features in Layout Editor section and they are already listed at our end. 

Regarding "Sorting of blogs, forums and their listings": I'm forwarding your suggestion to my team for internal team discussion to take require action on this.
Thanks!
