### ISSUE TITLE
Milestone/Date Of Next Upgrade

### ISSUE THREAD

**Issue by meetgerry** [SocialEngine/phpv4-issues#321]
Why the milestone is not update or the propose date of upgrade is not indicated. Its been half year now and no upgrade has been released.

When is the proposed date of next upgrade release?

**Comment by smazurov** [comment]
we don't have anything to announce at this time, when we know more, we'll be sure to let everyone know through various channels. I would like to remind you that this channel is used for reporting bugs and suggest features, off topic issues such as this might be closed without notice.

**Comment by meetgerry** [comment]
True! This is a place for highlighting issues with the objective of getting it resolved. If this is true then you should be courteous in keeping everyone informed on the progress of the issues. There is nothing I see. Only issues are pointed out and no wave of any solutions heard or felt so far.
