### ISSUE TITLE
Members Manage - Bug

### ISSUE THREAD

**Issue by playmusician** [SocialEngine/phpv4-issues#322]
Hi ,
 after I installed social engine (Playmusician.me)

 I have 4 members.
 When I click on ANY  members "edit" link.
 It keeps just showing me the 1st members details  to edit..

 It does not reflect the correct members edit details.

 example .. If I click on the 3rd members "edit" link.
 It shows me just the 1st members details to edit.

Also - Even though some of these members are Super Admins
 it lists them as "Regular Members" if I click on Stats. 

 Thanks

 Have attached image
![managemembers_edit_feature does_not_work](https://cloud.githubusercontent.com/assets/15879412/11197034/b670f53c-8c88-11e5-9387-1eac26d2e171.jpg)

**Comment by Anshuse** [comment]
Hi @playmusician , We're not able to reproduce this issue at our end so, it's an installation specific issue. As you've opened a ticket regarding same issue and we'll handle your case over there. 
Thanks!

**Comment by playmusician** [comment]
Hi Anshuse,
It seems that Super Admins cannot delete Superadmin accounts.
Thanks

**Comment by Anshuse** [comment]
Hi @playmusician , we would like to tell you that members of Super-admin Member Level can't be deleted from the site. Thanks!
