### ISSUE TITLE
SE PHP doesn't load css files

### ISSUE THREAD

**Issue by ajbasket** [SocialEngine/phpv4-issues#323]
Hi, recently I install SE on a hosting server, but after do the installation when I get to any page CSS styles doesn't load correctly, they get an error 500 when SE tries to load them.

I don't know what's happening!!!

**Comment by Anshuse** [comment]
Hi @ajbasket , issue seem to be due to File permission settings and we'll need to check it on your server so, we suggest you to file a support ticket along with your site details and our support staff will guide you accordingly.
Thanks!
