### ISSUE TITLE
Make Unified Admin Interface Across All Plugins

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#326]
Currently social engine hasn't got a unified admin interface.
In the blogs area for example, everything is controlled using a menu.
In the profile section, everything is shared between the admin area and the actual profile menu which is not actually convenient because you don't know which interface to go to in order to manage anything.
This is also reflected in the forums area where admin options are so complex it's easier just to avoid it completely.
In the polls section, there is no admin options. You cannot delete a poll, edit answers, attach a poll, close comments or voting etc.
In the photos and videos area, you have to scroll all the way to the bottom of the page just to see tiny icons that show you where to edit the item but not delete it.
Groups have the same thing. What's more you only have control over what you can delete in the admin area of the control panel, but on the user side, only if you are the group creator, do you have the option to even edit the group or do things group creators can do but only them, not admins.
Events don't seem to display the option at all.
You see this is seriously why I am considering phpfox as an alternative. Not only are the admin settings very easy to universally edit, but they are very easy to get to no matter what you are viewing.
I'd say social engine needs to be a lot more integrated with how it recognizes writing to a database regardless of plugin or default built in functionality.
What I'm getting at is there needs to be a default admin plugin that gets called when ever admin functions are needed. Just like comments and likes are beautifully displayed across all items. The administrative plugin would check to see what kind of a plugin admin features support. Universally these could be classified into either one edit button, or an edit and a delete button. All other local options could be redefined as required. For example, under the groups and events section, because when you create a group or event, you're able to choose privacy items immediately, you are also able to make them appear in their edit menus. When it comes to managing members for example, such permissions aren't granted to things like polls, forums or blogs, so ideally such settings would only be available to group and events, even though they would be an integral part of the supposed admin plugin, they would only appear for the types of events that support it.
This would make managing a social engine site a lot easier. The admin plugin would have one menu, it would function just like the sign up sign in menu with access to everything an admin would need. It could be repositioned on a page using layout editor or embedded as apart of the page content. Or, it could be called using a smoothbox.
In terms of the admin control panel, managing content currently relies on respective plugins to be accessed through the plugin manager. Only because members appear under social engines basic core plugin do they show up under the manage menu.
Using a global social engine admin plugin, this would fix such a requirement making managing content a one click process. Editing in bulk would simply require clicking a checkbox for either a smoothbox or a dialog to appear depending on what you want to do. Editing an item for example would check to see if global permissions could be applied in bulk like for example, changing a user title or editing the permissions of a user group setting from one member level to another. Bulk editing would make this process easy because the plugin would be able to universally access all data and would make it safer as well.
Social engine needs a new way to manage members, content and files. This could be the answer.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#17

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
