### ISSUE TITLE
Widget Improvements

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#328]
Here are some bugs I've noticed with several widgets.
1. You cannot like or indeed comment on groups and events. The comments widget won't display on group and event profiles to be able to like them or comment.
2. The profile forum posts widget has no comment cut off. This means the posts appear very long and do not fit with the profile widgets that display limited descriptions such as the blogs profile widget. Additionally, some widgets like the groups, events and polls widgets display full descriptions which can become also very long whereas the forum topic created, photos, music, videos and classifieds widgets only display titles. A fix for this would be to allow widgets to have custom character description lengths or display as title only in layout editor settings. Also it is a good practice to streamline widgets so you don't have a hundred widgets staring you in the face, you could have one widget per plugin and then when you edit it when you drag it on to the page, you can select what kind of widget you want to associate with the plugin for example choosing members would allow you to select a menu, popular members, newest members and so on. It makes it a lot more clean looking this way.
3. Profile links widget doesn't work in member, group and event profiles. Links posted in the activity feed don't appear in the profile links widget.
4. Widgets don't appear in cache.
5. Using cloudflare railgun in conjunction with cloudflare caching settngs causes first time loading of some widgets such as the activity feed, who is online and rich text editors to not display properly. The rich text editor doesn't display at all in some cases requiring a refresh of the page for it to do so.
6. Tags should be a separate widget and all modules should support this.
7. In friends and following related profile widgets, the oldest friends display first, not newest. This is also the case when viewing groups and events where members are displayed.

**Comment by DonnaScriptTechs** [comment]
Please check after 4.9 releases. If the issues still exist, please post one item per report.

**Comment by Elshara** [comment]
Awesome!
