### ISSUE TITLE
Warning The End Of Ning Closing Its Doors December 15 2015

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#329]
This isn't exactly a social engine issue per say, however I thought you all should know.
Social Engine php may receive a massive influx of Ning network creators looking to migrate content in a hurry.
Taken from this customer discussion, here is some new information about what is going on with Ning.
http://creators.ning.com/forum/topics/really-ning-you-re-raising-my-rates-from-60-to-1000-per-month
This was posted by http://creators.ning.com/members/ClarkP - November 26, 2015 at 1:14am
"Here is the complete letter from Ning regarding one of our sites:
Dear Network Creator,
In order to continue providing the best service to our top tier customers and our network as a whole, we are compelled to adjust our subscription plans in 2016 to address the increasing costs associated with maintaining our Ning infrastructure. As a result, we are taking the following actions:
• 
Instituting a 100,000 membership cap on the Ning 2.0 Pro plan
• 
Instituting a 500 GB data storage limit on the Ning 2.0 Pro plan
• 
Implementing a new tier of subscription plans to support our top tier networks
As of January 1, 2016 the new subscription plans will go into effect for both Ning 2.0 and Ning 3.0 networks and our subscription plan structure will be as follows:
 
Mini
Plus
Pro
Business Plus
Corporate*
Price  (Monthly)
$2.95
$24.95
$59.95
$500
$1,000
Member Limit
150
10,000
100,000
100K - 1M
1M – 1.5M
Storage Limit
1 GB
10 GB
500 GB
501 GB - 1 TB
1 TB - 3 TB
*In the event these limits are exceeded, custom pricing shall be negotiated.
Currently, your network utilizes 503 GB of data storage monthly and has more than 14,000 members (this data can be viewed in your network’s dashboard). Therefore, based on your data storage needs and membership, effective January 1, 2016 your network will be enrolled in the new Business Plus Subscription Plan and your new monthly rate will be $500.
As the network creator, you have two options:
1. 
Elect to continue your Ning 2.0 membership under the new Business Plus Subscription Plan. The new plan will go into effectJanuary 1, 2016 and your monthly invoice will reflect the new rate. Your plan will renew monthly until canceled (you can reference our cancellation policy here: http://www.ning.com/billingpolicy/). Annual plans will be credited for the amount of any unused portion. Under the new plan your payment will be collected from the default payment method associated with your account.
2. 
Elect to cancel your Ning 2.0 membership. If you elect to cancel your membership, you may do so at any time before January 1, 2016 (you can reference our cancellation policy here: http://www.ning.com/billingpolicy/). Annual plans will be issued a prorated refund for the unused portion of your subscription. If you do not cancel prior to January 1, 2016, you will be placed on the Business Plus Subscription Plan and be billed at the new rate until you elect to cancel your membership.
Prior to canceling your membership, you may contact Ning customer support to assist with the archiving of your network’s content.
Please notify us of your election to continue your membership under the new plan or cancel it, by replying to this email (theningteam@mode.com) no later than December 15, 2015. If you have any questions about this notice, please contact us at this email as well.
If we do not receive your election by December 15, 2015, we will deem your membership cancelled and will terminate your membership effective January 1, 2016.
We regret having to take these actions, however, we have no choice in order to maintain the Ning service for our members. We appreciate and thank you for your understanding in this matter. 
Thanks,
The Ning Team"
There are lots of other discruntled customers waiting to move from Ning this will enforce them to choose social engine php or word press or jamroom or jom social or some other platform even phpfox.
If you are one of these people you may wish to look at hostiso.com for social engine hosting that is reliable. Network creators are given until December 15 2015 to reply to Ning stating they are moving ahead with a new pricing plan for their network otherwise their network will automatically be removed without the option to archive content.
I'm glad I moved to social engine when I did.

**Comment by smazurov** [comment]
Hey, I appreciate you posting this, this is good info and we agree, SocialEngine is a great platform to switch to. We have a landing page built for potential ning converters here: https://get.socialengine.com/ning/. Since there is nothing more we can do here (at the current time), I'll close this issue.

**Comment by Elshara** [comment]
I just thought you should be aware of it <3 its my pleasure.
