### ISSUE TITLE
User Level not mapping to subscriptions

### ISSUE THREAD

**Issue by MiamiShade** [SocialEngine/phpv4-issues#33]
When an admin assigns a "normal" user (default level) to a new level (Paid Subscription) this new level is not registered in the users profile subscriptions section. i.e. they sre still listed as the original "normal" user. Is this the intended method?

**Comment by Anshuse** [comment]
Hello @MiamiShade ,

If you're referring to the information that is written just below the member's profile photo in the members' profile page then we would like to tell that this is the "Member Type" (Profile Type) of a member and "Member Type" is different from the "Member Level". "Member Type" (or Profile Type) is something that a user selects at the time of sign up process. It seems that you've changed the "Member Level" of a particular member but checking the Member Type of that member and so, we suggest you to please check this at your end again.

Best Regards,
Anshu

**Comment by MiamiShade** [comment]
I am referring to a users own settings page (link from mini menu)
The tabs are General | Privacy | Networks | Notifications | SUBSCRIPTIONS | Change Password
Select the SUBSCRIPTIONS Link
You are using the FREE Plan (Regardless of what subscription level admin changes to this will not change)

**Comment by Anshuse** [comment]
Hello @MiamiShade ,

Thanks for clarifying your query.

This is not a known issue in SocialEngine PHP and so, we suggest you to file a support ticket along with your site details (FTP details) and our technical support team will help you out.

Best Regards,
Anshu
