### ISSUE TITLE
Link posting

### ISSUE THREAD

**Issue by Voxitt** [SocialEngine/phpv4-issues#331]
I've tried posting links to articles from Forbes.com to my social engine site. Each time a link is pasted, the home page of Forbes is what shows up instead of the article selected. 

I've tried to do the same on the socialengine demo site but the outcome is not any different. Is there anything that can be done to resolve this?

**Comment by smazurov** [comment]
I believe this is a forbes issue - they use a javascript app so our scraping mechanism fails for them. They, in the past, had specific methods in place to allow the right article to be posted, but my guess is that mechanism is either temporary or permanently down.
