### ISSUE TITLE
Members cannot report activity feed.

### ISSUE THREAD

**Issue by fineh** [SocialEngine/phpv4-issues#334]
Hello,

How can people report abusive activity feed posts? there is no report button?
Can this be added on the next version? common sense for a social network?

**Comment by Anshuse** [comment]
Hi @qoutas , thanks for your suggestion. We'll discuss with our team to work on this near future.

**Comment by eugene-wh** [comment]
I think the problem here is that feed update cant' be opened on a single page (so it has no url). If you will add a view for a single fee post (+ comments) - it will be much easier to add reporting.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#19

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
