### ISSUE TITLE
Improving User Ineractions

### ISSUE THREAD

**Issue by inkyj** [SocialEngine/phpv4-issues#335]
I saw that you guys have been working on integrating intercom.io with the cloud version. Something like this would be amazing for the PHP version too! 

We've been looking for ways to automatically email our members based on their community activity (or inactivity). Like if the'ye been inactive in our community for a while, especially at the beginning of their membership, we need to send them a little nudge to get back in. I know Intercom.io can handle this type of automated task, but I haven't found any plugin, or integration that can handle anything like this. If you guys could add intercom integration to the PHP roadmap, I think it would be great as it would give everyone a fantastic tool to build up interactions.

**Comment by shivani2910** [comment]
Hi @inkyj,

Thanks for the suggestion. Yes, it would definitely be a good thing to be included in SocialEngine PHP.
We've forwarded it to our team for internal discussions.

Thanks again,
Shivani
