### ISSUE TITLE
Posting Photos

### ISSUE THREAD

**Issue by Voxitt** [SocialEngine/phpv4-issues#336]
I've noticed that photos posted on my social engine site are either being displayed sideways or upside down. This mainly happens when posting from mobile. Is there any reason why this is happening?

**Comment by Anshuse** [comment]
Hi @Voxitt , there used be one issue where photos used to turn sideways when captured and uploaded from a few android and iOS devices but we've resolved this issue in 4.8.9 so, make sure that you're using latest version i.e. 4.8.9 of SocialEngine.
Thanks!
