### ISSUE TITLE
Forums > Discussions: Editing post or comment displays html in post

### ISSUE THREAD

**Issue by LuciusPrime** [SocialEngine/phpv4-issues#338]
Any topic post or replies show HTML in the post.  I was under the impression 4.8.9p2 had this issue fixed.
<img width="957" alt="screen shot 2015-12-14 at 8 20 14 pm" src="https://cloud.githubusercontent.com/assets/10039148/11801137/3a398442-a2a0-11e5-99f3-4963401086b5.png">

**Comment by Anshuse** [comment]
Hello @LuciusPrime , HTML tags are working fine on our [Demo] (http://demo.socialengine.com/) site. Please make sure that you have enabled "Enable HTML" field for forums on your site.

![forums](https://cloud.githubusercontent.com/assets/11085507/11865086/c0e117ac-a4c7-11e5-83df-ea106a4eaa27.png)
