### ISSUE TITLE
Video Thumbs Disproportionate Sizes

### ISSUE THREAD

**Issue by MiamiShade** [SocialEngine/phpv4-issues#34]
It was in previous versions identical thumb sizes for SocialEngine Video.  Now in 4.8.8  HTML5 on/off "Youtube & Vimeo" thumbs are a different size than created for video uploads from "my computer" on video browse page resulting in a poor display presentation.

**Comment by Anshuse** [comment]
Hello @MiamiShade ,

Apologies for the delayed response.

We've checked this at our end and found that yes, thumbnails of videos uploaded via external sites (YouTube & Vimeo) are different from the thumbnails of videos uploaded from local system and so, it seems that these external sites have done some changes at their end and so, we're forwarding this case to our team to research on it.

Best Regards,
Anshu

**Comment by darkasylumradio** [comment]
i had change the code for mine, also facebook as well to  thumb sizes right! , but if you can get right size on new version be great
