### ISSUE TITLE
Forum Topics Title containint quotation marks

### ISSUE THREAD

**Issue by IgArI0K** [SocialEngine/phpv4-issues#340]
Tested in http://demo.socialengine.com/forums/topic/47/testing-topic-with-quotest-quot-text-inside-quotes-quot/view/post_id/68

Title of topic: Testing Topic with quotest "text inside quotes"
Look closely on link to this topic and preciselly at: quotest-quot-text-inside-quotes-quot
Also meta tag tile as following: <title>SocialEngine Demo - Testing Topic with quotest &amp;quot;text inside quotes&amp;quot;</title>.
If duplication of issue then please leave link to first issue and/or possible ways of  solving.

**Comment by Anshuse** [comment]
Hi @IgArI0K , thanks for bringing this to our attention. We've reported this case in our internal bug tracker for internal team discussion on this. Thanks!

**Comment by smazurov** [comment]
This has been addressed in [4.8.11](http://blog.socialengine.com/2016/05/26/socialengine-php-4-8-11-is-released/)
