### ISSUE TITLE
Can't save integer value "5" from member level settings

### ISSUE THREAD

**Issue by vjgarg2** [SocialEngine/phpv4-issues#341]
Hello SE Team,

I can not save integer value "5" from Member Level Settings from SE default plugins.  You can check here: SITE_URL/admin/video/settings/level

Here, you can enter "5" in "Maximum Allowed Videos" and save value. After, you refresh same page and text field is empty.

Please check this issue at your end.

I am waiting your response.

Best, 
Vijay

**Comment by Anshuse** [comment]
Hi @vjgarg2 ,

We've reported this issue in our internal bug tracker for internal team discussion on this to resolve this in near future release.

Thanks!

**Comment by DonnaScriptTechs** [comment]
This is fixed for our next release.

**Comment by Elshara** [comment]
:)
