### ISSUE TITLE
Privacy is not working on Browse page and widgets

### ISSUE THREAD

**Issue by vjgarg2** [SocialEngine/phpv4-issues#343]
Hello SE Team,

I have created a blog in SE default Blogs Plugin and set View Privacy "Just Me" but this blog is show on Browse Blog Page and also in Activity Feed.

View Privacy is not working on Browse Page and some other widgets and activity feed.

Privacy is only working on View Blog Page.

So, you can discuss this issue with your technical team and consider for next upgrade. Many Clients Want this things in there SE Sites.

Best

**Comment by Elshara** [comment]
That's how things are supposed to work. You can control privacy settings of browse pages from general settings page in admin panel.

**Comment by Anshuse** [comment]
Hi @vjgarg2 , as @Elshara has mentioned above that this is how the privacy of SocialEngine PHP currently works but we've plan to optimize the privacy settings of complete module in near future.

Thanks!

**Comment by Elshara** [comment]
That sounds very promising to know this.
Perhaps a redesign of the privacy settings where it is perhaps located
in layout manager on a per page basis for global pages, or a way to
implement it under global or member level settings to some extent in
plugin specific areas may be more of a streamlined idea useful to
where other relative settings may be found.
