### ISSUE TITLE
'domain.one' appears to be a DNS hostname but cannot match TLD against known list

### ISSUE THREAD

**Issue by xyzsimon** [SocialEngine/phpv4-issues#344]
Hi,  I'm on step 4 of the SE PHP installation and I am getting this message:

        'domain.one' is not a valid hostname for email address 'admin@forsalebyowner.one'
        'domain.one' appears to be a DNS hostname but cannot match TLD against known list
        'domain.one' appears to be a local network name but local network names are not allowed

Note:  'domain.one' is the not the name of my domain however my domain has the:   .one    extension.

**Comment by xyzsimon** [comment]
you can also go to this url to see is the issue I have explained above:  
http://forsalebyowner.one/install/install/account

**Comment by Anshuse** [comment]
Hi @xyzsimon , you may do below change at your end and after that this issue will be resolve on your site:

In file  ```/application/libraries/Zend/Validate/Hostname.php```, search for the below code:

```php
protected $_validTlds = array(
```

And,  just add a new item **"one"** at the end of this array.

We've added this issue at our end to resolve this in near future release.

Thanks!

**Comment by smazurov** [comment]
This has been addressed in [4.8.11](http://blog.socialengine.com/2016/05/26/socialengine-php-4-8-11-is-released/)
