### ISSUE TITLE
Profile Questions Field Dependent

### ISSUE THREAD

**Issue by meetgerry** [SocialEngine/phpv4-issues#345]
It would be good if there was an option to add fields or sub-questions for profile questions.

For example: If an user selects MALE from the select option field in the profile question then specific set of questions are displayed and if the user selects FEMALE then another set of questions are displayed.

**Comment by pacodrums** [comment]
This is option is available. Check this link support http://support.socialengine.com/php/customer/portal/articles/1644307-admin-panel---settings-&gt;-profile-questions 
-under the "Adding a Dependent Question" section

**Comment by meetgerry** [comment]
Thanks, this is what I needed.
