### ISSUE TITLE
Icons Are Depricated In Php 5.6

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#347]
In social engine development mode, when using php version 5.6, an error message appears at the top of all pages.
Here is the error featured on the control panel home page.
( ! ) Deprecated: iconv_set_encoding(): Use of iconv.input_encoding is deprecated in /home/unite593/public_html/application/libraries/Engine/Application.php on line 314
Call Stack
#
Time
Memory
Function
Location
1
0.0006
246184
{main}( )
.../index.php:0
2
0.0024
247912
include( '/home/unite593/public_html/application/index.php' )
.../index.php:24
3
0.0051
293192
Engine_Application->__construct( )
.../index.php:193
4
0.0052
295104
Engine_Application->setOptions( )
.../Application.php:130
5
0.0053
295760
Engine_Application->setCharset( )
.../Application.php:174
6
0.0053
295856
iconv_set_encoding ( )
.../Application.php:314

( ! ) Deprecated: iconv_set_encoding(): Use of iconv.output_encoding is deprecated in /home/unite593/public_html/application/libraries/Engine/Application.php on line 315
Call Stack
#
Time
Memory
Function
Location
1
0.0006
246184
{main}( )
.../index.php:0
2
0.0024
247912
include( '/home/unite593/public_html/application/index.php' )
.../index.php:24
3
0.0051
293192
Engine_Application->__construct( )
.../index.php:193
4
0.0052
295104
Engine_Application->setOptions( )
.../Application.php:130
5
0.0053
295760
Engine_Application->setCharset( )
.../Application.php:174
6
0.0057
296280
iconv_set_encoding ( )
.../Application.php:315

( ! ) Deprecated: iconv_set_encoding(): Use of iconv.internal_encoding is deprecated in /home/unite593/public_html/application/libraries/Engine/Application.php on line 316
Call Stack
#
Time
Memory
Function
Location
1
0.0006
246184
{main}( )
.../index.php:0
2
0.0024
247912
include( '/home/unite593/public_html/application/index.php' )
.../index.php:24
3
0.0051
293192
Engine_Application->__construct( )
.../index.php:193
4
0.0052
295104
Engine_Application->setOptions( )
.../Application.php:130
5
0.0053
295760
Engine_Application->setCharset( )
.../Application.php:174
6
0.0060
296424
iconv_set_encoding ( )
.../Application.php:316

( ! ) Deprecated: iconv_set_encoding(): Use of iconv.input_encoding is deprecated in /home/unite593/public_html/application/modules/Core/Bootstrap.php on line 33
Call Stack
#
Time
Memory
Function
Location
1
0.0006
246184
{main}( )
.../index.php:0
2
0.0024
247912
include( '/home/unite593/public_html/application/index.php' )
.../index.php:24
3
0.0051
293192
Engine_Application->__construct( )
.../index.php:193
4
0.0052
295104
Engine_Application->setOptions( )
.../Application.php:130
5
0.0063
296616
Engine_Application->setBootstrap( )
.../Application.php:174
6
0.0129
327464
Core_Bootstrap->__construct( )
.../Application.php:277
7
0.0158
346440
iconv_set_encoding ( )
.../Bootstrap.php:33

( ! ) Deprecated: iconv_set_encoding(): Use of iconv.output_encoding is deprecated in /home/unite593/public_html/application/modules/Core/Bootstrap.php on line 34
Call Stack
#
Time
Memory
Function
Location
1
0.0006
246184
{main}( )
.../index.php:0
2
0.0024
247912
include( '/home/unite593/public_html/application/index.php' )
.../index.php:24
3
0.0051
293192
Engine_Application->__construct( )
.../index.php:193
4
0.0052
295104
Engine_Application->setOptions( )
.../Application.php:130
5
0.0063
296616
Engine_Application->setBootstrap( )
.../Application.php:174
6
0.0129
327464
Core_Bootstrap->__construct( )
.../Application.php:277
7
0.0162
346536
iconv_set_encoding ( )
.../Bootstrap.php:34

( ! ) Deprecated: iconv_set_encoding(): Use of iconv.internal_encoding is deprecated in /home/unite593/public_html/application/modules/Core/Bootstrap.php on line 35
Call Stack
#
Time
Memory
Function
Location
1
0.0006
246184
{main}( )
.../index.php:0
2
0.0024
247912
include( '/home/unite593/public_html/application/index.php' )
.../index.php:24
3
0.0051
293192
Engine_Application->__construct( )
.../index.php:193
4
0.0052
295104
Engine_Application->setOptions( )
.../Application.php:130
5
0.0063
296616
Engine_Application->setBootstrap( )
.../Application.php:174
6
0.0129
327464
Core_Bootstrap->__construct( )
.../Application.php:277
7
0.0166
346536
iconv_set_encoding ( )
.../Bootstrap.php:35
Your site is currently in development mode (which may decrease performance). When you've finished changing your settings, remember to return to production mode. 
Changing to php 5.5 makes the message disappear.

**Comment by Elshara** [comment]
Here is the error featured on the member home page.

( ! ) Deprecated: iconv_set_encoding(): Use of iconv.input_encoding is deprecated in /home/unite593/public_html/application/libraries/Engine/Application.php on line 314
Call Stack
#
Time
Memory
Function
Location
1
0.0006
245224
{main}( )
.../index.php:0
2
0.0024
246952
include( '/home/unite593/public_html/application/index.php' )
.../index.php:24
3
0.0051
292272
Engine_Application->__construct( )
.../index.php:193
4
0.0052
294200
Engine_Application->setOptions( )
.../Application.php:130
5
0.0052
294856
Engine_Application->setCharset( )
.../Application.php:174
6
0.0052
294968
iconv_set_encoding ( )
.../Application.php:314

( ! ) Deprecated: iconv_set_encoding(): Use of iconv.output_encoding is deprecated in /home/unite593/public_html/application/libraries/Engine/Application.php on line 315
Call Stack
#
Time
Memory
Function
Location
1
0.0006
245224
{main}( )
.../index.php:0
2
0.0024
246952
include( '/home/unite593/public_html/application/index.php' )
.../index.php:24
3
0.0051
292272
Engine_Application->__construct( )
.../index.php:193
4
0.0052
294200
Engine_Application->setOptions( )
.../Application.php:130
5
0.0052
294856
Engine_Application->setCharset( )
.../Application.php:174
6
0.0055
295400
iconv_set_encoding ( )
.../Application.php:315

( ! ) Deprecated: iconv_set_encoding(): Use of iconv.internal_encoding is deprecated in /home/unite593/public_html/application/libraries/Engine/Application.php on line 316
Call Stack
#
Time
Memory
Function
Location
1
0.0006
245224
{main}( )
.../index.php:0
2
0.0024
246952
include( '/home/unite593/public_html/application/index.php' )
.../index.php:24
3
0.0051
292272
Engine_Application->__construct( )
.../index.php:193
4
0.0052
294200
Engine_Application->setOptions( )
.../Application.php:130
5
0.0052
294856
Engine_Application->setCharset( )
.../Application.php:174
6
0.0057
295544
iconv_set_encoding ( )
.../Application.php:316

( ! ) Deprecated: iconv_set_encoding(): Use of iconv.input_encoding is deprecated in /home/unite593/public_html/application/modules/Core/Bootstrap.php on line 33
Call Stack
#
Time
Memory
Function
Location
1
0.0006
245224
{main}( )
.../index.php:0
2
0.0024
246952
include( '/home/unite593/public_html/application/index.php' )
.../index.php:24
3
0.0051
292272
Engine_Application->__construct( )
.../index.php:193
4
0.0052
294200
Engine_Application->setOptions( )
.../Application.php:130
5
0.0059
295712
Engine_Application->setBootstrap( )
.../Application.php:174
6
0.0116
326544
Core_Bootstrap->__construct( )
.../Application.php:277
7
0.0144
345520
iconv_set_encoding ( )
.../Bootstrap.php:33

( ! ) Deprecated: iconv_set_encoding(): Use of iconv.output_encoding is deprecated in /home/unite593/public_html/application/modules/Core/Bootstrap.php on line 34
Call Stack
#
Time
Memory
Function
Location
1
0.0006
245224
{main}( )
.../index.php:0
2
0.0024
246952
include( '/home/unite593/public_html/application/index.php' )
.../index.php:24
3
0.0051
292272
Engine_Application->__construct( )
.../index.php:193
4
0.0052
294200
Engine_Application->setOptions( )
.../Application.php:130
5
0.0059
295712
Engine_Application->setBootstrap( )
.../Application.php:174
6
0.0116
326544
Core_Bootstrap->__construct( )
.../Application.php:277
7
0.0147
345616
iconv_set_encoding ( )
.../Bootstrap.php:34

( ! ) Deprecated: iconv_set_encoding(): Use of iconv.internal_encoding is deprecated in /home/unite593/public_html/application/modules/Core/Bootstrap.php on line 35
Call Stack
#
Time
Memory
Function
Location
1
0.0006
245224
{main}( )
.../index.php:0
2
0.0024
246952
include( '/home/unite593/public_html/application/index.php' )
.../index.php:24
3
0.0051
292272
Engine_Application->__construct( )
.../index.php:193
4
0.0052
294200
Engine_Application->setOptions( )
.../Application.php:130
5
0.0059
295712
Engine_Application->setBootstrap( )
.../Application.php:174
6
0.0116
326544
Core_Bootstrap->__construct( )
.../Application.php:277
7
0.0149
345616
iconv_set_encoding ( )
.../Bootstrap.php:35

**Comment by Anshuse** [comment]
Hello @Elshara ,

We've suppressed these warnings for the deprecated errors in the Production mode and now these warnings get displayed only in the Development mode. For now, you can ask your hosting company to downgrade PHP version on your server. And, we've plan to work on such deprecated errors in near future.

Thanks!

**Comment by Elshara** [comment]
Thanks for the update.
The problem is the icons wont display in production mode clearly
because they can't in development mode. I had managed after some time
to get the server to downgrade to 5.5 which by the way is only
supported for another 5 months.
A fix for this would be cool considering it is less taxing than tackling php 7.
Anyways I thought I'd bring it to your attention.

**Comment by smazurov** [comment]
This has been addressed in [4.8.11](http://blog.socialengine.com/2016/05/26/socialengine-php-4-8-11-is-released/)
