### ISSUE TITLE
feature request:  Matchmaker plugin

### ISSUE THREAD

**Issue by xyzsimon** [SocialEngine/phpv4-issues#348]
This is a request for a new feature. 

1. Name of feature:  Matchmaker

2. What does Matchmaker do?  The admin can choose which profile questions to  offer registered users, in the example of a dating website:  gender, age, city, and country can be chosen for Matchmaker questions.  

Registered users answers the Matchmaker questions.  

The website is automated so it sends out notifications to Users when criteria of 'new user' registration matches the criteria they have set in their Matchmaker profile. 

Also, in the case of a dating website, the  Matchmaker plugin can be setup by User so if other Users don't match their criteria set, the other Users won't be able to contact them. This of course can be turned on/off by both the Admin (to offer Users the ability to turn this on/off) and once offered to Users by the Admin, for Users to decide if they want it turn on/off at their end. 

3.  Why is the Matchmaker Plugin worthy of development?
Answer.   When a User gets an email notification that a new User matches their Matchmaker criteria, he/she will want to visit the website more often - it brings Users back to your site
Answer.  It's a great notification service.
Answer.  The Matchmaker Plugin can be use in a buy and sell site, for example if you want notification whenever a Tesla Roadster for sale, that is of a specific color, year, price range, etc.  you'll get a notification.  Image a real estate site that will notify you when a dream property is listed based on your criteria.....

Here is a dating script that offers a Matchmaking plugin that I have explained above:  http://www.datingscript.com/explore/features/matchmaker

**Comment by Anshuse** [comment]
Hello @xyzsimon , thanks for your suggestion. We're sorry to say but currently we don't have any plan to implement any such feature. Here's the list of our third party developers http://www.socialengine.com/customize/se4/developers who may work on this feature so, you may contact our top-rated developers and discuss this feature with them.

Thanks!
