### ISSUE TITLE
would SE PHP work with MariaDB, if not, any plans to make it compatible? 

### ISSUE THREAD

**Issue by xyzsimon** [SocialEngine/phpv4-issues#349]
I recently came across this open source database.  I'm wondering if SE has plans to make their script compatible with MariaDB or is it already?

Refer to MariaDB here: https://en.wikipedia.org/wiki/MariaDB  and https://mariadb.org/

p.s.  Do let me know if this post is something I should not be posting here.

**Comment by smazurov** [comment]
Since mariaDB is api compatible with MySQL db, it should work, although we don't have any official support.
