### ISSUE TITLE
Invite Code Is invalid In Mobile Site

### ISSUE THREAD

**Issue by kingmxiii** [SocialEngine/phpv4-issues#35]
When user try to sign-up in the mobile site they get the following error

Then Invite Code is invalid or does not match the selected email address.

It  works fine in the Desktop site.

**Comment by Anshuse** [comment]
Hello @kingmxiii ,

Thanks for reaching out.

This is not a known issue and we're not able to reproduce it at our end and so, you may file a support ticket along with your site details, our technical support staff will help you out.

Best Regards,
Anshu

**Comment by kingmxiii** [comment]
Thanks Anshuse.
I was able to find the problem. 
It was a bug on the mobile pluging from socialengineaddon
