### ISSUE TITLE
New features request for SE PHP's Forum

### ISSUE THREAD

**Issue by xyzsimon** [SocialEngine/phpv4-issues#350]
I've listed a lot of new feature requests, re:  SE PHP's Forum.  I hope, maybe, a few of them would be implemented. 

New features request, re:  for SE PHP’s Forum

* Admin can set which Member Level(s) can have access (view) to Forums
* Admin can turn:  on / off any of the present and future menu items on Forum (presently there are these functions:  Clear formatting, Paste as text, Source code, Insert  / Edit video, Insert  / Edit image, Upload an image, Insert / Edit link, Fullscreen and Preview).  The new Menu times will include:  Upload a video and Upload a document.  
*  Whatever Menu functions User are allowed, as set by Admin, User can undo (delete, edit), for example if Admin allows User to:  Upload a document (this is a new feature request), User can, in turn, delete the document he/she uploaded.  

Here is a list of other feature requests for SE PHP’s Forum.  

1.	RE:  Upload an image.  Ability for Admin to set:
a.	on / off  (already mentioned above)
b.	which Member Level can upload image in Forum
c.	which image extensions are allowed
          d. maximum number of images User can upload
e.	maximum size of each image 
f.	maximum dimension of image too?  

2.	Allow for User to upload videos.  Ability for Admin to set:
a.	on / off (already mentioned above)
b.	which Member Level can upload videos in Forum
c.	which video extensions are allowed
d.	maximum number of videos User can upload
e.	maximum size of each video upload
  

3.	 Allow for User to upload documents in Forum.  Ability for Admin to set:
a.	on / off 
b.	which Member Level can upload documents in Forum
c.	which Member Level can view documents in Forum
d.	which Member Level can download documents in Forum
e.	which document extensions are allowed
f.	maximum number of documents User can upload
g.	maximum size of each document

Thanks for reading my new requests for Forum! 

![se php forum - user end](https://cloud.githubusercontent.com/assets/16373524/12029249/ee759bee-ad9a-11e5-9a9f-286f8cb77f6d.jpg)

**Comment by Anshuse** [comment]
Hi @xyzsimon , thanks for your suggestions. We've noted down your thread at our end and will go through all the suggestions once we'll start working on the Forum enhancements in near future.

Thanks!
