### ISSUE TITLE
Activity feed: Members' display names are needlessly translated

### ISSUE THREAD

**Issue by rwetzlmayr** [SocialEngine/phpv4-issues#351]
If an activity feed item's body contains member names their display name is translated before it is rendered. This happens for instance when a member uploads a new profile picture and thus creates the associated activity feed item ``{item:$subject} added a new profile photo.`` 

Steps to reproduce:

1. Create a new member or modify an existing member and change their display name to any string which is contained in the languages files, e.g. ``ADMIN_ACTIVITY_TYPE_TAGGED`` (use this string literally as the member's display name).
1. Execute any action which creates a new entry in the activity feed for this member, e.g. by uploading a new profile picture.
1. Navigate to the activity feed and find that this entry reads "**When a user (subject) tags another user (object) in photos and other places.** has added a new profile photo.". NB: The activity item shows the translation of this member's display name.

Additional hints:

This translation happens in ``\Activity_Model_Helper_Item::direct``. I think that the translation step starting around line 45 should at least be omitted if ``$item`` is an instance of ``User_Model_User``. Other item classes may also be candidates for this exception though I have not encountered such issues up to now.

**Comment by Anshuse** [comment]
Hello @rwetzlmayr , do you mean to say that User oriented feeds should not be Translatable and only Subject oriented feed should be Translatable? Please confirm.

**Comment by rwetzlmayr** [comment]
@Anshuse I think I meant none of that. What I intended to say is:

If the variable part of an activity item's body (i. e. the part which is embraced in brackets``{}``) resolves to a user's display name it is not useful to pipe this display name through the translator as it happens in SE 4.8.9. 

Example:

- Uploading a profile picture inserts a row into ``engine4_activity_actions`` with the ``body`` column set to ``{item:$subject} added a new profile photo.``.
- SE **should not** translate the ``{item:$subject}`` part as this is the user's display name.
- SE **should** translate the ``added a new profile photo.`` part as this is a localizable string and every user would want to read it in their own chosen language..

**Comment by smazurov** [comment]
Thanks for the reproduction steps. We'll take a look!

**Comment by Elshara** [comment]
If someone uses a name in non English Characters or a Spanish Name then I think that name should be a part of the translation.

**Comment by sgreiner** [comment]
I can confirm that bug. Usernames get translated by their display name. Tested Version: 4.8.11

**Comment by Elshara** [comment]
Yeah it's just translating the entire page content.
You want to know another related bug? If a name is misspelled or a
word is mistyped, you know what happens? The word is just left in its
original form making a ton of grammar errors for the user reading it.

**Comment by shivani2910** [comment]
Thanks to you all for reporting this. We've added this issue to our internal bug tracker. This will be fixed in the next release of SocialEngine PHP.

**Comment by smazurov** [comment]
Fixed in [4.8.12](http://blog.socialengine.com/2016/07/07/socialengine-php-4-8-12-is-here/)
