### ISSUE TITLE
Incoherent delete cascade upon user deletion

### ISSUE THREAD

**Issue by rwetzlmayr** [SocialEngine/phpv4-issues#352]
When a user is deleted, an avalanche of cascaded deletes is triggered through the ``onUserDeleteBefore`` / ``onUserDeleteAfter`` / ``onItemDeleteBefore``  event handlers for many item classes: Blogs, forums, albums, photos, abuse reports, core comments ...

Activity comments ``Activity_Model_DbTable_Comments`` are **not** deleted when their original author is deleted while core comments ``Core_Model_DbTable_Comments`` are.  I don't know if this is intentional or an oversight.

Keeping comments may be both desirable (if you want to preserve a conversation thread despite one member being deleted) or a burden (spammy comments). It even could be up to the administrator to decide which child items they want to keep upon user deletion as long as it does not threaten the site's data integrity.

**Steps to reproduce:**

1. Log in in as a regular member.
1. Add an activity comment to an activity feed item like 'X has just signed up'.
1. Log in as an administrator.
1. Delete the regular member from step 1.
1. Find that said member's activity comment is still present and crediting a 'Deleted Member' as the author.

![screenshot - 07 01 2016 06_37_55](https://cloud.githubusercontent.com/assets/357054/12162933/946c57c6-b508-11e5-908f-6e03e7ff009c.png)

**Comment by Anshuse** [comment]
Hi @rwetzlmayr , yes, you're right, we don't remove the deleted user's comments to preserve the communication. I've noted down your point to provide an option in the admin panel for the same in our internal suggestion tracker and look into the possibilities to implement it in our core module when we'll work on this feature in near future.

Thanks,

**Comment by rwetzlmayr** [comment]
See #222 for related discussion.
