### ISSUE TITLE
Bug: Social Engine Doesn't Display Names Properly

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#353]
It's become apparent to me in this day and age, it's impossible to sign up for something without having to write your name down somewhere. In the case of social engine, before your name is asked, there's effectively two main naming systems, three to be technically exact, and all profile addresses do is confuse people. Turning them off doesn't get rid of the ones used by existing members who have one, and when they are on, they are required, not because it is used as someone's name, but because it's used in replace of a profile ID. What a technical fatality in my opinion.
In fact, because it is real, it's prevented a lot of people from being able to sign up. They want to, but get so confused with the error messages when it comes to that particular field, it turns them off. I tried playing around with the language editor, to make the name sound like a name, not a technicality. All that ended up doing was confuse people further in why it was necessary. What's more, when they wanted to change their name, they'd end up changing their profile address not their profile name, which I might add, is also very crude in displaying itself. Why the hell can't a profile address be automatically generated when someone types in their name and why can't their name be typed in on the same screen as they would their email and password when signing up or editing their profile? This makes no sense to me and to a lot of other people. I'm tired of using several screens to get basic information down and out of the way. Never mind the fact that people can't use html in their profile information. Or even format any text at all.
I want to do away with the current system of sign up and profile information. I think the time has come to redefine how people share information. This is because their entire profile is not just for sharing everything about them, but what they contribute two as a network. I can personally tell you, filling out profile fields is becoming a thing of the past. Sure, Facebook uses a rather cumbersome system to have basic information displayed, social engine isn't that far better, but it can be. Make all non essential information a part of a separate profile area of their profile, where each question is sort of like a tab or interface that is dragable by user preferences. It just seems to me the name, gender, birthday and location of someone can be defined in a basic statistic, a search perhaps. Who needs a separate field entry for everything? Things should be user selectable. You type in your name on one line regardless of first or last name, you add in a field if you really want it separate. You enter your information about your location, gender and birthday in a statistics section if you want people to see it, and the rest goes into a separate bio that is away from the rest of the profile area devoted to mainly what people posted. Even that should be just tabs in a news feed. It is so cumbersome to have to deal with many widgets on a page, it isn't that well integrated at all and people only look at the news feed anyways. It'd make a lot more sense to put everything into one area and although we have the tab container to make it possible, there's a lot of unnecessary tweaks involved just to have a basic profile look good.
Having said that, my main concern is the names. Something should be done about the way in which names and content ids are displayed. I'd love to hide them altogether if I could and just use the titles as an updated interface for their URLs. It's time we do away with URL alt text for images while I'm on the subject. I think profile addresses make it far too confusing for people and if they're disabled, they can't change what is already there. Not just that, their profile ids do not link to their profile so the whole feature overrides even that. IT should reflect the username of whatever the person has as their display name, one field, one place to put it, right under general settings with their email, password, birthday, gender and location. everything else is optional, but I would love to see profile photos uploadable on that screen as well. It would make a lot more sense this way, trust me on this.

**Comment by Anshuse** [comment]
HI @Elshara , we appreciate your suggestions and the efforts that you put to make SocialEngine PHP better but it would be great if you can write your suggestions/issues precisely and concisely. This will help us to understand your point more clearly and thus, discuss your suggestions with our development team. We hope that way our communication will be more effective. So, please write down your query in points precisely describing what is the issue and what should we do to resolve it.

Thanks!

**Comment by alimoosavi15** [comment]
@Elshara Now that @Anushe mentioned this, I want to say that I like your posts, I've read most of them but a better paragraphing would also be nice.

**Comment by Elshara** [comment]
Sorry it got muddled up in the excitement.
Sometimes I try to be playful with words subconsciously without
realizing the point isn't always seen clearly I apologize. I love to
help. It's a personality thing I think sometimes my honesty can turn
into rambling so I don't mean to bore you. It comes from having people
live with me who are always like that.
Here are the facts.
Names in social engine php need a restructuring.
This is because the way they are created, appear and are updated do
not work for many people.
You have a profile address which people create when first signing up.
Unlike the actual name system that is usually displayed to people upon
signing up in other platforms, they have to manually type in the url
of their profile before filling in their name. It would be a lot
simpler if they filled in their name instead, making their profile
address automatically match whatever their name is upon sign up,
allowing users to both add spaces in their name, and be able to change
their profile address separately at a later time if desired.
I have tried playing around in language editor with renaming profile
address to username because a lot of people get confused at what to
type in this field not only because it is mandatory, but also because
they can't put a space there. The reason why people so frequently get
confused with this particular field is because that is normally where
a persons name ought to be upon signing up for something. At present,
it is not possible to make the field act like a name field should
because it is not a global field in terms of a single phrase. It is a
technicality that prevents people from wanting to sign up. disabling
it doesn't allow them to have a name at all.
The first and last name of profiles is okay, but it is hard to get at.
Not many people like having to split their name into two parts. It
doesn't look professional when you look at someone's profile
information and see the technicality of most people trying to split
their name into two separate fields. It should not have to be apart of
profile information at all. Usually when people sign up for a site, it
doesn't take three places for a name to appear independent of one
another to actually have it displayed. Particularly when accessing one
name is on a completely different settings page whereas the other part
is on edit profile page.
Speaking of profile information, It is much easier for users to fill
out account avatar, profile photo, birthday, gender and location
information on the same screen as their email, password and name. This
is how most setups work and what people are most used to. Having to
find different pages just to change something like that, is difficult
because most people look for it on the same page. Especially profile
photos.
I think the best way to solve this issue is to make one name field,
not three. Allow admins to select which questions appear on which page
as a part of the sign up process. What I mean is, allow admins to
control how many pages there are to the sign up process, and what
information gets recorded when users complete certain fields as a
security ability when they access such pages upon submitting their
information. Allow profile addresses to be changed separately upon
users creating their account, using a global name field to replace the
current requirement to replace profile addresses as opposed to user
ids when signing up for a site and allowing their name to be filled in
as a users first profile address once their name is filled out.
Based on real user feedback, a multipage sign up process is very
tricky for a lot of potential members because they do not expect it.
When they hit submit, they leave the page. Their account doesn't get
created and this is because they are not expecting to have to fill out
information on five pages just to have their information they already
did send in be saved. Currently, members expect after they fill out
their profile address, email and password to already have an account.
IT takes some users time to get used to the idea that they have to
verify their membership via email. This is only because they have
signed up for other services requiring the same thing and are not used
to the technical limitations of social engine and how the platform
works, preventing them from having an account at all if they don't
complete everything. This is not obvious to them as such. They think
once they do that their account is active, but instead, they have to
fill out a bunch of screens. This is very tiring for people because
they want to only hit submit once to have their account activated.
Whatever they miss will be filled in later so long as it isn't
required. This is how most platforms work.
In other words, allowing admins to optionally simplify the sign up
process with less fields and more global reliance on existing
information will make it much easier for both admins and users to
manage their information. Where names appear is the most noticeable,
but having pages of mini forms for members to fill out before becoming
a member, after realizing their profile address must have only letters
and numbers with no spaces because that is how crude they think the
naming system is, does not encourage people to continue using the
platform as it is and is why many platforms like phpfox and Ning are
so easy for members to sign up and not do anything on, as opposed to
social engine, where it is possible to do many things on, but the
inability to set things as simple as possible for that to happen from
sign up.
Please hear me out when I say the key points of this issue are as follows.
1. Names must be simpler in future if social engine wishes to be more
modern. One name field for everything with spaces and punctuation must
be allowed to replace the current way users enter their name. IT
should be placed at sign up where profile address currently is and
profile address will match the users current name or can be changed
independently later if enabled.
2. Making sign up simpler by allowing admins to control which fields
appear on which pages will also make things simpler. We don't need 24
pages of material for users to have to fill out just so they have a
profile. Everything should be straight forward and to the point for
new members to turn into active ones, we hope. Giving admins the
ability to select how sign up appears in terms of how pages are
structured, would allow us to select if sign up requires one page, or
many other pages allowing us to choose which fields gets recorded and
whether or not they are saved when a user clicks the submit button to
take them further in the application process of becoming a member.
Putting this bluntly, profile information is a thing of the past.
Merging that with creating a custom sign up process will make this
much easier for recorded information to appear under members accounts.
That is what I wish to make a reality. IT will help business as well
as social engine.

**Comment by Elshara** [comment]
Short version.
1. Change three name fields profile address, first name and last name
into one name field. Allow the functionality of profile address to
record current name upon ember sign up but could be changed later if a
member wishes.
2. Merge profile information and sign up process into one area. Allow
for admins to set up sign up process to be more efficient in what gets
recorded upon how users complete sign up process. Give admins the
option to cut down on how many pages are necessary for a members
information to be recorded and control over what gets recorded as
users complete required fields.
3. Replace id system with current title or name of content members
add. Instead of a post or profile being given a number, allow it to
have its current title or name as such. This would make much more
sense to keep numbering a back end process only social engine core
code would have to work with. A possible autogenerated screen name
would help a lot with this. I'm not sure if this can be done in php as
I have only seen this done in ruby on rails.
This all has to do with how names appear and are referenced as such in
social engine. The goal is to make it more easier and simpler for
users to record information as needed.

**Comment by Anshuse** [comment]
Hi @Elshara , 

1. Regarding "Change three name fields profile":
Only two types of name related fields are provided in SocialEngine. 1. Username 2. Display Name

- Username is the unique identity that a user selects at the time of signup process. Username can't be duplicated and it is unique identity of each user.
- Display Name of any user is combination of his/her First name and Last name.

So, this works fine and no changes are required for the names.

2. Regarding "2. Merge profile information and sign up process ":
We've noted down your suggestion at our end and will consider this in near future when we'll work on the improvements of signup process.

3. Regarding "Replace id system with current title ":
We already have a plan to implement this feature in our core module.

Also, thanks for sending over the queries in precise manner. Hope you'll follow same approach while reporting further issues.

Thanks,

**Comment by Elshara** [comment]
This is awesome news!
My simple request therefore, is if names could be changed slightly
upon signup so people could enter their full name instead of a display
name or username when signing up. The roles could be switched so that
the actual name itself is saved when people create their profile.
Usernames could automatically be assigned once they enter in their
full name as one field. IF two people enter in a name like John Smith,
the second John Smith would have an automatic number assigned to
indicate that is the second name based on profile url, but their
display name would remain the same. I'm also thinking of combining the
role of first and last name, so it shows up easier.
In other words, the sign up process could look like this. Ideally this
is what I'm thinking.
User clicks on Sign Up.
User types in their email address.
User types in their password.
User types in their full name using spaces or punctuation as required.
User clicks submit.
Their account is created instead of taking them to require more fields
right away.
They are prompted to login or are automatically logged in using those
credentials.
Unless email verification is required, they can choose to fill out
their profile right then and there, or could be redirected or choose
to be redirected if they clicked on sign up on a forum topic or blog
they wished to comment on from that page itself. This would
essentially allow them to finish what they wished to act on once sign
up was completed.
In this way, after completing that action such as liking an item or
replying to it, a user could be taken to a page where they could edit
their profile if those fields were not visible on the first seen sign
up page, or be taken to a page of their choice by them clicking on a
menu item. I'm thinking this could make it much easier for people to
stay engaged especially if they find a topic interesting and they wish
to respond to while not yet being a member to be able to allow this to
happen.
As stated previously, they wouldn't have to worry about choosing a
username right then and their, as their display name would appear
automatically without spaces or punctuation as a part of their profile
url. What I'm looking for is the ability to let users be able to sign
up for a social engine php powered site with that name used as their
profile url with a number beside it if the name is already taken so
they don't have to enter their own profile url as required when they
first sign up. This would function normally allowing people to edit
this later if required.
What I'm thinking for merging profile information and sign up process
is for admins to have the ability to arrange their own settings pages
having the ability to add fields on new pages if required and having
the option to include them in sign up process or not. Also a layout
manager for choosing how menu items appear for profile fields in
addition to what pages they are on would make this easier. Perhaps
having the ability to move one menu item to another could make this a
possibility, so instead of how profile questions work now, it would be
possible to arrange just as headings are possible, new pages so under
each new page, could be headings and profile questions as fields. So
assume I'm asking for the ability to add page capabilities to profile
information layout editor for such fields. This could make all the
difference in the world having the ability to merge such sections
together, it could be a simple check box allowing such a question to
appear at sign up, where if yes, and if it is required at sign up or
not which would therefore be required if people fill out their
profile. It'd also be interesting to set up member levels this way so
people could fight spam by if not filling out a profile question
correctly, their access could be restricted in some way to the site
itself.
These are ideas I'm tossing around.
Thank you for the suggestions in our future communication. I don't
mean to make it challenging.
