### ISSUE TITLE
BUG Updating Yotube API Key

### ISSUE THREAD

**Issue by lovettmade** [SocialEngine/phpv4-issues#354]
I am experiencing an issue when I attempt to update the API key under the video plugin's global settings. After I enter the youtube API key and press save, the page reloads as if it is saving however it returns to the page with the API text field blank as if I had never made a change. There is also no default value in the field which after looking in the code there should be, however I am having trouble finding other sections of the code to see where the problem might be causing this issue.

In the meantime, nothing I enter in the Youtube API key field under the video's global settings is actually submitted - nor am I presented with any type of error message. It is just as if it is reloading the form when I hit submit and clearing any content I've entered. Another note is that every other setting on the page is updating properly.

 I've tested the video feature to see if it was submitting but found that Youtube still was not an option upon submitting my video.

Please let me know if there is a quick fix to this issue, or which I might find the code to fix it myself.

**Comment by Anshuse** [comment]
Hi @lovettmade , we're not able to reproduce this issue at our end and thus issue seems to exist specifically in your installation so, you may create a support ticket and our support staff will debug this issue on your site.

Thanks!
