### ISSUE TITLE
Suggestion: Colored names

### ISSUE THREAD

**Issue by fineh** [SocialEngine/phpv4-issues#355]
Hello,

Colored names based on groups exist for years now, almost all forum boards are using it.

Since SocialEngine exist of member levels, can't we do the same but based on member levels?

All you need to do is add a option to provide our own "Formatting Prefix" for member levels.

So that we can add codes to member levels like:

<///////span style='color:red;'>

$username
or
$first name 
or
$lastname 
or
$displayname

</////////span>

Result = </////span style='color:red;'> nameofuser</////span>

$username = username of member
$first name = first name of member
$last name = last name of member
$displayname = display name of member

**Comment by Anshuse** [comment]
Hello @fineh , Thanks for your suggestion, we have added this in our internal suggestion tracker and we'll look into the possibilities to implement this in our module.
