### ISSUE TITLE
Bug: Still able send private messages after being blocked

### ISSUE THREAD

**Issue by fineh** [SocialEngine/phpv4-issues#356]
Hello,

I had a issue today in my social network.

Member A was able to receive messages from Member B after blocking Member B.
Only difference was that Member A and Member B couldn't reply to the private messages but were still be able to send a new ones to each other.

I assume this is a bug with socialengine.

Can this be fixed?

I am using latest version of socialengine.

**Comment by Anshuse** [comment]
Hello @fineh , 

Please accept our sincere apologies for the delayed response. 

This issue is already added in our internal bug tracker and we have plan to improve the Block feature in our core module in near future release.

Thanks!

**Comment by DonnaScriptTechs** [comment]
This is fixed for 4.9.0 when it is released.If you still have this issue after we release, please open a new bug report.

**Comment by Elshara** [comment]
Awesome!
