### ISSUE TITLE
Make A Sign Up Widget

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#357]
We don't have one yet. We just have a login widget so far.

**Comment by Anshuse** [comment]
Hello @Elshara , we've added this in our internal bug tracker for the internal team discussion to implement this in our module in near future release.

**Comment by alimoosavi15** [comment]
This is very important. SocialEngine sign up process is very long and it needs to be a shorter process available for the site owners to activate.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#21

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
