### ISSUE TITLE
Change The Way Layout Editor Modules Appear

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#358]
When dealing with the layout editor, it can sometimes be tedious to have to browse for the modules you want. Clicking and dragging things into position becomes harder to do the more third party modules you have.
Rather than having to scroll through to the exact widget you like, simply having a drop down menu to do that would make it easier. That way, you could use a button to add content, allowing widgets to appear at the bottom of a specific column once you find the one you are looking for. Through a series of drop down menus, you could be able to select the module you want, such as blog or forum, the type of widget you want, such as a menu, search or content display, then finally the type of display you would like the widget to have such as no titles, a limit on descriptions if enabled, the ability to count how many items you want, the ability to list things that can be resized such as tables or lists, even the ability to sort items by newest, most popular, or allowing the user to do that from their end and the ability to include in widget like, comment and other information ares which could optionally give detailed interactivity right from a specific location by the use of check boxes as things one could opt to include for a given item. For example, if someone used such a feature to add newest blogs, one could sort blogs as a table rather than a list, by most popular allowing members to choose what they can sort blogs by from their end with that as the default by use of a checkbox or radio button, allowing quick actions to be enabled via ajax on the same page using the widget inline options at the end of a list to do things such as comment on the blog, read more, view who liked it, like it, feature it, remove it or edit it if admin, view its statistics and message its publisher. At the end of a widget, global options could be applied such as in the blogs case, view all blogs, view all blogs in current order, search for a blog keyword, add a blog or view all personal blogs. In this way, all modules could be set up using similar criteria if supported. Naturally menus would not be applicable for many of the options detailed above, however one could for example, hide the title of a menu or create a new one if desired if they were to be added to a tab container to make it more visually appealing.
Each drop down menu would have the ability to be user default which could make it much easier for members to get to the type of content they wish to look at without having to actually do a full site or module search if they simply wish to see what is new or most popular in a specific way.

**Comment by Khushboo016** [comment]
Hi @Elshara , Thanks for your concern and suggestions, we would like to tell you that we already have many plans for the Layout Editor to be implemented in our near future releases, so, we'll take into account your suggestions also, when we'll work on implementation of those plans.

Thanks again!
