### ISSUE TITLE
Make All Supported Modules Apart Of Social Engine Package

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#359]
For years social engine has bundled each module separately. I think as a security option, bundling them altogether and charging one fixed price could make it more convenient as a whole.
This way modules could be optionally installed when refreshing future social engine packages and could always be disabled from package manager. Having a quick set up wizard could set all global modules as needed, therefore making social engine easier to manage, particularly when it comes to things like global html tags, email settings and user preferences.

**Comment by SpiritWolfie** [comment]
One thing that annoys me about this is the following

if you go to the website it says "Buy this addon" - forums, you click it and instead of letting you buy forums it wants you to upgrade your entire package, even know it says you can buy it as a addon as seen in the client store

**Comment by alimoosavi15** [comment]
SocialEngine is structured to have modules and all official and 3rd party modules are depending on this structure to add features to SocialEngine. There's no security risk in having separate modules and from a developer's perspective this a great advantage of SocialEngine.
