### ISSUE TITLE
Search History

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#360]
Places that provide search these days are coming up with the ability to view someone's search history. As an admin, it may be important on an active network to have this feature enabled to help keep things safer. If social engine provided this, it would be very easy to spot people searching for things which could help if necessary, people find what they are looking for on or off site. IT could also help measure the type of content people are looking for which could make it easier to be found on one particular site by researching it independently.

**Comment by smazurov** [comment]
This is not something we're interesting providing. Although somebody can implement it as an add-on.
