### ISSUE TITLE
Chat Improvements

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#361]
It isn't possible in social engine to have chat boxes as an integral part of who is online. Chat doesn't update itself very well, nor does the online users match true records. Sometimes they get stuck, particularly when moving from one page to the next. It would be nice to see this fixed.

**Comment by Anshuse** [comment]
Hi @Elshara , a Task called "Chat data maintenance" needs to be run frequently enough to update the members in the chat bar. If this task runs frequently then members get updated in the chat bar accordingly. We have released an article on the same: http://support.socialengine.com/php/customer/portal/articles/2170953?b_id=4311 that might help you.

Thanks,
Anshu
