### ISSUE TITLE
Create New Post From Activity Feed

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#362]
As the buttons for creating blogs and forum discussions are quite similar, it would be interesting to be able to do so from the activity feed or as its own widget. Through the use of ajax, it could be possible to make a post on the same page you are on without having to search for the ability to add something. In this way, the form could use a trigger method to determine where a post should go by giving you a drop down menu to choose where you want a post to be placed if you select forum or group or profile, but you can choose to put it as a status, forum topic, blog post or group forum topic. If forum topic or group forum topic is selected, you can choose where you want to place it and have it post there automatically directing you straight to it once it has been successfully posted. Using a simple form to control globally how posts are placed, may give people a lot more incentive to post things from a central location, but have it appear where they want. Making that part of the process optionally required, will help in this way. IT would be nice to be able to do this for a global file uploader as well, giving you the ability to post a photo, song or video or collection of photos, songs or videos respectively through tabs and ajax in the same way. The creation of a new playlist could be complete in this way and could be edited once completed.

**Comment by Anshuse** [comment]
Hello @Elshara , we have noted down your suggestion at our end for internal team discussion.

We're closing this case for now but will open it again once it gets approved and we'll start working on this.

Thanks,
Anshu
