### ISSUE TITLE
Redirection Issue When Creating New Posts

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#363]
When creating a new post such as a blog, forum topic or anything else requiring currently its own upload space, as in add new, when a post is created, it is not immediately seen once published. A user is taken to the page where all of their posts appear, and not the latest one they just made. It would be nice if that happened.

**Comment by Anshuse** [comment]
Hi @Elshara , when any new Blog or Group is posted then the user gets re-directed to "My entries" or "My Groups" page, which is fine:

![1](https://cloud.githubusercontent.com/assets/11085507/12480675/ffbade14-c069-11e5-9aa7-9305d8c89652.png)


![2](https://cloud.githubusercontent.com/assets/11085507/12480684/1513e468-c06a-11e5-99e6-89bffb09b802.png)


You can check the same on our demo site.

Thanks,
Anshu
