### ISSUE TITLE
Files Uploaded Don't Import Meta Data

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#364]
When uploading videos, photos or music, meta data which automatically tells you the title of a file if nothing else, isn't imported. It would be nice if this could be done. This way when uploading files, you can edit how they are seen by changing what gets fully imported before completing the upload process. If requesting information from youtube, this could be much simpler rather than having to copy and paste titles and descriptions. The same goes for photos, songs and videos respectively. Removing the ability for every file to have an album, would make this a lot easier to manage. A lot of times, files aren't seen in social engine because of the fact they are hidden by albums in indexing pages.

**Comment by Anshuse** [comment]
Hello @Elshara , currently when YouTube and Vimeo videos are imported on SocialEngine site then meta data i.e. Title and Description gets fetched automatically.

![yoitube](https://cloud.githubusercontent.com/assets/11085507/12480471/94342ce6-c068-11e5-88cc-93630003fd01.png)


![demo](https://cloud.githubusercontent.com/assets/11085507/12480472/9435d37a-c068-11e5-9f9d-d1ad1755c4ba.png)


But if any music or video file is uploaded from local computer then user will need to enter the meta-data manually as it's not possible to fetch their meta information on SocialEngine site.
