### ISSUE TITLE
140 Pizzas

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#366]
140 Pizzas at $5.00 per pizza, $699.00 with one dollar tax, the cost of one social engine license, excluding support or upgrade costs.
Is that necessary in this day and age? Where platforms like OSSN and Elgg among others cost nothing?
Everything looks good for the future of Social Engine. The cost used to be or seem much less at one time.
What about a monthly cost for social engine php. Yes it costs less because we end up paying a few hundred a month for dedicated servers for serious clients. But with that in mind, is social engine truly that desperate for money for, research and development as a business? I'm curious statistically if things are that bad in 2016. Ning wants a lot of money these days as does phpfox now that their flagship products are going down hill even though they'd never admit to having faulty management. Social Engine is the only product I can say that has kept its cool and is going strong.
I love the fact that it has recently one the 2015 cms critic awards. But will a decrease in price make that more of a certain future for people interested in the software? Maybe even dropping it down to $500 or perhaps $300 could make that a possibility?
Perhaps only paying for a license would make that a possibility. Everything else be extra, though included would be the default plugins covered by an individual license or group of licenses, perhaps even support coverage could be applied in this way. It just seems one time costs are less favorable just because they are much higher, than something monthly though that is recently starting to change, unfortunately with cloud based companies losing interest because of their bad management practices.
One such company that is not losing favor, is Jamroom. They've taken it upon themselves to start a hosting business to decrease the cost of in house made plugins to nothing while people pay monthly to keep their sites up and running. Otherwise people who use their software hosted on their own, pay a one time cost for an individual plugin, some are free including the core, others are not. This was customer suggested and is customer and client funded.
Social engine, if presented with a dedicated hosting area, could bring in so much money because everything could already be set up for such a purpose in a cheap way, bringing both business and infrastructure to the company. Social Engine cloud, is not social engine php however. If it were, people would be glad to have the option of hosting their community on their own server, paying the difference if they wished to do so originally, but it would be a one time cost on the company side of things, everything else would belong to another service unless a migration occurred.
If the price was right for low and well as high budget customers getting the same use out of great software, perhaps turning into something similar to open source with paid support would make all the difference in the world based on a cloud licensing structure.

**Comment by Elshara** [comment]
PS. I personally voted for social engine in cms critic awards three separate times last year.

**Comment by qoutas** [comment]
I don't mind paying a lot for quality. Until now socialengine has worked fine. Few things that are missing will hopefully be added or fixed in the next releases. Also higher costs will stop people from copying my social network site with a exact clone.

**Comment by Elshara** [comment]
Quality I can stomach. It's just nice to know social engine isn't the
only company with money on its mind when it comes to efficiency.
Perhaps I'm being a little paranoid.

**Comment by smazurov** [comment]
You bring up fantastic points. We've read your post and have had conversations around it. Since it does not pertain to the purpose of this channel of communication I will close this issue, but thank you for words.

**Comment by Elshara** [comment]
I appreciate your consideration truly!
