### ISSUE TITLE
Extract Error: No packages found in archieve

### ISSUE THREAD

**Issue by abhimanyubind** [SocialEngine/phpv4-issues#367]
I have created a module and exported it from the administration panel but when I try to install the newly  created module it gives "Extract Error: No packages found in archieve" message.

**Comment by Anshuse** [comment]
Hello @abhimanyubind , 

Please try following steps at our end:

1. Give 777 Recursive permissions to /temporary, /public and /install/config directories and try installing plugin.
2. If that doesn't resolve the issue then try uploading .tar file of the plugin in the temporary/package/archives directory on your server and try continuing the plugin installation from the Package Manager.
3. If above doesn't work then replace /install folder with default one and then try to continue the plugin  installation from the Package Manager.

If none of the above works then please file a support ticket or send an email to support@socialengine.com along with your site details.

Thanks,
Anshu
