### ISSUE TITLE
HTML5 Photo Uploader

### ISSUE THREAD

**Issue by nizhnyk** [SocialEngine/phpv4-issues#368]
Update/replace FancyUpload with something that supports HTML5 upload.

Without Flash installed, users are unable to upload photos into their album. They can select only one photo at once and "Save Photos" button is not showing up.

At this time it is not right for a website to ask user to install Flash Player, since so many websites don't even depend on Flash anymore.

**Comment by beevcra** [comment]
Totally agree not having multi-photo upload is a massive issue (getting the error message is a reputational risk) , when competing against other sites. Basically if any feature doesn't work on an ipad/iphone then basically 80% of my SE users will suffer.

**Comment by Khushboo016** [comment]
Hi @nizhnyk , @beevcra , The issues which both of you've mentioned here are two different issues, and  we've forwarded both the suggestions to our internal feature tracker, so that we can discuss and try making an improvement regarding these features in our near future releases.

Thanks!
