### ISSUE TITLE
Email Delivery Issue

### ISSUE THREAD

**Issue by meetgerry** [SocialEngine/phpv4-issues#369]
For the last 1 year, I have experienced 1 common issue and I thought of reminding it here. I know it makes no much of a difference because you guys take 8 months to release a set of 10 bug fix.

By the way the issue is, any email registeration with single alphabet domain like email@i.ua the activation emails are not ever sent to this email ID.

**Comment by smazurov** [comment]
#344 might be able to fix it for you. Let us know if it does, then we'll consolidate and address it more specifically there.
