### ISSUE TITLE
 wrong setup in code

### ISSUE THREAD

**Issue by marcusfsza** [SocialEngine/phpv4-issues#37]
wrong setup in code, it should be like this Asia/Tehran not just Iran

**Comment by Anshuse** [comment]
Hi @marcusfsza ,

Thanks for reaching out.

If seems that you're talking about the timezone which displays on the signup form, if so, then you may customize the code as per your requirements by editing "Account.php" file at path /application/modules/User/Form/Signup/Account.php

Best Regards,
Anshu
