### ISSUE TITLE
publish_actions permission

### ISSUE THREAD

**Issue by patrys666** [SocialEngine/phpv4-issues#370]
Hello, i have a problem with publish_actions permission. I'm trying to signup with Facebook but only on popup appear,the second for publish_actions doesn't show. Where's problem?

**Comment by smazurov** [comment]
You need to manually apply for this permission. This is covered on our KB: http://support.socialengine.com/php/customer/portal/articles/1796979?b_id=4311

**Comment by patrys666** [comment]
I have accepted this permission by Facebook
