### ISSUE TITLE
Session Hash length

### ISSUE THREAD

**Issue by cgcb** [SocialEngine/phpv4-issues#371]
In Apple's implementation of Apache/PHP, session.hash_function is set to sha512, which generates a 128-character hash. The db table truncates at 32 (because SE4 is expecting md5 no sha512).

This triggers the following error in SocialEngine:

exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Duplicate entry

Simple fix: The hash column in the session DB should be enlarged to 128 chars to better support more modern algorithms like sha512 (which is dramatically more secure than the old md5).

**Comment by Anshuse** [comment]
Hello @cgcb , you can increase the value of number of character allowed in the ID column to 128 by following below steps:

- Go to table ```engine4_core_session``` of your site's database.
- Run following command from "SQL" tab:

```php
ALTER TABLE `engine4_core_session` CHANGE `id` `id` CHAR(128);
```

![command](https://cloud.githubusercontent.com/assets/11085507/12749577/9b49a8d0-c9d7-11e5-8865-f84e7009a4c9.png)

Thanks!

**Comment by cgcb** [comment]
Wait, I know how to increase the column char count. But database changes like this shouldn't be necessary for end-users. I'm reporting this so that it can finally be addressed in a future release.
