### ISSUE TITLE
Insert video option not working in blog posts

### ISSUE THREAD

**Issue by maxx24** [SocialEngine/phpv4-issues#374]
A few months back, I posted an issue about the "insert video" option not working in the text editor of blog posts.  Also, you cannot add embed code by using the source code button either.  Someone responded with some type of work around, but that discussion has since been deleted. What can we do to make this work, and why has this not been addressed in updates??

**Comment by Anshuse** [comment]
Hello @maxx24 , no such issue exists in the core module. Please make sure that "embed"  and "iframe" tags are added in the "Admin" > "Plugins" > "Blogs" > "Member Level Settings" section of your site for the required Member Level. If these tags are already added and you're experiencing the same issue then we suggest you to please open a support ticket from https://www.socialengine.com/client/ticket/create and our team will help you out. Thanks!

**Comment by Elshara** [comment]
I reported something similar to no avail. So guess what, the fight isn't over until there's nothing to fight about.
Try making sure https is disabled then embed a youtube video. You need to use the html5 player. Script tags don't work. I've tried.
