### ISSUE TITLE
xCache same caching ID problem

### ISSUE THREAD

**Issue by Hostiso** [SocialEngine/phpv4-issues#375]
Hi, please set cache_id_prefix in cache.php to be auto-generated because with xCache if same ID one site can show some content from other site etc. basically sharing same cache,

**Comment by Anshuse** [comment]
Hello @Hostiso , we've noted down this issue at our end for internal team discussion and our development team will required action to implement the same in our module.

As of now we're closing this issue and will open it once we decide to work on this.

Thanks!

**Comment by smazurov** [comment]
If you wish to use a single cache for multiple SE PHP installs, please set the cache_id_prefix yourself when configuring it. Note, sharing cache between unrelated installations is a security risk and should not be happening in Shared Hosting environments. If it is, please address this internally @Hostiso.
