### ISSUE TITLE
Create Notifications Widget

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#377]
A notification box is available from a link at the top of the site in mini menu. But there's no way to reorder that link in menu editor, or the way the search area is displayed. It may even be a good idea to optionally get rid of search if desired.
Besides getting rid of the mini menu, there should be a functional way to include a notifications widget that can be placed anywhere in a page layout. This would give us the ability to include them on member home page for example, along with showing recent messages and requests. This widget would be very useful for members to check their most recent notifications without having to do so by clicking on the updates menu at the top of the site.

**Comment by Anshuse** [comment]
Hi @Elshara , 

Regarding "Notifications":
You have reported the same issue earlier #97 and we have already added this feature in roadmap of 4.8.9

Regarding "Notifications widget":
Currently, notifications get displayed in the mini-menu clicking on which displays all the notifications. If we will create a widget for notifications then we'll need to write heavy database queries to auto-populate the notifications that may affect site performances. So we don't have any plan to create such widget in our module yet.

Thanks!

**Comment by Elshara** [comment]
The truth of the matter is, that functionality is already being
populated every time the database is called to check for new updates.
This would be the same thing if the widget is placed on a particular
page. It would not effect the performance of the site because the code
is already being called on all pages.
