### ISSUE TITLE
Create Recent Comments Widget

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#378]
Comments are a great way to keep track of what is being said across the site. It would be very creative to show a recent comments widget, so it can show how and where comments are being placed, with the option to select what kinds of comments should be displayed.
The comments widget could be placed anywhere in the layout editor for pages. A nice way to view comments, would be on the home page of each module, so that in browse pages, including the member home page or visitor pages, people could view what blogs, forums, events, groups, profiles and other things were recently commented on.
Add the option to show likes and who shared the item would also be nice for this widget along with the date it was published and who viewed it or how many times it was viewed.

**Comment by Anshuse** [comment]
Hi @Elshara , thanks for your suggestion. We're sorry to say but we don't have any plan to create any such widget in our module. Creating such widget will require heavy database queries that will affect the performance. Also, each plugin has it's own widgets so, you can use those widgets and if you need to make any changes in those widgets then you may do it at your end.

Thanks!

**Comment by Elshara** [comment]
Thanks for the update.
