### ISSUE TITLE
Feature Request: SE PHP Native Responsive Theme

### ISSUE THREAD

**Issue by tkshredder** [SocialEngine/phpv4-issues#38]
Please consider this a formal request for making a new standard responsive theme for SE:PHP. I see that you now have Responsive theme support for SE:Cloud, but for devs like myself going for a fully custom standalone install, it's quite shocking that SE:PHP does not have a responsive theme out-of-the-box, and instead requires that I purchase one via a 3rd party. The lack of mobile support for a site in 2015 is frankly unacceptable and not forward-thinking. Hoping to see this rectified in the next major release.

**Comment by MeisterG** [comment]
I have already requested for this before except it was in the comments section of their blog. I do hope they release a nativeresponsive theme for PHP without having to add or depend on a mobile plugin

**Comment by shivani2910** [comment]
Hi @tkshredder and @MeisterG, 

Thanks for providing your valuable suggestions. We are glad to tell you that we've already planned to release a responsive native theme for SocialEngine PHP in the upcoming upgrades.

Thanks for your feedback and support!

Best Regards,
Shivani

**Comment by tkshredder** [comment]
Excellent, thanks for the update, Shivani! Just curious, do you have a
rough estimate as to when that might become available?

**Comment by shivani2910** [comment]
You're most welcome! 

We're planning to bring this in one of our major upgrades that will be available in the next 2-3 month hopefully.

Best Regards,
Shivani

**Comment by TheGreatAlexander** [comment]
@shivani2910 since you are creating a new template I suggest you also improve usability in the new design.  I suggest you look at littlemonsters.com. Attached you will see the best possible way a post should look like:
![anatonyofapost](https://cloud.githubusercontent.com/assets/1947524/8295973/8a99b128-1907-11e5-80cc-caf48cdd0f85.jpg)

**Comment by TheGreatAlexander** [comment]
@shivani2910 Here is a great way to organize the navigation of hot/new 
![navigation](https://cloud.githubusercontent.com/assets/1947524/8295992/ccb012aa-1907-11e5-8938-a0b89fa56c62.png)
information:

**Comment by TheGreatAlexander** [comment]
@shivani2910 Here is a great flow of posts.  See how appealing it is to see them and how easy is to understand them.  
![postingflowsample](https://cloud.githubusercontent.com/assets/1947524/8296013/14ea72c2-1908-11e5-858c-6d435eec333e.png)

**Comment by TheGreatAlexander** [comment]
@shivani2910 I just posted some layouts and information organization that if you take into consideration for your next theme, it would make Social Engine the best choice.  If you need to reference as to the interaction and how are the elements posted supposed to work.  Log into littlemonsters.com.  They have millions of users and have done a great job into taking their feedback and simplifying the user interface.  If you need any assistance you can contact me and I will gladly give you further information.

**Comment by TheGreatAlexander** [comment]
@shivani2910 @smazurov Do you have any questions/feedback about the comments I made above?

**Comment by tkshredder** [comment]
No, and actually we've already decided to go with a different platform.

On Wed, Jun 24, 2015 at 7:14 AM, TheGreatAlexander <notifications@github.com

**Comment by smazurov** [comment]
@TheGreatAlexander 

> Do you have any questions/feedback about the comments I made above?

This is fantastic feedback, we'll definitely take it into consideration when working on the new design.

**Comment by TheGreatAlexander** [comment]
I am confused @tkshredder said you will not.  This feedback I have collected over the time that I have been on social engine. @smazurov Could you confirm you will use it?  If so, I am willing to be available to you for anything you may need.

**Comment by smazurov** [comment]
@tkshredder is not an SE Employee. I can't confirm if we will use it or not, but all the feedback is valuable to ensure we address the needs of the community makers.

**Comment by smazurov** [comment]
this has been moved to #150

**Comment by smazurov** [comment]
We will use feedback from this thread so no need to re-post it, but if you have any additional or new feedback, please post it in #150
