### ISSUE TITLE
Create Recent Status Updates Widget

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#380]
There doesn't exist the ability to show recent status updates from different members.

**Comment by Anshuse** [comment]
Hi @Elshara , thanks for your suggestion, we don't have any plan to create any such widget in our module but we've noted down your suggestion in internal suggestion tracker. Thanks!

**Comment by Anshuse** [comment]
Hi @Elshara , thanks for your suggestion, we don't have any plan to create any such widget in our module but we've noted down your suggestion in internal suggestion tracker. Thanks!

**Comment by Elshara** [comment]
Thanks for the update.
