### ISSUE TITLE
Create Data Selection Widget

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#381]
This widget would be available from social engine core and would be able to showcase based on module availability, the types of things that could be available to build within a widget itself.
Whether the widget has different sorting types of data.
How the data is displayed.
How the data is repopulated or if it is randomly selected.
Who is able to see the data.
Who can interact with it and what types of interactions are allowed from the same page.
In this way, it would be very easy to create a site builder where multiple instances of this widget can make data availability very creative, and would allow people to position it to achieve the types of results they want. No more having to create tab containers just to add multiple data selections and filter options into a box, this would be possible all through this central control widget.
Allowing a target or user customized selection of how data is appeared along with its default setting applied in layout editor would make this possible.
A series of check boxes would allow a unified interface presenting ajax based functionality to visitors and the set up process alike.
This would be the one thing that would make social engine a design studio. Having this available as a theme editor would also make any social engine site shine where ever it is found.

**Comment by Anshuse** [comment]
Hi @Elshara , thanks for your suggestion. We're sorry to say but we don't have any plan to create any such widget in our module. Creating such widget will require heavy database queries that will affect the performance. Also, each plugin has it's own widgets so, you can use those widgets and if you need to make any customizations in those widgets then you may do it at your end.

**Comment by Elshara** [comment]
Thanks for the update.
