### ISSUE TITLE
Bug When Updating Menu Items

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#384]
If you add a new item or edit an existing menu item under menu editor and try to navigate to another menu, it saves the changes automatically but won't let you navigate away from the menu you just finished working on.

**Comment by Anshuse** [comment]
Hi @Elshara , we're not able to reproduce this issue at our end and if you're facing this issue on your site then you may file a support ticket along with your site details and our support staff will guide you.

Thanks!
