### ISSUE TITLE
Bug When Switching Mail Modes

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#385]
Under social engine mail settings, a bug occurs when attempting to switch mail modes.
Switching from php mail function to smtp works, however switching back from smtp to php mail doesn't. The save changes button doesn't appear making the setting disabled.
Additionally as seen in the latest version of social engine, smtp settings even if they are correct, does not allow any mail to be processed. I've tried using three different servers in non ssl and ssl configurations respectively. The social engine instance I'm testing is situated on cloud linux. This is a software bug.

**Comment by Anshuse** [comment]
Hi @Elshara ,

Regarding "when attempting to switch mail modes.":
We're not able to reproduce this issue at our end and if you're facing this issue on your site then you may file a support ticket along with your site details and our support staff will guide you.

Regarding " smtp settings even if they are correct, does":
We haven't done any work related to SMTP in the latest version and we're not able to reproduce this issue at our end. If you're facing issues with SMTP on your site then you may contact your hosting provider to look into it.

Thanks!
