### ISSUE TITLE
Make Global Columns Possible In Layout Editor

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#387]
In the layout editor, you can have either one of a few different configurations. Standard one, two and three column layouts. Independently of those, you can have a global top and a global bottom piece. You can't have a global top and bottom piece as a part of a column layout. It would be nice to add a custom header and footer here so that both can be updated if necessary. An excellent use for this requirement would be on a page where ads are displayed but only pop up from the bottom while using the top to customize the head of a particular page. This would automatically make things easier for advertisers to use both global areas of a page while keeping the center and sides open to whatever custom content mixed with a widget or two. Slide shows would go perfect in the wide column areas so having that option available, along with the ability to change the column widths would make it ideal to create any number of column configurations.

**Comment by Khushboo016** [comment]
Hi @Elshara , There are only Global Header and Global Footer in any page, if there is need of placing any header or footer in any column of the page layout, then there can be placed any other widget like "Html Block" to add the header or footer to that specific column. 
Thanks!
