### ISSUE TITLE
Bug When Adding Activity Feed To Footer

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#388]
There are times, when I experiment with widgets, only to find them unable to be dragable to global areas of the site. Like for instance, the profile links widget, the requests widget, the comments widget etc. One of the most noticeable things members look for when going to a social site, are things to interact with. Two days ago, I came up with a brilliant plan to add the activity feed to the footer. The problems started when I went to post content in the forums.
The activity feed filters out everything when I browse from page to page. In other words, content can't be engaged with, let alone the ability to post status updates from the feed while visiting anything content related. Browse pages work, but that's just more distracting in my experience. People often look for a sense of direction in what to do next after completing a task. If they can't find it, they go somewhere else that requests their attention, usually this means away from websites, into emails, into other programs or away from the internet altogether. This is why I figured having something engaging on every page of the site, would make them more inclined to stay, rather than just getting a link at the top of the site informing them they have new updates to things they subscribed to. In other words, was only aware of by personal interest or recommendation, not by reading it naturally, the way most social sites work.
My goal is to make this more apparent for social engine users. It is not just the activity feed that has problems displaying, but the chat box as well. Dragging that into the footer causes it to not work in the forums section at all, and only some of the time when a comment box is open in a blog post or other content item where comments feature appears. This is because only one instance of tinymce should be displayed, but instead, it displays where ever an edit box appears, only making the first one viable. The others don't record any data in them, the reason for status updates and the chat not working, making the whole thing a waste of time and space to put in the footer. Not just that, but the filtered feeds make it impossible for users to get a feel for what else is happening in real time for them to take a look at. The same issue occurs when browsing private messages, composing anything or editing a post.

**Comment by Khushboo016** [comment]
Hi @Elshara , Some widgets are designed specifically to be used in only some specific areas of the webpage keeping in mind the space that the widget requires to be displayed properly, like Activity Feed is designed for main content page of the site and not for Site Footer or Header, so it does not work fine in the Site Footer. Same is the case with Chat box, it is also designed to be placed in a specific area, so, you cannot place it in footer. Hope you understand our point.

Thanks

**Comment by Elshara** [comment]
I understand what you mean. If the header and footer areas along with
the rest of the page layouts and columns had responsive widths this
wouldn't be an issue.

**Comment by Khushboo016** [comment]
Hi @Elshara , it would not be a good idea to make page layouts and columns having responsive widths. Consider the case in which a very much wider widget is placed along with a very narrow widget in a column of the page layout. Imagine the overall look of that page, it would be quite distorted and unpleasant. So, keeping this thing in mind, we have not made the layouts to have responsive widths. 
Thanks !

**Comment by Elshara** [comment]
Should the widths be responsive for modules, this wouldn't be an
issue. Adding a responsive module width to a responsive layout column
would actually solve this issue entirely. Should a module take up as
much width as it is meant to, then it wouldn't make a difference. At
least it would fit on the page?
I thought of two possible alternatives for this.
1. Providing a minimum and maximum width option for columns and or
modules respectively.
2. Resizing module widths to fit the maximum dimensions of a column.
Using padding as extra spacing if need be.
3. Bonus side alternative. Allow each module to have its own defining
CSS class editable inline with a default structure. This could also
include module templates.
The other unspoken option is to have a tabbed column. This would
function similar to tab containers, but if a tabbed column is in
place, modules could utilize the space of tabs therefore creating
custom side bars along with responsive columns that make any module
fit on the page without having to bother with widths at all. Tabbed
columns would make it possible for any module to show more data just
by revealing certain parts of content within the module, allowing the
content to scale in both height and width as the space is required by
interaction of a given tab within a column. This way you don't have to
bother with much spacing, but instead, have one column with many tabs
facing whatever dimensions a specific content piece has the volume to
support if available, but also requires a such in its fullest
potential.
Tabbed columns would make it possible to add a column or remove a
column as needed without having to completely destroy columns with
widgets in. Similarly, tab containers could be set up to where the
widget contained inside them could be saved if the actual container
was removed. Columns themselves could appear as a widget allowing the
column itself to be positioned on a page. The global header column or
footer column could show up as a part of the page, where they belong,
or elsewhere. Individual column widgets would make responsive design a
possibility within social engine. Since a column is only defined as a
certain width on a page, that width could scale as needed but also
could be made available as a part of a table of columns so instead of
being limited by vertical long scrolling widgets, they could also flow
horizontally. This way the width in appearance equals the height of a
module, while it could actually address many modules parallel to each
other at the same spot on a page. This could also be done by shaping
how the column structure appears by drawing its exact point of entry
and exit is dimensionally so that it would appear as such on the
screen, possibly eliminating the need to scroll at all for the end
user. Drawing the column dimensions on the screen could be used as a
custom art form for the website design, therefore drawing patterns
around each module having the ability to preview the page from the
page options area.
