### ISSUE TITLE
Create A Promotion System For Member Levels

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#389]
A lot of third party plugin providers, have made it possible to add a credits or points system for social engine. The problem is, there's nothing that can link points to member levels. If social engine provided a way for members to automatically upgrade to a more accepted level of control on the site by participating more, this system could effectively bring more attention to real users, leaving spam bots and fake profiles at the door.
People enjoy getting rewards for things that bring pleasure. this encourages them to be more interested in communicating with other users. The point for a lot of social sites, is for people to forget the fact that they are using an online system to communicate with someone engaging, but for them to simply be able to share what is on their mind with that person. Member levels set the stage for their communications to be observed and interesting towards by the level of content that gets posted by users. The higher the quality, the better the site. The more diverse a site becomes, the more easy it is to enforce its mission as it grows to be something special and totally rankable as top dog in a particular field of specification not just in peoples hearts, but also in search engines, which people use to find their interests.
What matters to people, is what should matter to a site administrator looking for the best way to convey ideas back and forth communicating their purpose to interested users. As such, member level promotions would make this ideal, so people aren't just given an incentive to post, but are also showed how their contributions matter by being a contributor. That flexibility is what sites need to make their first members spread the word to others so they can fill in the blanks they leave for anyone as the floor is opened for sharing on a site requiring attention. IT isn't just about notifications, it is about staying updated so that people know where to go when the need arises. In order for that to become a social engine site, the platform has to be flexible enough to be built towards a purpose where members could fill that need as they share their story. once stories become the headline of a search result, that plus the fact that members can be personally recommended for a particular study of interest, leaves any social engine site at an advantage. To do that, member levels need a promotion system to let the big users with something to say, let their light shine. All web admins have to do, is monitor the active people to get the right mix of content with quality so their sites can thrive.

**Comment by smazurov** [comment]
We don't have plans to do this. At best we'll work with our 3rd party developers to ensure such functionality is possible (if not already).
