### ISSUE TITLE
Enabling posts

### ISSUE THREAD

**Issue by ernie003** [SocialEngine/phpv4-issues#39]
I'm not sure how much help you can be because I've only encountered this with add-ons I have purchased... Whenever I create something as a draft and then go to enable it after I am satisfied with the way it looks, it never shows up as "published." I have to go and create a whole new post.

**Comment by Anshuse** [comment]
Hello @ernie003 ,

Thanks for reaching out.

This is not a known issue and we're not able to reproduce this at our end. To be enable us to look into this issue on your site in detail, you may file a support ticket along with your site details.

Best Regards,
Anshu
