### ISSUE TITLE
Bug When Adding Chat To Other Pages

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#392]
The chat doesn't appear where it is placed when adding the chat box to a particular area. The only solution is to make a column dedicated to the chat.

**Comment by Anshuse** [comment]
Hi @Elshara , if you're placing "chat box" widget in the left or right column of the site then it will not be placed right in that column because "chat box" widget acquires complete window so, it will work fine when placed in the center column. 

If you're placing "chat box" window in the center column of your site and facing any issues then please let us know, along with the screenshot.

Thanks!

**Comment by Elshara** [comment]
Chat and tinymce don't mix at all.

**Comment by Khushboo016** [comment]
Hi @Elshara , It would be great if you can provide us a screenshot of the issue you are facing, so that we can understand your query better.

Thanks!

**Comment by Elshara** [comment]
This issue can be reproduced by doing the following.
Go to layout editor.
Go to the page site footer.
Place chat there.
Load something with tinymce in it. The add discussion page, add blog
post page, a private message, a forum topic, something that you'd
normally use a text editor to accomplish.
Scroll to the bottom. Try to type a message in chat.
Another way the chat has issues working is if an active editor
displays text. The activity feed is an excellent example of this. It's
editor has a problem displaying status updates if it's module is
placed in the footer or on any other page apart from a group, event or
personal profile and the home pages.

**Comment by Khushboo016** [comment]
Hi @Elshara , as we have also mentioned in your issue https://github.com/SocialEngine/phpv4-issues/issues/388 that some widgets are designed specifically to be used in only some specific areas of the page keeping in mind the space that the widget requires to be displayed properly, so Chat will also not work right in the footer. But we have added your point at our end for internal team discussion that the issue appears only when we have two tinymce editors opened in the same page.

Thanks!
