### ISSUE TITLE
Bug When Displaying Users Online

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#393]
This feature practically doesn't work at all. There's no invisible mode, however it acts like there is when ever members are called.
Because the private chat IM feature relies on this to locate online friends, it is very distracting to enable it only to find people who were online months ago have open chat boxes with new messages that have already been read. Nobody uses the social engine chat, it is a complete disaster when people do. Not only can people not talk to who they want, but they are unable to effectively use even the basic private message system feature of the chat because the fact that members online is so unstable. Plus, sometimes the private chat will not open at all even when members are online. It all depends on how much of a database and server load the site is facing at unexpected moments when too many things are being called at once. It's not the servers fault, it's just social engine taking up random resources it doesn't need at low peak times and still gives the online user count a major cold reading.

**Comment by Khushboo016** [comment]
Hi @Elshara , 
Regarding "There's no invisible mode, however":
There is not any invisible mode but "Offline mode" is present in Chat module, on switching to which, user's friends will not be able to see him online. The functionality to show users online depends on the task "Chat Data Maintenance", so, if you are facing any issues in showing online users, then please make sure that this task is running frequently from "Task Scheduler Settings" section. And if it is not running frequently, then you can get the trigger method changed to cron and for that you would need to ask your hosting company to set-up crontab on your server. We've also got a KB article for this: http://support.socialengine.com/php/customer/portal/articles/2170953?b_id=4311

Thanks
