### ISSUE TITLE
Allow People To Choose An Existing Album When Posting Media

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#394]
Every time someone uploads something, a photo, a song, it gets posted in a new album. This is very cluttered and doesn't work well. People should have a separate album creation process for newly uploaded content, rather than making it automatically be something people post to. This is why the most popular media attractions on social engine sites are videos, they are stand alone and don't need or have the ability to be put in albums. Photos and songs should get the same treatment, this way people can actually search through posts and organize them the way they want, rather than having to search through albums with a similar name, to go through one file names just to be able to decide what to do with them.

**Comment by Anshuse** [comment]
Hi @Elshara , we're not sure if providing an option, to choose an Existing Album while posting media files, would be feasible or not but we have noted down your suggestion in our internal suggestion tracker for the internal team discussion. 

For now, we're closing this thread and if we plan to work on this feature in near future, we will open it again.

Thanks!

**Comment by Elshara** [comment]
Cool. The reason why I suggest this is because people can have the
option to add things to existing albums when making a new batch of
uploads. I know I'd be able to organize things a lot easier by doing
this.
