### ISSUE TITLE
Transfer button on Storage Services says working but doesn't

### ISSUE THREAD

**Issue by sagekalmus** [SocialEngine/phpv4-issues#396]
What are the steps to reproduce this issue?
-------------------------------------------
1. …Log in to my admin using ######## and #####
2. …Go to Manage Storage Services & click Transfer on Local Storage to transfer FROM Amazon S3 back TO Local Storage
3. …It will appear to have worked, but observe whether or not any of the transfer actually occurs

What happens?
-------------
…Says transfer in progress but times out or cancels before any files transferred. 

What were you expecting to happen?
----------------------------------
…All the files to transfer FROM Amazon S3 back TO Local Storage

Any other comments?
-------------------
…problem started after upgrading to .10. Problem started gradually with fewer and fewer files transferring before timeout or cancel/failure until no files at all would transfer back to local storage from S3 anymore. 

What versions of software are you using?
----------------------------------------
**Operating System:** … my computer? Mac OS X Yosemite

**SocialEngine PHP Version:** …newest .10

**Comment by Khushboo016** [comment]
Hi @sagekalmus , Apologies for delay in responding back to you!

Thanks for reaching out!

This is not a known issue and issue seems to be in your specific installation. Please make sure that: 

1. Values of two variables : "memory_limit" and "max_execution_time" are set large enough for your site.

2. You're using correct Access key and Secret key. You can check these keys from the Amazon console.

3. Bucket name and public folder must be correct on your AWS account.

If after following the above points, the same issue persists, then you can try using AWS Command line to do the same work.

Please let us know if you still face the issue either by sending a mail to support@socialengine.com, or you can open a support ticket for the same at https://www.socialengine.com/client/ticket/create from your SocialEngine account.

Thanks!

**Comment by sagekalmus** [comment]
Those items had never changed between the time that the feature was working
perfectly and the time it gradually, intermittently started failing until
it stopped working entirely.

That's what I'm trying to tell you. Everything was working fine, then it
intermittently started failing and then it failed completely with no change
to whatsoever to any of those settings or keys, so neither the problem nor
the solution can be sourced to those items.

If the feature had never been working properly to begin with, or if we had
indeed changed any of those elements, then your troubleshooting steps would
be relevant and potentially productive. In this case, they're moot because
nothing had changed between the time that the service working and the time
that it was not.

**Comment by Khushboo016** [comment]
Hello @sagekalmus , this is not a known issue of SocialEngine PHP, and it seems to be associated with your specific installation, so, if you are still facing the same issue, then I would recommend opening a support ticket over at https://www.socialengine.com/client/ticket/create or you can also email us at support@socialengine.com regarding the same issue along with your site's FTP details.

Thanks!
