### ISSUE TITLE
'Open redirect' vulnerability

### ISSUE THREAD

**Issue by rwetzlmayr** [SocialEngine/phpv4-issues#398]
What happens?
-------------
Bad actors are able to craft URLs to SE-powered sites behaving as open redirectors. This is considered a security weakness according to [CWE-601](http://cwe.mitre.org/data/definitions/601.html).

Any other comments?
-------------------
Please provide a security contact to discuss this issue's details in private.

What versions of software are you using?
----------------------------------------
**SocialEngine PHP Version:** 4.8.10

**Comment by Anshuse** [comment]
Hello @rwetzlmayr , you can send us an email on support@socialengine.com for the same issue and we will discuss it over there. 

Thanks!

**Comment by rwetzlmayr** [comment]
Sent the vulnerability details to support@socialengine.com. Applying [RFPolicy v2.0](https://dl.packetstormsecurity.net/papers/general/rfpolicy-2.0.txt) in lack of a vendor-specified disclosure policy.
