### ISSUE TITLE
Menu show two times

### ISSUE THREAD

**Issue by vjgarg2** [SocialEngine/phpv4-issues#399]
Hello Team,

How are you ?

I have opened a URL for view message: https://demo.socialengine.com/messages/view/id/2
two menu is showing.

How to reproduce this issue:

1) You can go to URL: https://demo.socialengine.com/messages/inbox
2) Click on any message
3) Now, you can change message id from url

![menu 2 times](https://cloud.githubusercontent.com/assets/6785287/13497489/72c8047c-e17b-11e5-8a71-85f343b14233.png)

**Comment by smazurov** [comment]
might've been a temporary issue, I only see one menu. If you still see 2 on the demo, let me know.
