### ISSUE TITLE
Album upload links hidden on iOS (Redmine Bug #2610)

### ISSUE THREAD

**Issue by shivani2910** [SocialEngine/phpv4-issues#4]
## Bug:

iOS has supported photo uploads for several versions now. Albums injects a javascript to hide the photo upload buttons in full site.
## Solution:

In file `application/modules/Core/layouts/scripts/default.tpl` at line no. 184 (approx), below script should be removed / commented :

```
<script type="javascript/text">
if(DetectIpad()){
$$('a.album_main_upload').setStyle('display', 'none');
$$('a.album_quick_upload').setStyle('display', 'none');
$$('a.icon_photos_new').setStyle('display', 'none');
}
</script>
```

**Comment by DonnaScriptTechs** [comment]
@shivani2910 this appears to work for me in 4.9. Can you please test and verify.

**Comment by Elshara** [comment]
I can actually verify it doesn't.
Use mobile view.
Try going to photo upload page.
Or for that matter, try going to any post page when mobile plugin is enabled.
Add blog.
Add forum discussion.
Add video.
Add songs.
Add photos.
Add poll.
Add classified.
Add group.
Add event.
Comment on any of the above.
Not even status field appears.
Anywhere tinymce loads won't do so in mobile plugin.
Not even chat.
Or invite friends.
You can't load admin panel or notifications either.
Even if your member level is set to super admin.
The plugin is the problem.
Notice it won't let you. The option doesn't exist, even though it does
in the menu.

**Comment by DonnaScriptTechs** [comment]
@Elshara thanks for your post but I am asking for 4.9 :) It works for me in that version. I'm going to close this as fixed but @shivani2910 can reopen it if she finds it doesn't work for her.

**Comment by Elshara** [comment]
Okay.

**Comment by Elshara** [comment]
They have not been active for awhile.
