### ISSUE TITLE
Error When Classifying Friendship Statistics

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#400]
Social engine has problems displaying friendship statistics.
The number of friendships counted is greater than the total number of members on site. This goes for both one way and two way friendships verified and unverified.
You can test this on a site that has just two members. Adding a third member and adding one or both other members as friends with the third member would display a friendship count greater than the total amount of members. You can only have three separate friendships if you only have three members for the count of people who have a friends list to be displayed.
I'm not sure how Social Engine records statistics and if friends include the total number of posts counted towards people becoming friends. If so, the activity feed sometimes records a friendship between two people on both profile pages, and sometimes duplicates the feed if on the main activity feed. This would mean four possible ways of recording a friendship that is just one friendship. Regardless of one way or two way friendships, the amount of people who have a friends list shouldn't be greater than the total amount of members on site to have a list containing the same people. Otherwise the statistics are people times the amount of people on each friends list which totally defeats the purpose of a friendship statistic.

**Comment by Anshuse** [comment]
Hi @Elshara , this is not a known issue and we're not able to reproduce this issue at our end so, it seems that this issue exists specifically in your installation. Thus, we suggest you to please open a support ticket and our team will look into it on your site.

Thanks!
