### ISSUE TITLE
Editing Source Code Is Dangerous

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#401]
I'm not talking about the code of social engine, I'm talking about when doing something more practical like writing a blog, editing a discussion that sort of thing.
I prefer to write in pure html. I hate using text editors to do things I know how to code. My problem is, I'm using a laptop with a big touch screen on it. If I accidentally hit my finger as a light tap, I lose all the changes I am making in source code. There's no warning, it's just all gone.
I spend a lot of time rewriting blogs from scratch as I'm a blogger, and I'm talking about long content pieces. Because posts don't auto save and because the source code html editor is so crude, that if I don't hit the okay button, or if I don't repeatedly save hundreds of drafts, I lose everything and have to do it all over again just because my finger hit the touch screen as a tap or I accidentally moved the cursor away from the edit area.
I'm tired of working with a source code editor that I have to use as a pop up frame. I think editing source code this way is very dangerous if you don't know what you are doing and make every movement flawless. Typos I can handle. But losing everything because of a tap, is one reason why I'm not working with wordpress. If phpfox can design their editor like many others these days where I don't have to worry about losing posts while I type them out, social engine should be far above that nonsense but it isn't and I am getting to the point where it is becoming a major concern for me. I am not going to be using word pad note pad to do the same thing I can on the site itself. I'd close the browser if I didn't want to be there. This only happens with the tinymce editor. Where ever the editor appears, I almost cringe inside hoping I don't have to redo a long content piece. Comments need a better editor as well while I'm on the subject.

**Comment by Elshara** [comment]
I'm motivated to remind you of the price tag of social engine. $700.00 for the base software alone, and not a working text editor? I paid $99.00 for phpfox and I got a working text editor. One that loads where ever it is needed.

**Comment by Elshara** [comment]
All I want is the ability to warn users about the dangerous possibility of losing source code changes if navigating away from the edit area without saving changes. Or at least don't put the source code area in a pop up that you have to hit okay to actually make the post itself. It should already be there. It isn't as if you're saving the post live if editing it, why should I have to press save twice? The way the layout editor is set up, that would be totally fine. At least the whole thing is iframe based. Come on guys I'm surprised nobody has mentioned this before. Do you really expect people to use a crude form of unsupported tinymce editor? Do you know you are in my opinion playing with fire this way? This is costing my business. Not one of you, developers, could come up with a better source code to overwrite the core one? Stop making marketplace ads for two minutes and use member subscriptions already. We need core improvements for social engine product. A full on working html editor is about as nice as a gift of birthday cake on my birthday from a very dear friend at this point.

**Comment by Elshara** [comment]
You guys are lucky I'm not charging money for my advice. You charge for things that you can already do, with social engine core mostly and I'm talking directly to many add on developers at this point, younet, social engine add ons etc you guys listening? Not one of you could make a close to an affordable text editor I'd buy in an instant if you only knew how needed it truly was rather than advanced comments, advanced feed etc. The second you guys stop copying each other in marketplace items not that they are bad products, hire experts, ceofox, social engine pro company, social engine solutions etc, the better your products become as they are original, not trying to make a similar amount of money off of something that is already there. I don't care if it is a one time or monthly cost, I'm interested in what you can do to improve the product, not make flashy alternatives to something that mostly works. It's spam when I have to read through repeat posts in the marketplace about products I don't need to search for something that I manually scroll through at least 50 pages of plugins alone to never find or miss while trying lol. That's after getting no results in the search area. I'm serious this is a potential deal breaker for me. HTML editors aren't out of use by a long shot especially when it comes to coding. Just because wyciwyg may be in existence doesn't mean it has to replace what actually is more functional overall. The alternative to no html is no browser support for formatting and I'm tired of putting up with that being such a heavy constant in social engine plugins. We need a standard consistent text editor it's that simple. As a matter of fact, radcodes may do the best job at providing one since they're the most original plugin provider out there with products dating back to social engine 3 that still work today.

**Comment by Elshara** [comment]
Sorry for the rant but it has to be said. I don't want to see this product go to waste because the core needs an update it doesn't have yet. That's the bottom line. If your alternative, Ning, has an official social engine import script vailable, and their text editor which hasn't been updated in half a decade if not more, can convince people to stick with a product that doesn't get any updates what so ever. Don't you think it's time for a change?

**Comment by Elshara** [comment]
I realize this is a github page for making solutions, not problems. Here's my solution.
If no developer can come up with a better text editor by social engine version 5, I'll do my best to create my own for free and give it out to anyone who wants it. I'm not a developer as in hard core programmer yet, but I'm motivated to help this product succeed as much as my own website if not more so, since so many people love it.
That does not mean social engine can't make one, it isn't as if that's a part of the product that's out there yet, but it is a possibility if nobody ever does. I want to be able to be useful, what would be more so than making a functional text editor for people to use on a daily required basis.
Hats off to radcodes for making a functional social engine rss feed, hire experts for a pretty rock solid newsletter plugin, younet for advanced notification, layout editor and profile styler and mysql dump, social engine add ons for the phpfox importer, social engine for an excellent platform and to everyone who uses it for great sites. Lets make it better together. You are a huge inspiration in my life.

**Comment by pacodrums** [comment]
Great @Elshara  is true, all developers only copy plugins, i vote for more creative developers.

**Comment by Elshara** [comment]
Thank you for your vote of confidence and agreement! Much appreciated.
This is close to my heart.
I just realized something.
Source code edits are hidden in dialogs so moving away from one
doesn't exactly cancel it out, but clicking on source code again opens
up a new source code html box so it looks as if your changes never
took effect. You have to close that box to reopen the other but it is
hidden so you really have to put your cursor over every inch of the
page to actually find it then click on it twice to reopen it and get
back to the changes which never took effect if you accidentally moved
away from it.
This actually makes me more madder than just losing the changes!
Because you think you actually lost them, discovering you haven't
isn't the worst part. Realizing you found them and then hit okay,
deletes anything you have written to replace it instead of adding to
it. So now you have to click undo and then redo to get access to the
text which should've always been there in the first place. Then when
you try to save your changes, posting a blog gives you an error no
token to match against, so you are taken back to the add or edit
screen. Now you have to save changes again, but this time, you don't
have the option of undoing and redoing previously open dialogue boxes,
you are now stuck with what is right in front of you. Saving changes
at this step brings up an error where you try to allocate more bytes
than available some php memory error, so now you have to hit control
plus r, click on yes I wish to reload page by sending insecure data
and wait for the same screen to pop up. When it does, saving changes
once more takes you to my blogs page. Click on your blog finally gets
you to where it is published or written as a draft.
What an easy way to write a blog! Write? Forum topics and private
messages are even worse. You want to know why? Because they don't have
a draft feature. Private messages you can't edit and forum topics
shows how many times you edit it. Doesn't look good for a live
presentation.
And lets not forget comments, writing descriptions for media which by
the way has a terrible presentation as well, the status updates in the
activity feed and profile fields. What do these places all have in
common? The inability to render any formatting changes what so ever.
You have to write in plain text or code shows up as code and not the
html you want. What a wonderful text editor we are stuck with. And to
top it all off, you can't edit those either, apart from profile fields
to which you have to go to your own profile to do that.
This is what social engine can do in 2016. Did I mention editing css
is a breeze? You can't even preview your changes but you can make sure
the site is live if it breaks due to a coding error in about 12000
lines of it. And that's just the front end themes. What about the
cintax error in a file that is about 12 levels up from web root
directory? Error messages would normally help but every time you have
to manually go into the application/settings/general.php file and
manually change production to development mode to figure out where the
error is originating, you then have to browse to it, find around the
line it is referencing if it isn't a random line error that is broken
and or just do a  complete reinstall of social engine to delete the
changes you could've made a lot easier with the right template
equipment. That means text editors, proper coding tools and html
verification with warnings so that you don't make a mistake that could
be more serious than failing to get to the package manager to
reinstall something you broke and even that is not a guarantee. There
is always the database to clean up if that happens. Worst case
scenario, your server can't handle the load of a database repair
maintenance operation which by the way social engine does not support
so you are left manually cleaning up the mess that database tables
referencing incorrect cached versions of things no longer in place
still have partially working causing site down time and a huge head
ache for the main web administrator.
But you know what? We put up with all that as a part of managing a
social engine site because people realize it is easy to use it if
everything works the way it should.
See what a difference a text editor makes?

**Comment by Elshara** [comment]
Developers who have the creative spark in them to fix such problems,
would be able to in no time at all. But instead of working around
these problems, they create new ones for us to figure out. This is
just client side maintenance at this point. Because recreating widgets
and fancy modules that require a simple column width to be put in
place which half work as versions change like the seasons, is more
important apart from copying all the other expensive developer
products and then making us pay license requirements which are more
restricting then the software itself is which is of course illegal,
but never the less it happens and because it is a third party product,
nobody steps in to say what the product is made for apart from the
sales pitch which dictates in no uncertain terms, social engine php
version 4.x compatibility, can't give a best practice to save their
life because all they care about is the money they get from paying
clients which by the way is less than half since everyone gets it all
null anyways. No offense, but there you have it. And you know what,
they deserve it because I wouldn't pay $100.00 per plugin just to give
money to someone who didn't really make anything new at all. i have to
point out here that social engine knows their software best and they
should know their clients best, but instead, they're slower at
updating than wordpress or Ning the core of their own product using
code that customers never got asked if they liked, but were encouraged
to place bug reports on it as the paying people never got a say until
recently about what changes the product we use every day, may just
entail. Wow. And to think social engine plugins could fix it by doing
the same thing and getting away with it because of a fix that never
was meant to be in the first place? Here I'm quoting advanced albumbs,
advanced activity feed, check out my version of a copied code social
engine makes and I can sell it to you but you need to prove to me you
are loyal so just for good measure require my core to be installed for
a verification that is more secure than social engine licenses which
by the way are about as unified as a gingerbread house.
Pun intended. Feelings aside. I don't care who owns what at this
point. I care that it works. And you wonder why people use ruby on
rails? Here's a hint, Facebook, Twitter, Google etc.

**Comment by Elshara** [comment]
I think at the end of the day we all have the right to how we would
like our community set up. But there needs to be some basics we can
all agree upon that would help us. That should be somewhat of a
priority with social engine developers without us having to always
report them but it's nice and I appreciate the fact that we can and
are able to. You are awesome.

**Comment by Anshuse** [comment]
Hi @Elshara , we appreciate the efforts that you put to make SocialEngine PHP better but it would be great if you can write down your points precisely and concisely. This will help us to understand your point more clearly and thus, discuss your suggestions with our development team. We hope that way our communication will be more effective. So, please write down your query in points precisely describing what is the issue and what should we do to resolve it.

Thanks!

**Comment by Elshara** [comment]
The tinymce editor as it stands currently isn't deployed across all
social engine text editor areas. It should be.
A problem occurs when editing source code of any text specified. The
code is lost if the cursor is moved away from the edit field.
Instead of having code pop up in a window, have it pop up in an iframe
so it remains open if the cursor is moved away from it.

**Comment by smazurov** [comment]
we have plans to address tinymce issues, you can track this issue: #278
