### ISSUE TITLE
Untranslated Classifieds phrases

### ISSUE THREAD

**Issue by Tomislav20** [SocialEngine/phpv4-issues#402]
Hi,

I found these 2 phrases that are missing from classifieds.csv file. Could you insert them with rest from #5 in next upgrade?

![settings classifieds](https://cloud.githubusercontent.com/assets/12753666/13586164/b13b3dc2-e4bf-11e5-97b3-bb3ebd199a54.jpg)
![classifieds maximum](https://cloud.githubusercontent.com/assets/12753666/13586112/71cda1b6-e4bf-11e5-9758-c39c0e71aca3.jpg)

Regards

**Comment by Khushboo016** [comment]
Hello @Tomislav20 , Apologies for delayed response.

- The phrase "ACTIVITY_ACTIONTYPE_COMMENT_CLASSIFIED_PHOTO" is not associated with our core Classifieds module, so it cannot be found in "classifieds.csv". This phrase may belong to any third party plugin installed on your website.

- For the translation of a phrase shown in your second screenshot, please note that this is not a single phrase, this is concatenation of two different phrases: First is "You have already created the maximum number of classified listings allowed." and second is "If you would like to create a new listing, please delete an old one first.". 


You will need to translate this complete one phrase by splitting it into parts, as we mentioned above, from "Admin" > "Layout" > "Language Manager" section of your website. If you still face any issue while translating this phrase at your end, then please drop us an email at support@gmail.com mentioning your site's FTP details or you can open a support ticket from https://www.socialengine.com/client/ticket/create section of our website.

Thanks!
