### ISSUE TITLE
Autogrowing textareas cause screen jumps when entered text exceeds a certain amount

### ISSUE THREAD

**Issue by rwetzlmayr** [SocialEngine/phpv4-issues#403]
What are the steps to reproduce this issue?
-------------------------------------------
* Add a longish text into an autogrowing textarea (e.g. a blog comment) making the textarea fill the browser window height to a great extent. I cannot give an exact measure, please see attached screenshots:

![screenshot - 09 03 2016 07_31_48](https://cloud.githubusercontent.com/assets/357054/13627244/5af54f56-e5c9-11e5-9b0e-d71e6d843564.png)

* Move the caret to the end of the comment, try to click there and add another character. The textarea will autogrow upon key-up and cause the whole browser window to scroll up, thus hiding the textarea caret below the visible client area:

![screenshot - 09 03 2016 07_31_58](https://cloud.githubusercontent.com/assets/357054/13627271/93bf1d12-e5c9-11e5-975c-66a187880466.png)

What happens?
-------------
Text entry caret moves out of the browser window's visible range.

What were you expecting to happen?
----------------------------------
No automated scrolling in the browser window.

What versions of software are you using?
----------------------------------------
**Operating System:** Win10, Firefox 44.0.2

**SocialEngine PHP Version:** 4.8.10

**Comment by Anshuse** [comment]
Hello @rwetzlmayr , thanks for brining this issue to our notice. We have noted down this issue in our internal bug tracker and our development will take required action on it. Thanks!

**Comment by SpiritWolfie** [comment]
I'm willing to vouch on this issue as well, this happens also when you extend commenting length on the **activity wall**, the scroll bar will start jumping if you type past certain point.

**Comment by smazurov** [comment]
This has been addressed in [4.8.11](http://blog.socialengine.com/2016/05/26/socialengine-php-4-8-11-is-released/)
