### ISSUE TITLE
Social Engine Rarely Sends Out Invites

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#404]
When inviting members, social engine doesn't send out the email. Members receive no email even if the mil settings are set to send email immediately. In this case, social engine says it sends the email, but nobody gets it. There is nothing wrong with the email server because regular notifications still get sent but no invitation mails are received.

**Comment by Anshuse** [comment]
Hi @Elshara , we're not able to reproduce this issue at our end so, it seems that this issue exists specifically in your installation. Thus, we suggest you to please open a support ticket and our team will look into it on your site.

Thanks!
