### ISSUE TITLE
new feature request for Forums - Member Level Setting - Allow reporting of topics?

### ISSUE THREAD

**Issue by xyzsimon** [SocialEngine/phpv4-issues#405]
Hi, 

This is a request for a new feature for Forums (SE PHP).  I would like Forums' Member Level Setting to allow the Admin to turn 'on / off' "Allow reporting of topics?"

At the present moment Forums' Member Level Setting does not have this.  I would love to be able to turn off the ability for members in the 'default' level from being able to report forum topics. 

I hope you'll consider implementing this new feature. 

thank you, 
Simon

**Comment by Anshuse** [comment]
Hi @xyzsimon , 

Thanks for reaching out!

We've noted down your suggestion at our end to discuss it with team to take required action on implementing this feature in our core module. Thanks!
