### ISSUE TITLE
Missing transliteration for Cyrillic and other non-western characters in slugs

### ISSUE THREAD

**Issue by rwetzlmayr** [SocialEngine/phpv4-issues#406]
## What are the steps to reproduce this issue?
1. Create a new blog post.
2. Use 'Здравствуйте Мир' as the post's title.
3. Save the post and find that the post's slug consists of only a single `-` dash and nothing else.
## What happens?

Cyrillic and other non-western characters are dropped while the post title is processed by `\Core_Model_Item_Abstract::getSlug`.
## What were you expecting to happen?

A proper transliteration of Cyrillic and other non-western characters in slugs. See https://github.com/textpattern/textpattern/blob/master/textpattern/lib/i18n-ascii.txt for prior art.
## What versions of software are you using?

**SocialEngine PHP Version:** 4.8.10

**Comment by smazurov** [comment]
We would use [`transliterator.transliterate`](http://php.net/manual/en/transliterator.transliterate.php) to address this issue. Only question is, is falling back to default OK in case `intl` isn't installed, or php is < `5.4`? We're considering bumping the minimum required version of php as well.

Thanks for the report, as always!

**Comment by rwetzlmayr** [comment]
One thing to keep in mind with either falling back to the default solution or implementing this feature with a PHP version dependency: Cool URIs Don't Change. 

In detail:

1. I believe that the slugs are generated on-the-fly while the content is rendered. 
1. External links might point to a URI which was generated with SE 4.8.x  or SE 4.9.x running on PHP 5.3.
1. Later on, the site owner might choose to upgrade to SE 4.9.x or PHP 5.4+. This would result in new slug being generated *on the site* while *external* links still point to the old URIs with "faulty" slugs.
1. SE happily renders blog posts and other content no matter what slug is requested (see exhibits [A](https://demo.socialengine.com/blogs/23/4/belgium-a-hidden-gem) vs [B](https://demo.socialengine.com/blogs/23/4/foobar-quxbaz-hello-world)).
1. This is a classical duplicate content problem.

I propose that SE checks the requested slug and responds with a `301 Moved Permanently` response pointing to the current correct content URL whenever the requested slug does not match the actual correct slug.

**Comment by smazurov** [comment]
Those are great points to bring up, I do not think we use any slugs for lookups, but in those cases we'd just do it moving forward, any content created with the updated system will have updated slugs. For things that do not care about the slug url (as you mentioned in 4)), we can do it retroactively as the content is still accessible at the old url.

We could do 301 redirect to any "mistyped" slug urls, but I am not sure its worth the extra http request.

**Comment by rwetzlmayr** [comment]
> We could do 301 redirect to any "mistyped" slug urls, but I am not sure its worth the extra http request.

As an alternative to a full-circle HTTP request I would suggest to add at least a `<link rel="canonical" href="..."` element with the correct slug to the `head`.

**Comment by smazurov** [comment]
I like that, will consider it for sure.

**Comment by Elshara** [comment]
I've noticed this also.

**Comment by DonnaScriptTechs** [comment]
This is implemented for 4.9.0 when it is released.

**Comment by Elshara** [comment]
Awesome!
