### ISSUE TITLE
Custom Embed Code For Videos

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#407]
Videos plugin can't embed code like this.
<script height="480px" width="640px" src="http://player.ooyala.com/iframe.js#ec=RlanZrdDpe3yCf9NcF_itkR5rQx7Hi6C&pbid=ZTIxYmJjZDM2NWYzZDViZGRiOWJjYzc5"></script>
I was going to share it as a blog, but can't do that either. Nor can I do it in a discussion.
Sucks because uploading the video isn't an option. Embed codes won't save.

**Comment by Anshuse** [comment]
Hi @Elshara , it seems that when you're trying to embed the video's embed code in the Blogs and Forums module then no video gets posted. If so, then please make sure that you have allowed "iframe" tag for Blogs and Forums modules from it's Member Level settings. Thanks!

**Comment by Elshara** [comment]
So is that the html tags option? I'm unable to paste an embed code for
videos section though, just a url, link for youtube. I would like to
be able to embed videos in the video module. Some embed codes use the
script tag, while others use object, and some use iframes.

**Comment by Khushboo016** [comment]
Hi @Elshara , We're sorry for the miscommunication happened above. We thought that you were referring to embed the videos in Blogs and Forums modules of your website, so we suggested you to add the "iframe" tag in the Member Level Settings of these modules.

But now it seems that you want to upload videos on your website from the Video section using video's embed code and if so, then we're sorry but its not possible. From the Video's section or from the Activity Feed, you can post a video via "Youtube" or "Vimeo" or using "My Computer" option.

**Comment by Elshara** [comment]
That is a basic feature of all websites, to place embed codes for
videos. Why isn't this supported? All you would need is a simple html
box to place the code into.

**Comment by Khushboo016** [comment]
Hi @Elshara , Embedding video codes is required when user is drafting some content and want to embed a video somewhere into that content. This is done when using a rich text editor and so this feature has been provided in all our modules where we use rich text editor like in Blogs and Forum modules. But in Videos module, when a video is posted individually and is not embedded with any text, then there is no use of text editor because of which videos can just be posted using different sources and not embedded.  Hope you understand my point. Thanks.

**Comment by Elshara** [comment]
True. But Usually those sources only include Youtube or Vimeo, and not
a way to embed codes from other video providers. Because if a video is
no longer available on Youtube or Vimeo, it will be elsewhere like on
news casting sites.

**Comment by smazurov** [comment]
this is covered in #141, thanks for your request!
