### ISSUE TITLE
Guest Users

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#408]
I think that we should be able to have guest users and signed out or anonymously signed in members count towards the number of members actually online. We should be able to recognize when ever a search engine visits the site as well to get an idea of who is online when in real time. Also it would be nice to be able to track where people are visiting by the pages they are currently viewing and how many times such a page has been viewed as a page statistic also in real time.

**Comment by rwetzlmayr** [comment]
-1 as this would probably multiply the actual count of online members tenfold. Every scraper, search engine crawler, vulnerability scanner, script kiddy and other flotsam would inflate the online member count.

**Comment by Elshara** [comment]
Not if it was coded to gather list of current online users every
controlled amount of seconds as a setting option. One could turn this
feature off if desired. IT wouldn't break anything, it would work
similar to those widgets you see in areas like feedgit makes. Comet
chat has this functionality already as does arrow chat. The idea is
just putting those list of names and basic details into a module.

**Comment by Anshuse** [comment]
Hi @Elshara , we have discussed this case with our team and using current architecture of SocialEngine,  it's not possible to track and display Online members but we have noted down your suggestion at our end and will look into the possibilities to work on it in future. Thanks!
