### ISSUE TITLE
Facebook login has stopped working

### ISSUE THREAD

**Issue by jdouk69** [SocialEngine/phpv4-issues#41]
I believe Facebook updated their API and now none of the socialengine site FB login work. Do you have a fix for this?

**Comment by shivani2910** [comment]
Hi @jdouk69,

Yes, you're right. There have been some recent modifications made by Facebook in their integration API. To resolve this issue on your website, please follow the solution provided here:

https://github.com/SocialEngine/phpv4-issues/issues/42

Regards,
Shivani
