### ISSUE TITLE
Create overview of size used per user

### ISSUE THREAD

**Issue by freakerparty** [SocialEngine/phpv4-issues#411]
Hi,

When you go to the admin panel and view all the users, there is one important thing missing. I have set a maximum overal quota for my users. But i can't see how much my users are using.

When you list the users in the admin panel a extra column viewing the quota and size used would be very useful.

An example provided here: 
User1 || Quota: 500 MB || 324 MB of 500 MB used
User2 || Quota:     1 GB || 643 MB of     1 GB used
User3 || Quota: 500 MB || 223 MB of 500 MB used
User4 || Quota: NoLimit || 334 MB of NoLimit used

This would be handy for a lot of things, for example:
****
1. You easily see if users need more space
2. You see an overal view of what users are proximity use
3. If there are problems reported by a user you see simply if it is a space problem

Hope you will add this in the future :)

**Comment by smazurov** [comment]
I can totally see the use for this functionality, but we would leave such things to be implemented by a 3rd party plugin
