### ISSUE TITLE
Auto Save Not Present

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#413]
Yet again, another text editor feature not present is auto save.
Imagine contributing hours of hard work to a discussion or blog and suddenly your computer decides to restart on you. Your browser stores the session, the title remains when you open up the browser to the post you worked so hard on, but the body of the post is gone for ever. All your hard work has been deleted and there's no way to get it back.
This happens to me frequently and most if not all common browser text editors I know of have an auto save feature at least as a draft if the post has been idel for a certain amount of time. Text in html boxes isn't a problem but in the tinymce box, it is because the minute you leave the page, even to reload it, your work is gone even though the text in the title and tags area remains intact.
Wyciwyg editors suck so bad that the entire text field has to be rewritten over top of an existing one. Nobody knows the significance of a truly html powered text editor anymore. This is one of them, it is why I write in html and quite frankly it is why I write longer content pieces specifically for the purpose of a renderable html text editor to pick up on. I cannot afford to have it be lost by the click of a mouse away from the text editor, especially if you have instances where comet chat may be installed or other browser pop ups that could happen at any time. It isn't fair for people who sit down to write something to lose it all because the text window focus happens to shift. I don't have to change comet chat settings so that when people type to me I have to look for currently open windows when I'm done writing? That's what this is doing, and it is because the text editor sucks so damn much.
I currently have to sign up for another website just to use their text editor to write something decent, save it then post its contents into the tinymce one and still line breaks appear in the html code, the only way for it to make paragraphs possible because the html code is so bad it can't render the difference between a line break and a filter of html code under source code. Here we are in 2016, Microsoft word has an online version people have to pay for, and this is the alternative? We pay for a broken text editor. A non functional, useless, piece of code we rely on to make our sites look good powered by social engine. I've seen better work in note pad and word press where it is very cumbersome to get to where you want to for you to write something. We have excellent menu support, excellent modular functionality and a very very poorly designed outdated useless text editor.
How far do I have to travel to use a functional html box, just a simple html box. Do I have to iframe my documents and upload it manually on the server just for it to look good? I can't upload any files because the functionality doesn't exist. I can't embed iframes because Google doesn't support them and because the iframe tag isn't allowed, nor is the tag to put scripts into the source code of a post. Am I in jail on my own website because I need a good html renderer? Makes me wish I should have stayed with phpfox or vbulletin or envision power board. But no, I wanted the ability for people to post files, which isn't possible as attachments in social engine so we're stuck with poorly designed photos, music and videos plugins requiring flash player or embed services to use them. This is not working for me!
As someone who enjoys the look and feel of setting up a social engine site, can this be at all considered?

**Comment by Khushboo016** [comment]
Hi @Elshara , We have added this suggestion of having the auto-save feature present in our Text Editor to our internal feature tracker. Hopefully this will be added in our near future releases.

Thanks!

**Comment by shivani2910** [comment]
This is implemented for 4.9 when it is released.

**Comment by gsf00001** [comment]
Is this optional?  Is this auto-save or auto-backup?  Some prefer to never auto-save because there's no way to backout.  Auto-backup however is not a destructive function.

**Comment by Elshara** [comment]
Awesome!
I don't mind if it appears as an autosave draft. Those we can manage
and delete if we want to.
