### ISSUE TITLE
Include Language String For Varable Email Edits

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#414]
1. When first installing Social Engine, it would be nice to have the site name be verified under email settings so that one doesn't have to edit all email templates to replace words like social network administration and default email sender information.
2. It'd be great to include more variable settings for dynamically addressed information to be placed in emails by default. This way all available variables for content can be addressed so that if something needs to be removed, it can be without having to go through all email templates to specify things to put in. Basically redoing the entire email language section.

**Comment by smazurov** [comment]
1. This is taken care of by editing footer template, you don't have to edit them all, as all emails include a footer.
2. We include all variables we think are necessary. There is no need for language section as ability to edit templates already takes care of language aspect.
