### ISSUE TITLE
Autogenerated Meta Tags

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#415]
Content in some scripts has auto generated meta tags included with the body of content found in longer articles or on dynamically generated content pages. In addition to static page tags, it would be cool to have this functionality for social engine as it is very successful in working with programs like Phpfox and word press.
It would also be cool for seo to be able to include the site name after the title of the page being currently viewed.

**Comment by Khushboo016** [comment]
Hi @Elshara , Thanks for your suggestion, currently we do not have any plans regarding this feature but surely we'll discuss it with our team.
