### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by Lavie7** [SocialEngine/phpv4-issues#416]
Hi sir,

We face unusual login process on SEPHP 4.8.10. Each time a user login on our site, it is redirected to the Admin profile or to a previous profile Address of another user. It is like user A is redirected to profile of User B, once login.

Can you let us know what to do to fix this issue. Our site is hosted on AWS console. 

I wait your feedback and other details can be sent by email, if necessary.

Thanks & regards,
Lavie

(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. …
2. …
3. …

What happens?
-------------
…

What were you expecting to happen?
----------------------------------
…

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** …

**SocialEngine PHP Version:** …

**Comment by smazurov** [comment]
This issue does not seem to be fully filled out. This is not a support channel. If you need support assistance please open a ticket at https://www.socialengine.com/client/ticket/create
