### ISSUE TITLE
Upload failed: Server returned HTTP-Status  #403

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#418]
When uploading files I assume via flash uploader, this error appears upon completion of upload. permissions check is fine and have reinstalled uploads of original package plugins.

**Comment by smazurov** [comment]
We have personally tested and ensured uploads work. We can't assist you here with server related issues. If you feel the issue is with software, please follow the [issue template](https://github.com/SocialEngine/phpv4-issues/blob/master/ISSUE_TEMPLATE.md) to report your problem.

**Comment by Elshara** [comment]
Seems to be a local issue don't worry about it.
