### ISSUE TITLE
Replace List Boxes With Check Boxes Combo Boxes Or Radio Buttons

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#420]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … List boxes provide an unstable interface for managing Social Engine settings.
2. … They appear in the page info screen, edit forum categories, category selection, select privacy settings, select member levels under broadcast newsletter email to members and other fields. It is the same type of list box.
3. … Simply navigating the options and having to press control just to select more than one item, breaks when ever you cannot select something in the order of how it is displayed on screen.

What happens?
-------------
… Every time a list box appears, settings don't save properly even though they appear to be selected. Forum permissions and page permissions are an excellent way of proving this.

What were you expecting to happen?
----------------------------------
… The list box be replaced by either a combo box or drop down menu, a radio button or a series of check boxes for multiple selection respectively. Much more reliable text fields.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Just get rid of list boxes. They can only be used on pc, making it next to impossible to manage from mobile. Assume all devices that access the site require mobile html5 controls to operate smoothly.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10

**SocialEngine PHP Version:** … 4.8.10

**Comment by Khushboo016** [comment]
Hi @Elshara , You can easily select the right choices in the list boxes by holding "Ctrl" key, and also there are no issues while selecting the required options in the Mobile site as the interface provided in mobile view is also fine as shown below:
![mobi](https://cloud.githubusercontent.com/assets/18209340/16336727/1df48f6e-3a2d-11e6-9d8d-c4531141b8cc.png)

Thanks!
