### ISSUE TITLE
Built in mail function

### ISSUE THREAD

**Issue by SpiritWolfie** [SocialEngine/phpv4-issues#421]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. …Use built in mail function
2. …mass email
3. …

What happens?
-------------
… allot of people state they don't get the emails when the website is using the built in email function, nor does it show up in Spam

What were you expecting to happen?
----------------------------------
… For users to get welcome emails and such

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
…
When someone signs up and they are approved by staff, they don't get the approval email, it doesn't show up in spam or anything, this also seems to be the case if you use the mass email function, I've had this problem for a while but figured it may be something on my end but after much checking on our server I can't find any thing wrong with our end which leads me to believe the built in mail function has problems.
What versions of software are you using?
----------------------------------------
**Operating System:** … Linux, I'd have to check which one.

**SocialEngine PHP Version:** …Latest

**Comment by smazurov** [comment]
Use SMTP, there are companies dedicated to ensuring mailbox delivery. Sendmail has issues that are outside of our control. This is not a bug we can assist with.

**Comment by DonnaScriptTechs** [comment]
I use Sendgrid for my sites as servermail is not recommended these says. Just a few mistaken reports by your members of spam and your entire server IP could be blacklisted. Sendgrid has a free option which has worked fine for me for years. :)

**Comment by SpiritWolfie** [comment]
@DonnaScriptTechs 

Thanks for the suggestion (That is really awesome that you made it a point to point one out that costs no money!)

How ever Me and my coder fixed this, it wasn't because we where blacklisted it just wasn't working correctly to begin with, we patched it ourselves.
