### ISSUE TITLE
Remove Restriction For Sending Messages

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#423]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Go to messages.
2. … Click on compose message.
3. … Try entering more than 10 members to receive a new message.

What happens?
-------------
… Maximum message recipients is only 10. This should be removed. Admins should be able to send messages to who ever they want to and include more than 10 people, all site members could be sent messages if admin wants. This should not be an issue.

What were you expecting to happen?
----------------------------------
… People could send more than 10 messages at a time.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… The edit field for typing a persons name should be replaced with check boxes if not for friends, than for all members if admin configures this option as a new setting.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10

**SocialEngine PHP Version:** … 4.8.10

**Comment by Khushboo016** [comment]
Hi @Elshara , if site admin wants to send a common message to all the site members, there is an "Email All Members" feature in the Admin panel using which an email can be sent to all the members of site.
But if you want that from front end also, users should be allowed to send messages to more than 10 people at a time, you can do a little code level customization to modify that as we've not put any hard limit on the number of users. We just put a soft limit for maximum 10 users. If you want to change this, you can do it at your end.

Thanks!

**Comment by Elshara** [comment]
I've taken two screen shots. The create page in the members area and
the questions page in the admin area.

**Comment by Elshara** [comment]
Oops wrong issue.

**Comment by Elshara** [comment]
Thanks for the info. Where would that be implemented? Is it possible
to include a setting for this in control panel in future?

**Comment by Khushboo016** [comment]
Hi @Elshara , 

Regarding "Where would that be implemented?":
You need to do below code change to edit the the limit set on maximum number of recipients that can be messaged simultaneously:

In the file /application/modules/Messages/controllers/MessagesController.php

Search for the code:
` $this->view->maxRecipients = $maxRecipients = 10;`

And replace the value '10' with the required value.

Regarding " Is it possible to include a setting for this in control panel in future?":
We have added this feature in our internal feature tracker and will discuss it with our team regarding its implementation in future releases.

Thanks!

**Comment by Elshara** [comment]
This is an excellent idea! Thank you!
