### ISSUE TITLE
Create New Email Templates For All Social Engine Modules

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#424]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Go to control panel.
2. … Go to settings.
3. … Click on mail templates.

What happens?
-------------
… You are presented with a list of options to choose from. Unfortunately, only a portion of video content, along with all forum, group and event content is supported under email templates with the exception of blog subscriptions. The rest, blogs, photos, music, videos, polls, classifieds, status updates, chat and mobile modules do not have their own email templates to customize. It falls under posts and general comments.

What were you expecting to happen?
----------------------------------
… All modules have their own separate email templates.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… This would be nice to have so that all modules are integrated well with the interaction of emails of the Social Engine system. This includes being able to set a custom logo in the header and a custom signature in the footer. Some templates place holders must be updated per setting so as to not mix and match the example or default text with place holders that are not there, while misleading people into thinking they can use all available place holders listed when they only show up as error messages in live emails.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10

**SocialEngine PHP Version:** … 4.8.10

**Comment by Khushboo016** [comment]
Hi @Elshara , Currently there is only one Mail Template for Blogs Module i.e. Blog Subscription, because in present there is not any other email that is sent out for Blogs. If in future, we make some other emails which will be sent to users related to Blogs module, then we'll also provide the Mail Templates for customizing those mails.

And same is the case with mail templates related to other modules, that is templates are provided for only those emails that are actually sent currently in SocialEngine.

Thanks!

**Comment by Elshara** [comment]
What about for likes and comments on post activity? Object_description
only gives part of the post description not the comment in the email.

**Comment by Khushboo016** [comment]
Hi @Elshara ,

Regarding "What about for likes and comments on post activity? Object_description":
Please attach screenshots of the Mail templates you are referring to here, so that we can exactly understand your query here. Thanks!

**Comment by Elshara** [comment]
Add the object_description field to the email templates referencing
likes and comments about posts you started and posts you commented on
or liked.
Instead of showing the comment as the post description, it is showing
the actual post itself or part of it.

**Comment by Khushboo016** [comment]
Hi @Elshara , 

Regarding "Instead of showing the comment as the post description, it is showing":
The [object_description] shows the post description because in this case the object is the post on which the comment has been done, so, we suggest you that if you want to have the comment made to be shown in the email sent in case a member comment on post, then you can do customization for this at your end.

Thanks!

**Comment by Elshara** [comment]
That was very helpful.
Every other post provider in the world provides a way to view comments
inline in emails. Why not you? By default? I'm finding more and more
that the plugins and their native functionality, are not actually
improving much if at all.
The next time someone asks me what social platform they should go
with. I'm going to tell them social engine, but never buy their
plugins. Just get a core license and go to an alternative plugin
developer who knows what they're doing because this functionality
problem is just not your specialty. I think you should cancel
development on plugins if you can't provide simple tweaks like this in
email templates by default. The sad thing is, we don't know what gets
sent out until it's already done. Emails is the biggest and most
important way of communicating with people because it's something they
know to check all the time for updates. Not just a social engine
website, or any other, even Facebook for that matter.
To have to require members to login every time to view a comment which
may or may not be there, is part of the reason why they don't comment
much. Knowing someone else will have to do a whole lot of clicking
just to see part of the comment, not even the full comment because
they have to click the more icon to see an extra 250 characters of
text. Not even the full comment gets posted on the website, even
though it saved successfully.
Things like a simple rich text editor for comments, would be nice.

**Comment by Elshara** [comment]
Having said that, where do I go to edit the custom file? I'd like to
do customization at my end.

**Comment by Khushboo016** [comment]
Hi @Elshara , As the required code customization is not a small change/modification and it requires many code level modifications in different files, so, unfortunately we are not able to provide you the code changes required. So, you  can refer to our third party developers for the same in this case.

Thanks!
