### ISSUE TITLE
Add Popular Pages To Statistics Section Of Admin Control Panel

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#425]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Go to control panel.
2. … Click on statistics.
3. … Click on referring URLs.

What happens?
-------------
… You see a list of URLs linking to the website in some way, but you don't see what part of the site they link to. The options cannot be sorted by popularity.

What were you expecting to happen?
----------------------------------
… The website display a list of most popular pages and who frequently visits the site most.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Lets get rid of Alexa, Google Analytics and Crazy Egg one site at a time.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10

**SocialEngine PHP Version:** … 4.8.10

**Comment by smazurov** [comment]
we have no plans for this. Use a dedicated analytics package (there is plenty of alternatives to GA).

**Comment by Elshara** [comment]
It was worth a shot.
