### ISSUE TITLE
Web Cam lightbox is formatted for portrait orientation.

### ISSUE THREAD

**Issue by zachsjc** [SocialEngine/phpv4-issues#426]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. Using Luminous Theme
2. Under profile, select take picture using web cam.

What happens?
-------------
Light box formatted for portrait orientation, cutting off right half of the preview screen.

What were you expecting to happen?
----------------------------------
Have a full preview with the window.

Any logs, error output, etc?
----------------------------
No
What versions of software are you using?
----------------------------------------
Mac OS 10.11.1  …

SocialEngine PHP Version: PHP Version 4.8.9 …

**Comment by Khushboo016** [comment]
Hi @zachsjc , Luminous Theme is one of the third party theme of SocialEngine, so we suggest you to contact the developers of this third party theme to assist you in resolving this issue. 

Thanks!
