### ISSUE TITLE
Adding Code To Tinymce Does Not Work

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#427]
`(Thanks` for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Go to any module with custom html tag support.
2. … Add script and form tags.
3. … The simplest of forms like a pay pal button will not copy over!

What happens?
-------------
… The code does not save. It appears fine when you click on add source code, and when you hit okay to save changes. The button appears beautifully. But when you try to add code, and then hit submit, part of the code does not even save. The entire thing is a mess. Even though under preview in the editor, the code displays perfect.

What were you expecting to happen?
----------------------------------
… The code to save when ever the submit button is pressed just like it shows up to do when saving the html source portion and it appears like it is supposed to in the wysiwyg rich text portion.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… I need to add a pay pal button to a blog post, forum topic or classified listing it uses the same editor as the private message system. Even though the html tags are set under module settings per member level, it does nothing!

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10

`**SocialEngine` PHP Version:** … 4.8.10

**Comment by Khushboo016** [comment]
Hi @Elshara , As we've also mentioned in your issue https://github.com/SocialEngine/phpv4-issues/issues/428 that we have added this in our internal feature tracker to have the ability of adding html fields to Tinymyc editor. So, am closing this issue.

Thanks!
