### ISSUE TITLE
Explanation Required: Regarding Fixes In Social Engine V4.8.11

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#429]
This is not a regular bug report so I've removed the template system for this issue.
In Social Engine 4.8.11 specified here http://blog.socialengine.com/2016/05/26/socialengine-php-4-8-11-is-released/?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+socialengine%2Fblog+%28SocialEngine%29 the following changes occurred:
1. Regarding the removal of show this page in search results check box:
A. For Non custom pages, why would it make any difference with it there?
B. For non custom pages, this makes it harder to control what people can search for if the global variable isn't there to set.
C. For non custom pages, this option was most useful because it allowed us to control who could search for what.
D. I went through every default page on my own personal site to specifically turn this feature on for all pages, only to find out it's been removed. I'd have been happier if the permissions system was removed regarding the ability to remove change page URL for non custom pages, so as to not mess up the site completely. Further more, while I'm on the subject of page permissions, it is currently possible to delete a system page which cannot be recovered once it is gone, like the site home page, the member browse page and so on.
2. Regarding the removal of tab container title field:
A. Completely unnecessary. The title field acted as a custom module header for a tab container and so providing it was very useful in this way to be able to headline a specific portion of a page or page column. Further more, one could potentially style a Tab container field by using this variable by putting an HTML box inside of it. This functionality was one of the only reasons why I'd use tab containers, because you could place a tab container inside of a tab container if you wanted, and was able to custom brand the tab menus as such.
B. Doing away with module titles takes away customization of the most basic level. We have no control over the description of a widget currently without having to modify code. Now we will have to do this for titles. This is a step backwards, not a smart idea.
3. Regarding the removal of admin settings link on profiles displaying to member levels without access to the control panel:
A. This issue never appeared on my site. The only way it ever could have, is by using the moderator role. Speaking of roles, you should do away with the public role, it never gets used. There should only be one admin role and perhaps a moderator role with limited customizable access to the control panel to remove or edit specific content.
B. This may cause potential problems because super admins are now the only people who are able to access this setting apart from admins.
4. Regarding the new setting of admin panel email enable disable option:
A. This could be seen as a cancellation of the change received to prevent people from receiving two welcome emails. This would recreate that issue.
B. I would never use this setting.
For the first time ever, I've had mixed feelings about upgrading to Social Engine latest version. I've never faced any security vulnerabilities on my site thus far, so no need to upgrade to less functionality than a big part of what I'm used to. Seems like some bloatware found its way into the development schedule roadmap along with the setting aside of important features of improving practical usage of the software. Issues that could never have been under feedback or opinion as they could be voted no on and this is the seemingly rather apparent and long overdue updated debut of this type of action.
Having said that, I'm glad the update is there. It shows you're still in business and haven't given up on us completely. Thank you for referencing the git hub page in the blog post. I really appreciate that. Also the welcome progress update for php7 and php6 is much appreciated.
You should consider supporting the mysqli extension for all modules.

**Comment by alimoosavi15** [comment]
1. Regarding the removal of show this page in search results check box.
_This is a UI improvement. No features were removed._
The checkbox was not being utilized for non-custom pages so it was removed for non-custom pages only. You can still use that option for custom pages. 
----------
2. Regarding the removal of tab container title field.
_This is a UI improvement. No features were removed._
The widgets inside tab containers can have titles. The tab container itself does not need a title and it was never showing a title even when you had a title set for it, so you're not going to see any differences.
---------
3. Regarding the removal of admin settings link on profiles displaying to member levels without access to the control panel.
_This is a UI improvement. No features were removed._
We addressed this issue for moderators only. Admins can still do profile edits from user profile page.
----------
4. Regarding the new setting of admin panel email enable disable option.
_This is a bug fix_
There was an issue with sometimes welcome emails being sent 2 times. We addressed this issue and also added an option for admins to choose if they want new users to receive emails or not.
---------
All fixes that are done are discussed in details and quality checked before release. The issues we addressed in this release were important issues reported by SocialEngine customers and all were confirmed by our development team. There are still more in our bug tracker and we'll be working on the rest for the next release. We're also discussing PHP7 and will be working to add support for PHP7 in SocialEngine in future releases.

**Comment by smazurov** [comment]
@Elshara I hope that is satisfactory. To follow up on #4, we now give admin an option to either send both emails or just one. Even though you might not use it, others will certainly appreciate it, since emails are different, separate, unique content can go into them.

Also, in the future, feedback on released features should be in either the blog comments, or the original issue, if they were reported using our public bug tracker.

As always, I thank you for your feedback!

**Comment by Elshara** [comment]
I understand this a bit better now. This does make a lot more sense. I
still believe issues 1 and 2 were things that seemed useful at the
time they were there. Perhaps I thought we had the feature activated
when it really wasn't there or necessary. As for issue 3, I actually
have come to take a look at it in greater detail and figure it is for
the best. Issue 4, I think I misinterpreted it slightly so I apologize
there. Thanks for removing the weather widget, I was going to report
it.
