### ISSUE TITLE
Video Embedding Won't Disable

### ISSUE THREAD

**Issue by MiamiShade** [SocialEngine/phpv4-issues#43]
SE 4..8.8

Unable via video plugin to disable video embedding of youtube & Vimeo.

To duplicate set to No.

**Comment by Anshuse** [comment]
Hello @MiamiShade ,

Thanks for reaching out!

This is not a known issue in SocialEngine PHP and we're not able to reproduce this at our end and so, we suggest you to file a support ticket along with your site details and our support staff will help you out.

Best Regards,
Anshu

**Comment by MiamiShade** [comment]
Perhaps you could take another look I have multiple SE users with the same bug

**Comment by Anshuse** [comment]
Hi @MiamiShade ,

We've checked this issue at our end again by following below steps:

1) Disabled "Allow Embedding of Videos?" from "Admin" > "Settings" > "Videos" > "Global Settings".

![video_embedding_option_disabled](https://cloud.githubusercontent.com/assets/11085507/7680966/6720c9be-fd89-11e4-85d3-98b65113be25.png)

2) Uploaded a video on site and we didn't see an option for "Embed" video.

![no_embed_option_is_being_displayed](https://cloud.githubusercontent.com/assets/11085507/7680972/7156a43a-fd89-11e4-8c9e-dc3715bd1e14.png)

If you're still facing this issue at your end then you may open a support ticket and our support staff will be glad to look into it.

Best Regards,
Anshu

**Comment by Anshuse** [comment]
Hi @MiamiShade ,

Currently, there's no such feature using which you can disable the option for Youtube or Vimeo from the video creation page.

Best Regards,
Anshu

**Comment by meetgerry** [comment]
While working on this, could you add an option where we can add the embed code to display videos of any video sites?

**Comment by shivani2910** [comment]
Hi @meetgerry, Thanks for your feedback. Yes, we already have a plan to work on something very similar to that in near future.

**Comment by smazurov** [comment]
consolidated under #155
