### ISSUE TITLE
Disappearing Comments

### ISSUE THREAD

**Issue by FurNation** [SocialEngine/phpv4-issues#430]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. …Use PHP 7+
2. …Post something on the activity feed.
3. …Reply to that feed.

What happens?
-------------
…  You post will appear for a second, but then the entire post and comment dissapears.

What were you expecting to happen?
----------------------------------
…No

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```Nothing logged.  Can't find any error.
Paste Log Here
```

Any other comments?
-------------------
…When switching back to PHP 5.6 the comments appear.  They are being saved, so it may be something in the reply back from the server that makes the comments go poof.

What versions of software are you using?
----------------------------------------
**Operating System:** …Windows 2012

**SocialEngine PHP Version:** …Latest on the site.

**Comment by Khushboo016** [comment]
Hi @FurNation , Thanks for bring this issue to our notice, I would like to tell you that we've just fixed some major bugs related to compatibility of PHP 7 with SocialEngine and we still have a lot more to do. So, we'll check this issue too.

Thanks!
