### ISSUE TITLE
Polls Module Doesn't Show Who Voted

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#432]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Polls module, click create new poll.
2. … Get another user to comment on the poll once it has been created.
3. … Notice comments don't appear in the activity feed. More to the point it doesn't show who voted if someone even yourself votes on an answer. This is critical for user feedback. Activity feed also doesn't show voting activity. Nor does anyone get an email such as the poll owner if someone voted on their poll.

What happens?
-------------
… Explained above. Short version, we need to see who votes on a poll.

What were you expecting to happen?
----------------------------------
… See above.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Nobody makes advanced polls. I tried to use a poll in an email to all members to gather feedback on site improvement. I never know if someone has commented or voted without viewing the poll and even then it only shows what the votes were for, no way to manage them or edit comments meant as a general note or any way to edit the poll itself. The feature is very underdeveloped in my opinion.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10

**SocialEngine PHP Version:** … 4.8.11

**Comment by Khushboo016** [comment]
Hi @Elshara , This is good to have an account of which members of site have taken part in polling, but at the same time it is not right to show which option of Poll the user has voted for. We have added this feature in our internal feature tracker and would discuss regarding its implementation in our future releases. 

Thanks!

**Comment by Elshara** [comment]
The option to turn it on or off would solve the problem.

**Comment by Khushboo016** [comment]
Hi @Elshara , We have added this suggestion in our internal feature tracker for internal team discussion. Thanks!
