### ISSUE TITLE
Enforce Social Engine Compatibility Settings For All Modules

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#433]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Install a new module from package manager.
2. … Check to see if it installs okay.
3. … Enforce query and technology update check for any time the module is being interacted with and track or record its statistics as a log.

What happens?
-------------
… Not implemented yet.

What were you expecting to happen?
----------------------------------
… Plugin is disabled if causing problems. Depending if the problem is temporary, plugin is once again reenabled via task scheduler. Plugin is reinstalled automatically if detected files may have changed that impact its performance. This is done to repair files that aren't working properly or throwing automatic Zend errors.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… The way in which module providers update their modules isn't stream lined and poses a security risk for social engine websites as technology supported by older plugins isn't supported by social engine or the greater web in terms of both server performance and competition websites. We need to make it easier for code to update and take care of itself only needing intervention if customizations wish to be made to how it works. This means more task scheduler reliability or cron jobs as an alternative.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10

**SocialEngine PHP Version:** … 4.8.11

**Comment by Khushboo016** [comment]
Hi @Elshara , It seems that if you are referring to have some kind of feature in SocialEngine that would check for the compatibility of modules at the time of their installation in terms of technology update. If this is what you want to explain, then would like to tell that as we are unaware of the code / features / implementation of the various third party modules, so, its hard to have an auto detection that whether features are working fine or not. So we don't have not any plans to implement this kind of feature. If you were referring to something else, then you can explain further.

Thanks!

**Comment by Elshara** [comment]
That's exactly what I'm referring to.
It isn't just the developers fault a website has intentional down time
after a plugin is installed or something is upgraded. The point is,
even Mozilla Firefox has a simple check to ensure add on modules are
compatible with the script, and Firefox is free.
Phpfox also has this though it's only used in rare cases.
Word press has it.
What I'm saying is that there should be a way to enforce a version
check on plugins so that say if a plugin boasts compatibility for the
last known version of Social Engine to its current version installed,
any social engine versions installed after that could potentially
bring up a warning if how social engine treats code in future
releases, changes significantly.

**Comment by smazurov** [comment]
We have plans to implement certification process that will include manual QA of the plugin prior to approving it.
