### ISSUE TITLE
Provide A Button To Edit Comments

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#434]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Make a post supporting the comments module.
2. … Post a comment with spelling errors.
3. … Once you click post a few times, and it shows up, try to find an edit button.

What happens?
-------------
… No edit button appears.

What were you expecting to happen?
----------------------------------
… An edit button to appear.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Comments need the ability to be edited from time to time. Preferably sorted by oldest first, newest first etc.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10

**SocialEngine PHP Version:** … 4.8.11

**Comment by Khushboo016** [comment]
Hi @Elshara , We have this feature added in our internal feature tracker and we'll work on this in our future releases.

Thanks!
