### ISSUE TITLE
Provide Navigation Buttons For Modules

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#435]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Specifically on the member profile page, adding modules related to profile posts, when the max item of posts is reached, previous and next buttons appear.
2. … Adding modules to any other page does not do this.
3. … They should function all the same. the navigation buttons make it very easy to find posts by module.

What happens?
-------------
… In addition to editing a module, before the module gets added, it should function like the html box where it asks you for the settings before closing the box as it gets saved. Settings should include navigation controls and the ability to sort items especially for the members modules.

What were you expecting to happen?
----------------------------------
… All of the above be implemented already.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… This will make users feel less alienated on the site as they start to become more active.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10

**SocialEngine PHP Version:** … 4.8.11

**Comment by Khushboo016** [comment]
Hi @Elshara , It seems that you referring here to further categorize the "Update" tab available on Member Profile Page i.e. to make sub categories under "Updates" for all the different modules available, so that updates related to a specific module can be accessed and searched faster by clicking on the category present for that module. Please confirm us if that is what you are referring here.    

Thanks!

**Comment by Elshara** [comment]
That is what I'm referring to.

**Comment by Khushboo016** [comment]
Hi @Elshara , There are some third party Advance Activity Feed based plugins available for SocialEngine which offer such feature to view categorized updates on the Member Home Page, so currently you can refer to those plugins for your site, and we have added this feature at our end for internal team discussion regarding its implementation in our future releases.

Thanks!
