### ISSUE TITLE
Fix for the Add Friend issue appearing after upgrading your site to v4.8.11

### ISSUE THREAD

**Issue by shivani2910** [SocialEngine/phpv4-issues#436]
What are the steps to reproduce this issue?
-------------------------------------------

- Login as User A and send friend request to user B.
- Login as user B and click on "Updates" from mini menu under header.
- Click on "View All Updates" link and you'll be redirected to `/activity/notifications` page.
- Click on "Add Friend" button appearing under "My Requests" section.

What happens?
-------------
An error message: "**invalid data**" gets displayed.

Solution
----------------------------------

- [Click here] (https://github.com/SocialEngine/phpv4-issues/files/297475/application.zip) to download the application.zip file and extract it to get the "application" folder.
- Upload this "application" folder in the document root of your SocialEngine installation to merge these files and overwriting the ones already existing on your server.
- That's all, you're done.

[NOTE: While we'll include this fix soon in our next release of SocialEngine PHP, above fix to enable you resolve the problem immediately on your site.)

What versions of software are you using?
----------------------------------------
**SocialEngine PHP Version:** 4.8.11

**Comment by Elshara** [comment]
Kind of surprised core updates like this isn't released as a minor update automatically in any currently hosted versions of social engine from client area.

**Comment by SpiritWolfie** [comment]
After applying this my users are still getting a Token error, (I've put a thread about it with a screenshot)

**Comment by Elshara** [comment]
Don't worry. It'll get fixed eventually.

**Comment by beevcra** [comment]
Yes - getting the same problem with 'view Recent updates' ...  look forward to next fix.

**Comment by Elshara** [comment]
Same here.

**Comment by smazurov** [comment]
Fixed in [4.8.12](http://blog.socialengine.com/2016/07/07/socialengine-php-4-8-12-is-here/)
