### ISSUE TITLE
Add Various Pages To layout Menu Editor

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#437]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Missing pages in layout editor.
2. … Missing menus in menu editor.
3. … Missing modules for both.

What happens?
-------------
… Cannot manage the user notifications or user updates page. No menu exists for this page.

What were you expecting to happen?
----------------------------------
… Being able to add a menu and add modules to the user notification page.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… The member browse page has no menu items. The forum topic page, along with all forum modules has no individual modules assigned. There is no menu for forums. The page doesn't exist for forum topics. Forum replies don't use the comments box. Forums require an over hall as far as the modularity, layout editor and menu editor are concerned as well as being able to like forum content, would be possible with the comments module. Forums require a browse menu, search menu, quick menu and comments. Not all modules have a quick browse menu.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10

**SocialEngine PHP Version:** … 4.8.11

**Comment by Khushboo016** [comment]
Hi @Elshara ,

Regarding "Missing pages in layout editor.":
We have already added this feature in our internal feature tracker and have plans to add new pages in Layout Editor in our future releases.

Regarding "Missing menus in menu editor.":
Please let us know which more menus need to be added, of which you think there is a requirement.

Regarding "Missing modules for both.":
Please explain this query in a bit more detail.

Thanks!

**Comment by Elshara** [comment]
Menus should correspond with the pages in layout editor you are
planning to implement. For both requires this implementation to be
active.
Possible examples include.
A purpose for the member browse menu. Adding some menu items to it, or
functionality accessing current member content or member basic profile
functions maybe like friends, messages, invitations, settings etc.
A menu to manage forum content as well as a search module. All forum
discussions, my forum discussions, add forum discussion. On which
page, all categories would have a drop down menu allowing someone to
choose which discussion to add the category to, rather than having
forums act like groups specifically because all the user sees is the
categories, and not the actual forum content. This should be changed
via module adaptability in layout editor.
The ability for members to have a user notifications menu, allowing
them to quickly view things that are pending their attention. Be it
unread notifications, recent messages, recent comments filtered by
module categories, recent likes filtered by module categories, the
ability to see content they've interacted in as well as automatically
filtration of updates posted to it and content involving module
requests independently such as friends, groups and events.
Additionally, the user notifications page should have the ability to
be able to follow any post without having to interact with it.
Automatically follow or unfollow specific posts by email or site
notification respectively so that a person if someone else comments on
it, would be able to view a notification stating a content item you
follow has received activity. Then it could be broken down into three
distinct categories. Content you created, content you responded to
either via like or comment someone else created, or something someone
else created you follow that you didn't respond to.
All of the above should be manageable via modules. I think main
content areas should be replaced in favor of specific modules placed
throughout the layout editor. This should be effective for all pages
of the layout editor covering the entire site, allowing individual
control over what columns and their respective height and width take
up things like the global footer or header, to the way in which the
page is accessed and utilized including global and member specific
settings for all pages. Content should be sorted based on what type of
content it is. Be it in the form of a menu, a post listing, like
latest activity, current post with custom questions, global settings
for menus and content sorting as well as a host of other integrations
that could link more than one module together. All managed through a
custom layout editor which could include a navigational site builder
and settings manager all in one area. Similar to how Boonex Dolphin
has their system manager set up.

**Comment by Khushboo016** [comment]
Hi @Elshara , We have added your suggestions at our end for internal team discussion and will take these into consideration whenever we'll work on adding new pages in the Layout Editor.

Thanks!

**Comment by Elshara** [comment]
Awesome. I'd like to point out that pages still in waiting are in
group and in event module functionality. In group home page, in group
discussion pages, in group event pages, in event photos pages, in
event discussions pages, in group photos pages etc.
