### ISSUE TITLE
Remove Title Field For All Non Essential Modules

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#438]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Layout editor.
2. … Modules list.
3. … Drag module to column click on edit.

What happens?
-------------
… Some modules have the inability to edit existing titles while other modules have the title already filled.

What were you expecting to happen?
----------------------------------
… Menus, search modules, sign up sign in module and other various modules like ad campaign among others remove or update the title tag. The quick links module has a title built in, but it can't be edited. All menu related modules have the same. Search has none. All other modules should have titles or should be able to edit the title using existing format rather than having to save changes, reload the page then edit it for any existing text to appear.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Cleaning up the UI suggestions and improvements like this is worth taking into consideration.

What versions of software are you using?
----------------------------------------
**Operating System:** … windows 10

**SocialEngine PHP Version:** … 4.8.11

**Comment by Khushboo016** [comment]
Hi @Elshara , We are sorry, but we did not exactly understand your point here. Please explain us query clearly that if you want us to remove the Title field for the modules, if yes then explain for which modules you want us to delete the Title field.

Thanks!

**Comment by Elshara** [comment]
Modules with a custom heading title already in place so its title can
be changed as necessary.

**Comment by Khushboo016** [comment]
Hi @Elshara , We have provided Title Field for the widgets, so that if anyone needs then he can change the title according to his wish. If you do not need to change the title, then you can skip that.

**Comment by Elshara** [comment]
ok
