### ISSUE TITLE
Provide Better Way To Manage Friends List

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#439]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Friends need a better management system.
2. … As does requests for groups events and personal updates.
3. … Preferably on independent pages.

What happens?
-------------
… There's no way to manage friends on its own page. Same goes for groups and events. If someone is invited somewhere, they have to double approve the invitation either by clicking on notifications and confirming their acceptance, or by having to view the item itself and again, confirming their willingness to participate or decline.

What were you expecting to happen?
----------------------------------
… Invitations, requests, approval and user moderation notifications be on their own pages.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… They all need their own menu or menu items as a module in addition to their own page.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10

**SocialEngine PHP Version:** … 4.8.11

**Comment by Khushboo016** [comment]
Hi @Elshara , Friends, group invitations and other personal updates are easily manageable from the Recent Updates page having the URL as http://**yoursitename**/activity/notifications. So, all updates can be managed from this single page. Please check this at your end and let us know if you have further queries.

Thanks!

**Comment by Elshara** [comment]
I know they are manageable from here, but if they had their own pages,
one for post comments, one for post likes, one for group invitations,
one for friend requests, one for event invitations or one for module
updates specifically, it would be very easy to manage by viewing the
module as a central hub of activity, rather than having to use a
separate page for managing all types of requests and notifications.
furthermore, a separate ability to put friends as their own module
rather than having to use the profile friends module would be very
much preferred. As it stands right now, there simply is no way to put
those modules on their own page, forcing people to view their own
profile to accept, confirm and remove friends. I'm asking for the
ability to have friends specifically be put on its own page.

**Comment by Khushboo016** [comment]
Hi @Elshara , Currently we don't have any plans to make separate pages to manage different activities like post comments, post likes, group invitations, friend requests etc, but we've added your suggestion at our end for internal team discussion for future releases.

Thanks!

**Comment by Elshara** [comment]
This is the best news I've heard in a long time!

**Comment by Khushboo016** [comment]
I am closing this issue for now, will reopen this when we'll work on this feature in future.
