### ISSUE TITLE
activity update loop start

### ISSUE THREAD

**Issue by SpiritWolfie** [SocialEngine/phpv4-issues#440]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. …install 4.8.11 SE (I Have applied the friends patch made by a SE team member that was listed in the git hub, not sure if this has anything to do with it)
2. …Check Details
3. …Happens in both SSL/None SSL of the site

What happens?
-------------
core.js?c=1:565 activity update loop start
core.js?c=1:565 TypeError: Cannot read property 'getElementsByTagName' of null(…)
core.js?c=1:565 activity update loop stop
core.js?c=1:565 activity update loop start
core.js?c=1:565 TypeError: Cannot read property 'addEvent' of undefined(…)
core.js?c=1:565 activity update loop stop

(And it just keeps spamming this over and over)
﻿

What were you expecting to happen?
----------------------------------

Not to see this error
Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------

This is a fresh SE install of the latest ver. This does not show up on my older vers 

What versions of software are you using?
----------------------------------------
**Operating System:** …

**SocialEngine PHP Version:** … 4.8.11

**Comment by SpiritWolfie** [comment]
Here is a screenshot of dev and none dev

![image](https://cloud.githubusercontent.com/assets/9712738/15816024/90e662e2-2b85-11e6-8024-a1e73112d311.png)

Vs

![image](https://cloud.githubusercontent.com/assets/9712738/15816037/ae1114de-2b85-11e6-871b-a520d8cc2410.png)

**Comment by SpiritWolfie** [comment]
Fix maybe?

Find: 
`console.log(object);`
Replace all instances with:
`console.dir(functor);`

The error seems to go away when I have done this.

**Comment by smazurov** [comment]
Thats probably incorrect. But, the `console.log()`'s only show up if your have console open, they have no negative impact on 99.9% of your visitors/members.

We'll certainly want to address this and any other javascript issues as we work on clean up and upgrade of the javascript, but we won't keep this issue open. Thank you for the report!

**Comment by DonnaScriptTechs** [comment]
Just a note to this, I tested my site today and don't see this issue. I believe we must have fixed this one already.
