### ISSUE TITLE
Improve W3C Validation

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#441]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)
## What are the steps to reproduce this issue?
1. … https://validator.w3.org/ for fixing html
2. … http://jigsaw.w3.org/css-validator/ for fixing css
3. … https://developers.google.com/speed/pagespeed/insights/ for fixing page speed and other usability errors
## What happens?

… Each page delivers performance based suggestions to improve the functionality of each page on your website. When you submit each URL of your site, you get detailed statistics by verified leading web developers of what are common issues in social engine sites that more often than not, are more than preventable.
## What were you expecting to happen?

… To not fix as many errors as I did using this tool. Errors can be duplicated using fresh install of social engine latest version. Pages tested includes all module main pages, the home page and all sample module pages including custom pages in layout editor.
## Any logs, error output, etc?

(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```
## Any other comments?

… I was going to upload the source code for my website to prove how improved I was able to make it using the google optomised version of the core files, but decided you could do this in independent tests for your website. The key here is to find common place errors on multiple pages to fix each issue in turn using the files required to load on the page. The most severe of which is loading too much unorganized script and css files in the head tag. Also absolutely 0 html mark up structure support for any html5 or css 3 documents. this must change in future versions of social engine for Google and other search engine compatibility problems to go away.
## What versions of software are you using?

**Operating System:** … Windows 10 and Firefox latest version

**SocialEngine PHP Version:** … 4.8.11

**Comment by alimoosavi15** [comment]
W3C validation is not important in ranking or performance. W3C is meant to be used for future-proofing, code maintenance and promoting good practices. Even Google [does not pass](https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.google.com%2Fwebhp%3Fsourceid%3Dchrome-instant%26ion%3D1%26espv%3D2%26ie%3DUTF-8) W3C tests.

[Why validate?](https://validator.w3.org/docs/why.html)

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#23

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
