### ISSUE TITLE
Feature request: Device sign-in notification and Sign-in Secruity 

### ISSUE THREAD

**Issue by xyzsimon** [SocialEngine/phpv4-issues#444]
Hi,

This is a feature request for:  Device Sign-In notification and Sign-In Security. 

I have a Gmail (Google) account.  Recently Google sent me an email that notified me that an attempted Sign-In was made to my Gmail account.  It was made in Manhuaca - State of Minas Gervais,  Brazil on June 5, 2016.  I was in Canada and have never been in Brazil. 

When Google emailed to informed me of this.... I followed their steps to secure my gmail account.  This got me to thinking.... SocialEngine PHP & Cloud would benefit from such a feature.  I hope SE would consider developing this feature for both User and Admin login.   This was be a great feature for v 4.9 or 5.0.
Refer to my attached images of the Alert that I received from Google and the corresponding pages that allowed me to view the history, etc. of my Device Sign-Ins.   Or better yet, ask someone from another state or country to attempt to login your Gmail account and you'll get the alert I am referring to.

Also, it would be great if SE  had a feature where the Admin can set how many attempted Sign-In can be attempted before, a wait time is implemented (decided by Admin too), they have to wait _________ minutes before allowed to Sign-IN.  However, I think implementing something like Google's feature discussed above is sufficient.... I think. 

Thanks for considering the feature request. 

Simon
![google new sign in from alert](https://cloud.githubusercontent.com/assets/16373524/15987474/6f1735bc-2fde-11e6-8ffd-fa6ade1c9bb2.jpg)
![google recently used devices - account secured](https://cloud.githubusercontent.com/assets/16373524/15987475/742150d8-2fde-11e6-8d91-e5062817a080.jpg)
![google recently used devices - if i click yes that it was me](https://cloud.githubusercontent.com/assets/16373524/15987477/7797014a-2fde-11e6-9dad-074d7c16b164.jpg)

![google recently used devices - securing account](https://cloud.githubusercontent.com/assets/16373524/15987481/a74e72ba-2fde-11e6-9117-c4cc7945a5ea.jpg)
![google recently used devices - unknown device sign-in attempt](https://cloud.githubusercontent.com/assets/16373524/15987484/ac87fe22-2fde-11e6-8f12-61fa1c50b523.jpg)
![google recently used devices - when i click secure account](https://cloud.githubusercontent.com/assets/16373524/15987486/b1c3ffd0-2fde-11e6-9e02-c1207373c1e0.jpg)
![google recently used devices part 1](https://cloud.githubusercontent.com/assets/16373524/15987488/b7e2ac0e-2fde-11e6-8e98-17bcbf41b361.jpg)
![google recently used devices part 2](https://cloud.githubusercontent.com/assets/16373524/15987489/bdac73a4-2fde-11e6-9208-06673457e958.jpg)
![google security-related notification and alerts part 2 of 2](https://cloud.githubusercontent.com/assets/16373524/15987490/c458439a-2fde-11e6-94b2-b43521743ab8.jpg)
![google security-related notofications and alerts page part 1](https://cloud.githubusercontent.com/assets/16373524/15987491/c80f7cce-2fde-11e6-8c03-cd21e2be9886.jpg)

**Comment by Khushboo016** [comment]
Hi @xyzsimon , Thanks for your nice suggestion, currently we do not have any plans for adding this feature in SocialEngine, but we've added your suggestion at our end for internal team discussion. 

Thanks!

**Comment by Elshara** [comment]
Providing a verified IP address would make this possible.
