### ISSUE TITLE
Provide Bulk Mark All As Read Functionality In Private Messages

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#447]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Send a message to someone.
2. … Wait for a reply.
3. … Once the reply is in, open your inbox.

What happens?
-------------
… No mark as read option is available.

What were you expecting to happen?
----------------------------------
… To be able to do more bulk actions than delete. Perhaps archive or forward or mark as read, unread, or save to a custom folder.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… All other message systems have this functionality.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10

**SocialEngine PHP Version:** … 4.8.11

**Comment by Khushboo016** [comment]
Hi @Elshara , Thanks for your suggestion, we have not any plans for its implementation now but have added this at our end for internal team discussion.

Thanks!
