### ISSUE TITLE
Spam Ban Tools Feature Request

### ISSUE THREAD

**Issue by bfriended** [SocialEngine/phpv4-issues#448]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. …Log into the admin panel
2. …Click On Settings
3. …Click On Spam & Banning Tools
4......Click On Log-In History
5......Type a selected IP in a simple search filter
6......Click on Select All
7......Click on Delete Selected
8.......View a Pop Up that as are your sure you want to delete selected IP's
9...... Click Yes or No
![screenshot 181](https://cloud.githubusercontent.com/assets/12755263/16327878/c1db3694-3999-11e6-89cf-8945de89416b.png)

What happens?
-------------
…There is no way to select individual items for deletion. The only option is to clear the entire history

What were you expecting to happen?
----------------------------------
… We would like to be able to select individual items from the login history and delete them as we add them to the bad IP list for banning. We would like check boxes to be placed by each log in item so it may be selected individually and deleted once the bad IP is added to the banning tool.

Any logs, error output, etc?
----------------------------
 http://www.bfriended.com/admin/user/logins

```
Paste Log Here
```

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** …
Windows
**SocialEngine PHP Version:** …
4:8:11

**Comment by Khushboo016** [comment]
Hi @bfriended , Thanks for your suggestion but if we provide check boxes against each entry in the login history to delete individual IPs from history, then the Admin would have to select all the occurrences one by one of a particular IP address to delete it from the list in case there has been done login for several times from that IP and that is not a good idea. 

Thanks!

**Comment by Elshara** [comment]
Why not do a database search for that IP and when the ban action is performed, remove it from the log or currently show a list of banned IP login attempts once an instance of a particular IP and or email address is found to be in the ban list. Essentially, check the ban list before displaying results and prevent them from displaying in the main results list.
This could be done by doing the following.
1. Sign in to site x. Use a bad password.
2. Go to admin. Ban spam tools. login history.
3. Click the filter show bad password attempts. Make sure a search filter is displayed allowing you to search by specific user name, email, IP etc.
4. When you click on the result you want, an edit option should appear along with a delete option. Performing standard actions like removing the entry or placing their ip, email or name in the banned members list should if found to have an account or ip by such criteria, remove all other instances because you've already performed a search in the first place. Then you can just remove all attempts by criteria such as bad password, no member etc.
Another way you can do this is just provide such search tools on the main page.
I fully support this idea. It is a very good idea, if you follow a process to remove or block an IP from the history page itself.
Especially useful if an annoying user is doing all the fuss.

**Comment by bfriended** [comment]
I think its a great idea because spam from bad IPs is a huge problem for websites. A simple search filter would populate the IPs that need to be banned, and a simple delete selected would eliminate the need for checking of each Ip individually.  Please consider this more carefully.  Please read the suggestion of another user Elshara below:

Why not do a database search for that IP and when the ban action is performed, remove it from the log or currently show a list of banned IP login attempts once an instance of a particular IP and or email address is found to be in the ban list. Essentially, check the ban list before displaying results and prevent them from displaying in the main results list.
This could be done by doing the following.
1. Sign in to site x. Use a bad password.
2. Go to admin. Ban spam tools. login history.
3. Click the filter show bad password attempts. Make sure a search filter is displayed allowing you to search by specific user name, email, IP etc.
4. When you click on the result you want, an edit option should appear along with a delete option. Performing standard actions like removing the entry or placing their ip, email or name in the banned members list should if found to have an account or ip by such criteria, remove all other instances because you've already performed a search in the first place. Then you can just remove all attempts by criteria such as bad password, no member etc.
Another way you can do this is just provide such search tools on the main page.
I fully support this idea. It is a very good idea, if you follow a process to remove or block an IP from the history page itself.
Especially useful if an annoying user is doing all the fuss.

**Comment by bfriended** [comment]
I think its a great idea because spam from bad IPs is a huge problem for websites. A simple search filter would populate the IPs that need to be banned, and a simple delete selected would eliminate the need for checking of each Ip individually.  Please consider this more carefully.  Please read the suggestion of another user below:
Why not do a database search for that IP and when the ban action is performed, remove it from the log or currently show a list of banned IP login attempts once an instance of a particular IP and or email address is found to be in the ban list. Essentially, check the ban list before displaying results and prevent them from displaying in the main results list.
This could be done by doing the following.
1. Sign in to site x. Use a bad password.
2. Go to admin. Ban spam tools. login history.
3. Click the filter show bad password attempts. Make sure a search filter is displayed allowing you to search by specific user name, email, IP etc.
4. When you click on the result you want, an edit option should appear along with a delete option. Performing standard actions like removing the entry or placing their ip, email or name in the banned members list should if found to have an account or ip by such criteria, remove all other instances because you've already performed a search in the first place. Then you can just remove all attempts by criteria such as bad password, no member etc.
Another way you can do this is just provide such search tools on the main page.
I fully support this idea. It is a very good idea, if you follow a process to remove or block an IP from the history page itself.
Especially useful if an annoying user is doing all the fuss. 

    On Friday, June 24, 2016 7:21 PM, Elshara Silverheart <notifications@github.com> wrote:
 

 Why not do a database search for that IP and when the ban action is performed, remove it from the log or currently show a list of banned IP login attempts once an instance of a particular IP and or email address is found to be in the ban list. Essentially, check the ban list before displaying results and prevent them from displaying in the main results list.
This could be done by doing the following.
1. Sign in to site x. Use a bad password.
2. Go to admin. Ban spam tools. login history.
3. Click the filter show bad password attempts. Make sure a search filter is displayed allowing you to search by specific user name, email, IP etc.
4. When you click on the result you want, an edit option should appear along with a delete option. Performing standard actions like removing the entry or placing their ip, email or name in the banned members list should if found to have an account or ip by such criteria, remove all other instances because you've already performed a search in the first place. Then you can just remove all attempts by criteria such as bad password, no member etc.
Another way you can do this is just provide such search tools on the main page.
I fully support this idea. It is a very good idea, if you follow a process to remove or block an IP from the history page itself.
Especially useful if an annoying user is doing all the fuss.—

**Comment by Khushboo016** [comment]
Hi @bfriended , @Elshara , We have added your suggestion in our internal feature tracker for internal team discussion and whenever we'll do any improvement work regarding Spam & Banning Tools section, we'll surely take your suggestions into consideration.

Thanks!
