### ISSUE TITLE
Google Bot Access Is Denied

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#449]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Install online counter on your site, make sure it's visible on the page. http://freehostedscripts.net/onlinecounter/
2. … Wait about 20 hours after you install it, then open up the unique id based url on your site.
3. … Browse to the 24 hour statistics page.

What happens?
-------------
… Google bot and other search bots will be listed in there along with the pages it visits. The page is not being displayed to the regular human eye as a link, but the path is included. The path is different where it shouldn't be.

What were you expecting to happen?
----------------------------------
… Google bot to visit regular trackible urls you could paste in any web browser so it could read the content on your site!

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Urls look something like this. /login/return_url/64-L2xvZ2luL3JldHVybl91cmwvNjQtTDJ4dloybHVMM0psZEhWeWJsOTFjbXd2TmpRdFRESjRkbG95YkhWTU0wcHNaRWhXZVdKc09URmpiWGQyVG1wUmRGUkVTbGROYkhCWVRsUkNUV1ZyVmpWVlJFbDRaR3hzZEdKSVRtRldSRUl6VURJeGRsbHRiSE5hVkRCM1AyMXZZbWxzWlQwdz9tb2JpbGU9MA%3D%3D  /login/return_url/64-L2Jsb2dzLzMwLzI3OS9wcm9ncmFtLWN6eS1pbnR1aWNqYS13eWJvci1uYWxlenktZG8tY2llYmll /login/return_url/64-L2xvZ2luL3JldHVybl91cmwvNjQtTDJ4dloybHVMM0psZEhWeWJsOTFjbXd2TmpRdFRESjRkbG95YkhWTU0wcHNaRWhXZVdKc09URmpiWGQyVG1wUmRGUkVTalJrYkc5NVlraFdUVTB3Y0hOYVJXaFhaVmRLYzA5VVJtcGlXR1F5Vkcxd1VtUkdVa1ZUYlVacllsVTFNVlp0TlZOaGJWWlZZVE5rV21Gck5VUlpNRnB6VGxVNVNXSkZOVmRTTTFGNVYyeGFhazVWTVZabFJtaFRZbTE0YUZaWWNFWmtNV3hXV2taYWExSXhSalZWYlhCWFZGWmtSMU51V2xoaVJURTBWRlZrVDJSV1duRlJiV2hTWld0YWRsZFhNSGhWYlZKSVZXdG9hRkl6YUU1V2FrNXZaREZrY1ZOdE9VNVNhMFkxVkZab1lWZHRTbGhsU0hCWVlrWkdNMXBJ

What versions of software are you using?
----------------------------------------
**Operating System:** … Not sure how to answer this question, either server or personal OS. Server Linux, personal Windows 10.

**SocialEngine PHP Version:** … 4.8.11 with mobile version enabled

**Comment by sgreiner** [comment]
You can fix it with a robots.txt:
```
User-agent: *
Disallow: /login/return_url/
```

**Comment by Elshara** [comment]
Interesting! I didn't know that was possible. I thought the path for
robots.txt had to be relative as in an absolute directory for it to
work. Such as /application/modules or /application/themes etc.

**Comment by smazurov** [comment]
Don't think this is a SE issue, so I am closing it.

**Comment by Elshara** [comment]
I wouldn't have reported it here if it isn't related to social engine.
It's a third party access issue.
The part that strictly deals with SE is the code redirection. The fact
that Google visits it, frequently, indicates it's either trying to
access a blocked resource, or it's looking at the page structure and
the first url it sees, the sign in url, would result in this behavior.
Diagnosis shows the sign in url is the most accessed because on each
page, it is different. Google thinks as well as other bots, the url is
a new page, so it starts crawling it, only to find out it's the same
sign in page. Having a static sign in url would fix this on the front
end, even though redirection could still be managed on the back end if
desired.
Think about it. Any page that offers a redirect can be also accessed
directly without sign in. So Google tries to access an alternative
version of that page not realizing it can access it directly if the
login url was a static one like every other url on the page.
This is why the errors continue. Social Engine is redirecting someone
to sign in, but, because the url has a redirect dynamic structure to
it, bots think it's a new page, so it gets more of itself to look on
that page to discover is it an error in the server, what do I do with
this? In response, Google puts more bots on the same page it
frequently visits thinking it's blocked and is a dynamically updating
page, even though it's a static content page.
You know another fix for this issue would be to create a bot account
for Google to automatically be signed in to as well as for other
recognized bots so that the error doesn't occur. Even though, it might
because instead of the log in url, it would now be faced with the log
out url unless the options were essentially hidden by disabling the
member updates menu. I don't want to have to remove the mini menu from
the global header because I need it to access the admin page. I have
no way of hiding that menu item from members otherwise. I tried to get
you to see that earlier indirectly but you said you have no plans of
implementing member access permissions level control for modules and
module items, so because dynamic urls link to redirection, not like
the mobile version where the actual main url remains the same accept
for the added mobile=1 or mobile=0 respectively, it wouldn't result in
a problem should signed out and signed in visitors be treated
similarly and you could still redirect the page because the
redirection factor isn't there plus the url wouldn't be treated
dynamically.
So to reiterate the social engine culpability of improvement for this
type of issue, the url structure for the sign in sign out page is what
is the cause of this problem. I only linked you to a third party tool
to access and reproduce the issue so you could see for yourself what
was going on, not that such a tool was the problem, which is what you
were thinking.
