### ISSUE TITLE
Translation Performance: csv_folder_to_array() tries to escape file resource, constantly fails

### ISSUE THREAD

**Issue by rwetzlmayr** [SocialEngine/phpv4-issues#45]
Affects SE PHP 4.8.8.

Steps to reproduce:

1. Verify that PHP may call the 'exec' function
1. Check 'Translation Performance: Convert Language Pack CSV files to a PHP Array?' in **Settings > Performance and Caching**
1. Hit **Save Changes**
1. Receive error message stating 'Language packs could not be converted to PHP Arrays.'

I traced this back to the ```csv_folder_to_array()``` function in ```application/modules/Core/Controller/Action/Admin.php``` line #130:

```
    exec('php -l ' . escapeshellarg($fp), $output, $ret);
```

SE tries to apply ```escapeshellarg()``` on ```$fp``` which is not a string but a file resource, and fails.

Proposed fix:

```
    exec('php -l ' . escapeshellarg($php_array_file), $output, $ret);
```

**Comment by Anshuse** [comment]
Hello @rwetzlmayr ,

Thanks for bringing this issue to our attention and providing fix.

We've forwarded this issue to our development team and will resolve this in next version.

Best Regards,
Anshu

**Comment by myetter37** [comment]
SocialEngine PHP version 4.8.9 has been released, and this issue has been fixed in that release.
