### ISSUE TITLE
Make Follow Module Separate From Friends And Allow The Use Of Follow By Content Type

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#450]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Follow module is completely disabled if two way friendships are enabled.
2. … When follow module is activated, or independent of friends module, no way currently exists to follow someone either by their activity or via a specific post unless you like or comment on it. No email is sent regarding the status of what you follow and don't follow as you follow it.
3. … Followers and friends don't have their own page. the requests module only works on the members home page, making it difficult to distinguish user based interaction from group interaction with other members regardless of the module you are viewing. A must have for members to take privacy and other one on one functions seriously without having to rely on private messages to get the job done.

What happens?
-------------
… Friends and followers are the same thing, but adding all friends and follow modules on a profile updates page sorts all the data by oldest first, not newest first. It's like watching the same sports game every time you visit someones profile, having to click next a few thousand times to see the latest friends you have is not cool. So by these 4 modules being accessed as if they were meant to be out of the way by their sorting order, and because it only takes one of them to properly not duplicate the same content, it would be wise to make the functionality of follow module separate from that of the friends module. So that you could see the content as well as the users someone is following or follows, similar to Twitter regardless of whether it is a post, post index, post category or a group of posts, users and categories. Sorted by newest item first.

What were you expecting to happen?
----------------------------------
… This implementation to be considered because it would make a very wise use out of the follow module.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Rename follow module to interactions.

What versions of software are you using?
----------------------------------------
**Operating System:** … Linux server, windows 10 personal computer.

**SocialEngine PHP Version:** … 4.8.11

**Comment by Khushboo016** [comment]
Hi @Elshara , We've added your suggestion at our end for internal team discussion.

Thanks!
