### ISSUE TITLE
Appreciation For Social Engine Add Ons And Radcodes

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#451]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Radcodes is amazing at RSS content creation for modules, a must have for seo and sitemap generation.
2. … Social Engine Add Ons makes the best content importer and the most user friendly modules out there for advanced inspiration.
3. … Together they are the best main module developers social engine has at the moment.

What happens?
-------------
… When people install a module from social engine add ons, they make sure things work no questions asked. Same goes for radcodes, installation works well.

What were you expecting to happen?
----------------------------------
… Some parts of social engine add ons work to load faster at peak times during the day, but overall a very worth while investment. Some performance improvements with radcodes, but overall a very worth while investment.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… I recommend buying anything they put out. Nothing is bug free in the world, but things are definitely better when they work well together. Compatibility is mutually intelligible which makes it worth it.

What versions of software are you using?
----------------------------------------
**Operating System:** … Linux server, windows personal computer.

**SocialEngine PHP Version:** … 4.8.11

**Comment by smazurov** [comment]
please leave reviews for those developers on their pages, this is not a discussion forum.

**Comment by Elshara** [comment]
Thanks for the update.
