### ISSUE TITLE
Photos In Emails Don't Display

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#452]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Photo email templates exist for user interactions.
2. … Adding the code manually doesn't do a damn thing.
3. … Even though email providers report the links as if they would have an image attached.

What happens?
-------------
… Users open their email expecting to see images or photos but find none.

What were you expecting to happen?
----------------------------------
… Templates like this to `work.` [header]<br> <a href="http://[host][recipient_link]"><img src="http://[host][recipient_photo]" alt="">[recipient_title]</a><br> <a href="http://[host][sender_link]"><img src="http://[host][sender_photo]" alt="">[sender_title]</a> has invited you to join the group <a href="http://[host][object_link]"><img src="http://[host][object_photo]" alt="">[object_title]</a> on Website Name.<br> [object_description]<br> [footer]

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Referencing the img tag should pull up the relative image directly.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal computer, linux server.

**SocialEngine PHP Version:** … 4.8.11

**Comment by smazurov** [comment]
the way around this is to just reference a full url. Since we don't do any media storage per-se, I don't think its our responsibility to convert relative image paths to full image paths

**Comment by Elshara** [comment]
Dynamically generated photos belonging to user profiles and their
posts cannot be seen when an email containing its possible property is
sent out.
That's why I posted this issue to begin with. Using a static url in
such cases doesn't represent the content or profile it's supposed to.
Making your own photo template useless because it doesn't reference
that particular photo as a full path where it should to be included in
an img tag.
