### ISSUE TITLE
Browse Member Search Widget not working properly

### ISSUE THREAD

**Issue by luramos2016** [SocialEngine/phpv4-issues#453]
## What are the steps to reproduce this issue?
1. Go to Member Browse page
2. Select Profile Type #1 to browse members
3. Select some 2nd level Profile Question from Profile Type #1
4. Change Profile Type #1 to Profile Type #2 (on the same page, using the Browse Member Search Widget)
## What happens?

Profile Type #2 displays Profile Questions from Profile Type #1 or another (e.g. Profile Type #3, Profile Type #4)
## What were you expecting to happen?

I expect Profile Type #2 to display the Profile Questions from Profile Type #2
## Any logs, error output, etc?

No.
## Any other comments?

It seems to be caused by a Javascript error/conflict.
## What versions of software are you using?

Tested on Google Chrome, Mozilla Firefox, Windows 10, deactivated all 3rd party plugins.

**SocialEngine PHP Version:** …
SE PHP 4.8.11

**Comment by smazurov** [comment]
How are you displaying profile types in the search?

**Comment by luramos2016** [comment]
I've got:
Profile Type #1 
Profile Type #2 
Profile Type #3 
Profile Type #4

If user chooses:
Profile Type #1 
        > Choose your Profession
                  > Profession 1
                  > Profession 2
                  > Profession 3

If user then opt to choose:
Profile Type #3 
        Instead of:
        > Choose a Service
                  > Service 1
                  > Service 2
                  > Service 3
        User sees:
        > Choose your Profession
                  > Profession 1
                  > Profession 2
                  > Profession 3

Meaning Profile Type #2 shows Profile Questions of Profile Type #1 when it should be showing Profile Questions of Profile Type #2 

I believe there should be a Javascript conflict somewhere that doesn't allow Ajax to update the Profile Questions of the corresponding Profile Type

Did I make myself clear?

**Comment by smazurov** [comment]
Ok, thanks for that. I was still unable to reproduce it. Here's an example of it: https://kyle.socialenginedev.com/members, and it works fine, can you provide more detail? Does having more than 2 profile types important?

**Comment by luramos2016** [comment]
Can you email me at edgarmoria@hotmail.com so I can send you an example?

**Comment by luramos2016** [comment]
Just sent you an email to the contact on your GitHub profile

**Comment by luramos2016** [comment]
Hi there, 
Are you getting my emails at all? Are you looking at the issue? Please, pretty please, let me know if you're taking care of it because if you're not I'll have to find an alternative.

**Comment by alimoosavi15** [comment]
@luramos2016 To keep everything organized, please include all the information here instead emailing. We'll use this topic as a reference when working on the issues.

**Comment by smazurov** [comment]
We're still working on reproducing it. Keep in mind that this is lower priority than our paid support (which you can contact with this issue), and general tasks we're working on, such as a very recent 4.8.12 release.

**Comment by luramos2016** [comment]
Hi Stepan,

The changes you've made fixed the fields update issue but broke the search button. Can't perform a search at all now :/

**Comment by luramos2016** [comment]
Hi again,

Just to leave you a sincere THANK YOU for the professionalism and the brevity you dealt with this issue. Kudos for the Social Engine team!

**Comment by DonnaScriptTechs** [comment]
I cannot reproduce this in our upcoming 4.9 release. If you can still reproduce this after our release, please open a new issue.

**Comment by Elshara** [comment]
Awesome!
