### ISSUE TITLE
bug crashes upgrades

### ISSUE THREAD

**Issue by FrankatMassif** [SocialEngine/phpv4-issues#456]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. …download updates
2. …open update control panel and press update button
3. …press and follow the update stream

What happens?
-------------
…Web site crashes

What were you expecting to happen?
----------------------------------
…expecting website to be updated

Any logs, error output, etc?
----------------------------
Warning: include_once(/home/cntrymuz/public_html/application/libraries/Engine/Server/Php.php): failed to open stream: No such file or directory in /home/cntrymuz/public_html/application/libraries/Engine/Loader.php on line 103

Warning: include_once(): Failed opening '/home/cntrymuz/public_html/application/libraries/Engine/Server/Php.php' for inclusion (include_path='/home/cntrymuz/public_html/application/libraries:/home/cntrymuz/public_html/application/libraries/PEAR:.') in /home/cntrymuz/public_html/application/libraries/Engine/Loader.php on line 103

Fatal error: Class 'Engine_Server_Php' not found in /home/cntrymuz/public_html/application/modules/Core/Bootstrap.php on line 31

```
Paste Log Here
```

Any other comments?
-------------------
…just that it cost me $15 bucks, and three days of activity!

What versions of software are you using?
----------------------------------------
**Operating System:** …

**SocialEngine PHP Version:** …

**Comment by SpiritWolfie** [comment]
did you get a no key for zend_db error by any chance while doing the upgrade? if so that's the same issue I got and you may wanna read my post by Shiv that she closed.

**Comment by Khushboo016** [comment]
Hi @FrankatMassif , We are very sorry for the inconvenience caused, this issue occurred when we made the new release 4.8.12 and it lasted for about 4-5 hours, after that we resolved the same issue in the build of SE itself, so if you are still facing the same issue please download the update afresh and install it, you wouldn't face the issue again.

Thanks!
