### ISSUE TITLE
Enhancement request - notating staff

### ISSUE THREAD

**Issue by SpiritWolfie** [SocialEngine/phpv4-issues#457]
As it stands from what I can tell, there is no way to add like a banner/or like color coding/tagging to Admin/moderators of the site

This is a huge problem for any community that has user base, As some users will not know who the staff is, Is there ANYway I can adjust something in the code or what not to maybe color code staffs names or something? or add like a small banner next to our name that says "Admin?" or something?

**Comment by Khushboo016** [comment]
Hi @SpiritWolfie , We've added this suggestion at our end for internal team discussion regarding its implementation.

Thanks!

**Comment by SpiritWolfie** [comment]
@Khushboo016 

Could you tell me where I could do the code changes on my end to achieve this? I'm sure I'm not the only person who would like to know this, I'm sure plenty of other social engine addon owners would love to know how to do this.

**Comment by Khushboo016** [comment]
Hi @SpiritWolfie , We provide solution for code customization only when it is a small or minor code level changem but in this case there is need to do modifications in several files at several locations, so we are sorry, we would not be able to provide you the solution for this issue. You can refer to our third party developers from http://www.socialengine.com/customize/se4/developers for this issue, these developers would be happy to help you.

Thanks!

**Comment by Elshara** [comment]
You could also change where it says members profile type to members level under profile basic information.
