### ISSUE TITLE
Search broken with MySQL 5.7

### ISSUE THREAD

**Issue by sgreiner** [SocialEngine/phpv4-issues#458]
What are the steps to reproduce this issue?
-------------------------------------------
1. Do a search /search?query=something

What happens?
-------------
Error: Zend_Db_Statement_Mysqli_Exception: Mysqli prepare error: Incorrect usage of UNION and LIMIT in
/application/libraries/Zend/Db/Statement/Mysqli.php:77

What versions of software are you using?
----------------------------------------
**SocialEngine PHP Version:** 4.8.11

Here is a patch for file: application/modules/Core/Api/Search.php:
```
Index: Search.php
===================================================================
--- Search.php	(revision 1660)
+++ Search.php	(working copy)
@@ -105,7 +105,7 @@
           ->limit(3);
 
       $select_union = $table->select()
-          ->union(array($select_word, $select))
+          ->union(array('(' . $select_word->assemble() . ')', '(' . $select->assemble() . ')')) // not compatible with MySQL 5.7 without parentheses if using aggregate functions
           ->order('type DESC');
     return $select_union;
   }
```

**Comment by alimoosavi15** [comment]
I can't reproduce this issue on SocialEngine 4.8.12 and MYSQL Server 5.7.12.
