### ISSUE TITLE
Opting out of a feed (Feature request)

### ISSUE THREAD

**Issue by SpiritWolfie** [SocialEngine/phpv4-issues#459]
As it stands feeds can get pretty busy, there seriously needs to be a way to opt out of a feed to stop getting notices from it...

This has been requested by my community more times then I care to count, there's a few ways you guys could go about this, using a unsubscribe feature like the forums has.. Etc..

**Comment by Khushboo016** [comment]
Hi @SpiritWolfie , If you are referring here to the notifications that are shown in the "Updates" tab, then there is setting provided at the users end from "Settings" > "Notifications" section from where it can be set that which notifications are to be populated in the updates. 

And if you are referring to the feeds generating in the Activity Feed, then we suggest if you have a large network then allow only the feeds from "Friends and Networks" to be generated in the Activity Feed. And there are Activity Feed Item Type Settings from where you can choose which type of action feed to be shown in the Main Feed. So, you can set these according to your requirements to reduce the feed content.

Thanks!

**Comment by SpiritWolfie** [comment]
I am referring to when people have a conversation on the activity wall

User A Starts a post about the movie Zootopia , User B, C, D , E , F all jump in talking about the movie

Users C, D, E Decide the conversation is getting too noisey, they want to no longer get 'notices' from this feed and wish to 'opt out of just this feed or any other feed they no longer wish to be apart of'

Think of a Forum post, how you can 'unsubscribe from it' when you no longer wish to be apart of it, Social engine is dire need of this kind of feature for the activity wall.

**Comment by smazurov** [comment]
Makes sense, we'll look into it.

**Comment by SpiritWolfie** [comment]
@smazurov 
Thank you, If I need to give a more clearer explanation I can take a screenshot

**Comment by Elshara** [comment]
Comments don't have an unsubscribe or subscribe option in general so comments would also need to be looked in to.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#24

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
