### ISSUE TITLE
Manual password reset doesn't seem to work

### ISSUE THREAD

**Issue by davidfavor** [SocialEngine/phpv4-issues#46]
Customer has lost their admin login + a developer they hired has apparently modified their login code, so normal password recovery returns an empty user + empty password.

Went through steps listed here to do a command line password reset...

http://support.socialengine.com/php/customer/portal/articles/1639195-manually-reset-an-admin-password-

Reset password + salt. Still unable to login.

Let me know if this procedure is still correct or there's a more up to date way to do this.

Thanks.

**Comment by smazurov** [comment]
the procedure is still correct, ensure you have a recent version of SEPHP and followed it correctly.  You might need to reset the cache if that exists as well.

**Comment by davidfavor** [comment]
http://www.socialengine.com/support/php/faq (SEPHP) has no mention of reset procedure.

http://www.socialengine.com/support/php/faq has no instructions for "resetting cache".

1) What does SEPHP have to do with manual password reset?

2) Where are instructions for "reseting cache"?

Thanks.

**Comment by smazurov** [comment]
Resetting the cache will depend on which cache you've set up. You can read more about cache in [this article](http://support.socialengine.com/php/customer/portal/articles/1639869)
