### ISSUE TITLE
Feature requests regards profile questions

### ISSUE THREAD

**Issue by poeticjustice** [SocialEngine/phpv4-issues#461]
Hi Social Engine 

Just dropping message regarding a feature request.

I think its a valuable asset to SE and future, especially as alot of third party developers dont like editing core files.

Profile questions need updating.

1/ I think a great addition would be tags.
Great example

for a profile question Hobbies

Listing a list of multiselect or multi radio button feels very very old and looks messy especially when using browse members

a great addition would be like tags, 
As members begin typing and hit enter, it adds that tag to the profile question answer, or as they click on a hobby in a single select box, it adds the tag selected below, and as they access same select box, they can add more, and those tags that have been added already are greyed out or have a strikethrough so the tag cant be readded

2/ When user signs up or edits /members/edit/profile

Now ive never seen a website display the description above the entry box.

If a description is added to a profile question.
SE by default shows the question on the left, and directly inline on the right shows the description, then the entry box below it, and it looks confusing as most users are use to a description detail below the box they can add data too.

3/ Another feature regarding descriptions added to questions.

It would great if decription box supported html.
Example, If a question is asked, and its regards to measuring my inside leg. adding a href html link to a external video that acts as a tutorial would be very valuable.

and if it had option to make the text italic would be great.

4/ ive successfully in past made specific profile questions, for social links such as instagram, its very simple this one and i could even provide the extra 2 files plus where to edit core file, but tbh it would be great for others.
I mean who uses AIM?
such a old question

hope to hear others thoughts and hear back from SE, i mentioned some of these to SE team in past plus James Clark, but not heard much regarding the ideas

thanks

**Comment by poeticjustice** [comment]
Just additional comment regards to point 2.

2/ When user signs up or edits /members/edit/profile
Now ive never seen a website display the description above the entry box.
If a description is added to a profile question.
SE by default shows the question on the left, and directly inline on the right shows the description, then the entry box below it, and it looks confusing as most users are use to a description detail below the box they can add data too.

---
This is more confusing because when you signup, on first signup page

description is below the fillable content form area

example
 email address, then directly to right is the box, and below it is a description "You will use your email address to login."

![desc](https://cloud.githubusercontent.com/assets/19233272/16690607/ae80fd94-4520-11e6-9335-40b9a93f6cfb.jpg)

**Comment by poeticjustice** [comment]
Ive been mentioning this for a while in the past, it looks so confusing when you have loads of profile questions, especially when everyone if use to descriptions below not above, and especially as the first page shows descriptions below.

@smazurov love to hear your thoughts.... it may not seem a big issue, but believe me it really is, when my users email in about it, and have entered data too early because they read the descriptions as below, rather than on top

examples of users entrys

Location (description above user reads as description below) = entry = Football
Hobbies  (description above user reads as description below) = entry = Web Designer
Job title  (description above user reads as description below) = entry = Web design for dummies
favourite book (description above user reads as description below) = entry = Falling Down
favourite film (description above user reads as description below) = entry = Cat
favourite animal (description above user reads as description below) = entry = Mcdonalds
favourite food (description above user reads as description below) = entry = Military

**Comment by smazurov** [comment]
moving description to be above can be accomplished with css. We should make it standard, and move it below the fields, though.

**Comment by poeticjustice** [comment]
i asked the SE team in a ticket once about this, and asked if can be done with css, they said it couldnt as it was core files, i asked for location in core files to change it round, but they said they couldnt advise and i would have to hire a developer, and all developers have said they will not edit core files at all.... i personally tried to do myself via custom css but could not achieve it,

but as standard i truely believe it should be below, as i personally get too many wrong entries and emails regarding it, and if the description is very long, it totally ruins the look.

If you know a custom css for time being id appreciate, but it really needs addressing esp as i have upto 50 profile questions  @smazurov

**Comment by smazurov** [comment]
I do not of top of my head.

**Comment by SpiritWolfie** [comment]
If you are going to make some of this stuff at the bottom of the boxes, please make it a two way street, Meaning, give us a option to use that methiod or not

not everyone likes stuff under the boxes, Almost every website in existence I've used has the label ontop the box on bottom, this is a normal standard for allot of websites, having it on box on top and label on bottom would get very confusing to those of us use to the top to down

So please don't change this without providing a option for those of us who are use to this layout. 
Thanks!

**Comment by poeticjustice** [comment]
I agree there @SpiritWolfie 

I think, this was done in error ages ago and never really noticed it.

It looks silly when first signup page is one way, then changes on page 2 of signup.
But when you have 2 plus paragraphs for description, it looks stupid with description on top.

but to all those who are use to it, i fully understand your concern, if @smazurov or social engine could offer update with a choice that would be great.

if he or the social engine could give me a custom css code to change this, id be happy.

but personally description above looks messy, silly, and i have never in my life seen a website with the description above it.

**Comment by Elshara** [comment]
Actually I think the description field should be above the post editing area but below the post edit area title. This makes most sense.  Perhaps if we had a way to move title and description boxes around through a drag and drop interface it would make it much easier.
Also keep in mind that when accessing settings pages in admin menu, the title and description boxes there follow the same format as profile questions so they should be updated as well.

**Comment by poeticjustice** [comment]
sorry i disagree, and believe i am right

**Comment by shivani2910** [comment]
One of the points that is fixed in 4.9 (when it's released) is that we've displayed descriptions below form elements for profile fields.

**Comment by Elshara** [comment]
Awesome!
