### ISSUE TITLE
Profile numbers start from 10000 or random 5 digit number

### ISSUE THREAD

**Issue by poeticjustice** [SocialEngine/phpv4-issues#462]
Someone may know how to do this, but would be awesome to create a start user number or prefix to user id or user number.

personally, i want users to have unique numbers, but NOT from the start point of 1

selecting a start point from 10000 would be great
or random 5 digit numbers

if someone knows how to do this, id love to hear

**Comment by shivani2910** [comment]
Hi @poeticjustice thanks for contacting us.

If you want to set the auto increment value in `engine_users` table, you'll need to little customize the creation query for this table from file `/application/modules/User/settings/my.sql` before doing installation of SE PHP:

You can just replace this (for users table):

`ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_unicode_ci ;`

with

`ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_unicode_ci AUTO_INCREMENT=10000;`

Hope that helps!

Thanks & Regards,
Shivani

**Comment by poeticjustice** [comment]
Hiya, i nearly installed SE and created all my profile questions, and only accounts at this moment is the admins, i have no public members yet, is it ok to do this now, or does it HAVE to be prior to installation only?
