### ISSUE TITLE
upgrade spits error

### ISSUE THREAD

**Issue by SpiritWolfie** [SocialEngine/phpv4-issues#463]
I just tried to upgrade to the new se following the upgrade instructions to a letter, and was met with no entry key for Zend_db then after trying to go back to my admin panel my entire website was down with a 503 error and we had to restore our backup

The instructions my server tech followed was these - http://support.socialengine.com/php/customer/portal/articles/1666869-performing-upgrades

**Comment by poeticjustice** [comment]
Ive freshly installed SE on my server with 4.8.11, i will try the ugrade myself now and see if i get this issue and report back

**Comment by poeticjustice** [comment]
Upgraded myself and not had any 503 errors, have you tried again since restoring backup

**Comment by SpiritWolfie** [comment]
Well we didn't get the 503 right away, we got a no key entry Zend_db error then when we clicked 'admin panel' the entire site was down and we had no logs nothing on what happened, we did the instruction precisely how the instructions says and I have a professional server tech that has been dealing with servers for decades who did this for me.

**Comment by poeticjustice** [comment]
out of interest matey, what version did you upgrade from?

**Comment by SpiritWolfie** [comment]
Version 4.8.11

And we where not able to upgrade, the moment I tried to go back to our admin panel the entire site was completely broken and I had to restore our backup

**Comment by poeticjustice** [comment]
I had this once when upgrading to 4.8.11, but it was a hire experts or younet plugin that caused it

**Comment by SpiritWolfie** [comment]
well I told it to overwrite so plugins shouldn't have anything to do with it one would think? and if they do maybe SE should consider adding a ability for users to uninstall plugins fully? This is something I've spoken to plugin people about and they try to charge me just as much as the plugin itself cost to get it removed and refuse to tell me the steps to do it myself even know I have a server tech that would just need to know 'which' entry's to remove...

As far as I could see on what the update-updated, it didn't look like anything the plugins I have touches so it wouldn't make sense, Would disabling the plugins temporary be a work around or would they still cause interfarance due to the entry's the plugins created? (once again I looked over the list of the files being modified and I don't believe I saw one file my plugins touched, I could be wrong)

**Comment by poeticjustice** [comment]
far as i know, plugins dont ever overwrite core files, they are all seperate files that are for modules, that the modules link to core features.

there is a way of deleting files completely, but you have to do it in the mysql database 

http://support.socialengine.com/php/customer/en/portal/articles/2121821-how-to-remove-delete-a-plugin-from-your-website?b_id=4311

have you set up a staging server aka subdomain for dev

**Comment by SpiritWolfie** [comment]
the issue is the devs wont even tell me the entry's and theirs no point in doing a subdomain for a dev, if you try to move dev to live the whole engine breaks because for whatever reason Social engine makes it a point to tie everything into everything, including Domain names into the code strings.... Heck SE doesn't even release ID's correctly when they get deleted

So here's a question, I notice if I upload this update to package manager it puts a whole list of stuff in there, would it be safe to do the update in pieces?

**Comment by shivani2910** [comment]
@SpiritWolfie this issue was faced by some of our clients who upgraded SE PHP within few hours after the upgrade was released. Please email your site's Cpanel details along with site admin login details at support@socialengine.com and I'll fix this issue on your site:

Cpanel details:
URL:
Username:
Password: 

Thanks & Regards,
Shivani

**Comment by SpiritWolfie** [comment]
@shivani2910 I wont be charged for this will I?

**Comment by SpiritWolfie** [comment]
@shivani2910 I sent it to you, I'd like to not lose my color scheme service I paid for if possible.

**Comment by shivani2910** [comment]
@SpiritWolfie No, you'll not be charged for this. We can continue this discussion in the support ticket now.

Thanks & Regards,
Shivani
