### ISSUE TITLE
Minor language improvements

### ISSUE THREAD

**Issue by Tomislav20** [SocialEngine/phpv4-issues#464]
What are the steps to reproduce this issue?

There are 3 language errors that could be edited in less than 5minutes so all Socialengine users don't have mistakes in .csv files.
## What happens?

![wow se blog](https://cloud.githubusercontent.com/assets/12753666/16703814/feb3a82a-4570-11e6-9f2a-f1f515a1c82a.jpg)

![wow se classifieds](https://cloud.githubusercontent.com/assets/12753666/16703816/02649574-4571-11e6-93ac-fe1057c1ae42.jpg)

![wow se forum](https://cloud.githubusercontent.com/assets/12753666/16703822/0a08d8bc-4571-11e6-8292-d17bcd59533a.jpg)
## What were you expecting to happen?

In blog delete dare y on line 1
In classifieds insert ;"Delete Classified Category?" on line 158
in forum add "" around phrase Category on line 74

Any other comments?

Hoping to be repaired in next update.
## What versions of software are you using?

**Operating System:** All affected
**SocialEngine PHP Version:** 4.8.12

**Comment by shivani2910** [comment]
HI @Tomislav20,

Thanks for reporting this. We've noted down this issue at our end to our internal bug tracker and will get this fixed in the next release of SE PHP.

Thanks & Regards,
Shivani

**Comment by DonnaScriptTechs** [comment]
This is implemented for 4.9.0 when it is released.

**Comment by Elshara** [comment]
Awesome!
