### ISSUE TITLE
Upgrade Zend vers on SE website under resources

### ISSUE THREAD

**Issue by SpiritWolfie** [SocialEngine/phpv4-issues#467]
I just did a check on side by side View, Zend with the latest update is 4.8.10 but on the website under resources its still at 4.8.0 you may wish to update this info.

**Comment by Khushboo016** [comment]
Hi @SpiritWolfie , Please attach a screenshot here showing the location on the site where this issue is appearing, so we can resolve the same.

Thanks!

**Comment by SpiritWolfie** [comment]
on this page here at the very bottom under resources https://www.socialengine.com/client

The upgrade Zend is out of date. I'm positive on this as I did a Side by side with fresh install and the zand info itself says its a higher vers then what you have listed.

**Comment by smazurov** [comment]
that zend upgrade is only for the main zend framework - it has to be separate from others. Additionally, if you're on SE PHP v4.8+, you do not need to worry about it.

**Comment by alimoosavi15** [comment]
I can confirm this. Zend version is not showing correctly after 4.8.12 upgrade:
![manage socialengine](https://cloud.githubusercontent.com/assets/1803197/17069795/5b96271a-500d-11e6-865a-83f1c17f5945.png)

**Comment by SpiritWolfie** [comment]
@alimoosavi15 thank you...

but as per usual my github report is closed, I honestly don't know why I bother

**Comment by smazurov** [comment]
There is no issue here - 4.8.0 is the last time we've updated zend framework. Similar to other plugins that do not receive a version bump due to not being updated, zend framework follows that pattern.

**Comment by SpiritWolfie** [comment]
@smazurov I can dispute that quite easily, zend framework is not on 4.8.0, and I have checked, its like 4.8.10 is the current vers, this is stated in the zendframework code on a Diff check itself.....

So ether I'm not understanding something correctly or the info you may have is outdated?

**Comment by alimoosavi15** [comment]
@SpiritWolfie It wasn't clear enough where you're referring to. @smazurov is right. I thought current Zend version is greater than 4.8.0. There's no issue @SpiritWolfie .

**Comment by SpiritWolfie** [comment]
@alimoosavi15 it is greater then 4.8.0 Zend is on 4.8.10

heres some steps 

1) Install fresh copy of SE
2) grab the 4.8.0 resource for zend
3) go ahead and toss it into the package manager and start the process (Do not complete process)
4) the engine will complain about overwriting and offer a "Diff" check by clicking the (?) 

in one of the files you will see that it says Zendframework 4.8.10

**Comment by alimoosavi15** [comment]
4.8.10 is the latest version from Client Area:

![account dashboard socialengine community software](https://cloud.githubusercontent.com/assets/1803197/17070028/9e7fc6fc-500e-11e6-90c3-09a2672bc18f.png)

**Comment by SpiritWolfie** [comment]
@alimoosavi15 that screenshot you gave says from 4.x to --> to 4.8.0 That's the file I'm talking about, that spefic file is still vers 4.8.0 while Zend is technically 4.8.10 So because of I was thinking they should list the most updated one?

or is there something I'm missing here?

**Comment by alimoosavi15** [comment]
4.8.0 is the latest version.

**Comment by SpiritWolfie** [comment]
That's not what the File comments says it says 4.8.10, Let me get a screenshot.

**Comment by SpiritWolfie** [comment]
![image](https://cloud.githubusercontent.com/assets/9712738/17070359/4959b794-5010-11e6-86b6-557a20764459.png)
one pic here showing that it complains about differances

Pic 2 as you can see in picture 2 it clearly shows 4.8.10 in the difference check.
when Shay did my upgrade the Zend did not become 4.8.10
![image](https://cloud.githubusercontent.com/assets/9712738/17070382/6f6035bc-5010-11e6-96cd-6f784a182495.png)

**Comment by SpiritWolfie** [comment]
Please note, that the pics I took is from a Fully fresh install, not a Upgrade, when I check my main site (not my test site) and the person Shay (Something) upgraded it, these files still show 4.8.0 on my main site.

**Comment by smazurov** [comment]
Yeah, upon closer look we've actually updated zend framework package since 4.8.0, we shouldn't have, but it slipped through the cracks. We'll see if we can update that link to ensure those 2 minor changes get included in the package. You can simply replace libraries/Zend folder on your main site to get those fixes in the meantime.

**Comment by smazurov** [comment]
Since this not actually related to SE PHP, the software, i'll keep this issue closed. In the future, try to let us know via support@socialengine.com or community.onsocialengine.com about issues similar to this one.

**Comment by SpiritWolfie** [comment]
@smazurov 

Could I get a updated zend so I can apply it to may main site then please?

And could you please pitch in your voice on my opting out of activity feeds, I think the other person isn't understanding what I'm trying to say, Thanks!

**Comment by smazurov** [comment]
Grab full version zip, and copy over `application/libraries/Zend` folder.

**Comment by SpiritWolfie** [comment]
may want to also update the info on the package info on the SE website too to state 4.8.10 just so the info is clear...

**Comment by smazurov** [comment]
This is now addressed.

**Comment by Elshara** [comment]
Good.
