### ISSUE TITLE
widget/index Security bug MAJOR ISSUE

### ISSUE THREAD

**Issue by SpiritWolfie** [SocialEngine/phpv4-issues#469]
All of my stuff is set to disallow public viewing, -everything- I have double/tripled checked my settings yet

/widget/index allows you to view someones SE Site whether it set to private or not... 

if theirs anything I can do right now on my end to resolve this matter please let me know.

**Comment by Khushboo016** [comment]
Hi @SpiritWolfie , it would be great if you can explain this issue in a bit more detail that how this file /widget/index is breaking the privacy of your site. You may take reference of your site to explain the issue.

Thanks!

**Comment by SpiritWolfie** [comment]
http://www.furgather.net/widget/index/content_id/751

This allows you to the see the website even when all the settings are set to private, you can watch the feed happen etc, (We blocked this url because this is a BIG ISSUE for our website) but thats the kind of url that will let anyone watch your website even if its set to private on -everything-

**Comment by SpiritWolfie** [comment]
@Khushboo016 @smazurov  any news on this?

**Comment by smazurov** [comment]
https://demo.socialengine.com/widget/index is not a valid page. Can you give steps on how to take a vanilla installation of SE PHP and enable functionality you're having issues with?

**Comment by SpiritWolfie** [comment]
@smazurov 

Honestly I don't much about this issue as some other social engine site owner brought it to my attention and we had to block that part. I wouldn't even know where to begin on how to track this specif issue down, I just know if I unblock this page it shows the entire feed even know all my settings are strictly set to private and not allow 'global' users to access anything on the site.

**Comment by Elshara** [comment]
Try changing security permissions for the folder. I know the fix may be hacked using .htaccess settings. As of now the page is a 403 forbidden error so I wouldn't worry about it too much.
