### ISSUE TITLE
Sign Up Redirect

### ISSUE THREAD

**Issue by BikersPost** [SocialEngine/phpv4-issues#47]
If an existing member is on let say a forum page but not logged in and they sign in it will redirect them to the same page they where on. but if your a new member and sign up it will redirect you to the main page. It would be great if on sign up it could redirect them to the same page also. considering the are probably joining to take part in the discussion or looking to leave a comment.

**Comment by Anshuse** [comment]
Helllo @BikersPost ,

We've noted down your suggestion in our internal suggestion tracker for our development team to have discussion over this.

Best Regards,
Anshu

**Comment by Elshara** [comment]
This is confirmed.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#2

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
