### ISSUE TITLE
Blogs Insert Video Fails

### ISSUE THREAD

**Issue by TravisHollister** [SocialEngine/phpv4-issues#470]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. Go to Blog > Write New Entry
2. Click Insert/Edit video on the tool bar
3. Type video source URL in Source box
4. Type poster source URL in Poster box
5. Define Dimensions (512 x 288)
6. Click OK
7. Click Preview on the toolbar > Everything looks great!
8. Click Post Entry or Save
9. Video disappears, no video code as defined above is in the source code; it's stripped out
s…

What happens?
When the Blog post does not have the video that was inserted into it

What were you expecting to happen?
----------------------------------
I expected the Blog post to appear just as it did in preview

Any logs, error output, etc?
----------------------------
I believe this is the relevant error message:
```
2016-07-25T01:15:51+00:00 NOTICE (5): [8] Array to string conversion (/home/buttswap/public_html/application/libraries/Engine/View/Helper/HtmlLink.php) [51]
Error Code: cbd6e6
Stack trace:
#0 (unknown file)(0): Engine_View_Helper_HtmlLink->htmlLink('/blogs/1/3/seven-ways-the-gay-co...', Array)
#1 /home/buttswap/public_html/application/libraries/Zend/View/Abstract.php(350): call_user_func_array(Array, Array)
#2 /home/buttswap/public_html/application/modules/Blog/views/scripts/admin-manage/index.tpl(85): Zend_View_Abstract->__call('htmlLink', Array)
#3 /home/buttswap/public_html/application/modules/Blog/views/scripts/admin-manage/index.tpl(85): Zend_View->htmlLink('/blogs/1/3/seven-ways-the-gay-co...', Array)
#4 /home/buttswap/public_html/application/libraries/Zend/View.php(108): include('/home/buttswap/public_html/appli...')
#5 /home/buttswap/public_html/application/libraries/Zend/View/Abstract.php(890): Zend_View->_run('/home/buttswap/public_html/appli...')
#6 /home/buttswap/public_html/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(900): Zend_View_Abstract->render('admin-manage/index.tpl')
#7 /home/buttswap/public_html/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(921): Zend_Controller_Action_Helper_ViewRenderer->renderScript('admin-manage/index.tpl', )
#8 /home/buttswap/public_html/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(960): Zend_Controller_Action_Helper_ViewRenderer->render()
#9 /home/buttswap/public_html/application/libraries/Zend/Controller/Action/HelperBroker.php(277): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#10 /home/buttswap/public_html/application/libraries/Zend/Controller/Action.php(527): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#11 /home/buttswap/public_html/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('indexAction')
#12 /home/buttswap/public_html/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Zend_Controller_Request_Http, Zend_Controller_Response_Http)
#13 /home/buttswap/public_html/application/modules/Core/Bootstrap.php(84): Zend_Controller_Front->dispatch()
#14 /home/buttswap/public_html/application/libraries/Engine/Application.php(160): Core_Bootstrap->run()
#15 /home/buttswap/public_html/application/index.php(214): Engine_Application->run()
#16 /home/buttswap/public_html/index.php(24): include('/home/buttswap/public_html/appli...')
#17 {main}
```

Any other comments?
-------------------
NONE

What versions of software are you using?
----------------------------------------
Windows 10

**SocialEngine PHP Version:** 
Version 4.8.11

**Comment by Khushboo016** [comment]
Hi @TravisHollister , Please make sure that while inserting a video using the button "Insert/edit video" on the toolbar in blogs or any other module which allows this functionality, you have allowed all the tags that are used in the source code (you can view the source code by clicking on the Source code button present on the toolbar) defined to attach that video to your post in the list of HTML tags allowed for that module. It needs to list all those HTML tags in the list of allowed HTML tags from the Member Level Settings of that particular module. 

While posting URL links of the videos of websites like vimeo, youtube etc. which are mainly video based websites, "iframe" tag is used in the source code to attach the videos which is by default added in the list of allowed HTML tags of Blogs along with other modules. So, the links of videos on youtube and vimeo should work fine without adding any additional tag, but if you are adding direct storage links/URLs of videos e.g. if you are adding a link of a video uploaded via "File & Media Manager" section then there is not "iframe" tag used in the source code to attach these videos and some other tags like "video", "source" etc. are used, so these tags need to be added in the list of allowed HTML tags.

Thanks!

**Comment by TravisHollister** [comment]
Thanks for your prompt response. I thought I had added the necessary tags to the module, but I'll go back again and double-check.

**Comment by TravisHollister** [comment]
Nope, that didn't work either. I downloaded a list of 115 tags and added them to the allowed tag list in the blogs module I made sure the default and super admin levels were given the tags. I tried several different videos to insert into the blog. Each time I saved the blog, the video code was stripped out. Then I tried just embedding a YouTube video using the source code view and that code was stripped out too.

In preview mode everything works great, but once I save it, the code is removed. Here is the YouTube code I used as an experiment: 

<iframe width="560" height="315" src="https://www.youtube.com/embed/pPEhhmNQevs" frameborder="0" allowfullscreen></iframe>

This is the list of tags I added to the allowed tags list:

a, abbr, acronym, address, applet, area, article, aside, audio, b, base, basefont, bdi, bdo, big, blockquote, body, br, button, canvas, caption, center, cite, code, col, colgroup, datalist, dd, del, details, dfn, dialog, dir, div, dl, dt, em, embed, fieldset, figcaption, figure, font, footer, form, frame, frameset, head, header, hr, html, i, iframe, img, input, ins, kbd, keygen, label, legend, li, link, main, map, mark, menu, menuitem, meta, meter, nav, noframes, noscript, object, ol, optgroup, option, output, p, param, pre, progress, q, rp, rt, ruby, s, samp, script, section, select, small, source, span, strike, strong, style, sub, summary, sup, table, tbody, td, textarea, tfoot, th, thead, time, title, tr, track, tt, u, ul, var, video, wbr, h1, h2, h3, h4, h5, h6

**Comment by TravisHollister** [comment]
Is anyone for SE going to respond to this? I'm not sure what to expect as this is my first time using github.

**Comment by TravisHollister** [comment]
Knock, knock...Hello. Do I have to go to Facebook to get someone's attention?

**Comment by shivani2910** [comment]
Hi @TravisHollister,

Sorry for the delay in responding to you. Our team was actually looking into the issue at our end and missed sending an acknowledgement to you.

Regarding the problem mentioned by you, I understand what you're saying but after we enabled `video` and `source`  tags for all the member levels (who should be able to create blogs with videos site), video code was getting saved properly in blog post and it appeared like this in TinyMCE editor when I clicked to viewsouirce code:

```html
<p><video width="300" height="150" controls="controls">
<source src="http://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_1mb.mp4" type="video/mp4" />
</video></p>
```
But after we saved settings, we faced another issue - only an image of that video was being displayed on video page like this:

![blog_view](https://cloud.githubusercontent.com/assets/7815961/17432378/7be52c7c-5b1c-11e6-9c5e-008bdd6bceef.png)

Solution for this issue has been figured out and posted below. We'll also do this change in our core files so that you may not face this issue again in future after upgrading SE on your site.

- Open file `/application/modules/Blog/Form/Create.php`
- Search for below code:
```php
new Engine_Filter_Html(array('AllowedTags'=>$allowed_html))),
```
and replace it with below code:
```php
new Engine_Filter_Html(array('AllowedTags'=>$allowed_html, 'AllowedAttributes' => array('controls', 'autoplay')))),
```

So, I suggest you to please:

1) First make sure that you've enabled these tags: `video` and `source` for all member levels (you can do it by selecting each member level one by one from Admin > Plugins > Blogs > Member Level Settings section  and then saving these tags for each level and save settings).

2) Follow above provided steps to do that code level change on your site.

I hope your issue will be resolved after doing these things. If you still face any problem, please share your website's details with us by sending over an email at support@socialengine.com and we'll get back to you quick.

Thanks & Regards,
Shivani

**Comment by TravisHollister** [comment]
Shivani,
Thanks a lot! This got it working.

**Comment by Elshara** [comment]
Don't put custom embed code in for videos either as it will break on blog upload.

**Comment by zamanmukhtar66** [comment]
If you want to download any video on you tube or any other site visit this site for download video www.downlody.com

**Comment by Elshara** [comment]
Thanks. I notice a bunch of youtube videos getting removed right after
upload so this would be good for music.
