### ISSUE TITLE
Zend Framework security updates

### ISSUE THREAD

**Issue by eugene-wh** [SocialEngine/phpv4-issues#471]
SE PHP 4.8.12 uses Zend Framework 1.12.3

The most recent Zend Framework version is 1.12.20

There were numerous security updates since version SE uses, for example
https://framework.zend.com/changelog/1.12.19
https://framework.zend.com/changelog/1.12.16
https://framework.zend.com/changelog/1.12.12

It's really important to update SE so it will use the most recent version of Zend Framework 1 as there are potential security vulnerabilities.

**Comment by Elshara** [comment]
Good idea to report this! I suspected for a long time Zend was never a major concern in security fixes for Social Engine.

**Comment by SpiritWolfie** [comment]
I've also checked this and can confirm, and I'd also like to point out zend framework is out of the 1 versions and on 3 now as shown on  - https://framework.zend.com/blog/2016-06-28-zend-framework-3.html

**Comment by Elshara** [comment]
This if changed might even speed SE up a ton.

**Comment by eugene-wh** [comment]
Migration for ZF2 or ZF3 is definitely a must, but ZF1 upgrade isn't a complex thing. It was already done in past - I do remember reporting a similar issue in past.

**Comment by Elshara** [comment]
I'm kind of surprised this isn't a priority especially because they
rely on this framework rather than making their own.

**Comment by eugene-wh** [comment]
@smazurov Stepan, I've reported possible security issues and it's been 3 weeks already and there is still no reply or feedback.

**Comment by Elshara** [comment]
I don't know what thread it was but someone reported the zend
framework was updated in 4.8.12. There are actually a few of them
flying about lately on this git hub forum.

**Comment by RaymondBenc** [comment]
We've updated Zend to 1.12.20 and currently running QA to make sure everything is in order. The milestone for this is currently set at 4.9.

**Comment by Elshara** [comment]
This is awesome news. Welcome to social engine from phpfox btw.

**Comment by DonnaScriptTechs** [comment]
This is updated to latest zf1.12.20 for our 4.9 once it releases.

**Comment by Elshara** [comment]
Awesome!
