### ISSUE TITLE
Votes Don't Show In Activity Feed

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#473]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Create a poll.
2. … Vote on the poll.
3. … Like the poll.

What happens?
-------------
… Only the fact that the poll gets created shows up in the activity feed. The comment feed entry is blank, when the comments show up if you commented on the poll. Vote activity doesn't show in the feed.

What were you expecting to happen?
----------------------------------
… Instead of where the option to vote appears only in the created a feed story item, the option to comment, change vote or like should appear when ever the feed item itself gets reposted or repopulated if other members interact with the poll or other content type such as music involving plays, groups involving membership etc.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… This would make polls more popular.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10

**SocialEngine PHP Version:** … 4.8.12

**Comment by Khushboo016** [comment]
Hi @Elshara , we've added your suggestion at our end for internal team discussion.

Thanks!
