### ISSUE TITLE
Dashes In Profile Questions

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#475]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)
## What are the steps to reproduce this issue?
1. … Create a profile.
2. … View your profile.
3. … Look under profile fields for your information.
## What happens?

… Dashes appear quite at random making it hard to identify what someone is saying. It happens in between words and so copying links for example don't work via highlight. But if you go to edit your profile information, the dashes don't appear.
## What were you expecting to happen?

… No dashes be present when viewing member profiles.
## Any logs, error output, etc?

(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```
## Any other comments?

… The dash character f­or some reason cannot be copied here t­o show you s­o I'm ad­ding i­t a­t rando­m.
## What versions of software are you using?

**Operating System:** … Windows 10 latest Firefox Version

**SocialEngine PHP Version:** … 4.8.12

**Comment by Khushboo016** [comment]
Hi @Elshara , Please attach a screenshot showing the issue, so we can guide better.

Thanks!

**Comment by Elshara** [comment]
Here's some more information about the issue.
When you create a text or multi line text area for profile
information, when viewing the profile, dashes appear in those specific
fields.

**Comment by Khushboo016** [comment]
Hi @Elshara , Please attach a screenshot here showing the random dashes which you are referring here, so that we can address the exact issue and can resolve the same.

Thanks!

**Comment by Elshara** [comment]
Screenshot won't work in this case because the dashes show up as an
invisible character for some reason. But they exist but only on the
profile questions page if someone writes in a multiple line text area
and is viewing a profile with text posted there.

**Comment by Khushboo016** [comment]
Hi @Elshara , I've checked this issue on my localhost, but I did not observe any random dashes in between the text when I copied it from Profile Info section and pasted the same in text editor `Gedit`. Below are the screenshots showing how the text looks in the Profile Info section and how it looks when pasted in a text editor: 

![profile_information](https://cloud.githubusercontent.com/assets/18209340/17735741/9fcacfb4-64a1-11e6-9962-3c108ee4d628.png)

![editor-gedit](https://cloud.githubusercontent.com/assets/18209340/17735786/d1b8cde6-64a1-11e6-92bf-faa90424a3fb.png)

So, please help us in reproducing the same issue at our end.

Thanks!

**Comment by Elshara** [comment]
A part of the problem is in this file.
/application/modules/Fields/View/Helper/FieldTextarea.php
The multiple line text area references chunks of text cut off by the
same character that is appearing in profile questions if someone
writes a piece of text longer than the cut off limit. The cut off
limit shouldn't be there at all. But that isn't the only place where
the cut off dash issue appears, as it also appears in the
FieldText.php file in the same folder. Unfortunately, I haven't
figured out where the code is to stop this from happening. It is those
two fields the single line and multiple line text area that causes the
dashes to be viewed if pasted such as when people add links, the links
won't copy properly.

**Comment by Khushboo016** [comment]
Hi @Elshara , It would be great if you can show us the dashes that appears, as we are not able to reproduce this issue at our end even after adding a long URL into a multi-line text input field as shown below:

![long_url](https://cloud.githubusercontent.com/assets/18209340/17854213/a3b91310-688e-11e6-942c-c6510f5402ae.png)

![no_random_dashes1](https://cloud.githubusercontent.com/assets/18209340/17854312/47f7ba1c-688f-11e6-94db-21449b1155dd.png)

So, please provide us the exact steps to reproduce this issue at our end.

Thanks!

**Comment by Elshara** [comment]
You know exactly what I'm talking about. Stop the run around game and
the canned responses because you were able to reproduce the exact same
issue in this thread.
https://github.com/SocialEngine/phpv4-issues/issues/468
I posted this independently of that report only after I posted it did
I see it was there. This means either my explanation isn't good enough
or you're trying to confirm the exact same steps I took to have the
same issue appear. It's been said in different wording a lot in this
thread and in the other.
So let me walk you through it once more.
Go to profile questions.
Create a new question.
Call it whatever say Websites I'm On for example.
Make it a multiple line text field.
Save the profile question.
Go to site settings.
Click on performance cache.
Click clear cache.
Go to edit my profile on your own profile or home page.
Fill in the question.
Save changes.
Go to your profile page.
Scroll down to where you'd paste in the link.
Try to click on it.
Try copying it in your browsers address bar.
Try pasting it in a text editor as plain text.
If you're telling me you don't see dashes then it means only some
installations of SE do. That means it wouldn't hurt to update the
installation package or right here on git hub before a major version
is released that a particular issue has been fixed and it wouldn't
hurt to run the upgrade package to fix the issue if it is something
bothering a social engine admin.
Notifications of whether or not an issue is fixed or is in progress
would help  lot to bring communication forward even if it is just to
the creator of that issue so that we aren't sitting here hanging
trying to say the same thing in different independent research, only
to find some people get heard, not others.
Please correct me if I'm misunderstood in my thinking.

**Comment by Elshara** [comment]
Here's another screen shot.

**Comment by Khushboo016** [comment]
Hi @Elshara , 
Regarding "you were able to reproduce the exact same issue in this thread #468":
In the thread https://github.com/SocialEngine/phpv4-issues/issues/468, I confirmed that I was able to reproduce the issue that the links that get created are not clickable but I was never been able to see any random dashes when copied those links to any text editor. 

Regarding "If you're telling me you don't see dashes then it means only some installations of SE do":
If this issue is appearing in your installation then please just attach a screenshot showing the random dashes that appear on pasting the link in a text editor similar to the screenshot that I have attached of the text-editor `gedit` in which no random dashes are there in the link I pasted. 

Thanks!

**Comment by Elshara** [comment]
Did you not see the screenshot I attached after I responded?
I will attach a new one if you can't see it. I think I uploaded one a few times.
Yes links aren't clickable either.
But the dashes are there.

**Comment by Khushboo016** [comment]
Hi @Elshara , It seems that the screenshot was not attached successfully, so please attach it again.

Thanks!

**Comment by Elshara** [comment]
Here is the screenshot.

**Comment by Khushboo016** [comment]
Hi @Elshara , There is no screenshot attached in your reply.

**Comment by Elshara** [comment]
I attached it via email and it shows up for me when I view the email thread.

**Comment by eugene-wh** [comment]
@Elshara I don't see the screenshot either (sorry for breaking into the thread)

**Comment by Elshara** [comment]
That's okay. It's an issue with Github not posting the screenshots via
email. I don't know why it's not posting it. I'll try and post it from
the web, maybe that will work.

**Comment by Elshara** [comment]
![2016-08-26](https://cloud.githubusercontent.com/assets/12810222/18058364/d65b7ac6-6dc8-11e6-977d-b1182d224fa0.png)

**Comment by Elshara** [comment]
That is the latest photo I took.

**Comment by Khushboo016** [comment]
Hi @Elshara , I'm not able to figure out any random dashes in the screenshot you've attached. Please highlight or mark them in the screenshot if you can see any.

Thanks!

**Comment by SpiritWolfie** [comment]
@Khushboo016 

They do appear in notepad, but it takes some work to get it to appear, and I have confirmed this myself personally, I think what some of us need to start doing is getting together and making a list of problems and getting video recordings of our screen on how we go about getting these results ,that way you can watch a video on how to reproduce it, and then any missing details can be explained. (Such as I used Ctrl+C or highlighted and right clicked and copyied for example, but I can confirm that there are invisable dashes and I have reported this with Screenshots in the past, its in one of my closed bug reports I believe? if you want to see the screenshots of it in action. 

I also confirmed this issue on your demo site as well

**Comment by Elshara** [comment]
It'll probably never get fixed if it  can't be reproduced.

**Comment by SpiritWolfie** [comment]
@Elshara 

The issue is and I don't want to sound disrespectful but I'm going to bluntly say it

some of these people have no clue how to actually test this stuff, so they try 1-2 things and call it 'attempting to reproduce' and mark it as unreproduceable when I can sit here and consistently reproduce the problem repeatedly over and over on more then 3 computers, (Even on a freshly installed SE/ freshly installed computer, etc' 

and that's why this becomes a issue, if you have User A trying to reproduce this stuff but doesn't think outside the box and willing to try things a few different ways then the 'norm/standard way' things will never be found or figured out, This is still a issue even currently and I can still 'easily' reproduce this problem in both urls and simply copying and pasting links from the activity feed on both a plugin version of SE and a none...Here's the previous thing I got into a heated argument with them about 
https://github.com/SocialEngine/phpv4-issues/issues/419 this is completly related to this thread and the one you referenced of mine (With urls) it's all tied into each other as this problem is global and not just specif.

**Comment by Elshara** [comment]
Just paste the text into note pad and then load up a text to speech
program and see if it reads the words incorrectly. Problem duplicated.

**Comment by DonnaScriptTechs** [comment]
I can reproduce this issue and have a screenshot of it by using Beyond Compare, one of my favorite programs. 

1. Get a Youtube link.
2. Enter that in a multi-line profile question.
3. View your profile and copy the link.
4. Put the link on the left in the Beyond Compare Screen.
5. Put the original Youtube link in the right of the Beyond Compare Screen.

You will see the following:
`https://ww­-w.youtube.­-com/watch?­-v=43EBrXYj-­OVc`

<img width="965" alt="link bug profile" src="https://cloud.githubusercontent.com/assets/6908282/26000598/9346308e-36f7-11e7-8422-1e1da7e476c5.png">

I'm going to add this as a separate bug report to see if we can do anything for this as it stops accessibility readers from properly reading the links and so those with sight impairments will not be able to use the fields.

**Comment by DonnaScriptTechs** [comment]
I will note that even setting the profile question to use "Show on member profiles with links" doesn't work. I'm adding this report to the one we have open for that as the fix needs to encompass this situation.

**Comment by DonnaScriptTechs** [comment]
Marked enhancement as it is working as designed but we need to improve it for our next release (after 4.9.2) .

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#26

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
