### ISSUE TITLE
Does anyone know how to href current user for a html link

### ISSUE THREAD

**Issue by poeticjustice** [SocialEngine/phpv4-issues#476]
im making a a dashboard for users, so areas are clear
example for messages, settings etc

i want to also have button saying "view profile"
but how can i href this link so it pulls in users id?

any ideas?

@smazurov any ideas matey

examples i have tried

href the whole link upto /profile and adding php echo $engine4_users->user_id; etc

<a href="http://domain.com/profile/<?php echo $engine4_users->user_id; ?>"
$engine4_users->user_id; ?>"

**Comment by poeticjustice** [comment]
Hiya 

I tried this to make a button, but still not working

<?php
    $viewer = Engine_Api::_()->user()->getViewer();
?>
 
<a href="profile/<?php echo Engine_Api::_()->user()->getViewer()->user_id; ?>;">View Profile</a>

ANy ideas @smazurov or any other SE team

just want to make my own button link for all members that goes to that users pofile

**Comment by smazurov** [comment]
Hey, correct place for these types of questions is [stackoverflow](http://stackoverflow.com/questions/tagged/socialengine)

**Comment by Elshara** [comment]
Isn't possible in SE. Core framework doesn't support single url for profile.

**Comment by poeticjustice** [comment]
thanks @Elshara paid someone to make me a widget now

**Comment by Elshara** [comment]
Awesome! Was it expensive? I was actually looking for the
functionality to show content to signed in members only.

**Comment by poeticjustice** [comment]
cost me $25 @Elshara

**Comment by Elshara** [comment]
Awesome! I'm interested in getting in touch.
