### ISSUE TITLE
social engine 4.8.12 not sending welcome emails

### ISSUE THREAD

**Issue by poeticjustice** [SocialEngine/phpv4-issues#479]
Hi All

need serious help, as about to launch site, and discovered the only email that doesnt send, is the welcome email, for upon signup

@smazurov hope you can help

**Comment by Khushboo016** [comment]
Hi @poeticjustice , This is not a known issue and we have not received similar queries from other clients, so, it seems to be related to your specific installation. So, we suggest you to follow this KB article http://support.socialengine.com/php/customer/en/portal/articles/1643190-basic-email-troubleshooting?b_id=4311 to troubleshoot this email issue on your site. And if you still face the issue after following the article, then you are suggested to open a support ticket for the same at https://www.socialengine.com/client/ticket/create or you can send us an email to us at support@socialengine.com.

Thanks!

**Comment by Elshara** [comment]
Yes welcome emails work fine on this end. Sorry but it's something to do with the email provider you have for your server host.
