### ISSUE TITLE
Comments And Replies Need An Edit Button For Creators And Administrators

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#481]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Make a post.
2. … Comment on an existing post.
3. … View the comment you made.

What happens?
-------------
… You aren't faced with the option to edit the comment you made. If you are an administrator, you cannot edit comments at all.

What were you expecting to happen?
----------------------------------
… To be able to be able to edit comments and replies and to be able to like replies.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Settings for the comments and replies module should be available either from the widget where it is displayed or from the core settings area to be able to control and approve comments like you can posts.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10

**SocialEngine PHP Version:** … 4.8.12

**Comment by Khushboo016** [comment]
Hi @Elshara , You can refer to the Advanced Comments based Plugin developed by our top rated third party developers, this plugin allows to have this feature on a SE site.

Thanks!

**Comment by Elshara** [comment]
I don't want all the bloatware such plugins provide, voting and such.
Just the ability to edit comments from within the core comments
plugin. If I can edit posts, I should be able to edit post replies.
Comments on every other social site platform have this functionality,
including Facebook. I'm not asking for much or the ability to even
reply to comments or any of the other bloatware, just the ability to
edit comments.

**Comment by Elshara** [comment]
Fine I get the picture. If you had to recommend someone for this
ability and who is good at it with few bug reports, who would you
choose? There's a few providers who offer this. It should be something
the core package supports as a small but very useful tweak. I guess
social cms priorities aren't that developed in social engine. I don't
like having to use many third party plugins to get the job done the
core package in terms of functionality would be most useful at doing.
It ads extra load on the servers already very slow performance because
of how many external scripts have to load all at once just to open up
a page on a social engine site. I don't mean to nag.

**Comment by eugene-wh** [comment]
@Elshara we have plugin called Nested Comments. It can be used to replace standard comments feed with threaded comments (depth is configurable, so you can turn threading off). There is a function to edit comment present (in addition to more accurate loading of lots of comments and voting).

Note, that the main news feed comments won't be affected in this case (as it's impossible to easily replace comments there with the same widget).

I recommend to check it - possibly it's something that will ft your needs http://webhive.com.ua/store/product.php?id_product=74

If you will like it - contact me directly I'll arrange a discount for you.

**Comment by Elshara** [comment]
I'll definitely check that out! Thanks bro! I'll contact you shortly.
