### ISSUE TITLE
Create Custom Dynamic Profile URL

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#482]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)
## What are the steps to reproduce this issue?
1. … Go to menu editor.
2. … Create new menu.
3. … Add new item.
## What happens?

… You are unable to create a dynamic profile link if you wanted the current viewing members profile link to be displayed.
## What were you expecting to happen?

… To be able to go to your site URL slash profiles or your site URL slash profile to automatically redirect you to your own profile.
## Any logs, error output, etc?

(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```
## Any other comments?

… Creating a dynamic profile address will give you the option of creating a custom menu for signed in visitors instead of having to use the structure and style of the over complicated mini menu because you are unable to position the updates item and the search bar to where you want it. As a matter of fact, all menus should just be under a menus widget, rename it from generic menu and delete the other types of menus available but keep the option to edit the global menu structure where ever an instance of the generic menu widget is displayed by the name of the menu in menu editor. The more widgets you add to a page, especially the mini menu, the more it slows the site down. Just removing the mini menu makes the site run a lot faster.
## What versions of software are you using?

**Operating System:** … Windows 10

**SocialEngine PHP Version:** … 4.8.12

**Comment by Khushboo016** [comment]
Hi @Elshara , Currently there can only be created menus with static links, if you need to have menus with dynamic links, you need to customization at your end. We do not have plans now to make menus work for dynamic links. 

Thanks!

**Comment by Elshara** [comment]
Explains why i didn't vote this year for any cMS awards.
