### ISSUE TITLE
Menu Editor Doesn't Allow You To Manage Module Menus

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#483]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)
## What are the steps to reproduce this issue?
1. … Go to menu editor.
2. … Browse for a global menu, blog browse, footer, main, etc.
3. … Try to delete an item, or click on edit and look for where the address URL field should be.
## What happens?

… It doesn't exist. You aren't currently able to edit the structure of a menu. You cannot see its relative path URL either like you can with custom menu items. You also aren't able to delete a core menu item.
## What were you expecting to happen?

… To have core menu items function the same as custom menu items.
## Any logs, error output, etc?

(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```
## Any other comments?

… Having this functionality would make creating custom menus more of an easier task so people can if you set it up right, access something in a more professional manner instead of having to scroll over duplicate content such as browse and quick menus for most modules to view the module index page. Or as in the case of blogs, have the main content only take up part of the screen because of how the content in the very bloated blog gutter modules is displayed. And in the case of forums, not have the option to edit any content of the page at all. Compared to how you are able to edit it relatively in other modules such as videos.
## What versions of software are you using?

**Operating System:** … Windows 10

**SocialEngine PHP Version:** … 4.8.12

**Comment by Khushboo016** [comment]
Hi @Elshara , We have added your suggestions at our end for internal team discussion.

Thanks!

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#27

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
