### ISSUE TITLE
Sign In History Has Problems Displaying Member Information

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#484]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Go to control panel.
2. … Go to settings - spam ban tools.
3. … Go to login history.

What happens?
-------------
… Information isn't displayed by date. It is random and some information doesn't get recorded in the database correctly at all. For example, some recent sign in information gets recorded as v3 migration. While others gets recorded as wrong password when it was a successful sign in.

What were you expecting to happen?
----------------------------------
… Sign in information to be better displayed. Login history to record if a member has left the site, or cancelled their account.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… It's a useful tool if and when it works correctly.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10

**SocialEngine PHP Version:** … 4.8.12

**Comment by Khushboo016** [comment]
Hi @Elshara , The Login History is displayed along with the time-stamp and by default the recent logins are shown at top and then less recent logins are shown and so on in a sorted fashion. And the history can be sorted by clicking on the heading of the columns present to sort the history based on that column. 

Thanks!

**Comment by Elshara** [comment]
Basically the columns don't update as they should for more active
social sites with a lot of sign in information.

**Comment by Khushboo016** [comment]
Hi @Elshara , the login history is working fine at our end and the columns update properly, so if login history is not updating properly in your installation, then you can open a support ticket for this issue at https://www.socialengine.com/client/ticket/create or you can also email us at support@socialengine.com along with the details of your site.

Thanks!

**Comment by Elshara** [comment]
Thanks for checking it on your end. Will do if the problem persists.
