### ISSUE TITLE
Page Display Improvements For Information

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#485]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)
## What are the steps to reproduce this issue?
1. … Go to layout editor.
2. … Go to a module page.
3. … Go to edit info.
## What happens?

… Module pages display a blank URL field. If you write something in the field, the site breaks when viewing the page. Module pages do not show a warning if you accidentally delete it, you cannot recover the page. Module pages do not allow you to know what modules are supported on the page so if you add something like content module to a page that doesn't support it, you don't know it won't display unless you view the page to find out what is not displayed. Pages that belong to other modules that get uninstalled keep their ID in the database so missing module layout and header information is saved if you try to add a new blank page or a new page that is a duplicate of an existing page, instead of removing the page completely from the database itself.
## What were you expecting to happen?

… Module pages to show a URL field if the URL can be changed without the site breaking when viewing the page, or to not show a URL if the URL cannot be changed for that page. Module pages to warn you that deleting this page will cause the module to not function correctly, or removing the delete option for pages connected to a database or site module. The ability for custom pages to have direct absolute URLs with slash support, so instead of slash pages slash my content link, it could be domain slash direct content link, or domain slash module slash direct content link. For pages to list supported and unsupported modules under available modules you can add to the page. When adding new modules, for its edit box to open automatically when adding it for the first time as a new instance from the available modules area like the HTML box does. For new pages to optionally be added to a menu under a connect to menu area so that all pages of the site listed as a menu item are also linked through the layout editor.
## Any logs, error output, etc?

(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```
## Any other comments?

… Page support could be improved in areas where it is officially under development through social engine modules. Pages and menus relating to the admin control panel and package manager should also be added as reference points to edit if it would make it easier for a specific website to have better administration access. It would also be nice to have a page pop up for both admins viewing the front end and back end of what ever content they are viewing to have a manage menu be available for all content types as a part of the core package. This way no matter what the module is, you can easily manage its content via a unified interface because of how it connects to fields in the database.
## What versions of software are you using?

**Operating System:** … Windows 10

**SocialEngine PHP Version:** … 4.8.12

**Comment by Khushboo016** [comment]
Hi @Elshara , There is a confusion, the core pages cannot be deleted from the Layout Editor section, only custom pages can be deleted, so there are no chances of deletion of core pages accidentally. But yes, there should be then no option of delete provided for those pages that is we should not show or should remove the option to delete core pages. We've noted down this at our end and will try to implement in future versions. And if core pages can never be deleted so can always be used for creating new pages by duplicating these.   

Thank you for your other suggestions regarding page display improvement, we have added these at our end for internal team discussion.

Thanks!

**Comment by shivani2910** [comment]
It's fixed in 4.9 when it's released.

**Comment by Elshara** [comment]
Awesome!
