### ISSUE TITLE
Multi select browse members

### ISSUE THREAD

**Issue by poeticjustice** [SocialEngine/phpv4-issues#488]
Hi SE

I have a query if its possible to do.
It seems bad that it cant be done anyhow

When browsing members, and narrowing search type

example
skin colour
white, black, asian, native american, middle eastern etc
It makes sense on sign up, users can only choose one of these options.
But its annoying in browse members, for example if it was a dating site,
If a user only likes black or asians, they would have to re-search, because they can only choose one option, only when the question becomes multiselect, can a user select black and asian, but that also means on signup, a white person could select white, black, asian..... why would they do this? because some people may accidentally select.

another example hair length
a user will have a specific hair length, they wont be short hair and long unless wearing a wig
but if a user wants to search people with shoulder length hair and long hair
then again they have to do 2 separate searches.
because when you give users initial option of multi-select on signup, they will just tick everything, to become more searchable.

Point is browse members should have more options and control.

even if tags were introduced, so if browsing you select long hair, and short hair, the search shows tags of the fields searching based on selection

@smazurov

**Comment by poeticjustice** [comment]
id like to re expand on this

within signup questions, i have for example

Hair type 
option 1- bald
option 2- short
option 3- mid length
option 4- long

the above is a single select option, as their answer can only be one of the 4 mentioned.

But within browse members, is there a way to allow multiselect on single select answers.

as admin when i search for example, id like to search people who are bald and have long hair.
but due to being single select question/answers, you have to search one at a time

so just wondering if there is a way to enable multiselect for single select questions, only on the browse members section

**Comment by poeticjustice** [comment]
@smazurov @jamesoclark @alimoosavi15 @Danno040  @scrutinizer-auto-fixer @Danno040 be great to hear views on this, even if social engine in browse members selection worked like this

goto browse members 
soon as click on a option of interest, ie if gender chose is male, a male tag is added, then hair type from a single select box is bald, then that is added as a tag and cannot be selected again, but you can revisit that same browse option and add long hair, to which add as a tag, then height blah blah blah, then hit search

single select questions are perfect for people to choose from
Male or Female, because if wish to search both, you simply do not narrow down
soon as 3 plus, its a headache to search
example hair colour blonde, red head, brunette
a blonde will only select blonde hair colour from single select

but as admin or another user searching, its a headache, esp if i only like blonde and redheads
because i have to either BLonde only, then RED head only, or search EVERYONE without selecting a colour, so i then have to view profiles i have zero interest, need to be able in browse members to be able to be like, a multi select option or tags as mentioned, but mirroring the initial signup form and search is just terrible IMO

**Comment by Elshara** [comment]
If there was a way to have tab containers present per search, you could define what people could search for within a specific filter range.

**Comment by DonnaScriptTechs** [comment]
https://github.com/SocialEngine/phpv4-issues/issues/582 as these are for the same thing, we'll close this one since the other one has more details.
