### ISSUE TITLE
thousands and decimal separators might take different value in certain countries

### ISSUE THREAD

**Issue by simpliby** [SocialEngine/phpv4-issues#489]
Hi,
the thousands and decimal separators might take different value in certain countries. Why socialengine doensn't support this in frontend and backend? 

This is the reason that socialengine and many plugins are not usable (or only usable with extensive  workarounds) in many countrys around the world 

[https://en.wikipedia.org/wiki/Decimal_mark]

Whichever language (in the following example english or german) the user selects - it should be different dates, time, numbers, currency and measurements. At the moment socialengine take differnt date formats, but the numbers format is always the same (see screenshots)

**Socialengine should use all the Zend language settings in /application/libraries/Zend/Locale/Data/de.xml (for example)
in SE Frontend, Backend and Plugins ....**

![bildschirmfoto 2016-09-15 um 10 26 29](https://cloud.githubusercontent.com/assets/22168165/18543216/f81182b4-7b2e-11e6-9738-56d937680a6d.png)

![bildschirmfoto 2016-09-15 um 09 01 57](https://cloud.githubusercontent.com/assets/22168165/18542058/10657484-7b29-11e6-9a00-beb484e5f345.png)
![bildschirmfoto 2016-09-15 um 09 06 16](https://cloud.githubusercontent.com/assets/22168165/18542064/1418fb96-7b29-11e6-90d9-3691fb62e049.png)
![bildschirmfoto 2016-09-15 um 09 09 02](https://cloud.githubusercontent.com/assets/22168165/18542065/15841600-7b29-11e6-9687-d3d15b7cc3cb.png)
![bildschirmfoto 2016-09-15 um 09 13 02](https://cloud.githubusercontent.com/assets/22168165/18542069/18d60778-7b29-11e6-9220-3fd5e6c85267.png)

**Comment by Khushboo016** [comment]
Hi @simpliby , We do not exactly understand your query here, so, please explain it in a bit more detail and attach a screenshot of the same issue that where you are facing this issue in SE, so that we can locate and get it. 

Thanks!

**Comment by simpliby** [comment]
Hi Khushboo016, i have explain it in a bit more detail and attached scennshot. I  hop that you now understand it.

Thanks & Ragards

**Comment by Khushboo016** [comment]
Hi @simpliby , Thanks for the clear explanation, I understood your query and have noted down this suggestion at our end for internal team discussion.

Thanks!

**Comment by leandrotavaresrocha** [comment]
Hello @Khushboo016 I am really interested in a solution for this. In my country "." are for thousands and "," are for decimals. I cant use any marketplace solution because is impossible to my users understand that they need to use a different price notation.

**Comment by smazurov** [comment]
Hey guys, thanks for bringing it to our attention - we want our international customers (and your users) to have a first rate experience, unfortunately its a bit difficult for us to know exactly how that experience differs as we do not have german, french, spanish native speakers on our team. Reports like these are important and I encourage everyone with same issue to "upvote" it by giving it a thumbs up in the original post. I did it to get us started. 

Our long term plan is to address all known limitations of internationalization system we have in place, and this is on the list. As to priority, I would say its slightly below some other items, such as better format and management of language files.

**Comment by leandrotavaresrocha** [comment]
Hi @smazurov!

Although this seems to be a simple problem, this is causing some problems in my community. I tried to start a subscription system in my website, but I needed to stop it since my users get confused with the usage of "dot/points" for decimals separators. When I tried to use the marketplace the case was worst, some users complained so much that users start to delete their accounts. So I am unable to adequately monetize my site since everything that refers to currency depends of this feature.

In most part of the world or countries use points (.) or commas (,) the link that simpliby there is a list of commons decimals separators in the world.

**Comment by simpliby** [comment]
Hi @smazurov,
are there any news on this subject? 

We can not use most plugins for socialengine and would have to make a lot of adjustments. The best solution is that socialengine supports the zend localization (not only for the date, but also for the numbers !!!)

Thanks & Regards

**Comment by smazurov** [comment]
Not at this time.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#28

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
