### ISSUE TITLE
Google New reCaptcha

### ISSUE THREAD

**Issue by meetgerry** [SocialEngine/phpv4-issues#49]
The existing google captcha seems to be very outdated and the captcha is easily broken by bots.

Please update socialengine to the new Google reCaptcha.

http://www.google.com/recaptcha/intro/index.html

**Comment by Anshuse** [comment]
Hi @meetgerry ,

Thanks for the suggestion. We're discussing this with our development team and will take appropriate action to implement this in near future.

Best Regards,
Anshu

**Comment by meetgerry** [comment]
Will this be included in the 4.8.9 release?

**Comment by smazurov** [comment]
No.

**Comment by meetgerry** [comment]
Will wait!

**Comment by MiamiShade** [comment]
This would be really nice to have the latest smart look and technology

**Comment by smazurov** [comment]
consolidated under #153

**Comment by brian7997** [comment]
This is breaking my signup page, is there a way to manually upgrade to v2? when will 4.9 drop???
