### ISSUE TITLE
Enhancement for Networks

### ISSUE THREAD

**Issue by poeticjustice** [SocialEngine/phpv4-issues#490]
I truely believe a enhancement to Networks is needed

Networks as it stands is more pointless than a paper oven, sorry to be blunt.
Especially when auto assigned

When you can browse members based on Male or Female, its absolutely pointless Making a Gender network.
Auto assign profile question field question
Male value to form Male Network, and same for Females.

there needs to be an add field
so each network can be norrowed down to actual networks

example

Related Profile Question
select values
would you like to add another related profile question

having ability for example to 
Related Profile Question = Gender
select values = Female
would you like to add another related profile question = Yes
Related Profile Question = Location
select values = UK
would you like to add another related profile question = Yes
Related Profile Question = County
select values = London
would you like to add another related profile question = no

Now that right there is a real Network, Based on Females in UK, within London

some values have questions within themselves if people set them, so its a shame they are not additional but apart of the same networkquestion

**Comment by Elshara** [comment]
I never use networks and disabled the option for people to use them in menu editor.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#29

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
