### ISSUE TITLE
Sign on not correct

### ISSUE THREAD

**Issue by smarty555** [SocialEngine/phpv4-issues#492]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)
## What are the steps to reproduce this issue?
1. …Sign on as admin
2. …click on main navigation menu item
3. …Click on another navigation menu item

What happens?
The sign on as admin will disappear from the top menu as I never sign in. On the top menu again "Sign in" and "Sign up" labels. Than as I click on another menu item the "admin" appeard 

…
## What were you expecting to happen?

I sign on on a page. When I click on other menu item, the sign up menu appear as I never sign up, then I click on another menu item and sign up disappear. So as I am clicking on different menu item on main navigation menu, I appear as I sign on and then as I am not sign on. I am at the same window session when it's happening.

Please click on different menu items of main navigation screen and you will see that.
## Any logs, error output, etc?

(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```
## Any other comments?

…
## What versions of software are you using?

**Operating System:** …

**SocialEngine PHP Version:** …4.8

**Comment by eugene-wh** [comment]
Can you login as a regular user (not admin)?

**Comment by Khushboo016** [comment]
Hi @smarty555 , This is not a known issue of SE PHP and seems to be related to your specific installation, so, if you still face the same then please open a support ticket for this at https://www.socialengine.com/client/ticket/create or email us at support@socialengine.com along with your site details.

Thanks!

**Comment by smarty555** [comment]
That is a bug in your system. All this happens with pages that I created as
New in Social Engine in Layout Editor. When I Created this pages in Layout
Editor with "Duplicate Existing Page" option and just copy/paste my
content, everything was back to normal.

**Comment by Khushboo016** [comment]
Hi @smarty555 , As I told you earlier also that we are not able too reproduce this issue on our local installation and it is also not reproducing on demo site https://demo.socialengine.com , so we suggest you to open a support ticket for this at https://www.socialengine.com/client/ticket/create or email us at support@socialengine.com along with your site details, so that we can check this issue.

Thanks!
