### ISSUE TITLE
CSS files not showing on Live server.

### ISSUE THREAD

**Issue by rkrathor** [SocialEngine/phpv4-issues#497]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Do some changes in any .css files and check that will not reflect on live server. but it works on local server. 

What happens?

there is a problem while updating css file into live?
I mean when I upload the changes of .css flie it don't reflect in sites but I can see those changes in file that is present in live..

What were you expecting to happen?
Changes should reflect as soon as file upload.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** …Linux(centos).

**SocialEngine PHP Version:** … v4.8.8

**Comment by Khushboo016** [comment]
Hi @rkrathor , This seems to be a caching issue, so, please check the issue after deleting the cache of your browser and after flushing the cache of the server of your site from "Admin" > "Settings" > "Performance & Caching" section of your site.

Thanks!

**Comment by rkrathor** [comment]
Hi,

Thanks it didn't work by that too.
actually other developer change the functionality the way css file used , i
mean for development and production mode. I changed that and its working
now.




Thanks & Regards,
Rajesh Kumar Rathor I PHP DEVELOPER LEVEL 2
Cell- +91-9911758531, +91-9555844379
http://in.linkedin.com/in/rajeshrathor
<https://mailtrack.io/trace/link/b9ca04bee4205278be4420cbb1c897d4a86626e3?url=http%3A%2F%2Fin.linkedin.com%2Fin%2Frajeshrathor&signature=f1163eaefcbeee62>
https://twitter.com/smilerathor
<https://mailtrack.io/trace/link/a5e47689d59936da9776ea5525bace3261f08e5f?url=https%3A%2F%2Ftwitter.com%2Fsmilerathor&signature=4efdb742dcb24d66>
https://www.facebook.com/smilerathor
<https://mailtrack.io/trace/link/2f076b701ef7a7f5caeefa421f09849f96a01780?url=https%3A%2F%2Fwww.facebook.com%2Fsmilerathor&signature=dd7bc888b57e0777>
https://www.google.com/+RajeshRathor88
<https://mailtrack.io/trace/link/776c967991c293f303506fe2bd773e0716b56f44?url=https%3A%2F%2Fwww.google.com%2F%2BRajeshRathor88&signature=e0667bf5f8495853>

**Comment by Khushboo016** [comment]
Hi @rkrathor , Glad to know that the issue has been resolved, so, am closing this github issue.

Thanks!
