### ISSUE TITLE
Double Add Video in Compose Message Area

### ISSUE THREAD

**Issue by leandrotavaresrocha** [SocialEngine/phpv4-issues#498]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)
## What are the steps to reproduce this issue?
1. Just visit a message in the /messages/inbox
2. Check the compose box if there is two "add video" options
## What happens?

…
## What were you expecting to happen?

There should have only one add video link, since the second is useless.
## Any logs, error output, etc?

(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```
## Any other comments?

…
## What versions of software are you using?

**Operating System:** Windows 10, Chrome

**SocialEngine PHP Version:** 4.8.12

![dungeonist compose](https://cloud.githubusercontent.com/assets/5342341/18808530/233d03ec-823b-11e6-906e-6d717a5bb2f5.png)

**Comment by Khushboo016** [comment]
Hi @leandrotavaresrocha , It seems to be an issue specific to your installation as you can see in the attached screenshot there is only a single option available to add video in the section "Compose Message" of our local SE site.

![single_add_video](https://cloud.githubusercontent.com/assets/18209340/18827186/1f7483f6-83ef-11e6-934d-21c3a7db6cad.png)

So, we suggest you to open a support ticket for this issue at https://www.socialengine.com/client/ticket/create or you can also email us at support@socialengine.com along with your site details, so we can check this issue.

Thanks!
