### ISSUE TITLE
Forum Replies Send Wrong Email

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#499]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)
## What are the steps to reproduce this issue?
1. … Create a forum topic.
2. … Have another user reply to the forum topic.
3. … Have yet another user reply to the same topic.
## What happens?

… User B gets an email saying user C replied to User B's discussion. While it was originally user A's discussion. User A gets the email stating users B and C replied to a topic user A has subscribed to.
## What were you expecting to happen?

… User A to be notified if users B and C replied to user A's discussion. User B to be notified user C replied to user A's discussion. User C to be notified if users A and or B or another user replies to the same discussion.
## Any logs, error output, etc?

(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```
## Any other comments?

… This happens in the most recent version of social engine.
## What versions of software are you using?

**Operating System:** … Windows 10 personal. Linux Server.

**SocialEngine PHP Version:** … 4.8.12

**Comment by Khushboo016** [comment]
Hi @Elshara , Thank you for reporting this issue! We have noted down this in our internal bug tracker and will fix the same in future releases of SocialEngine.

Thanks!

**Comment by shivani2910** [comment]
This is fixed in 4.9 when it is released.

**Comment by Elshara** [comment]
Awesome!
