### ISSUE TITLE
Pasting rich text content into editor

### ISSUE THREAD

**Issue by maxx24** [SocialEngine/phpv4-issues#50]
It isn’t possible to post copied and pasted text in rich text format when using the Blog Text Editor. Rich text posted in the blog text editor appears fine after pasting it, but the formatting is lost upon publishing the blog post. Copy and paste does not bring over links, photos, or paragraph formatting. Also, typing in a URL does not automatically make it a hypertext link–you have to manually add it.

Is this a bug, or just the way the editor works?  Or am I (and my members) missing something?  I spend a lot of time editing blog posts due to this issue.

**Comment by Anshuse** [comment]
Hi @maxx24 ,

When you say "the formatting is lost upon publishing the blog post", can you please explain the issue using the screenshot(s) to be able us to catch the issue quickly.

Best Regards,
Anshu

**Comment by maxx24** [comment]
A lot of my members have their own blogs.  So when they want to post a blog on my site, they typically copy and paste it from my site.  However, when they do this, paragraph spacing is lost, hypertext links are broken, and images do not paste.  The images aren't a big deal.  But it is a major hassle to go back in and add a line space between each and every paragraph, and to re-add any hypertext links.  A true rich text editor would carry all of this formatting over when you paste it.  There really is no screenshot to show what I am explaining.

**Comment by Anshuse** [comment]
Hi @maxx24 ,

Thanks for providing detailed explanation of the issue.

We've reported this issue at our end for our development team to have discussion over this to work on this in near future.

Best Regards,
Anshu
