### ISSUE TITLE
Changing Email Frequency Prevents Emails From Being Sent

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#500]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Go to settings.
2. … Click on mail settings.
3. … Change default frequency from 25 to another number. Doesn't matter if it is 1 or 100.

What happens?
-------------
… The cue shows the emails as being sent but the emails never get received. Only if the cue is specifically set to enabled and 25 do emails get sent if they are found to be delivered or awaiting delivery if in the cue already.

What were you expecting to happen?
----------------------------------
… Emails to be sent the same way if another number is put in to that field.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… I usually keep the cue disabled for this reason.

What versions of software are you using?
----------------------------------------
**Operating System:** … Personal windows 10. Server Linux.

**SocialEngine PHP Version:** … 4.8.12

**Comment by Khushboo016** [comment]
Hi @Elshara , The maximum number of mails that can be sent out in one go from a SocialEngine site depends on the server of your site that how many emails it can support to send successfully in one time in case you are using the built-in mail function to send mails. And if you need to send large number of mails from your site, then we suggest you to use services like sendgrid.com or mailgun.com to send mails and then it would depend on these services that how many emails they would allow to send in one time. So, we've just suggested a minimum value of `25` for mail count and you can set this value according to the capacity of the server of your site or according to the email service you are using, if you are using one.

Thanks!

**Comment by Elshara** [comment]
I understand that.
What I'm referring to is setting this to a custom number other than 25
does not seem to send emails.

**Comment by Khushboo016** [comment]
Hi @Elshara , This issue seems to be occurring in your specific installation, so we suggest you to open a support ticket for this from https://www.socialengine.com/client/ticket/create or you can also send us an email along with your site details at support@socialengine.com, so we can check this issue.

Thanks!
