### ISSUE TITLE
Website Functions Are Inaccessible To Mobile Users

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#502]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)
## What are the steps to reproduce this issue?
1. … Install and enable mobile plugin.
2. … Sign in on a mobile device or enable mobile site from the footer.
3. … Try to do normal actions, posting comments, joining groups, adding photos, writing blogs etc from within the mobile mode.
## What happens?

… The functionality doesn't exist. The button to add or contribute content simply isn't there.
## What were you expecting to happen?

… Mobile users to be able to do the same thing as desktop users without having to ditching mobile site completely upon first loading the website.
## Any logs, error output, etc?

(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```
## Any other comments?

… Lets start with the basics. Mobile users can't even view their notifications. They are treated as less than welcome guests because of the device they use. Forget admin functionality, if you are on a mobile, you can't access the admin panel at all.
## What versions of software are you using?

**Operating System:** … Windows 10 Linux

**SocialEngine PHP Version:** … 4.8.12

**Comment by Khushboo016** [comment]
Hi @Elshara , In mobile site, you can post comments, add new photos to albums and can also join groups if you place the widget "Group Profile Options" on the page "Mobile Group Profile", but yes, there are so many features which do not exist in our Mobi plugin. Our mobile site is currently more oriented towards browsing of items than creation of items. But we already have many plans to enhance mobile site features in future releases of SE, till then we suggest you to refer to one of the various 3rd party responsive themes available for SE to have all those features in your mobile site too that are available in your full site.  

Thanks!

**Comment by Elshara** [comment]
It is good to know you have plans to improve mobile accessibility.
