### ISSUE TITLE
Facebook integration doesn't working.

### ISSUE THREAD

**Issue by rkrathor** [SocialEngine/phpv4-issues#504]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. …Open crezilla.com 
2. …click signin 
3. …click on facebook icon.

What happens?
-------------
Page Not Found

The page you have attempted to access could not be found.

What were you expecting to happen?
----------------------------------
it should work as facebook integration works.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** … centos

**SocialEngine PHP Version:** … 4.8.8

**Comment by Khushboo016** [comment]
Hi @rkrathor , I tried login to your site using f-connect button, but received error as shown below:

![error](https://cloud.githubusercontent.com/assets/18209340/19148020/7c1d4336-8bd8-11e6-938f-9727a2d51215.png)

So, it seems that your Facebook app has not been configured well which is leading to this error. So, we suggest you to follow this article to integrate your SE site with Facebook: http://support.socialengine.com/php/customer/portal/articles/1796979-admin-panel---settings-&amp;gt;-facebook-integration

Hope that would help, Thanks!

**Comment by rkrathor** [comment]
Hi,

Please recheck now everything is fine no error will come but it will not do
anything.

thanks
Rajesh




Thanks & Regards,
Rajesh Kumar Rathor I PHP DEVELOPER LEVEL 2
Cell- +91-9911758531, +91-9555844379
http://in.linkedin.com/in/rajeshrathor
<https://mailtrack.io/trace/link/f9843d5f13968d7f0bed10671f4c3e4916976119?url=http%3A%2F%2Fin.linkedin.com%2Fin%2Frajeshrathor&signature=2ec8e4f5ec90708e>
https://twitter.com/smilerathor
<https://mailtrack.io/trace/link/ec306a6c8e4e03a0239a2254bae92d0296e61220?url=https%3A%2F%2Ftwitter.com%2Fsmilerathor&signature=a3ee8d843cbbdae2>
https://www.facebook.com/smilerathor
<https://mailtrack.io/trace/link/a67c91bf0c96c6265e1f973ebfb4b1bb25865c07?url=https%3A%2F%2Fwww.facebook.com%2Fsmilerathor&signature=8e86fe6138b1e938>
https://www.google.com/+RajeshRathor88
<https://mailtrack.io/trace/link/91304db5c1fe108b5d03080b8a82c0e12503a8c6?url=https%3A%2F%2Fwww.google.com%2F%2BRajeshRathor88&signature=0aab65a0aaa72140>

**Comment by Khushboo016** [comment]
Hi @rkrathor , I've replied to your similar query in your support ticket, so please do further conversation there.

Thanks!

**Comment by Elshara** [comment]
Facebook is retiring its API.
