### ISSUE TITLE
need Social Engine to show expanded comments/likes within Group context, not jump to Profile page

### ISSUE THREAD

**Issue by Traveler0** [SocialEngine/phpv4-issues#505]
## What are the steps to reproduce this issue?
1. …Go to a post inside a Group that has many comments/likes.
2. …Click to show all comments or likes.
## What happens?

…Get taken to a person's profile page and the full comments/likes are shown within that context. This is not only confusing to users who are unaware that they are on someone's personal page and have left the group and then don't know how to get back and why suddenly stuff has disappeared and they can only see this one post with comments. But it also has the unintended consequence that if a user has made their profile viewable to friends only, and I am not their friend, I am now unable to view all those comments even though we are both members of a group within which their post was made and so I should be able to view that post and all the comments on it.
## What were you expecting to happen?

…Stay inside the group page and simply expand the comments view, with all other group posts and group elements staying where they are, relative to the viewer.
## Any other comments?

…This is very confusing to our users and makes it difficult to use the site. Please fix.
## What versions of software are you using?

**Operating System:** …any

**SocialEngine PHP Version:** …4.8.11 at the moment though it's the same in .12

**Comment by Khushboo016** [comment]
Hi @Traveler0 , I've added this issue at our end in our feature tracker, and our team will discuss regarding its implementation in future releases, but if you need this to be resolved on your site now, then we suggest you to do code customization at your end to achieve this.

Thanks!

**Comment by DonnaScriptTechs** [comment]
This was fixed in 4.9.0 release. If you sill see the issue in 4.9.0 and up, please open a new bug report.
