### ISSUE TITLE
Users Logging as another user

### ISSUE THREAD

**Issue by leandrotavaresrocha** [SocialEngine/phpv4-issues#507]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)
## What are the steps to reproduce this issue?
1. This error occur sometimes, but I couldnt identify what is the reason. 
## What happens?

Sometimes users just login as another user. Today a user after post a photo logged automatically as me and I already logged as another user when I tried to login with my account. 
## What were you expecting to happen?

This should not occur since this can become a security breach.
## Any logs, error output, etc?

(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```
## Any other comments?

I cant say what is the reason that start this because seems that there is no connections between the action that started this error to me and to a user. I already faced a friend that logged as me when it logged with his own credentials. 
## What versions of software are you using?

**Operating System:** Windows 10

**SocialEngine PHP Version:** 4.8.12

**Comment by Khushboo016** [comment]
Hi @leandrotavaresrocha , As this issue is not a known issue of SE PHP and seems to be related to your specific installation, so, I suggest opening a support ticket for this along with your site details from https://www.socialengine.com/client/ticket/create or you can also email us at support@socialengine.com. 

Thanks!

**Comment by smazurov** [comment]
If you could provide step by step reproduction instructions, we'd be able to verify. I can tell with confidence this is not a bug that occurs under normal operating conditions.
