### ISSUE TITLE
Feature Request: Include Link Icon In Private Messages

### ISSUE THREAD

**Issue by sunfellow** [SocialEngine/phpv4-issues#509]
We need the ability to add links to private messages. The edit bar in private message is missing the link icon. Does anyone know if there are plans to include this in a future update? Thanks.

We're using SocialEngine 4.8.12
https://nhne-nde-network.org

**Comment by Khushboo016** [comment]
Hi @sunfellow , The feature of adding links in private messages is already provided in SocialEngine PHP, see below screenshot of SE demo site for reference:

![add_link](https://cloud.githubusercontent.com/assets/18209340/19928353/16cfa5a8-a124-11e6-9b11-c703c5181d09.png)

Thanks!

**Comment by sunfellow** [comment]
Khushboo, I'm not seeing the window you posted. In the window I see, there is no ability to post links. Go here to see what I'm seeing: https://nhne-nde-network.org/media/private-message-window.jpg

**Comment by Khushboo016** [comment]
Hi @sunfellow , Thanks for bringing this to our notice! We've checked this issue at our end and can see that there is no option available to add a link in the window to send a reply to a message. So, we've forwarded this issue to our development team and they will fix it in the next release of SE.

Thanks!

**Comment by sunfellow** [comment]
Thanks, Khushboo.

**Comment by Elshara** [comment]
This is awesome! Same issue happening here.

**Comment by DonnaScriptTechs** [comment]
I can see the Link option in the send reply in version 4.9.2. Please test once that is released.
