### ISSUE TITLE
Additional feature requests

### ISSUE THREAD

**Issue by maxx24** [SocialEngine/phpv4-issues#51]
I moved my site from ning like many others. I love social engine, but here are the improvements I would like to see:

1 - Add FB like and FB/twitter/linkedin share tools to bottom of blogs, videos, forum/group discussions. Right now I am using the ”addthis” sidebar which allows me to share things, but I want to see built in social media likes and shares.

2 - When using sharethis app, headlines include the title of the website in addition to title of blog/video. Also facebook is not picking up the image from the blog or video.

3 - Downloading/exporting member email addresses. I use an outside email software program. Right now I am just copy/pasting from the manage members page.

4 - View which members delete their accounts

5 - Remove status updates from the ”view members” page and instead add other pertinent info from their profile (location, occupation).

6 - Text editor on blogs– copy and paste does not bring over links, photos, or paragraph formatting. Also, typing in a URL does not automatically make it a hypertext link–you have to manually add it.

7 - Activity feed RSS importing outside content (for groups also). On ning, they had an app where you could add RSS feeds and it would import the content of those feeds into the activity feed making it look like there was more activity.

8 - Have images appear in the activity feed when a blog is posted, similar to facebook.

**Comment by Anshuse** [comment]
Hi @maxx24 ,

Thanks for providing feedback. We've noted down the feature requests for our internal team discussion.

Best Regards,
Anshu
