### ISSUE TITLE
Member's blog posts not filtered by category

### ISSUE THREAD

**Issue by angelinfante** [SocialEngine/phpv4-issues#510]
What are the steps to reproduce this issue?
-------------------------------------------
1. Open a member's blog post
2. Click on one of the categories to filter by category from the blog post

What happens?
-------------
All the posts of the member are displayed instead of filtering by category

What were you expecting to happen?
----------------------------------
See all the member's posts that belong to the selected category

What versions of software are you using?
----------------------------------------
**Operating System:** Amazon Linux

**SocialEngine PHP Version:** 4.8.12

**Comment by Khushboo016** [comment]
Hi @angelinfante , we've checked this issue on our local server and search by category is working fine at our end, so, we suggest you to open a support ticket for this issue from https://www.socialengine.com/client/ticket/create or you can also send us an email at support@socialengine.com along with your site details, so, we can check this issue.

Thanks!

**Comment by angelinfante** [comment]
So, you have checked that filtering by category is working from blog post page? (not from Browse Blogs, where I can see it is working fine)

**Comment by Khushboo016** [comment]
Hi @angelinfante , Thanks for your reply, we're now able to reproduce this issue at our end and have forwarded the same to our development team. They'll fix it in the next release.

Thanks again!

**Comment by Elshara** [comment]
Thanks for double checking. Same can be reproduced on this end.

**Comment by shivani2910** [comment]
This is fixed in 4.9 when it is released.

**Comment by Elshara** [comment]
Awesome!
