### ISSUE TITLE
Layout Editor Problem

### ISSUE THREAD

**Issue by mujaksaba** [SocialEngine/phpv4-issues#511]
Hello,
As admin I have access to admin panel layout editor:
-But click Block edit function does not work.
-Blocks with dragdrop no work.
-Bloks select no work
I have actuel socialengine version 4.8.12
Two days ago I upgraded Zend Framework (4.X → 4.8.10)
Before Zend upgrade true with layout editor everything ok., maybe is bug?
error log file show:
2016-11-11T09:20:02+00:00 NOTICE (5): [8] Undefined variable: matched (/home/xxxx/public_html/application/modules/Core/View/Helper/HeadScript.php) [206]
Error Code: dc8120
Stack trace:
#0 /home/xxxx/public_html/application/modules/Core/layouts/scripts/admin.tpl(145): Core_View_Helper_HeadScript->toString()
#1 /home/xxxx/public_html/application/libraries/Zend/View.php(108): include('/home/xxxx/public_html/appli...')
#2 /home/xxxx/public_html/application/libraries/Zend/View/Abstract.php(890): Zend_View->_run('/home/xxxx/public_html/appli...')
#3 /home/xxxx/public_html/application/libraries/Zend/Layout.php(796): Zend_View_Abstract->render('admin.tpl')
#4 /home/xxxx/public_html/application/libraries/Zend/Layout/Controller/Plugin/Layout.php(143): Zend_Layout->render()
#5 /home/xxxx/public_html/application/libraries/Zend/Controller/Plugin/Broker.php(333): Zend_Layout_Controller_Plugin_Layout->postDispatch(Zend_Controller_Request_Http)
#6 /home/xxxx/public_html/application/libraries/Zend/Controller/Front.php(965): Zend_Controller_Plugin_Broker->postDispatch(Zend_Controller_Request_Http)
#7 /home/xxxx/public_html/application/modules/Core/Bootstrap.php(84): Zend_Controller_Front->dispatch()
#8 /home/xxxx/public_html/application/libraries/Engine/Application.php(160): Core_Bootstrap->run()
#9 /home/xxxx/public_html/application/index.php(427): Engine_Application->run()
#10 /home/xxxx/public_html/index.php(24): include('/home/xxxx/public_html/appli...')
#11 {main}

Best Regards

**Comment by mujaksaba** [comment]
hi,
Problem ist solved, multilanguage problem.
Thank You

**Comment by Khushboo016** [comment]
Hi @mujaksaba , Glad to know that the issue has been solved. Please let us know in case of any further queries.

Thanks!

**Comment by mujaksaba** [comment]
Hello Khushboo016,
for admins is not a problem for the layout editor used in English, normally should work with other language or not? (Language Bosnian is from www.webritam.com , Support is dead, last language update is  2013),  
Probably header(javascripts) not loading in other language. 
If you can help me and tell me what to do would be ok.
thank you

**Comment by Khushboo016** [comment]
Hi @mujaksaba , We suggest you to open a support ticket for this issue at https://www.socialengine.com/client/ticket/create or you can also send us an email at support@socialengine.com along with your site details, so we can look into this issue.

Thanks!

**Comment by mujaksaba** [comment]
Hi @Khushboo016 ,

Thank You to suggest. Language Bosnian is problem from webritam.com, last update 2013, webritam.com is mafia :)
Problem is solved.
Regards
