### ISSUE TITLE
Search only users, not albums, not anything else, only USERs

### ISSUE THREAD

**Issue by poeticjustice** [SocialEngine/phpv4-issues#513]
hi Social engine

Love new branding, im wondering how to only have the search feature only search users, i really hate the search feature searches albums and other things.

**Comment by Khushboo016** [comment]
Hi @poeticjustice ,

First of all, we're very glad to hear that you're liking our new website.

Regarding  " im wondering how to only have the search feature only s":
It seems that you're referring to the global search feature here, so, we would suggest that if want to search only among users of the site, then you can search them from the Member Browse page or you can also select "Member" while performing global search to filter out only users from the search results on search page as shown in the screenshot below:

![member_search](https://cloud.githubusercontent.com/assets/18209340/20622861/debf4fce-b32a-11e6-9430-9ac848e92797.png)

**Comment by poeticjustice** [comment]
I really dont want users having option to search albums, esp when i have restricted member levels and if they perform search, and a profile album pops up etc, they may click on it for them to only see you dont have permission etc, its kind of pointless, thats why i want the search to only search members, or if i can set to members as default rather than everything, then i can custom css it to hide the drop down box

**Comment by Khushboo016** [comment]
Hi @poeticjustice , 

Regarding "I really dont want users having option to search albums, esp whe":
You can achieve this by doing code customization in the core files at your end. If you are not comfortable in doing code level changes, then I suggest you to refer to our third party developers, they would be happy to assist.

Thanks!

**Comment by poeticjustice** [comment]
all third party developers will refuse to touch core, and only work on independent widgets.

I have no issue editing core, but i cant find the file location

**Comment by Khushboo016** [comment]
Hi @poeticjustice ,

Regarding "all third party developers will refuse to touch core, and only work on independent widgets.":
This is the code in the file: /application/modules/Core/controllers/SearchController.php that is responsible for display of multiple options in the drop-down of the global search feature.

` // Get available types
    $availableTypes = $searchApi->getAvailableTypes();
    if( is_array($availableTypes) && count($availableTypes) > 0 ) {
      $options = array();
      foreach( $availableTypes as $index => $type ) {
        $options[$type] = strtoupper('ITEM_TYPE_' . $type);
      }
      $form->type->addMultiOptions($options);
    } else {
      $form->removeElement('type');
    }
`
So, you can edit it as per your needs to show only required option/options.

Thanks!

**Comment by eugene-wh** [comment]
Why not direct search to Browse Members page as a simple solution?

**Comment by poeticjustice** [comment]
@eugene-wh I am using Social Engine in such a unique way compare to other social networks.
hence why i purchased your access manager to restrict users using browse members page.
I have loads of worked made to browse members section.

TBH the search function should have greater control in the backend, I cant see any reason why users would search for albums.

Having that feature as default seems sooooo silly.

What social engine need to address is multi select into = Tags, so when select a option in multi select box, it removes it from the option and adds it as a tag, which users can easily remove.

And networks needs to be addressed, Networks is soooooo pointless unless they address combining multipul varients.
example

Network Men
Network Women.

I can search men and women, so why bother making networks based on questions that can be searched

Need to be able to make networks like
Men, caucasian, 20-40, in UK
Combine 4 varients to make a specific network

**Comment by Elshara** [comment]
I agree. Search should be a thing you use a multi select list box for to be able to search all areas of the website or specific areas at once.

**Comment by ownergroup** [comment]
@poeticjustice have you solve it? I need to achieve the same thing, limit the search to just few items. Please let me know!

**Comment by Elshara** [comment]
What do you mean?

**Comment by poeticjustice** [comment]
@ownergroup yea I fixed it , delved into the MySQL database to achieve it tho took a while to find and change tho

**Comment by Elshara** [comment]
Awesome

**Comment by ownergroup** [comment]
@poeticjustice that's cool!! Could you please let me know what did you do to get that done? I've checked the controller's code but I'm not that advanced to customize it

**Comment by ownergroup** [comment]
@poeticjustice sorry to bother, is it posible any help on this?

**Comment by poeticjustice** [comment]
@ownergroup what is it exactly your trying to achieve, or what do you only want shown?

If you can in detail say exactly what want I may be able to help, but I'd need all the info up front

**Comment by ownergroup** [comment]
@poeticjustice great, thank you!! Well, I need almost the same like you: I need to make searcheable only the following item types:

• Products (Store plugin from Hire-Experts)
• Members (User module from SE)
• Custom field I created for sign up process: Company name (User module from SE)

So, I need to hide all other item types from the suggested search (as you showed it in your first image above) and therefore limiting the results to just those 3 item types

**Comment by poeticjustice** [comment]
I'm out all day tomorrow so I'll look up my personal written documentation on Friday matey @ownergroup if you have the website let me know and I'll personally contact you

**Comment by ownergroup** [comment]
@poeticjustice sure, no problem! my site is https://www.ownergroup.net. If you register we can be in touch over there. Also, let me know if you have your site online

**Comment by Elshara** [comment]
You have a lovely network.

**Comment by ownergroup** [comment]
Thank you!! Whenever you wanna use it you are more than welcome

**Comment by Elshara** [comment]
Mind if I check it out?

**Comment by Elshara** [comment]
Your website seems to not have a submit button when uploading a photo
and yes it's mandatory.

**Comment by ownergroup** [comment]
Yes, there is a submit button after uploading the pic, it reads "save" and allows to pass to the next page: home page

**Comment by Elshara** [comment]
I'll try another browser. Currently using Firefox.

**Comment by Elshara** [comment]
Chrome let me do it. Firefox wouldn't.

**Comment by ownergroup** [comment]
Hi @poeticjustice, have you been able to reach your written doc about what tables/values modifying?

**Comment by poeticjustice** [comment]
@ownergroup signing up to your site now
will message soon

**Comment by ownergroup** [comment]
@poeticjustice  Great, I'm logged in now, wait for you to chat in my site

**Comment by Elshara** [comment]
If he signed up there.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#30

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
