### ISSUE TITLE
Comment System Improvements

### ISSUE THREAD

**Issue by leandrotavaresrocha** [SocialEngine/phpv4-issues#514]
This is a improvement request for how comments in Social Engine works.

Comments are the main way that users interact on social networks so this feature need a completly special attention. Social Engine has a comment system that is pretty outdated and doenst help users to continue interacting others users. Just to know:

1- If a user reply a comment directly in the feed no new entry is created in the activity feed, so no user except those that participated of the discussion know that there is something happening.
2- If a user comment in a item (like a blog) a feed entry is created but if someone comment on this new entry this comments will not go to the original content, creating a second and completly separated discussion that just a few users can interact.
3- If someone reply a comment from a content (like a blog) the own content is not attached with the new entry. Just a "User B comment on A Blog" is created. Facebook, by example, include a original copy of the content, so users that view this activity can know about what the A blog is.

As a example of the problem if I post a content and two weeks after a users comment on the item directly in the feed I will receive a notification, but the content will stay in the feed in the same position, that is two weeks ago in the feed. A new entry in the feed is only created if the user go until the content and comment on it.

This structure create a problem when users want to reply comments and continue with the discussion, because the original activity stay chronologically two weeks ago in the feed they need to scroll it until find it. The best way to find a comment in this case is to use the notification, but this is bad to the website since user doesnt use the feed and others users will lose completly the discussion. I already find a great discussion between three users in a old blog posted 2 months before that no one noticed because the original content doesnt appear anymore in the feed without several scrolls.

My suggestion are:

1- Items in feed appear chronologically but if someone comment on it, this entry is will appear in the feed considering the date of the last comment/reply instead the published date;
2- If someone comment in "comment activity entry" like "user b comment a blog" this comment should be aggregated with the original content;
3- The "comment activity entry" must include the original content and not only "user b comment a blog" text;
4- Comments made directly in the feed create entries like "user b comment a blog" and not only comments made in content page;

The first suggestion would solve the whole problem alone, but I think that a possible issue with feed filter may happens when someone comment on a content published by a user and nobody is friend.

The point is that the actual comment system from SE is really poor for User Experience and we know how this is important.

**Comment by eugene-wh** [comment]
We have tried to address some of those issues with our plugin Nested Comments. But unfortunately, improvements for the main feed aren't that easy to implement without the modification of the feed itself.

There are more issues that you have mentioned. More problems are noticeable in active communities when there are numerous comments for the same blog/page. There is no pagination but 'View More' link, which breaks the experience when you try to read all comments.

**Comment by leandrotavaresrocha** [comment]
I create a suggestion based on my experience, I dont know if is the best solution, however is notable that we have a problem here. Comments are the main way that user interact and we should give a special dedication to this feature even that we need to change the feed by itself.

My community isnt very active now but the actual way how comments are displayed in the feed is not helping to improve it. Sometimes people comment my posts and I get lost trying to figure out where is the original content, I just imagine that my users suffer also like me.

**Comment by Elshara** [comment]
Comments needs to be redesigned in general. The problem with how comments work is that it is in its current form displayed to really only meant to be seen from the activity feed, and so they never truly represent the ability for posts to have their own comments area devoted to it as seen in the lack of pagination. I actually like the way forum comments display themselves.

**Comment by Khushboo016** [comment]
Hi @leandrotavaresrocha , Thank you for your suggestions! We would like to let you know that we've already some plans for improving feed generation in Activity Feeds in SE future version 4.9 and your suggestions also helped us in this improvement work. We would like to let you know that hopefully we're going to cover all these three points suggested by you in 4.9 moving towards the improvement of SocialEngine.

Thanks & Regards!

**Comment by leandrotavaresrocha** [comment]
Thanks @khushboo16. There is any ETA about version 4.9? Someone said that we would expect something coming before the year's end and I would like to know if this estimative still active.

**Comment by Elshara** [comment]
I would as well.

**Comment by Khushboo016** [comment]
Hi @leandrotavaresrocha , @Elshara ,  We're releasing a minor upgrade in 2-3 days and 4.9 is also close to its launch. We're trying hard to make its release as soon as possible.

Thanks!

**Comment by leandrotavaresrocha** [comment]
Just a update. I was talking with some users and they suggested a simple solution. The feed is basically organized according to the publish date, the suggestion was that in cases where it has been liked or commented the date of the most recent like or comment become the publish date of the content for purpose of organize the feed. Notice that I am talking to update the publish date, but make that the feed recognize the date of the last like or comment as the date of the content.

The only problem of this case, I believe, is how the system would handle when I have a feed where only the publications of friends appear. In this case when you like something the idea is that it be available to your friends, however as the content originally belongs to another user I believe that it does not appear.

**Comment by Elshara** [comment]
IT wouldn't anyways. The core isn't able to handle such a system update anyways.

**Comment by leandrotavaresrocha** [comment]
@elshara, I think that is possible with a small query change. I was reading the code that generate the activity feed and it display based on the "post date" what we need is to make a SQL join with the like and comment tables to get the like and comment publish date,  filter the last recent action and use this date.

**Comment by Elshara** [comment]
Sounds like it could be something to expand on. Perhaps I was
mistaken. The code will need to be ported to other areas.

**Comment by leandrotavaresrocha** [comment]
I made a test and this is the logic that some scripts adopt like phpfox and buddypress. When someone comment or like something the original content jump to the top of the feed based on the last like or comment made. I think that this is the most easy and secure way to mantain the feed dynamic, since as the activity stay in the chronollogical order of the feed people start to like and comment an item and nobody knows that this is happening. I am really anxious to know what is comming in this case.
> 
Sounds like it could be something to expand on. Perhaps I was
mistaken. The code will need to be ported to other areas.

**Comment by Elshara** [comment]
Well what I was trying to point out, the code will need to be utilized
across the platform. The comments and likes system integrates across
all site modules.

**Comment by iborisovBG** [comment]
All system need to use longpolling + to be ajax based (this will up the speed of the engine) but there is a lot of work and may will be more easy to write a new engine

**Comment by Elshara** [comment]
I agree.

**Comment by DonnaScriptTechs** [comment]
This is implemented for 4.9.0 when it is released.

**Comment by Elshara** [comment]
Awesome!
