### ISSUE TITLE
Maintenance code issues

### ISSUE THREAD

**Issue by poeticjustice** [SocialEngine/phpv4-issues#516]
Hi guys

how many have experienced this issue with Social Engine

Main site
and
Staging site (for tests and dev in subfolder) 

both have maintenance mode enabled
Main site has code (test1234)
Staging site has different code ( dev1234)

you log into main site via entering maintenance code, all is fine, you then visit your staging site, enter the maintenance code and it doesnt let you in, it shows it tried the maintenance code in the url displaying ?en4_maint_code=maintcodeused

but remains on the maintenance page, and it will only let you in once you clear the cache.

But each time you go between each site, you must clear the cache or use two browsers.

wondered if there was reason for this

**Comment by Elshara** [comment]
It's a cookie issue I think. Making the maintenance code different cookie settings would fix this.

**Comment by Khushboo016** [comment]
Hi @poeticjustice , Can you please let us know which caching method are you using on the server of your site?

Thanks!

**Comment by poeticjustice** [comment]
@Khushboo016 i have a cloud server with fastcomet, unsure what caching method, as partner deals with the server

**Comment by Khushboo016** [comment]
Hi @poeticjustice, If you're not sure which caching method is enabled on your site, then please go to "Admin" > "Settings" > "Performance & Caching" section of your site and check which option is selected against the field "Caching Feature". The option which is found selected is the caching method being used on your site. Please see below screenshot for reference:
![caching_feature](https://cloud.githubusercontent.com/assets/18209340/21542868/40ffd5d8-cde7-11e6-91ed-8e234a13ca07.png)

**Comment by poeticjustice** [comment]
Yes file based!

**Comment by Khushboo016** [comment]
Hi @poeticjustice, We tried to reproduce this issue several times at our end, but we did not face such an issue that Maintenance code of staging site did not work. So, we suggest you that if you still face the same issue, then please send an email to us at support@socialengine.com regarding this issue along with your site details, so, we'll look into the issue.

Thanks!

**Comment by poeticjustice** [comment]
I know have SSL (https) and it doesn't do it when over https, only http.
Its not so much bother simply deleting cookies or opening in edge (firefox however is aweful to use )

Appreciate you replied to this tho https://github.com/SocialEngine/phpv4-issues/issues/536

This is a major bug and its affecting some signups
