### ISSUE TITLE
Multi-select option not showing up on mobile device.

### ISSUE THREAD

**Issue by rkrathor** [SocialEngine/phpv4-issues#518]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Go to site , login with credentials. click on the name of profile like (crezilla admin). 
2. … You will come to edit profile, if you are in Desktop than click on any dropdown, you will able to see the options list.
3. … Now check the same in mobile , you wouldn't able to see the dropdown options list.

What happens?
-------------
… Dropdown Option lists not showing up for mobile devices.

What were you expecting to happen?
----------------------------------
… It should also option the option list in mobile device same as desktop.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

``` One difference I check the" <div class="optWrapper> not coming in mobile while it coming in desktop.


Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** … Linux(centos).

**SocialEngine PHP Version:**Version	4.8.8

![desktop-multiselect](https://cloud.githubusercontent.com/assets/10502380/20966649/542dffce-bca1-11e6-827e-c9a5b4827763.png)
![mobile_multiselect](https://cloud.githubusercontent.com/assets/10502380/20966650/5437fd44-bca1-11e6-8ca6-d240b2548852.png)

![optwrapper-desktop](https://cloud.githubusercontent.com/assets/10502380/20966715/ab47fca6-bca1-11e6-91e1-fde4582a5862.png)
![optwrapper-mobile](https://cloud.githubusercontent.com/assets/10502380/20966716/ab4d0250-bca1-11e6-93ea-abc2d55019f9.png)

**Comment by Elshara** [comment]
Nothing really does other than reading the website itself, work properly on mobile at present.

**Comment by poeticjustice** [comment]
I dont have this issue as i use a responsive theme, i can see such settings fine, plus a manually made an awesome dashboard :) @rkrathor are you using the basic theme?

**Comment by Elshara** [comment]
Maybe that would fix it.

**Comment by rkrathor** [comment]
@Elshara I check by my end but it shouldn't happen this way.

**Comment by rkrathor** [comment]
@poeticjustice I am using theme named "Snowbot v4.7.0".
this is a responsive theme I guess.

**Comment by Elshara** [comment]
Okay then let us know if you are able to upload photos or any other
file type from mobile.
Come to that, try and find the option to do so.
