### ISSUE TITLE
Can't Add Content From Mobile

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#519]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Sign in on your mobile.
2. … Browse to the module you want to contribute to, blogs, forums, photos, videos, etc.
3. … Notice the add button is missing.

What happens?
-------------
… There is no way to add content when you are signed in on a mobile phone.

What were you expecting to happen?
----------------------------------
… For people using their mobiles to be able to use the website, up to and including being able to chat with people online.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… This kind of problem is an ongoing issue in social engine, and is one of the many reasons why people don't come back.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 as well as Linux Cent OS and Debian

**SocialEngine PHP Version:** … 4.8.12

**Comment by Elshara** [comment]
People also aren't able to update their profile, manage account settings or even respond to private messages.

**Comment by poeticjustice** [comment]
@Elshara as in content do you mean users cant add images or even status updates?

**Comment by Elshara** [comment]
That's right. Nothing. Can't even change settings.

**Comment by poeticjustice** [comment]
That's odd, I'll see if mine does that, which mobile device?

**Comment by Elshara** [comment]
Well this is a bit of a generic response. All of them. Apple Iphone
Ipad, Google Android Phone Tablet, Microsoft Windows Phone, Blackberry
etc.
The problem is, with mobile plugin installed, the website becomes
quite literally a bottleneck for trouble because all mobile users
won't be able to participate in anything. From simple tasks such as
uploading files and posting comments and making main posts to editing
settings and even if admin, navigating the admin panel. The default
mobile plugin just isn't functional.

**Comment by Khushboo016** [comment]
Hi @Elshara , @poeticjustice , We've plans to launch default responsive theme in the release 4.9, so, hopefully all these mobile site features would be including in 4.9.

Thanks!

**Comment by Elshara** [comment]
Hopefully in the new year this will happen. If not then, maybe 2020. lol
Thanks for the update.
