### ISSUE TITLE
Issue when adding Youtube Videos 

### ISSUE THREAD

**Issue by Domokun** [SocialEngine/phpv4-issues#52]
Hello guys!

Since a couple of days, it is impossible to add Youtube Videos with the Standard plugin. Not in my site, not in a fresh installation, not in your demo site.

With Vimeo everything works fine, but youtube sends back an error... any help is welcome!!

15-06-03T20:30:16+00:00 CRIT (2): 
Error Code: 41362b
exception 'Zend_Gdata_App_HttpException' with message 'Expected response code 200, got 410
No longer available' in /home/nydomain/public_html/application/libraries/Zend/Gdata/App.php:714
Stack trace:
#0 /home/nydomain/public_html/application/libraries/Zend/Gdata.php(221): Zend_Gdata_App->performHttpRequest('GET', 'https://gdata.y...', Array, NULL, NULL, NULL)
#1 /home/nydomain/public_html/application/libraries/Zend/Gdata/App.php(880): Zend_Gdata->performHttpRequest('GET', 'https://gdata.y...', Array)
#2 /home/nydomain/public_html/application/libraries/Zend/Gdata/App.php(768): Zend_Gdata_App->get('https://gdata.y...', NULL)
#3 /home/nydomain/public_html/application/libraries/Zend/Gdata/App.php(225): Zend_Gdata_App->importUrl('https://gdata.y...', 'Zend_Gdata_YouT...', NULL)
#4 /home/nydomain/public_html/application/libraries/Zend/Gdata.php(187): Zend_Gdata_App->getEntry('https://gdata.y...', 'Zend_Gdata_YouT...')
#5 /home/nydomain/public_html/application/libraries/Zend/Gdata/YouTube.php(293): Zend_Gdata->getEntry('https://gdata.y...', 'Zend_Gdata_YouT...')
#6 /home/nydomain/public_html/application/modules/Video/controllers/IndexController.php(995): Zend_Gdata_YouTube->getVideoEntry('Pr9S5vSlYOs')
#7 /home/nydomain/public_html/application/modules/Video/controllers/IndexController.php(257): Video_IndexController->handleInformation(1, 'Pr9S5vSlYOs')
#8 /home/nydomain/public_html/application/libraries/Zend/Controller/Action.php(516): Video_IndexController->createAction()
#9 /home/nydomain/public_html/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('createAction')
#10 /home/nydomain/public_html/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 /home/nydomain/public_html/application/modules/Core/Bootstrap.php(75): Zend_Controller_Front->dispatch()
#12 /home/nydomain/public_html/application/libraries/Engine/Application.php(160): Core_Bootstrap->run()
#13 /home/nydomain/public_html/application/index.php(205): Engine_Application->run()
#14 /home/nydomain/public_html/index.php(24): include('/home/nydomain/...')
#15 {main}

**Comment by smazurov** [comment]
this is a known issue and will be addressed in 4.8.9 which we're going to release soon, thanks for your report but we'll consolidate it with #44
