### ISSUE TITLE
Add Photo option is not working in Mobile and Add Music option is not showing in Mobile

### ISSUE THREAD

**Issue by Vaibhavagarwal0807** [SocialEngine/phpv4-issues#520]
Follow steps to reproduce this issue?
-------------------------------------------
1. Open "https://demo.socialengine.com" on your mobile device and login with your email id and password.
2. You can go to Member Home Page and Click on Status Box and Click on Add Photo link.
3. Select File option is missing because, Flash Player is missing error shown.
4. Also, Add Music option is not showing in mobile device but showing in Desktop.

**Comment by Khushboo016** [comment]
Hi @Vaibhavagarwal0807 , Flash Player is required to be able to upload images from SocialEngine site, so please make sure it is installed in your mobile browser.

Thanks!

**Comment by Vaibhavagarwal0807** [comment]
@Khushboo016, I have installed Flash Player in my mobile device but it is not working. 

Have you check "https://demo.socialengine.com" ?

**Comment by Khushboo016** [comment]
Hi @Vaibhavagarwal0807 , Yes, I tried to upload an image from my android device and I was able to do so, as you can see in the screenshot below, so, I suggest you to try in another mobile browser:
![i_was_able](https://cloud.githubusercontent.com/assets/18209340/21100664/5d1db9d2-c09b-11e6-98e8-641f5457d08a.png)



Thanks!

**Comment by PaloPepper** [comment]
Hi @Khushboo016, My users are not able to upload photos from their iPhones and do not want to download Flash Player. Is there a workaround to this issue? Any code or suggestions you can share? I need to get this fixed ASAP. 

Thank you in advance!

**Comment by Khushboo016** [comment]
Hi @PaloPepper , I tested the issue at my end by uploading a photo on SE PHP demo site from iPhone and I was able to do that, so, we suggest you to check the issue again at your end.

Thanks!

**Comment by PaloPepper** [comment]
Hi @Khushboo016, 
Q1.  Is it because you have flash installed on your iPhone? Some of my users do not have flash and do not want to download it. **The upload option "Select Your File" button is missing in mobile view.** 

Q2. Which flash app did you install? 

Thanks!

**Comment by Khushboo016** [comment]
Hi @PaloPepper , Photo can be uploaded via iPhone even when no Flash player is installed in it, as shown in below screenshots, it gives an option to choose a file to be uploaded:

![choose_file](https://cloud.githubusercontent.com/assets/18209340/21424167/f3d252fc-c866-11e6-9c02-08d539f30539.png)    ![photo_selected](https://cloud.githubusercontent.com/assets/18209340/21423936/b2af0e1a-c865-11e6-8d78-0dd44b4fb332.png)

Thanks!

**Comment by PaloPepper** [comment]
Hi @Khushboo016 , thank you for the images. I will forward this to my developer. 

Much appreciated!

**Comment by Vaibhavagarwal0807** [comment]
Hello SE Team,

I have checked again above issue on SE demo site in Ipad and it is not working fine. 

<img width="1440" alt="se_demo" src="https://cloud.githubusercontent.com/assets/11191902/21559873/bc1a1664-ce7a-11e6-9ab3-1e500fba15ad.png">

**Comment by Elshara** [comment]
Flash has been discontinued for two years. Time to get rid of it I think. Mobile phones shouldn't need to suffer with it. As it frequently crashes.
