### ISSUE TITLE
Community Ads Plugin Mobile Design issues..

### ISSUE THREAD

**Issue by rkrathor** [SocialEngine/phpv4-issues#521]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … The Create Ads page looks pretty fine for desktop? But for mobile its taking the full width even more than the desktop one. When designing according to mobile but I have to check for each and every device with and lots of media query to be written and whatever I written not working as I want.

What happens?
-------------
… The Design not at all supportive for any mobile device.

What were you expecting to happen?
----------------------------------
… I just wanted to know I can make that a mobile friendly design , without making lots of changes for each and every mobile device separately.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** … centos 

**SocialEngine PHP Version:** … 4.8.8.

There are some mobile design's full screenshots, how it looking design wise?
![screencapture-crezilla-ads-create-id-1-1481534977095](https://cloud.githubusercontent.com/assets/10502380/21094487/45360c7a-c07d-11e6-82f1-3292b8c38c11.png)
![screencapture-crezilla-ads-package-1481534953201](https://cloud.githubusercontent.com/assets/10502380/21094488/453a4290-c07d-11e6-8bfa-f84c1c5f6093.png)
![screencapture-crezilla-ads-create-id-1-1481535756727](https://cloud.githubusercontent.com/assets/10502380/21094567/875a7064-c07d-11e6-9d33-37cb6e816a24.png)

these are Desktop designs

![screencapture-crezilla-ads-create-id-1-1481535861954](https://cloud.githubusercontent.com/assets/10502380/21094611/c3ac9722-c07d-11e6-95db-94691bfa3080.png)

![screencapture-crezilla-ads-package-1481535931309](https://cloud.githubusercontent.com/assets/10502380/21094630/de220a1a-c07d-11e6-93dc-e22aae0123c6.png)

![screencapture-crezilla-ads-create-id-1-1481535961938](https://cloud.githubusercontent.com/assets/10502380/21094641/f1d7793c-c07d-11e6-8fe6-3d66ea7d118d.png)

**Comment by Khushboo016** [comment]
Hi @rkrathor , The screenshots you've attached show that this issue belongs to a third party plugin and is not an issue related to our core module of SE PHP, so, we suggest you to contact the respective developers of this plugin to assist you regarding this issue. For future perspective, we would like to let you know that this Github repository is meant for reporting any issues related to SE core module and the core plugins only, so, please do not report issues related to third party plugins here.

Thanks & Regards!

**Comment by rkrathor** [comment]
Hi,
I get whatever you said but I don't get when you say its not related to SE because its a social engine add on 
[community ad](https://www.socialengineaddons.com/socialengine-advertisements-community-ads-plugin)

**Comment by Khushboo016** [comment]
Hi @rkrathor , This repository is meant for reporting issues that belongs to or exists in core SE PHP and not for the issues existing in or belonging to any 3rd party plugins/addons. Hope you get my point here.

Thanks!

**Comment by rkrathor** [comment]
Yes mam,
 I got your point but just wanted to know is the socialengineaddons part of socialengine or not?

Thanks

**Comment by Khushboo016** [comment]
Hi @rkrathor, SocialEngine and SocialEngineAddons are different. We are SocialEngine and SocialEngineAddons is one of our third party developers who develop plugins for SocialEngine.

Thanks & Regards!

**Comment by Elshara** [comment]
It's confusing. Any third party developer who call themselves social engine add ons, or social engine pro company, social engine mods, etc, kind of brands themselves to seem like they hold official plugins, when in fact they do not. Responsive theme should take care of the problem you have with over sized widths.
