### ISSUE TITLE
Scaffold Paginator breaks CSS media queries

### ISSUE THREAD

**Issue by shivani2910** [SocialEngine/phpv4-issues#522]
Applies to SE 4.8.9.

**Steps to reproduce:**

1. Switch your site into development mode. Scaffold may serve cached style sheets otherwise.
2. Upload this large CSS file to your site: https://gist.github.com/rwetzlmayr/4de46a2090a28b7ade76. For illustration purposes I will use the `temporary` folder and the file name `fubar.css` in this issue report. You may use any other suitable folder and filename.  Note that this file includes media queries and contains more than 4000 selectors. 
3. Visit http://example.com/application/css.php?request=temporary%2Ffubar.css
4. The first line contains an `@import` statement referring to `/application/css.php?request=temporary%2Ffubar.css&pageStart=99860&pageEnd=102490`. Open that style sheet from http://example.com/application/css.php?request=temporary%2Ffubar.css&pageStart=99860&pageEnd=102490.
5. Notice that the imported CSS file does no longer frame the style rules with a media query and we now have a lot of global CSS rules which probably weren't intended for current output device. Also, there's a dangling right brace at the very end of that imported style sheet.

Root cause:

The `Paginator` module naively looks for right braces to find a segmentation breakpoint in `Paginator::_getPreviousSelectorEnd()`. This is not a valid assumptions as soon as media queries are allowed in style sheets.

Reported by:
https://github.com/SocialEngine/phpv4-issues/issues/214

**Comment by Elshara** [comment]
Just one typo can cause a whole string of problems. I generally like to keep CSS files short and sweet. Believe it or not, pages load quicker this way.
