### ISSUE TITLE
Social engine Website Dashboard error.

### ISSUE THREAD

**Issue by SpiritWolfie** [SocialEngine/phpv4-issues#523]
Greetings, I just saw the new update for SE, and when clicking on ether zend framework update or social engine upgrade package I am met with 

`{"error":true,"message":"User does not have access to this resource","code":"forbidden","statusCode":403}`

when clicking ether 

From: https://www.socialengine.com/account/dashboard

https://warehouse.socialengine.com/file/download/e568a872-59b9-4603-935a-27028934ca72?downloadToken=f88ea3d630a35faa56c923bae043b270

or 

https://warehouse.socialengine.com/file/download/bcb65b89-675c-4d4c-a1b8-5e75ad1270ff?downloadToken=d944e62be38294aa13cc798e3880ff5c

**Comment by Khushboo016** [comment]
Hi @SpiritWolfie , This issue sometimes arises because of caching. So, please clean your browser cache and then reattempt to download the latest upgrades and plugins, you would be able to do that.

Thanks!

**Comment by SpiritWolfie** [comment]
@Khushboo016 

Tried Ctrl+F5 tried flushing cache, Tried 3 browsers, same error. Issue is on your end not mine.

Other download links all around the internet work flawlessly. May I suggest google drive or something?

**Comment by Khushboo016** [comment]
Hi @SpiritWolfie , Thanks for reaching out!

Regarding "Tried Ctrl+F5 tried flushing cache, Tried 3 browsers, same error. Issue":
Some other clients also faced the same issue, but the issue resolved on cleaning the browser cache, so, please try again at your end and let us know if it do not resolves.

Thanks!

**Comment by SpiritWolfie** [comment]
@Khushboo016 
As I said in my above post I did clean the browser cache... I even used ATF cleaner to do it, I tried by hand on all 3 browsers, Loaded the browsers in safe mode and tried, uninstalled and reinstalled one of my browsers and got the same precise error.... I don't believe the problem is on my end.

**Comment by Khushboo016** [comment]
Hi @SpiritWolfie , Please send an email to us regarding this issue at support@socialengine.com and we'll check the issue at our end and will get back to you.

Thanks!

**Comment by Elshara** [comment]
Hope this got resolved.
