### ISSUE TITLE
placeholder for profile questions made

### ISSUE THREAD

**Issue by poeticjustice** [SocialEngine/phpv4-issues#524]
just wondering if any plans to add placeholders for profile questions made?

**Comment by Khushboo016** [comment]
Hi @poeticjustice, Currently we do not have any plans for adding placeholders in Profile Questions, but we've forwarded your suggestion to our development team for discussion regarding its implementation.

**Comment by poeticjustice** [comment]
Such a shame considering how the description placement looks silly when one initial enter email and password etc has descriptions below entry boxes and then when enter details in profile fields on question page, the description is above the box.... a placeholder would look nice

**Comment by Elshara** [comment]
What about tool tips?

**Comment by poeticjustice** [comment]
Tool tips are rubbish, have you ever hidden the tooltips with custom css, you notice how the fields and rows work.

if you hide a tooltip on say question Name .....

if you hide the tool tip, this is how that question appears in say the members section

George(answer)      Name:

rather than 
Name: George (answer)

it puts the answer before the question, this is if you hide the tooltip.

why would you hide the tooltip you may ask, well

If you have advance member , you will constantly see the tool tip if your that user of admin, seeing the tooltip on every user in advance members is annoying and looks stupid, exact same with the profile fields is shown on the members page,

you see a massive ongoing tooltip, saying
this is hidden, this is hidden, blah blah and looks soooo sloppy and disgusting, and when you see so many tool tips... totally confusing lol

**Comment by Elshara** [comment]
I see what you mean. Highly ineffective. Well perhaps if we had the
option to choose how the question displayed itself, as in name
description and choice fields, this could be resolved.

**Comment by Elshara** [comment]
You mentioned CSS conflict with tool tips. I guess there's no way to
actually change each class of CSS so you could hide each element
depending on what it is if you needed to hide a specific tool tip
message, and no way to hide the fact that it is hidden from the
browser. Even if you were able to.

**Comment by poeticjustice** [comment]
the signup form and process feels like the oldest part of social engine, old questions from before Instagram got big..... in another thread I mention how to create an Instagram specific field, but this shouldn't be me telling them how to do it, it should have been done ages ago.

The profile questions are soooo dated.

Tags should replace the multi select feature, soon as you click on something it should turn to a tag which you can delete, rather than hold Cntrl and select each.

Also should have ability to span it over pages, so page one is name etc

Then next page a dif section, next page another etc, just to break up the questions

**Comment by Elshara** [comment]
Yeah it just doesn't really make sense to me either. The whole system
needs a template over hall.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#31

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
