### ISSUE TITLE
'Friends online' window not displaying properly

### ISSUE THREAD

**Issue by xyzsimon** [SocialEngine/phpv4-issues#526]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … When I login to my account.  The "Friends Online" window displays improperly.  Refer to attached image.  

What were you expecting to happen?  For "Friends Online" to display properly. 
----------------------------------
…

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** … 

**SocialEngine PHP Version:** … SocialEngine PHP Advance  4.8.13

**Comment by Khushboo016** [comment]
Hi @xyzsimon, Please follow the steps mentioned in this KB article http://support.socialengine.com/php/customer/en/portal/articles/2170953-online-friends-are-not-being-shown-in-chat-bar?b_id=14386 to find out the cause of this issue and please let us know if you need our further assistance.

Thanks & Regards!

**Comment by xyzsimon** [comment]
Hi Khushboo016, 
![socialengine php friends online](https://cloud.githubusercontent.com/assets/16373524/21629216/10cdb31a-d1db-11e6-9b44-03add3027000.jpg)
Thanks for your reply.  

I have followed the instructions found in the reply link you sent me.  The problem is now intermitten.  During day hours, Pacfic Time,  'Frineds Online' appears properly on the right bottom corner of my page, however, when I 'Sign In' to my site in the evening 'Friend Online' appears in the middle section of my page as shown in the image attached.  

Simon

**Comment by Khushboo016** [comment]
Hi @xyzsimon , Please send an email to us for this issue at support@socialengine.com along with your site details, so we can check this issue at our end.

Thanks & Regards!

**Comment by Elshara** [comment]
This issue is not just with your social engine instance. I think over time, the online check for who is actually on the site times out.
