### ISSUE TITLE
Missing Translation

### ISSUE THREAD

**Issue by angelinfante** [SocialEngine/phpv4-issues#528]
What are the steps to reproduce this issue?
-------------------------------------------
1. Follow the Sign up process  until photo upload

What happens?
-------------
1. 'Save Photo' is not translated

What were you expecting to happen?
----------------------------------
/Users/angelinfante/Development/PHP/orientalisimo/application/modules/User/views/scripts/_formSignupImage.tpl should have the string 'Save Photo' translated like this

echo '<button name="done" id="done" type="submit" onClick="javascript:finishForm();">'.$this->translate('Save Photo').'</button>';

**Comment by Khushboo016** [comment]
Hi @angelinfante, Thanks for reporting this issue, we've added the phrase "Save Photo" in the list of translation issues and this issue will get fixed in near future releases.

Thanks & Regards!

**Comment by Elshara** [comment]
Looks good.
