### ISSUE TITLE
Deleted Members Posts Exists After Member Is Removed

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#529]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Sign up and post somewhere, forum, blog, group, any other module.
2. … Delete the member who posted in any module, forum, blog, group etc from admin panel
3. … Deleted members posts are still there, even the comments they made, the replies, their photos, and there's no way to recover a deleted members account because their unique ID still exists in the database

What happens?
-------------
… When spam bots join the website and try to ddos the database with frequent posting of utter nonsense, it is more than just seo that takes a hit. Deleted posts have to be done manually, and when you have thousands to get through plus the replies to existing posts you don't want to delete like comments and replies to a popular forum post, this task becomes next to impossible. Not only does their member ID still exist in the database, but also their posts as well. There is no way to bulk delete someone's content especially if deleted members content is harmful to the community. However the reverse is also true, there is no way to save deleted members content, if someone has left the website due to spam bots posting. So you can't just target all deleted members, because if a member left the website, they are classified as a deleted member as well, so it is not always a spam bot free solution to a growing problem on all social engine websites.

What were you expecting to happen?
----------------------------------
… To have a check box to check to ensure deleted members and their content stay deleted, and if a member leaves the website, to be classified under a different category entirely. To be able to ban members if need be, which would then have the option to do a soft ban, just suspend the profile, or a hard ban, delete all content. To be able to assign bulk actions automatically if someone is flagged for spamming the website. To be able to set up bulk actions manually if you wish to remove a certain amount of whatever someone has posted no matter what module it is. To be able to reinstate left member profiles, and suspended profiles, as well as bulk assign or bulk import profiles and export profiles from a site backup if necessary to restore the website based on trusted members and their content. To be able to block spam bots from joining the website, as the multiple step registration form plus captcha plus third party spam bot services, just isn't preventing them from mass attacking the sign up and sign in screen or any other page like the contact us page they can find with edit boxes present.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Something must be done about the problem social engine has when it comes to vulnerabilities in the sign up sign in area for members. I have noticed the developers from an existing social networking solution have joined with Social Engine, and I recall many vulnerabilities not just to protect spam bots, but also to limit functionality of members from being able to do bulk actions from said script developers which have recently jumped ship from phpfox and moved to Social Engine. I worry about the platform and its future, and I also worry about my community migrating to a completely different script if this issue does not get resolved. You know that Una is developing a social engine migration script for free to be able to port it into Dolphin pro. Which is also a free platform. Fix your script, or lose a customer.

What versions of software are you using?
----------------------------------------
**Operating System:** … Linux on server, Windows 10 personal

**SocialEngine PHP Version:** … 4.8.13

**Comment by Khushboo016** [comment]
Hi @Elshara, As we have also explained in the issue https://github.com/SocialEngine/phpv4-issues/issues/222 that if the content of deleted members is not retained, then various older posts which have comments/replies made by that deleted member would become quite confusing and non-understandable. So, keeping that point in mind, we opted to not delete the content of a deleted/past member of site.

Thanks!

**Comment by SpiritWolfie** [comment]
@Khushboo016 

There should be a option to delete members stuff fully, or to keep it

if someone made it a point to post something illegal and you delete them, instead of having to manually go though every little thing to find it, it would be lovely to have a option to "Opt" To delete it in full. Most other social platforms provide a option to keep/or remove someones content from your site in full.

Think if a spam bot managed to get in and made countless posts on your wall, forums, blogs, polls etc, (which they can do, i've seen it) the staff would then have to find every little area (and believe me its not that easy) and delete it one by one.

**Comment by Elshara** [comment]
That's the whole point of the problem here. The choice shouldn't be
made as a system change one size fits all here. It should be a plain
and simple, cut and dry solution for administrators to click a check
box per account that says, delete all posts by this member and or bulk
assign actions to all deleted members posts.
Unfortunately, if a left member had posts they wished to maintain, but
just not have a profile on the website, what you are envisioning here
just isn't happening. Some modules retain posts, others do not. If
someone creates a group and they leave the site, the group still
exists in the database, but not on the website. But their forum topics
and other comments they have made on posts still are maintained. And
there is no way to manage this left over junk that can never be
recovered, even if the member returns.
So you see, the discord happens based on content that cannot be backed
up here. There in lies the problem of deleted and left member
accounts. There is no suspension option in social engine. If you're
gone, you're ghost account remains in the database and there's not a
stinking thing you can do about it but delete every post manually
which in the case of spam bots, amounts to thousands of comments,
status updates, false friend requests, and pretty much any other
feature social engine uses on a daily basis to connect people
together.
This is not a fool proof situation here. Deleting the wrong database
table has severe consequences. You have to be well versed in mysql and
php just to be able to prune old content by left users. This is not
okay. As I recall, PHPfox has this problem to this very day. In fact
it's so bad in that script that left accounts are just classified as a
non recoverable user group. In social engine, you just see a right
mess if someone leaves or is deleted. I'm sorry but your solution
isn't working. If someone wanted to maintain their content, or
transfer it, they can't do that. If I joined a social engine website
right now and posted something, and then left, or was deleted,
everything I worked hard on would still be visible under deleted
member content. It would still clutter the database even if all the
posts weren't visible on the website. Who wants to see deleted members
posts if they are a bad member, and see ghost posts of a well liked or
perhaps a truly missed and beloved member of a social website.
This solution you have come up with, is just underdeveloped and
overstated to put it mildly. It needs serious work. Besides, who is
the we've opted for, comment, directed to? Your staff, or us
customers? It would appear we mean nothing at all, as creators and
paying members of social engine, if the latter is true.
However it would appear to both of us, that you don't really use
social engine PHP long term. Because you know what I find very
interesting, is that your cloud solution has no such problems what so
ever. But yet people give you a lot more money for a product you can't
even keep updated to modern web standards, both security wise and
administration compliant. If you refuse to consider features we work
well and truly hard to make sure you as a company listens to, then we
as your customers will move our business elsewhere. It is social rules
101. You can't make us stay with a broken, out dated, platform, to
which cannot be fixed without your cooperation. And as our lead
developer, for thousands of people, we expect results.
Get a grip, listen to what we have to say for just a moment, and do
your job. We're reporting a serious bug with how something we both
want, is not functioning and you are either too under paid or over
worked to see it.

**Comment by poeticjustice** [comment]
I understand what @khushboo016 means regarding posts get confusing.

That said the other day I had a user posting all other his wall, in forums, and various of modules that he could post, on walls of others etc.
It was found to a employee of a company that I'm competing with who doesn't have the social aspect with their buisiness. 

I logged in as this user and one by one deleted off his wall.

Then thought I'd just delete the user, deleted him then I found loads of posts still excisted in forums.

Problem then was , to other members it would appear I deleted this member to shut him up rather than resolve what was being said. As I rather resolving anything negative so users can see we are trying to help publicly, now it looks like I deleted this member and users don't know why I did.

I spent 3 hours cloning my site to then delete his entries on MySQL entries, just so I could test in a staging environment to make sure nothing went wrong, then redo it on the live server.

It would Be great when deleting a user, if a tick box option is present and says, do you want to delete all entries this user posted, with a warning saying past conversations may long make sense blah blah.

That would be awesome.

**Comment by Khushboo016** [comment]
Hi @Elshara, @SpiritWolfie, @poeticjustice, We have forwarded this suggestion to our development team for internal team discussion regarding the implementation of this feature.

Thanks!

**Comment by alimoosavi15** [comment]
Please continue the conversation in #222 . I'll close this one as it's a duplicate issue.
