### ISSUE TITLE
Translation Issue

### ISSUE THREAD

**Issue by JazzJane** [SocialEngine/phpv4-issues#53]
Hi, 

The translation doesn't reflect for the phrase highlighted in the below screenshot. Please check. 

http://dmymvgkp4fkjt.cloudfront.net/cdn/farfuture/-w8ebJcRY0sau9ToU7ZhxsGa304WVYxiWGhKSdizF_M/mtime:1432794689/sites/default/files/supportimgs/picture-1432794689-835-4513.jpg

Thanks .

**Comment by Anshuse** [comment]
Hello @jamesoclark ,

We've added this issue in our internal bug tracker and will resolve this in near future release.

Best Regards,
Anshu

**Comment by smazurov** [comment]
Fixed in [4.8.10](http://blog.socialengine.com/2016/01/20/socialengine-php-4-8-10-is-released/)
