### ISSUE TITLE
Images arent fetched (thumbnail) in link share

### ISSUE THREAD

**Issue by leandrotavaresrocha** [SocialEngine/phpv4-issues#530]
This is not a new issue to me. Several time when I try to share a link no image is fetched to create a link thumbnail. I have no idea why some links has thumbnails while others not. I already thought that this was due some missing opengraph or small images avaliable but couldnt confirm since I saw sites with opengraph that doesnt have any thumbnail in my SE community.

This is a bit frustating to some users that believe that the problem is in our website not in the link destiny, so to explain to my users I would like to know what is the reason of this issues and also suggest to SE development team an improvement in the code to allow a better image fetching.

I attached below a link that usually where SE usually doesnt fetch any image.

(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. Go to activity feed widget
2. Share the following link: https://www.catarse.me/rastro_de_cthulhu
3. Post this link once attached

What happens?
-------------
No image is fetched to create a link thumbnail

What were you expecting to happen?
----------------------------------
That a image from the several avaliable in the link is used as a thumbnail

Any logs, error output, etc?
----------------------------
No, there is no log or errors output.

Paste Log Here
```

Any other comments?
-------------------
...

What versions of software are you using?
----------------------------------------
**Operating System:** Windows 10

**SocialEngine PHP Version:** 4.8.13

**Comment by Khushboo016** [comment]
Hi @leandrotavaresrocha, As also mentioned in github issue https://github.com/SocialEngine/phpv4-issues/issues/141 we have plans of integration of iframely with SocialEngine in our near future release 4.9, so, this issue would not arise after that and if a similar issue arises after that, we'll look further into the issue.

Thanks!

**Comment by Elshara** [comment]
It's possible the type of file used in the image is not supported to be used as an image thumbnail.

**Comment by leandrotavaresrocha** [comment]
I already checked and is not a problem with the image. In the community someone said that this would be related with open graph from Facebook as if Social Engine recognize open graph also, but I checked and in the Facebook open graph debug everything work fine, only SE has this type of problem.

**Comment by Elshara** [comment]
Must be an internal coding error in social engine. It's too bad.
