### ISSUE TITLE
Updates of custome css file not reflecting.

### ISSUE THREAD

**Issue by rkrathor** [SocialEngine/phpv4-issues#531]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. I change the .css file, upload.
2. Change the System Mode back and fourth. 
3. Refresh the page , waited for few minute but I am not able to see the changes. even If I check file the changes can be seen (using filezilla or putty).

What happens?
1- Recently I have changed my hosting server to amazon. now strange things start happening, like these css file updates sometime see immediately some taking lots of time but now today its yet not reflect.

What were you expecting to happen?
Css changes should reflect immediately after I change system mode back and fourth.  

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** …Amazon Linux AMI 2016.09.1 (HVM)

**SocialEngine PHP Version:** … 4.8.8

![screenshot_3](https://cloud.githubusercontent.com/assets/10502380/21928366/62829676-d9b0-11e6-9dcc-9ac6ba185068.png)
![style](https://cloud.githubusercontent.com/assets/10502380/21928367/6285fa32-d9b0-11e6-9f35-fbc1a1ddefb6.png)

**Comment by Khushboo016** [comment]
Hi @rkrathor, Please make sure that after doing the changes in the CSS code of your site, you flush the server cache of your site and as well as clean the cache of your browser, so that the changes may get reflected.

Thanks & Regards!

**Comment by rkrathor** [comment]
Hi @khusboo016, Yes I do that everytime, As I mentioned that we have just change our hosting server, Earlier these steps was working fine.
Now today after 2 days when I checked I am able to see that one change today.
So is there any other way to do this? or A way by which I can check how much time it will take so will update accordingly because when this will be fully functional than every second will be count.
Please guide 
Thanks

**Comment by SpiritWolfie** [comment]
@rkrathor We're having this issue ourselves and are having to force it to load it instead of it loading normally, normally css changes will take affect a few hours unless you flush se and server cache, but we're having to manually force it in full...

**Comment by rkrathor** [comment]
Thanks @SpiritWolfie , 
1- Server cache you mean the hosting server?
2- How can manually be done this?

**Comment by SpiritWolfie** [comment]
@rkrathor 

I'll ask my coder how he does this and i'll post back

**Comment by rkrathor** [comment]
thanks @SpiritWolfie

**Comment by SpiritWolfie** [comment]
@rkrathor 
My coder got back to me, this is what he said

Here's the steps I use in my file, edited a bit for a wider audience. Note this only applies to plugin-specific CSS code. (not regular files like theme.css and customization.css for us)

1. Determine main.css file to be changed in /application/modules directory. (this will be plugin-specific)
2. Clear Paginator cache in /temporary/scaffold/application/themes/[your social engine theme]
3. Disable cache flags in /application/settings/scaffold.php.
4. Re-enable cache flags in /application/settings/scaffold.php.
5. To refresh browser cache, do a Ctrl-F5 on the affected page(s).
More specifically, this whole issue has to do with how CSS is cached on the server through frameworks like Paginator.
Also, if he's on AWS, he may be having a different set of issues if it uses it's own server-side caching of files. This may not work in such a situation.

To add, he may need to do this instead if it's set up on his web server: http://bertanguven.com/disable-caching-of-assets-in-apache
Unfortunately, I'm not too familar with Apache or how it's installed/located on all the different UNIX distributions, so I can't help much beyond that.
I deal with HP-UX on ksh. Seems like most UNIX distributions use csh and have different paths despite ksh and POSIX being the most flexible shells...

(I just copy and pasted)

**Comment by rkrathor** [comment]
Hi @SpiritWolfie thanks a lot with your help , this is actually a custome.css and I will try this and check.

thanks

**Comment by alimoosavi15** [comment]
@rkrathor If you put your site in development mode and load your site using hard refresh (CTRL + F5) after making CSS changes, you should see your file changes immediately.

**Comment by Elshara** [comment]
I wish task scheduler included a way to automatically refresh cached files at least once per every hour or so. That would make it ideal for situations like this.
