### ISSUE TITLE
Widget for admin to view only

### ISSUE THREAD

**Issue by poeticjustice** [SocialEngine/phpv4-issues#532]
Hi 

Is anyone able to give help or feedback regarding widgets being able to be viewed via Admin only on users profile page.

Example Profile Fields, this widget mimics the profile questions, depending on your site you may have sensitive data, but users may feel uneasy that users can see all their profile question answers.
I know you can hide it from this, but if the user themself see the data thats hidden, they may feel others can still see it.

is there a way to make this widget so only admin can view it.
On my site i have it set to approval, so i like making sure users filled out a form correctly, so i use this profile fields on their page, to vet the user essentially.

But i dont want users seeing someones info, i dont want users friends to see it, i do even want the user themself to know this info is on their page.

understand file is located here application/modules/User/widgets/profile-fields/Controller.php

and the code is  the following below, but what can i change to just render for admin/super admin levels only, but view it on a users profile page

<?php
/**
 * SocialEngine
 *
 * @category   Application_Core
 * @package    User
 * @copyright  Copyright 2006-2010 Webligo Developments
 * @license    http://www.socialengine.com/license/
 * @version    $Id: Controller.php 10189 2014-04-30 18:51:06Z andres $
 * @author     John
 */

/**
 * @category   Application_Core
 * @package    User
 * @copyright  Copyright 2006-2010 Webligo Developments
 * @license    http://www.socialengine.com/license/
 */
class User_Widget_ProfileFieldsController extends Engine_Content_Widget_Abstract
{
  public function indexAction()
  {
    // Don't render this if not authorized
    $viewer = Engine_Api::_()->user()->getViewer();
    if( !Engine_Api::_()->core()->hasSubject() ) {
      return $this->setNoRender();
    }

    // Get subject and check auth
    $subject = Engine_Api::_()->core()->getSubject('user');
    if( !$subject->authorization()->isAllowed($viewer, 'view') ) {
      return $this->setNoRender();
    }

    // Load fields view helpers
    $view = $this->view;
    $view->addHelperPath(APPLICATION_PATH . '/application/modules/Fields/View/Helper', 'Fields_View_Helper');

    // Values
    $this->view->fieldStructure = $fieldStructure = Engine_Api::_()->fields()->getFieldsStructurePartial($subject);
    if( count($fieldStructure) <= 1 ) { // @todo figure out right logic
      return $this->setNoRender();
    }
  }
}

**Comment by Khushboo016** [comment]
Hi @poeticjustice, There is no way to make the widgets viewable to Admin only in our core module, so, if you need it for your site, you can do code customization at your end to achieve this feature.

Thanks & Regards!

**Comment by poeticjustice** [comment]
That's a shame, I really wanted profile fields widget to be placed on users profile but only admin can see it, as I have a approval system to do it, when approving members I like to make sure data is provided correctly, and I have to do these approvals late at night to make sure no one sees other users profile fields as some fields contain sensitive data.
Ohhh well

Could you please check my other post out about a bug, it's being ignored https://github.com/SocialEngine/phpv4-issues/issues/536
@khushboo016

**Comment by poeticjustice** [comment]
Glad this has been marked down as enhancement.

Still trying to figure out how some widget are visible to users who are not friends with users.

As i set profiles so only friends can see their profile, ive found a few widgets are visible in the tab, where as some are not visible until they are friends.

This is why i thought there may be a code that i can edit in profile fields widget so Admin can only view.

Because when you chose to hide a question on profile, you get aload of tool tips saying, only visible to you and admin, and it looks so messy plus it also messes up the tables

Example, try hiding the tooltip with display none, and the answer is displayed befor the question lol

**Comment by Elshara** [comment]
A work around would be if social engine included admin permission level changes so that when someone puts a privacy setting to just me, admins can see it as well.

**Comment by gsf00001** [comment]
@Khushboo016 
-->Hi @poeticjustice, There is no way to make the widgets viewable to Admin only in our core module, so, if you need it for your site, you can do code customization at your end to achieve this feature.
Well, there may be 'no way' right now, but I don't understand why there can't be a way in the future (if the solution is code customization then it seems that the code customization could be an overall thing).  

There could be a setting for all widgets for this - and not only for ADMIN purposes, but for selection of which MLs should be allowed to view it.  There could be an ADMIN-panel system-wide default that ADMIN may override when dropping/editing widgets.

**Comment by Elshara** [comment]
Maybe Younet won't allow it at the moment.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#32

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
