### ISSUE TITLE
Hide widget in mobile

### ISSUE THREAD

**Issue by skylucrew** [SocialEngine/phpv4-issues#533]
In widget settings if I select "yes, hide in mobile", when I browse my website in a mobile phone the widget still appearing. I am using a responsive theme, this setting works only with the SE mobi plugin? I suppose it should work not just by using mobi SE but with any responsive theme, am I right?

**Comment by Khushboo016** [comment]
Hi @skylucrew, This setting is applicable only if you are using Mobi plugin on your site and the site is accessed in mobile browser with the help of Mobi plugin. So, if you are using a responsive theme, then this setting would not work and if you want it to work there also, so the theme needs to be customized accordingly.

Thanks!

**Comment by Elshara** [comment]
I think 4.9 will fix this problem as you can use the new social engine responsive theme with the mobile plugin without any issues. Although it would be nice to be able to upload and edit content using the mobile view without having to switch to desktop.
