### ISSUE TITLE
Is Social Medial like FB, Instagram and Twitter login worked with SE 4.8.8?

### ISSUE THREAD

**Issue by rkrathor** [SocialEngine/phpv4-issues#534]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. I want signup with social media like Facebook, LinkedIn and Twitter.
2. Save some of the main information into SE profile.
3. Fetch data like pic about me from Facebook and profile summary from linked, jobs description etc.

What happens?
-------------
…

What were you expecting to happen?
I want signup using social media and fetch data and update my socialengine profile?

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** … Amazon Linux AMI 2016.09.1 (HVM)

**SocialEngine PHP Version:** … 4.8.8

**Comment by Khushboo016** [comment]
Hi @rkrathor, 

Regarding "Is Social Medial like FB, Instagram and Twitter login worked with SE 4.8.8?":
Yes, the feature of social integration via Facebook, Twitter, and Janrain existed in SocialEngine 4.8.8 version. Settings for social integration via Instagram was not provided separately but was possible with the help of Janrain integration.

Thanks & Regards!

**Comment by rkrathor** [comment]
Hi @Khushboo016 thanks for you reply.

Sorry I typed Instagram accidently, By Instagram I want to know about LinkedIn integration.
Moreover my concern mainly here to get personal and professional information of user and saved in our database to use in our SE.

If this is possible , can you help me with any tutorial documentation?

Thanks

**Comment by Khushboo016** [comment]
Hi @rkrathor, Yes, the feature of social integration via LinkedIn was also possible in 4.8.8 with the help of Janrain integration. 

Regarding "Moreover my concern mainly here to get p":
The information fetched of users through use of APIs in case of social integration via Facebook, LinkedIn and Twitter is very small and limited info. And it seems that you want to get more information of users to be saved in your database, so, for that requirement you'll need to refer a developer who can assist you regarding this issue.

Thanks & Regards!

**Comment by rkrathor** [comment]
Hi,
Its been a tough task and I am still facing issue with this social media login.
So just for help , Is there a link or step by step guide to perform this Integration and profile signup using these social media.
I mean I tried the SE tutorial ot login via FB but the data or information don't actually stored in SE database.
Same the Janrain integration tutorial is also not enough to get the result.

So if anyone having a proper installation tutorial or can provide the steps that will be very helpful to me.

Thanks

**Comment by Elshara** [comment]
Try emailing janrain about it. Ask them what kind of data can be imported using their api.
