### ISSUE TITLE
Upgrade SE?

### ISSUE THREAD

**Issue by rkrathor** [SocialEngine/phpv4-issues#535]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What happens?
1- As we know there is new version of SE is live. We have slightly older version. We have to upgrade to new one but we have couple of questions to ask. 

1- What are the new changes that have come in 4.8.12 from 4.8.8?
2- As we have customize our SE engine, how much it can affect my current SE if I upgrade?
3- Is there any other way to upgrade so that I can keep my changes (design and functionality) and also can upgrade my SE?
4- What are the possibilities that I have to fully change or customize from the beginning if I upgrade to current version?
5- If I have to start from the beginning than is there a process I can follow to upgrade every time SE launch a new version because we all know new version always keep on coming? Because its a beginning and we can take a risk now instead of later.

Any other comments?
Please give your best suggestions.

What versions of software are you using?
----------------------------------------
**Operating System:** … Amazon Linux AMI 2016.09.1 (HVM)

**SocialEngine PHP Version:** … 4.8.8.

**Comment by SpiritWolfie** [comment]
I'd actually like to have a answer to this too as I have custom changes to SE (Such as font/color etc)

When SE gets upgraded how do we move this stuff over, what precisely do we need to do to keep our configurations but not mess with the update code itself? 

Also to OP, 4.9 is coming around the corner sometime soon I'd honestly just wait for that, thats going to be a HUGE update.

**Comment by rkrathor** [comment]
@SpiritWolfie yes As we know SE will keep on changing , so have to have a easy and batter process so that we can keep both new code and custom changes like design etc.

**Comment by SpiritWolfie** [comment]
@smazurov do you guys have a doc on this you could link or such?

Simply put we want to know what steps to take if we have custom code or custom code in our plugins.

**Comment by smazurov** [comment]
We have a [general upgrading](http://support.socialengine.com/php/customer/en/portal/articles/1666869-performing-upgrades?b_id=14386) doc, I let @DonnaScriptTechs know - shes responsible for keeping upgrade doc up to date.

Each release includes a detailed file changelog along with what changed in that file. For smaller releases you can certainly go through those and update files we've updated.

**Comment by alimoosavi15** [comment]
Themes are not included in the upgrade packages so installing upgrade packages won't effect the changes you've made to the themes, however, if you've made modifications to the core files, you'll lose those modifications. The solution is to keep the modifications is to compare your current files with the files in the latest upgrade package with softwares like WinMerge, keep a note of your modifications and re-add the modifications after installing the upgrade package.

Generally, keeping the core files untouched and using the extensibility feature of SocialEngine via plugins is recommended. If you would like to keep your SocialEngine up to date I suggest moving the modifications to stand-alone plugin(s) so upgrading won't be a difficult task when SocialEngine releases upgrades.

**Comment by Elshara** [comment]
When upgrading, all files are essentially overridden if you've made any changes to anything. Database changes remain partially intact depending on install folder of the update files. A solution to this would be an individual check box whether or not you want what files to be overridden when you upgrade.

**Comment by Elshara** [comment]
Another option would simply be to include a custom templates area where you can actually make changes to templates inside social engine itself, so you don't have to make file changes directly.
