### ISSUE TITLE
Subscription module With Paypal Cancels Immediately - Payment also does not go through immediately

### ISSUE THREAD

**Issue by dreamgeekcoder** [SocialEngine/phpv4-issues#537]
What are the steps to reproduce this issue?
-------------------------------------------
1. …Sign up on a monthly or weekly or 3 month paypal created subscription plan
2. …Cancel plan before end of subscription plan - say on the 10th of the month instead of day 30
3. … Paypal immediately issues cancel code and user is immediately dropped to "free" plan instead of on day 30.

Issue 2 - Immediate Paypal payment not happening
1. User subscribes to monthly subscription. 
2. Paypal generates subscription. 
3. Inital Payment does not happen till some time later in the next 24 hour period. 
4. Regardless of "Enable if member has an existing successful transaction, wait if this is their first." option, user is upgraded immediately even though payment has not successfully happened yet or previously. If payment fails on initial subscription, user remains upgraded forever as the Paypal API code is currently set to "unlimited amount of failures" on paypal payment processing.
5. Tie this into Issue 1 above and users are able to upgrade, get advanced features and cancel at anytime without ever paying a cent. My smart users have figured this out and are sharing that information. 

What happens?
-------------
… Paypal immediately issues cancel code and user is immediately dropped to "free" plan instead of on day 30. User has remaining 20 days, but doesn't get them. 

Users upgrades and never pay successfully, but remain upgraded. Can go on forever with the core settings.

What were you expecting to happen?
----------------------------------
…Paypal issues cancel subscription immediately. Code runs on day 30 and returns user to free plan

User is not upgraded until payment is completed successfully, unless they have already completed a transaction.

Any other comments?
-------------------
… This subscription module has never worked properly. I have 200+ subscriptions happening on my network and constant missed payments and no way to keep track of who has actually paid and who hasn't because of the issues above. This is my last attempt to work with support with serious flaws to your core product. If you want screenshots, more details etc.. please let me know. I know there are tons of complaints in this github - many are not valid or just complaints,  but I hope you will take this bug report seriously.

**Comment by Khushboo016** [comment]
Hi @dreamgeekcoder, Thanks for reporting the issues!

Regarding issue 1.
We would like to let you know that this bug is going to be fixed in our upcoming release 4.9, so, you will not face this in future versions.

Regarding issue 2.
We have forwarded this to our development team, so they would discuss it and hopefully it can be fixed in future versions of SocialEngine PHP.

Thanks & Regards!

**Comment by dreamgeekcoder** [comment]
I know this release is still several months off.. .Please let me know if you want any help with testing the edits... I lose money every day because of this bug and would be glad to help you get it sorted and working properly.

@Khushboo016

**Comment by Khushboo016** [comment]
Hi @dreamgeekcoder,
Regarding "Issue 2 - Immediate Paypal payment no":
We are sorry for any confusion, but we forgot to mention that this issue should be fixed by selecting the option "Wait until the gateway signals that the payment has completed successfully." against the field "Initial Subscription Status" from "Admin" > "Billing" > "Settings" section of your site. A new member will not be enabled unless until SocialEngine will receive gateway signals that the payment has completed successfully. So, please check this at your end.

Thanks!

**Comment by dreamgeekcoder** [comment]
@Khushboo016 as mentioned above... regardless of what setting is checked wait till payment, wait if previous payment, they are still upgraded immediately. This button does nothing as far as i can tell.

**Comment by Khushboo016** [comment]
Hi @dreamgeekcoder, 

Regarding "regardless of what setting is checked wait t":
We'll have to check this issue on your site, so, please open a support ticket for this issue from your SocialEngine account  along with your site details.

Thanks!

**Comment by Elshara** [comment]
Automatic member level adjustment based on confirmation of successful payment should be default behavior in social engine in real time. Perhaps a task scheduler entry could regulate this.

**Comment by DonnaScriptTechs** [comment]
Issue 1 was fixed in 4.9.0.

Issue 2 is still open in this other bug report https://github.com/SocialEngine/phpv4-issues/issues/629
