### ISSUE TITLE
Sharing and object generates a message without translation of the object

### ISSUE THREAD

**Issue by angelinfante** [SocialEngine/phpv4-issues#538]
What are the steps to reproduce this issue?
-------------------------------------------
1. Check that "event" has translation for an additional language, different of english
2. Switch to that language
2. Share an object, for example an event

What happens?
-------------
Check the post in user's wall, the word "event" is not translated.

What were you expecting to happen?
----------------------------------
The object should be displayed in the current language (not english)

Any other comments?
-------------------
Same problem has been observed in the notifications

**SocialEngine PHP Version:** 4.8.13

**Comment by Khushboo016** [comment]
Hi @angelinfante, If you are referring here to the translation of the word "event" in the phrases for action types like "X created a new event" etc as shown in the screenshot below, then we would like to let you know that this type of phrases have separate entries for them in the CSV files of the respective modules, and thus if you want to translate these phrases, you need to edit the corresponding language phrases for them in the Language Manager section. Like if you have to translate the phrase "X created a new event", so you need to search for the phrase "{item:$subject} created a new event:" in the Language Manager and to provide a translation for this phrase. I hope you understand my point here and let me know if I misunderstood your query here.

![created_event](https://cloud.githubusercontent.com/assets/18209340/22137773/151b7f8a-df03-11e6-83f9-531f56346b51.png)


Thanks & Regards!

**Comment by angelinfante** [comment]
I mean when an object has a link. It happens, for example, when the users shares an item. For example, in the screenshot, "event" is not translated to spanish. In the translations file, the string being translated is "{item:$subject} shared {item:$object}'s {var:$type}. {body:$body}"

![captura de pantalla 2017-01-23 a las 19 59 01](https://cloud.githubusercontent.com/assets/10200654/22218303/79f0d072-e1a6-11e6-8644-09c6e6ab6658.png)

**Comment by Khushboo016** [comment]
Hi @angelinfante, For translation of phrases for action types like "{item:$subject} shared {item:$object}'s {var:$type}. {body:$body}", you would need to add the translation for the phrase ""{item:$subject} shared {item:$object}'s {var:$type}. {body:$body}" and also need to add the translation of the object used as object is a dynamic entity here. For example in case when an event is shared, then event is the object, so, you need to add the translation for the word "event" too along with the translation of the phrase for the respective action type. You can see in the screenshot below that we are able to translate the phrase as required:

![phrase_translated](https://cloud.githubusercontent.com/assets/18209340/22237136/d4de45d0-e22f-11e6-9a76-4bdc84f9d014.png)
So, we suggest that if you are facing issue in translating any phrase on your site, then please open a support ticket to us from your SocialEngine account dashboard along with the details of your site, so we can check the issue on your site.

Thanks & Regards!

**Comment by angelinfante** [comment]
Thank you. I have both the phrase and the word "event" translated. I'm using Advanced events from Hire Experts. They told me they can't fix the issue because it depends on SE. I'll forward them this ticket and hope they fix it.

**Comment by Elshara** [comment]
Sounds like a good idea. Might be an issue in other third party providers as well.
