### ISSUE TITLE
Show error when file exceeds size limit when uploading music via Activity Feed

### ISSUE THREAD

**Issue by Vaibhavagarwal0807** [SocialEngine/phpv4-issues#539]
What are the steps to reproduce this issue?
-------------------------------------------
1. Go to SocialEngine demo: https://demo.socialengine.com/members/home
2. Try to upload music using Add Music link in Activity Feed.

![image](https://cloud.githubusercontent.com/assets/11191902/22065935/836af65e-ddb0-11e6-8ee5-f870e81a4865.png)

What happens?
-------------
After selecting the Music, loading image is shown continuously.

What were you expecting to happen?
----------------------------------
The music should be attached.

**Comment by Khushboo016** [comment]
Hi @Vaibhavagarwal0807 , I successfully uploaded a music file on SE demo site https://demo.socialengine.com using "Add Music" link in the Activity Feed as shown below in the screenshot. So, please make sure that the music file that you're trying to upload should not exceed 2Mb, as this is the maximum size defined for music file that can be uploaded on SE demo site. So, please try to upload a music file of less than 2Mb, you'll be able to do that and if you are facing any issue in uploading music on your SE site, then please send an email to us at support@socialengine.com along with your site details.

![uploaded_music_successfully](https://cloud.githubusercontent.com/assets/18209340/22136843/4a101846-defd-11e6-80a0-1d805a98a626.png)

**Comment by Vaibhavagarwal0807** [comment]
@Khushboo016 : I that case, if we can show some error to users that would be great because user might know this and we are also not showing somewhere that the limit is 2 Mb.
Its just a suggestion.

**Comment by Elshara** [comment]
Showing file size limits is standard on all file upload websites.

**Comment by RaymondBenc** [comment]
@Elshara yes, it sure is. We are working on getting the right error message across to the user.

**Comment by Elshara** [comment]
Awesome!
Something like:
"The file you uploaded is 5.49 mb. the server can except only 3.00 mb
per file. Your daily quota is 10.00 mb and the quota for all content
you have uploaded is 1.00 gb."
to the effect of explaining on the page itself what the limit is, and
what types of files are allowed, preferably using an html5 uploader,
would work well.
Up to you.

**Comment by Elshara** [comment]
IF you've uploaded multiple files, specifying which ones uploaded and
which ones were not uploaded would be ideal in the same way.

**Comment by gsf00001** [comment]
Also, another option is to display the limit(ations) prior to allowing the file selections since some Users are smart enough to think "uh-oh - this won't work - let me do something else prior to wasting time here".  Also, their available space in the ML Quota should be displayed.  Obviously these are considered approximates but informing me I can only upload a 3MB file tells me that a 1MB will work, a 2.5MB may work, and a 3.5MB won't (we can argue the will/may/won't another time :)

**Comment by Elshara** [comment]
Yeah that is what most file hosts do. Again, PHPFox has this feature built in.

**Comment by JonSimon93** [comment]
this would be a great feature

**Comment by Elshara** [comment]
I think it is being worked on.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#33

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
