### ISSUE TITLE
Member Count Not Reading Bug

### ISSUE THREAD

**Issue by meetgerry** [SocialEngine/phpv4-issues#54]
See video link for the issue:

https://www.youtube.com/watch?v=BMpZy5gUwyM

**Comment by Anshuse** [comment]
Hi @meetgerry ,

It seems to be a translation related issue on your site. You need to go to the ```application/languages/en/custom.csv``` file and search for below string:

```php
"%s members found."
```
And, verify that this string is correctly defined there. If the string is correctly defined and still you're facing the same issue then you may file a support ticket along with your site details, our support staff will help you out.

Best Regards,
Anshu

**Comment by meetgerry** [comment]
I am aware of that. What I was trying to highlight here is that whenever you guys release an update this issue keeps repeating.

I wonder what at your end stops you updating your files while you release updates.

**Comment by meetgerry** [comment]
![2015-06-401](https://cloud.githubusercontent.com/assets/8540750/8036945/a7325eca-0e03-11e5-8067-21f33ab6ded3.png)

**Comment by Anshuse** [comment]
Hello @meetgerry ,

This is not a known issue and we've not received the same issue from any other client and thus, this issue exists specifically in your installation. Therefore, you may do the above mentioned changes at your end to resolve this issue on your site.

Best Regards,
Anshu

**Comment by meetgerry** [comment]
Ok, thanks!
