### ISSUE TITLE
SocialEngine PHP, .js not loading or something stopped working - Errors attached 

### ISSUE THREAD

**Issue by Ben2522** [SocialEngine/phpv4-issues#540]
Certain functions on my social engine network aren't working, where as they were yesterday and I haven't changed anything.... i.e the wall plugin from Hire-experts doesn't load now and the mini menu buttons at the top don't work, albums dont work, ads dont work...

Here is a list I have identified:

1. Click on the notifications, message icons on the mini menu in the header. Nothing happens. It used to show notifications and messages. 
2. Wall plugin activity feed used to load the activity feed items, now it doesn't load. 
3. Albums page doesn't work at all. It says "sorry we're experiencing tech issues".
4. The community ads plugin/widget isn't displaying the ads. 
5. The like button on wall items doesn't do anything, where as it used to like the post. 
6. certain links in the admin panel don't do anything i.e community ads, view ads and nothing. But the links next to the buttons work. 

Steps taken after issues:
1. I have updated all the software to the most update versions 
2. reset the entire database to a time when it was working
3.disabled plugins to troubleshoot 

No joy. 

Here is the google inspect element errors on the main page. 

Any logs, error output, etc?
Failed to load resource: the server responded with a status of 404 (Not Found)
core.js:11 Uncaught ReferenceError: en4 is not defined
    at core.js:11
    at core.js:314
home:54 Uncaught ReferenceError: en4 is not defined
    at home:54
home:76 Uncaught ReferenceError: en4 is not defined
    at home:76
core.js:11 Uncaught ReferenceError: en4 is not defined
    at core.js:11
    at core.js:575
core.js?c=148:1806 Uncaught ReferenceError: en4 is not defined
    at core.js?c=148:1806
core.js:15 Uncaught ReferenceError: en4 is not defined
    at core.js:15
core.js?c=148:73 Uncaught ReferenceError: en4 is not defined
    at core.js?c=148:73
composer_date.js:4 Uncaught TypeError: Cannot read property 'Plugin' of undefined
    at composer_date.js:4
composer_photo.js?c=148:4 Uncaught TypeError: Cannot read property 'Plugin' of undefined
    at composer_photo.js?c=148:4
composer_link.js:3 Uncaught TypeError: Cannot read property 'Plugin' of undefined
    at composer_link.js:3
composer_tag.js:5 Uncaught TypeError: Cannot read property 'Plugin' of undefined
    at composer_tag.js:5
core.js:18 Uncaught TypeError: Cannot read property 'baseUrl' of undefined
    at core.js:18
    at core.js:204
composer_music.js:5 Uncaught TypeError: Cannot read property 'Plugin' of undefined
    at composer_music.js:5
composer_video.js:4 Uncaught TypeError: Cannot read property 'Plugin' of undefined
    at composer_video.js:4
composer_people.js:5 Uncaught TypeError: Cannot read property 'Plugin' of undefined
    at composer_people.js:5
fixWidthLightBox.js?c=148:1 Uncaught TypeError: Cannot read property 'runonce' of undefined
    at fixWidthLightBox.js?c=148:1
core.js?c=148:167 Uncaught TypeError: Cannot read property 'baseUrl' of undefined
    at core.js?c=148:167
core.js:15 Uncaught TypeError: Cannot read property 'baseUrl' of undefined
    at core.js:15
home:250 Uncaught TypeError: Cannot read property 'runonce' of undefined
    at home:250
home:843 Uncaught TypeError: Cannot read property 'runonce' of undefined
    at home:843
core.js?c=148:88 Uncaught TypeError: Cannot read property 'runonce' of undefined
    at Object.add (core.js?c=148:88)
    at home:1231
core.js?c=148:88 Uncaught TypeError: Cannot read property 'runonce' of undefined
    at Object.add (core.js?c=148:88)
    at home:1248
core.js?c=148:88 Uncaught TypeError: Cannot read property 'runonce' of undefined
    at Object.add (core.js?c=148:88)
    at home:1268
core.js?c=148:88 Uncaught TypeError: Cannot read property 'runonce' of undefined
    at Object.add (core.js?c=148:88)
    at home:1303
core.js?c=148:88 Uncaught TypeError: Cannot read property 'runonce' of undefined
    at Object.add (core.js?c=148:88)
    at home:1333
core.js?c=148:88 Uncaught TypeError: Cannot read property 'runonce' of undefined
    at Object.add (core.js?c=148:88)
    at home:1346
core.js?c=148:88 Uncaught TypeError: Cannot read property 'runonce' of undefined
    at Object.add (core.js?c=148:88)
    at home:1386
core.js?c=148:88 Uncaught TypeError: Cannot read property 'runonce' of undefined
    at Object.add (core.js?c=148:88)
    at home:1421
core.js?c=148:88 Uncaught TypeError: Cannot read property 'runonce' of undefined
    at Object.add (core.js?c=148:88)
    at home:1435

Any other comments?
Everything I have done mentioned above is about as far as my knowledge goes. Not a coder by any means. 

If you are able to help, I need it in a way that a beginner can understand and step by step if possible. 
…
**SocialEngine PHP Version:** …
I'm using the most up to date version of all software as of 19/01/2017

Thanks in advance.

**Comment by Khushboo016** [comment]
Hi @Ben2522 , Please send an email to us for this issue along with your site details at support@socialengine.com, so, we can check this issue.

Thanks!

**Comment by Ben2522** [comment]
Hi, I cant do that is you want to charge me $50 dollars for support.... I have already paid enough and feel that paying for support is going to keep burning a hole in my pocket. Unless your offering to fix for free. However. Thanks for your comment. Appreciated.

**Comment by Elshara** [comment]
Try removing plugin files and database entries and then reinstalling the plugins. When all entries are removed, update the core social engine installation and then add each plugin back one at a time. If social engine offered a maintenance tool, this wouldn't be an issue.

**Comment by Elshara** [comment]
Some third party providers like Hire Experts, Social Engine Add Ons, are known for having some issues over time with databases.
