### ISSUE TITLE
User can skip photo upload although it is required

### ISSUE THREAD

**Issue by angelinfante** [SocialEngine/phpv4-issues#542]
What are the steps to reproduce this issue?
-------------------------------------------
1. Open "Member Signup Process" configuration in the admin panel
2. In step "Add Your Photo" select "Yes, require users upload a photo upon signup."
3. Logout and sign up
4. When the system requests the photo upload, upload your photo

What happens?
-------------
The option "Skip" is displayed and the new member can click "skip" and continue without photo

What were you expecting to happen?
----------------------------------
"Skip" shouldn't be displayed because photo upload is a must

What versions of software are you using?
----------------------------------------
**Operating System:** Amazon Linux

**SocialEngine PHP Version:** 4.8.13

**Comment by Khushboo016** [comment]
Hi @angelinfante, We are not facing this issue at our end, so, if you are facing this issue at your end, then please open a support ticket to us from your SocialEngine account dashboard along with the details of your site or you can send us an email at support@socilaengine.com along with the details of your site, so we can check the issue on your site.

Thanks & Regards!

**Comment by Elshara** [comment]
It could be a problem with the requirement check.
