### ISSUE TITLE
Unable to upload any photo/pic.

### ISSUE THREAD

**Issue by rkrathor** [SocialEngine/phpv4-issues#543]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. On timeline->Click on Upload pic. after loder, its shows unable to upload photo.
2. On Add Album-> Giving error.

What happens?
I am not able to upload and pic even having size of 50-60KB only.

What were you expecting to happen?
It should take all files , I put upload upto 12MB in my php.ini.

Paste Log Here
2017-01-24T10:18:34+00:00 CRIT (2): 
Error Code: 6711aa
exception 'Engine_Image_Exception' with message 'No available adapter for image operations' in /var/www/html/application/libraries/Engine/Image.php:52
Stack trace:
#0 /var/www/html/application/modules/Album/Model/Photo.php(150): Engine_Image::factory()
#1 /var/www/html/application/modules/Album/controllers/IndexController.php(268): Album_Model_Photo->setPhoto(Array)
#2 /var/www/html/application/modules/Album/controllers/IndexController.php(172): Album_IndexController->uploadPhotoAction()
#3 /var/www/html/application/libraries/Zend/Controller/Action.php(516): Album_IndexController->uploadAction()
#4 /var/www/html/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('uploadAction')
#5 /var/www/html/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#6 /var/www/html/application/modules/Core/Bootstrap.php(83): Zend_Controller_Front->dispatch()
#7 /var/www/html/application/libraries/Engine/Application.php(160): Core_Bootstrap->run()
#8 /var/www/html/application/index.php(211): Engine_Application->run()
#9 /var/www/html/index.php(24): include('/var/www/html/a...')
#10 {main}

Any other comments?

It was working perfectly fine , I don't know what I am missing here..

What versions of software are you using?
----------------------------------------
**Operating System:** … Amazon Linux AMI 2016.09.1 (HVM)

**SocialEngine PHP Version:** … 4.8.8

![unable to upload](https://cloud.githubusercontent.com/assets/10502380/22243430/50a568b6-e24d-11e6-96e6-fe2db84dc43c.png)

**Comment by alimoosavi15** [comment]
I was not able to reproduce this issue on our demo site and from the error log you posted, it seems your server is missing one or more SocialEngine requirements so please make sure your server has all [SocialEngine requirements](https://support.socialengine.com/php/customer/portal/articles/1649350-socialengine-requirements). If you need any further help, please contact us via support@socialengine.com and we'll investigate the issue in your site.

**Comment by Elshara** [comment]
Try reinstalling in a private directory or sub domain to see if it is your installation of social engine causing the problem. If so, just update the files.
