### ISSUE TITLE
Please can someone look into issue #536 seems to be ignored!

### ISSUE THREAD

**Issue by poeticjustice** [SocialEngine/phpv4-issues#544]
Can someone please please please please address issue #536 

Im seeing no response, but newer threads have been address and had various replies in them!!!!

**Comment by poeticjustice** [comment]
Ive made a video for this no, where can i send it without being ignored? @smazurov  @jamesoclark @Khushboo016 @alimoosavi15 @RaymondBenc @alimoosavi15 @cgenevier

**Comment by DonnaScriptTechs** [comment]
Hello,

Thank you for posting.

We don't ignore any issues posted. Your issue will be checked by our staff as they go down the list. You can link a video in the original bug report. As this is a duplicated issue, I'll close this one. Please keep any correspondence to the original report so that our team doesn't get slowed with duplicates.

Thank you.

**Comment by poeticjustice** [comment]
It was only duplicated @DonnaScriptTechs because people were getting response to posts after my post, and based on this, it was seen as my original post was being ignored

**Comment by DonnaScriptTechs** [comment]
It is not. We need to test on the same device. I notice though that you are not using our current version. I am not sure if it is related to you using a previous version. Current is 4.8.13. However, someone will check your report. I would but my local won't work on my iPhone.

**Comment by poeticjustice** [comment]
this bug hasnt been reported as a fix for 4.8.13 and believe its not known.
It would be very irresponsible of me to update to 4.8.13 until i have tested all my plugins on my staging server etc.

It seems to be on apple devices.

Its a shame social engine demo, doesnt demontrate all the field options in their demo, as i could have pointed this out much soon

**Comment by Elshara** [comment]
I can confirm random or spiratic  updates to issues sometimes by social engine. But they get addressed usually.
