### ISSUE TITLE
First page not showing correctly of admin.

### ISSUE THREAD

**Issue by rkrathor** [SocialEngine/phpv4-issues#546]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. when I clear cookies of browser , I reopen my local website.
2. I found everypage working accept admin home page.

What happens?
-------------
See the screenshot nothing working on that.

What were you expecting to happen?
It should work normally.

Any other comments?
I check all setting cache and everything.
I don't know why only one page not working.

What versions of software are you using?
----------------------------------------
**Operating System:** … local-xampp on windows 10.

**SocialEngine PHP Version:** … 4.8.8

![localhost-admin](https://cloud.githubusercontent.com/assets/10502380/22463743/528d473e-e7d9-11e6-955e-7b107b9e201a.png)

**Comment by poeticjustice** [comment]
I had this issue with xampp and similiar programs, they were so unreliable, that i just went for actual hosting environment with specilists

**Comment by rkrathor** [comment]
Hi @poeticjustice I don't know it happen suddenly earlier it was working correctly.
Actual hosting environment in local, kind of tough task for me.

Thanks

**Comment by Elshara** [comment]
Try clearing browser cache.
