### ISSUE TITLE
Feature request - required fields asterisk 

### ISSUE THREAD

**Issue by poeticjustice** [SocialEngine/phpv4-issues#548]
Just wondered if any plans to add required fields asterisks.

When looking at social engine signup form and having required fields.

It literally seems so dated not to have a required fields asterisk (we are in the year 2017)

Some users sign up, and leave certain fields blank because, obviously no asterisks next to fields which is basically industry standard for a required field, even 50 year olds understand this.
Instead an error message for each field only after submitting.
but when you have loads of fields, this equals loads of error messages saying fill out this that this that

Really baffled how this hasnt been brought up or looked into

**Comment by Khushboo016** [comment]
Hi @poeticjustice, Thanks for your suggestion! We have noted it down at our end for internal team discussion regarding its implementation.

Thanks & Regards!

**Comment by poeticjustice** [comment]
Awesome :) i tried custom css but it wasn't having any of it

**Comment by GabryNet** [comment]
Very good idea ... i also had this problems with most of the users when they want to register ... they don;t have any clue which from fields they have to fill or they can skip ... thank you for your suggestion !

**Comment by poeticjustice** [comment]
exactly, i have a load of users who keep emailing me saying, i dont want to put that info in mandatory, because they auto assume everything is mandatory lol

**Comment by SpiritWolfie** [comment]
this is why I put [Optional] in my description for each field >.>

**Comment by gsf00001** [comment]
@SpiritWolfie Duh - why didn't I think of that (Optional in Desc).  That's a fantastic idea - thank you for it.  That's a great temp (actually, probably permanent) workaround.  I didn't realize I could do that for the default fields.  Thanks very much :)

**Comment by poeticjustice** [comment]
@SpiritWolfie tbf Placeholders would be best to say optional than description.

Social Engine has had for years a major flaw regards to description, when first signing up the Description is below the entry field boxes for email, password etc.... just like any normal site.

When actually filling in information, the description is now above the entry box, as many general public are use to a below description, i have found many to incorrectly fill out information, as the entry field is not in line with the question.

Plus even i opted for this "Optional " in my description. that doesn't cover mandatory.

it would look like this, and this is how silly it would look, especially when all sites have asterisks  


Name:                  Description saying Mandatory
                             ______Field entry________________

Middle name      Description saying Optional
                             ______Field entry________________

Surname              Description saying Mandatory
                             ______Field entry________________



doing this, you would have to use optional and mandatory as a description which is sooooo silly, especially when the description field is above the field of entry........... looks sooooo tacky

**Comment by Elshara** [comment]
I agree. We need to just get rid of the description place holder altogether. Make it a tool tip if a user hovers over it. I wish we could organize fields so required information is what a user fills out first, then could skip the rest if desired.

**Comment by poeticjustice** [comment]
instead of asterisks for required fields, the outline of the fields could be coloured on signup
Just idea but, i truely believe asteriks should be present

**Comment by Elshara** [comment]
Me two. I think it would provide a better standard.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#34

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
