### ISSUE TITLE
Facebook Integration

### ISSUE THREAD

**Issue by rkrathor** [SocialEngine/phpv4-issues#549]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. Go to http:// test.crezilla.com
2. Go to http://test.crezilla.com/login
3. Click on facebook Icon. 
4- Try login using  u- open_nxxrrqt_user@tfbnw.net pw- crezilla_test.
5- First time there will be a facebook popup will come and ask for permission and all like you have seen most of the time whenever you choose facebook login but in my page second time it straight away going to signup page even I clear all cookies and all.

What happens?
1- Only first time pop come for facebook login but second time it don't.
2- There is no information coming after login which I want to put in my website.

What were you expecting to happen?
1- There is must be a pop come if user is not yet login with there fb account or there is no fb account already open in other TAB.
2- Secondly there must be some information come and user must be able to login from facebook.
3- Facebook people also saying whatever you showing in screencast not enough to check us.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
1- There is a link for how to integrate Facebook in socialengine and I have did all the steps but still unable to find, how it will work for me like how after permission page of facebook how all information will come on socialengine and how I will able to use those information to fill user information in our application.
2- Can any one give me a step by step guide to how I will able to take information from facebook and use then into my application to signup and fill user basic information.

What versions of software are you using?
----------------------------------------
**Operating System:** … 4.8.8.

**SocialEngine PHP Version:** … Amazon Linux AMI  (HVM).

Link for the video.

https://drive.google.com/file/d/0B7Kez-aI-fhTbnE0bnVnSHF1cjg/view?usp=sharing

**Comment by DonnaScriptTechs** [comment]
Hi @rkrathor , 

We had updated our Facebook tutorial a few months ago, http://support.socialengine.com/php/customer/portal/articles/1796979-admin-panel---settings-&amp;gt;-facebook-integration

When updating, I went through the entire process and got approved by Facebook for the app. Have you followed our tutorial? There is also a link in the tutorial for Facebook's instructions on how to make the video for them. 

Please double check our tutorial and follow each step as you create your app. Perhaps a step was missed?

**Comment by rkrathor** [comment]
Hi @DonnaScriptTechs thanks for reply ,
That was beautiful tutorial and I followed that step by step, but I don't know what happening , I mean , I missing any coding part that I should do or I don't know why Its come to the signup page with no information after facebook permission popup page.
I have sent you the google drive link that I am sharing with facebook as well , following with the description that present in SE tutorial.

Feedback From Your Last Submission (Yesterday at 4:12am)
Your screencast doesn't show how this permission is used in your app, and we weren't able to reproduce the permission on our end either. Please upload a new screencast and update your submission notes before you resubmit. Learn more about making and submitting a screencast. 

I think first a user must signup to our social engine application using facebook login.
than they will consider my review , may be they are not able to see facebook integration working on my application.

**Comment by Khushboo016** [comment]
Hi @rkrathor, After reading this "I think first a user must signup to our social eng", it seems to me that you are missing or not following properly the steps for creating test users for testing your Facebook app. These steps have been clearly described under "Testing your App" section of this tutorial http://support.socialengine.com/php/customer/portal/articles/1796979-admin-panel---settings-&amp;gt;-facebook-integration . 

So, please make sure that you have specified valid test users in the steps to test your app for various Facebook permissions that you are submitting for approval to Facebook team. That is you should define a test user in the steps to test your app of a Facebook permission, only when the permission is working for that test user. For example, you should specify a new test user (who have never login-ed on the site previously) in the steps to test your Facebook app for "user_birthday" permission, while you should specify a test user who already has his account created on your site using Facebook login option in case of steps to test your app for "publish_action" permission. That is the test users mentioned for a particular permission should be such that Facebook team can check that permission's use in your app with the use of test user mentioned.

Hope this would help and if you still face issues in approval of your Facebook app, then you can open a support ticket for this issue from your SocialEngine account and we'll look into this issue.

Thanks & Regards!

**Comment by rkrathor** [comment]
Hi @Khushboo016 ,

I have followed whatever listed in the tutorial and exactly the same way, but I don't know if anything I have to check in the code of SE because sometime FB permission page don't popup and it redirect directly to the signup page with no information.
![test_users](https://cloud.githubusercontent.com/assets/10502380/22816450/232296c8-ef88-11e6-8f09-b053d45bdfa9.png)

**Comment by Elshara** [comment]
Just send your app for approval again in Facebook. It isn't you, it's them. This used to be a feature included by default in Facebook apps.

**Comment by DonnaScriptTechs** [comment]
Were you able to resolve this @rkrathor ? If not, please send a ticket to our support as we can't reproduce an issue in 4.9.1. You would need active support.
