### ISSUE TITLE
Profile Image Trim

### ISSUE THREAD

**Issue by meetgerry** [SocialEngine/phpv4-issues#55]
Currently only the profile image thumbnail has the option to trim to square.

All images dimension of the profile picture while uploaded should have the option to be trimmed into square dimension.

As it looks very unprofessional when the thumbnail is square and all other profile images in other parts of the site is as per the uploaded file dimension.

**Comment by Anshuse** [comment]
Helo @meetgerry ,

Apologies for the delayed response.

We've reported this suggestion at our end and will take appropriate action over this.

Best Regards,
Anshu

**Comment by meetgerry** [comment]
Curious to know if this being flagged for any action as I see this closed without being flagged.

**Comment by meetgerry** [comment]
Surprising why nobody wanted to write a one line reply to the above?

**Comment by shivani2910** [comment]
@meetgerry: we had added this suggestion to our features list that is discussed internally among our team. We can not confirm that we'll be able to add this feature but yes, we'll discuss about the possibilities with our development team. If we'll decide to work on this, we'll open the thread and let you know about the same. Thanks.
