### ISSUE TITLE
Payment gateway supported in SE?

### ISSUE THREAD

**Issue by rkrathor** [SocialEngine/phpv4-issues#550]
Hi,
I was just want to know how many types of payment gateways are supported by SE?
In current I can only two (2checkout and paypal) , So what if I want some other payment gateway to use?

What versions of software are you using?
----------------------------------------
**Operating System:** … Amazon Linux AMI  (HVM).

**SocialEngine PHP Version:** … 4.8.8

**Comment by smazurov** [comment]
Those are the only 2 supported, there is several available gateways in the marketplace.

**Comment by rkrathor** [comment]
Hi,
Why this is closed?
I didn't get answer for this.
 So what if I want some other payment gateway to use?
It means if I want to use any other payment gateway than is there any way or tutorial to do that?.

Please let other also help me here may be someone did this with there application.

Thanks

**Comment by smazurov** [comment]
Because this is not an issue as it relates to core SocialEngine PHP v4. If you wish to discuss/bring up general concerns please do so in the community or blog comments, thanks!

**Comment by rkrathor** [comment]
Hi @smazurov , According to me its a core SE question because we talking about the payment gateway that can be used in SE.
If you saying this is not than can you suggest or help me with those community or blog comments where I can post for these kind of help?

Thanks

**Comment by shivani2910** [comment]
Hi @rkrathor, if there are any topics where you need help from other SE PHP owners/admins or discuss things in general related to platform, you can do that on our community website: http://community.onsocialengine.com/

Thanks & Regards,
Shivani

**Comment by rkrathor** [comment]
Hi @shivani2910 thanks , I checked out this website earlier also it give me a message "Please request an invitation to join our community." every time I try to sign in.
Can you help me here?

thanks

**Comment by Elshara** [comment]
Simple answer. You need a third party plugin to add other gateways. I recommend Radcodes for this.
