### ISSUE TITLE
[Suggestion] Community team.

### ISSUE THREAD

**Issue by SpiritWolfie** [SocialEngine/phpv4-issues#551]
I had suggested this to @DonnaScriptTechs 

So I will suggest it here

I honestly believe SE would do great with a group of community leaders who fiddle with Lots and have blooming/growing  community who can test stuff and communicate with each other, I.E Hey Furgather I found this bug, could you test it on your end? sure, Hey Starlight.net ya the same thing is happening to me, lets report this to Donna or something and get a git hub (or better) up

This would cost SE zero dollars, would provide no security or legal risk, and only one or however many staff you decide to join us, you could personally send out invitations to certain community leaders, I would also offer to join and provide my experience in this stuff.

Heck if you guys don't have the time and I have your blessing I will personally set this up and we can have Donna join us, she can choose to communicate or just watch, but this would allow us the leaders to agree or disagree on what things SE needs or needs to be fixed that is affecting our community/or causing them to leave our websites. I was thinking something like Slack or equivalent for the hanging out spot.

Let me know what you think.

(Its not uncommon for a company or creators of something to do stuff like this, Riot games has the wrench man program, FF14 has the mentors program, and so fourth)

**Comment by leandrotavaresrocha** [comment]
I like your idea and already suggest something similar sometimes ago.

I think that a community team would improve the bug check process, but this will depend mainly from the community admins time to envolve this project.

**Comment by Elshara** [comment]
I'd also be interested in participating in something like this. I like the idea as well. I think that we should get other companies involved in an ambassador program of sorts to test out each others products to give suggestions and feedback about each in turn, to help them grow. Personally I think Boonex or Jamroom could be a start, maybe even Oxwall or Wordpress for references to modern web code in practice. Get a team of core developers on board from different areas of experties uniting for a common goal.

**Comment by DonnaScriptTechs** [comment]
Hi everyone,

Thanks for your feedback and contribution. Would you please open this at our community at https://community.onsocialengine.com where we can all discuss this further? This issue tracker is for script bugs and script features. We don't want to lose this discussion though, so we would like for one of you to please feel free to open the discussion at our community.

I'll close this bug but feel free to add a comment with a link to the post at our community when you open one.

**Comment by Elshara** [comment]
I'd be honored to help out in any way I can.

**Comment by Elshara** [comment]
I can't sign in to there. Sorry about that.

**Comment by DonnaScriptTechs** [comment]
If you have a paid license, please contact our support and we'll send you an invite to it. I don't want you to post your email here and that's the only way I can get an invite to you.

**Comment by DonnaScriptTechs** [comment]
If you don't have a paid license, you could go to my site at forum.scripttechs.com and we could interact there.

**Comment by Elshara** [comment]
See you there.

**Comment by DonnaScriptTechs** [comment]
If you mean my site, I will be there after work. :)

**Comment by Elshara** [comment]
Cool. Hope work goes well for you.

**Comment by gsf00001** [comment]
I don't see this on community.onsocialengine.com.  Did I miss it (if so, please provide a link). 

This is a great idea.  I'd be happy to be a part of this as well - even though I'm no expert yet.  I wish some 3rd-Party Devs did this sort of thing too for their Plugins.

**Comment by Elshara** [comment]
I didn't post it there yet. I can't seem to sign up.

**Comment by DonnaScriptTechs** [comment]
Only licensed clients have access to our community. To gain access, log into your account and send us a ticket asking for an invite please. We are working on making it easier for licensed clients to gain access though. 

As for the thread, no one had created it yesterday. One of you is welcome to or make it at my site if you are not allowed access to our SE community.
