### ISSUE TITLE
Payment-Gateway : Zend_Json_Exception' with message Decoding failed

### ISSUE THREAD

**Issue by rkrathor** [SocialEngine/phpv4-issues#552]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. http://test.crezilla.com/admin/payment/gateway
2. Here I am seeing error rather than two payment gate like paypal and 2checkout.
see pg-error.png
What happens?
I want to configure payment gateway but seeing error instead of gate to manage.

What were you expecting to happen?
There must be two gateway to manage payment mode it should be like screenshot_3.png

Any logs, error output, etc?
----------------------------
2017-02-09T09:24:49+00:00 CRIT (2): 
Error Code: f2e75e
exception 'Zend_Json_Exception' with message 'Decoding failed: Syntax error' in /var/www/html/application/libraries/Zend/Json.php:93
Stack trace:
#0 /var/www/html/application/libraries/Engine/Db/Table.php(214): Zend_Json::decode('\xE0\x108xV\x02\x10!\x07\xBC(\xA9\xD4\xF7\xA4...')
#1 /var/www/html/application/modules/Payment/Model/DbTable/Gateways.php(90): Engine_Db_Table->_unserializeColumns(Array)
#2 /var/www/html/application/libraries/Zend/Db/Table/Abstract.php(1390): Payment_Model_DbTable_Gateways->_fetch(Object(Zend_Db_Table_Select))
#3 /var/www/html/application/libraries/Zend/Paginator/Adapter/DbTableSelect.php(46): Zend_Db_Table_Abstract->fetchAll(Object(Zend_Db_Table_Select))
#4 /var/www/html/application/libraries/Zend/Paginator.php(797): Zend_Paginator_Adapter_DbTableSelect->getItems(0, 10)
#5 /var/www/html/application/libraries/Zend/Paginator.php(626): Zend_Paginator->getItemsByPage(1)
#6 /var/www/html/application/libraries/Zend/Paginator.php(1118): Zend_Paginator->getCurrentItems()
#7 /var/www/html/application/libraries/Zend/Paginator.php(862): Zend_Paginator->_createPages(NULL)
#8 /var/www/html/application/libraries/Zend/View/Helper/PaginationControl.php(119): Zend_Paginator->getPages(NULL)
#9 [internal function]: Zend_View_Helper_PaginationControl->paginationControl(Object(Zend_Paginator))
#10 /var/www/html/application/libraries/Zend/View/Abstract.php(350): call_user_func_array(Array, Array)
#11 /var/www/html/application/modules/Payment/views/scripts/admin-gateway/index.tpl(48): Zend_View_Abstract->__call('paginationContr...', Array)
#12 /var/www/html/application/modules/Payment/views/scripts/admin-gateway/index.tpl(48): Zend_View->paginationControl(Object(Zend_Paginator))
#13 /var/www/html/application/libraries/Zend/View.php(108): include('/var/www/html/a...')
#14 /var/www/html/application/libraries/Zend/View/Abstract.php(890): Zend_View->_run('/var/www/html/a...')
#15 /var/www/html/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(900): Zend_View_Abstract->render('admin-gateway/i...')
#16 /var/www/html/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(921): Zend_Controller_Action_Helper_ViewRenderer->renderScript('admin-gateway/i...', NULL)
#17 /var/www/html/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(960): Zend_Controller_Action_Helper_ViewRenderer->render()
#18 /var/www/html/application/libraries/Zend/Controller/Action/HelperBroker.php(277): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#19 /var/www/html/application/libraries/Zend/Controller/Action.php(527): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#20 /var/www/html/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('indexAction')
#21 /var/www/html/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#22 /var/www/html/application/modules/Core/Bootstrap.php(83): Zend_Controller_Front->dispatch()
#23 /var/www/html/application/libraries/Engine/Application.php(160): Core_Bootstrap->run()
#24 /var/www/html/application/index.php(211): Engine_Application->run()
#25 /var/www/html/index.php(24): include('/var/www/html/a...')
#26 {main}
```
Paste Log Here
```

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** … amazone Linux

**SocialEngine PHP Version:** … 4.8.8.

![pg-error](https://cloud.githubusercontent.com/assets/10502380/22778609/8c681b86-eedd-11e6-8fb4-4a5298cd628e.png)

![screenshot_3](https://cloud.githubusercontent.com/assets/10502380/22778670/cc317758-eedd-11e6-9eb3-c36238f97095.png)

**Comment by Khushboo016** [comment]
HI @rkrathor, Please open a support ticket for this issue from your SocialEngine account or you can send us an email for this issue at support@socialengine.com and we'll look into this issue.

Thanks & Regards!

**Comment by Elshara** [comment]
Mine seems to work okay.
