### ISSUE TITLE
[Feature Request] Question Type Instagram

### ISSUE THREAD

**Issue by angelinfante** [SocialEngine/phpv4-issues#554]
It would be nice to have a question type "Instagram" that builds the link to the Instagram profile from the Instagram user name if http://www.instagram.com/ is not explicitly informed by the member.

Instagram is as famous as twitter and Facebook today and deserves a specific field type.

**Comment by poeticjustice** [comment]
This is easy to do @angelinfante 

Ill leave a comment tomorrow on how to do this :)

**Comment by poeticjustice** [comment]
@angelinfante I know how to do this :D

**Comment by angelinfante** [comment]
@poeticjustice can it be done via configuration?

**Comment by poeticjustice** [comment]
Need to make a few files then just add 5 lines of code to and existing file, I made it once for a client in the past but for every social media i.e. Vimeo YouTube Pinterest etc, if you can dm on GitHub feel free to message me, shame SE haven't added it tho because it's sooooo easy to do

**Comment by Khushboo016** [comment]
Hi @angelinfante, Thanks for your suggestion, we've added this suggestion at our end for internal team discussion.

Thanks!

**Comment by poeticjustice** [comment]
Best advice give is goto 
/application/modules/Fields/View/Helper
copy the twitter file then rename the copied version as FieldInstagram 
Edit this file changing words FieldTwitter only, to FieldInstagram
then for the two web addresses change Twitter to Instagram

then goto /application/modules/Fields/Form/Element

Copy Twitter.php and rename the copy Instagram.php , then edit the file replacing any words saying twitter, renaming to Instagram
example class Fields_Form_Element_Twitter extends Engine_Form_Element_Text
rename to class Fields_Form_Element_Instagram extends Engine_Form_Element_Text

then goto /application/modules/Fields/settings

Open Fields.php (make backup first)
 you will see these, just add -Instagram above -Twitter
Nickname
-First Name
-Last Name
-Gender
-Birthday
-About Me
-Websites
-Instagram
-Twitter
-Facebook
-AIM

then further down
 Below //Communications and above Twitter, insert this

'Instagram' => array(
      'base' => 'text',
      'label' => 'Instagram',
      'category' => 'specific',
      'helper' => 'fieldInstagram',
    ),


You will have no errors, it will appear in specific section of profile questions, it takes litrally 5 minutes to do, and it really baffles me, that it hasnt been done in the past, especially as instagram is more powerful that twitter and AIM lol

**Comment by Elshara** [comment]
Cool.

**Comment by angelinfante** [comment]
@poeticjustice your solution works like a charm

**Comment by poeticjustice** [comment]
Ohhh it sure does doesn't it :)

How easy was it? Yet SE haven't done that themselves in future updates which is very sad!

**Comment by Elshara** [comment]
Yeah works here two.
