### ISSUE TITLE
ADMIN MLs for Admin Panel access

### ISSUE THREAD

**Issue by gsf00001** [SocialEngine/phpv4-issues#557]
Just like providing various functions to Users based on ML, it would be helpful to do the same for ADMINS.  There are many instances where Access Panel is needed, but you want to limit who has access to what (which plugins, which tabs and/or settings for a plugin).  This is obviously not a simple Yes/No for each menu item in Admin Panel, but would have to allow Devs to tie into this for flexibilty within their Plugins.

**Comment by Elshara** [comment]
Good idea. Control what admin actions member levels can host.

**Comment by Khushboo016** [comment]
Hi @gsf00001, Thanks for your suggestion, we have noted this at our end for internal team discussion regarding its implementation in future versions.

Thanks & Regards!

**Comment by Elshara** [comment]
Cool!
