### ISSUE TITLE
XSS vulnerability in FlowPlayer

### ISSUE THREAD

**Issue by cgcb** [SocialEngine/phpv4-issues#56]
The version of Flowplayer in SE 4.8.8 and earlier has multiple XSS vulnerabilities. Additionally, the packged version 3.1.5 is very old. The most recent version resolves these vulnerabilities and many other bugs.

The current version is 3.2.18, and can be downloaded at https://releases.flowplayer.org/flowplayer/flowplayer-3.2.18.zip

It may be advantage for Webligo to implement the HTML5 version of their player instead, which is available at https://releases.flowplayer.org/6.0.1/flowplayer-6.0.1.zip

In any case, Apple rates these defects as critical.

**Comment by Anshuse** [comment]
Hello @cgcb ,

We've reported this issue at our end for our internal team discussion over this.

Best Regards,
Anshu

**Comment by smazurov** [comment]
Fixed in [4.8.10](http://blog.socialengine.com/2016/01/20/socialengine-php-4-8-10-is-released/)
