### ISSUE TITLE
Social Engine Link Filter

### ISSUE THREAD

**Issue by leandrotavaresrocha** [SocialEngine/phpv4-issues#560]
Hello,

I am facing a problem with some bad users that share links to pirate and malware websites. 

Social Engine doesnt have actually a way to block links to a piracy or malware website and I need to remove manually each link. A feature that allow us as admin to block and blacklist websites would be a great addition for security and also community development.

I know that there is a way to use the bad word list to block names, but it is not so good since the link still be shared.

**Comment by Elshara** [comment]
Have you tried using wild card filters in censored words? Go to spam banning tools to set this up.
I also agree bad link domains could be useful. It would also be nice to be able to be automatically reported if any such censored words gets used as they are posted.

**Comment by leandrotavaresrocha** [comment]
I made a test and the censored words work fine with plain text, but not links. When I share a link using the link share feature from activity feed the link to the bad website still point to there.

I really don't know what to do, I work with some publishers and I don't like when someone share a link to a piracy website. Worst when someone share links to a malware website or one of those links that redirect to several others like adfly and similar.

**Comment by Elshara** [comment]
And there's no way to edit the post Without deleting it?

**Comment by Khushboo016** [comment]
Hi @leandrotavaresrocha, We have added your suggestion to be able to block links to websites at our end for internal team discussion.

Hi @Elshara, Editing of status posts would be possible in 4.9.

Thanks & Regards!

**Comment by Elshara** [comment]
Awesome! I'd say things are moving forward.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#39

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
