### ISSUE TITLE
Bug When Enabling Captcha For Member Comments

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#561]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Go to settings, spam and banning tools.
2. … Select yes for the integration of captcha on comments.
3. … Go to activity feed, or a post page on site and try to comment.

What happens?
-------------
… The comments window will not load no matter how many times you click it.

What were you expecting to happen?
----------------------------------
… The comments window to pop up with a captcha form. Configurable by member level for who can see captchas and who is exempt.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Captchas should also be present when creating a new post, and replying to forum discussions. Per personal preference. Captcha should be upgraded to version 2 of the Google API or alternatively use another captcha integration service.

What versions of software are you using?
----------------------------------------
**Operating System:** … Linux server Windows 10 personal

**SocialEngine PHP Version:** … 4.8.13

**Comment by Khushboo016** [comment]
Hi @Elshara, The issue seems to be related to your specific installation, so, we suggest you open a support ticket for this issue along with your site details from your SocialEngine account, so we can check it on your site.

Thanks!

**Comment by Elshara** [comment]
Thanks for checking into it. I thought it could be due to something on
this end but wasn't sure.
