### ISSUE TITLE
Positive Error Messages

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#562]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Do an action which results in an error. For example, adding a space to your profile address on sign up.
2. … Read the error message. Notice how generic, boring and how lacking of personality it is?
3. … Imagine being a new member who isn't sure on what to do next? Especially if the error message is hidden in plain sight?

What happens?
-------------
… The error messages you receive throughout the website which are user error generated, not script side or server side, make people discouraged from repeating the action they are trying to perform.

What were you expecting to happen?
----------------------------------
… For error messages to be interesting enough, that instead of an error, it transforms into a guideline, so it doesn't appear as if a user is facing a software limitation. Instead, the message should be full of tips, encouraging users on how they can better participate, by doing what they are already trying to do a different way, therefore encouraging them to try new things, and come back to do what they feel most comfortable with.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Generic software error messages, should be something scripted to be a thing of the past. Our future depends on working with technology, not just adapting it to our needs and have it throw an error if we can't work with it to do something a programmer never allowed it to do. Presently, people get very frustrated the first time if when they think an action has completed using technology, and it hasn't, even after following the steps they think they did to the best of their ability, we should be more helpful and less ridiculing to people who wish to enjoy a fluid user experience. It isn't just our brand name online which should benefit from doing business this way, but also your typical user who comes across something for the first time, should be encouraged to add some personality in to what they are there to do. Customizing error messages, is already possible using the language editor. But you have to customize them so much, just to make the user understand how to do the action they want to do, in a way the software can except. That is progress.

What versions of software are you using?
----------------------------------------
**Operating System:** … Linux for server. Windows 10 for personal.

**SocialEngine PHP Version:** … 4.8.13

**Comment by Khushboo016** [comment]
Hi @Elshara, Thanks for your good suggestion for making error messages being displayed at various places in an SE PHP site to be more significant and user-friendly, we've added this at our end and will work on this in future.

Thanks & Regards!

**Comment by Elshara** [comment]
You're welcome. Thank you.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#40

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
