### ISSUE TITLE
Communication Of On Site Actions Through RSS

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#563]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … No ability to subscribe to member activity.
2. … No ability to subscribe to event, group or site activity.
3. … No ability to subscribe to your own activity.

What happens?
-------------
… Receiving updates based on what you comment hardly classifies as staying socially aware especially as an administrator of what is going on in real time via email. I had to open up a Twitter account, install the RSS plugin from Radcodes, pay for customization of said plugin just to be able to see if new members sign up, feed it through Twitter Feed, just to be able to look at Twitter to be able to be notified about what my own account was sending out based on what was happening notification wise with public activity on site. I then had to somehow find a way to feed my twitter page to my email by subscribing to its RSS widget and then piping it through feed burner just to be able to get notifications based on what someone is doing, another expense. Twitter Feed has since discontinued its service, leaving me once again in the same position as if I never bought the Radcodes module. Because I actually had the Twitter page notifying people of what was going on, people cared to follow me there just so they could receive on site notifications through a public filter. Now you tell me how in this day in age, that is fair, when social engine is pretty far from social. On Site notifications does not currently have a subscription feature for anything anyone does. While I'm on the subject, you can't unsubscribe from what you do get notifications about, such as when someone likes your comments or an item you have liked, or has commented on something you posted, or something you posted on that someone else shared. Speaking of shared activity, all the share feature does in select times it does appear in the activity feed, is spam it to your wall, which isn't helpful at all. Talk about isolated from the rest of the world. There's another problem that is related to this, in that you can't subscribe from any emails social engine gives you, which is the only software platform of its kind that does not have required by law unsubscribe links in the footer of all emails, regardless of whether or not you are actually a member of said site. Social platforms like PHPFox and Dolphin are way ahead of you here. And that is just the tip of the ice burg if you think this covers the issue in its entirety.

What were you expecting to happen?
----------------------------------
… To be able to have proper subscription based notifications set up based on automatic user action, or a button someone can click on which is site wide apart of the core product, which lets you individually select what types of posts you wish to be notified about. Be it a comment thread, a particular members posts, if a new member signs up, if a new activity is posted site wide. Anything which is remotely social to engage new and existing members alike so the website can actually gain real traffic statistics, and not hang in the 10 millionth spot due to severe server slow response times, speed limitations, high page loads causing temporary errors due to too many javascript and css files loading at once. You name it, social engine needs it fixed. A brand new template engine would be a start.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Social engine does not currently represent itself as a social anything. It's more like an unfinished blog, with separate categories for what is allowed to be posted by anyone, and what isn't. It can't even be considered a forum, which is one step up from a blog, because of the lack of communicative options available to you notification wise. I think it is time social engine become more social, and less isolated from the rest of the world.

What versions of software are you using?
----------------------------------------
**Operating System:** … Linux Server. Windows 10 Personal.

**SocialEngine PHP Version:** … 4.8.13

**Comment by Khushboo016** [comment]
Hi @Elshara, Thanks for your suggestion! We have added this at our end for internal team discussion regarding its implementation in SE core module.

Thanks & Regards!

**Comment by Elshara** [comment]
You're welcome. Thank you.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#41

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
