### ISSUE TITLE
Wordpress/BBpress/Buddypress Importer

### ISSUE THREAD

**Issue by leandrotavaresrocha** [SocialEngine/phpv4-issues#564]
Recently Social Engine released a PHPFox Importer and I would like to suggest a new importer to allow import information from wordpress based social networks that use bbpress and also buddypress.

Between the free alternatives buddypress is without any doubt the most used, however there is no "bridge" that allow us to import information from those types of websites without lost several good content. I, by example, have around 26k of posts in an old social network that used Social Engine, however I couldnt transfer all those content because it would need require a huge job. Until now no third party developer showed interest in to develop this bridge.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#42

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
