### ISSUE TITLE
Specific Profile Questions - How to make them!!!!!!!

### ISSUE THREAD

**Issue by poeticjustice** [SocialEngine/phpv4-issues#565]
Now im raising this because it was asked recently and instead of being marked down as enhancement, it was just closed.

Social Engine im doing the work for you now, incase your current team actually don't know how to add it, company may have changed hands and therefor clueless how to add specific questions, so let me help.

This example is making Instagram a specific question..... why AIM is still on there is beyond me lol
Instagram is by far more popular, and more popular than twitter which lets be honest is dying and used as customer support now.

this really shouldnt even be discussed, but instead implemented asap as it takes like 5 mins to do

Below Social Engine is a clear guide how to make it possible, you could do this for tumblr, pintrest, bloglovin, endless possibilities 

/application/modules/Fields/View/Helper

copy the twitter file then rename the copied version as FieldInstagram
Edit this file changing words FieldTwitter only, to FieldInstagram
then for the two web addresses change Twitter to Instagram

then goto /application/modules/Fields/Form/Element

Copy Twitter.php and rename the copy Instagram.php , then edit the file replacing any words saying twitter, renaming to Instagram
example class Fields_Form_Element_Twitter extends Engine_Form_Element_Text
rename to class Fields_Form_Element_Instagram extends Engine_Form_Element_Text

then goto /application/modules/Fields/settings

Open Fields.php (make backup first)
you will see these, just add -Instagram above -Twitter
Nickname
-First Name
-Last Name
-Gender
-Birthday
-About Me
-Websites
-Instagram
-Twitter
-Facebook
-AIM

then further down
Below //Communications and above Twitter, insert this

'Instagram' => array(
'base' => 'text',
'label' => 'Instagram',
'category' => 'specific',
'helper' => 'fieldInstagram',
),

You will have no errors, it will appear in specific section of profile questions, it takes litrally 5 minutes to do, and it really baffles me, that it hasnt been done in the past, especially as instagram is more powerful that twitter and AIM lol

**Comment by DonnaScriptTechs** [comment]
Hi,

When you mention that you made a report before and it was closed, would you kindly link to the one you had made so that we can check it? It would be very helpful.

You can also add profile questions without editing source files. http://support.socialengine.com/php/customer/portal/articles/1644307-admin-panel---settings-&amp;gt;-profile-questions in case that helps.

**Comment by poeticjustice** [comment]
Someone raised it before and it was closed, not een marked as enhancement 
https://github.com/SocialEngine/phpv4-issues/issues/554

Yea i know you can make profile questions, but like specific questions example
twitter specific is predefined so you just add the ID handle

I know if you made a question using the website question so it creates a hyperlink, and your question is instagram, users will auto assume you just add the instagram handle like the twitter handle..... no they would have to add the whole link

it literally takes 5 mins to make the files, and i have even explained how to make it.

**Comment by Elshara** [comment]
Thanks for your suggestion.
Social Engine does not currently have plans to implement this feature or subsequent related features at this time.

**Comment by DonnaScriptTechs** [comment]
https://github.com/SocialEngine/phpv4-issues/issues/594 keeping that open as it has more options. This is the same and we are working on implementing.
