### ISSUE TITLE
default notifications settings improvement

### ISSUE THREAD

**Issue by poeticjustice** [SocialEngine/phpv4-issues#566]
Now this needs to be addressed.

default notifications needs to be updated asap.
If anyone knows a way around this please help like i have in past.

Now, when setting up, i turned off all notifications. personally i believe this should be default set to all off until enabled.

I had a plugin that i changed because the plugin was out dated and buggy.

When i installed the new plugin the default notifications were enabled for this, then i found out this made every old user have notifications for this plugin, which is soooooo annoying.
I have no way of turning off these notifications unless i log into 600 profiles one by one unticking, which i dont want to do...... and i dont want users to to be incharge of these notification settings because
A/ it shows the names for the plugins (which cannot be changed in language editor)
B/ i dont want to send loads of pointless emails to users saying, you got a like from BOB, there will be a point where someone hits spam and screws me over and adds my domain to a spam list which can be difficult to get off.

Why is there not a button to overide default notifications for excisting  users?

does anyone know a way to do this automatically in the MYsql database

Is there a way to set it to disable when installing the plugins?

Please help as this is an important area, Spam and emails are very important, there needs to be an overiding button to change all users. not just apply to new users, because when adding to the site with new features or plugins , this cause massive headache

**Comment by poeticjustice** [comment]
@DonnaScriptTechs love to hear your thoughts on this or any help,

**Comment by poeticjustice** [comment]
I actually cant stress enough at an option to override all existing profiles, we really need to consider the effect placing a new network on a spam list, this can come from default email notifications for pointless things, there is only so much time until someome hits SPAM.

NEED and overiding feature for this pronto

**Comment by gsf00001** [comment]
@poeticjustice 
Just another example of something that seems like it should be included, but isn't that requires a 3rd-Party customization (I actually asked my primary Dev to quote something similar - and will eventually do it if funds are remaining after other more pressing needs).  This is one of those things I wish there was an easy way to group-sponsor (i.e. if 5 or 10 or whatever# needed this, the specs could be agreed upon and the cost would probably be similar or or even less than a typical Plugin).

**Comment by DonnaScriptTechs** [comment]
Hi and sorry for my late response. I must have missed the notification of your pinging me in it. 

This actually is something I have on my sites using another script as a plugin though as that one doesn't have the setting either. I think this would be a handy feature. If not in the core script, then as a third party plugin. 

Regarding crowd funding. Clients can easily start a thread at our community and title it Crowd Fund - (topic).

(topic) would be the name of the thing you want to get funding together for. Then, you would ping some developers in the thread to get them looking at it. See how many are interested in doing the project under a crowd funding option. Go from there. This was done at the other script by some clients and seemed to work fine in that forum. Perhaps it will work fine in our community as well. Noting that not many participate in crowd funding these days for some reason.

Good luck with this. If you do it, you might consider including the option to also allow unsubscribing from the newsletters too as I don't find that option available in my site I just migrated to SE. However, I don't use internal newsletters, I prefer Mailchimp and letting my users choose to subscribe via a block I place on the side. I was mentioning the option as you might get more interested in crowd funding this if that option is also included.

**Comment by poeticjustice** [comment]
developers will not touch anything to do with core.
So i doubt 3rd party developers would do this, would be great as core feature @DonnaScriptTechs 

I have to now log in manually to over 700 accounts, to each profile manually change, log out, log in as admin, then login as user, change for them, then log out, log in as admin, then login as user, repeating process......

this is really time consuming and bad in my opinion :(

**Comment by Elshara** [comment]
Subscribe unsubscribe feature would take care of the problem and I know based on my issue, SE will be considering it soon in core product.
Default notifications should be something a user gets asked perhaps as a welcome pop up on the main page when they log in for the first time. All you have to do is create a menu item and point them to the right place.

**Comment by gsf00001** [comment]
@poeticjustice 
==>"developers will not touch anything to do with core."
Some will (in fact, I have 2 different Devs that each performed a change to Core that I obviously must add-back into Core each time it's updated)

But, the Dev that was willing to do a customization of this function was not going to affect core.  Many things (such as items in this discussion) seem to be core, and often should be implemented at that level (preferably by SE).  But, this particular functionality was going to be developed outside of Core - all settings and processes could easily be implemented without changing core.  

@Elshara 
==>"Subscribe unsubscribe feature would take care of the problem ..."
Yes, part of this can be implemented that way, but other aspects (depending on the needs of Site-ADMIN) will require more.  For example, there are some notifications I wish that the User could enable/disable, and many others I don't even want them to have a choice or even see it in a list of 'options' (some of these I would force enabled, others I would force disabled - there are some notifications I don't want anyone to get, others I want to be sure everyone does get).  There are also times I would like to temporarily override the User's settings.

**Comment by Elshara** [comment]
This is why my thoughts on the matter are so seriously misunderstood.
Everything you want to do can be achieved. I just don't understand how
one person says yes, another says no, nobody is putting clients first
in any situation and I have a feeling the more who continue to not do
so, is just going to eventually seek to want to because of how their
business must change as others realize it is important.
What would fix the problem is getting more customization per module.
And in order to do so, work on individual modules must be possible.

**Comment by JonSimon93** [comment]
I think all notifications should should be be disabled by default unless the user wants to opt for the notifications, not the other way round and all notifications enabled, plus the ability to delete some notifications that you catergorically do not want sent

**Comment by Elshara** [comment]
We have the option to do so already for new users. But not to be able
to bulk edit actions or options for all users in this way.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#44

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
