### ISSUE TITLE
Boonex Importer

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#568]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Boonex software including Dolphin Pro, Trident, Rocket Chat and their various names, is software which works great for some things, but not for others. Their communities though loyal, wish sometimes to have an easier alternative to what they currently are using.
2. … An import script for Boonex products does not yet exist, making their migration options impossible, as none currently exist out there.
3. … Should social engine developers find a way to provide one, they will bring better business here.

What happens?
-------------
… For various reasons, Boonex is an isolated community. IT has add ons, but like Ning, the support for Boonex products remains in house.

What were you expecting to happen?
----------------------------------
… Boonex to have data migration options if needed.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Tons of communities use Boonex to power their social community networking websites. If an alternative option existed where they could keep their website and its users, and still grow from it, social engine would be a perfect alternative for this type of activity.

What versions of software are you using?
----------------------------------------
**Operating System:** … web server

**SocialEngine PHP Version:** … 4.8.13

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#45

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
