### ISSUE TITLE
Jamroom Importer

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#569]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Jamroom is also an isolated community like Ning and Boonex looking for ways to better their community networks hosted there.
2. … There is no current way for Jamroom users to import their data into anything, and recent development suggests Jamroom developers are looking for ways to export communities hosted by other platforms such as Social Engine, PHPFox and Ning among many others.
3. … A Jamroom import script will help social engine to empower websites created on the platform.

What happens?
-------------
… Jamroom can be a bit difficult to use for some people, and be expensive to use. No developers has currently made an import script possible for Jamroom to any other platform, and if social engine developers do this, it would be the first of its kind.

What were you expecting to happen?
----------------------------------
… Given the large database of Jamroom users out there, as well as it being a direct competitor to a market share of social engine, as it is the only other provider out there providing a full Ning archive import, a Jamroom import to social engine seems ideal.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… This will help social engine grow.

What versions of software are you using?
----------------------------------------
**Operating System:** … web server

**SocialEngine PHP Version:** … 4.8.13

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#46

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
