### ISSUE TITLE
XSS vulnerability in Open Flash Chart

### ISSUE THREAD

**Issue by cgcb** [SocialEngine/phpv4-issues#57]
Open Flash Chart has an XSS vulnerability:

https://your-site.org/externals/open-flash-chart/open-flash-chart.swf?get-data=%28function%28%29{alert%28document.domain%29}%29%28%29

Apple lists this as a critical security vulnerability.

**Comment by Anshuse** [comment]
Hello @cgcb ,

We've reported this issue at our end for our internal team discussion over this.

Best Regards,
Anshu

**Comment by happycoder1337** [comment]
I just confirmed this also, which apple service did you use to discover this flaw cgcb?

**Comment by cgcb** [comment]
This was confirmed by an Apple internal security audit. Apple is a customer of ours.

Cheers!

Chris Brewer
President

Zavoodi, Inc.
Digital Creation for Web, Mobile & Social

P: 859-653-2749
W: zavoodi.com <http://zavoodi.com/> and SocialNatives.com <http://socialnatives.com/>

Check out our software for SocialEngine <http://www.socialengine.com/customize/se4/developer?dev_id=1450>

**Comment by happycoder1337** [comment]
what do you develop for apple? don't they have tons of developers?

**Comment by cgcb** [comment]
We develop highly customized advocacy platforms inside Apple and other organizations based on the SocialEngine platform. Indeed, Apple has many talented developers. We bring a unique perspective and deep social network experience to the engagement.

**Comment by smazurov** [comment]
@cgcb would you be interested in talking with us directly? We're always looking to work and get feedback from our integrators and developers, email me directly at stepan@socialengine.com

**Comment by happycoder1337** [comment]
sounds exciting, I hope I can check out some of your work or maybe even collaborate with you. =)

**Comment by meetgerry** [comment]
I heard Apple is developing its own Social Networking site, would that be based on SocialEngine CM?

**Comment by cgcb** [comment]
No, it isn't. 

Chris Brewer
Zavoodi Inc. 
http://zavoodi.com

859-653-2749

**Comment by meetgerry** [comment]
Thanks for your reply.

**Comment by happycoder1337** [comment]
ibook? lol

**Comment by Elshara** [comment]
Thanks for reporting this.
