### ISSUE TITLE
Oxwall Importer

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#570]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Oxwall is a completely free alternative for the most part minus their add ons, to social engine. However, it is one of the largest free alternatives there are to community software offering social network capabilities.
2. … It powers platforms which build upon it to charge a fee such as Skadate.
3. … There are no currently available import scripts for this platform to transfer data anywhere.

What happens?
-------------
… People build their websites on Oxwall only to find its feature set to be more limiting out of the box than other places such as social engine.

What were you expecting to happen?
----------------------------------
… An import script to be developed for Oxwall users to social engine.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… A lot of people would jump on the chance to import their websites here if they could.

What versions of software are you using?
----------------------------------------
**Operating System:** … web server

**SocialEngine PHP Version:** … 4.8.13

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#47

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
