### ISSUE TITLE
Elgg Importer

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#571]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Communities using Elgg have few support options available.
2. … It can be used as a networking feature, however it also powers many blog sites.
3. … If there is any group of users out there who could really benefit from an upgrade, the Elgg platform is ideal.

What happens?
-------------
… Elgg is very limiting in terms of features. Yet because it is partially based on a fremium software solution, a huge portion of users depend on it to power their websites. Over time, Elgg becomes limiting as their vision grows, and to accompany it, few add ons are available to address the issues of limitations Elgg has.

What were you expecting to happen?
----------------------------------
… Social engine among other possible companies to develop an import script for Elgg communities.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Social engine will greatly benefit from Elgg migration.

What versions of software are you using?
----------------------------------------
**Operating System:** … web server

**SocialEngine PHP Version:** … 4.8.13

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#48

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
