### ISSUE TITLE
Drupal Importer

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#572]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Drupal, with the exception of several other thousands of CMS providers out there, is an interesting software. However, due to its many features, it can become slow over time. However, it is powerful enough to power the whitehouse.gov website, and given its capability to host social networks, it could be useful as a potential interest.
2. … Drupal users don't have a lot of import tools available to them. Their communities are strictly focused on one or two features, which could easily be replicated in social engine.
3. … The communities hosted on drupal, work well, but could be improved.

What happens?
-------------
… Drupal is great for the price, but as communities grow on drupal, a lot of database room is used for hosting module updates. Like Word Press, its speed relies on its resources, which the platform itself, could use an update or two. For this reason, Drupal is an ideal platform to build an import script for to social engine, as the community members will enjoy much better media features just to start with as migration occurs to social engine from Drupal.

What were you expecting to happen?
----------------------------------
… A migration script to be developed so a Drupal site can become a social engine site.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Believe it or not, Drupal could greatly grow social engine in many ways by studying how modern code effects the entire system just to keep up and running.

What versions of software are you using?
----------------------------------------
**Operating System:** … web server

**SocialEngine PHP Version:** … 4.8.13

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#49

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
