### ISSUE TITLE
Joomla Importer

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#573]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Joomla in recent months has been getting lots of attention for its ability to host social networks.
2. … As one of the oldest cms providers around, it seems to do well under high loads without many problems.
3. … Its feature set is very limiting. And although several in house add ons provide essentially the same or similar functionality, its core script is quite limiting in terms of features. Something social engine excels at.

What happens?
-------------
… Joomla users have nowhere to import their communities to.

What were you expecting to happen?
----------------------------------
… Social Engine to provide an import script for Joomla.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Joomla users would greatly benefit from using social engine.

What versions of software are you using?
----------------------------------------
**Operating System:** … web server

**SocialEngine PHP Version:** … 4.8.13

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#50

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
