### ISSUE TITLE
Tiki Wiki CMS Groupware Importer

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#574]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Tiki Wiki CMS Groupware is a script which seems to be constantly improving. It isn't just one thing or the other, it is everything grouped into one software.
2. … Its up side is it is totally free. Its down side is it is slow and sometimes can be resource intensive.
3. … People using the software have nowhere to go and migration options really don't exist.

What happens?
-------------
… People love it for what it can do. However all of what it can do, social engine does faster.

What were you expecting to happen?
----------------------------------
… Migration from tiki wiki cms groupware to be possible to social engine.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… The community would love how easy it is to make a social engine website work well.

What versions of software are you using?
----------------------------------------
**Operating System:** … web server

**SocialEngine PHP Version:** … 4.8.13

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#51

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
