### ISSUE TITLE
Code Canyon Importer

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#575]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Code Canyon has been making alternative software which could be considered social networking alternatives.
2. … Their software has no add ons available.
3. … It would make sense to import such communities to social engine to extend the websites capabilities.

What happens?
-------------
… Unlike other platforms, code canyon users are truly isolated from anything else around.

What were you expecting to happen?
----------------------------------
… Developers to be interested in migrating code canyon software to social engine.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… It would be like flicking a switch, night and day for the people there to experience true freedom.

What versions of software are you using?
----------------------------------------
**Operating System:** … web server

**SocialEngine PHP Version:** … 4.8.13

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#52

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
