### ISSUE TITLE
IPBoard Importer

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#576]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … IPBoard is going social.
2. … It's very expensive to maintain.
3. … Its alternatives are also very expensive to customize and maintain.

What happens?
-------------
… Users would simply have a hay day if they could import their communities to social engine. They'd literally be saving thousands.

What were you expecting to happen?
----------------------------------
… Migration to be possible.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… You'd be glad you made it happen.

What versions of software are you using?
----------------------------------------
**Operating System:** … web server

**SocialEngine PHP Version:** … 4.8.13

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#53

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
