### ISSUE TITLE
VBulletin Importer

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#577]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … VBulletin simply needs somewhere to rest in peace.
2. … Not only is it becoming a social platform, but also an outdated one.
3. … It is very expensive to maintain.

What happens?
-------------
… Frequent bug errors never get fixed, leaving people wanting to switch to somewhere better. The only place which would work well for this which could actually make users even more impressed, would be social engine.

What were you expecting to happen?
----------------------------------
… A migration script to be possible.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… It would be worth it.

What versions of software are you using?
----------------------------------------
**Operating System:** … web server

**SocialEngine PHP Version:** … 4.8.13

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#54

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
