### ISSUE TITLE
Vanilla Importer

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#578]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Great software features for the price. But ultimately a community with few add ons to support it.
2. … Would make sense to switch to something more robust.
3. … Social engine is hiring. Just kidding.

What happens?
-------------
… Vanilla users have a fast website going for them. However, the main attraction of course is the forum. Social engine could provide a stellar forum feature in its place, leaving only one thing to do. Get a migration happening.

What were you expecting to happen?
----------------------------------
… This to be possible.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Vanilla forums help keep other forums less popular, but social engine just makes it easier to migrate to despite the fact it may be a bit slower. The trade off is in customization.

What versions of software are you using?
----------------------------------------
**Operating System:** … web server

**SocialEngine PHP Version:** … 4.8.13

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#55

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
