### ISSUE TITLE
Social Media Importers

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#579]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … I'm not sure if this is possible, but importing from cloud based websites seems like a really good idea.
2. … API's could do this easily
3. … People would love the fact they could have their own export of posts available to them they could make a community out of.

What happens?
-------------
… API's being what they are, could be used to migrate data.

What were you expecting to happen?
----------------------------------
… To be able to import posts from platforms like Blogger, Tumblr, Facebook, Twitter, Linked In, OneSite, HoopLa, Social Go, Spruz, Groups, Socibd, Social Engine Cloud, RSS to Post functionality and others.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… If it is possible, this could be an invaluable resource to social engine.

What versions of software are you using?
----------------------------------------
**Operating System:** … web server

**SocialEngine PHP Version:** … 4.8.13

**Comment by DonnaScriptTechs** [comment]
This request is too broad. Please keep feature requests to one item. New requests can be opened at our [feature request tracker](https://github.com/SocialEngine/phpv4-feature-requests/issues).
