### ISSUE TITLE
Add Video is not working

### ISSUE THREAD

**Issue by JazzJane** [SocialEngine/phpv4-issues#58]
I tried to add a 'YouTube' Video using the 'Add Video' option but, unable to do so. I was shown an error message.

**Comment by smazurov** [comment]
we're aware of the youtube issue, its being tracked at #44, is this the issue you're experiencing?

As a reminder, to be able to fully help you figure out an issue, please follow our [posting guidelines](https://github.com/SocialEngine/phpv4-issues/blob/master/CONTRIBUTING.md#bug-reports)

Thank you.
