### ISSUE TITLE
NEED FIX NOW!!!! MAJOR BUGS !!! FIX NEEDED ASAP!! EMERGENCY

### ISSUE THREAD

**Issue by poeticjustice** [SocialEngine/phpv4-issues#581]
These multi select issues need fixing now! PRIORITY!!!

both tickets raised, no way am i waiting a year for a fix!!!! obviously was never tested when built.

https://github.com/SocialEngine/phpv4-issues/issues/580

https://github.com/SocialEngine/phpv4-issues/issues/536

@smazurov @cgenevier @alimoosavi15 @scrutinizer-auto-fixer @RaymondBenc @DonnaScriptTechs @

**Comment by DonnaScriptTechs** [comment]
Please do not open duplicate tickets. Our technicians are working on things as quickly as they can but duplicate reports and pinging us slows the team from coding. Thank you for your understanding and for your contributions.

**Comment by poeticjustice** [comment]
ok thanks

**Comment by Elshara** [comment]
Don't take it personally if you get told off.
There's always another day to make a difference.
