### ISSUE TITLE
Enhancement - for Multi select, multi check as they are very outdated

### ISSUE THREAD

**Issue by poeticjustice** [SocialEngine/phpv4-issues#582]
This is an enhancement request that i raised ages ago, over a year ago directly to SE.

best way to sum it up is, Multi select and multi check are outdated.
they feel so year 2000.

holding crtl and multi selecting, or having a long vertical list of multi checks, looks nasty signing up and also browsing the members.

Best way to describe the enhancement, is with a video, a video of a site that uses what im pushing for, check the video out 

https://sendvid.com/vnkc8665

This is the  new era way, and much better for users interacting and using, and looks streamline!

**Comment by Elshara** [comment]
To be completely honest here, I love check boxes. I also like combo boxes. I just don't much care for the multi-select list boxes. Drop down menus are pretty stream lined two though.
I personally think the profile options area needs some work. For instance, the browse members online feature just doesn't work. And the browse people with photos, is just useless. I'd replace it with maybe a birthday selector, age selector, male or female selector, or just hide them altogether. I wish you could browse by user group, member level and profile type. I wish you could hide or show the selectors just by clicking on them. It would be ideal to see results auto scroll so you don't have to keep loading pages to see people. I wish on the browse members page, you could have one click actions which you can do while on the page, liking their profile, commenting on it, sending a friend request, sending a message, various member blocking and administration options and the implementation of bulk actions.
The point is, to do that, you need check boxes and or combo boxes and or radio buttons currently implemented through html5.

**Comment by poeticjustice** [comment]
I use social engine solutions advance members, really good.

However yes Social engine NEEDS  profile questions and type of methods updating.
Same with browse members.
Areas I recently found to have bugs.

They seem to have never changed since when SE was first made.

Profile signup needs to be better, it be great if you could split the process of signup over pages, so you have certain info page one of signup, so Name, Surname, DOB, then next page be some of your profile questions, then next page dedicated to for example skills etc so on.

Also browse members only reflects the questions.

Example say on signup 

You have a single select option of

For example

Location,

On signup a members selects London

On browse members all you have is single select option, but being as your browsing the members, you should be able to multi select what your searching for on ALL questions.

So dumb you chose on sign up, but because the question was single select, it makes the browsing option single select too, which is silly

Example being, your looking for someone in London, Sout East (which is surrounding area), and south west.

In browse members your forced to search only one location at a time, then research the next then the next.

This was example so don't say "but you can search miles of a location radius"

Point is the questions to browsing  are horrid.

Hence why I say tags are better.

To be able to use multi select search you have to make the question on signup multi select, purely so the search can be multi selectable, which is annoying when on signup as you may only want then to select one option.

Great example of this is GENDER

You may have Male, Female and TransGender 

Now on signup you will want users to ONLY select one, so its single select.

User on browse members may like Males and Females but not Transgenders.

But the user can't search Male and Female, that user is force to search either male first, then female second, they simply can't select Male and Female......

Which is ridiculous

**Comment by Elshara** [comment]
Yeah. Like I said the profile questions area is very cluttered and
inefficient in today's day and age. Especially for a social profile,
it seems the one area with the least amount of customization and most
amount of head aches because everything to do with core edits, you
can't change how they appear.

**Comment by poeticjustice** [comment]
I think it's been the exact same since social engine 3 or first release of 4.

I really love social engine, and 3rd party plugins and customer Dev for own plugins is great , but the core profile questions and browse ability is sooooo old out dated, and as I recently found Buggy as hell.

When a social engine site has a great theme and plugins, it looks amazing, site sounds amazing.... then you goto signup and it's like hmmmm ok bit dated.

Then you browse and browsing isn't even good. 

Shame, really hope our input is considered, feel like getting all use SE members together and say let's throw $20 in each we all discuss what we want , and give the collected funds to SE and say ..... here do it lol

**Comment by Elshara** [comment]
I think it's a nice idea. I know some developers do this.

**Comment by poeticjustice** [comment]
Just be nice to keep it under SE roof to do that so it's core and updated etc

**Comment by Elshara** [comment]
Yeah exactly.

**Comment by Khushboo016** [comment]
Hi @poeticjustice, 

Regarding "This is an enhancement request that i raised ages ago, over a year ago directly":
Thanks for your good suggestions regarding improvement of Profile questions of Multi Select Box and Multi-Checkbox type. We have added this suggestion at our end for internal team discussion, the user-interface can be enhanced by the use of Combo-boxes for such type of questions which can have multiple answers.

Regarding "To be able to use multi select search you have to make the question on signup multi selec":
If you create a Profile Question of type "Multi Select Box" then on the Members Browse page, the search filer would also be of the type multi-select. It is not possible to have a search filter of type multi-select if you create a profile question of type "Single Select Box".

Regarding "Areas I recently found to have bugs.":
It seems you are referring here the issue you've reported in case https://github.com/SocialEngine/phpv4-issues/issues/580, if so, then we would like to let you know that our developers are working on this issue to fix it.

Thanks & Regards!

**Comment by poeticjustice** [comment]
Combo boxes is not a current feature tho is it?

regarding "It is not possible to have a search filter of type multi-select if you create a profile question of type "Single Select Box". "
Yea i know its not a feature, but was just saying as a search feature, would be great to multi select a selection of the answers from a single select box, single select is because you want the user to only choose one option, but for you to be able to have better search function your forced to use multi select.

i raise two bugs https://github.com/SocialEngine/phpv4-issues/issues/580 and https://github.com/SocialEngine/phpv4-issues/issues/536
yes

for bug #580 like @DonnaScriptTechs  described

_I made a multi-select profile question of "Favorite foods".
The three options I made are: Pizza, Hamburgers, Chocolate.

User A chose Pizza, Chocolate
User B chose Chocolate

User B went to the member browse and searched for those that like Chocolate and it brought up both User A and User B.

Oh ok I see. If the search is for Pizza and Chocolate it only shows User A. User A and User B should both show.
I can confirm the issue as you have described it.._

**Comment by Elshara** [comment]
Check boxes and combo boxes work good for search.
Not sure about other types of entry form data other than text.

**Comment by JonSimon93** [comment]
a slider would be great option for example age

**Comment by Elshara** [comment]
It would be a nice touch, I must admit.

**Comment by Khushboo016** [comment]
Hi @poeticjustice,

Regarding "Is what i showed in this video https://sendvid.com/vnkc8665 considered combo box?":
Yes, the boxes shown in the video are considered to be Combo boxes. Are these not combo boxes?

Thanks!

**Comment by poeticjustice** [comment]
@Khushboo016 the above confused me

**Comment by Elshara** [comment]
He's trying to understand what you want changed and right now, he
thinks you're trying to show him what a combo box is in a video you
linked.

**Comment by poeticjustice** [comment]
@Elshara the answer felt like it contradicted itself.
I originally asked if it was considered a combo box,
His reply was yes it is.... then added is this not a combo box?
Which is confusing because I first asked!

**Comment by Elshara** [comment]
Now I'm confused.

**Comment by Khushboo016** [comment]
Hi @poeticjustice, @Elshara, I am sorry for any confusion. But @poeticjustice, what you have shown in your video is a combo box as per my knowledge.

Thanks!

**Comment by Elshara** [comment]
Well whatever it was that was trying to be shown works for now. I'm
not even sure the problem of this particular issue.

**Comment by poeticjustice** [comment]
sorry @Khushboo016 had to familiarise myself with this post, as posted alot.

Yea combo boxes, obviously this is just a more fancy way of displaying multi-check and multi-select, with a better functionality.

Multi-select and multi-check boxes however should be acting like combo boxes.
Every other site in existence that i have witnessed that have multi-select or multi-check are combo, Only SE acts horribly.

hence bug report

even @DonnaScriptTechs cornfirmed

"I made a multi-select profile question of "Favorite foods".
The three options I made are: Pizza, Hamburgers, Chocolate.

User A chose Pizza, Chocolate
User B chose Chocolate

User B went to the member browse and searched for those that like Chocolate and it brought up both User A and User B.

Oh ok I see. If the search is for Pizza and Chocolate it only shows User A. User A and User B should both show.
I can confirm the issue as you have described it.."

This is because User A and User B should show in browse members, Because its showing those who like Pizza, those who like Chocolate and those who listed both.

Just like eCommerce sites, if a user set to show XL and L clothes
It would show XL and L clothes.
But based on how SE is at the moment  if a user set to show XL and L clothes
It would only show a listing that listed XL and L on its one listing, it wont fetch the XL listings and L listings

IT actually quiet easy to understand what im on about, it confuses me how some fail to see or understand what im talking about


This is a enhancement request tho for Multicheck and multiselect to be designed and function looking like that of the video, thats what im asking for.

But there is the bug of the multiselect and multicheck and thats in another thread

**Comment by Elshara** [comment]
The bug will be fixed in the next version.
What confuses me, is the nature of specifically, multi-select.
I think the box should be divided into individual controls to make
searching and usability easier.
On one hand, it is used to select certain aspects of a whole item. For
instance, member levels when sending a broadcast message, or when
targeting an ad campaign. It functions in this case, like a check box.
But on the other hand, there are other cases, where in multiple choice
questions, where it functions as a combo box. Even though the same
type of box is used to implement different types of controls. The
profile questions area, is a perfect example of such a use case
scenario. However privacy controls when adding a new item, is another
example.
I think when only being able to choose one item out of a list, a
standard combo box should be used. But when being able to choose
multiple items, a standard check box should be used. So the crafted
multi-select list boxes found throughout the site contained within all
site modules, can be replaced with specific boxes to handle item
selections specifically relating to the use of how the data choice
should be made.

**Comment by poeticjustice** [comment]
Hi @Khushboo016 and @DonnaScriptTechs 

I found this page http://selectize.github.io/selectize.js/

Which looks like what I mentioned about updating the multi select and also multis-checkboxes, but with the use of tags.

Especially the feature of having groups seen here http://selectize.github.io/selectize.js/#demo-optgroup

elements for these type questions seem to be held here
 application/modules/Fields/View/Helper
 /application/modules/Fields/Form/Element
 /application/modules/Fields/settings

**Comment by gsf00001** [comment]
@poeticjustice ==>"I found this page http://selectize.github.io/selectize.js/"

Wow - that's sweet.  Looks very professional and up-to-date and extremely flexible and intuitive.  Great example for SE to build from.  Thx for providing that.

**Comment by poeticjustice** [comment]
you know this @gsf00001 :D

**Comment by Elshara** [comment]
Yeah I love it! You should get Raymond Benc to look at this. I forget
his git hub name.

**Comment by poeticjustice** [comment]
@RaymondBenc  :)

**Comment by poeticjustice** [comment]
Id give SE $100 right now if they added it in 4.9 release ha

**Comment by DonnaScriptTechs** [comment]
We'll be looking at features after 4.9 releases. :)

**Comment by gsf00001** [comment]
I'd give SE $100 for many things if they added them (so that they'd be in Core).  I wish SE provided additional customization services to allow incorporating certain functionality into Core (just like some 3rd-Party Devs will customize something 'for your site only', others include it in future updates to their Plugin which is what I prefer).  This would provide $ to SE, get functionality we wish added, and potentially make the product much fuller-featured (but potentially more bloated) to meet other ADMINs' needs.  There's so much more that could be accomplished but there's obviously a cost to SE to do it (development, support, etc.) and I'd much rather be told "sure we can implement that - it'll be $X" rather than "no, we have no plans" which requires either a 3rd-Party customization to SE Core or to a 3rd-Party Plugin or creation of a completely new Plugin.  

Yes I know - many ADMINs would never pay SE for anything other than their initial purchase price, but others that rely on SE and believe in a more fair/realistic/mutually-beneficial relationship will pay for what we need.

**Comment by poeticjustice** [comment]
@gsf00001 I actually raised with with @DonnaScriptTechs on https://community.onsocialengine.com/

about all us buyers coming together and crowd funding to implementing features we want sooner rather than down the line.

Id happily do that, but not heard anything back regards to it as they have been busy.
Even if it was on their site submit a core feature request, we all see, and we try to fund it to make it happen sooner, rather than years later etc

**Comment by gsf00001** [comment]
I've sent 2 emails about this (paying SE for certain Core customizations) with no reply (which is unual - but it seems they're all very busy with 4.9 which is a good thing if you know what I mean).

Crowdfunding/sponsoring I think is a great idea rather than us ADMINs wait indefinitely or not get it at all.  There are simply some things that should be (or at least are better to be) in Core.

**Comment by Elshara** [comment]
I agree. We can be stubborn, two.

**Comment by DonnaScriptTechs** [comment]
https://github.com/SocialEngine/phpv4-issues/issues/613 this is a duplicate or related to that one. It will be resolved once that one is I believe. If not, please open a [new request](https://github.com/SocialEngine/phpv4-feature-requests/issues) after we implement the other request.
