### ISSUE TITLE
Log Browser Cannot Change Order Of Viewing

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#585]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Go to logs area in admin panel.
2. … Click on one.
3. … Be sure to let the page load fully prior to reading it.

What happens?
-------------
… The date is sorted from oldest to newest. In order to read the most recent log, you have to download the entire thing in order to scroll to the bottom of it using a text editor, as you can't load anything past 50000 lines of code in the browser. Besides, the system slows down to a not responding state every time you click show 50000 lines anyways, so the fast option is to download the log in its entirety.

What were you expecting to happen?
----------------------------------
… To be able to sort lines based on oldest first, newest first and also to be able to view the entire log in a pop up window.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… It's hard to diagnose an issue if you can't even find it and aren't sure if it will duplicate itself again any time soon. Logs are a crucial part of trouble shooting social engine if something isn't working right, and to be able to know the cause of the problem in real time as it happened then.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by Khushboo016** [comment]
Hi @Elshara, Thanks for your good suggestions! we've added these to our internal feature tracker and hopefully, would work on their implementation in future releases of SocialEngine.

Thanks & Regards!

**Comment by Elshara** [comment]
You're welcome. Glad I could help.

**Comment by JonSimon93** [comment]
downloading the log and ability to delete old loags would be great, i noticed some logs get to 10mb then they generate a part 2 log, part 3 log..... im scared to delete in file manage.

Confirm i can not see on my friends SE anything past 50000 lines

**Comment by Elshara** [comment]
That's why this issue was reported so it could be changed if people
are interested in it.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#58

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
