### ISSUE TITLE
Task Scheduler Manually Stops Recording Tasks Randomly

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#586]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Go to task scheduler main page.
2. … If the issue occurs, and you don't notice things like the background mailer running in its usual interval, then you will see the last date it was able to run.
3. … Clicking on the check box which says run tasks now, does not fix the issue. A similar case scenario also happens with the job queue area.

What happens?
-------------
… Tasks either never complete in time, or randomly stop working altogether. It is all based on server time out factors. If the settings are set to time out too soon, tasks never complete and are the cause of an endless loop. If the server time out is set too long, the time out occurs too soon even if php.ini value is set to -1 as to not interfere with the time out process. Usually it takes about a month of request time out activity for each task to start randomly failing to regenerate itself in such conditions. Severely altering the augmentation setting in task scheduler to have values displayed in intervals of 1000000000000000000 for each, you would think, should eliminate the problem, since tasks would only run in combination with php max time -1 as long as they needed to before a refresh. You wouldn't have the problem of concurrent process, or max server requests, because the tasks would just run again and complete before the time out was reached. However the problem is, nothing is enforcing the process to continue as the error is reached in time, therefore clicking on run tasks again manually does nothing, as a build up of tasks continues, causing a manual reset of the server setting in task schedulers make tasks time out at 60 seconds and have the max time per request 30 seconds a priority. Only then do tasks resume, where by then you can readjust the settings to their augmented values. The reason for doing this is so that tasks can complete concurrently without a problem, and if you always set the tasks to recheck themselves at every 1 second, and ensure a value of 1000000000000000000 is maintained, you should in theory, never run in to any problems. Unless of course, an error happens in the mean time, causing a back log of server tasks to be in the queue to be run. Like emails for instance, or tasks simply failing to regenerate themselves based on the cycle time out.

What were you expecting to happen?
----------------------------------
… To be able to satisfy values for both task max execution and job queue max execution so they complete even on a server with minimal resources allocated to it. I made sure I set in the database, custom values so tasks can run more efficiently and regularly so the job queue is smaller per task check. And everything gets completed within a day. The problem is not that tasks don't complete by making such a tweak, but that the completion effect takes too long to reset itself as a whole to free the task scheduler to run at will.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… There should be an alternative way to handle tasks. I wish the -1 feature would work for how long an individual task needs to complete itself, while it does not effect the generation of new tasks as the queue goes on. It isn't just as simple as shortening the long time out, because you never know how long a task should take. In theory, it would require a few minutes maximum, however while the task is completing and timing out, you have to also adjust the respective values of other tasks so that they only run once another task has finished completing. Therefore, making sure the job of concurrent tasks remains efficient enough to not time out other tasks. This doesn't maximize server resources because the frequency of which longer tasks run, has been adjusted so the time period it takes to complete them, does not interfere with shorter time periods for smaller tasks to run better. It's almost a perfect system, however the non implementation of the -1 value makes it impossible to complete full circle without any problems. There should be a difference if a task takes longer to complete based on movement, or if something is blocking it from moving to require manual intervention, which shouldn't just be a reset of the entire system. Especially if only one task is effected. Although this fixes the problem, that which isn't having problems shouldn't need a reset. What I'm saying is the task scheduler only has problems with maintaining longer periods of time out because the setting which controls process time out, controls it for all tasks, and over time, if tasks don't run due to a time out, and not a server response limitation, the only thing which gets them going again is a shortening of the time out itself. But it works fine once you change the setting back to its original value. So this means that either the tasks which run concurrently have never timed out in the first place, which would just make it worse if their setting was any different from the value of 1000000000000000000. Or, as each task completes, the time out fails to reset itself as a new task begins, making the tasks queue up unless the concurrent process themselves involve other task instances, which over time, build up to something resembling a total task scheduler hold up. The tasks never fail if stopped in such a manner however, which leads me to believe the issue is caused by no independent task time outs from the maximum default, which shouldn't in theory have anything to do with the maximum time out being reached in order to justify a requirement for the process to regenerate itself by waiting for the time out to happen. If this is done concurrently, it wouldn't make sense to do so as the whole system would therefore be effected by unused time while the queue piles up. Otherwise, the alternative points to the fact max time out requests are not replicating what the value is set determined by the inability to read the php ini current configuration in order to auto adjust the frequency of how time out behavior activates itself according to the value found there. Should such a feature be independent or dependent on such a value, it should auto adjust how long or short time out requests occur, and by monitoring real time server usage, automatically set safe server values for requests to complete in time on a per needed basis. Such functionality currently does not happen in such a way as per the existence of the physical server resource analysis. Doing so independently for each task would ideally result in best performance.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by Khushboo016** [comment]
Hi @Elshara, No doubts, you've always been an engaging SocialEngine user and your suggestions have helped us a lot in improving its features and functions. But, as we've told you earlier also that while reporting an issue/query in Github, please make sure you make the report in a concise form and it would be great if you can make a pointwise summary of the issue. Because such a long report of the issue as this one makes it very difficult for us to go through all the points mentioned in the report and chances are that we would unwantedly skip some points of the report. So, I request you to please make a brief pointwise report of the above issue, so we can be able to have a look at the major concerns of this issue.

Thanks & Regards!

**Comment by Elshara** [comment]
Task Scheduler sometimes gets stuck if the time out and or server
requests are set too long.

**Comment by Khushboo016** [comment]
Hi @Elshara, 

Regarding "Task Scheduler sometimes gets stuck if the time ou":
We suggest you use Cron tab as the trigger method for running task scheduler as it triggers tasks frequently, so chances that task scheduler would get stuck are very few.

Thanks & Regards!

**Comment by Elshara** [comment]
Thank you! I'll be sure to make the change on this end. I think you're right.
