### ISSUE TITLE
Group Mail Notification Feature

### ISSUE THREAD

**Issue by leandrotavaresrocha** [SocialEngine/phpv4-issues#587]
In the actual notification system SE send a email almost all times that that a action trigger a notification. This is good for websites with few activity but lets imagine a huge community, if each time that someone like one of your contents you receive a email, in a couple of days the website will be blacklisted as a spammer.

Facebook has a interesting way to avoid this. Instead you receive a e-mail for each notification it "ignore" a quantity of repeteaded activities during the day. 

Example: Lets suppose that you shared a link in a group and it is receiving several likes. You will receive a notification and a e-mail for the first like that you receive. For any additional like after the first you will receive a notification as usual, but you will only receive a mail notification for a like produced after a couple of hours after the first email notification.

I already tested and noticed that for most actions like comments and likes I only receive a new mail notification for actions produced one hour after the first mail notification. I am not sure how complex could be implement a way to filter mails to user based on quantity of mails send in a time period for the same e-mail address but this is without doubt a good feature to avoid problem with server being blacklisted.

**Comment by poeticjustice** [comment]
@leandrotavaresrocha  before you call me spammy again, i have raised this with via email and also similiar thread here #566 just incase they close for duplicated

**Comment by poeticjustice** [comment]
Would be great tho to have a group all notifications, to like a daily summery or weekly or monthly, like Linkedin in a way, SEAO have advance email, maybe they can do custom work based on that.

**Comment by leandrotavaresrocha** [comment]
I remember that buddypress has a plugin to send grouped mail notifications, but it only work for groups what in thesis is fine since almost all notifications from buddypress are from groups extension.

I cant remember if SEAO has an advanced mail, I can only remember about a couple of advanced notification plugins but they only offer a better interface for the notification area.

I think that this option would be better in the core because as our marketplace have a few integrations between developers products if third party develop this feature is high possible that it will only work with plugins developed by him.

I remember that Hire-Experts has a newsletter plugin that can work as a periodic newsletter, but in the end this will not reduce unnecessary mail notifications, unless you deactivate the default notifications and only use the plugin for this purpose.

**Comment by poeticjustice** [comment]
I have SEAO advance email, only product I really use if there's now,

But you get to design each notification email really nicely, but you can also use it as a newsletter too as you can design an email to send to all users or networks or even specific users (not limited to 10 only like the core feature) so you can type and you see the user etc , no limit.

**Comment by gsf00001** [comment]
Yes, this goes with related issue #566 .  The entire email/notifications system needs to be revamped (and/or customized via 3rd-Party Dev).  Although Sendgrid (and others) may be used to keep you from being flagged as a spammer, there's still a cost (site performance for emails/notifications, and direct $$ for emails) as the volume of traffic grows.  Plus, many Users obviously don't like (or need) dozens of notifications and/or emails when 1 will suffice.  Site-ADMIN should have total/complete control over which get sent via email/nofitication, how offen they get sent, and which the User is then able to configure and how often they wish to receive what and how.

**Comment by Elshara** [comment]
I think this also refers to my comments about having a separate like, comments and notifications plugin. Group activities need to be formulated as an extension of the mail plugin, because they incorporate invitations into the mix.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#59

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
