### ISSUE TITLE
Feature Request - Members stats - Last login

### ISSUE THREAD

**Issue by poeticjustice** [SocialEngine/phpv4-issues#588]
Hi Social engine,

Just a feature request / Idea

I think a great addition to the members section in admin would be, Last logged in

Reason I say this is, there are members who signup, and go to effort of filling out profile fields.

For them to never log in to the site, once accepted based on approval system, obviously if auto approved they will be on the site straight away.

But once as admin , i approve members etc, they are sent the approval welcome mail,
Loads have signed in, but some have Never signed in........

Be great if in members admin section, there was a tab similar to approved, not approved but one for
Logged in,, Never logged in

This is great then to identify specific users who can be removed from the site as non engaging users.
also help identify certain email hosts who may be putting emails in spam.

I have dedicated server, completely clean on spam check, hotmail, gmail, personal domain address etc all go straight to inbox no issues

but to have a ever logged in tab, we can identify if certain email hosting is putting our sites in spam,
If never logged in users have @ yahoo in common, we can identify problem email addresses .

And as mentioned we can delete users who have seen our welcome mail, but chose to never log in.

**Comment by SpiritWolfie** [comment]
I agree with this too, I get allot of people signing up for my website, and then never re-log back in, It'd be nice to know who has never signed in since being approved, This would greatly help us keep our stats accurate

**Comment by poeticjustice** [comment]
Exactly matey, so many good reasons to have this ability to see who hasn't logged in since approved.

Main one, maybe your mail is not reasching the person - or didn't see it, so you know to unapprove the. Reapprove so new email sent.

Finding out if some sign ups were robots

Finding out this who decided to not see the site thru, so you know to contact the user and ask feedback.

And many more reasons.

The more users the more time consuming to gather this data

**Comment by poeticjustice** [comment]
Just to clarify what would be good in Manage Members section

If there was a tab for "Last Login" where you have "Display Name" "Username" "Email" "Level" "Approved",

and the choices were linked to stats so the options were - Never | Under 1 Week ago | Under 3 Months ago| Under 6 Months ago| Under a year Ago | More than a year ago

This will be literally the MOST USEFUL tool ever!
To maintaining great community, deleting members who never came back, Targeting users with mail to get them back engadging in the community, to identify who never saw the welcome emails etc list of reasons

**Comment by Elshara** [comment]
I thought we had this. Click on stats under a profile and you should see their IP address among other things, the date they last logged in.

**Comment by poeticjustice** [comment]
@Elshara Yes if you click on stats of each individual user you can see this.

Im on about a filter tab, so you can see EVERYONE, who hasn't logged in at all,

If you had a community of 2000 people, do you honestly want to click stats of every member profile? Just to find out who hasnt ever logged in, or hasnt logged in in over a year?

**Comment by Elshara** [comment]
IT wouldn't take that long if you had several people looking over the
data worse case scenario. However if I had a community of 2000 people,
I'd probably know who wasn't active just by looking at what's been
posted by whom.
If I could count maybe 50 from 2000 people, then you have a community
consisting of 50 active people. Can't you sort member login history by
sign in date? That should be able to tell you whose logged in when,
shouldn't it? From whatever IP and Email they were using all in bulk?

**Comment by poeticjustice** [comment]
@Elshara I dont think you fully understand what im getting at, plus members login history has a bug.

There needs to be a way to quickly identify those who have never logged in

Because they may have never received welcome email, it would help identify problem email hosts who are placing you in junk.

Plus you could market material to get users to return if not been logged in, in a while.

checking stats of every user is just ridiculous, could your see Mark Zuckerberg doing that?

**Comment by Elshara** [comment]
We have to use what all it is we have to work with here. If you notice
someone specifically you wish to look into, then we use all the tools
at our disposal to find information on such a person. I wish I could
magically appear an alternative, but I cannot. In the mean time. All I
can do is hope and wait. You could reach for a third party developer
to help you code a simple module to do something like what you are
suggesting. I'm sure a coder would be happy to assist you. I don't
mean to seem harsh, but I'm getting to the point here. We have posted
a suggestion in agreement for what it is and all it has to offer, now
we wait to see if a developer from social engine, can do something
about it.

**Comment by JonSimon93** [comment]
this is a feature on a script i have for AVS for importing videos for a community.
Its filter is Active and Non-Active..... when choosing Non-active you see users who have not logged in, or not contributed.

What you mention would be great for comminities over 100 people,  agree

**Comment by Elshara** [comment]
IT would also be useful to have other bulk action pages besides login
history available to us.

**Comment by Khushboo016** [comment]
Hi @poeticjustice, 

Regarding "Be great if in members admin section, there was a tab similar to appr":
We have added your suggestion of displaying the last login of a member, at our end for internal team discussion regarding its implementation in future releases.

Thanks & Regards!

**Comment by Elshara** [comment]
Awesome!

**Comment by poeticjustice** [comment]
No that is awesome, best tool ever that will be!

**Comment by Elshara** [comment]
I agree.

**Comment by poeticjustice** [comment]
Any news @Khushboo016 if this is being tagged as an enhancement, would hate this awesome suggestion to be lost, and not easily found and ticked off by the team.

**Comment by Khushboo016** [comment]
Hi @poeticjustice, We would work on the implementation of this feature in future.

Thanks!

**Comment by Elshara** [comment]
I thought it was already available. Go to member admin page. You do
realize members on browse page are sorted last login by default? It's
not officially known, but that's how social engine sorts members. Not
by most recent, but by latest activity. AKA, last login.

**Comment by JonSimon93** [comment]
nope @Elshara there isnt a feature like this at all.

AVS for importing videos script, it has a feature to see exactly who has never logged in, this helps me identify who has no intention of using site, or potentially someone who never received an activation email and then forgot about the site.

You have to go thru 1 by 1 on social E, to see stats of each person, just to see who has never logged in. so backend makes sense to have a filter like this

**Comment by gsf00001** [comment]
Although the default sort may be by last login (not sure what order this is though) that still doesn't display the actual last login date/time.  2 of the Plugins I use provide some related useful info, but not the actual last login date/time.  Being able to see these in ADMINcp would be very helpful.  An extention of this would be to be able to send an email to all those that haven't logged in (date range).

**Comment by poeticjustice** [comment]
exactly that @gsf00001 targeting an audience!

**Comment by Elshara** [comment]
I agree. We should have it displayed as a column by default when
browsing members in the admin panel. It would make lots of sense, to
just replace the statistics section with links to such pop up via
smooth box. Or just extend the table using search filters.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#60

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
