### ISSUE TITLE
BUG - Spam Banning Tools Login history

### ISSUE THREAD

**Issue by poeticjustice** [SocialEngine/phpv4-issues#589]
Bug I have noticed in Spam banning tools

If you goto Login History

Then type a members name in Member , member ID , first name, last name or even full name

It will say
0 sign-ins found.

Even tho you know they attempted signin

It only works for Usernames,

Example 
Member A - Bob Smith has username Bobcat
Member B - Terry Smith does'nt have username so his ID number is 82

Search member Bob Smith = 0 sign-ins found.
search member Terry Smith = 0 sign-ins found.
Search member Bobcat = 1 sign-ins found.
Search member 82 (Id number) = 0 sign-ins found.

**Comment by SpiritWolfie** [comment]
I can confirm the search string thing, Happens on my site too, ID issue I haven't tested

**Comment by poeticjustice** [comment]
@DonnaScriptTechs @Khushboo016 any chance of getting this raised for 4.9 to fix this bug too??

**Comment by Elshara** [comment]
Confirmed here two. 4.8.13

**Comment by JonSimon93** [comment]
**confirm 4.8.12 also**

**Comment by Elshara** [comment]
This has yet to be looked into by the development team but it will
likely be done soon.

**Comment by JonSimon93** [comment]
great to hear its on your list @Elshara

**Comment by Elshara** [comment]
I thought so as well.

**Comment by Khushboo016** [comment]
Hi @poeticjustice, @SpiritWolfie, @Elshara, @JonSimon93, we have noted down this issue at our end and will fix the same in near future.

Thanks & Regards!

**Comment by poeticjustice** [comment]
Any chance for 4.9? I can live without for momement just wondering? @Khushboo016

**Comment by Elshara** [comment]
Relax just give it time. It'll happen. Kashboo is a great guy.

**Comment by poeticjustice** [comment]
relax, I am relaxed, and i never said @Khushboo016 wasnt a great guy??

Confused by this comment

**Comment by Elshara** [comment]
What I meant to say was what I've already said. Give it time. No need
to rush into things. If it's being considered, the likelihood of it
being in the next release is pretty stable. It's supply and demand
which runs things usually and social engine developers do so on a
democracy basis.
Don't worry about it. In other words, relax, the notion of it being
considered has already been a tried and true concept.
Different words same meaning ideal source of truth.

**Comment by poeticjustice** [comment]
Oh I get that yes, but supply and demand is very different to bug.
That's like saying "we know it's a bug but only 1 person out of 20 wants it fixed, so we will wait"

**Comment by Elshara** [comment]
I've lived with worse. I guess I can see where you're coming from. For
you, the concept is hard to get your head around. For me, it's my only
hope that I can see a light at the end of the tunnel. A tunnel I've
traveled before into, realized it was a dead end and got trapped in
its darkness until I figured out how to cut a side or two out of it
and crawl out, essentially escaping into where I am now.

**Comment by DonnaScriptTechs** [comment]
This is fixed for 4.9.0 when it is released. If you still have this issue after we release, please open a new bug report.

**Comment by poeticjustice** [comment]
Daaaaammmmm Social Engine have been busy, and this @DonnaScriptTechs  is a legend

**Comment by DonnaScriptTechs** [comment]
lol thank you. It's a team effort and the team has been working very hard.

**Comment by Elshara** [comment]
:)
