### ISSUE TITLE
Activity Feed Item Type Settings

### ISSUE THREAD

**Issue by alx2bgx** [SocialEngine/phpv4-issues#59]
In /admin/activity/settings/types
Is there a way not to show items created from desactivated plugins ???

**Comment by Anshuse** [comment]
Hello @alx2bgx ,

Thanks for bringing this to our notice.

When any plugin is disabled then the respective items in the "Action Feed Item" drop-down don't get disabled. We've reported this issue at our end for internal discussion over this to work on it in near future.

Best Regards,
Anshu

**Comment by alx2bgx** [comment]
Same problem with /admin/mail/templates
All templates are there... even if pluggin is disabled. :(

**Comment by Anshuse** [comment]
Hi @alx2bgx ,

As we've replied to you in issue# 60, we've reported this issue at our end for internal discussion and we will work on this in near future.

Best Regards,
Anshu
