### ISSUE TITLE
Where to go or what to do upon User Logout/Signout

### ISSUE THREAD

**Issue by gsf00001** [SocialEngine/phpv4-issues#590]
Feature Request 

As everyone knows, upon Logging-out the User is returned to the Landing Page (but I could be wrong- maybe there's options I haven't seen).  Although this might work for some/most Site-ADMINS, I actually paid for a customization to this (a whole hour - biggie customization - ha).  The issue is that although it's only 6 lines of code, it's done to Core (which I don't like, even though it's my only Core customization).

Why not return to the LP upon logout you ask?  For many reasons, but in my case - I'm using a separate 'marketing' website as the front-end to the SE Community Site.  It's where Users start and where I want them returned to upon Logout (site home page or other page).  Altough the SpectroMedia Theme I'm using provides lots of flexibility to the LP, it is limited by what can be done via Layout Editor and constraints within SE.  I'd much rather edit the external site when needed, than edit the LP configuration every time (which as I mentioned can't do everything I need to anyway).

Different strokes for different folks:
- some may wish to do something after logout process is started but before returning to LP.  At this point although logged-out, the User is still accessing the SE Site.
- some (as in my case) may wish to do something at the end of the logout process instead of the LP.  At this point the User is completely out of SE.

**Comment by poeticjustice** [comment]
I have my front main page as a HTML, as I have better control over what people see, so I can make it look super special.

I made sure Social Engine was installed in a directory so for example "user"

So it's domain.com/user

For the sign out page I'm pretty sure I placed a HTML redirect or redirected the actual URL so when log out, it open the link domain.com/user/logout then I redirect it to a page of my HTML section.

**Comment by Elshara** [comment]
Yeah. IT might just be simpler to manage mobile redirection the same way as the logout feature. Have you ever notice, the URL of the page you are on is encrypted in a double URL string when you sign in from any other page? Similarly, log out should just give you the option to return to the page you're currently on as you were signed in. Otherwise, just optionally choose redirection upon sign in or sign out. Let it be located in the user options area. I think there would make sense.

**Comment by gsf00001** [comment]
@poeticjustice "For the sign out page I'm pretty sure I placed a HTML redirect or redirected the actual URL..."

How/where did you do this (i.e. in a widget somewhere or modified code)?

Yes, I too am using .html as the front end at the domain.com of my site, and will be using various folders beneath that for version#s and status (development, staging, testing, live, etc.).  I originally installed SE the root of the domain, but quickly realized there was a much better way of configuring this and FastComet took care of moving things and editing the .htaccess file to make it all work.

**Comment by Elshara** [comment]
Fast comet is awesome. I much prefer them than host iso.

**Comment by Khushboo016** [comment]
Hi @gsf00001, 

Regarding "Where to go or what to do upon User Logout/Signout":
This feature is very useful for you based on your site's requirements but it does not seem to be a much useful feature in general, so, code customization performed at your end is a good way to achieve this feature. 

Thanks & Regards!

**Comment by Elshara** [comment]
IT sounds like a useful feature to me. You could just set it to main
page by default if people didn't want to use it.

**Comment by poeticjustice** [comment]
@gsf00001 was looking into this, i thought there was a signout page in layout editor, but there isnt.

Be great to have a page for signout to be added to layout editor

Purely as you could place ads on the signout page, or like i  mentioned add HMTL code for redirect.

@Khushboo016 a redirect on signout is a really good function, even if something in settings for signout redirect and you enter a weblink for redirect

**Comment by Elshara** [comment]
I agree. Trust me. I have a list of updates I'm making off site I plan
to release to git hub.. this is one of the features.
