### ISSUE TITLE
Who is online Widget 

### ISSUE THREAD

**Issue by SpiritWolfie** [SocialEngine/phpv4-issues#591]
@DonnaScriptTechs  has requested I repost this as I've shown her on screenshere this issue

Who is online - Widget is still not correctly showing the proper amount of people online

![image](https://cloud.githubusercontent.com/assets/9712738/23822932/0dcd206e-060c-11e7-9e9e-02b37d1fe015.png)

I have repeatedly (repeatedly) tested this, including fresh install of Social engine, I get the same results everytime.

**Comment by Elshara** [comment]
Same here. I'm not worried about it. I think it's to due with the number being cached. Try  changing the member data frequency in chat module in the database. It might fix it.

**Comment by SpiritWolfie** [comment]
@Elshara while its not to much of a big deal, its just silly how unreliable it is and inaccurate

**Comment by Elshara** [comment]
I know. I also find third party scripts like Comet Chat, arrow chat,
even have such a feature better aligned to real time.

**Comment by Khushboo016** [comment]
Hi @SpiritWolfie, The display of number of online users and online friends depends on the tasks "Member Data Maintenance" and "Chat Data Maintenance", so, if there is an issue in the display of the number of online users/friends, then these tasks would not be working properly and the tasks would stuck at times. So, please check from Admin > Settings > Task Scheduler if these tasks are working fine for your site and if these are not working properly, then we suggest you contact your hosting providers to make sure Task Scheduler run fine on the server of your site.

Thanks & Regards!

**Comment by Elshara** [comment]
You could also adjust the value in what tasks run and how frequently
they do so. I doubt that would cripple system performance too much.
