### ISSUE TITLE
MAJOR BUG - Profile signup NULL entries even tho data is there

### ISSUE THREAD

**Issue by poeticjustice** [SocialEngine/phpv4-issues#593]
Everyone look in your MySQL database now, got engine4_users_fields_search

Now look at all the NULL entries

Once identified loads of NULL entries look at that users ID number

Goto that USER on your site, looking at the profile signup answers attempt to search that USER , they will be unsearchable.

even tho your actually seeing the data they entered, The option ID's have not been added.

WHAT IS GOING ON

**Comment by Elshara** [comment]
I've no idea. Just probably a simple redirection issue.

**Comment by poeticjustice** [comment]
@Elshara when users signup and fill out the form, its NULL some entries of what they select, but the entries are shown on the site, but those who are NULL cant be found in search.

what could be causing this

**Comment by Elshara** [comment]
Search getting data from field entries which are not from the same data stream.

**Comment by poeticjustice** [comment]
@Elshara sorry i didnt understand the above?

**Comment by Elshara** [comment]
That's my guess anyways.

**Comment by poeticjustice** [comment]
I think the issue is 
Profile Questions

Example of the problem what i think is the issue.

Admin sets up profile questions Skills (Not shown on browse members).
User Signs up
User enters skills
more members sign up
more users enters skills
Admin decides to show skills searchable on browse members
****(Skills added to browse members)****
Everyone user who signed up before Admin adding this to browse members, is unsearchable for them skills.

**Comment by poeticjustice** [comment]
Yep

After more testing I can confirm this, to replicate do this

Use Gender profile question set to (Hide on browse members)
Sign up and select a Gender - for this example signup as Male
Now log in as Admin and click Edit Gender question (Set to show on browse members)
Now goto browse members
Search Male

it will return with NO members found.

-------
another test could be this
--------
Gender profile question originally set to (show on browse members)
Sign up and select a Gender - for this example signup as Male
Search browse members, goto Gender and select Male
Male users will show up
Goto profile questions as admin
set Gender to (Hide on browse members)
save
then edit it again so Gender is (Show on browse members)
Save
Goto browse members, select gender, set to Male............... No Males will ever be suggested.................... unless they signup after doing this excercise

**Comment by poeticjustice** [comment]
Here is a video http://sendvid.com/8apytcfd
or download video here https://we.tl/BZzjHcg0ry

I believe the issue i have detailed out here, was a bug raised back in April 2015 that was closed and not looked into 
https://github.com/SocialEngine/phpv4-issues/issues/24

SE for browse members is NOT searching the profile fields of each user, but creating a new database in engine4_user_fields_search, but based on the hide on browse members page / show on browse members page.

THIS KILLS ALL SEARCH FEATURES IN BROWSE MEMBERS, as from the very start everything needs to be set to show on browse members page. If you so much as accidently hide, or hide from testing purposes, it deletes all records of that field, which then becomes unsearchable when you set back to SHow on browse members!!!!!!!!!!!!!!!

extract from https://www.socialengine.com/features/php/core

Browse & Search
SocialEngine allows members to easily navigate your site, discover new content, and find specific posts.
Browse members
Members (and optionally visitors) can browse through your entire member list. Results can be filtered by profile information, like location, age, gender, height, occupation, etc. You can also choose to show only members that have a photo and members that are currently online.

**Comment by Elshara** [comment]
That is interesting.
So essentially every time you update a setting, it effects search
results from the effected date.
I wonder if this could mean search results actually originate from
database update changes, rather than existing database fields.

**Comment by DonnaScriptTechs** [comment]
Is this the same as your other reports? It seems the same as the other ones. If it is the same, it's better to update the original bug report so our technicians working on that one have the info.

Thank you for your contributions.

**Comment by poeticjustice** [comment]
Closing this its in connection with #592 but unrelated to other bugs mentioned, just in a similar area

**Comment by DonnaScriptTechs** [comment]
Thank you!

**Comment by Elshara** [comment]
hmm
