### ISSUE TITLE
youtube and vimeo and ebay and insta specific questions

### ISSUE THREAD

**Issue by JonSimon93** [SocialEngine/phpv4-issues#594]
**first post, but im hopeing this be considered for enhancment.
like twitter specific question, im after one for youtube and vimeo, possible instagram and maybe ebay.
be great if users signing up could just put their usernames or id in, like the tweeter specific question.
i know you can use website question, but that requires the whole link.**

**Comment by Elshara** [comment]
Would you be interested in the feature to automatically detect the kind of link inserted if a user enters it? Or just the ability to have a user place their ID in a text field marked specifically for a type of site integration as you suggest.

**Comment by DonnaScriptTechs** [comment]
Hi and welcome to our Github Repo. :)

There is a request already to add Instagram for profile questions. Is that the sort of thing you want for Youtube and Vimeo? 

It sounds like you want many different options for adding an ID. This would be quite a change to make as it would need to know each URL to grab. It could be possible, I think (not a core dev), if we could have the base URL (such as https://youtube.com/ ) added by the client in Admin setting and then all the user has to enter is their ID for each thing. 

I don't know how much interest we would have from other clients for this but our core dev team does look at each request to see how well it could implement and how many it could benefit.

**Comment by Elshara** [comment]
I for one wouldn't be opposed. In fact, it would actually only
increase integrations a lot better especially if any embedded service
options for links became available. So you could interact with some
aspects of the service right from someone's profile page. Similar to
how socialization works in the modern web.

**Comment by gsf00001** [comment]
Can there be a list of Social Networks that ADMIN may add to, as well as enable/disable?  Yes I realize that items may be added to the Profile Questions, but that doesn't standardize things (ex. if SE and/or 3rd-Party Devs wish to use this info, it obviously won't be consistent - or am I missing something?)

**Comment by Elshara** [comment]
Profiles aren't really dynamic yet in terms of structure.

**Comment by poeticjustice** [comment]
@JonSimon93 if you read my post here https://github.com/SocialEngine/phpv4-issues/issues/565

it will tell you exactly how to make these files and features in 5 mins,

Just replicate but change specifically for your purchase, they fully work, now errors, work on browse members etc.

This is an alternative if SE doesnt do it

**Comment by Elshara** [comment]
I just seen in another thread SE is significantly improving search and
that this issue will be fixed in 4.9.

**Comment by Khushboo016** [comment]
Hi @JonSimon93, Thanks for the good suggestion! we've added this suggestion at our end for internal team discussion regarding its implementation in future releases.

Thanks & Regards!

**Comment by Elshara** [comment]
:)

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#43

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
