### ISSUE TITLE
fontawesome or icon for profile signup questions, and shown on members info section

### ISSUE THREAD

**Issue by JonSimon93** [SocialEngine/phpv4-issues#595]
id love for this to be enhancement.
profile fields on profile and also on signup looks dull, could there be a way to enhance this soon.
it would be great to add fontawesome or icons to questions.

example twiiter question, it would look lovely for a icon fa-twitter instead on the text saying twitter or to show the icon fa-twitter first then text saying twitter, followed by the answer field.  
website field would look nice with fa-globe icon prior to wording and answer
gender fa-male and fa-female

etc etc etc etc

**Comment by Elshara** [comment]
So would you be interested in the ability to add a profile image to be able to further attune profile question fields? Or perhaps even another file type?

**Comment by poeticjustice** [comment]
I love this suggestion.

What you basically mean is, when creating a profile question, your given options like name, description, if required, custom css, 
You want an extra option for font awesome icon or even file location of an icon.

Once typed in file location or font awesome code 

You will see on sign up

(Font awesome icon) (Name of Question) ......(field for selection of entry)

Love this!

**Comment by JonSimon93** [comment]
exactly that of which you describe, yes.
here is a mockup of my enhancement idea suggestion
![profile](https://cloud.githubusercontent.com/assets/26391415/23931778/e518a666-092b-11e7-9715-0d3e67b752b8.jpg)

**Comment by Elshara** [comment]
Only work around at the moment is to use file media manager in
combination with adding custom CSS where the field selector is for a
custom CSS class. It works but it's a dirty hack.
I'm used to the dirty hacks. When you come from Ning, anything feels
like a breeze in comparison. And yet I can even add custom rendering
support via CSS two because the browser can just display it as a
custom image.
A text editor would fix this problem if we had text editor support for
composing questions. Like TinyMCE, or CKEditor or some other HTML or
BBCode Mark Down editing tool. Even wiki mark up would do just fine.

**Comment by Elshara** [comment]
Icons are easy enough to find or get. If you're like me, just use the
custom ones arrow chat, comet chat and other places emoji's exist. You
do realize text based icons exist. You just need Japanese Unicode
support for them to show up. I might switch, and they do show up in
questions.
emojipedia.org is a good place to start for text icons.

**Comment by poeticjustice** [comment]
Love the mock, that makes it look 50 times better.

@Elshara I thought the custom cas field in questions only control the actual box i.e. Height width etc

**Comment by Elshara** [comment]
You should be able to attach a background image to the custom class
name though using a div.

**Comment by DonnaScriptTechs** [comment]
We do have font-awesome coming in 4.9 :) . I've not checked to see if it's in any of the profile areas.

**Comment by Elshara** [comment]
Awesome. Always lovely to hear from you, Donna. I had no idea it was
in the works. My apologies.
And when Spring and Christmas collide...you get results.

**Comment by poeticjustice** [comment]
Would be awesome in the profile area like @JonSimon93 mentioned, makes it look slick and more pro, with the simplest of touches ;)

**Comment by Elshara** [comment]
Still waiting on the ability to embed raw html for profile area.

**Comment by Khushboo016** [comment]
Hi @JonSimon93, @poeticjustice, @Elshara, This feature request has been added to our internal feature tracker and would be considered in future releases. 

Thanks & Regards!

**Comment by poeticjustice** [comment]
niiiiiiiiiiice @Khushboo016

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#61

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
