### ISSUE TITLE
Search Fails To Display Results On Any Other Page

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#597]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Add any type of search module to a page other than the browse page. Custom page for groups search field. A profile page for members search. Forum page for blog search. Any type of search module on anything other than its native browse page. Using the layout editor.
2. … Try to use it to search for something. Then use the search function found using the exact same module, but on its native browse page.
3. … Record the differences. Social engine by default comes with 9 plugins to test this on. Forums, blogs, groups, events, photos, music, videos, polls, marketplace and the core members and site wide search modules as well. This can also be duplicated for third party search modules two.

What happens?
-------------
… If search modules are placed on pages other than their native browse pages, they don't work at all, even though the module itself displays fine.

What were you expecting to happen?
----------------------------------
… To be able to make custom search pages for each module to make modules load better. Even with the custom content module assigned to all of the pages where the extra search module is placed, search will not display results.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Search should be found in multiple places depending on where you are on the site to make it ideal for primary use.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by poeticjustice** [comment]
I added search and content widgets to a new page, when I did a search I found it completely went to the original search page rather than stay on current page! Am I doing this right to replicate matey?

**Comment by Elshara** [comment]
My tests confirmed, some modules do this while others just don't.
For example the member search widget does this. But the groups widget does not.
Others just behave variably.

**Comment by DonnaScriptTechs** [comment]
Please wait for 4.9 release as our search is improved.

**Comment by Elshara** [comment]
Claps hands in appreciation.

**Comment by DonnaScriptTechs** [comment]
Note that the global search box is for a specific page. Each module has its own search. Please see our tutorial for which widgets are allowed on which pages (which has been updated and should be available soon).
