### ISSUE TITLE
Make Pagination For Default Widgets Possible

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#598]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Add any new or popular widget of any module installed to any page using the layout editor.
2. … Save the changes and browse to the page, making sure you have the correct permissions to view or interact with it.
3. … Notice, the profile widgets contains pagination. But any other new or popular widgets do not.

What happens?
-------------
… No pagination is displayed to view more items, or navigate between previous and next items depending on the number of how many items the module retrieves per widget load. This is defined in the item count setting once the widget is first added to a particular page.

What were you expecting to happen?
----------------------------------
… For pagination to be possible to be able to scroll using all widgets containing new or popular posts. Like that which is already possible using all profile widgets of groups, events and member profiles.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… All widgets should open a settings box prior to just being added where ever column you put them in. For example, only the HTML box does this, whereas all widgets should open their own respective box, so you can configure settings right away. If you accidentally added the widget, just clicking close or cancel or ex should cancel the box automatically if it is already opened.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by Khushboo016** [comment]
Hi @Elshara, We have not provided pagination in popular and recent type widgets, as these are meant to display the top most popular and top most recent entries of a module. 
And we would also like to let you know that in 4.9, there would be a "View More" button in each recent and popular type widgets clicking on which you'll be taken to the Browse page of that module and you can choose there to browse the entries either by "Most Viewed" or by "Most Recent".

Thanks & Regards!

**Comment by Elshara** [comment]
The reason why I was asking for the feature, was because I wanted to
make a custom page with pagination containing specific widget
displays.
For instance. You can't, using the default set up, browse items in the
following ways.
By existing online members for all modules.
By latest activity per module.
By the assortment of ascending or descending item order.
By alphabetically filtering results.
By number of page views.
By number of likes.
By number of comments.
By the amount of words a post has.
By increasing or decreasing how long a media file is, video, song etc.
By the number of listed participants a particular post has.
By the amount of posts contained within a parent item, such as a photo
album, group, event and so on.
By however many entries a particular person has made, and a list of
each entry that person specifically has made as its own tag or
category.
By how ever many categories or tags a post has.
by the list of posts made by friends, groups, events, networks you are
a member of or any other parental data stream such as an on-going chat
room or discussion or something you follow is mentioned by account
association.
There is no way to sort items or display items based on existing item
data at all. Not even being able to sort the data you do receive. So
it is important to have the ability to display posts using modules,
you'd not normally be able to do using the default home page method.
Putting no item count limit in the post module itself under its
settings based on whatever page in the layout editor you place it on,
essentially means you can't control how people interact with the
posts. You can only give them a teaser of top posts, or give them a
limited amount of data to choose from. Some people like dedicated
pages to perform specific tasks. Be it specific module search, a
specific static order in which posts display themselves, and of
course, the ability to load more posts from the same member, the same
module, or by choosing different module categories if you include them
in a menu somewhere, containing a list of static pages, where such
posts can be found and easily accessed. That is the functionality I
was trying to achieve using the modules on other pages throughout the
site.
To give you an example, lets say I'm reading a blog, and want to know
what people are talking about after giving the blog or other module a
comment and a like. I don't want to have to scroll back all the way in
order to be able to gain access to another page so I can view the
latest activity feed, especially if I can just look at a glance based
on what all new has happened. For sites with lots of activity
happening, such a feature is essential. It keeps people reading
because of the simple fact, something is there for them to click on,
as a suggestion. A way of offering something to a group of users
reading a specific page. It isn't my first choice, but as a secondary
one it will have to do. My primary interest point would be
accomplished by establishing the means to be able to display data to
people based on pages they've already visited. Only showing all data
if no other suggestions interest the user in what they are currently
trying to achieve, assuming they are on a specific page for a reason,
of which the page was conceived, to be able to provide and perform its
intended purpose.
In order for me to achieve this, I have 3 options. Install some third
party widget to try to get people to understand there's something in
relation to them they might be interested in reading. Similar but yet
different to how the related and other videos by member feature works,
but only for that module, whereas I want the same functionality for
other modules as well. I can either place the browse menu or main
module menu on the page, as it is not included by default. So people
have the choice of adding something if they wish. I can place a module
search widget somewhere in hopes someone uses it. But I need a sure
guaranteed way people will regularly find information, without
actually having to click or be mindful of where they are on the site,
so such information which is actually relevant to the time they spend
on the site, can actually present itself to them. In order to make
that happen, my only sensible option is to place such modules on the
view pages of all site features. But there is no way to have users
interact with said modules, to load more data from the initial item
count each module has. The first reason is because pagination doesn't
exist. The second, is because if you load more than one module, and
say you put up 10 results. Any more results you place there, if you
put 15 or 20 or just leave the fields blank, display everything. It
makes the page not load at all, which is counter productive to the
module even existing. So without the ability for the module to have
flexibility, all it can do is be useful in one way. It can't be useful
as an informative tool for long, because once a user sees the most
popular post so many times, they get bored with having to scroll, and
then find out they can't scroll so they lose interest and don't look
at it. As for the new module, displaying the most accurate data, it's
useful if you have an active website, but you can't do much with it
either if you don't or can't get your website to be active by trying
to convince your existing user base, or search engines, to notice you
as some one having something to offer, somewhere to go, to stay, to
participate.
If you want to display data to users they haven't looked at yet, or
could reasonably suggest something relevant to the user in a way they
would love to participate, kind of like a set of directions. After you
read this and had enough, try this and see if you enjoy it. The idea
is to get them clicking, responding, interacting, but not have the
data be annoying, or suggest the same thing. It needs to be never
static, always dynamic, be simple in nature, relative, constantly
adapting to its environment. The only modules which move data around
presently, are ones which only really exist within the portable
widgets you can place on pages. But they have no way of scrolling more
items, or being able to include a sense of pagination if you were to
ever need to expand the data it can retrieve. Putting an activity feed
on the page, does not help matters. It just shows the time the blog
and its comments were posted, giving you the non functional option of
adding something to the feed via a status update. So it's practically
useless.
The widgets either need to go, or they need to be useful. Otherwise,
who would really find them useful? On the front page, or any other
static page, they might have a chance at being used. The only problem
is, they have to be able to load reasonably well, and if it takes your
browser 5 minutes to load 300 items because social engine is so slow
to begin with, what's the point if you don't have any flexible room to
work with? You need to have therefore, an existing, fast, alternative
option, installed on your site, ready to go, to engage front and and
back end action. There isn't one presently, not even with all the
third party developers making advanced module plugins. I think
personally such things are a major rip off, because all they o is bog
your site down with useless information which also, has no way of
stream lining its visibility. A visibility problem which actually, in
retrospect, can easily be navigated better using a tool such as PHP My
Admin as opposed to social engine. Hows that for a wake up call? So
instead of social engine performing what its intended purpose is
design for, it is having to compensate for out of date coding
practices, static modules and poor content ratings because members,
who are smart, through the helpful guidance of search engines who
already know so prior to showing such potential members who are
searching at this very moment within the target audience your site is
based on for assistance, realize there are other services which can
move their idea in better positions than a social engine site ever
could presently. The database tool has a better chance of displaying
relevant information to the interested online party, as opposed to
social engine's version of a widget which isn't responsive, doesn't
get people using it and has a rigid form which is unable to change
with its environment.
What you're planning on doing for 4.9 is basically giving the widgets
even more reason to be useless, and less of a reason to prove useful.
Adding a more link indeed. Well it's a start, but I think, in the
wrong direction, not the right one. Simply because this is due to the
fact, nothing exists for users to compensate the lack of things to do,
once they've done whatever it is which got them interested in the
action anyways, for them to repeat such action on other posts, for the
interest required to keep people socially engaged. And that is just
the foot of the mountain.
At its head or its peak, every social engine website requires some
kind of draw. People could upload the entire internet to a social
engine website, and never be able to browse the latest second of
information simply because the filter hasn't been made for the front
end. The back end is hardly better, with no ability to manage bulk
actions per user or per module, it is no wonder appearances tend to
have sway where ever the world turns to shift its focus. Focus, is the
key here. If you can get users to focus on your site, they must have
some sort of resemblance of an incentive to want to do so, if they
already have completed what they wanted to be able to do in the first
place. That's if they have any time to, what with peoples lives being
as busy as they are. If they can't do something on your site related
to what interests them to go there, they won't stay for ever as an
active member.
No social engine site has active members with out the possibility of a
reliable community to keep them alive and engaged. You need tools to
carry out the engagement of willing minds to comprehend and absorb
data. To be able to share it with the potential reach of billions of
other willing minds wanting to know what it is like to be engaged, so
the circle may complete itself. Social engine, has to become more
social and focused on its ability to ensure people have something to
look at. And less likely to bore users with poor performance. Even
forum boards have statistics to keep members engaged. Unfortunately,
not even the statistics plugin widget in social engine can even
display links to the most popular content, or even links to anything
at all.
Do you now see the point I'm trying to make here? I say everything on
a need to consider basis, so people can stop going to Ning, phpfox,
word press, dolphin pro and other places to achieve the front end
appearance social engine could deliver by default by making such
changes possible.
With this in mind, are you prepared to risk something which could
improve social engine sites, moving them forward along the same ladder
other providers have managed to do for a long time? Simplicity and
paying attention is the key here. I hope you know what you're doing.
I'm just not sure about the direction change is going right now. I
wouldn't want to be left behind because all I would need to be
productive ideally, is a platform which can move independently, giving
people the freedom they seek, the answers they need and the
entertainment they desire, to want to progress through communities on
the web independent of Facebook, Twitter and other social gatherings.
They've had help, yet developers are exactly the kind of help which
can bring success to peoples lives, as they already know how to look
for, so they are able to find it, based on the experiences they've
had.
It's up to you. I'm just reporting what I see.

**Comment by DonnaScriptTechs** [comment]
Please check 4.9 and up as we have "view more" or "view all" links in the widgets now. If you don't see the ones you wanted, please submit a new feature request in our new feature request area.
