### ISSUE TITLE
Some Pages Don't Properly Align Themselves Accordingly To Module Or Database Changes

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#599]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Add a third party module widget to a page.
2. … Uninstall the module as best you can, including all database values, files and settings.
3. … Go to layout editor and attempt to remove the page module you added prior to installing the third party module.

What happens?
-------------
… If the widget belongs to a tab container, or is added to global areas, header and footer, the widget cannot be removed, the remove option does not become available and the widget is reported as missing. If you try to add a new page from the layout editor, after manually removing the page the module installed was associated with, you will come across a major bug. The page itself will fail to be created, and the only way to remove it would be to do so from the database, as trying to even view it causes a system crash. If you're lucky, sometimes you are able to view the page, if the module was able to be somewhat deleted, you will discover the page looks extremely distorted. Columns you think don't exist, do exist, even when attempting to adjust the number of columns present. The columns displayed in the layout editor, do not coincide with the live view of the page if you attach a URL link string to it. And, modules don't keep their settings if any new modules are applied to the page. The only solution is to find a way to remove the entire page ID from the database, currently not possible in Social Engine. You can't just remove the page from the pages area, you have to completely remove all traces of it from ever existing. In short, if you install a third party module, you can't expect it to completely be uninstalled even after running all database queries. The layout editor does not let go of page settings based on page ID tags, found within whatever configuration variables it sets when ever new pages are created. The creation of pages here, keep their settings for ever, so even when removing a page, you can't just wipe over its ID, because every time you go to create a new page, the ID gets recycled, but the settings from the previous use of the ID still exist. Therefore, creating a lot of very serious looking error reports in the error log.

What were you expecting to happen?
----------------------------------
… For the layout editor to not be a disaster when making new pages if a module happened to be installed, or uninstalled, regardless of such a state of activity.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Don't hit the uninstall button. If you don't like a module or its functionality, you're stuck with it for the duration of your social engine database.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by Khushboo016** [comment]
Hi @Elshara, we just display "Missing Widget" in the Layout Editor for all those widgets for which the associated third party plugins are not found installed on the site. There is no option provided to remove those widgets because for this a long script needs to be run in the background to check which 3rd party widgets are associated with which pages of the site, which would need much processing, so, we skip this processing as leaving these widgets as missing widgets in the Layout Editor does not cause any issue in the front-end of the site and if you need you can drag such widget and drop it out of the layout of the page to remove it from the Layout Editor. 

Thanks & Regards!

**Comment by Elshara** [comment]
A database query brought those widgets into existence. But there's no
way to remove them without knowing blindly where the database stored
their settings? It's insanity.
I say, without the widget files in progress, they should just find a
way to cancel themselves out from being able to exist making the
queries a waste of space, but a more productive one than the mess they
leave once uninstalled.

**Comment by DonnaScriptTechs** [comment]
This should resolve once we implement the other feature request to fully remove plugins. I'll close this for now as we've already got it added to our list to completely remove a plugin.
