### ISSUE TITLE
Deactivated plugins still load their email templates

### ISSUE THREAD

**Issue by alx2bgx** [SocialEngine/phpv4-issues#60]
Hi ! 

I use 36 different plugins on Bougex.com

Email templates are a big mess in  /admin/mail/templates

It's very hard to find the good template. 

1) Even desactivated plugins are showing templates. 

2) We should be able to regroup them by plugin. It will be easier to find !

Thank you

Alex
Bougex.com

**Comment by Anshuse** [comment]
Hi @alx2bgx ,

Thanks for bringing this to our notice.

We've reported this issue at our end for internal discussion and we will work on this in near future.

Best Regards,
Anshu

**Comment by smazurov** [comment]
Great suggestions, we'll start with fixing an issue with deactivated plugins still loading their templates and consider your other points as possible enhancements.

**Comment by Elshara** [comment]
This isn't just present in email, it is also present in other files, css, database queries and they load even though disabled. Also, when plugins are disabled, they still appear on pages that used to house them and sometimes when a certain plugin is enabled like advanced members or advanced comments, it disables the native plugin which doesn't get enabled when the plugin is disabled. A more serious problem occurs when such plugins do not remove their listed pages from layout editor even when removed. This results in a huge database edit which shouldn't happen. There should be a much easier way to clean up both cached and still dormantly active positions for disabled plugins. When it's disabled, an option should be there to remove it which would remove all data entries, files and queries associated with it in its entirety. Currently, this doesn't happen at all.

**Comment by shivani2910** [comment]
@Elshara Regarding ```"sometimes when a certain plugin is enabled like advanced members or advanced comments, it disables the native plugin which doesn't get enabled when the plugin is disabled...."``` : If you install a 3rd party plugin and they ask you to disable any of core plugins manually or their script does so, then it's upto you that when you want to get the core plugin enabled again on website. It can not be automated.

Similarly, if you disable/remove a 3rd party plugin and some of it's pages still exist then you can contact the respective developer for this issue. If anything like this happens with our core plugins, please tell us.

As we've already mentioned that we'll fix an issue with deactivated plugins still loading their templates, activity feed settings and also consider the other enhancements. Thanks.

**Comment by Elshara** [comment]
That's good to know. Yeah some theme templates do this when disabled,
they modify core files so I'm just saying when you modify things to
the point of no return, that's where and why I've posted this as a
general overview. There's no getting away from a bad theme or plugin,
usually plugins are self contained however when it comes to themes,
that's where things start to change.

**Comment by DonnaScriptTechs** [comment]
This is fixed for our 4.9.0 when it is released.

**Comment by Elshara** [comment]
Awesome!
