### ISSUE TITLE
Layout Editor Allows Deletion of Core System Pages Which Breaks Site

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#600]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Make this one vital mistake here, and you have to completely wipe all data and reinstall everything!
2. … No exceptions, as far as the front end is concerned.
3. … Your members and visitors won't be bouncing back from this any time soon.

What happens?
-------------
… This is one very good reason to back up everything you ever own! Go to the layout editor, and remove any system page. Doesn't matter if it is the home or landing page, member browse page, blog page, any core or module page you regularly use. Say, you are in the middle of removing some extra pages you don't need. Well, every time you remove a page, you are asked prior to its deletion if you wish to proceed. Perhaps you were in the middle of cleaning up your website. Well, every time you remove a page, guess where you are redirected to after the confirmation of the page is removed? Your landing page. Say, you accidentally click delete on this, or any other system page. And you happen to click okay, when you are asked, are you sure you would like to remove the page? No warning or anything it is a system page, and not a user created page. You have just condemned your website to permanent suicide! There is no recovery. No database alteration to recreate a custom landing page, or system core page. No way to duplicate it even if you get all the modules in order. It is a one way ticket to crash and burn your social engine site and there isn't anything you can do about it. That, is, a, fact! And this bug has been around since social engine version 3. Over 7 years ago! It still exists to this day.

What were you expecting to happen?
----------------------------------
… If you have Cpanel, get ready to dive into root access into WebHM, because you're going to need it. First of all, back up your site if you have the means to. Don't be a web owner and not think you'll be fine without it. This, is the only way you can have a chance, at getting your data back up and running to move forward with your website. If you don't know what you're doing, don't play with the layout editor! You only get one shot at this. So be very, extremely careful who you set as admin, super admin, moderator of your website, even if you are aware of the dangers of such a non full proof way to get your site knocked offline. What ever you do, fix this or for ever hold your peace. This is not something any user created work around, can ever make better again. Not a simple fix you can live with. So if you want to know what is expected to happen, either back up your website, or help me ensure this bug gets resolved as soon as possible. Add your voice here to say no, to permanent website problems.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… I can't stress how important it is, to not delete system files. Social Engine is way too immature of a platform right now to even consider the ramifications of doing so without a complete reinstall. It doesn't know what to do if its precious Xend framework platform isn't intact, which is severely outdated at the time of this writing. Just be warned, know what you're doing before you touch admin settings of any kind. You might think a module looks cool, or a page needs to be removed, but always, remember to back up your work before going settings hunting. Always keep a log of who is admin, when they are online, and what changes they make. There are lots of ways to break social engine, which usually require a major file replacement or a database value to be overridden. But this is one such error, neither can fix.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by Khushboo016** [comment]
Hi @Elshara, Deletion of core pages is not possible in via Layout Editor. There is an option provided to delete core pages in Layout Editor but the pages are not deleted even if we delete them using that option. And we would like to let you know that in 4.9, that option to delete pages would be removed from all the core pages to avoid any confusion.

Thanks!

**Comment by Elshara** [comment]
Awesome! Thank you.
