### ISSUE TITLE
Emails are going into SPAM or Junk folder.

### ISSUE THREAD

**Issue by rkrathor** [SocialEngine/phpv4-issues#601]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. Sign up into test.crezilla.com
2. Verification mail will go into spam or in junk folder.

What happens?

All mails using SE mail service are going into spam or in junk folder.

What were you expecting to happen?

It should go to inbox as regular website mail go.

Any other comments?

I just wanted to know , is there any setting or solution to avoid this?
I have checked with my email provider and everythings has been done from there end.
DKIM and SPF are passed now  but mails are still going to spam or in junk folder.

So is there anything we can change or work in SE to resolve this problem?

What versions of software are you using?
----------------------------------------
**Operating System:** … AWS linux.

**SocialEngine PHP Version:** … 4.8.8.

![screencapture-mail-google-mail-u-2-1489557368701](https://cloud.githubusercontent.com/assets/10502380/23942866/a1583460-0993-11e7-9f36-d634f4ffbd71.png)
![screencapture-mail-google-mail-u-2-1489557348632](https://cloud.githubusercontent.com/assets/10502380/23942873/a6ac980c-0993-11e7-903e-7f707349c6ec.png)

**Comment by DonnaScriptTechs** [comment]
Generally, emails go to spam due to the email program filter or the isp labelling it as possible spam. On my own sites, I avoid that by using Sendgrid (or other transactional mail services) and I have a 100% delivery rate. 

Here is a tutorial that should help you, http://support.socialengine.com/php/customer/en/portal/articles/1643190-basic-email-troubleshooting?b_id=14386 .

I don't believe this is a bug in our script as my own sites have a 100% delivery rate that doesn't go to spam folder.

**Comment by DonnaScriptTechs** [comment]
We also suggest that you download the current version 4.8.13 from your client account and upgrade as it's best to be on most current version.

**Comment by rkrathor** [comment]
@DonnaScriptTechs thank you for your reply, let me check. want to upgrade but can be tough for me because of design changes.

**Comment by DonnaScriptTechs** [comment]
If you used a clone custom theme, it should be fine to upgrade. I suggest backing up the site first, and making a separate backup of the theme files too.

**Comment by rkrathor** [comment]
@DonnaScriptTechs that is a nice thought , Can you suggest me how I can do that?

**Comment by rkrathor** [comment]
@DonnaScriptTechs Don't you think applying those changes again will be tough task?
I create new widget and pages too, moreover whole new modules.

**Comment by DonnaScriptTechs** [comment]
It depends on how you made them. If you edited core (which isn't recommended) then you would have to reapply them. If you made your own modules, then you might have to update the code if you used older methods. 

I suggest making a development clone of your site and doing the upgrade on that. It's never a good idea to stay on older versions as you risk missing important fixes and updates.

You could also wait for our 4.9 to come out before upgrading, but still use a development site first. This avoids issues on your main site from upgrading without testing.

**Comment by rkrathor** [comment]
@DonnaScriptTechs is there any link or tutorial to take backup and clone of Site?

**Comment by DonnaScriptTechs** [comment]
Most hosts have tutorials for how to back up but we do have one, http://support.socialengine.com/php/customer/en/portal/articles/1641112-making-and-restoring-backups?b_id=14386 . It would be best to check with your host though as they would have specific tutorials relating to your hosting since it is a hosting issue.

Regarding a clone, I didn't see a tutorial for that. You could ask your host to make it for you by copying your site files and database if they do that sort of thing.

**Comment by rkrathor** [comment]
@DonnaScriptTechs thanks this is I know how to do (A seprate backup of files + Database), I was thinking if there a simple procedure from Admin of SE.
Thanks For you time and suggestion.
Its really helpful.

**Comment by poeticjustice** [comment]
What server are you using, i have dedicated and never hit spam, went straight to inbox from day one,

Also used track delivery in cpanel to see all mail.

make sure DKIM set up correctly.

Shared servers have a higher rate of already being on spamlists before you even pay for it.

**Comment by rkrathor** [comment]
@poeticjustice 
Using Amazone for hosting
for mail Go4hosting
Dkim SPF and Dmarc are set.
Mine is a shared for mail service.

**Comment by poeticjustice** [comment]
check your server ip address on mxtools site for email spam list, it will check which spam list that shared ip is on

**Comment by Elshara** [comment]
I'm using a shared server from Name Cheap. I never had any spam problems either.
What I'd suggest is getting a dedicated server IP address. If your host offers it, may be under add on packages.
