### ISSUE TITLE
page_title handling inconsistent vs. instructions

### ISSUE THREAD

**Issue by cgcb** [SocialEngine/phpv4-issues#603]
Following the instructions in the SocialEngine PHP software, as well as help docmentation on the web, a page title can be localized by adding a key phrase to custom.csv that matches the entry for page title in the General Settings page. See this KB for details: http://support.socialengine.com/php/customer/portal/articles/1645737-admin-panel---settings-&gt;-general-settings

What are the steps to reproduce this issue?
-------------------------------------------
1.  I set the page title to "FOO" in the general settings.
2. I add the following to custom.csv language file:

"FOO";"bar"

3. I don't add a logo to my menu logo.

What happens?
-------------
The site outputs the text "FOO"

What were you expecting to happen?
----------------------------------
The site should output the text "bar".

Any logs, error output, etc?
----------------------------

**SocialEngine PHP Version:** 4.8.13

OTHER NOTES:

Elsewhere, this translation works as expect with respect to the KB instructions. Just not in the site logo scenario outlined here.

**Comment by cgcb** [comment]
This also affects the alt tag for the site logo image, when there is an image enabled.

**Comment by Elshara** [comment]
I can confirm this bug as well.

**Comment by Khushboo016** [comment]
Hi @cgcb, @Elshara, we have added the issue in our internal bug tracker and will work on the fix.

Thanks!

**Comment by cgcb** [comment]
Great. I should also mention that since a language variable can contain HTML, the title tag should be sanitized as well.

Cheers!

Chris Brewer
President

Zavoodi, Inc.
Digital Creation for Web, Mobile & Social

P: (888) 742-3799
W: zavoodi.com and SocialNatives.com

Check out our software for SocialEngine

**Comment by Elshara** [comment]
Perhaps HTML purifyer might be able to do the trick.

**Comment by smazurov** [comment]
I dont understand - why are you not entering translated string as your title?

**Comment by DonnaScriptTechs** [comment]
@smazurov I'll look at this tutorial today and see what the issue is.

**Comment by cgcb** [comment]
@smazurov, because I want the title to be translated to different languages.

**Comment by Elshara** [comment]
I thought titles aren't located in language.csv file. Otherwise they
would translate just fine. Or would they?

**Comment by DonnaScriptTechs** [comment]
This is fixed for our 4.9.3 when it is released.

**Comment by DonnaScriptTechs** [comment]
We'll also double check our tutorial now that the bug is fixed.
