### ISSUE TITLE
Make All Site Admins Moderators Officers In Any Site Groups And Events

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#604]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Admin a test user.
2. … Create a group, event, or other post using your regular identity.
3. … Sign in as the test user you promoted to admin.

What happens?
-------------
… As an admin, you can't manage public places on the site including their settings and posting rights.

What were you expecting to happen?
----------------------------------
… To be able to manage all settings and posts as if they were your own depending on what you allow to have happen to be possible in membership levels.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Anyone should be able to send group messages to the membership. Same goes for events. Only group creators have the ability to do so. Any admin should be able to edit the groups settings same as they should be able to for all posts module wide, events, blogs, videos, photo albums, etc. Only creators of such contents have the ability to do so. The front end ability to remove a post should be visible to content creators and admins moderators on every posted piece of content site wide modules provide. The core should be integrated in such a way to allow it to happen without effort. Bulk actions should also be available.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by DonnaScriptTechs** [comment]
I'm testing in 4.9.1 and am able to edit the group as an admin user.  Can you please test that?
