### ISSUE TITLE
Allow Multiple Authors To Create Specific Posts

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#605]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Multiple author content would give members the ability to collaborate on posts together as a fun, interactive activity for your website.
2. … Such activity would be expected to have admin defined limits, whether a member has to be online with the other member to initiate contact, or whether posts can be created separately and joined or split into different posts by different authors later on. Or whether it is possible to build on a post someone else, unrelated, has to say as a fun thing to do.
3. … Multiple authors per post and or the ability for someone to create a post by means of using another post as a root base, would provide people the tools to build true friendships based on real time or individual input as per the interest of an archived yet interactive playground.

What happens?
-------------
… Currently posts can only belong to a single author or profile. If the ability to move posts to a new author or profile existed, any member who previously left the network, could regain their posts back either with the assistance of automatic approval, or the manual approval of the admin. Either way, posts could be recovered from deleted accounts or left accounts if they could be salvaged using a profile system which saves content if the member wishes it to be restored later on. All you'd need is the profile ID and or a way to verify the identity of the original author, to be able to retrieve the posts. Which is where admin approval would come in useful.

What were you expecting to happen?
----------------------------------
… A work in progress. But one I find to be an excellent suggestion so people can truly put the meaning of social, to social engine head on.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… All modules would be able to support this type of interaction as it would be built into the core. You could set which modules were allowed to engage in such activity in member level settings.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#62

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
