### ISSUE TITLE
Inbound And Outbound Share Options

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#606]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Many people see a reason to place outbound share options on their websites. This includes links to places where mass groups of people already are, such as Facebook, Twitter, Google, Linked In as well as other social options plus Email. However, since control of the Email Marketplace is such that everyone doesn't want something seen to be Spam to influence their main hub for notifications, an answer to such an interest for social engine website creators and administrators, as well as users, would be to have inbound share links.
2. … An in bound share link, is a button which has the ability to consist of HTML, or a custom link, which could be shared on other websites, linking to a piece of content, or profile address, on your website. So instead of links to content you post going to other places, other places carry the code where links that can be posted to your website, exist there, driving native traffic to your website. Importing posts and exporting shares from one website to another, is usually managed through plugins like activity walls, comment walls, or on its own. Outbound links may still be possible, however inbound links would drive possibilities further, as people could for instance, just share a link they see around the web, totally offline from anything to do with your social engine site, and place it right on their wall. It may be difficult to control what gets shared at first, but anything which does get shared no matter where it comes from, would go to your site for the full article, instead of going from your site to another to read or interact with it. Mutual sharing gives you one way, two way, three way and four way social control regarding how content is distributed and recommended to people. Especially, if someone were to take the idea, and implement it as a unified ID system, allowing browser plugins to have a one click share option, so whatever you see, goes with you, and also appears on your website as a members point of reference, interest and enjoyment for their friends and other visitors to check out.
3. … Outbound share links, is code which is placed in the form of a widget or HTML code, allowing you to share a link to a page you like, from your website to another. This would give a target audience, exposure from one site, to their invited participation of another. A shared login system, would make the transition easier, so they can in turn, drive your website onward to success.

What happens?
-------------
… Both types of share functionality, internal, external, inbound, outbound, do not yet exist.

What were you expecting to happen?
----------------------------------
… A keen interest for it to be possible.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Sharing makes the world more open and connected.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by gsf00001** [comment]
Until SE addresses this, does the new SEAO Advanced Share address some of your needs?  [https://www.socialengineaddons.com/socialengine-advanced-share-plugin](url)

**Comment by Elshara** [comment]
I looked at it, even signed in to their demo page.
It's a bit pricey. I've got the same functionality already pretty
much. Thing is, when I buy that plugin, I'd have to buy all their
other advanced plugins to go along with it. Just so members get
notifications about what was actually shared if I was to use the on
site sharing features. Especially when it relates to groups and
events.
It also seems kind of cluttered. I don't mean to say this in a bad
way, but every time I load a social engine add ons network or anything
associated with them, it takes a very long time to load their page.
I hope they fix that before I consider buying any of their plugins.
So, sorry, but no. It's just not my cup of tea.

**Comment by DonnaScriptTechs** [comment]
We added AddThis to 4.9. Please see if that has part of what you want. As this feature request contains more than one item, we cannot move it to our new request area as it breaks our posting rules. If you still have a feature you want, please open it in our new request area but limit to one feature per request. Thank you.
