### ISSUE TITLE
Activity Action Type Improvements

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#608]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Go to the activity action types page in admin control panel under settings.
2. … Browse through the items.
3. … The items listed here do not exist yet.

What happens?
-------------
… Settings should be inclusive so people understand better about what is going on, but people don't know about.

What were you expecting to happen?
----------------------------------
… See below.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… User Subject has updated their profile object. User subject liked post object where post object equals module specific action. User subject has updated their settings object. User subject has updated a post privacy settings object. User subject has updated a post content object. User subject has disliked a post object. User subject has updated a comment in the post object where post object equals module specific action. User subject has replied to a comment in the post object where post object equals module specific action. User subject has subscribed to a post object where post object equals specific module action. User subject has updated their display language object. User subject has updated their time zone object. User subject has changed their profile information object. User subject has been demoted to member in the post object where post object equals module action. User subject has been promoted to member level object. User subject has changed their profile type object. User subject has made an administrative change object where administrative change object equals specific setting updates. User subject has removed friendship with user object. User subject has removed a post object where post object equals module specific action. User subject has unsubscribed from post object where post object equals module specific action. User subject has left the post object where post object equals module specific action. Other variants can be added or edited as you wish.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by Khushboo016** [comment]
Hi @Elshara, The Activity Feed Item Type settings section is going to be improved in 4.9, the action item types would then be shown in a more organized way as mentioned in this Github issue: https://github.com/SocialEngine/phpv4-issues/issues/158. So, hopefully, this work done for 4.9 would help cover this feature request of yours.

Thanks!

**Comment by Elshara** [comment]
Awesome! Looks good.

**Comment by DonnaScriptTechs** [comment]
This is implemented for 4.9.0 when it is released.

**Comment by Elshara** [comment]
Awesome!
