### ISSUE TITLE
Unsubscribe even if not loged

### ISSUE THREAD

**Issue by alx2bgx** [SocialEngine/phpv4-issues#61]
When somebody receives an automatic email from our network (Frends request or what ever...) the receiver has a link to unsubscribe... but he has to login to detete its account. 

Could we have a direct link in footer of every of our emails to delete account without having to login ???

Would be great... Thanks !

**Comment by Vaibhavagarwal0807** [comment]
@alx2bgx : this is really a good suggestion and can be done too.

**Comment by shivani2910** [comment]
Hi @alx2bgx,

Thanks for your suggestion. We've forwarded it to our team for internal discussions.
Thanks for your continued support!

Regards
