### ISSUE TITLE
File Module Improvements

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#610]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … All file types need folders, or albums.
2. … All files and folders need individually view able files to explore.
3. … All files and folders must have the ability to comment and like them, or share them and view related content or other types of modular updates on each page.

What happens?
-------------
… Videos don't have video albums, or playlists. Music playlists don't have individual songs to view in their own page. Photo albums cannot be viewed individually as photos on browse page and there is no way to view photos inline as embedded into the page itself. There is no way to view embedded files of any type inline as things stand right now.

What were you expecting to happen?
----------------------------------
… This to be possible. As well as to customize the file types people can upload, including non media related ones.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… People will appreciate the updates.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#63

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
