### ISSUE TITLE
Updating Modules Duplicates Database Entries

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#612]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Install any module twice. Uninstall it once. Doesn't matter what one it is, third party, social engine core.
2. … Notice the database dramatically increase in size after each refresh, update, installation or uninstallation.
3. … Notice pretty much any database field is randomly numbered and not one of them shows as being active.

What happens?
-------------
… Have you ever periodically looked at the size of your database? If you think it is getting bigger because of user data, forget it. A huge percentage of what you see there, is old settings, unused information and conflicts of ID tags. You'll have to go into two or three layers deep to see the duplication effect but it is there, hidden in plain sight, and it's a gigantic mess. No, joke. Social Engine has a very incomplete, out dated and archaic system of database queries when it comes to the installation of data. It is 100 times worse than the Windows registry. It simply creates new queries with no regard to existing queries, so any change you make, it creates a separate whole system of repetitive tasks already existing and in working order. No matter what setting you change, or update. When installing updates, even refreshing packages, complete duplicate entries as if you were reinstalling social engine to the same database, exists, making huge unnecessary database queries causing the database to be seriously bloated with unused information. The more you upgrade or refresh your system, your database instantly doubles in size. It is impossible to know where to start cleaning up the database, because you don't know what fields are active, and what ones are not. But the existence of old fields is not recognized as the new fields take priority, so removing them if you wish to, add a page to the layout editor for example, becomes bloated with missing modules from a previous uninstall and or bits of empty columns still exist when adding new pages due to direct ID conflicts with duplicate database entries and phantom installation settings of a previous instance, sometimes making the page itself impossible to even view. When ever you make any change to your network, update a setting, change a modules layout order, the database does not replace the existing field data. It will just create new fields for it. It does not recognize existing database field entries, especially concerning settings and existing working complete modules, causing your entire system to populate very quickly with unrecognized, unused and corrupt data cells. Such as ones which seem harmless, for instance, when viewing things like activity logs, or viewing the progress of the task scheduler. Perhaps, even, the statistics count. You may think when you delete an item from the network it is actually being removed, but all it is doing is actually adding 4 times the amount of database queries. One for removing it from the index, appearing in the logs area. One for keeping the ID alive, view able in the specific module information tables area. One for any previous versions of such a page, such as a blog or its comments to actually add themselves to its own data fields in the modules area. One for updating the statistics area with up to date information, which gets updated not only during a task scheduler process, but also all previous records of statistics are still within the database. Luckily, only records of past number counts are there. However, when doing more complex things like viewing how many times a task has run, here is where the data really starts to pile up with corrupt or unused information. When ever two tasks are happening at the same time, there is only so many database connections social engine can handle at once. AS new things get updated, logs exists to record the update, both in a file, and in the database which updates the file itself. This therefore requires monitoring of both file and server storage space, as well as the database for any sign of change. Leading to lots of bloated information still existing within not only the logs, but also extra indexing queries located within the database in the areas the delete command never penetrated, because it only currently can manage one thing, the index directory section of the database. So when ever a task is run, a log entry exists for both the current statistics of such a time, as well as the current statistics from the time the site was born, until now. So really all you are clearing, is the files section of the task manager. One of the most prolific areas to clear, is the cached data areas. The usual logs exist for the item, but a record of how many times the process actually ran also exists in several places, not just as a statistics record, but also as a main processes record as well. Cached data only includes files, not database entries, so when clearing the cache, all you are doing, is actually making it twice as difficult for the database because it now has to make so many other requests just to retrieve information, as the cache resets itself in addition to the connections it is already making automatically, and when ever a user views, edits a setting or adds a page full of data. Several records exist of such an entry in different simultaneously updating, duplicating and replicating aspects of the database, causing the bloatware to be so serious as time goes on. This has to stop. And if this somehow is some kind of a back up system, it is far from being a failure or a success, it is like dumping a vacuum of dust all over your clean work surface every day, but the dust can't go anywhere, so it just collects itself into huge piles which are impossible to be rid of in any manner of speaking, involving a timely way with regards to the accumulation of data in a crowded non managed abandoned database. Sorry to say, but I find such activity very inefficient and impossible to work with, when you are trying to test different scenarios out. A record of your incomplete state exists somewhere else, other than the directory and statistics index, even if you remove something from the directory index, other partitions are being treated as active and log duplicate corrupt records of activity still there, where information can't write over data fields which aren't blank, but which are instead, being treated as if they are a part of something else, which therefore here in lies many conflicts and problems in and of outside themselves, belonging to wrongfully assigned parts of a cluttered database.

What were you expecting to happen?
----------------------------------
… Database clean up to be a task scheduler priority. If a module is disabled, offer a means to remove all of its associated settings from all aspects of the database as if it never was there, statistics or any other logs as well coming into account. All settings and content and profile areas including their ID tags to be updated with replaced information if existing information becomes unavailable. Provide ways to delete absolute data entries from all associated aspects of the database when managing commands from the administration panel. To be able to refresh and install packages overriding database tables which already exist, and to be able to recognize if any existing tables, rows, columns and fields within a specified database have to be updated with new information. To be able to control which information is overridden as the process happens manually, or let an automatic setting of override or don't override changed information be possible, just like it is for file changes. To be able to uninstall a module with complete awareness of the fact it will remove all associated existing database queries as to its widgets, settings and associated contents whereabouts, as well as to be sure any files associated with it including custom templates, pages, or files are removed and have all modules record a list of all default files it requires to function normally using task scheduler settings to make the required updates a regular part of module maintenance, so if an uninstall was to happen, it would take note of where ever the module itself had any database queries stored, replaced, updated or amended to along with any files it required as a part of the package itself. To be able to refresh existing module packages without making new database tables for each setting change, or data update. To be able to automatically detect current ID statistics per table and associated connected or simultaneous dependencies where ever database queries exist. To be able to know with confidence such a problem will be resolved by being able to using any aspect of social engine's interface, to be able to effectively manage all singular and or multiple aspects of the database automatically by what ever means required to do so through  scheduled or manual actions which do not break upon accessing their administrative functions as a site creator or owner.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Too many to list here. I'm appalled at such a recent discovery. Nobody else seen it coming? Really? Impossible. And yet here we are. And I made it known. It has to change. It is a deal breaker for me.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by poeticjustice** [comment]
I had this issue, i removed a plugin just like Social Engines site suggested, where it suggests which mysql files need deleteing, but because there are loads of hidden references to plugins in different areas that SE doesnt tell you about, that when you reinstall, it duplicates entries and sometimes cause it to fail to work, or miss widgets or even the page to register the serial key of the plugin

**Comment by Elshara** [comment]
Yeah exactly. I had to reinstall social engine one time because it got
so bad like that where it would just fail constantly. This is the
reason why I don't touch the database unless I absolutely have to.
It's disgusting. Like a leak you can't fix. In fact it's so bad that
right now if I wanted to touch the layout editor to add a new page,
all these old bits of other programs and corrupt column spacing makes
the page not even load properly due to ID conflicts. It's gross. Of
course they duplicate themselves and when I went into the database to
check, there's all kinds of empty columns in the most oddest place
you'd expect. Some of them don't even have any page ID assigned to
them, some of them just have empty container fields and then some have
repeat page ID. Missing modules, extra columns you can't get rid of
even when updating the layout editor, can't delete a page without its
entries still being in existence. It's so bad if you ever get those
spam bot requests, your member data ID fields usually end up with the
most recent being in the hundreds of thousands, even though you may
only have 20 real members. You can't remove the spam bot content when
removing the member, so in the database you go, hunting for duplicate
entries of posts in each and every module every time a spam bot gets
through and then sifting through real member data you have to match
their ID's hoping none are actually conflicting with each other, not
even sure what is the Forum or comment ID and what is the member ID.
Let alone which ones are active. Oh yeah and if you go over to your
activity actions page, or your member settings email notifications
area, you'll see all kinds of corrupt module codes and keys listed
there in the drop down menus to partially select. It's a royal
disaster.

**Comment by poeticjustice** [comment]
Yep totally agree matey, check out my latest posts ha @Elshara

**Comment by Elshara** [comment]
You bet. I'm with you 100% on this.

**Comment by SpiritWolfie** [comment]
@Elshara 

You really really need to start summarizing and gaping your posts when everything is so combined and so long its almost impossible to read

**Comment by Elshara** [comment]
Thanks for the suggestion bud. I'll try to do so much better. I know
this post is very long and a bit rambled but the theme is comprised of
4 main points.
1. Installation of anything, updating, removing or adding packages, is flawed.
2. Existing database queries upon managing packages makes it very
difficult to use the website as new duplicate entries are created
rather than replacing existing tables required to display information.
3. Duplicate entries cause issues especially when modules don't exist anymore.
4. Database is very hard to clean up because you are not sure what
fields are actively being used by the system.

**Comment by poeticjustice** [comment]
Amen to the above @Elshara so many duplicate entries

**Comment by Elshara** [comment]
...that moment where you are looking in Gmail and have to click expand
all messages just to get the jist of the previous comments. Because
I'm too lazy to view it on the web and I have the ability to reply via
comment.
I've been making some progress with deleting some entries on mine
though. But it's very delicate and tedious work.

**Comment by Khushboo016** [comment]
Hi @Elshara, 

Regarding "but the theme is comprised of 4 main points.":
The number of queries that are run at the time of a plugin installation depends on the plugin itself, that is how it is structured and in which tables entries are needed to be made for its registration on the site. So, the increase in database's size is dependent on the nature of the plugin itself. And whenever an upgrade is performed for a plugin/module to upgrade it from a version to another, for example, say from 4.x to 4.y, then the queries that are run are the time of that upgrade are listed in the file /application/modules/**_NameofPlugin_**/settings/my-upgrade-4.x-4.y.sql.
One point that needs to considered is removal of plugins after their deletion and as we mentioned in the issue https://github.com/SocialEngine/phpv4-issues/issues/555 that we will work to include an option using which it would be possible to completely remove a plugin from SE PHP site along with the removal of all its entries from the site database.

Thanks & Regards!

**Comment by Elshara** [comment]
Okay. What you're mentioning here is a huge improvement from what
currently exists.
However, it still doesn't fix the duplication problem when packages
are updated. I'm very concerned specifically, about the following
areas for improvement.
engine4_activity_actionsettings
engine4_activity_actiontypes
engine4_activity_notificationsettings
engine4_activity_notificationtypes
Duplication appears very strong here. No multiples of settings should
need to exist. But they do so after every package update.
Also concerning is here.
engine4_core_menuitems
engine4_core_menus
engine4_core_modules
This is where corruption starts happening. Due to module uninstallation.
Adjacent to this problem, you'll find places like.
engine4_core_pages
engine4_core_content
Extremely susceptible to both corruption and duplication of
corruption, due to existing values set here. Specifically, targeting
data fields a new install of a package believes to be empty, but are
in fact occupied by ID's not being used for anything other than
storage space.
When you compare such a mess to clean fields such as.
engine4_core_settings
engine4_core_themes
You can see they are clean, have no duplication so therefore cannot be
corrupt. Mind you, themes installation may be a different story but
you can see here is where when you disable a package, the settings
seem to stick, rather than not be applied as opposed to if you update
or remove a package.
You know what would make this sit a lot easier with me? All you'd have
to do is record the field entries posted specifically where ever data
appears regarding each module. When the module is disabled, remove the
data fields it occupies. Place them in some other part of the
database. If you wanted to enable the module again, they could just be
transferred to their original position as their ID would already be
recognized.

**Comment by Elshara** [comment]
I just realized something. Those settings you mention,
/application/modules/NameofPlugin/settings/my-upgrade-4.x-4.y.sql for
example. Would probably give references to all the database fields
required for the plugin to function.
What if, we blocked off access to certain fields, where third party
plugins and themes, could not share the same database table as core
menu items. Therefore, making the database appear a lot cleaner and
easier to deal with, if manual action is required. At least until this
whole system is sorted out.
I only wish when installing updates to packages, new database tables
would not need to be created. But instead, the fields would
automatically recognize existing content in the database, to just
update those specific fields if any matches could be searched for in
such a way, so they could be found. The idea is to update existing
values to the upgraded defaults, so a complete reset of the
installation could take place if someone desires it. Just like files,
if any modification was made to the file, it could also detect such
events in the database.

**Comment by DonnaScriptTechs** [comment]
Our team is not sure of the issue in this report and did check the various things you mentioned. We'll close this for now as we are closing this github area. Once we have the improvement to remove plugins fully, please test again and please provide screenshots of the issues you are reporting, at our community. Thank you!
