### ISSUE TITLE
Feature request - google maps api intergrated with locations profile question

### ISSUE THREAD

**Issue by poeticjustice** [SocialEngine/phpv4-issues#615]
This is example from a company ive never heard of easysocial / stackideas

Yet SE is behind here, Profile questions prooving to be even more out of date with 2017 standards.

Adding Location manually which has room for spelling errors, or other variables, profile question for location is just aweful.

yet other sites are adding little touches like this, which makes a awesome touch to a website.

![loc](https://cloud.githubusercontent.com/assets/19233272/24106815/00ef9620-0d81-11e7-8fd6-c224ec72ecc8.jpg)

**Comment by poeticjustice** [comment]
Backend photo of profile edit, 

It even has asterisks for required fields - yet Social Engine doesnt!

Description field in the admin section is html editable.
So even for description edit, your able to style the word note in bold! 

And even add html links in the descriptions, yet SE doesnt.


![prod](https://cloud.githubusercontent.com/assets/19233272/24107135/dda08bf6-0d81-11e7-8528-cd8bb39cc4f1.jpg)

**Comment by Elshara** [comment]
The best profile questions type integration I've ever seen, is from a company called Ning. Full html5 integration. Full embed support if you wanted to add a video. Full icon and font support. Full animated gif support. Full mobile support. Full public, private admin only and member specific question integration.

**Comment by Elshara** [comment]
I know dolphin pro has google maps integration for profile questions.

**Comment by Khushboo016** [comment]
Hi @poeticjustice, Thanks for the suggestion! We've added your feature request at our end for internal team discussion regarding its implementation in future releases.

Thanks & Regards!

**Comment by Elshara** [comment]
:)

**Comment by poeticjustice** [comment]
Cant wait for this enhancement

**Comment by Elshara** [comment]
I was going to add it as a feature suggestion myself. I would love to
be able to able to upload albums of maps.

**Comment by gsf00001** [comment]
This is another useful function that I never realized SE didn't have because I use so little of it and all the SEAO Addons I use have had this since at least 2 years ago.  It's great to search for Pages or Groups or Members or whatever by radius too - and then see the results on a map.  It's great SE is considering implementing something with Google Maps.

**Comment by Elshara** [comment]
Yes I'm happy.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#65

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
