### ISSUE TITLE
Feature requests, and regards to Social Engines website.

### ISSUE THREAD

**Issue by poeticjustice** [SocialEngine/phpv4-issues#616]
Hi All

Ive raised some feature requests and bugs over last few months.

And to start off lets be honest the top dogs of social network scripts are Social Engine, PHP Fox, and Oxwall. But there is some contenders coming along which @Elshara documented in a post that was closed.

**Oxwall** looks beautiful and its on the raise, sadly the team doesnt seem to push it in ways of advertising, and their twitter account is like hardly in use (over a year), their market place is flooded with random coders and rubbish apps

**Social Engine** - IMO the best, it has all the best Developers, when you look at phpfox, oxwall, and other contenders 3rd party plugins, they dont even come close to the works of Social Engine Solutions, Social Engine Addons, Webhive, Younet, and Hire-experts.
But, soooo much is out of date with SE, and we are all here making feature requests that should have been implemented a year or 2 years ago. I just feel SE are making it to easy for their contenders to swoop in, or for the 3rd party developers to give up and explore being PHPFOX devs only.
The best thing SE has, is the 3rd party DEVs, but SE needs to not only commit to its customers, but building a better platform that entices clients in that also generates work for these DEVS.

**PHPfox**, i know you have @DonnaScriptTechs and @RaymondBenc now from there, and i hope they will push things forward with SE, but PHPfox 4, is simply beautiful, its upto date, modern, the profile questions and search ACTUALLY work, Like Oxwall, PHPfox can do searches in browse members at a multiselect level, when the original question was single select only, see post here for images #613 
Yet SE have said it cant be done, yet ALL other competitors can.
They have been using fontawesome for ages, the social signup logo used are not 5 years old like SE.
But, the DEVs on phpfox are not on the level of devs on SE, is phpfox more locked down, or not so easy to build, i do not know.
But at the moment PHPfox 4 is making Social Engine look like Phpfox 3.
Even looking at Younets latest themes for SE and PHPfox 4, PHPfox seems like, theme wise it has more to plays with, where as themes for SE are so problematic
http://phpfox4templates.demo.younetco.com/responsive-business/
http://se4templates.demo.younetco.com/responsive-purity/

**As Donald Trump said "Make Social Engine Great Again"**

I love social engine and i want it to stay the best, but i feel as a client, that SE are making it so so so easy for competitors to sneak up behind, that when other potential clients compare software, SE will be ignored, purely because competitors have seen the curve ball, and they are staying up to date, some things are tiny little touches, but loads of these touches are making SE appear outdated.

We obviously dont know how SE is run, but im guessing all the devs for SE internal are all freelancers, they don't have office meetings, they live across the globe, and they are hired on set dates to do fixes or enhancements, and meetings maybe held over skype, rather than in-house team who are constantly updating, fixing bugs etc.

If cost is an issue, im sure with all the clients on SE, if you said lets crowdfund all these enhancements, and if people were willing to do it, to make sure they are added, things updated, i can guarantee you people will do it, Id gladly whack $100 down, if it meant these features were added, id rather that than pay $50 for support which im unsure about still based on the past.
SE don't be afraid to ask your clients, id gladly crowd fund to make SE the top dog, because by SE being better, it generates better work for the DEVs, who we then hire, which makes our site great too.

SE need to consider also selecting clients to test new releases and bug fixes, When i owned a recording studio, i use to record all time, then when it came to mixing,i couldnt tell the difference as my ears heard everything to much, so it was better having others work as they have fresh ears.
Same with testing, your fixing bugs constantly that your bound to miss things, so find people with a fresh aspect to test.

**Another thing Social Engine website**

Love the look of the new site, but searching of market place needs to be better.
Finding plugins by Developer is impossible, even when you find a plugin, it mentions dev name, but you cant click and see their other apps nor can you see there other plugins, like an upsale.
Also I think it be great if Devs updated things like updates and changes, like a log, similiar to code canyon.

even if you leave market place, goto experts, click on expert , view experts profile, then view plugins...... its just way to many clicks to get to a place, when there should be something on their product pages..... too many clicks equals drop offs.

In each market place listing, i have not once seen a button saying demo or any links to demos of plugins, some have listed the username and password for the demo, but absolutely now links.

Also there should be display options, when you hit the market place all you see is Titles and a funky picture, no small write up of the plugin, doesnt even say the developer until you click on it, as a client there is 100% no way im going to click on every plugin to read about it, there needs to be a short summery of the plugin, just like your old website.

**Comment by DonnaScriptTechs** [comment]
Hi,

Thank you for your post. 

In regards to our website, since that is not phpV4, we would kindly ask for those features to be asked for in our https://community.socialengine.com in order to keep the bug tracker for bugs within the script itself. 

We do have more improvements coming for the store and there are experts with more themes coming.

In regards to discussions about other scripts, please feel free to open topics at our community as well. This github is not for general discussions or script comparisons but is better served for posting bugs and feature requests one item at a time.

**Comment by poeticjustice** [comment]
@Elshara @SpiritWolfie @Mthorganby @cgcb @JonSimon93 @leandrotavaresrocha @gsf00001 @thespidirman  @Vaibhavagarwal0807  @angelinfante @sunfellow @Burno317 @dreamgeekcoder @simpliby what all you guys think?

**Comment by poeticjustice** [comment]
Ohhhhhhhhh its been closed :( @DonnaScriptTechs

**Comment by DonnaScriptTechs** [comment]
Please post at our community. Thank you.
