### ISSUE TITLE
Pulldown Or Update Notification not working?

### ISSUE THREAD

**Issue by rkrathor** [SocialEngine/phpv4-issues#618]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. Go to Update notification.
2. Click it shows you have no new updates.
3. Even view all updates have 1 new update to show?

What happens?
It is not showing all updates in dropdown even giving an error 500 Internal Server Error.
All screenshots attached.

What were you expecting to happen?
It should work like my test website which have same code and show all updates and in notification page also.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
Could it be because of https in my live website and elsewhere I am using http?

What versions of software are you using?
----------------------------------------
**Operating System:** … Linux

**SocialEngine PHP Version:** … 4.8.8.

![pulldown not working1live](https://cloud.githubusercontent.com/assets/10502380/24186024/3d3dab04-0efc-11e7-8425-e48ec5af2f76.png)
![pulldown not working2live](https://cloud.githubusercontent.com/assets/10502380/24186023/3d3d6afe-0efc-11e7-9123-65c2a3cfdbe1.png)
![pulldown test1](https://cloud.githubusercontent.com/assets/10502380/24186025/3d3ed1f0-0efc-11e7-8faf-cfeee469bec7.png)

**Comment by Elshara** [comment]
I have a similar configuration to you. But I'm using 4.8.13. I wonder
if it could be a .htaccess causing the problem. My https works fine.
