### ISSUE TITLE
BUG - Deleting users leaves data in core engine4_activity_notificationsettings

### ISSUE THREAD

**Issue by poeticjustice** [SocialEngine/phpv4-issues#619]
Hi Just to let SE know, that when users are deleted, it does not delete the mysql entries for notification settings 

engine4_activity_notificationsettings

**Comment by Elshara** [comment]
OF course not. The database is far too primitive for multifield actions.

**Comment by Khushboo016** [comment]
Hi @poeticjustice, Thanks for reporting the issue, we'll fix the same in near future releases.

Thanks & Regards!

**Comment by poeticjustice** [comment]
@Khushboo016 Is it ok to go ahead and manually delete these entries of a member which are stuck in engine4_activity_notificationsettings

**Comment by Elshara** [comment]
I'd say it's relatively safe to do so. Just be sure to check the ID of
the person you are doing this to.

**Comment by DonnaScriptTechs** [comment]
This is fixed for our 4.9.3 version when it is released.
