### ISSUE TITLE
Invite Request Mode

### ISSUE THREAD

**Issue by TheGreatAlexander** [SocialEngine/phpv4-issues#62]
It would be great if we can set Social Engine on an invite mode so that people who want to access must have an invitation. People will have to click a button for an invite and receive an invitation.

**Comment by Vaibhavagarwal0807** [comment]
@TheGreatAlexander : You can set SE on invite mode from the admin panel: Settings >> Signup Process >> Step 2: Create Account - and choose values for "Invite Only?" and "Check Invite Email?" as per your requirement.

See, screenshot.
![invite only](https://cloud.githubusercontent.com/assets/11191902/8299798/e525636a-199a-11e5-8c77-fa61be397773.png)

**Comment by TheGreatAlexander** [comment]
I must have been more specific then.  If SE is on invite mode, then there should be a place where the user can enter his/her email and name so that when the Admin owner wants can email them an invite.

**Comment by Anshuse** [comment]
Hi @TheGreatAlexander ,

We've noted down your suggestion at our end for the internal team discussion to take appropriate action over this.

Best Regards,
Anshu

**Comment by Vaibhavagarwal0807** [comment]
@TheGreatAlexander : Meanwhile users can contact admins from Contact Us form to get the invite.
