### ISSUE TITLE
Allow Meta Data For Views To Be Recorded In Activity Feed

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#620]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Vote on a poll.
2. … Play a song, video.
3. … View a profile or other piece of content, page or go online for chat.

What happens?
-------------
… The activity feed doesn't record this behavior.

What were you expecting to happen?
----------------------------------
… The activity feed to make a record of such behavior. As well as widgets to display who viewed, voted, played, chatted to or interacted with what. Relating to module specific actions.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Having this data be member level configurable, would also be nice. But having it there to play with, will give undeniable proof, signed in members care about what people have to say.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#67

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
