### ISSUE TITLE
Include Invite And My Friends Links For Member Browse Menu

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#621]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Go to browse members page in layout editor.
2. … Place the browse member menu widget somewhere.
3. … Save changes. Now navigate to the browse member page itself in site front end leaving the administration panel.

What happens?
-------------
… No links are displayed and the menu hides itself. Even if you are signed in.

What were you expecting to happen?
----------------------------------
… Member related links to pop up there. Such as messages, notifications, friends, invite, all members, search members, or something.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… IT just seems odd the only menu in core product has nothing to display but yet it exists.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by DonnaScriptTechs** [comment]
I can confirm this. Not sure what the widget is for as it seems to only contain a title.

**Comment by Khushboo016** [comment]
Hi @Elshara, We have not provided any default menu items for the Member Browse Menu because there are not any essential menus that are required to be placed on the Member Browse page. But instead of showing a hard coded title of the page, we have provided a menu interface, so that if an Admin requires, then he would be able to add any menu items on the page. So, if you require any menu items to be shown on the page, you can add those to Member Browse Navigation Menu from Menu Editor section.    

Thanks & Regards!

**Comment by DonnaScriptTechs** [comment]
We'll provide a tutorial for this. Thanks @Khushboo016 and @Elshara :)

**Comment by Elshara** [comment]
I know how to do that. My issue, was that core links can be provided
to existing menu items, for the menu to contain.
My friends, and invite members, are pretty standard for a menu like
that. Hence the suggestion. There's no core page available for my
friends, and if I add the invite link to the menu itself, I can't make
it appear for just members signed in.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#68

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
