### ISSUE TITLE
Create Specific Links To Module Main Navigation Menus

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#622]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Go to any browse page.
2. … View the menu options.
3. … Compare them to the list of widgets displayed on the page itself.

What happens?
-------------
… Menus are bare, and usually only consist of the bare necessities just to be able to display data. All items, manage or my items, and add new item. What if in addition to the widgets, menu items existed for things like search, popular, active, featured, alphabetical, categories and other filtered lists.

What were you expecting to happen?
----------------------------------
… Currently such functionality is only possible using widgets. But if it could be done using built in menu items, widgets could be assigned to carry such menus as optional, extended, module adaptations which could be available if you wished to replace default navigation menus with something a bit better designed for the user wishing to browse what all is available. This way, you can't just assume nobody cares enough to post content if all you are presented with, rather than having to look for the advanced search functionality to sort content a certain way, that anybody has something to say, because the option is there to include, instead of exclude, existing content posted to the site itself.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Individual menu items might just be a step forward for everyone.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#69

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
