### ISSUE TITLE
Consider Addthis Or Sharethis Integration For Better External Sharing Functionality

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#623]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Go to a post in activity feed.
2. … Click share.
3. … What you're presented with, isn't a share option. It's a spam post.

What happens?
-------------
… Spamming your wall with feed items you never created, isn't the best way to let people know the content exists on the site to be viewed. Instead, you need an attractive, dialog box outlining your options. Something you can do inline, but shares while you are on the page, to some other type of network profile system.

What were you expecting to happen?
----------------------------------
… Social Engine to realize sharing content doesn't need to involve spamming things people can't even get notifications about.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… People can't interact with content shared on your profile. So the only way to make sure this happens, is if you improve how people can do so. While they complete such actions, let them know they are welcome to be encouraged to tell others about what they've done, so they can do the same. So when they share their own posts, it becomes twice as much meaningful. Share this and add this are third party providers, which give you the means to do this. However, what would be better, is if social engine came up with a way to do so internally, so all your friends, groups, events or comments on existing posts can be informed about something you care about. Therefore informing other users, who care about the same things you do, this is possible and that it can be done, has been done and they can also do it.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by DonnaScriptTechs** [comment]
We already have AddThis coming in 4.9 :) . This will be for sharing to things available with AddThis. Are you speaking of internal sharing or external? I thought it was external but reading again, I am wondering if you meant internal.

**Comment by DonnaScriptTechs** [comment]
With AddThis coming in 4.9, we will close this for now. If you find you need something more once we've released it, please open a new request. Thank you for your contributions.

**Comment by Elshara** [comment]
Awesome!
I mean add this for external. As for internal, I was thinking
something that could be managed via a queue system in task scheduler.
Then just manage post notifications this way for internal promotion.
