### ISSUE TITLE
Css breaks

### ISSUE THREAD

**Issue by SpiritWolfie** [SocialEngine/phpv4-issues#625]
I'm not sure if this is a issue with plugins or SE itself
Every now and then myself and my users will get a completely white page (css breaking on the /home/) it doesn't consistently happen but its happening enough that my users are complaining about it

This only started happening when our websites activity increased drastically and wall posts/photo's uploads started happening quite allot, if anyone can help me with this please!

**Comment by Elshara** [comment]
If the page reloads and the css works normal, it's due to some kind of
a time out.

**Comment by DonnaScriptTechs** [comment]
Can you check in development mode to see if it happens with that on? Noting that you would not want to keep that enabled for a long time as it is resource heavy. This will disable caching to see if perhaps you've an issue with caching on your server.

You could also test with default theme and see if there are display issues with that. Just let your members know that you are testing things for a day or so to avoid them being stressed out by the changes.

**Comment by SpiritWolfie** [comment]
@DonnaScriptTechs 

I will test that on our dev site instead honestly, and see if it happens, if I remember correctly the CSS always breaks when I go into dev mode even on a fresh install, but I most differently need some help with figuring this out as its starting to become a headach for my users...

**Comment by DonnaScriptTechs** [comment]
You might want to remove the image you linked as this is a public repo and that image contains user names and image locations plus the site url. If you want to keep those private. I think you should test on your dev without any plugins in case there is some interference. Then, try with your theme on there and see if it's the theme or some other plugin causing the issue.

**Comment by SpiritWolfie** [comment]
@DonnaScriptTechs Will do, could you take a look at the log I uploaded on google drive and tell me what you think?

**Comment by Elshara** [comment]
I remember having this issue once, way back in the day. It was
actually due to a file install not completely installed or
uninstalled. I simply reuploaded the package of the entire site core,
plus all the modules I was using at the time. Then I went database
diving to fix the conflict and then things started working as if
nothing had ever happened.

**Comment by DonnaScriptTechs** [comment]
@SpiritWolfie I didn't see a file. Sorry for the late response. I was offline with a flu. Still recovering.

**Comment by SpiritWolfie** [comment]
@DonnaScriptTechs its fine, its in the above post where I tagged you in the first time, its toward the bottom its the google drive link, its a direct link to it, Social engine addons said Ctrl+ U should have only spit out a few lines and a link but sadly thats not the case when I or my users hit Ctrl+ U this is what we get each time.

**Comment by SpiritWolfie** [comment]
@DonnaScriptTechs have you had a chance to look over that file? if so any thoughts or whatever

**Comment by DonnaScriptTechs** [comment]
I never saw the file you mentioned. I see a txt file but I'm not a core developer. Debug is the thing I look at normally, to see issues. Log files can show what's going on. I would say to check the logs and see what shows during those times. Since CSS is cached, cache is the first suspect. It's really hard to say with random issues without having support check it.

**Comment by SpiritWolfie** [comment]
@DonnaScriptTechs 

https://drive.google.com/file/d/0B_4vlBCneKvnQm1vcXV0NHNNT1U/view?usp=sharing <-this link here

What would I look for persay if I check the logs, and what logs would I check, the one on the admin panel or which ones, so I can pass the info to my coder to have it looked it, because this is becoming a major problem, and it only started happening after my activity increased, Its not my server box, we've adjusted our resources multiple times.

**Comment by FG-QuirkyKitty** [comment]
@DonnaScriptTechs 

Hello, I'm the coder that @SpiritWolfie is referring to.
I was able to get this issue by accident on the splash page of the website, so I did a bit more analysis to look into it.

Here are my findings, which I hope will assist you all.

- The HTML files generated are the same. (html_fg_normal.txt and html_fg_whitepage.txt respectively)
[html_fg_normal.txt](https://github.com/SocialEngine/phpv4-issues/files/894663/html_fg_normal.txt)
[html_fg_whitepage.txt](https://github.com/SocialEngine/phpv4-issues/files/894664/html_fg_whitepage.txt)

- When using the Inspector from Firefox's developer tools, I noticed that the CSS was missing and therefore unrendered.
![fg_unrendered_css](https://cloud.githubusercontent.com/assets/26911048/24681382/f018ac22-1962-11e7-8fd8-0ff6711422ea.jpg)
The unrendered CSS corresponds to this URL: [http://www.furgather.net/application/css.php?request=application%2Fthemes%2Fresponsivetheme-modified%2Ftheme.css&c=321&pageStart=311588&pageEnd=595830](url)
The link above is referenced at [http://www.furgather.net/application/css.php?request=application/themes/responsivetheme-modified/theme.css&c=321](url)

- Doing a normal refresh of the page still resulted in the issue. Instead, a Ctrl-F5 was required.

**Comment by FG-QuirkyKitty** [comment]
Experience tells me that we're dealing with one of these issues:

- CSS file in cache becomes corrupt; solution is typically to force it to download every time. One of the solutions here is ingenious for that purpose. http://stackoverflow.com/questions/18543776/why-is-my-css-not-updating-in-web-browser

- CSS file is large enough (in this case, 280KB) that it doesn't always download when rendering the webpage. The solutions I know of would require either (1) writing a fresh all-inclusive stylesheet and ignoring default stylesheets, or (2) some intelligent generation of CSS which removes selectors/declarations that would not be rendered on the website anyways.

**Comment by DonnaScriptTechs** [comment]
What's odd here is that this is not happening for others. I have my own SocialEngine live site now and have not seen any CSS issues but I use one of the default themes (cloned and css styles changed some) and no third party products. I have to wonder if a third party product is producing some sort of conflict. Has this been tested on a development site with no third party products?

There is a CSS issue fixed for 4.9 that could possibly be related but it doesn't seem the same in the report there. You would see an error with development mode on. https://github.com/SocialEngine/phpv4-issues/issues/214

**Comment by FG-QuirkyKitty** [comment]
I was going to implement the solution from alimoosavi15 in #214 but I cannot find that path on our server. We are currently on version 4.8.13.

I don't think we have any third-party products that would be loaded on the splash page.

Just in case I'm wrong - The third-party plugins that I'm finding are:
- YouNet Advanced Groups
- Hire-Expert Core
- Hire-Expert Badges
- Family Member Plugin by technobd

I'm also assuming that Webligo develops official plugins for you all, so I haven't listed those here.

**Comment by FG-QuirkyKitty** [comment]
@SpiritWolfie Do you know off-hand if this issue has occurred with any browsers other than Firefox and Opera?

**Comment by SpiritWolfie** [comment]
@FG-QuirkyKitty This happens on chrome as well and I.E, so its not a browser issue, its gotta be something with the way CSS is handled in general, i've had this happen on Default social engine pages as well

I think it has allot to do with the amount of activity we are generating, other social engine websites don't get as much activity as we get from what I've seen (I haven't found one that generates the amount of uploads/photos/posts/links ours generates yet) and I think that may have something to do with it personally.

**Comment by gsf00001** [comment]
@SpiritWolfie  ==> "... responsivetheme-modified/theme.css&c=321  
- What theme is this referring to?
- What (code and/or .css) has been modified if anything that you're aware of?
- Could there be any conflicts with the .css from YouNet/HE/technobd?
- Have you tested with SE Default Theme, and if so, did it still break?

No, I'm not an expert - just looking at this from a different perspective so you can tell me to take a hike if you wish :)

**Comment by SpiritWolfie** [comment]
The issue with testing it with default Themes is the default themes are just as buggy and haven't had CSS updates for a while (with the new core engine updates) not only that they are far to bright for my my users, none of the themes are stable that i've personally tested (regardless of plugins or not) I've had issues with midnight and default/clean/music box etc

**Comment by FG-QuirkyKitty** [comment]
@gsf00001 
The Responsive Captivate theme is what we have. (which is a custom one developed by SE)
According to Spirit, he's also had this issue with the default theme before.

While we have made minor modifications to the CSS in the past to correct issues, the changes were tested and verified not to cause these sort of issues on their own.

I don't have any reason to suspect the third-party plugins yet, as CSS does render on the site as expected outside of this intermittent issue.

**Comment by SpiritWolfie** [comment]
The other issue is whatever is causing this issue also may be related to the website being slow/or staggering to load for people (including myself) it may be connected.

**Comment by FG-QuirkyKitty** [comment]
Also, this whole time, I had misread the solution in #214 . I just implemented that in hopes it will help since it addresses the pagination directly.

**Comment by gsf00001** [comment]
@FG-QuirkyKitty   I may be wrong, but the only Responsive Captivate Theme I'm aware of is one from SEAO (this is why I asked about the '..responsive..' in the URL you provided because I wasn't aware of SE offering any responsive themes yet (but I could be wrong - I thought this wasn't coming from SE until 4.9).  I'm used to using SEAO and SES Themes (SES provides my primary theme, but sometimes SEAO asks me to use one of theirs for testing along with the SE Default).

If that is the case (i.e. it's SEAO's theme not SE's) have you considered contacting SEAO to resolve this?  I use a theme by SES and SEAO is very good about resolving issues they caused and letting me know when it's an SES Theme issue so I may contact SES.  

I realize this doesn't resolve the issue you're having or point to the problem, but I can't understand why SEAO isn't fixing this for you (if it's their Theme).

**Comment by SpiritWolfie** [comment]
@gsf00001 

This is happening on base Social engine pages as well (ones like the 'login page') which has no plugins touching it, 

I do have SEAO looking into this as well but I'm starting to wonder if its a issue with social engine with the vast amount of activity my website gets vs a plugin, there is no way for me to test this on a dev site because I couldn't get the amount of activity I get on live.

The ctrl+U trick I been told to do just pulls the source, we need a more sure way to catch what happening when the page goes white or staggers to load, if anyone has any suggestions what we could do to capture whatever is breaking etc that'd be great.

The built in admin panel error logs are super unhelpful and for whatever reason SE isn't sending cache logs to our serverbox.

**Comment by Elshara** [comment]
Such is the problem when dealing with websites coded in the mvc
pattern. This happens all too frequently when you have to wait for
dependencies to load all the time. One syntax error could throw
everything off. And when you're loading possibly upwards of 30 css
files for every page load, not to mention all the javascript required
to place those css files somewhere, while the database is constantly
being accessed, the more people even viewing the site, there is where
the problem happens on page load.
Perhaps a server php extension may be causing such a connection to be
delayed somehow. That's happened to me a lot of times when I was
experiencing intermittent breaking of files. Especially the ones that
controlled the pull down menus, even though that was a javascript
problem. It's very relevant here as the same type of issue seems to be
occurring. The files never fully load in the browser due to some kind
of overload with the connection itself to the server file rendering
process.

**Comment by Elshara** [comment]
The only fix I can think of, is perhaps updating Zend or getting rid
of it as soon as possible. That way, you can tackle where the bug (s)
occurs, be it a code or connection problem, if the line number (s)
is/are consistent. If it isn't, then it's due to a database rendering
error, something Zend has in abundance.

**Comment by DonnaScriptTechs** [comment]
As we have clients with more than 100k members and very active (I saw one of them last week), they are not reporting this. 

Since you mention it is happening when you have more users, it could be that the server needs updating. Perhaps more resources? Please note that I am just providing some tips here and not accusing the server of being bad as we don't have any server info.

You might need a support ticket for our team to come see what's happening on the site and check files on the server. I'll see if someone can check this bug report though.

**Comment by SpiritWolfie** [comment]
@DonnaScriptTechs 

My server box is more then capable, we have it sitting on a 10gig pipeline and the specs of my server box are fine..  as for clients having 100k members, having X members vs X activity are two big different things, Its super easy to have More users then that actually use the website, so thats not a valid claim honestly (no offense)

If someone from SE wants to come have a look at all the issues we're having and tell me what we're doing wrong, that'd be great, have a look show me where the issue is we're fix it our selves or I'll even Tip someone some $ for the time to find the issues we're having or a solution.

No worries I know your not blaming my server box..

we've looked into this more and more, and honestly the way Social engine at its core handles css is a problem, theirs to much Css being loaded from to many places, I just had a CSS expert look over our home page and thats what he said, he's also super confused to why social engine the platform needs to have so much going on in regards to that, as most any other websites doesn't load anywhere near as half much css as Social engine does

We've got CSS timing out and what not and browsers refusing to load some of it or skipping over them and not rendering them fully.

Just a FYI I have never NEVER had these kind of issues with Joomla, Oxwall, Druple, Elgg, etc. even when using third party plugins/modules etc...

(I heard 4.9 changes the way CSS is handled in social engine, I hope its less css in whole or better done then its currently done)

**Comment by FG-QuirkyKitty** [comment]
I think she meant that there's still a larger amount of activity on the other site than ours. (If 1% of users are active at any given time, that's 1,000, so it's realistic for their activity to exceed ours)

Also, I left out Arrowchat by accident earlier, but I'll let @SpiritWolfie update on that part.

**Comment by DonnaScriptTechs** [comment]
@FG-QuirkyKitty yes, that's what I meant. :) the other site is hyper-active and lots of action. However, that doesn't mean there isn't an issue. Not until someone can test and see. I'm trying to rule out things so our team can know what to check.

**Comment by SpiritWolfie** [comment]
@DonnaScriptTechs 

All day to today we've had white pages, social engine error codes bc03d1, internal server error 500

I've had my server tech check our resources his response was "The website isn't even touching the 1 core.." the graphs etc all look normal and everything else on the book never has issues, Every one i've spoken to says its something with Social engine, I've had CSS experts look it over, i've had my server tech who I trust very much, who has been doing this stuff for decades look it over, Quirky who works as a programmer in a big name company look it over, I've had People from my connections with major top name websites (like league of legends etc) i've had them look it over

Every single person I've spoken to states the issue is with social engines code...

we've reconfiguration my box multiple times because people kept saying my box was configured incorrectly, so we've uped the resources, changed to a stronger server box etc... we are still having these issues and no one can give me a clear answer, I've even made it a point to go as far as to disable 90% of my plugins and I STILL run into issues.

If someone from the SE team wants to get in contact with me to look this over and try to help us that'd be great, I have a entire community that is getting REALLY upset over this, as its been happening more frequently, If I need to pay I'll pay, but once you've identified the issue you can then quote me whatever to fix it (with in reason), Please, this isn't just for me but my entire community.

**Comment by SpiritWolfie** [comment]
We restarted our server box earlier hoping this might help clear things up and now we're getting a 404 only on /admin but /home/ works fine....

**Comment by DonnaScriptTechs** [comment]
You would need to send a ticket to our support for our technicians to check the site. We can't come to the site via Github as it's not safe to post details here.

**Comment by SpiritWolfie** [comment]
@DonnaScriptTechs 

I'm aware posting ftp/sftp would be silly.... 

So here's what i've done, I've once again re-disabled all plugins from every other provider that I use.. (every inch including the core for those plugins)

This is what I see now when I inspect the home page (This is just PURE SE) now..

![image](https://cloud.githubusercontent.com/assets/9712738/24774479/e53b18dc-1acd-11e7-99c7-1092c59c6f91.png)

Please note the Start and stop loop and the Sound thing erroring out.

**Comment by SpiritWolfie** [comment]
@DonnaScriptTechs 

So I refreshed the packages using Social engine update and zend update to remove any custom coding

now I get 

![image](https://cloud.githubusercontent.com/assets/9712738/24776387/61430cd0-1ad5-11e7-9385-1b71c5039267.png)

**Comment by SpiritWolfie** [comment]
I've put a Support ticket in like you suggested @DonnaScriptTechs  I've regone over everything before I did, Server box, server box configurations, Refreshing the SE files and Zend files directly from the dashboard of my account, and these issues "Still" persist.

**Comment by SpiritWolfie** [comment]
here is the base themes (once again nothing else enabled except SE, and packages have been refreshed)

This is the Modern theme

![image](https://cloud.githubusercontent.com/assets/9712738/24777160/f293bac4-1ad8-11e7-9e99-c1d7b2876f41.png)

**Comment by SpiritWolfie** [comment]
I also keep running into this

[Violation] Forced reflow while executing JavaScript took 43ms
home:1 GET https://www.furgather.net/index.php/externals/soundmanager/swf/soundmanager2_flash9_debug.swf 404 (Not Found)
core.js?c=336:565 activity update loop start
core.js?c=336:565 activity update loop stop
core.js?c=336:565 activity loop req complete
core.js?c=336:565 activity update loop start
core.js?c=336:565 activity update loop stop
core.js?c=336:565 activity loop req complete
core.js?c=336:565 activity update loop start
core.js?c=336:565 activity update loop stop

**Comment by FG-QuirkyKitty** [comment]
@DonnaScriptTechs As a curiosity, does the high-activity site you mention use a responsive theme?

I ask because media queries and the such are a common cause of forced reflow, which can also cause this sort of issue. Unfortunately, forced reflow is often required when dealing with responsive themes as a general rule.

**Comment by DonnaScriptTechs** [comment]
@FG-QuirkyKitty I didn't check to see if they do. Our 4.9 is coming with a responsive theme and it's working fine thus far. However, I believe our support answered your ticket last night. I've not checked but I hope they did.

**Comment by SpiritWolfie** [comment]
@DonnaScriptTechs 
With all due respect......
If you call basically telling me I need to spend money for them to "look" at issues we've confirmed on both a fresh install of social engine straight out of the box and confirmed on our live site with every single plugin disabled except core social engine stuff a answer then yes, Yes they did answer my support ticket../Sarcasm

I can confirm these issues on multiple server configurations across the board, Fresh installs, and I keep being told its ether my server box or a issue with my installation or 'its site spefic' Allot of these issues I've even confirmed on your guy's demo site, Yet I get no patches, no help, no support, I get told "Spend more money"

With all due respect in all fields I paid over 300+ dollars so far toward this engine, Since day one of my purchase I've been treated like everything is "Our fault" both here in the github (Having tickets prematurely closed, staff fighting with me or encouraging/telling me to spend even more MONEY) 

I've paid COUNTLESS Coders, programmers whatever term you wish to use, to look these issues over and they Keep telling me its a issue with social engines Code somewhere, I've hired a CSS expert etc, Where do I draw the line on how much money I need to spend to get basic level stuff fixed that shouldn't be happening out of the box?

I have ran Druple, Joomla, Dolphin, Oxwall, Elgg without these level of issues, While it may not be as featurestic as social engine but I've NEVER had these kind of problems...

Everytime I try to seek help or a solution, I get told "You want us to look? Give us money!" You guys sold me a broken product right out of the box, I expect it to work, I paid for a product I am YOUR Customer who has been happy sense day one, I was told SE had blocking, Daring a sells inquiry, That is not the case, I've proven this countless times, (supposedly 4.9 has working blocking) the point is, I am Completely sick and tired of being told Its a issue with my box, or my website, or 'my specif install' when I can reinstall social engine god knows how many times in different OS environments and reproduce these same issues over and over and over! 

I am putting my foot down, I should not have to PAY to get someone to fix a dang bug with a product I PAID FOR, So someone PLEASE For the love of god help us I am not a LIMITLESS ATM for money, and these bugs have been repeatedly confirmed, I don't care if other people have 'reported them or not' I can make you a VIDEO showing these bugs being reproduced over and over and over.

I Could make a mile long list of things that should be in social engine out of the box like uh Spell check in the forums/blogs etc? This isn't a browser issue its a issue with SE at its core not allowing browser to use the spell check feature...

or what about the swiffplayer issue thats reproducible repeatedly on a fresh install?

or the core.js loop that was listed as "Fixed" in the patch notes, yet I can freshly install SE right now and reproduce that as well

Or the token errors that I keep getting (once again reproducible on fresh install)

How about this

**Tell me PRECISELY What server configurations to use, What OS etc, and I will set up a Dev site on the configurations you CHOOSE FOR ME, And I will reproduce all these issues on the "configuration"/'setup' of your choice, Just tell me the OS or whatever and I'll get it going, and I promise you I will STILL have these issues.**

IF you believe 4.9 will fix my problems then I can only hope but right now I am pulling my hair out because my website is consistently growing on a day to day bases and more and more people are getting very upset with my website and no matter who I reach out to, Or pay to look things over I get told the same things, Go talk to social engine, When I talk to social engine I get told "Give us money then we look".... So ether the problem is SE or supposedly All the people I know who have been coding for years, work for big name companys such as Riot ,Linden labs, Blizzard, Delict does gaming, Oracle, ETC has been lying to me about where the problem lay's, Which I honestly doubt is the case...

I doubt this is the case because me and quirky Spent the entire day/night YESTERDAY Doing Diff checks because a fresh install of SE and our live site File by file, Plugin by Plugin, SE Core etc... and no matter how hard we tried we kept finding issues with SE out of the box! 

Yes I'm upset, NO I Will not pay to have someone from the tech team of SE Simply LOOK over things to only find a reason to not do anything like most of my support tickets have been handled.

**Comment by SpiritWolfie** [comment]
To prove my point about my above rant 

I have once again re-installed SE following the documentation listed here 
- https://support.socialengine.com/php/customer/portal/articles/1667583-installing-socialengine

This has been followed precisely... Create my user account and right click the page and hit 'inspect' This shows up in google chromes inspect and Firefox's Firebug 

![image](https://cloud.githubusercontent.com/assets/9712738/24795789/73257112-1b3f-11e7-8525-58646556b6f6.png)

Regardless how minor this might be, this was claimed to have been fixed in previous notes

I have used the files directly from my -account- dashboard, as seen from this page here

![image](https://cloud.githubusercontent.com/assets/9712738/24795878/c16713ee-1b3f-11e7-9d31-7bf28afc938b.png)

Following this, Nothing has been touched or messed with, I am using the default theme pre-included in social engine, the version of said engine shows up correctly as seen here 

I've did a snippet in the below image to protect my product key since it shows all admins that info (cough) and anyone access to said panel (Plz fix this security issue)

![image](https://cloud.githubusercontent.com/assets/9712738/24795966/11909c00-1b40-11e7-8322-04c5b54228f9.png)

taking it a step further, Mind you this is only taking me a few moments as I type this to reproduce this stuff on a FRESH INSTALL

![image](https://cloud.githubusercontent.com/assets/9712738/24796109/8f671ad2-1b40-11e7-8f32-abf9e99d5c5b.png)

if I wanted to change Gender to "Species" Adding X species starts causing this MENU to wig out (I've reported this in the past multiple times to be told this is not reproducible) I Just reproduced it in moments!

This is just Some small examples of how I can break SE right out of the box in less then 10min!, ALL of this I have reported, and been told it couldn't ether be reproduced (Cough cough) or some other excuse and my tickets got closed, some where not closed and honestly looked at and found to be a issue... (Not very many compared to how much I've reported)

So what's it going to take you guys to take me seriously and start treating me like I know what i'm doing?

I DO have coding experience!, I have computer knowledge, I've been in this field for over 16years.

/Done

**Comment by SpiritWolfie** [comment]
To prove my point about my above rant 

I have once again re-installed SE following the documentation listed here 
- https://support.socialengine.com/php/customer/portal/articles/1667583-installing-socialengine

This is a pretty fresh install of SE that I put up not to long ago. It has not been modified in any way

![image](https://cloud.githubusercontent.com/assets/9712738/24795789/73257112-1b3f-11e7-8525-58646556b6f6.png)

Regardless how minor this might be, this was claimed to have been fixed in previous notes

I have used the files directly from my -account- dashboard, as seen from this page here

![image](https://cloud.githubusercontent.com/assets/9712738/24795878/c16713ee-1b3f-11e7-9d31-7bf28afc938b.png)

Following this, Nothing has been touched or messed with, I am using the default theme pre-included in social engine, the version of said engine shows up correctly as seen here 

I've did a snippet in the below image to protect my product key since it shows all admins that info (cough) and anyone access to said panel (Plz fix this security issue)

![image](https://cloud.githubusercontent.com/assets/9712738/24795966/11909c00-1b40-11e7-8322-04c5b54228f9.png)

taking it a step further, Mind you this is only taking me a few moments as I type this to reproduce this stuff on a FRESH INSTALL

![image](https://cloud.githubusercontent.com/assets/9712738/24796109/8f671ad2-1b40-11e7-8f32-abf9e99d5c5b.png)

if I wanted to change Gender to "Species" Adding X species starts causing this MENU to wig out (I've reported this in the past multiple times to be told this is not reproducible) I Just reproduced it in moments!

This is just Some small examples of how I can break SE right out of the box in less then 10min!, ALL of this I have reported, and been told it couldn't ether be reproduced (Cough cough) or some other excuse and my tickets got closed, some where not closed and honestly looked at and found to be a issue... (Not very many compared to how much I've reported)

So what's it going to take you guys to take me seriously and start treating me like I know what i'm doing?

I DO have coding experience!, I have computer knowledge, I've been in this field for over 16years.

/Done

**Comment by DonnaScriptTechs** [comment]
Please keep each issue to one thing as per our instructions. This aids us in resolving issues. We understand you are frustrated but all of the extra input will confuse the issue for this bug report itself. This issue is the CSS issue. We will address that in this report. 

Regarding support, I looked at the history and we answered the tickets and even went beyond our [policy](https://www.socialengine.com/terms-and-privacy) in a few tickets and provided fixes that are not part of support. We can address any of those concerns via a ticket to sales if you have some specific tickets you are not happy with. Please link those in a ticket to our sales department which can be done via your account or via the contact us form.

An agent is checking your current ticket for the response that was sent last night.

**Comment by SpiritWolfie** [comment]
@DonnaScriptTechs 

'Address' by telling me to spend more money is not 'addressing' anything, I am by no means trying to be disrespectful, You want to help resolve the CSS issue Lets do that

Here are my questions.

1) What can I do to find more information about what's happening when the CSS breaks? because CTRL+U that people have suggested just calls the websites source page and inspect isn't being helpful in this regards.

2) What log files should I be looking at for something related to this?

3) since SE is ran off of Zend framework, How would one Enable the DEBUG apart of the zendframework so we can better look at whats going on?

4) Any other tips or advice you can give for me or my coders to help us re-stabilize our website that isn't going to cost us money.

**Comment by RaymondBenc** [comment]
@SpiritWolfie Just wanted to drop a line that we are looking into this issue.

I've logged into your site and was able to confirm the issue with the missing `swf` file, which you pointed out here 
![image](https://cloud.githubusercontent.com/assets/9712738/24774517/158744ac-1ace-11e7-9319-f928753f3d85.png)

In 4.9 we changed how we reference the parent file, which at this time we believe should solve the issue. However, we are going to be taking another look at it.

As for the CSS blanking out, I was not able to reproduce it now, but like you mentioned its intermittent. If it does happen again, try to check the error log `/temporary/log/main.log` or `/temporary/log/scaffold/*`.

Hang in there, we will get to the bottom of this. As for the future of handling CSS I can assure you this will change very soon as one of the proponents we are working on is to move away specifically from Scaffold so SE loads your CSS file(s) statically and never touches PHP code.

**Comment by SpiritWolfie** [comment]
@RaymondBenc 

This has to be one of the best responses to a issue I've written...  Thank you so much!, my dev site shows the loop error btw (if I installs a responsive theme the loop error goes away) What you've said makes perfect sense, Me and my coder keep seeing issues with the purgatory? 

I am super sorry for my attitude earlier, but I just can't take the consistent money stance toward me anymore :( ... just myself my staff team and my entire community is beyond frustrated...

If you don't mind, I do have this question here;
Also I have a off topic question, Please tell me that the thumbnails in 4.9 are gif animated supported and not just your profile avatar picture.. (we all want animated gifs for 'posting' on the wall) not our avatars ^^;

**Comment by DonnaScriptTechs** [comment]
@SpiritWolfie I tested on my local 4.9 and loaded both an avatar and a status post image. Each image is animating for me. Is that what you meant?

**Comment by SpiritWolfie** [comment]
@DonnaScriptTechs 

On the 'activity wall' if you make a post will the 'thumbnail' animate

here's a picture with circles for where i'm talking, It would also be nice if it functions on users profile pages too (for their personal activity feeds) and even in forums etc.. (or at least have a option to flip it on or off)

**Comment by DonnaScriptTechs** [comment]
Yes, the thumbnail in the feed is animated when I:

Posted a status in the main feed with an animated gif attached via the photo button.
On profile when checking the status feed post, it is animating.

Please feel free to continue that part of this discussion on our community where I can provide screenshots perhaps (but it won't show animating via a screenshot) as we would like to keep this issue tracker for the issue mentioned. :) We can also converse at our community better.

**Comment by SpiritWolfie** [comment]
@DonnaScriptTechs 
Understood, Thanks

@RaymondBenc I would be honored to get with you perhaps in a call or something or what not and go over some issues to make things more real time and quicker to deal with if you ever get permission/time to do so, I think you and I could potentially figure stuff out and even perhaps find stuff that needs to be fixed with your help and my bug hunting skills.

for the css (in relation to this thread) allot of the issues is that as it stands Social engine pulls CSS in ways it shouldn't, or way to much, more then other platforms, this alone can create issues, then one thing pulls from this call and many other things conflict and want to pull from call, then this here and that here, it creates to many requests that begin to time out and what not.

Allot of it has to do with the Scaffold system in place from what we've seen and the perhaps the way the stuff handles caching?

**Comment by FG-QuirkyKitty** [comment]
@SpiritWolfie I would also like to see what comes in those logs whenever the CSS is not rendered/pulled. It may provide some information I'm not privy to yet.

**Comment by Elshara** [comment]
The fewer queries the better. That's how top ranking websites actually
get to page ranks above the millions.

**Comment by DonnaScriptTechs** [comment]
This should be resolved with the 4.9 changes as mentioned. If you find it an issue still, please test after 4.9.1 releases and see if the CSS issue is still there. If so, please submit a new bug for that issue.

**Comment by Elshara** [comment]
okay
