### ISSUE TITLE
Login with facebook- does not work

### ISSUE THREAD

**Issue by ciaoamigo** [SocialEngine/phpv4-issues#626]
Since March 25, the login through facebook, it stopped working.
SDK-facebook using socialengine is too old!
How to solve?

**Comment by Elshara** [comment]
Confirmed. Graph api won't update and the code has to be updated from
the client, social engine side, to reach server, facebook side.

**Comment by DonnaScriptTechs** [comment]
I have added this for our team to check. Thank you for your post.

**Comment by eugene-wh** [comment]
The fix is rather simple, but it will be nice to add some checks here. Currently, when the problem appears it's impossible to see any clues in the error log. More importantly, the website owner isn't aware of the problem until there are multiple users' complaints coming it.

Please add some checks in the new version.

**Comment by Elshara** [comment]
What do you recommend for the fix?

**Comment by eugene-wh** [comment]
I've posted details here
http://socialenginecamp.com/question/view/1091/social-engine-4-8-and-broken-facebook-login

Note, this fix does not include proper error handling, which should be added to avoid the repetition of a situation like this.

**Comment by DonnaScriptTechs** [comment]
This is fixed for 4.9.0 when it is released. If you still have this issue after we release, please open a new bug report.

**Comment by Elshara** [comment]
Awesome!

**Comment by djSupport** [comment]
So Basically, go edit the code myself or wait to pay to upgrade for a fix?!?!?

**Comment by Elshara** [comment]
What do you mean?
