### ISSUE TITLE
Feature request - Logout page in Layout editor

### ISSUE THREAD

**Issue by poeticjustice** [SocialEngine/phpv4-issues#627]
Hi 

Feature Request.

Be great to have a page for signout to be added to layout editor

Purely as we could place ads on the signout page, or add HMTL code.
Example some installs of SE may be in a sub folder, and with a signout page in layout editior, html can be used to redirect to the main display page.

@gsf00001 raised similar in #590 that was closed for ability to set a redirect in settings, but it may be easier to just add Signout page to layout editor

**Comment by gsf00001** [comment]
Actually I seem to like both options - an actual page in layout editor as well as a redirect (my original #590 ).  The 'logout options' could be:
- LP (the default and only option now)
- 'Logout/Signout' page in Layout Editor
- Redirect to another URL (my current configuration which took 3 lines of code in 2 places - I just don't like to have to edit Core upon updates - and prefer not to edit Core ever for anything).
- Other ideas?

I don't use my LP for anything (well, except it gets loaded by default upon certain conditions that I can't control).  The login for the site is from a front-end page which the user is returned to upon logout.  The LP is simply too limiting for my needs (both for logging in and out) no matter what Theme I've used.  

Great idea @poeticjustice - I didn't even think of a page in Layout Editor.  But then if using that I'd like the ability to enable/disable Header/Footer separately.

**Comment by Elshara** [comment]
I was thinking. The ability to add a redirection page within the core
section of layout editor, so you could just trigger that page to be
activated to take a user to a target destination, as a member does a
certain action to make it appear where such action is set by you to do
so as administrator, would be ideal.
So for instance. Creating login page would achieve two results.
1. Target a redirect as soon as a browser visits the specified url. It
would work as the reverse of the login url in this way.
2. The redirection widget could be set to do anything. But in that
case, its primary target would be to specify a url. IT could be
programmed to do other things, like send notification updates,
activity feed updates, as a security measure. As well as log
information, statistics, you name it. It could lead us into new
territory.

**Comment by Khushboo016** [comment]
Hi @poeticjustice, we have added this feature request to our internal feature tracker and whenever we'll work on the improvements for Layout Editor section, this would be considered.

Thanks & Regards!

**Comment by Elshara** [comment]
Awesome!

**Comment by poeticjustice** [comment]
:)

**Comment by Elshara** [comment]
This will be great to see once implemented.

**Comment by gsf00001** [comment]
I'm excited

**Comment by Elshara** [comment]
So am I.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#71

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
