### ISSUE TITLE
send message to multiple recipients / FluentList wrong

### ISSUE THREAD

**Issue by oddityFry** [SocialEngine/phpv4-issues#628]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1 Messages Module
2. Translation "Between you and %1$s" is wrong
3. at senders site looks ok. e.g. "Between you and B, C and D"
4. on recipients (e.g. B) site is the same like 3) ... expected "Between you and A, C and D"

What happens?
-------------
Send a message to multiple recipients.

What were you expecting to happen?
----------------------------------
see 4)

What versions of software are you using?
----------------------------------------
**SocialEngine PHP Version:** 4.8.12
bug must be in //application/libraries/Engine/View/Helper/FluentList.php

**Comment by Elshara** [comment]
Interesting.

**Comment by poeticjustice** [comment]
screenshot?

**Comment by oddityFry** [comment]
<img width="436" alt="bildschirmfoto 2017-04-05 um 14 10 02" src="https://cloud.githubusercontent.com/assets/17434471/24704987/2eed4cd0-1a0a-11e7-8b05-61cce5ef3364.png">

there's not to much to screeshot. looks like this. for both users.

**Comment by Khushboo016** [comment]
Hi @oddityFry, Thanks for bringing this issue in front of us! We would resolve the same in near future releases.

Thanks!

**Comment by Elshara** [comment]
Awesome!

**Comment by DonnaScriptTechs** [comment]
We've added this to our list to fix . As this tracker is closing, we'll close this now. For new bugs, please post at our [new community](https://community.socialengine.com/forums/).
