### ISSUE TITLE
Update Uploader

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#63]
Social Engine should use a better uploader. Flash based uploads won't work in mobile. I recommend an integration with some of these for better performance. http://designscrazed.org/html5-jquery-file-upload-scripts/

**Comment by smazurov** [comment]
we already use html5 uploader for ipad and mobile.

**Comment by Elshara** [comment]
I'm still installing an alternative at the earliest convenience. It'd
be nice to have a few available.
