### ISSUE TITLE
Create Recent Notifications Widget

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#631]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Go to recent notifications page.
2. … Notice it does not appear in layout editor, or under any available widgets as a content type.
3. … There are many options you could make to expand this area of core updates.

What happens?
-------------
… Every post type you ever make gets sent here. Any response to post types get sent here. Any requests for friendship you have get sent here. Any new messages you receive get updates here. Any invitations you receive also get updates here. The point is, there's no way to establish widget customization for this page. There is also no way to prioritize the types of widgets you are most likely to encounter here either.

What were you expecting to happen?
----------------------------------
… To be able to set custom layout for widgets here. Each widget controls a different action type of what you have to be able to better filter options you may wish to view as most or least important.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Recent notifications are the life line of social engine sites. There's no other page for people to go to manage anything else, so making this page look like it's useful is essential.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by gsf00001** [comment]
Great idea (similar in concept to Requests/Invitations in #633 )

**Comment by Elshara** [comment]
I know right?

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#72

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
