### ISSUE TITLE
Create Friend Request Widget

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#632]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … The current requests widget controls events, groups and friend requests.
2. … It would appear this widget could be made into 3. One for groups. One for events. One for friend requests.
3. … People usually associate friend requests, messages and notifications as 3 separate modules just like Facebook.

What happens?
-------------
… When requests are sent, they usually appear as a link to the recent notifications page. From there, only 10 items can load at a time depending on what requests you do receive. So if you have 20 group invitations, 10 events and 5 friend requests awaiting your attention, you have to approve each request by reloading the notifications page just to see the latest requests you have. AS there's no pagination for that page, and no way to display content on that page, this means requests get buried if you have a lot of them to answer.

What were you expecting to happen?
----------------------------------
… Friends to have their own page. Along with subsequent pages from pending and approved requests. The same idea be possible for follows as well. Have widgets designed for follow requests if you have your community set for custom verification and one or two way friendship.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Friends, mutual friends and other people are a great way to start having custom relationships with people, especially new members who may wonder how to be involved in the social activities your network has to offer.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by gsf00001** [comment]
Yes, this would be very useful (SEAO offers this via widget and it includes so many more useful items with each 'type' of item selectable individually).

**Comment by Elshara** [comment]
I would love this two.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#73

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
