### ISSUE TITLE
Content Invitations

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#633]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Apart from groups and events, nobody is aware other content exists as they only receive notifications about things they post.
2. … Invitations help get conversations noticed.
3. … This functionality is in its bare infancy right now in social engine.

What happens?
-------------
… Content you create has the ability to notify you if comments or likes happen to it. The problem is, one sided personal activity only works out best for the original share holder of the content, the person who created or posted it. The only way people know how to engage with something, is if they search for it. Content invitations, allows the ability to share something with friends or other contacts, by giving people the option to inform people about the existence of posts. This allows members to manually yet automatically, be informed about important posts their friends, or administrators wish to share with them.

What were you expecting to happen?
----------------------------------
… Better options to engage members with the things they post.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Sharing is caring. Making invitation content possible, allows people to invite members to post on all content types. It allows people to add others to an existing conversation, be it in a module post, comment, message or general announcement. It allows tagging to be possible to engage people so they know you are thinking about them to invite them to post. I propose the ability to have individual post widgets assigned within or throughout the site, allowing people to share both core and module content in such a way.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#74

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
