### ISSUE TITLE
Portable Profile Widgets

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#634]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Profile widgets can only be displayed on profiles.
2. … Profile widgets don't give you the ability to display custom item counts prior to pagination appearing.
3. … Too many profile widgets on one page, cause slow loading and lots of scrolling.

What happens?
-------------
… Widgets do not display on any other page. They would be ideal for manage pages so you could perhaps make changes to posts in bulk or remove them entirely.

What were you expecting to happen?
----------------------------------
… Widgets related to profile content to be portable so you could compare them to content posted on other pages. Or make custom pages with them on it. For example. Loading up the browse page, and while you are viewing latest content, you could view content you've posted along side it if you have shared anything there.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Profile widgets help you visually see your contributions as you browse the site.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by gsf00001** [comment]
==>"Widgets related to profile content to be portable so you could compare them to content posted on other pages."

Yes, this would be very useful (and there are sites I use that do this - show me 'my contributions' related to the viewed content.  It's definitely very engaging (at least to me).

**Comment by Elshara** [comment]
Exactly! That's all a part of what members share. It's not just the
posts of topic starters which are important to sites. IMO too many
modules make it difficult for sharing to be comfortable for members to
do even for business. People are just used to sharing things in one
place. But they don't want a feed to have to look at to need to share
everything in, because they hate having to scroll with no landmarks or
bookmarks on posts they wish to keep. Or at least have reminders
they've participated in them unless someone shares notifications about
responses to such posts. So it would be much easier to have widgets
take such tasks on board to heart.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#75

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
