### ISSUE TITLE
Separate Joined And Created Groups And Events Display Order

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#635]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Groups and events display your content based on your participation.
2. … Your activity has both joined and created partitions to it.
3. … AS of now, they are displayed as one unit in social engine.

What happens?
-------------
… Instead of separating the displays, they are conjoined.

What were you expecting to happen?
----------------------------------
… Groups and events as well as other parental content, to show you what you have joined or participated in, as well as show you what ones you have actually organized or created.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… This would make it easier to manage.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by gsf00001** [comment]
This is a function of SEAO Plugins that I just assumed SE had (but based on this tix it seems SE doesn't).  It's very useful to differentiate what the connection is between the User and content.

**Comment by Elshara** [comment]
I agree. That's why I shared it here.

**Comment by DonnaScriptTechs** [comment]
Please post this as separate requests at our [feature request area](https://github.com/SocialEngine/phpv4-feature-requests/issues).
