### ISSUE TITLE
Add Contribution Filters For Posts And Comments

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#636]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … All modules except the forum, contain the ability to view personal content.
2. … Content you contribute to however, is also a very useful management tool.
3. … There is no way to display content based on what you've commented on or otherwise contributed to posted by others.

What happens?
-------------
… Content you post falls into one of two categories. Something you contribute to by another author. Something you have posted yourself. Such content is defined as contributions, if you contribute to content posted originally by someone else, as in the form of a share, like or comment. Among other reactions, being able to display your own contributions based on themselves, will help you be able to view your own activity purely based on contributions to what other people have posted. Currently, there is no way to do so yet in social engine.

What were you expecting to happen?
----------------------------------
… To be able to view post contributions you and others have posted respectively.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Posting means you have a mutual connection with what ever it is your interests are currently focused on. So if you bring focus to the connection it self, you can grow it and keep it active.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by gsf00001** [comment]
I definitely see this as useful - including myself as a User not just an ADMIN.  There are sites I'm a member of that allow this and it's great to be able to locate all the 'stuff I did' because I often wish to refer to it later on.  This is a little like an autosubscribe function for all of 'my own' content, but without harassing me with notifications about them - just allowing me to access anthing I've done (like, comment, share, etc.).  3rd-Party Devs could build on this too if it was part of SE Core.

**Comment by Elshara** [comment]
Awesome!

**Comment by gsf00001** [comment]
So it seems that only 2 of the tens-of-thousands of SE Site-ADMINs see this as useful?  

:(

**Comment by Elshara** [comment]
I'd start tagging but was advised against it numerous times..
Wish it was encouraged. :) Would totally get a poll started.

**Comment by DonnaScriptTechs** [comment]
Please add these as separate requests in the new feature area. These are weighty requests (they will add weight to a site) and should be separate.
