### ISSUE TITLE
Create Sub Post Navigation

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#637]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … When viewing profiles, there's no way to view post navigation for existing module types.
2. … Same goes for groups, events and other folder file related structures.
3. … Having such shortcuts available would go a long way in making activity happen.

What happens?
-------------
… People don't want to scroll to see what people have posted where.

What were you expecting to happen? Finding the ability to post something, is very challenging at present for parental structures within social engine. Navigation on such a level would make this problem virtually disappear. Widgets for secondary navigation and control would make this possible.
----------------------------------
…

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… You would also need to create pages for such modules in full using the layout editor to customize them as if they were main site areas.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#76

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
