### ISSUE TITLE
Site Wide Breadcrumb Support

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#638]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … I'm not talking about the food. I'm talking about post suffix or prefix navigation related to module page positions.
2. … This functionality doesn't exist yet for social engine. However it would be very useful.
3. … Breadcrumbs help seo.

What happens?
-------------
… A bread crumb is a way of sub navigation. So if you are viewing a blog for example, bread crumbs will show you links on how to directly navigate to the page you are on. From the home page of the site installation directory itself. So for instance, if viewing a blog page, home, blogs, blog page, would be the subsequent links bread crumbs would apply to. This feature, if available site wide, would allow better navigation for everyone. Especially for search engines, directing users to an article for the first time. This way, the main menu at the top of the page, has much better use, because of its relativity to where you are now. Rather than just displaying module links. If mutual or customizable bread crumbs were available, you could jump to any page of the site without having to go the long way around, effectively creating any kind of short cut on request.

What were you expecting to happen?
----------------------------------
… Such to be implemented.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Bread crumbs are cool. They make great badder for cooking.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by Khushboo016** [comment]
Hi @Elshara, Thanks for the suggestion! We already have plans for the implementation of breadcrumbs on a SE PHP site in future.

Thanks & Regards!

**Comment by Elshara** [comment]
Awesome!

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#77

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
