### ISSUE TITLE
Better Text Editor

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#64]
Social Engine should use a better text editor. As is the case now, html source code cannot be edited inline, as is the case with a few other features of the editor, where it could be more useful. People should have a way to collapse the option bar when making a post this way they can click on what they need rather than just being faced with a few rows of buttons.

**Comment by meetgerry** [comment]
I agree with you Elshara. The current text editor is so outdated and is so heavy.

**Comment by Elshara** [comment]
Glad I'm not the only one.

**Comment by wtoalabi** [comment]
No Elshara, you are not the only one.
Please help us change this.
Thanks!

**Comment by Elshara** [comment]
I'll do everything I can within my power to do so.

**Comment by Elshara** [comment]
In another issue called paragraph spacing opened by jbakuk I explained
alternatives for text editors for social engine.

**Comment by DonnaScriptTechs** [comment]
We have updated TinyMCE in 4.9.0. When it is released, please see if it works better for you. If not, please submit a new issue for us to check but please be more specific to the issue. Thank you.

**Comment by Elshara** [comment]
Awesome.
