### ISSUE TITLE
Create Video Albums

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#640]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Post a video.
2. … View it.
3. … Notice, you can't group it anywhere.

What happens?
-------------
… Videos you post cannot be made into albums.

What were you expecting to happen?
----------------------------------
… Albums to be possible. As well as to control whether or not videos auto play.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Albums are a great way to organize content.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by gsf00001** [comment]
Are you referring to something like what SEAO and SES offer with their Video/Channel Plugins?

**Comment by Elshara** [comment]
Yes I am.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#79

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
