### ISSUE TITLE
Create Files With Albums

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#641]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Add ability for files to be posted.
2. … Add ability for folders to be posted.
3. … Assign files to folders.

What happens?
-------------
… Not created yet.

What were you expecting to happen?
----------------------------------
… Inline files to be accessible instead of having to use file media manager.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Essential feature for post types without integration of content.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by gsf00001** [comment]
@Elshara Are you referring to the functionality that Radcodes' Folder/File Sharing Plugin offers for all Users or something different for ADMIN (since you mention 'inline files ... file media mgr'?

**Comment by Elshara** [comment]
Yes. Inline file functionality would include things like post
attachments, but they would be interactable on the web rather than
having to separately need to download the file. Whereas file folder
functionality would allow better control over what people could
actually download, or view inline as such as options.

**Comment by Khushboo016** [comment]
Hi @Elshara, For this requirement, we suggest you refer to the above-mentioned "Folder / File Sharing Plugin" developed by our third party developers Radcodes.

Thanks & Regards!

**Comment by Elshara** [comment]
Well I was thinking, file media manager could support this.

**Comment by gsf00001** [comment]
I too wish that File/Media Manager had folders and offered more 'management' capability.  I gave up on it a while ago and moved most of my files to another folder w/sub-folders that are referenced in the site using relative addressing.  This way, I can .ftp to view/manage my files better, and it keeps the list very short in F/M Mgr.

**Comment by Elshara** [comment]
Exactly. That's why I've been using a sub domain boonex dolphin for a
web server file manager.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#80

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
