### ISSUE TITLE
Audio Video Posts

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#642]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Posting can only currently be possible using text and embedded content for files, photos, music and videos.
2. … Audio Video and file posting allows responses to be gathered by real world data.
3. … Virtually made possible through html5 or flash.

What happens?
-------------
… Not available yet.

What were you expecting to happen?
----------------------------------
… Comments and posts to support responses like this.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Dolphin pro has this feature and it gets used frequently.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by DonnaScriptTechs** [comment]
Can you elaborate please? I don't understand the request. A description or example would be great. :)

**Comment by Elshara** [comment]
To be able to record or upload a video or other file type to post as a
response or main post.
Video comments. Or video posts.

**Comment by Khushboo016** [comment]
Hi @Elshara, Thanks for the suggestion, we have added your suggestion at our end and will discuss it with the team to see if such a feature can be implemented in the core module in future. For now, we suggest you refer to the various third party Advanced Activity Feed based plugins to have these features on your site.   

Thanks & Regards!

**Comment by Elshara** [comment]
Awesome! I will check them out. So far I haven't found any third party
ability to accomplish this yet. But it's a great suggestion to
consider, hence I posted it.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#81

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
