### ISSUE TITLE
Create View Other Posts By Member Widget

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#643]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Videos feature has this integration along with plenty of others.
2. … Such is made possible via either a pagination link to view such persons content, or the ability to have it be widget related.
3. … Anything goes. Other posts people have reacted to, liked, commented on, rated, viewed, shared, reported, etc.

What happens?
-------------
… Currently unavailable. Except for the videos widget.

What were you expecting to happen?
----------------------------------
… The idea is you are able to view other posts a particular user has made or contributed to and vice versa.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Works well so far in videos integration. Other posts should have this two.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#82
