### ISSUE TITLE
Custom Action Types

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#644]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Responding to posts gives you the option of choosing how to do so.
2. … There are times when the choices social engine gives you, aren't always extensive enough to fulfill such a requirement you have in mind.
3. … Custom actions allows you to make such choices known, by simply choosing what you want to do with a post and how people can do such while they view it.

What happens?
-------------
… Comments and likes are fine. But favorites, rating, voting, inviting, sharing, reporting, editing, deleting, rearranging, reposting, disliking, closing, featuring, scheduling, assigning, moderating, merging, splitting, moving, archiving, trading, transferring, exporting, importing, migrating, collaborating, etc aren't out of the question.

What were you expecting to happen?
----------------------------------
… Members to be able to choose what type of reaction they want for each post they make, so people can do so.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Implementing such a system would be a simple matter of renaming the type of input field actions can have if they are independent to the post. Otherwise, actions can have dependencies regarding how the post looks and even if it is available to view at all. Essentially, creating action types which can be instances of support via the ability to add or remove response and other action specifications.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#83

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
