### ISSUE TITLE
Custom Input Fields For All Modules

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#645]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Modules only have the inability to post custom data. Data posted is one sided, and cannot be collaborated or contributed with based on original posts.
2. … Data bulk actions require certain content to be able to be flexible enough so that fields can be changed based on requirements of custom questions or input.
3. … Providing collaboration feedback is essential for data inputs to support mutual or multiple sided sources of information to be collected based on both dependent and independent values.

What happens?
-------------
… When you create a post, you have two - 5 options which must be completed. The title and description fields being the only requirements. Categories, tags and privacy options, are extras. But they are far from basic in terms of their needs, to support custom projects. Modules therefore, are built to try to make adjustments based on what types of data can be collected. Unfortunately, such data is specific to only social requirements, leaving out the possibility for business assessment of such requirements to be implemented or handled differently. AS a result, many fields and action types go hand in hand assuring mutual interest and compatibility with each other respectively. But what is missing, is the ability to add custom input fields to all posts be they messages, comments, module topics or other items requiring initial user activity.

What were you expecting to happen?
----------------------------------
… The ability to support custom fields and field types.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Social builders taken to a whole new level by members, will ensure one module, not 20, remains the go to source of information for all your real time or archived site needs.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#84

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
