### ISSUE TITLE
Replace Content Widget With Specific Widgets For Custom Positioning On All Pages

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#646]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Content could mean anything not displayed by other widgets.
2. … Widgets help keep order.
3. … By replacing content with new widgets created to display the items the content widget contains, you can rearrange the order position.

What happens?
-------------
… Widgets are the most flexible. The content widget cannot be customized.

What were you expecting to happen?
----------------------------------
… Replacement to improve things like post meta information. Likes. Separate from comments. Search separate from filters. Rate separate from player. Vote separate from results. Etc.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Dolphin pro does this, and it lets you have complete control of every widget available to you.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by Khushboo016** [comment]
Hi @Elshara, Thanks for this suggestion! We already have plans to work on the implementation of this feature in the future versions of SE PHP, so that the pages in the Layout Editor can be purely widgetized.

Thanks & Regards!

**Comment by Elshara** [comment]
Awesome! Sounds like a plan!

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#85

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
