### ISSUE TITLE
Bulk Forum Actions In Admin Panel

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#649]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Admin panel doesn't have the ability to automatically remove forum content.
2. … Actions taken to remove such manually take a lot of time.
3. … Giving time to automatically or bulk act based on forum topics or replies, would make a lot of sense.

What happens?
-------------
… When you go to the forums plugin in admin panel, you see the ability to manage forums and categories as well as global and member level settings. But no way to manage posts.

What were you expecting to happen?
----------------------------------
… Posts to be managed from admin panel.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Every other posts related plugin in social engine has this ability.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#86

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
