### ISSUE TITLE
Don't Restrict Character Limits For Activity Feed Posts And Comments

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#651]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Make a comment longer than 1000 characters.
2. … Have a post in the activity feed mirror it.
3. … Click the more link at around 100 - 250 characters as you view the post you just created.

What happens?
-------------
… The rest of whatever you posted gets cut off. Even after clicking more.

What were you expecting to happen?
----------------------------------
… The cut off point to only effect the more link, and not the entire post once it has been clicked.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… More links don't usually work well unless the entire post can be accessed through them.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by gsf00001** [comment]
I haven't tested this, but if it's true that 'more doesn't let you view it all, shouldn't SE flag this as a bug?

**Comment by Elshara** [comment]
Yes they should. But they limit the more to some other text limit,
instead of the full post. You can't see the full post.

**Comment by DonnaScriptTechs** [comment]
What do you mean:

>… Have a post in the activity feed mirror it.

**Comment by SpiritWolfie** [comment]
Just a small suggestion, but I know the wall uses a char limit, No one knows what that char limit is when they are typing, so it'd be great to know how many chars people have left to type

**Comment by SpiritWolfie** [comment]
I disagree with this though, Activity walls are not designed on any platform to be a place to write a Wall of text, and would discourage the use of things like Forums/blogs making them useless if people could abuse the activity feed like this.

**Comment by DonnaScriptTechs** [comment]
That's a great point @SpiritWolfie as a feed is meant to contain activity from the site in a short term capacity. Blogs, forums and other such venues are much better for writing longer posts. However, if we get a response from the OP with more details, we'll still test. I do believe we need limits in order to better manage the loading as well.
