### ISSUE TITLE
Separate Search From Filters For Browse Pages

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#652]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Navigate to a browse page.
2. … Locate the filters option.
3. … Notice search is always above it.

What happens?
-------------
… It's nice to keep the position there, but it would also be nice to separate search from filters so you could independently sort items. Right now, this isn't possible. The only thing you can do to make sure search works independently of filters, is to not use search results in a way which can be displayed using the filters. You can't do so anyways as the option doesn't exist to independently sort options, regardless of whether or not you have searched for something and see results there, or the option comes up when viewing all content of a particular assortment type.

What were you expecting to happen?
----------------------------------
… Ideally, to have search and filters be separate widgets in layout editor.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… This would give filters the flexibility they need to expand based on different post types. While making search, its own field type.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#88

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
