### ISSUE TITLE
Create Option To Duplicate Menu In Menu Editor

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#653]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Go to control panel.
2. … Go to layout.
3. … Click on menu editor.

What happens?
-------------
… You can either create a new item, or a new menu from any existing menu page. However what you can't do, when creating a new menu, is duplicate it or work from an existing menu to add some of its items to your custom menu.

What were you expecting to happen?
----------------------------------
… To have the option to build a menu based on an existing one. Or to have the option to merge or split existing menus into new ones and associate them with modules in the layout editor as menu widgets themselves, instead of needing to generate a generic menu to achieve the task.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Menus are great. They can become special, if we treat them well.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#89

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
