### ISSUE TITLE
Let Members Embed Their Content Pages

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#654]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … When members create posts, they have the option to share them. But they don't have the option to embed them onto other sites.
2. … This would allow anyone to grab an embed code to place it where ever to embed original and third party content.
3. … There's always something to be gained from being able to repost or reshare something important someone else has created.

What happens?
-------------
… Posts created just seem to go nowhere once they are on the site. Comments and likes make them recirculate at times, however they are essentially imprisoned where ever they land. Moving them from one place of the site to another, may be a step forward to progress in evolution as the posts grow, but making them flourish, needs to involve something else. The step beyond, would be to allow people to embed their content and profiles, or even the entire site, where ever they could, to gain traction and let people know, there is a way for people to do the same, and make mutual contacts inside and outside domain and database confinements. The purpose of websites, is to bridge containers, not isolate them. With people being the containers, communication here can remain a free road way.

What were you expecting to happen?
----------------------------------
… Post embedding to consist of all core modules.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… HTML code is far from dead.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by gsf00001** [comment]
SEAO offers an Embeddable Badge for their Groups/Pages/Businesses modules that allows the Group-Admin for example, to allow posting of selected types of content (feed, photos, videos, discussions, polls, etc) through an embed code.  Is this the type of thing you are referring to, but for Users to do so with their content, or something else completely?

**Comment by Elshara** [comment]
Yes this is what I am referring to, but have the post be sharable
through such a code on other sites.

**Comment by gsf00001** [comment]
Yep - thats what SEAO's Embeddable Badge does.

This could be useful for User content too as you've Requested.

**Comment by Elshara** [comment]
That's very interesting. When I looked up badges, social engine add
ons had a plugin which did not do what I thought. It essentially was
just like a gifts feature, giving badges like special titles or
statuses to members. That wasn't what I was after at all. I don't see
social engine solutions in the marketplace directory yet.

**Comment by gsf00001** [comment]
Elshare - my apologies.  SEAO (SocialEngineAddons) not SES (SocialEngineSolutions).  

The SEAO Embeddable Badge is different from the typical 'badge' Plugins that a few Devs offer.  This is a feature in some of their Plugins (Groups/Communities, Directory/Pages, Directory/Businesses, Stores).  Actually, I think it may be an Extension Plugin (which requires the main Plugin) for 3 of those.  Anyway, it's great because a Page may simply select the Content Type they wish to display, and then copy the created embed code into another site and voila - their content (from your site) now appears on another website.  Plus it has links back to your site in the top/bottom of the Embeddable Badge.

**Comment by Elshara** [comment]
I do not believe seao has the embed badge functionality as a stand
alone site wide solution. I'd love to integrate it with the share
feature personally.

**Comment by gsf00001** [comment]
Yes, you are correct - that's what I mentioned is that the Embeddable Badge is a part of some of their Plugins not separate (well, for 3 of them it's an Extension which may be purchased separately but is useless without the primary Plugin).

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#90

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
