### ISSUE TITLE
Create Records Of Existing Tags For Posts

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#655]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Create a post.
2. … Assign tags to it.
3. … Publish it.

What happens?
-------------
… The tags are shown, but only on the post itself. There's no independent way to view existing tags based on what the site has used.

What were you expecting to happen?
----------------------------------
… A tags module to exist showing the topics people post about.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… One per module is fine, but a site wide one would be interesting as well.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#91

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
