### ISSUE TITLE
Create Categories Widgets For Posts

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#656]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Assign a post to a category.
2. … Create a way to view the category independently of having to search for posts using it.
3. … Display such categories in use for all posts according to their respective module, as a widget.

What happens?
-------------
… As posts are created they are assigned to categories if you place them on your site. But categories are only view-able from the post itself. They cannot be viewed independently.

What were you expecting to happen?
----------------------------------
… Category lists to appear as a widget.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Allowing members to add their own categories would be beneficial as well, as you could see their contributions. You could also allow other members to use a category you have created, if you allow people to do so, effectively being the owner of your own little group within a module itself.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by gsf00001** [comment]
Would a hashtag Plugin help with this or am I not following you Elshara?

**Comment by Elshara** [comment]
Somewhat, but it would be complementary.

**Comment by DonnaScriptTechs** [comment]
we have category widgets for each module. Please check 4.9. If that is not what you meant, please open a new feature request in our feature area and please include screenshots.
