### ISSUE TITLE
Add Discussions From One Interface

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#657]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Set up forums and forum categories.
2. … Browse for them using the site.
3. … Click add discussion where ever you see the ability to do so.

What happens?
-------------
… Notice, you will only find such function in the forum itself. Rather than being able to add a discussion directly to any forum regardless of what page you happen to be browsing.

What were you expecting to happen?
----------------------------------
… To be able to have one central place where people can add discussions, but choose the forum they want it appear in the add form.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Forums module seems way too out dated. There's no pages to be able to view discussion topics in the layout editor. Or the ability to manage the menu items found on any of the forum pages itself.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#92

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
