### ISSUE TITLE
Make Post Attachments

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#658]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Create a post.
2. … View it.
3. … Notice at the bottom of the post, the usual comment, like, share functionality.

What happens?
-------------
… Once you're done with it, you may wish to assign it somewhere other than its natural place on the site. As a reference point, this could be achieved by attaching it to an existing post. Currently, you can't assign posts as attachments. The most popular use for this could be a video, photo, poll, discussion or related post involving all types of modules including comments, and parent posts found in groups and events. Activity feed updates are also important, for time information if such is important to the project you are working on.

What were you expecting to happen?
----------------------------------
… To be able to move, merge, split, update, add custom fields to or attach reference points to posts in a natural way.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Post attachments could bridge the gap between profile owners and collaborators.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web version.

**SocialEngine PHP Version:** … 4.8.13

**Comment by gsf00001** [comment]
Are you referring to something like how github allows you to reference another issue and link to it, or something entirely different?

**Comment by Elshara** [comment]
Yes I am.

**Comment by gsf00001** [comment]
Then, Yes please - may I have this too?

**Comment by Elshara** [comment]
If I had it to give, you'd already have it in your grasp.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#93

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
