### ISSUE TITLE
Upgrade SE4.9.0 Activity MSQL Duplicate column name 'modified_date'  error

### ISSUE THREAD

**Issue by mujaksaba** [SocialEngine/phpv4-issues#659]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. Socialengine Upgrade 4.8.13 to 4.9.0
2. …
3. …

Upgrade is finished with an error
Activity 4.8.12 upgrade to Activity 4.9.0 :
Mysqli statement execute error : Duplicate column name 'modified_date' 
Activity upgrade is not finished
…

What were you expecting to happen?
Smooth upgrade :)
Activity work without any problem

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** …

**SocialEngine PHP Version:** 4.9.0

**Comment by DonnaScriptTechs** [comment]
Thank you for your post. When you upgraded, did you make sure any third party products were compatible? 

Do you have plugins that may have added any database tables such as anything for the feed?

What version of PHP and Mysql are on the server? What operating system is on the server?

**Comment by mujaksaba** [comment]
Hello,
I have addons mostly from socialengineaddons, Advanced activity did not have in to datab base columnName 'modified_date'
For me is Linux server
Php 5.6.18
Server type: MySQL
Server Version: 5.1.73-cll-lve - MySQL Community Server (GPL)
Other errors are still sign in with twitter authorization.
I do not see any more errors.
here error log:
2017-04-13T09:49:50+00:00 WARN (4): [2] include_once(): Failed opening 'PEAR/Error.php' for inclusion (include_path='/home/bxxxxxxb/public_html/application/libraries:/home/bxxxxxxb/public_html/application/libraries/PEAR:.') (/home/bxxxxxxb/public_html/application/libraries/Engine/Loader.php) [103]
Error Code: 8824ad
Stack trace:
#0 /home/bxxxxxxb/public_html/application/libraries/Engine/Loader.php(103): Engine_Loader::autoload()
#1 (unknown file)(0): Engine_Loader::autoload('PEAR_Error')
#2 (unknown file)(0): spl_autoload_call('PEAR_Error')
#3 /home/bxxxxxxb/public_html/application/libraries/PEAR/PEAR/Exception.php(255): class_exists('PEAR_Error')
#4 /home/bxxxxxxb/public_html/application/libraries/PEAR/PEAR/Exception.php(327): PEAR_Exception->getCauseMessage(Array)
#5 /home/bxxxxxxb/public_html/application/libraries/PEAR/PEAR/Exception.php(318): PEAR_Exception->toHtml()
#6 (unknown file)(0): PEAR_Exception->__toString()
#7 /home/bxxxxxxb/public_html/application/libraries/Zend/Log/Formatter/Simple.php(103): str_replace('%exception%', HTTP_OAuth_Consumer_Exception_InvalidResponse, '2017-04-13T09:49:50+00:00 CRIT (...')
#8 /home/bxxxxxxb/public_html/application/libraries/Zend/Log/Writer/Stream.php(131): Zend_Log_Formatter_Simple->format(Array)
#9 /home/bxxxxxxb/public_html/application/libraries/Zend/Log/Writer/Abstract.php(88): Zend_Log_Writer_Stream->_write(Array)
#10 /home/bxxxxxxb/public_html/application/libraries/Zend/Log.php(464): Zend_Log_Writer_Abstract->write(Array)
#11 /home/bxxxxxxb/public_html/application/modules/Core/controllers/ErrorController.php(49): Zend_Log->log('
Error Code: 33ad59
errorAction()
#13 /home/bxxxxxxb/public_html/application/libraries/Zend/Controller/Action.php(516): Slpagenotfound_ErrorController->errorAction()
#14 /home/bxxxxxxb/public_html/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('errorAction')
#15 /home/bxxxxxxb/public_html/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Zend_Controller_Request_Http, Zend_Controller_Response_Http)
#16 /home/bxxxxxxb/public_html/application/modules/Core/Bootstrap.php(84): Zend_Controller_Front->dispatch()
#17 /home/bxxxxxxb/public_html/application/libraries/Engine/Application.php(160): Core_Bootstrap->run()
#18 /home/bxxxxxxb/public_html/application/index.php(219): Engine_Application->run()
#19 /home/bxxxxxxb/public_html/index.php(24): include('/home/bxxxxxxb/public_html/appli...')
#20 {main}

2017-04-13T09:49:50+00:00 CRIT (2): 
Error Code: 33ad59

 HTTP_OAuth_Consumer_Exception_InvalidResponse: Failed getting token and token secret from response in /home/bxxxxxxb/public_html/application/modules/User/controllers/AuthController.php on line 961

Exception trace

#	Function	Location

0	HTTP_OAuth_Consumer->getRequestToken('https://twitter.…', 'http://www.djesi…')	/home/bxxxxxxb/public_html/application/modules/User/controllers/AuthController.php:961

1	User_AuthController->twitterAction()	/home/bxxxxxxb/public_html/application/libraries/Zend/Controller/Action.php:516

2	Zend_Controller_Action->dispatch('twitterAction')	/home/bxxxxxxb/public_html/application/libraries/Zend/Controller/Dispatcher/Standard.php:308

3	Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))	/home/bxxxxxxb/public_html/application/libraries/Zend/Controller/Front.php:954

4	Zend_Controller_Front->dispatch()	/home/bxxxxxxb/public_html/application/modules/Core/Bootstrap.php:84

5	Core_Bootstrap->run()	/home/bxxxxxxb/public_html/application/libraries/Engine/Application.php:160

6	Engine_Application->run()	/home/bxxxxxxb/public_html/application/index.php:219

7	include('/home/bxxxxxxb/p…')	/home/bxxxxxxb/public_html/index.php:24

8	{main}

Best Regards

**Comment by DonnaScriptTechs** [comment]
We would need to check on your site to see if this is a bug or site issue. Can you please send a support ticket to us and in the subject please reference Github 659? If you don't have support, please email our support@socialengine.com and we'll go from there. We can't reproduce this in any of our upgrades.

**Comment by mujaksaba** [comment]
Hello Dona,
new ticket is open "reference Github 659"
Best Regards

**Comment by DonnaScriptTechs** [comment]
Thank you! Someone from our team will check it. :)

**Comment by leandrotavaresrocha** [comment]
I am facing the same issue. I receive two errors; The first is related with "modified_date" and sometime a editable.

**Comment by DonnaScriptTechs** [comment]
@leandrotavaresrocha would you also please send a ticket to our support? Either via your account or via the email I provided. Our team can check to see what the issue could be. Thank you!

**Comment by leandrotavaresrocha** [comment]
Thanks Donna. I send a e-mail. 

I made a test:
1- I checked my activity_actions table and there is a modified_date column. Considering all plugin that interact with activity feed that I already used there is two possible reasons: Wall Plugin from Hire-Experts or Advanced Activity Feed from SEAO.
2- I checked the activity_type and  there is not a editable column.
3- If you try to install and modified_date is already created it will crash, but if you try a second time it will display a error about a duplicated editable column.
4- I deleted both columns (when you try the second time the script create the column and crash) and tried again. The plugin was installed.

The point now is which plugin created this modified date.

**Comment by DonnaScriptTechs** [comment]
Yes we need to check that. Our testing didn't have that and my site went fine (for the clone upgrade). Thank you for sending the info. One of our team will check.

**Comment by SpiritWolfie** [comment]
Can confirm, happening on my site as well.

**Comment by DonnaScriptTechs** [comment]
Do you all have the same plugins? I mean third party? Are the plugins compatible with this version?

**Comment by SpiritWolfie** [comment]
I've disabled the plugins and tried to update and got the same issue, and its social engine addons yes. but I disabled them so it shouldn't have any affect.

I've also been having issues installing 4.9 all night.

**Comment by DonnaScriptTechs** [comment]
@SpiritWolfie please send a ticket to us so we can check it on your site too. Even if you don't have support. We are checking each one to see what the issue is. If it is a plugin that altered the database, disabling wouldn't change that (posting for others that might not know, I know you know that :) ). If it is a bug in our script, we can fix that. If it is with third party products, we'll let you know that as well.

**Comment by SpiritWolfie** [comment]
@DonnaScriptTechs 

well its not detecting mod rewrite (which is enabled and all other software detects it just fine, just not social engine) its also not detecting ImageMafic extension for gifs which we have turned on, and once again other software is detecting it... so I have no dang clue whats wrong with the updates x.x

**Comment by DonnaScriptTechs** [comment]
That's good info to provide in the ticket please. Our technicians will look to see what's up in case of an issue with the upgrade process, or with third party products or something else. Thank you.

**Comment by mujaksaba** [comment]
Hello.
Support team has problem solved.
Thank you very much :)

**Comment by SpiritWolfie** [comment]
@mujaksaba 
If they resolved it could the rest of us get the patch?

**Comment by mujaksaba** [comment]
@SpiritWolfie 
I do not have a path, support team problem have solved
Regards

**Comment by SpiritWolfie** [comment]
@mujaksaba 
Thanks for getting back with me

Guess I'll wait, I'm having multiple weird issues since updating....

**Comment by poeticjustice** [comment]
I dont have SEAO activity feed, so i will test on my staging site, i use social engine solutions activity wall, so if i dont get this error, it must be a SEAO thing.... but then again @mujaksaba said SE sorted it, do you know what they said or what they did to fix??

Because im guessing you didnt give SE your live site, and instead a staging site, and so you would have to reproduce to your live site

**Comment by Elshara** [comment]
This is why you don't overlap database tables. Third party plugins
just tend to override everything because they're already doing it.
Have you tried clean installs without them to see if it successfully works?

**Comment by Khushboo016** [comment]
Hi all! I've discussed this issue with the development team and this does not seem to be a bug in the new release because the developers have frequently tested this upgrade (upgrade to 4.9) on their systems and have not faced the same. So, this issue is happening only in some cases where because of some reasons (like delay in server response etc.) the upgrade being run is stopped in the middle of the execution and then the queries are run again because of which these two columns `editable` in table 'engine4_activity_actiontypes` and `modified_date` in table `engine4_activity_actions` are duplicated. So, in order to resolve this issue, please drop these two columns from their respective tables. This is what we have done to resolve the issue on @mujaksaba's site. 

The development team will further look into this issue to see what can be reasons that the upgrade is stopped in between the execution, but for now, you can manually drop these two columns from their respective tables in order to get this resolved.

Thanks & Regards!

**Comment by Elshara** [comment]
Good idea. I think when people try to replace existing modules with
other ones, such as advanced blog, photo, video, activity feed, wall,
comments etc, this tends to happen more often because of database
overlapping.

**Comment by DonnaScriptTechs** [comment]
I just upgraded my live demo site on a vps server. No issues found so I cannot reproduce this issue on this hosting environment I use.

**Comment by Elshara** [comment]
I'm glad it's not happening to everyone who upgrades. If creating a
sub instance reveals there to be no problems transitioning from just
core plugins from one version to another on the same server as you are
having the problems with the specified plugins of third parties
already installed, then we have a simple answer.
If this is not the case, then we have to work on that. Starting, I'd
presume, with some server configurations not taking new code well. I
wonder if upgrading to the latest mysql version has something to do
with the error if it's proven third party activity feed code, really
doesn't interfere with this process. As well as multiple server
configurations, coming up with the error.
Since we know not every server is doing so, we have to rule out the
possibility third party plugins are to blame for it happening.

**Comment by SpiritWolfie** [comment]
@Khushboo016 

it fixed it, thank you. perhaps something in a future patch needs to be done about these sort of issues, or ether you need to have the software read from the tables already created or whatever?

**Comment by Elshara** [comment]
:)

**Comment by DonnaScriptTechs** [comment]
We will improve the process but this is caused by third party products from what we've found.

**Comment by MeliMolo** [comment]
So in conclusion, what plugin do we have to disable or what column do we have to delete to be able to perform a good upgrade?
I get this line "Query failed with error: Mysqli statement execute error : Duplicate column name 'editable'"

**Comment by DonnaScriptTechs** [comment]
Best bet is not to upgrade until checking with each developer whose plugins you use, as mentioned in our blog as there are several developers who haven't updated all of their products yet.

If you are already in the process, please see our details above where Khushboo016 posted the columns that you need to remove.

**Comment by DonnaScriptTechs** [comment]
This is improved for 4.9.1 when it is released.

**Comment by Elshara** [comment]
:)
