### ISSUE TITLE
Update Page Seo

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#66]
Currently as it stands, social engine has a very odd seo structure. First of all, you got the site name linked before any page title. Put it last. Second, you not only have a global seo area, but a page seo area as well. This should be in separate metatags and speaking of meta properties, there should be a way to use the html5 advantages of meta properties for the use of google and other search engines to recognize what each page actually is, without having to first use the global description then use the page discription such as this is a members profile, this is a mobile home, to make a post appeal in search results. No social engine sites appear in google, it's a fact you just don't see it. This needs a major update.

**Comment by smazurov** [comment]
SEO is important to us. I believe we're doing a great job, but there is always room for improvement and best practices to follow. If you want more fine grained control over SEO, there are fantastic 3rd party plugins to let you do that. 

We show up in search results just fine.

![screen shot 2015-06-23 at 11 41 10 am](https://cloud.githubusercontent.com/assets/21636/8312917/c664bdc0-199c-11e5-9077-07dcad1ba5cd.png)

**Comment by Elshara** [comment]
Thanks for the update. I'll check it out. I'm simply saying what they
can do, you can to if there was enough demand for it via the product
support.

**Comment by smazurov** [comment]
consolidated under #149
