### ISSUE TITLE
Token not matched error

### ISSUE THREAD

**Issue by SpiritWolfie** [SocialEngine/phpv4-issues#662]
4.9 

Token Errors, I've gotten this more then usual with 4.9, happen with installing some of the updated files like groups etc

(inside admin panel and accepting friends still puts out a token error)

**Comment by DonnaScriptTechs** [comment]
As you have several open issues here, would you please make sure to include these in your ticket?

**Comment by SpiritWolfie** [comment]
@DonnaScriptTechs this issue isn't related to the chat bubbles etc, You've told me to not include multiple bugs in one report multiple times, so I have honored this request.

**Comment by DonnaScriptTechs** [comment]
Yes I mean in the ticket in support. :) Please include any issues in your support ticket too.

**Comment by Elshara** [comment]
:)

**Comment by DonnaScriptTechs** [comment]
https://github.com/SocialEngine/phpv4-issues/issues/602 duplicate
