### ISSUE TITLE
Loop Error

### ISSUE THREAD

**Issue by SpiritWolfie** [SocialEngine/phpv4-issues#664]
4.9 New theme

![image](https://cloud.githubusercontent.com/assets/9712738/25012551/ae314a16-2025-11e7-9173-4d7d91676bd2.png)

Loop error is still here from core.js

**Comment by Elshara** [comment]
Probably because it never was updated to the latest version.

**Comment by SpiritWolfie** [comment]
@Elshara if your talking about me updating to 4.9 I did, I made sure almost every file was 4.9 and same with Zend.

**Comment by Elshara** [comment]
No I'm talking about social engine updating core js files like
mootools and chootools.

**Comment by DonnaScriptTechs** [comment]
After discussing with our core developers, this is not a bug. It is an activity loop to get the activity streams in order to display new content.

**Comment by Elshara** [comment]
okay
