### ISSUE TITLE
Themes issues

### ISSUE THREAD

**Issue by SpiritWolfie** [SocialEngine/phpv4-issues#667]
4.9

Multiple themes have issues, the ones supposedly updated to 4.9 is smooshed together on mobile, The advertised theme for 4.9 Insigini is cluttered on mobile and looks and runs poorly on mobile devices

Midnight and such 4.9 update is impossible to use on mobiles

and the Constraint for the new theme wont update the css if you make changes to it of any kind, you have to 'over-ride- the css to not use constraint to make any changes on insignia.

**Comment by DonnaScriptTechs** [comment]
Are you having issues on our https://demo.socialengine.com with mobile? I tested on iPhone 5c and didn't have any issues. What device is causing issues on our demo if you tested there? If not, please test there and let us know if you see the same issues. Thanks.

**Comment by DonnaScriptTechs** [comment]
One note, our original themes are not responsive. We did not make them responsive so please don't check to see if those are responsive.

>Multiple themes have issues, the ones supposedly updated to 4.9 is smooshed together on mobile, The advertised theme for 4.9 Insigini is cluttered on mobile and looks and runs poorly on mobile devices

Is this in the "full site mode"? Once you check on our demo, please also let us know if you are checking in full site mode or not. Thanks.

**Comment by Elshara** [comment]
I can tell you right now mobile plugin isn't responsive. it won't
support responsive themes, so that's why you're seeing the issue.

**Comment by SpiritWolfie** [comment]
I'd also like to point that if we make any changes to the insiginia themes constraints css nothing happens.

**Comment by DonnaScriptTechs** [comment]
@SpiritWolfie thanks for reminding us of that. I have custom stuff I do to my demo so I'll test as well.

**Comment by poeticjustice** [comment]
@SpiritWolfie if you want to make sure your css is always delivered, add in !important

example color: red !important;

I usually alway use custom css part and make all changes there and apply !important; to all

**Comment by DonnaScriptTechs** [comment]
I tested on my demo and was able to change and save the constant.css. I'm not sure what's up on your site atm.

**Comment by Elshara** [comment]
Hmm
Good CSS would never enforce  a requirement for the important tag.
I had to use it on another platform because it was used first in
custom CSS. It was a nightmare. I'm glad we have full CSS access in
social engine. I only wish we had full template access for tpl files.

**Comment by Elshara** [comment]
ok

**Comment by DonnaScriptTechs** [comment]
This issue resolved once the client made a clone of the Insignia theme and worked on that. We recommend clients work only on a clone of a theme and keep the main one unedited. It's best for troubleshooting as well. 

Just posting so others following this thread or having the same issue can see what resolved it.

Thank you.

**Comment by Elshara** [comment]
Awesome!
