### ISSUE TITLE
Audio Playback Issue - Imported Network From Ning 2.0

### ISSUE THREAD

**Issue by troydbertrand** [SocialEngine/phpv4-issues#668]
This SocialEngine installation is running on v4.8.13. A do over of the import on 4.9 is not an option. Not sure if upgrading to 4.9 will solve the issue - I doubt but want to see if this can be addressed before updating. 

What are the steps to reproduce this issue? (Not practical in this case but here goes...)
-------------------------------------------
1. Import a Ning 2.0 Network containing audio files.
2. Try playing back an imported audio file.

What happens?
Nothing really...
The "Play" button will engage (toggles to "Pause" button) but there is no actual playback. 
…

What were you expecting to happen?
----------------------------------
Expecting audio playback.

Any logs, error output, etc?
----------------------------
Output from Chrome Console - See attached screenshot. This happens with all the major browsers and on Windows and Mac.
![2017-02-17_0859](https://cloud.githubusercontent.com/assets/13011003/25049855/e1cc5414-2111-11e7-8e76-231c05634c3a.png)

Hope this will be a easy fix for this (like editing a JavaScript file)
Thanks

**Comment by Elshara** [comment]
Are the files in the import physical or embedded? Embedded files of
all media types, photos, music, videos, don't work right when
importing from Ning. I've noticed.

**Comment by DonnaScriptTechs** [comment]
Hi @troydbertrand could you please send a ticket to our support and reference this bug report for 4.8.13 Ning importer? We can check to ensure there is not an issue with our importer routine with music. Please note that with today's holiday, responses will be delayed.

**Comment by troydbertrand** [comment]
Thanks for the speedy response Donna. Apologies for the delay response. I'll advise the site owner on how to proceed with this.

@Elshara : These are uploaded audio files.

TDB

**Comment by Elshara** [comment]
Interesting. IF they are actual files uploaded to the music directory,
there shouldn't be an issue playing them. I could see if the actual
embed source wasn't found, but the files themselves. Could be a sound
on mute issue as well. IF they are playing in real time, perhaps there
is a problem with all sounds. Maybe try uploading new sounds to an
existing album to check.

**Comment by Elshara** [comment]
:)
