### ISSUE TITLE
Update Share Feature

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#67]
In social engine, the share feature is nothing more than quite literally, a repost of an existing one. What's worse, it is a repost on someone's wall. Replace that with a repost button allowing people to choose what type of post they'd like to either tag it in or find a way to recommend or suggest it to others. Better still would be the ability to invite people not just on your friends list if you are an admin, to participate within a post included with a post recommendation. That is how content gets shared. There should be a way for admins to have their own outside share buttons so that it is easier to post stuff on facebook, twitter and other places or perhaps write their own code as a share feature itself.

**Comment by shivani2910** [comment]
@Elshara you can enable sharing on facebook and twitter on your website by enabling Facebook and Twitter integrations on your website. More details can be checked here:
http://support.socialengine.com/php/customer/portal/articles/1796979-admin-panel---settings-&amp;gt;-facebook-integration
http://support.socialengine.com/php/customer/portal/articles/1642499-admin-panel---settings-&amp;gt;-twitter-integration

**Comment by Elshara** [comment]
Did that already. They both work for sign up and sign in. The like
buttons and share buttons aren't there.
