### ISSUE TITLE
Quick Add Widget

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#671]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Quick add widget would allow people to be able to add any installed module type the member level has access to from one place.
2. … Everything from statuses to third party modules would be covered.
3. … IT currently doesn't exist yet.

What happens?
-------------
… When people add content, they have to spend time looking where to click to be able to do so. Not everyone realize the browse page in one tiny menu item, is the only place to do so. But you have to be careful, because you need to know what module you are currently looking at to be able to do so, prior to figuring out how to let your post fit in with the content adjacent to it. Relatively speaking, for sites with specific focuses or complex navigation, this is almost impossible to do. With no ability to add sub tabs for navigation, people are left struggling to figure out where to go, to contribute the way they want to. Wishing, and needing, especially in terms of functionality, are two separate things. But having, provides the ability to meet them in one easy to remember, place of admin customizable navigation, as an option to visitors and returning members, who wish to post on the site.

What were you expecting to happen?
----------------------------------
… Quick add widget to take care of the problem. Giving people a sense of familiarity as they associate navigation, with site wide or specific page access which stands out on its own. Just like search and settings do.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Menus won't exactly work for this, simply because there's no way to collapse or expand the items listed.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by gsf00001** [comment]
Do you mean the ability to add whatever conent a User wants from (almost) anywhere, rather than going to the Albums page for Photos, or Video page for Videos, etc?

**Comment by Elshara** [comment]
Yes I do.

**Comment by gsf00001** [comment]
Hmmm.  It seems I may already be doing this for some content using an SES Plugin.  Content adds/creation that uses java instead of a URL as well as content that requires a parent such as Group I don't do.

**Comment by Elshara** [comment]
Good to know. Seems easy to implement. I could just put all the quick
menus on one page or all pages if I wished, but it wouldn't show to
who I wanted it to.

**Comment by gsf00001** [comment]
I have an icon in my header for 'my stuff' to quickly let a User access their own content (about 15-20 menu items), instead of going to Photos just to view their Photos.  Not a huge benefit, but a little convenience to hopefully keep Users happy.

**Comment by Elshara** [comment]
Yeah if only we had menu default access permissions. Then I'd not have
to request this. But a quick add menu for people signed in, would do
wonders.

**Comment by gsf00001** [comment]
I will soon add this using the existing SES Plugin I have.  I never thought of using a menu for creating/'quick-adds' of content, only viewing 'my stuff'.  Great idea for SE to work on.

**Comment by DonnaScriptTechs** [comment]
There is a free plugin named Uplinks that allows you to add content from wherever on the site and contains all of the default core plugin add options. https://www.socialengine.com/marketplace/app/uplinks and above there was mentioned another plugin for this feature. Since there are free and paid options, we feel this is covered.
