### ISSUE TITLE
Quick Manage Widget

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#672]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Managing posts is a bit tricky, but not impossible to do. Provided you have all the menus on the specific pages which corresponds to their related modules.
2. … Managing items, means being able to fully customize posts in terms of editing, deleting and listing functionality along with their responses, either in terms of viewing, sharing, commenting, liking or other such actions.
3. … This feature doesn't exist yet.

What happens?
-------------
… Navigation for some sites, may not be as easy as others. Most people won't think to place the browse widget for menu items, on to the page members need to be able to manage their posts. Additionally, creating menu items to be able to do so, just takes up a lot of room, with no ability to collapse or expand items. For this reason, we need a widget which allows the ability for all posts, belonging to core, default modules and third party modules, to have item listings here.

What were you expecting to happen?
----------------------------------
… The manage content widget to be something tied in with the functionality of adding and viewing posts from a kind of user control panel.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Singular type interfaces integrated with items you have access to control are easy for members to get the hang of.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#95

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
