### ISSUE TITLE
Shopping Cart Widget

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#673]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … It looks real good for ecommerce type websites where in the business of making money is more than just a commodity.
2. … It allows people to directly purchase something and receive money for selling something in return.
3. … Admin or member to member based money earning schemes helps people grow businesses in a social way whose mannerisms are similar to custom interests.

What happens?
-------------
… This functionality isn't available yet. But it would be easy enough to create either on a per module basis, or per item basis depending on the actions member levels have to work with.

What were you expecting to happen?
----------------------------------
… Such to work well so people can feel good about being a member on a site which is offering paid services.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Paid access is nothing new, and is kind of a requirement in the professional dating world.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#96

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
