### ISSUE TITLE
Integration Of Broadcast Message Functionality With Other Modules

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#674]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Sharing a message with all members, allows notices to be sent in a mutual dialog. As opposed to a one way communication for admins.
2. … Such communication allows members to comment on recent news, if shared with them through such a means of conversation.
3. … In order to do so, existing modules need to be configured to send broadcast messages.

What happens?
-------------
… This feature is not available yet, however if it were, members and or admins could choose who to send messages to from the front end, instead of needing to access the back end for simple moderation or broadcasting functionality.

What were you expecting to happen?
----------------------------------
… All core, default and third party modules have the ability to share messages with friends, all members or custom filters.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Having widgets available to view recent broadcasts and comment on them would also be nice, and could be tied in with announcements with added comments functionality.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by poeticjustice** [comment]
What Broadcast Message Functionality?

**Comment by Elshara** [comment]
Where you go under members, click on email all members. That broadcast
message functionality.

**Comment by Elshara** [comment]
The newsletter which currently has no archive support.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#97

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
