### ISSUE TITLE
Create Posts Calendar

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#675]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Browse posts you have created or posts available site wide for any particular module. Could even be members.
2. … Notice the flat, list view for everything?
3. … If alternative viewing types were available, a calendar view would be great so people could visually see when activity has appeared for each post along with a few post statistics. Such as found in table views.

What happens?
-------------
… Calendars provide people with the ability to visually see important aspects of how posts or other items are created, and how they are visually appealing to do so.

What were you expecting to happen?
----------------------------------
… Such views, among others to be possible when viewing or browsing posts.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… IF people see calendars, they love to make them populated.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#98

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
