### ISSUE TITLE
Mobile Profile Options Widget Not Working (4.9)

### ISSUE THREAD

**Issue by nizhnyk** [SocialEngine/phpv4-issues#678]
What are the steps to reproduce this issue?
-------------------------------------------
1. Upgrade to 4.9.
2. Switch to mobile.
3. View friends profile or any profile as admin.

What happens?
-------------
Profile options menu is not displayed.

What were you expecting to happen?
----------------------------------
Expecting to see the Profile Options menu (Send Message, Remove from friends etc.)

Any logs, error output, etc?
----------------------------

`Zend_Controller_Router_Exception: Route messages_general icon_message is not defined in /var/www/website/public_html/application/libraries/Zend/Controller/Router/Rewrite.php:325`
`.....`
`#10 /var/www/website/public_html/application/modules/Mobi/widgets/mobi-profile-options/index.tpl(25): Zend_View_Helper_Navigation_Menu->render()`

Steps to fix
-------------------

In "application/modules/Mobi/Plugin/Menus.php", find (line 495):
```php
      'route' => 'messages_general icon_message',
```

Replace with:
```php
      'class' => 'icon_message',
      'route' => 'messages_general',
```

Find (line 562):
```php
        'route' => 'admin_default icon_edit',
```

Replace with:
```php
        'class' => 'icon_edit',
        'route' => 'admin_default',
```

Fix double class parameters
-------------------

Remove the following from lines 310, 327, 340, 380 (you will notice there is existing correct class parameter above):
```php
          'class' => 'smoothbox',
```

**Comment by Elshara** [comment]
That's kind of a serious bug.

**Comment by Khushboo016** [comment]
Hi @nizhnyk, Thanks for reporting the issue, I've added this to our internal bug tracker, so, it can be fixed soon.

Thanks & Regards!

**Comment by Elshara** [comment]
:)

**Comment by poeticjustice** [comment]
Is this Mobile Profile Options Widget a new feature and works on responsive, or for the mobile plugin from SE?

**Comment by Elshara** [comment]
No idea. I don't use the plugin because it's totally underdeveloped.

**Comment by nizhnyk** [comment]
Mobile plugin works great on my website. I wouldn't say it's underdeveloped but maybe has outdated design, it's a good starting point for those who're willing to redesign it. For people with responsive design it's kind of useless but in my case I have the main website static width designed for desktop and responsive mobile version using Mobile plugin designed for cell phones/tablets and optimized for touch. Because of the style I'm going for it will be very hard to almost impossible to maintain a single responsive design. You can check it out here https://yyc.city

**Comment by Elshara** [comment]
I like what you did there. :) That's kind of been my theory as well
with regards to mobile plugin versus responsive design. I suspect
mobile plugin overrides some css properties for some unknown reason,
but I figure it should be changed so it doesn't do it anymore. Also
the separate menu items for mobile, doesn't sit right with me. They
should be unified at some point. Hopefully soon it will happen.

**Comment by Elshara** [comment]
By the way, I'm Canadian as well. I live in Vancouver. I thought about
moving to Calgary however.

**Comment by Elshara** [comment]
I really love the way you designed the website. Some of the widgets
and menus look a bit different from the default, such as the double
menu items. It's really neat you did a wonderful job with it. :)

**Comment by DonnaScriptTechs** [comment]
This is fixed for 4.9.1 when it is released. If you still have this issue after we release, please open a new bug report.

**Comment by Elshara** [comment]
:)

**Comment by MMAMELEE** [comment]
Someone please help me I ran into an issue. I didnt know I had to install the 4.9.1 zip file first and i did the blog tar and it gave me this error. Now I tried to upload the old 4.8.13 blog it says it is already there and just shows me an error. I'm scared to continue and i dont have a backuup of my site as it would take hours and hours
![unnamed 1](https://cloud.githubusercontent.com/assets/12929729/25558539/f394a61a-2cf6-11e7-9dcb-5323c551e0d9.jpg)

**Comment by DonnaScriptTechs** [comment]
@MMAMELEE please contact our support from your client account as this thread is not for that topic. If you don't have support, you'll need to purchase it. Alternately, you can post at our community for assistance.

**Comment by MMAMELEE** [comment]
Thank you...do you think you can help me out. It's saying Warning: Your database structure for this package is out of date. The version you currently have is 4.8.13. Please complete the installation of this package to resolve this problem. when i try to update to 4.9.1 thanks 

    On Saturday, April 29, 2017 5:11 PM, DonnaB <notifications@github.com> wrote:
 

 @MMAMELEE please contact our support from your client account as this thread is not for that topic. If you don't have support, you'll need to purchase it. Alternately, you can post at our community for assistance.—

**Comment by Elshara** [comment]
Unzip the .tar files using a program like 7zip. Then just extract the
contents of the actual directory to your main folder where social
engine is. Be sure to to do so for the core if you wish to upgrade in
full, or keep 4.8.13 files and do the same. Essentially treat the .tar
file like the .zip one and just override it from base directory.
