### ISSUE TITLE
Action Item Layout Needs Updating

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#68]
When ever you are about to change something in social engine, for example, when on a settings page with lots of different settings on one page, smaller settings don't actually appear as its own item. Social engine is the only script not to have a separator present when doing a separate action, for example, on the general settings page in the admin panel, or even on the broadcast message page under members, each field doesn't have a separator indicating another field is present. This is especially true for comments and the activity feed. This should be addressed or outlined more clearly or at least have the option to include one.

**Comment by shivani2910** [comment]
@Elshara We already have a plan to improve Activity Feed Settings section of admin panel in coming time. This will be addressed then. Thanks

**Comment by smazurov** [comment]
reopening so people can see whats tracked for 4.9.0 milestone.

**Comment by Elshara** [comment]
:)
