### ISSUE TITLE
Feature enhancement: Advanced Share Plugin

### ISSUE THREAD

**Issue by ritika-saini-bs** [SocialEngine/phpv4-issues#680]
1) A notification is sent out when an item is shared. We need to work on sending emails also for this action.

2) For a 'Share Type' under it's settings >> Notifications >> Create a new option 'None'.

Support Ticket: https://www.socialengineaddons.com/support/viewthread/42836

Point 5 B & 5 C in the support ticket.

**Comment by Elshara** [comment]
lol
