### ISSUE TITLE
Feature Request - Make Iframely Optional

### ISSUE THREAD

**Issue by nizhnyk** [SocialEngine/phpv4-issues#682]
I hope someone can support me on this. I was under impression that Iframely integration will be optional and I would be able to turn it off, even your [documentation](https://support.socialengine.com/php/customer/en/portal/articles/2766234-admin-panel---settings-&gt;-iframely?b_id=14386) shows that it could be turned off. Then I found that Video app is also using Iframely, without any option to disable it.

I'm not a fan of Iframely, please don't force it.
I don't want to rely on someones service, I also don't want to host it on my server and have another peace of software to manage.
I like news feed clean, Iframely makes it very cluttered.
I'm perfectly fine with open graph and ability to display content the way I like.

**Comment by Elshara** [comment]
Can't you just turn off video embedding?

**Comment by DonnaScriptTechs** [comment]
My bad. I didn't realize the image wasn't updated when we published the document and I had made it well before release. Sorry for the confusion.

Regarding this improvement, I've added it to our list for our team to discuss. Thank you for your suggestion.

**Comment by gsf00001** [comment]
Optional.  Yes, optional.  Most things should be up to ADMIN.  There.  I said my peace :)

**Comment by Elshara** [comment]
Awesome!

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#99

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
