### ISSUE TITLE
Sentry Integration An Unofficial Feature

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#683]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Go to demo site. https://demo.socialengine.com/admin then go to settings, sentry integration.
2. … Install a fresh copy of social engine 4.9.
3. … Go to your fresh copy settings page, and look for sentry integration.

What happens?
-------------
… You won't see it anywhere.

What were you expecting to happen?
----------------------------------
… For it to show itself. On the demo page, there is no knowledge base article about it. Furthermore, the demo page shows as listing 13 plugins. I presume this is one of them, and the other, is some form of translation widget. Whose settings don't appear anywhere in the admin settings area of the demo at all, found in the footer. To which does not appear in fresh copies of 4.9. Based on trial installation packages.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Other than that, everything appears to be default configuration.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … Live 4.8.13 until bugs are sorted in latest 4.9.

**Comment by DonnaScriptTechs** [comment]
This is not a bug as it's not something we include in our default script. We have it on the demo for our own needs. We did, however, make it available free for anyone to use as well, https://github.com/SocialEngine/phpv4-sentry

**Comment by DonnaScriptTechs** [comment]
https://github.com/SocialEngine/phpv4-sentry/releases this is where you can get it but it has no documents as we've not released it yet.

**Comment by Elshara** [comment]
Ah I understand. This just looks way cool!

**Comment by Elshara** [comment]
I knew I seen it before I just couldn't remember where.
