### ISSUE TITLE
Spelling Error On Create New Poll Page

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#684]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Go to create new poll page.
2. … in the title field, it shows the error. It's missing an o.
3. … There is a usable work around, but it involves a core edit.

What happens?
-------------
… No error exactly, it just sits there, representing the page.

What were you expecting to happen?
----------------------------------
… Not to see it.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Simple enough to fix using the edit page menu in layout editor, but why bother?

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by DonnaScriptTechs** [comment]
Thank you for your report. We've added it to our list to fix.

**Comment by DonnaScriptTechs** [comment]
This is fixed for 4.9.1 when it is released. If you still have this issue after we release, please open a new bug report.

**Comment by Elshara** [comment]
:)
