### ISSUE TITLE
Git Hub Format

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#685]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Post an issue here.
2. … This form appears.
3. … But it doesn't cover all the information we really need to fix stuff.

What happens?
-------------
… I have a feeling it was created because you need a guideline to follow for basic question and answer type stuff, but this isn't really a support forum for you. It's a place to post actual problems for both you and us, the clients slash customers.

What were you expecting to happen?
----------------------------------
… To be shown  different templates which is something you can pick from for easier access relating to the type of issue you are seeing. Code bug, versus minor error, versus feature request, versus something else. If you aren't going to use separate forums for such, then we need different templates to add or edit as needed. I know we can do that here, but it's a pain because I can't write git hub style mark down like I can html and it never formats like I want it to if I started now.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Feel free to close this, but just keep in mind what I said. I don't mind if you ignore it, but it's just easier on the rest of us to feel like we have a place to go for dedicated discussions about specific issues. It will or should also help with off topic comments. We are a community, working as a team here, and since we all have something in common, we should respect the diversity of what we come here for, but do so in  focused ways, so we all can sleep at night, worst case scenario. Best case scenario, we are happy with what we all contribute to develop together, which is the goal of the git hub here. It's either that, or make the social engine official community open to the public. This is how I feel.

What versions of software are you using?
----------------------------------------
**Operating System:** … TLDR

**SocialEngine PHP Version:** … TLDR

**Comment by DonnaScriptTechs** [comment]
We have improvements coming. Thank you for your suggestions.
