### ISSUE TITLE
Provide Better Map Integration

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#687]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Upload any type of post which has map integration. location fields on profiles and classifieds have this by default. Events and groups do as well.
2. … Notice, maps display fine.
3. … No other module has integration with maps including activity feed.

What happens?
-------------
… Aside from location based posts, maps love to be used by people who care about their location. Most often, such posts are posted in the form of status updates, such as when shared as check in through Facebook and other such services using the Facebook open graph api system. Socially locations allow you to do more than establish meeting places, they allow you to see other users who have similar physical whereabouts to you in such locations and as such, member maps are used to be able to do so effectively. As social engine does not offer such a feature by default, the location based feature in user profiles, is the next best thing. However, you have no control over multiple users per map setting, as you have no way of viewing separate locations in one place. Therefore, location based integration is great for other modules, so you can attach  location (s) to a post which currently does not have locations assigned. For photos and videos, you should be able to specify multiple locations, to show where you filmed or took pictures of something somewhere. The forums and blogs modules, would have excellent reputations for locations, because you could attach a location to a blog which talks about somewhere specific. Chat as well, could have this enabled. It could also be a part of the tinymce editor, so you could either attach a link or a location as such, to a map of where you are in the world regardless. As such, locations for polls would also come in handy, as you could specify where people would prefer to meet, if you wanted to actually meet somewhere. Therefore, integration with all modules for location based results, would be ideal. The only thing which is preventing social engine from having such enabled right now, is the lack of the location based profile field. Just like some modules such as photos, videos, music, events and groups, don't have the ability to tag any of such, as they have the location field for some modules as a replacement. Polls as well would do nice for tagging as well.

What were you expecting to happen?
----------------------------------
… locations and tags to be possible for all modules. Believe it or not, tags and locations kind of go hand in hand. They are to be searchable as such. They should provide members with an objective outlook of what is already subjectively happening.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Locations are useful because they make you physically meet the person on the other side of the internet.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#101

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
