### ISSUE TITLE
Meta Tags Still Show In Reverse Order

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#689]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Compare versions 4.8.13 with 4.9.0.
2. … Notice how the title and description tags show site wide content first, in 4.9.13, and site wide content last, in 4.9.0?
3. … The keywords section does not follow this rule. In 4.9.0, site wide keywords show up first, not last. Same as 4.8.13.

What happens?
-------------
… Page specific keywords are crucial to show up first, because they are what search engines first see as well as people. They don't currently.

What were you expecting to happen?
----------------------------------
… To have keywords follow the standard practice of showing page specific first, and have the option to optionally show site wide title, description and keywords for all pages.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… SEO generally works well if you apply a bit of effort to the order of things.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13

**Comment by Khushboo016** [comment]
Hi @Elshara, Thanks for bringing this up! We've added this issue to our internal bug tracker and this will be fixed in future.

Thanks & Regards!

**Comment by Elshara** [comment]
you're welcome!

**Comment by Elshara** [comment]
:)
