### ISSUE TITLE
HTML Post Problem

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#69]
When it comes to html in posts, it shows up as code, not as what the code is designed to do. We live in a modern era now where html is not only accepted, but in some cases, prefered as opposed to just text. This could be as simple as embedding images or videos in posts. We need the ability to disable the feature of not allowing html in any post, but rather, we need the ability to choose what html tags we do not want and have them present by default so that html in comments, forums, blogs and other items is always visible including tags like tables, embed, images and other items. HTML should by default also include proper mark up such as the alt tag for images, full support for any quick in content css adjustment and other complex items such as tables and other in content columns, very useful for people who enjoy styling their posts.

**Comment by Anshuse** [comment]
Hi @Elshara , Currently. we don't have any such plan to implement this in our core module but we'll forward your suggestion to our team and they will take appropriate action on this. Thanks!

**Comment by Elshara** [comment]
Awesome. That would be cool.
