### ISSUE TITLE
Missing Translation Of Some Names For Activity Type Settings Page

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#690]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … In social engine 4.9.0, activity improvements were made. But not all of which, has had their final touches added.
2. … Missing language strings exist in some areas.
3. … All effected areas are listed below.

What happens?
-------------
… In the following order from first to last, here are the field types missing. ADMIN_ACTIVITY_TYPE_COMMENT_EVENT. ADMIN_ACTIVITY_TYPE_COMMENT_GROUP. ADMIN_ACTIVITY_TYPE_COMMENT_USER. 

What were you expecting to happen?
----------------------------------
… For the text to be replaced with when a user subject comments on object name.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… That's all I've noticed for this issue.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13 live

**Comment by DonnaScriptTechs** [comment]
We've added this to our list. Thank you.

**Comment by Elshara** [comment]
:)

**Comment by DonnaScriptTechs** [comment]
This is fixed for our 4.9.3 version when it is released.
