### ISSUE TITLE
Problems With Menu Items For Insignia Theme

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#691]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Half of them aren't visible. Such as the admin link in mini menu.
2. … The ones which are, sort themselves in odd positions on the page. Such as browse menu items, horizontally instead of vertically.
3. … Effects version 4.9.0 of social engine.

What happens?
-------------
… Some CSS could be blocking menus from displaying properly.

What were you expecting to happen?
----------------------------------
… Menus to function the same as in other themes. The default theme seems to do the same thing.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Visibility is important and should not be hidden for navigation reasons.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13 live

**Comment by DonnaScriptTechs** [comment]
Please provide screenshots of visual issues. Please also let us know if this is for vertical or horizontal menus. Perhaps check with browser cache fully cleared to rule out old css mixing with new css.

This is how it looks for me:
Horizontal
<img width="1105" alt="menu1" src="https://cloud.githubusercontent.com/assets/6908282/25239598/6cad916e-25be-11e7-9c3c-b194116c3aad.png">

Vertical
<img width="977" alt="menu2" src="https://cloud.githubusercontent.com/assets/6908282/25239670/a0af94c6-25be-11e7-94d8-e200d58aac57.png">

**Comment by Elshara** [comment]
The text for the items actually disappears.
For instance.
When clicking on notifications. In the old theme, you could just click
on any part of it and it would open up.
But with the new theme, you can't do that. The links themselves
disappear to be replaced with icons.
You can't click on the text part of an icon, say for instance, if you
had 2 new updates. You couldn't click on the text part where it shows
2, you could only click on the icon.
Whereas with any other theme, you could do so.
If no icon is available for a menu item, it just refuses to display at all.

**Comment by DonnaScriptTechs** [comment]
This is how insignia is designed as far as notification icons.

Again, are you using horizontal or vertical menu? I need to know. Vertical menus require icons.

**Comment by Elshara** [comment]
Horizontal. I never changed it from the default. Makes no difference.

**Comment by DonnaScriptTechs** [comment]
Ok the horizontal doesn't have icons for the main menus so that would only show text.

**Comment by Elshara** [comment]
Yes. The icon issue is happening through the mini menu only.

**Comment by DonnaScriptTechs** [comment]
We've found that CSS issues have been from third party products being on the server, whether enabled or not. We did put a patch that has fixed things for all others. I'll go get the issue it's in so you can try it.

**Comment by DonnaScriptTechs** [comment]
https://github.com/SocialEngine/phpv4-issues/issues/688 try that or please try a fresh install on a development site or local install.

**Comment by Elshara** [comment]
Thanks I'll install it.

**Comment by DonnaScriptTechs** [comment]
Is this still an issue?

**Comment by Elshara** [comment]
Not for me. I just use a different theme and get rid of the icons. But
with the icons enabled, yes.

**Comment by DonnaScriptTechs** [comment]
Does this happen for you at our demo? I'm not able to reproduce it on my local, the SE demo, my live demo.

**Comment by DonnaScriptTechs** [comment]
<img width="627" alt="iconsdefault" src="https://cloud.githubusercontent.com/assets/6908282/25943751/efae003e-360e-11e7-8db0-4d04fc2cb423.png">
The above is default theme and I think I see what you mean for insignia. The above has text for the various mini menu items. I can't see a way to disable the font-awesome icons to show just text in insignia.

I'll go play with the code but we do need to improve this so that clients can show text instead of icons.

**Comment by DonnaScriptTechs** [comment]
Marked a bug as people with screen readers can't use it.

**Comment by DonnaScriptTechs** [comment]
This is fixed for our 4.9.3 version once we release it.
