### ISSUE TITLE
Extra Space At The End Of Mini Widgets

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#693]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Install mini search and mini menu at the header.
2. … After the list ends in the mini menu, space is visible.
3. … Same happens for the mini search widget.

What happens?
-------------
… It seems silly to report this, but usually, space isn't detected at the end of widgets.

What were you expecting to happen?
----------------------------------
… Not to see it. It doesn't bother me, but it's there and yeah, visible.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Extra space is fine for development, a lot of developers over use the tab key when coding. But they forget to edit it out at the bottom of some files. I presume this is the case with the widget .tpl files of the mini variety here.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13 live

**Comment by DonnaScriptTechs** [comment]
Please test with 4.9 and if this still happens, please provide a screenshot if possible.

**Comment by Elshara** [comment]
I will thanks.
