### ISSUE TITLE
Phrase Improvement To Fix Spelling Error In Performance Caching Overview Page

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#694]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Go to performance caching page.
2. … Find this text. noticable
3. … Replace with noticeable

What happens?
-------------
… An e is missing at the end of the word notice.

What were you expecting to happen?
----------------------------------
… I know it may seem like I'm a critic, but I just noticed it was something new. Effects version 4.9.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… You're awesome.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.8.13 live

**Comment by DonnaScriptTechs** [comment]
Thank you! We've added this to the list to fix.

**Comment by Elshara** [comment]
:)

**Comment by DonnaScriptTechs** [comment]
This is fixed for 4.9.2 when it is released. If you still have this issue after we release, please open a new bug report.
