### ISSUE TITLE
Core Package Updates

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#696]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Go to socialengine.com/account/dashboard and click on available .tar files.
2. … Notice the Zend package and the upgrade package for 4.9.0 file sizes.
3. … There's something wrong here. The newly created phpfox import script is not included in default core package if you wanted to do a fresh import, officially supported by social engine. The Zend package should be within the core upgrade package. The core upgrade package times out and an error appears, bad extraction.

What happens?
-------------
… The core upgrade package extracts part way through and then won't finish it. You have to unzip the default social engine installation package and override all files. This results in a part of the files uploaded,,, resulting in an error as manual uploads cause some files to have newer versions than older ones. It can't be helped, because the .tar installation for the same, does not work as it should. Additionally, the import script is not seen in any of the packages for zend, core upgrade or default installation.

What were you expecting to happen?
----------------------------------
… Such to be made simpler.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Other than that, no issue.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.9.0

**Comment by DonnaScriptTechs** [comment]
We don't include the phpfox importer. That is something that has to be requested on a separate form.

**Comment by DonnaScriptTechs** [comment]
I'm not having any issues extracting the files and I download from my client account.. The zend is included in the core upgrade package. We also included it separately as it's always been there in the past and clients would have wondered where it went.

**Comment by DonnaScriptTechs** [comment]
Are you doing this on local? I've upgraded several locals and a live and not had any issues with them extracting. Please download the files again in case there was a glitch on your download.

**Comment by Elshara** [comment]
Live upgrade actually but I'm not worried. I solved the issue and it's
not a problem.
Regarding import script, it just seems odd you'd have to have it
separate and it not be available in the download files section as the
other import scripts, from social engine 3 and Ning are already in the
core package.

**Comment by DonnaScriptTechs** [comment]
The fox import was a special case. Since two of the key fox people work for SE now, we wanted a personal greeting from us for those coming.

**Comment by Elshara** [comment]
Oh. I thought it was an extended one so anyone who bought it coming
from there could just import their existing community.
