### ISSUE TITLE
Error Displaying Attachments

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#697]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Post something via activity feed.
2. … Reload page.
3. … You get this error. en4.core.runonce.add(function () { en4.activity.bindEditFeed(16209, { lang: { 'Post Something...': 'Post Something...' }, allowEmptyWithoutAttachment: 1 }); });

What happens?
-------------
… You can't view the attachment.

What were you expecting to happen?
----------------------------------
… To be able to view it.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Activity feed was working fine in previous version.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.9.0

**Comment by DonnaScriptTechs** [comment]
Do you see this on our live demo? We ask in order to have more troubleshooting information as we cannot reproduce this issue.

What "something" are you trying to attach? Image, video, link, ?

Is this a fresh install or upgrade? If an upgrade, did you disable all third party plugins?

Did you enable development mode to see for any other errors?

**Comment by Elshara** [comment]
Status feed attachments when uploading from there. Also other forum
attachment areas if adding custom photos, they seem to do that. The
demo works as it should as far as I'm aware, and no I didn't test it
there. It actually concerned the display of attachments, not showing
up right since the upgrade but if it's not something that's replicated
I'm just going to have to accept I've a corrupted upgrade or install
of something. As it worked fine when displaying them prior to doing
so.

**Comment by DonnaScriptTechs** [comment]
Try 4.9.1 and see if it works better. If not, we can reopen this bug report.

**Comment by Elshara** [comment]
Seems to be working fine now.
