### ISSUE TITLE
Profile Pages Won't Save Changes

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#698]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Go to layout editor in admin control panel.
2. … Go to profile pages. Member, group, event, mobile profile, mobile group, mobile event and any other third party profile pages you see.
3. … Try to click on save changes, not even editing widgets placed there.

What happens?
-------------
… Nothing. The dialog doesn't appear, and the changes never get saved even if you remove all the columns and widgets. Nothing happens if you edit the page name either, it just doesn't do it.

What were you expecting to happen?
----------------------------------
… To be able to save profile pages.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… All other pages seem to save fine. This effects only version 4.9.0 of social engine.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.9.0

**Comment by DonnaScriptTechs** [comment]
I cannot reproduce this. I tested a few of the pages. Are you sure it's all of those you listed? I tried member profile and group profile.
<img width="1016" alt="group" src="https://cloud.githubusercontent.com/assets/6908282/25241449/08172bb0-25c4-11e7-9675-af5547de25f6.png">

**Comment by DonnaScriptTechs** [comment]
Please enable development mode and check for errors.

**Comment by Elshara** [comment]
Yes. I'm sure it's only those 3 pages. Was testing with slip stream theme.
I can confirm it happens with all themes, and it only effects those 3 pages.
Development mode yields same results.
All other pages save fine. This didn't happen prior to upgrading. I've
cleared cache and dns settings as well. I am able to change things
like column numbers and their positions, edit page details and such,
but just not save layout information on those 3 pages. It simply won't
save.
Event profile. Groups profile. Member profile. Those 3 pages are for
me at least, causing the issue.
On the demo.socialengine.com/admin page, the same issue happens. But
for all layout editor pages, not just the ones I mentioned.

**Comment by DonnaScriptTechs** [comment]
I believe the demo admin is set to guests cannot change anything. This is to avoid people messing with the demo. :) 

I can't reproduce any issues in my sites.

**Comment by DonnaScriptTechs** [comment]
Just checked and our demo is set so that people can view it but settings are disabled and cannot be saved.

**Comment by Elshara** [comment]
Yes I know this. That's the kind of functionality I'm seeing happening here.

**Comment by shivani2910** [comment]
@Elshara we've checked this at our end on local and multiple staging sites in all themes but this issue is not appearing. As Donna said that on demo, you can not make any changes in admin.

On your site, this should not be happening and no other user has reported it yet. Please try checking this at your end again in another browser and make sure 3rd party aps are disabled (because these can sometimes cause javascript conflicts on layout editor). If you still have issues saving settings in Layout Editor, please contact support. Thanks!

**Comment by Elshara** [comment]
No problem. sorry for the trouble.

**Comment by DonnaScriptTechs** [comment]
We appreciate your feedback so it is not trouble for us to check. :)

**Comment by Elshara** [comment]
cool :)
