### ISSUE TITLE
Enable Ajax And Jquery

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#70]
Social Engine has to at some point, rewrite its code base. For one thing, just having a basic page load like the home page, a blog page and so on, requires so many scripts to load on one page, not including inline css styles, this is becoming a major problem in more than one way. Google has switched its entire search bot traffic for mobile optimized pages. Yeah, the closest thing social engine will get to even indexing half of what it cannot see, is mobile view. I can assure you, no widget, in page anything will be displayed to google and mobile users if you post say a new members area on the home page, you have to edit all your mobile pages by hand. What if you add code to the head tag of your page? It won't show up in mobile. What if you click on full site every time you just want to view something? Users get very annoyed at having to do this. It's better to cut out mobile view entirely, to replace it with something phpfox has done for years. Introducing: ajax and jquery. Social engine needs a modern update to be useful for both members and search bots alike. This way our existing sites will be updated not only with content, but with the code every person loads to keep it running. I'm talking minimal scripts on each page, just load the content and whatever scripts needed to be individual, not on every page. You don't want to have scripts for 18 other modules loading on a blog page if all you want to do is view a blog comment. Same goes for photos, videos and just about any other content item out there.

**Comment by smazurov** [comment]
When it comes to a complete rewrite, we'll most certainly account for making frontend more fluid in its rendering.  We'll also be making smaller improvements in the next few 4.x versions. I will close this issue because it doesn't seem to have any concrete suggestions.

**Comment by Elshara** [comment]
Thanks. I know updates uses ajax and this is really cool!
Auto loading items is a first step. Next is page loads. I suggest
trying page loads.
