### ISSUE TITLE
Videos not playing

### ISSUE THREAD

**Issue by jhayden2000** [SocialEngine/phpv4-issues#700]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … upload a video
2. … try to play the video after it finishes processing
3. …

What happens?
-------------
… the video screen disappears

What were you expecting to happen?
----------------------------------
… the videos should play

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
------------------
watch video here: https://drive.google.com/open?id=0ByPVgtzzXNZKWXBRZElJZm95RDQ

What versions of software are you using?
----------------------------------------
**Operating System:** …

**SocialEngine PHP Version:** … **4.9**

**Comment by Elshara** [comment]
Did you try uploading it from another source? I'm not sure if
drive.google.com is one iframely supports.

**Comment by jhayden2000** [comment]
I wasnt uploading from google drive. The videos were on my harddrive

**Comment by Khushboo016** [comment]
Hi @jhayden2000, We have added this issue to our internal bug tracker that after upgrading to version 4.9 from an earlier version, the video uploaded using "My Computer" option does not play in the videos section after its processing. We'll soon fix this bug.

Thanks & Regards!

**Comment by GabryNet** [comment]
It seems is working fine with SEAO-SES Advanced Videos Plugin ... do you use the SE default video plugin ?

**Comment by jhayden2000** [comment]
Lol. Yes i havent added any plugins yet

**Comment by GabryNet** [comment]
Hmm ..why LOL ? not all from here knows that they need to test the SE with original plugins to discover problems/bugs ... is a big community and we need to help each other with questions and tests before a decision ..as i can see in your bug description you are not saying anything about using the original video plugin for testing so i think i have put a normal question to help solving this ! Have a good day !

**Comment by Elshara** [comment]
That's good news.

**Comment by DonnaScriptTechs** [comment]
This is fixed for 4.9.1 once we release it. If you still have this issue after we release, please open a new bug report.

**Comment by Elshara** [comment]
:)
