### ISSUE TITLE
Updates not loaded in mini menu

### ISSUE THREAD

**Issue by angelinfante** [SocialEngine/phpv4-issues#701]
What are the steps to reproduce this issue?
-------------------------------------------
1. Generate an update for a member
2. Log in with that member and try to view the notification from mini menu

What happens?
-------------
Updates are not loaded. It gets stuck on "Loading..."

What were you expecting to happen?
----------------------------------
View the updates.

Any logs, error output, etc?
----------------------------
JS ERROR: ReferenceError: Can't find variable: DetectMobileQuick

What versions of software are you using?
----------------------------------------
**Operating System:** Mac OS and Safari

**SocialEngine PHP Version:** 4.9.0

**Comment by Elshara** [comment]
You using php7? This happens on php7 with me.

**Comment by angelinfante** [comment]
Yes, PHP7

**Comment by GabryNet** [comment]
Thank you for posting this bug, the same for me !

**Comment by Khushboo016** [comment]
Hi @angelinfante, @Elshara, @GabryNet, We have added this issue to our internal bug tracker and this will be fixed soon.

Thanks & Regards!

**Comment by Elshara** [comment]
:)

**Comment by Elshara** [comment]
Thank you! You're welcome.

**Comment by Elshara** [comment]
I should point out, this issue happens prior to 4.9.0 and existed in 4.8.

**Comment by DonnaScriptTechs** [comment]
We've added this to our list to fix and scheduled it for 4.9.3. As this tracker is closing, we'll close this now. For new bugs, please post at our [new community](https://community.socialengine.com/forums/).
