### ISSUE TITLE
Fast fix for the exec() function is not available ffmpeg path video plugin

### ISSUE THREAD

**Issue by GabryNet** [SocialEngine/phpv4-issues#702]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. …Enable PHP-FPM for your domain in MultiPHP Manager
2. …Install Video plugin from SE admin
3. …Insert path to ffmpeg

What happens?
-------------
…After insert ffmpeg path (example:  /usr/bin/ffmpeg) you can receive the next error "the exec() function is not available"  ...

What were you expecting to happen?
----------------------------------
…Should save the ffmpeg path without error if ffmpeg is installed on your server

Any other comments?
-------------------
…TO FIX THIS PROBLEM JUST DISABLE PHP-FPM FOR YOUR DOMAIN IN MultiPHP Manager

PS: this fix is only for those encountering this problem like i had , for others all can work without any errors, depends also on how did you compiled EA4 ... myself i have to make a profile to work not only for SE php as i use also other scripts on my VPS.

What versions of software are you using?
----------------------------------------
**Operating System:** … CENTOS 6.9 x86_64 virtuozzo – server cPanel & WHM 64.0 (build 15) latest updates PHP 7.0

**SocialEngine PHP Version:** …4.9

**Comment by Elshara** [comment]
I wonder what else the plugin disables? I think it may be happening on
my server as well.

**Comment by Khushboo016** [comment]
Hi @GabryNet, This is something related to Fast CGI which is generally not recommended to be enabled on the server if you are running SE PHP site on the server. So, we recommend you to disable "PHP-FPM" too on the server.

Thanks & Regards!

**Comment by GabryNet** [comment]
Hello @Khushboo016 thanks for reply ... this is what i did and it solved the ffmpeg path error , that's why i opened this topic so i can help also other that can have this problem.
Hello @Elshara , after i disabled the PHP-FPM i did not see any other problem related with disabling it ...so for the moment we can take the advice from @Khushboo016 and keep it disabled if it does not help us to run our scripts that we use on the server.

**Comment by Elshara** [comment]
Sounds good! Ty.

**Comment by Elshara** [comment]
:)
