### ISSUE TITLE
Add Ability To Choose Column Number In Page For Layout Editor

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#703]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Go to layout editor in admin control panel.
2. … Click on edit columns.
3. … You will see a list of preset options available to you, featuring sets of 1, 2 and 3 column layouts. Some have side bars.

What happens?
-------------
… The new column width editor is nice, but not ideal if you want to have, say, a 4, 5, 6, etc, column layout. Some columns, could position themselves vertically, while others, could do so, horizontally, creating the ability to view content on any angle. Whether it is a diagonal or not, choosing the number of columns, would allow you to add a full width column, or a partial width column, and then provide a slider to let you choose the width or height or depth as it were, of every column present on the page. This way, you have control of what content looks like on the page. You wouldn't need to, therefore, have to manually edit column counts in the database, if you uninstalled one module, and replaced it with another, which used the same page ID settings as the prior one did. You'd just be able to cancel out any existing columns of data, to replace them with other ones, if you wished. Each column would have its own controls at the top of the layout editor, so you would be able to independently control existing data, for both modules and columns alike.

What were you expecting to happen?
----------------------------------
… Better management of columns. Right now, social engine can't even have two full width columns per page, officially. But if you swap third party modules which create pages for such, you are left with an over bloated layout editor for new pages.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Layouts are fun. We should have the ability to enhance how fun they can be on our sites.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.9.0

**Comment by Khushboo016** [comment]
Hi @Elshara, We are sorry but we do not quite understand your feature request here, so, can you please explain it with the help of an example.

Thanks & Regards!

**Comment by Elshara** [comment]
1. Columns can only be 3 side by side on a page.
2. Columns can only have 1 full width on the top or bottom of a page, not both.
3. Specifying the number of columns a page can have, means having the
ability to manually edit the number of columns you can have, by just
adding one with a fixed or variable width.
4. A column editor function would need to be in place to do so.
5. Right now, columns which are already existing in the database, does
not integrate with the page count of columns controlled by the layout
editor functionality.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#102

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
