### ISSUE TITLE
Hide Show Navigation Menus

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#704]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Provide the ability to add hide and show buttons for menus.
2. … For longer type browse menus, main menu, and other menus, like the footer, social links, etc, it takes up space... It's common practice for mobile based navigation controls to have it available, but could be an optional feature for all menus, including but not limited to generic ones.
3. … Right now, menus and menu items created through the menu editor, are very bulky and can't be hidden or placed in tab containers to hide or show their contents.

What happens?
-------------
… You don't have control of what items are accessible provided the space you have to work with. People don't like scrolling, but they love to be able to access things they need to. You can create a dozen short cut type menus, but they just bloat the page you are trying to make visually appealing. Having the ability to have one menu for everything, but be able to hide or show it, would give a better appearance. I'm not just talking about navigation menus here either, I'm also talking about search and filter menus as well. Settings two.

What were you expecting to happen?
----------------------------------
… Have menus look better, but accessible if you need to use them.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… It would be cool to assign menus to all available search type filters for modules, so all you have to do, is specify what type of filter you want to search for, and a menu will pop up showing you all which is available.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.9.0

**Comment by gsf00001** [comment]
Are you referring to how some Apps (like sidebars) display a small 'something' to allow opening/displaying the menu only when the User desires?

**Comment by Elshara** [comment]
Yes I am.

**Comment by gsf00001** [comment]
Yes, this would have saved me some theme/customization costs and could still be useful to me in the future.  Great FReq Elshara.

**Comment by Elshara** [comment]
Same here. You're welcome.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#103

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
