### ISSUE TITLE
Column Modifier For Menus

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#705]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Menus themselves can be sorted into tab containers to occupy available space, however parallel menu items, or columns for menu items, seem to not exist. This functionality would provide people with a way to add more items per menu, and also make the menu look unique and attractive.
2. … Replacing one menu with another, would be necessary. Considering, most menus, are dependent on the column of the page, and not their own space within the column, menus themselves with their own column assignment, would provide ample room needed, to make available space look streamlined and interesting. This way, while menus generally take up a full width column or a part of one anyways, you could assign any relevant items you want, but they wouldn't have to exist underneath other menu parent items, as sub tabs or hover tabs, or have to fit within a horizontal or vertical line.
3. … Currently, menus can only be positioned one way, in a single column, full width space alignment.

What happens?
-------------
… Menus provide people with a means to get around. Imagine transportation that could travel any direction, at any speed. If distance matters within limited space, you have options. But if space matters for limited distance, you have none. This is because the distance you travel virtually speaking, needs a point of direction to travel to. It can't do that if only one direction exists, and that's neutral.

What were you expecting to happen?
----------------------------------
… The possibility for menus to have independent columns or layouts per item.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Menus should also have the ability to control who can see them on a per item basis.

What versions of software are you using?
----------------------------------------
**Operating System:** … Windows 10 personal. Linux web server.

**SocialEngine PHP Version:** … 4.9.0

**Comment by gsf00001** [comment]
@elshara
Can you provide a mockup of what you're thinking?  I think I get it but I could also be off in a completely different direction.  As they say, a picture is worth a thousand words, and I can be a little dense in the head at times.

**Comment by Elshara** [comment]
No not as yet.
But just imagine parallel menus. That's what I'm thinking of. The
layout could be horizontal or vertical.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#104

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
