### ISSUE TITLE
Feature request - Admin can add users back end, to avoid signup or  ability to hide profile types

### ISSUE THREAD

**Issue by poeticjustice** [SocialEngine/phpv4-issues#707]
If this feature is already there I apologise but I have never seen it.

sum it up quick... either way, to make new members skipping signup questions in admin, or ability to make profile types, but the ability to hide profile types from being chosen or seen on signup and browse members

An example of a site I have, I have about 30 profile questions, that are all required and detailed.

The other day, an advertiser wanted to see the site, for potential advertising.

Now, I dont want an advertiser to join in the same process as my members, and I dont want the advertiser to fully browse my site.

I also dont want to create a profile type for advertisers, because I dont want Advertisers seen as an option for profile type for members joining, nor do I want Advertisers as a search option in browse members.

Way round this was me, going into MySQL and creating an entry with NULL.
Then logging into the site, and giving the new member a member level of the advertiser, thus skipping the signup, although if advertiser went to edit profile, they are asked to choose profile type.

As admin you want to be able to create these specific profiles easily in the backend, I dont want to log out of admin, and go thru signup process, making quick fake entries.... just so i can set a profile up for an advertiser, and frankly, i dont want them doing the same.

So either way, to make new members skipping signup questions in admin, or ability to make profile types, but ability to hide profile types from signup and browse members

**Comment by Elshara** [comment]
So essentially you want a dedicated advertiser profile type, but
without members being able to know it is a profile type for the
advertiser and have the advertiser profile type, or any other for that
matter, be able to be automatically filled in via manual member sign
up in the admin control panel? Is this what you want?
It is possible to just remove the statistics plugin from the member
profile page. So nobody knows what profile type you belong to. Only
admins know. Sorry, I called it statistics, it's probably known as
member info, not profile fields.
As for manual sign up from administration panel, it isn't possible yet.

**Comment by Khushboo016** [comment]
Hi @poeticjustice, 

Regarding "sum it up quick... either way, to make new members skipping signup questions in ":
If the Profile Type created for advertisers is made hidden at the time of sign-up, then how the new user who has to sign-up on your site as an advertiser would be able to select that Profile type at the time of sign-up. 

Looking forward to your reply.

Thanks & Regards!

**Comment by gsf00001** [comment]
I could use something similar, and my thinking is:
A)  We need the ability for ADMIN (probably through ADMINcp) to add Users 
B)  Some fields (such as Profile Type) should have an added control/filter/whatever to display in front-end, back-end, or both.

(A) seems it would address the OP FReq
(B) seems it would allow the flexibility desired (by me - I obviously can't speak for poeticjustice)

**Comment by poeticjustice** [comment]
the advertisement profile was an example.
and the point is, you dont want users or even advertisers to signup via profile type as advertisers.

If an advertiser contacts you, you want to be able to give them a unique profile, that isnt of any profile type, the profile you give it a member level.

Way i currently do it is , go into users of mysql, and a user for the next sequence of member number, put an email and name in then, go back to SE admin panel, and I get a new profile thats completely null in all fields, making it not searchable, and not even a profile type... but it works.

Its litrally so users can be added, you may need to add a contributer or another admin, its silly to say ohhhh hello new admin, i cant make you account unless you signup, and on signup you would never have a profile type called ADMIN, specifically for admin to sign up, because your users will try to become an admin

**Comment by gsf00001** [comment]
SEAO has a Subscription Plugin that allows the ML and Profile Type to be hidden and automatically configured upon signup (the primary reason I was going to use that Plugin).  Although a very useful Plugin, it doesn't address the above issues A+B that I mentioned which are useful for other purposes, so if A+B get addressed (front-end and back-end functionality), I'll be using that as well as SEAO's Plugin (front-end).

Thanks for this FReq.

**Comment by adira-g** [comment]
Hi @poeticjustice, 

Maybe I have an idea for your advertisement profile, at least as long the feature is not implemented.

Create a profile-type, i.e. "advertisement account". Create also a member level for advertiser and edit the member level settings, that this profile is hidden, nobody can post on that profile, nobody may visit the profile etc, just as you need or want it. Same with the profile questions.

Then use the (free) plugin from SEAO "Mapping Profiletype to Memberlevel" and map the advertisement profile-type with the advertisement member-level.

This way, your users won't see the ad-profiles but the advertisers can login and browse. 

It is visible on sign-up though, but maybe it is a little start.

Kind regards,
Dorina

**Comment by adira-g** [comment]
by the way: I'd like the ability for admins to add users without using the sign-up routine in the frontend, I was missing this feature several times. It would make things easier and with the possibility to hide certain profile types on signup it would be perfect. I am here absolutely with you, @poeticjustice

**Comment by poeticjustice** [comment]
SEAO doesnt exactly do what is needed, Social engine solutions has a more advance plugin I use, but its about creating a profile admin side that is NULL in each field, i can do manually in mysql, but id rather not

**Comment by Elshara** [comment]
I'll tell you something related which would totally make better sense
than profile types, is dependent fields.
This way, you can create profile types but they are integrated based
on the dependency of other questions. If you want someone to have
completely separate questions than someone else, the solution is not
to isolate common questions from having to be duplicated. But rather,
to use categories for such if you want it to be publicly known, and
then have dependent fields programmed for specific question and answer
types which can have their own sub questions based on the answer, you
won't see unless you change your other answer.
OF course, members will still be able to fill out the wrong profile,
if say, you had an admin based profile type with additional questions
associated with it via field dependencies. However, you not only have
member approval on sign up, but you also have the ability to code a
profile edit screen into the approval screen, so if members decide
they are going to answer questions wrong on purpose, to enforce right
answers, you can reject their profile and have it be pending approval
again, based on a dependency violation. This would give members the
option to enter different information in the profile question (s)
which were marked as invalid. This way, that which is correct can stay
on the site. It also works if you wish to schedule approvals, to auto
approve, so if a member answers a field dependency through multiple
choice for example, or tick boxes, you could assign certain sequences
to auto approve, but certain ones to require approval based on the
order of information provided by the member. Then it would just be up
to you to decide how the information gets processed, once it is there
to analyze for itself as such.

**Comment by gsf00001** [comment]
@elshara
Yes, dependent questions would be a great Feature Request (on signup and anywhere else Profile Questions can be added).  An Advanced Forms Plugin out there is implementing this so Users can create form questions that are dependent on answers to other questions.  My thinking is that although this is related to this post, it is possibly (probably?) a separate FReq for another ticket.  If you agree, I'd be happy to create it if you would like (I don't want to hijack your idea or muddy up poeticjustice's issue in this ticket).

**Comment by poeticjustice** [comment]
Doesnt SE do this already?

I have dif questions set up based on Male Female being choosen?

**Comment by Elshara** [comment]
Feel free to do so. I'll back you up. I'm actually very glad and happy
you can see it from this point of view. I think it would solve things
and provide an interesting creative way to manage user fields.

**Comment by Elshara** [comment]
Advanced forms wouldn't provide replacement functionality for profile types.

**Comment by Mthorganby** [comment]
You can also add a payment subscription plan to the website which is link to a member level type, say "Advertisers" with a description " You can place adverts, but you can't add/delete anything else" if you use SEAO advertising plugin. Charge them a USD 1.00 so others don't chose the member setting.

If you don't use this SEAO advert module give this member level only view options to all modules so they can still see the site.

Or you can manually add a new user and assign to a member level, send the login details to the user.

**Comment by poeticjustice** [comment]
I think no one truely understands.

What Im saying is ability for admin to make profiles backend, so they can make a new admin, a new super admin, a new contributer, a profile that they map as member level advertiser or what ever......

without asking advertisers to go thru the process of a profile that has no relevence to them, filling out pointless info.

making member type for an advertiser is nasty. because Advertiser begins with A, and is alphabetically first on signup if you had profile types.

Imagine a new use comes to join, choose profile type, the advertiser is first thing they see.......

No that member will be like "wtf why is advertiser priority, omg this site will be spammed with ads" = drop off.

I think some people are missing the point

**Comment by Mthorganby** [comment]
Members have to go through the signup process to get and set all the setting, max Mb, max videos etc from the Member Level.

Number you  Profile Type with: 01. general, 02. Seller, 03.-----, 04.---- .... 99. Advertiser

Advertiser will be at the bottom as there is no other way of sorting the Member Profile Types, unless there is a sorting order field added to the database and it will need to be hard coded to sort on the sorting field

**Comment by Mthorganby** [comment]
If you save the bullet list and look in Chrome the <ol> is converted to <ul>
In the theme.css : 

```
ul
{
  list-style-type: none;
}
```
Where are my nice little bullets gone??

**Comment by poeticjustice** [comment]
@Mthorganby 

I can create in mysql new members without a profile type, and then assign them as a member level

As mentioned, want option to not display certain member types on signup.

And once again im saying it be great to add member accounts within admin panel.

I think people are losing sight of the request here.

**Comment by gsf00001** [comment]
@poeticjustice ==> "I think people are losing sight of the request here. Ive laid it out pretty simple, And no one gets it..... which is more shocking."

I'm with you "B) Some fields (such as Profile Type) should have an added control/filter/whatever to display in front-end, back-end, or both."  Or am I still missing it?

**Comment by Elshara** [comment]
The issue here is you have to fix one issue, to recreate the fix when
making the other.
In this case, you need to fix the inability for members to recognize
advertiser profile ID, prior to making available, the ability to add
such a functionality to admin. They are related issues but it's like
asking a slice of orange to look like a slice of apple. It will look
different but they cut the same and that's only if you know how to
slice them properly in the way you wish to.
What I'm pointing out here, is this is two separate issues.
In order for you to edit a member type, you have to do so via the
database once an initial selection is made.
You can't add people manually from admin. Period.
You also can't hide member type from other members. Unless you remove
the profile info block from the profile of the person. But you would
then have to hide it from everyone if you did it since it is a site
wide layout.
You can't achieve it. Not yet. Things have to change, but in order for
them to do so, the ability to show member level   and member type, or
hide it altogether, must be present in the profile info module.  Then,
you have to be able to edit member profile from admin panel. Something
which isn't available. Then you can't just add people manually,
essentially filling out their profile for them, since the feature
doesn't exist. Unless you do the full sign up routine by logging out
and then signing up  as someone else.   Then you have to go through
the messy business of telling the unknown person their password, get
in touch with them by not knowing a thing about them. So you see?
It's impossible to do, it won't happen.

**Comment by gsf00001** [comment]
@poeticjustice FYI - I just realized that SEAO's Bulk Import Plugin offers the ability to add a single User from ADMINcp, just an option that might buy you time until SE incorporates this functionality.  Haven't tried it yet (it's 1 of 5 of their Plugins I still have to get), but they do have a video on the Plugin info page on how it works.

**Comment by Mthorganby** [comment]
USD 59.00

Single user / bulk users etc You can add them to a member level (which can be a hidden one )

https://www.socialengineaddons.com/socialengine-administration-tool-bulk-importing-users-creating-dummy-test-users-plugin

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#105

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
