### ISSUE TITLE
Activity Feed And Comments

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#71]
People should be notified as a new activity feed item when ever a new comment or like has appeared. This way, posts aren't just a 1 time occurrence and can be seen again and are more friendly to people who haven't noticed them.

**Comment by shivani2910** [comment]
@Elshara, activity feeds corresponding to new comments posted on different content already exist. By default, they are set to appear only on "Subject's Profile Feed". So, you can simply go to Admin > Settings > Activity Feed Settings page and then choose comments related feed one by one and select "Main Feed" option in "Display" field and save changes. Now, these activity feeds will also appear on the main feed of your website.

Regarding activity feeds for new likes, we've noted down your suggestion to our features list and will discuss this internally. Thanks.

**Comment by meetgerry** [comment]
I am not sure if anyone has mentioned this earlier here. I thought of adding it here.

While posting a message in Activity feed, currently you can only upload one picture. Would be great if you allow users to upload controlled number of images. Same with the commenting on a post, i would be good if you have all the options available for comments which are found in the post field. See image.
![2015-06-544](https://cloud.githubusercontent.com/assets/8540750/8383386/693af652-1c42-11e5-8cce-bf649e21eea6.png)

**Comment by shivani2910** [comment]
Hi @meetgerry, thanks for the feedback. We're glad to tell you that we already have some of these features listed in our roadmap of SE PHP and will work on these in near future.

**Comment by meetgerry** [comment]
Thanks Shivani, whether its works or not, you guys are the best in support and service, that's one reason why I switched from Boonex to SocialEngine.

**Comment by shivani2910** [comment]
You're welcome @meetgerry! We appreciate your feedback!

**Comment by smazurov** [comment]
this has been split up into #142, #143 so closing this one.
