### ISSUE TITLE
Feature Request - Document upload on signup.

### ISSUE THREAD

**Issue by poeticjustice** [SocialEngine/phpv4-issues#710]
Like niche communities where the importance of having genuine members, may need members to be ID verified, to prove, who they are.

Having a document uploader on signup would be fantastic if it was simply limited to PDF, Jpeg, PNG upload, and/or url to be viewed on google docs,

and then in manage members stats, your able to see the file link for file uploaded server, or external link.

You are able to verify people soooo quickly.

Getting someone to signup, then email them to say " Hi can you provide documents to prove who you are before accepted and approved"

Adds extra communication, more time in between getting them verified, or them just ignoring the email.

Its a great way to find people early on who are pretending to be someone they are not. No recapcha can detect fraudsters and catfishes ha

Either add it in a stage similiar to profile questions, photo upload, document upload

Or add it as a specific profile question

**Comment by Elshara** [comment]
File upload as profile question type would solve this easily. Just set
allowed extensions for this.

**Comment by poeticjustice** [comment]
Yep its needed badly as a profile question, or at a stage of signup

**Comment by Khushboo016** [comment]
Hi @poeticjustice, To avoid fake sign-ups on your site, you can create the Terms of Services for your site very carefully in such a way so that users avoid doing fake sign-ups on the site.

Thanks & Regards!

**Comment by angelflo** [comment]
Hi @Khushboo016 , I think you don't really understand what ask @poeticjustice 
1/ Nobody read term of service and if you want to use a fake picture on your profile do you really think that if the TOS say that this is not allowed, people will not use fake pic ?? sorry but this is really naive (this is why all community websites use verfication process)
2/ Need a upload file for a real verification of members like this is the case for all the major community websites like couchsurfing, airbnb, blablacar, etc... where you need to update a proof of your identity like passport, driver licence or a picture of you with a post-it in your hand on which you write your member ID (for all the dating community websites). This process is the only way to exclude fake members and/or fake pictures.
Thanks & Regards!

**Comment by poeticjustice** [comment]
@Khushboo016 your reply here has actually shocked me!

**Comment by poeticjustice** [comment]
@angelflo I truely appreciate you understood, exactly what I meant.
@Khushboo016 response has actually stun me.

TOS, I have more TOS conditions than LinkedIn has, My TOS is Long.
TOS is basically i means to execute an action, such as kicking someone off my site legally.

I actually confused by Khushboo response.

I NEED, like Angelflo said, To do true verifications, this includes ID, Passport, Maybe Right to work documents, To prove they are real.

Hence Document uploader which only supports pdf, jpeg, pngs

**Comment by DonnaScriptTechs** [comment]
Hi everyone,

Thank you for providing this feedback. Document uploads can also allow malware/viruses to be uploaded so there are considerations for that with this request. 

You want to have a profile question type that allows admin to chose Upload File with allowed attachment types to be set? 

Another option to this is two factor authentication , https://www.twilio.com/use-cases/two-factor-authentication . There are other providers, that's just an example.

**Comment by poeticjustice** [comment]
yea basically a profile question or a next stage signup, similiar to adding a photo, another file upload section but for identification purposes, be it jpeg only, or pdf
And in manage members section, you can click to view the ID file uploaded

I know obviously malware virus is big thing, but surely someone could upload a virus at the photo uploads, disguise a exe as a jpg? Im sure SE would have tested this.

PDF obviously can contain virus easier than jpg.

So maybe only allow document uploads to be jpeg only, smart phone take great photos, so taking photos of ID and Documents will be clear.

Its all about making sure the person signing up is VETTED, like Airbnb and so many other sites

Its not about bots joining, or 2 stage verification, its literally for ID-ing people

**Comment by JonSimon93** [comment]
I fully understand this, I have plans for a dating site, and its important that we ID people & use 3rd party plugin to give a verification tick.

As people will be meeting, WE DO NOT want catfish, and if people plan to meet, we would have their ID at hand

Having this at signup make more sense because profiles can be set to approve basis, so once checked.... approved.

I miss SE, and wish I never got this other script now.

**Comment by gsf00001** [comment]
==>"You want to have a profile question type that allows admin to chose Upload File with allowed attachment types to be set?"

Yes please.  You know me - flexibility (i.e. allow ADMINs to make their own choices, not the script locking them into certain file extensions because some ADMINs think certain ones are safe(r)).  Each ADMIN should determine the format(s) that are best for their needs and the risk(s) they wish to take.

**Comment by Elshara** [comment]
I have a feeling social engine is worried about default
implementation. It doesn't have to be on by default, but it's
available if someone wants it kind of thing. I doubt the concept is
far fetched.
I two want the ability, specifically to just add more profile photos
displayed inline.

**Comment by poeticjustice** [comment]
I have this, I have 4 profile photos, all inline and responsive

**Comment by Elshara** [comment]
Nice! If you're about to tell me/us it''s possible using profile
questions, I'd be very shoccked. I haven't found a way to do so.

**Comment by poeticjustice** [comment]
Not profile questions no.

But I have 4 inline Profile photos.
All photos goto profile photo album,
But each profile photo displays each photo uploaded to that profile photo widget.

So i have 4 profile photos all inline on profiles

**Comment by Elshara** [comment]
Ah okay. I understand better now. Yeah profile photos or embeds in
profile questions area would be awesome.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#106

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
