### ISSUE TITLE
Logical issue with the Share feature

### ISSUE THREAD

**Issue by adira-g** [SocialEngine/phpv4-issues#711]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. User privacy settings: everything checked
2. Activity settings: network & friends
3. User A is friends with User B
4. User C is friends with user B
5. User A posts some content
6. User B shares that content of user A

What happens?
-------------
Since user C is not friends with user A, he cannot see their content in the activity stream. User B can see user A's content. User C can see content posted by User B, however he can't see the shared item. Only user A can see the shared content, which doesn't make sense, since he see his own content anyway

What were you expecting to happen?
----------------------------------
It should be like in Facebook, that if a user shares some content, their friends will be able to see it, no matter if they are friend with the original owner of the post. In my example I expect user C can see the shared item, related to their privacy settings. Currently there are no privacy settings for activity like "who can see my activity: [everybody|registered members|networks&friends|friends]", hence all activity which is checked in privacy settings should appear to everybody (wich it does when activity feed setting is "everybody")

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
Some words about my network: I was running SE with an open activity stream. By the time there were  groups of people with different interests. With the module from SEAO advanced activity the people were able to hide certain posts or users, but in fact people were complaining about the content they didn't want to see rather than hide users. Well we have the great feature to change the activity setting to networks and friends only: problem solved: people can now choose their friends and just see content of friends. Here comes the share feature into the game: since people don't see everything of the network anymore, it is very interesting to share content that one like, so that other users eventually find new friends. But how the current share feature works, people only see content, they can see anyway. This makes the share feature useless in my eyes.

I faced this issue already a while ago on 4.8.12 with a couple of third-party plugins running, hence didn't give it more attention. Now running a new installation 4.9 I tried again and it seems to be a logical issue in SE core. I have to admit, I also had installed on 4.9 SEAO advanced activity before I was trying out the share feature. However advanced activity has been deinstalled completely (I hope). So I didn't try with a really fresh SE installation, but I don't think it would change anything.

If you say, it's intended how the share feature works, I herewith request a new share feature, where people can see their friends shared posts, based on the privacy settings of the original post. I request the feature, that people can set privacy settings for activity for "who can see" additional to the existing "what activity is posted"

Thanks for reading! 
Dorina from TanarisMedia NV

What versions of software are you using?
----------------------------------------
**Operating System:** NGINX, Debian 8, Php 5.6

**SocialEngine PHP Version:** 4.9

**Comment by Elshara** [comment]
Hi there. :)
I have a solution to this and it's simple and easy to implement.
1. Go to activity feed action type settings page. Sharing has been
significantly improved, and you'll be able to see different options
for such there.
1.1. The first option is to not allow sharing, and it's a separate
control from being able to share at all, keep this in mind.
1.2. Share attachments. If posts have links associated with them, to
external images or other types of content, they can be shared but only
if you select that type.
1.3. Share with objects profile feed. This means if you have a group
or event, and you only want the share option to appear within such,
you enable it there. For blogs and forums, it would be useless. For
profiles, member profiles I mean, this type of control is separate
from the option to enable or disable the item appearing in each type
of feed. An object feed, is something more than one person can post
to. A subject type feed, is something belonging to one profile itself.
The main feed, is the feed that is shown where no profile and or all
profiles converge on the same point. Note all such controls are
separate from this setting.
1.4. Share with subjects profile feed. This option is useful if you
want to let people view items, but only if they are viewing a specific
profile belonging to a member where only one person can post to it.
Which is the owner of the profile itself. Same rules apply for this
being separate controls for the sharing of content, as opposed to the
liking and commenting of it.
1.5. Share everything. This means no matter what happens, where ever
the activity feed module is displayed, sharing, liking and or
commenting functionality exists.
2. In order to achieve member privacy settings, you need to set
activity controls to public. The friends option, is only useful if you
don't want the public to see everything where ever main feeds appear,
such as on the home page. It also acts as a bottle neck, because the
feature of friends only, blocks other content from being viewed unless
you personally are friends with the person. So if a friend shares
content from another friend, you can't see the content because you
aren't friends with the person your friend shared their friends post
with. This is not the case if you set your feed to public, and then
limit on a post by post basis, who can actually see it. If you allow
friends of friends to do so, also replicated if you use networks for
such a purpose, you will then be able to get the functionality you
desire here. This way, you control what can get shared where, but if
you set privacy settings in plugin and member levels to only allow
friends of friends to view, you'll be able to customize who can see
what, and you will be able to track the friends you have by such as
well.
I hope it helps. Let me us know if you are facing a problem, I'll do
my best to help you out.

**Comment by adira-g** [comment]
Hi @Elshara,

thank you for your reply! Oh yes I noticed the improved activity settings including the share-options. It's a great thing, however if I set the activity to public, how could people see their friends activity in main feed and not that of other users? The idea is, that people can choose from whom they would like to see content. For this purpose, the setting of activity to friends is perfect. The only issue with this is, as you confirmed in your reply, that with friends-only activity settings, other people are excluded completely, even from shares from their friends in case the original post is not their friend.

I did not understand your suggestion, to limit on a post by post basis. I can't limit singe posts to be published only to friends or networks, can I?

Kind regards,
Dorina

**Comment by Elshara** [comment]
Hi Dorina. :)
What you do to achieve the functionality, is go to the main activity
item type settings page.
Go to the option which allows you to choose my friends, my friends and
networks and everyone for the activity main feed item option.
Now click on my friends and networks then save changes.
Now go to the manage tab, and underneath click on networks.
Under there, you'll want to change the default network names from the
continents, to custom.
Now who ever joins the custom network name, under settings, networks,
will be able to view updates from the network if they are a member of
it.
You can rename the title custom to whatever your network is about.
This way, if people wish to receive updates from friends of friends,
they will first need to be members of the network to do so.
If all members of the site join the network name, then by default, if
they add new people as friends, they will be able to see posts shared
by other people, as long as they are a member of the network.
Note networks are different than groups.
To block member updates from reaching members who aren't friends of
friends, all you do is just remove them from the network. They will
still be able to receive updates from their friends, and if they wish
to rejoin the network, and have their friends push the updates they
make to their friends, it can still happen. But by default, if you
join the network, and aren't friends with someone, say, if you are a
new member, and you join the network, you will see all the updates of
the network.
You could use networks to override friends, but that way anyone who
joins the network, will understand the requirement to do so, as being
able to have their updates viewable by anyone who doesn't want only
their friends to do so. This way, if you don't join a network but make
friends, you can still have the friendship, but that's all whose
updates you see as you aren't yet a member of the network.
Now, if the friend of yours decided they were going to share your
updates with the networks they belong to, you wouldn't know about it
if you are outside the network. But by default, if you have no
friends, it can't happen but you can remain an anonymous contributor
as far as the activity feed is concerned. If you only wish to see
updates from friends, and only allow such updates to be shared with
friends of friends, but viewable by only friends, then you will need
to customize who can see your posts upon their creation. Which means
editing the view permissions in member level and module level
settings, to set who is able to see the post itself. Unfortunately,
the friends of friends option does not exist, so you only have the
ability to set it to friends, or networks to achieve the functionality
right now.
I don't work for social engine and so I cannot guarantee you a time
where such a feature can become available. I don't even know if
advanced feeds have the ability to do so yet, however it would be nice
if it were possible. For now, I suggest trying the network option and
see if it works out for you. This way, you aren't limited by the chain
of command if friends lists matter. You could always change it later
if you wish.
I hope it helps.

**Comment by adira-g** [comment]
Hi @Elshara,

thank you very much for your post. The idea working with networks is great and it's what I have implemented into the site. I do it this way: I have several networks, based on profile questions, so users can see posts from friends and their network. They can't choose more networks, it is just limited to the one and that one can't be chosen directly, but through the profile question. It is a kind of compromise between completely open and friends-only since members group themselves by filling the profile questions, but I think it brings at least people with similar interests together. I would just love to use additionally the share functionality.

So my **issue turns into a feature request.** I am also trying to figure out how to code something myself. If anybody has some suggestions for a snipped, I am very happy to learn about it.

Thanks again :-)
Dorina

**Comment by adira-g** [comment]
> I don't even know if
advanced feeds have the ability to do so yet, however it would be nice
if it were possible.
In Advanced Activity by SEAO every user can specify, who may see the post similar to Facebook. But this doesn't change the limits of SE core. Shared items are still limited due the activity feed settings. To me it is even more confusing, if one posts something "public", but due the activity settings only friends can see it.

...time to dive into the code *laughs*

**Comment by Elshara** [comment]
I know the feeling. Friends of friends should just be a display issue
if anything, and shouldn't really be too much of a problem to
implement.
I hope you find a better solution. I try to be helpful. If you want, I
can tag one of the social engine developers directly to see if they
could provide some light here.

**Comment by adira-g** [comment]
>  If you want, I
can tag one of the social engine developers directly to see if they
could provide some light here.

That would be great! 

So far I think, it has to be done in /application/modules/Activity/Model/DbTable/Actions.php:
in the _public function addActivityBindings($action)_

There it sets the bindings in the table activity_stream.

Currently we get a table with the type "members" with the target_id of the original owner (type="parent"). This leads to the result, that the feed renders this post to the original poster's friends. I manually changed the value "target_id" in in the row with type="members" to the id of the user, who shared the item (type="owner") and there we go, the friends of the user who shared the item can see it :-)

Now I need to find out, where exactly happens the binding. The above mentioned function calls an event:
`    // Get privacy bindings
    $event = Engine_Hooks_Dispatcher::getInstance()->callEvent('addActivity', array(
      'subject' => $action->getSubject(),
      'object' => $action->getObject(),
      'type' => $action->type,
    ));
`
Any idea?

Thank you :-)

**Comment by adira-g** [comment]
Okay, I got it to work, though it's probably not the most elegant way, since I was editing the core code. However, I am sharing it here in case it will help someone else:

in the already mentioned file /application/modules/Activity/Model/DbTable/Actions.php

beginning in line 526 ( function addBindings() ) remove the following lines:
`      $streamTable->insert(array(
        'action_id' => $action->action_id,
        'type' => $action->type,
        'target_type' => (string) $target_type,
        'target_id' => (int) $target_id,
        'subject_type' => $action->subject_type,
        'subject_id' => $action->subject_id,
        'object_type' => $action->object_type,
        'object_id' => $action->object_id,
      ));`

and add instead:

`	// case shared content

	if ($action->type == 'share' && $target_type == 'members')
	{ 
      $streamTable->insert(array(
        'action_id' => $action->action_id,
        'type' => $action->type,
        'target_type' => (string) $target_type,
        'target_id' => $action->subject_id,
        'subject_type' => $action->subject_type,
        'subject_id' => $action->subject_id,
        'object_type' => $action->object_type,
        'object_id' => $action->object_id,
      ));

	}
	else
	{
      $streamTable->insert(array(
        'action_id' => $action->action_id,
        'type' => $action->type,
        'target_type' => (string) $target_type,
        'target_id' => (int) $target_id,
        'subject_type' => $action->subject_type,
        'subject_id' => $action->subject_id,
        'object_type' => $action->object_type,
        'object_id' => $action->object_id,
      ));
    }
`

That's it. I hope it helps somebody. I am always interested in better solutions. For me it works now so far.

Thank you.
Dorina

**Comment by Elshara** [comment]
That's good! I'll still tag the developers in here as I promised to
you I would, to let them know the issue exists so they can look at the
code and see what they can implement or do with it.
Let me know if you would like third party developers for social engine
added and I can tag them two.
Glad you got it to work!
Summary: allow friends of friends filter to be implemented for various
items. Current issue is about activity type share.
@Anshuse @DonnaScriptTechs @Khushboo016 @RaymondBenc @shivani2910 @smazurov
Hope I got everyone. :)

**Comment by gsf00001** [comment]
@Elshara Should this all be part of the bigger discussion of sharing of all content in general?
- who can see this (for example, friends of friends)
- what do I want to see (only friends - not friends of friends)
- blocking needs to be considered
- Custom Lists (not every site uses 'Friends' as the primary determination of sharing)
- etc.

As usual, interested in your thoughts.

**Comment by Elshara** [comment]
Yes and no. Specific sharing options are simply tied in with the
feature itself. This addresses the base need of who can be allowed to
share the content itself, not exactly how it can be shared. Although
such functionality would be nice besides a profile update.

**Comment by DonnaScriptTechs** [comment]
Sorry for the late reply. I thought I had replied earlier. Please do not ping us in the bug reports. We will see them. :)

Things that tie into the feed tend to create more weight. It's always a balance of weight against benefit. 

There's also the privacy issue. If someone doesn't want friends of friends to view something and is forced to, that would not go over too well. As we had a release today, I've not had time to fully go over the request but it's not something I would want on my own site as I'm very careful as to things I enable that can cause unnecessary loads. 

Facebook is ok but they pay billions for servers for their features.

Thanks for posting your feature request and the tips that you found work for you. I honestly think this feature would generate too much weight in the script. Perhaps a plugin by a third party would be best for those that want something like this.

**Comment by Elshara** [comment]
Actually, I was thinking replacing networks with friends of friends
functionality would probably do this justice. But that's just me.
Sorry if the pinging is annoying. I'll not do it anymore. That's what
I thought you may have missed it somehow.

**Comment by DonnaScriptTechs** [comment]
I wouldn't want to remove networks. It's a handy feature. I use it for genres for people on my writing community. :)

**Comment by adira-g** [comment]
@DonnaScriptTechs 

Thank you for your reply.

Regarding privacy, our network is set up in a one-way friendship basis (follower), people can just follow without request approve. So they basically know, that any user could see their content anyway. So friends of friends is in our case confusing, it should be followers of followers, but that is surely not in every network the case. But other networks are completely open and show any activity to all users.

Why do you think, it would cause unnecessary more loads that way?

**Comment by DonnaScriptTechs** [comment]
Hi @adira-g !
You're welcome. :) 
Well the script already has to check privacy for each user x the amount of users online x the amount of items being posted. Then if someone shares an item, or many someones, it has to check the privacy again when that is posted and accessed by the ones it's being shared to. Anything extra we add to it can add more queries. I can't say exactly what the results would be in your case. It depends on the amount of activity in the feed since this is just for feed items (if I read the issue correctly).

**Comment by adira-g** [comment]
Well, I didn't add another privacy check, I just changed the code in that way, that shared items appear in the feed to the followers of the user, who shared the item, instead to the followers of the user, who posted the original post. So the queries are exactly the same as in the original version.

It's just the question, if you want to keep the logic of the share function as it is. In my opinion that way it doesn't make so much sense to share posts, since the are visible to exact the same people, who can see the original post anyway, right? Or do I miss something here?

The little fix works for us and I am pretty happy with it. If you see my point and agree, that the share logic in the current SE doesn't make sense, it would be great to get an update soon.

Additional it could be a feature, to have an option in the admin panel to use it that or that way. However, I understand, if you had privacy options for users to chose, who may see the posts (which are not there, right?), that this would increase the weight including extra queries.By the way, there are third-party-developers who have these extra privacy options included (SEAO Advanced Activity), but this only works, when the activity feed is set to everyone. Once you set it to friends or networks only, the posts are limited by this settings. It would be an experiment to check, how it works together with my little hack, but honestly.. I am totally with you and I don't want to much extra queries in my installation: less is in this case more.

**Comment by Elshara** [comment]
I wonder if a network dependency would make a difference here.
