### ISSUE TITLE
Bug: Categories in plugins Event and Group 490 can't be deleted or renamed.

### ISSUE THREAD

**Issue by Burno317** [SocialEngine/phpv4-issues#712]
Hello World,

I have found a bug that regards the default categories of the Event and Group plugins in SEPHP 490 that can't be deleted or renamed. This bug was confirmed on others sites I have.

What are the steps to reproduce this issue?
-------------------------------------------
1. Just try to delete the default categories in the event and group SEPHP plugins
2. Just try to rename the default categories in the event and group SEPHP plugins

What happens?
There is a pop up message indicating a technical issue or error.

What were you expecting to happen?
the possibility to delete and rename certains categories

Any other comments?
Have a great day.

What versions of software are you using? 490
**Operating System:** Windows 7

**SocialEngine PHP Version:** 490

**Comment by DonnaScriptTechs** [comment]
We've already fixed this for 4.9.1 which will release soon. Sorry for the inconvenience this may have caused.

Please upgrade to that version once we release it. Should you see the issue again, please open a new report at that time.

Thank you!

**Comment by Burno317** [comment]
Hi,

Thanks for your fast response.

I am glad to read that you already fixed it.

Have a great day.

**Comment by DonnaScriptTechs** [comment]
Have a great day as well. 4.9.1 will be out soon. watch our blog or community today for news. :)

**Comment by Elshara** [comment]
:)
