### ISSUE TITLE
Add Support to Gif Player

### ISSUE THREAD

**Issue by leandrotavaresrocha** [SocialEngine/phpv4-issues#714]
Hello,

Now that SE support GIFs I would like to request that it also support GIF Players to avoid messy timelines with several GIFs running all together.

Some social networks like Facebook and Twitter use a GIF Player, a buttton that make the GIF play in similar way of videos. There are some jquery libraries that reproduce this feature and are simples to use, here is a example: http://rubentd.com/gifplayer/

**Comment by DonnaScriptTechs** [comment]
We can't use jquery with moo so we would need to find another solution if we were to do this. Thanks for the suggestion.

**Comment by Elshara** [comment]
Jquery is much faster so perhaps a dependency replacement could work
in such a way.

**Comment by leandrotavaresrocha** [comment]
It's weird that SE can't use JQuery since I saw several third party using it. SEAO and SES are two from the list that I know that include a JQuery script in their core.

Possibly there is some way to introduce this type of feature using mootools. This will make the websites more professional.

**Comment by DonnaScriptTechs** [comment]
It works with Jquery but a core developer said we would need to update to use Jquery in order to make that suggested thing work. I assume he said that because it may not be as efficient or work as well as it should in moo.

**Comment by Elshara** [comment]
Moo should just transfer to jquery and then it would work without a
problem I suspect.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#107

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
