### ISSUE TITLE
4.9.0 Photo Album module

### ISSUE THREAD

**Issue by SpiritWolfie** [SocialEngine/phpv4-issues#715]
Since I can't update to 4.9.1 to test this because of the syntex error we're getting... 

Go to Photo album, go to member levels, set it to public, Set it to no, Watch it error out, Fresh install 4.9, No plugins.

Get generic error

We're sorry!
We are currently experiencing some technical issues. Please try again or report this to your site administrator using the contact form.

Administrator: Please check the error log in your admin panel for more information regarding this error.

Error Code: 04b631

**Comment by DonnaScriptTechs** [comment]
I can't reproduce this with a fresh install. Please make sure the testing server you use is not nginx since SE doesn't support nginx.

**Comment by adira-g** [comment]
> Please make sure the testing server you use is not nginx since SE doesn't support nginx.

I am confused... what does this mean, SE doesn't support nginx? I am recently reading this here in several posts... What did I "wrong", that our SE installation is running on pure nginx? Or is this related to 4.9.1?

**Comment by DonnaScriptTechs** [comment]
It has never supported nginx but people can get it working on it. It's just not officially supported and our documents show to use Apache. We will work on improvements in future versions for nginx support.

**Comment by DonnaScriptTechs** [comment]
@adira-g are you using 4.9.0? If so, can you reproduce the error in this report? Just checking as we've no one else reporting this and it would be helpful to know if anyone else can reproduce it.

**Comment by adira-g** [comment]
Okay, thank you @DonnaScriptTechs 
Of course nginx is a complete different server setup and one needs some deeper understandings of server config, hence installing SE on nginx is not recommended for people with little server skills. However I wouldn't describe myself as an expert, but I learned enough by reading and googling to setup my server completely to nginx with SE running smoothly.

Regarding to the issue here: no, it's working perfect at my site

![screenshot 2017-04-28 14 56 29](https://cloud.githubusercontent.com/assets/27999622/25529559/f804c83a-2c22-11e7-9299-5bcb9de4ebc5.jpg)

**Comment by DonnaScriptTechs** [comment]
Thank you for testing @adira-g

**Comment by adira-g** [comment]
@SpiritWolfie did you check the error-log? What does it say?

**Comment by SpiritWolfie** [comment]
I will re-test this that we finally managed to get 4.9.1 updated and got the photo album updated as well when I wake up, 

We had to put the update in the manual way and then go though the install process vs using the package manager from the get-go...

I haven't slept yet and will retest this on 4.9.1 when I wake up and if this has been resolved in 4.9.1 I will close this myself :)

**Comment by DonnaScriptTechs** [comment]
Thanks @SpiritWolfie !

**Comment by Elshara** [comment]
Can't reproduce here.

**Comment by SpiritWolfie** [comment]
I can reproduce this on 4.9.0 on a older package of Photo Album, I can not reproduce this on the updated Photo Album on 4.9.1

This was a 'bug' it has been fixed. which is probably why it could not be reproduced.

I tend to keep old copy's of plugins as they get patched with the new copy's, for testing reasons and to confirm code changes/differentiation checks.

**Comment by Elshara** [comment]
Good to know. :)
