### ISSUE TITLE
Updating core files

### ISSUE THREAD

**Issue by SpiritWolfie** [SocialEngine/phpv4-issues#716]
We have installed a fresh copy of SE at 4.9 (once again)

4.9.1 got released and we have as per usual tried to update to it. (mind you once again, "EVERYTHING ELSE WORKS") I can't stress this enough....

I go to the admin panel and upload the 4.9.1 Zend and 4.9.1 Social engine update (not the fresh install package)

It uploads just fine gets to 100% and the text changes to "Please upload package" their is no next button etc..

Using the 'inspect menu' I see

![image](https://cloud.githubusercontent.com/assets/9712738/25514503/520f904e-2b92-11e7-8fef-c2a0ad50e17c.png)

Now I have once again 'tested' this on my live site and a fresh install site of 4.9.0 trying to update it

According to my server tech after he's done some digging into this a bit it seems this only happens with SE's core files, If I update the 4.9.1 Albums from my dashboard that works 'flawlessly' because according to my tech its not changing core files, Something to do with our secure server and the 'old way' SE handles its httpdocs or something is triggering all my issues

My server tech has agreed to dig into this a bit more tonight after dinner to get to the bottom of this, but he has confirmed it is without a doubt NOT a issue on our end and it is a something to do with the way the trigger daring the core updates happens, its not liking a secure setting of our box

I'll hopefully have more info to add so we can at least improve the issue where this happening or get a fix or something.

**Comment by DonnaScriptTechs** [comment]
Ask him to make sure mod_sec is disabled and you are not using nginx.

**Comment by DonnaScriptTechs** [comment]
Also, the zend upgrade is included in the main upgrade package. You don't need to do it separately.

**Comment by SpiritWolfie** [comment]
As I have repeatedly stated, we've followed the link you guys have sent us, To a T..... Not sure where the confusion lays here...

The link you guys so kindly keep linking me I have given my server tech multiple times, I have watched him personally go over our stuff and watched him install it on a freshly installed OS from scratch and watched him go though the list piece by piece >.>

Our server box is NOT running Nginx. It is running Apach as stated in your requirements >.<

Perhaps it might be best to include that info in the dashboard, to avoid confusion.

**Comment by DonnaScriptTechs** [comment]
Please see your image here https://github.com/SocialEngine/phpv4-issues/issues/661 :
![image](https://cloud.githubusercontent.com/assets/6908282/25527963/4952395a-2be9-11e7-92b1-d484561129a2.png)
which shows nginx. That is why I asked.

**Comment by SpiritWolfie** [comment]
![image](https://cloud.githubusercontent.com/assets/9712738/25528351/37948aae-2bd2-11e7-839d-a21f288a3f4b.png)

As I said at one point we tried both Nginx and Apacha. but we primary run Apacha, as seen here by Wappalzer

**Comment by DonnaScriptTechs** [comment]
For my server (local), I downloaded Mamp and installed it. I didn't change anything. I have now 7 installs of SE running. I tested with php 5.6.23 and php 7.1.0. 

For my live sites, I use a default server config at cazaratech. It isn't even set up for SE (not optimized) as I started on it with fox. I have a live demo that I upgraded with no issues. It's just an apache server with nothing special on it. 

For the upgrade, you only need to do the se core upgrade file and not the zend upgrade as that is included in the se core upgrade files. Perhaps try that in case the bigger zend file is timing out during the upgrade. That is something we will try to improve in case of servers with time out issues.

**Comment by SpiritWolfie** [comment]
Thanks for that info, it would be helpful if that was honestly listed in the dashboard as it was never very clear from what I've could see or read... (perhaps add a little note under 'resources' in the client area?

I don't think our server is timing out to be honest, we don't have time out issues with any of our other stuff and rarely have issues with our boxes, and if we do its normally resolved very quickly..

We've been digging into this all morning none stop and we've found some info that might be helpful but I am to tired to get into it right this moment.

**Comment by Elshara** [comment]
I can reproduce a similar error to package manager.
The funny thing is, it seems to work even though it throws a false error.
The uploader times out on the server but only for the actual upgrade
package. The Zend one extracts fine, but the upgrade package doesn't.
It throws an error on the uploader progress page stating this.
14.5 MB
social-engine-php-upgrade-4-x-4-9-1-4.9.1.tar
Extracting ...

Please wait until the upload finishes or while archives are extracted.
Then after 5 minutes, it shows the error.
Extract error: Bad response
This is because it fails to extract Zend archive. Everything else
extracts okay, but not zend.
How you confirm this is if you reload the page, you'll see what it was
able to extract. Sometimes the server times out when moving to the
next step.

**Comment by DonnaScriptTechs** [comment]
Are you able to upgrade without adding the zend update since it is included in the main 4.9.1 files? There is no need to do the zend separately. I did test this again with the zend file added as well and it worked fine. It just takes longer for the server to load and extract the files. It is possible there's a timeout happening with the process. Try just loading the main files and not the zend since it's not actually necessary to load.

**Comment by SpiritWolfie** [comment]
No, the only way we've been able to upgrade is by manually uploading.

**Comment by DonnaScriptTechs** [comment]
So even if you don't choose the zend upgrade package, just the base package is still not working and your server is timing out during the extraction? 

Do your server error logs show anything?

**Comment by SpiritWolfie** [comment]
We're not timing out, i'll ask my server tech if we see any log errors

I'll have him check daring his free time.

**Comment by SpiritWolfie** [comment]
He says we're just use manual upload its less of a hassle at this point.
