### ISSUE TITLE
Video plugin removes ability to embed Flowplayer.

### ISSUE THREAD

**Issue by cgcb** [SocialEngine/phpv4-issues#717]
What are the steps to reproduce this issue?
-------------------------------------------
1. Install Video Sharing plugin
2. Upload a video in FLV format.

What happens?
-------------
The upload complete successfully, but when trying to view the video, the video is not displayed, and the console reports a 404 for /externals/flowplayer/flashembed-1.0.1.pack.js.

What were you expecting to happen?
----------------------------------
I expect the video to be displayed, and the console to not report a 404 error for this file.

This is due to the removal of flashembed-1.0.1.pack.js in 4.8.10 according to the Flowplayer manifest.php file.

What versions of software are you using?
----------------------------------------

**SocialEngine PHP Version:**

Confirmed as missing in 4.8.13 and 4.9.1. I've not looked in other versions.

**Comment by DonnaScriptTechs** [comment]
I've just tested on my clone site running 4.9.1 and loaded the attached flv video. It worked for me. It took a little longer to process but it worked after a few minutes.


[SampleVideo_1080x720_1mb.flv.zip](https://github.com/SocialEngine/phpv4-issues/files/965022/SampleVideo_1080x720_1mb.flv.zip)

**Comment by DonnaScriptTechs** [comment]
On my settings, I have enabled html5, allow embedding of videos in case that helps. 

Please check error logs to see if you see any other issues.

**Comment by Elshara** [comment]
Interesting. Good to know.

**Comment by Elshara** [comment]
I didn't know flowplayer could support .flv file extension. Does it
only happen for that file type?

**Comment by DonnaScriptTechs** [comment]
As we have updated many things, perhaps you have a third party product using the old methods. I don't have any issues using the video plugin with the flv file I posted here. Please submit a ticket to our support so our team can check your site. If you don't have active support, you'll need to purchase it.
