### ISSUE TITLE
Missing translations in fields, group and user csv

### ISSUE THREAD

**Issue by Tomislav20** [SocialEngine/phpv4-issues#718]
What are the steps to reproduce this issue?
-------------------------------------------
There are 5 language errors in 3 .csv files: fields, groups, user. 4 language phrases don't have pairs and 1 doesn't read very well because of space. See the pictures below to reproduce and repair.

What happens?
-------------

![wow se fields](https://cloud.githubusercontent.com/assets/12753666/25555841/f0c5e922-2cf0-11e7-9da6-d72e13a28126.jpg)

![wow se group](https://cloud.githubusercontent.com/assets/12753666/25555842/0c661c06-2cf1-11e7-8488-043fb4b5f4dc.jpg)

![wow se user](https://cloud.githubusercontent.com/assets/12753666/25555843/0e5e6bda-2cf1-11e7-9a55-08766b010cbd.jpg)

![wow se user2](https://cloud.githubusercontent.com/assets/12753666/25555844/116785dc-2cf1-11e7-9d5b-6e537d730e55.jpg)

What were you expecting to happen?
----------------------------------
In fields insert ;"These extra questions appear when ""%1$s"" is selected for ""%2$s""." on line 63
In groups insert ;"Delete Group Category?" on line 364
In groups insert ;"Are you sure that you want to delete this category? It will not be recoverable after being deleted." on line 365
In user insert ;"Select the city closest to you that shares your same timezone." on line 71
In user remove the space on line 328       

Any other comments?
-------------------
Hoping to be repaired in next update, because these could be edited in less than 5minutes so all Socialengine users don't have mistakes in .csv files. 

What versions of software are you using?
----------------------------------------
Operating System: All affected
SocialEngine PHP Version: 4.9.0

**Comment by Elshara** [comment]
I didn't notice this until now. :)

**Comment by Tomislav20** [comment]
@Elshara I also didn't notice this until now, but this time checked every .csv file for missing columns.
These 5 phrases aren't much but loading would be little faster, and translating would be easier. ;)

**Comment by DonnaScriptTechs** [comment]
We've added this to our list to fix. As this tracker is closing, we'll close this now. For new bugs, please post at our [new community](https://community.socialengine.com/forums/).
