### ISSUE TITLE
Consistent Module Layout

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#72]
Social Engine doesn't have a consistent module layout. Titles exists in the same <h3>heading structure</h3> and needs to be updated. Module posts should be <h3>like this</h3> module titles should be <h2>like this</h2> and big titles like site name should be <h1>like this</h1> which makes it much easier for both google and users to browse through things. In the case of tab containers, if no title is present, use <h2>this</h2> at least if you want a title to show.

**Comment by shivani2910** [comment]
@Elshara Thanks for your feedback. We've noted it down to our features list for internal discussion.
