### ISSUE TITLE
Polls not editable even no answer has been given

### ISSUE THREAD

**Issue by Mthorganby** [SocialEngine/phpv4-issues#721]
SE PHP 4.91 - Polls core module

It is not possible to edit a Poll even when there is no answer is given.
There is no such option to set a general setting to allow a poll to be edited before there are any answers.

The only option is to delete the poll and create a new one, even if you just made a tiny spelling mistake. 

If there are answers given on the poll then it is fair enough not to change it.

OR an option should be added to publish the poll when you fully checked it. (standard unticked)

**Comment by gsf00001** [comment]
I second this FReq

**Comment by Elshara** [comment]
Me two. It's been a problem for awhile.

**Comment by DonnaScriptTechs** [comment]
https://github.com/SocialEngine/phpv4-issues/issues/480 this is already added to our list via that request for polls to be editable. :)

**Comment by Elshara** [comment]
Thanks for the update. Good to know it is being considered.

**Comment by DonnaScriptTechs** [comment]
Yes, we need to have them editable at least until there is a vote on them.

**Comment by Elshara** [comment]
Perhaps a setting to determine whether or not editing a poll should be
considered until a vote happens, or afterwords prior to one occurring.
Admins could decide how people should handle that. To be honest, it's
kind of like asking people who view a video, play a song or look at a
photo in an album, how their content should be edited if it already
was viewed?
