### ISSUE TITLE
Some CSS is missing from the Mobile module

### ISSUE THREAD

**Issue by Mthorganby** [SocialEngine/phpv4-issues#722]
PHP 4.91 core module Mobile
When you install it out the box, some css is missing.

On the "mobile browse page" lines `<li>`are missing the height.

```
.browse_menu>ul>li {
    display: block;
    border-bottom: 1px solid #d8dbe2;
    line-height: 60px !important;                 /*missing */
    font-size: 20px !important;                    /* optional, but looks better */
    font-weight: 700 !important;                 /* optional, but looks better */
}
```

**Comment by Elshara** [comment]
Yes it is missing.

**Comment by DonnaScriptTechs** [comment]
I'm not sure if it was done intentionally as that height on my iPhone 5c makes the list way too long with a lot of empty space. However, I'll leave this open for @Khushboo016 to see as I'm not a CSS expert.

**Comment by Mthorganby** [comment]
@DonnaScriptTechs try a lower line-height: 40px
I did line-height: 60px as I got fat fingers and i am not as advanced as you are...still using iPhone 4S latest iOS tho :)

**Comment by DonnaScriptTechs** [comment]
lol that was fun. :) I'll let Khushboo check this as she's got the CSS expertise. I don't know all of the various devices we might have to deal with and why it was done like it has been. Perhaps it is the best way for other devices to be able to view it and so we leave it for the clients to adjust as they wish (for fat fingers and well seasoned devices :) )

**Comment by Khushboo016** [comment]
Hi @Mthorganby, Thanks for the suggestion! We've checked this issue at our end and after adding the "line-height" attribute to the CSS code, the "Mobile Browse Page" looks better, so we are adding your suggestion as an enhancement.

Thanks & Regards!

**Comment by Mthorganby** [comment]
Hi @Khushboo016 thanks !!
Are you doing the CSS @Khushboo016 ?

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#108

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
