### ISSUE TITLE
Bug in announcement

### ISSUE THREAD

**Issue by Burno317** [SocialEngine/phpv4-issues#725]
Hello World,

I noticed thatwhen addign an annoucement any added style in bold or in color shows the some code at the beginning and at the end.

What are the steps to reproduce this issue?
1. Create an announcement in: admin/announcement/manage
2. add any text, and try for example putting it in bold or in color

What happens?
There is some coding at the beginning and at the end of the text.

What were you expecting to happen?
no visible coding

What versions of software are you using?: SEPHP

**Operating System:** Windows 7

**SocialEngine PHP Version:** SEPHP 491

Regards

**Comment by DonnaScriptTechs** [comment]
https://github.com/SocialEngine/phpv4-issues/issues/669 Thank you for your post. The announcement issue with TinyMCE is posted in the linked bug report. We'll get it fixed for our next release.

**Comment by Burno317** [comment]
Hi Donna,

Thank you for your fast response.

Have a great day.

**Comment by DonnaScriptTechs** [comment]
You're welcome. :) Hope you also have a great day.
