### ISSUE TITLE
Changing users 'user name' 

### ISSUE THREAD

**Issue by SpiritWolfie** [SocialEngine/phpv4-issues#726]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Go to a Users profile
2. …Admin settings
3. …Change their username

What happens?
-------------
… Their profile wont display

What were you expecting to happen?
----------------------------------
…For their profile to display

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
…From what I can see when you click on the users profile it keeps trying to go back to the old user-name vs the new, you have to manually type in the new username to be able to see their profile vs clicking.

What versions of software are you using?
----------------------------------------
**Operating System:** …

**SocialEngine PHP Version:** … 4.9.1

**Comment by SpiritWolfie** [comment]
I've noticed it doesn't update right away but after about 5-10 mins it starts working fine, It should update the moment the changes are made...

**Comment by Khushboo016** [comment]
Hi @SpiritWolfie, Thanks for bringing this issue in front of us! we've added this issue to our internal bug tracker and will fix the same soon.

Thanks & Regards!

**Comment by SpiritWolfie** [comment]
@Khushboo016 

Any reason to why you listed this as a bug only to remove the bug label o.0

**Comment by DonnaScriptTechs** [comment]
As user names are cached, did you test by clearing cache?

**Comment by DonnaScriptTechs** [comment]
Actually, I can't reproduce this other than in the blocks which has the cached display name (which I tested instead of username so now I will go test username).

**Comment by DonnaScriptTechs** [comment]
Ok tested with username and cannot reproduce any issue. The only thing we have is the url. You are currently on yoursite.com/profile/originalname before changing. The url you have in your address bar isn't going to change until you leave that page. I changed donnab to donnab1. My original url was mysite.com/profile/donnab and when I changed, I'm still on that page but if I go to members and find that same user, I can go to their profile by clicking their name and am on mysitelcom/profile/donnab1 so that part is working for me. 

Is there a specific area it is not working for you once you have navigated away from the old url?

**Comment by DonnaScriptTechs** [comment]
We're checking to see if we can improve this process so the url changes once the username changes. (issue in my comment above) 

Please let us know if that is not the issue you meant so we can ensure to check your issue specifically.

**Comment by SpiritWolfie** [comment]
@DonnaScriptTechs 

What happens on my end is if I go to the users profile, click the admin setting button in the bottom left, the field called "username" If I change said field to say ServerTechRandomJoe and save it, if I leave page and click on persons avatar image, it takes me to the "Old" profile address instead of the new, instead of it taking me to ServerTechRandomJoe it'll take me to RandomJoe which causes the page to say its not found.

After about 5-10 mins this fixes itself (probably due to caching) as far as I'm concerned, something like this should tell the system to update right then and there, regardless of caching.

**Comment by DonnaScriptTechs** [comment]
I'll try to reproduce it again.

**Comment by DonnaScriptTechs** [comment]
I am not able to reproduce this on a site with no third party plugins and default unedited theme. As for caching, things need to be cached in order to serve a faster site. All scripts I know of that are dynamic have caching or would be too slow.

 However, I'm not able to get any issue for this with development mode off either. I'll test more tomorrow and see if I can make it reproduce your issue.

**Comment by SpiritWolfie** [comment]
I'll retest this again, maybe it just glitched on my end, but yes I do have caching enabled.

**Comment by DonnaScriptTechs** [comment]
I've tried on another site and still can't reproduce the issue you mention.

**Comment by DonnaScriptTechs** [comment]
Were you able to reproduce this?

**Comment by SpiritWolfie** [comment]
Yes, but at this point I think its just taking longer to update it due to caching. It does update like after a few mins but something like that should be updated right on the spot vs being in a que.

**Comment by DonnaScriptTechs** [comment]
Are you clicking the user avatar in any place specific (such as a widget for online users, popular, etc)?

**Comment by SpiritWolfie** [comment]
No idea why I didn't get a notice you responded to this until now

to respond to question

I go to the users profile, click 'edit member profile' and make the changes in that, Hope that helps.

**Comment by DonnaScriptTechs** [comment]
Yes I know that as you said it before. I want to know where you are clicking the avatar after you change the settings. Above, you said that after you change the name, you can't go to the user's profile any more as it tries to go to the old profile. How are you trying to go to the user's profile after changing it - from an image in the feed, member browse, one of the user blocks on member home page, admin manage members, anyplace else instead? I've been trying to reproduce it and can't.

Here's what you said and why I'm asking for where you are clicking:

"If I change said field to say ServerTechRandomJoe and save it, if I leave page and click on persons avatar image"

I tried everyplace I could think of to click the user avatar but perhaps I missed one. 

Thanks!
