### ISSUE TITLE
Generic Menu Admin Title

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#728]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Go to layout editor in admin control panel.
2. … Add generic menu widget to a page.
3. … Click edit on the generic menu widget, choose the title if you want one, assign the appropriate menu you want, be it custom or otherwise, and then save changes.

What happens?
-------------
… The title of the menu you have chosen does not display in the layout editor if you assign one. Additionally, if you do not assign a title to the menu, and you place it in a tab container, along with any other widget, its language key is the default title.

What were you expecting to happen?
----------------------------------
… To be able to read the title of the widget in layout editor.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Generic menu should probably be renamed to custom menu for better use.

What versions of software are you using?
----------------------------------------
**Operating System:** … Linux web server. Windows 10 personal.

**SocialEngine PHP Version:** … 4.9.1p1

**Comment by DonnaScriptTechs** [comment]
Hello,

Thanks for reporting these issues.

For issue 1 - The title of the menu you have chosen does not display in the layout editor if you assign one.

A. This is how it is designed as it has no "Admin Title" and only has a "Title" which is for front end view. If you want to add an "Admin Title" to this, please add a separate feature request. Please only report one issue at a time per report from now on.

For issue 2 - If no title is assigned, the phrase shows as the title in a tabbed block.

A. I can see this issue and we should improve this so it shows the same in a tabbed block as it would in a normal block position as the language key does not show if no title is added for a normal block.

**Comment by DonnaScriptTechs** [comment]
I have changed this back as you added the other issue in a separate report. For issue 1, that would be a feature request. I will mark this as an enhancement.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#110

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
