### ISSUE TITLE
Widgets Placed In Tab Containers Must Contain Titles

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#729]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … Place random widgets in tab container fields in layout editor on a random page and save changes.
2. … When you view the page, look for the names of the tabs.
3. … Notice some widgets, if they aren't assigned titles, like core search, core menus, core logo, etc, display the language key instead.

What happens?
-------------
… Widgets which aren't assigned titles have language names users on the front end won't be able to understand.

What were you expecting to happen?
----------------------------------
… To assign titles to all widgets placed inside tab containers, or fix the bug where widgets which aren't assigned titles, don't have to pull language keys.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Would help a lot.

What versions of software are you using?
----------------------------------------
**Operating System:** … Linux web server. Windows 10 personal.

**SocialEngine PHP Version:** … 4.9.1p1

**Comment by DonnaScriptTechs** [comment]
Ok I didn't see this one as you had it in the other one. I'll go change the other one.

**Comment by DonnaScriptTechs** [comment]
We've added this to our list to fix . As this tracker is closing, we'll close this now. For new bugs, please post at our [new community](https://community.socialengine.com/forums/).
