### ISSUE TITLE
Tag Post Problem

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#73]
Recently, there is a problem with social engine where people who stay on the site longer than 5 minutes while trying to post say a blog or forum, are present with a token error. This is related to tags I believe and this should be fixed so that people do not think they are not allowed to post or there is a problem with the website, which there is not, but they do not know this.

**Comment by Anshuse** [comment]
Hi @Elshara , Thanks for reporting this issue! We have noted down this issue at our end for our internal team discussion to work on this in near future. Thanks!

**Comment by smazurov** [comment]
Fixed in [4.8.10](http://blog.socialengine.com/2016/01/20/socialengine-php-4-8-10-is-released/)
