### ISSUE TITLE
Music upload show error on file too large

### ISSUE THREAD

**Issue by GabryNet** [SocialEngine/phpv4-issues#730]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. …Go to demo.socialengine.com/music/create
2. …Upload a song bigger i think then 2M which is the standard limit
3. …You will receive the error 
{"viewer":{},"viewer_id":40,"status":false,"message":"Invalid upload or file too large"}

What happens?
-------------
…Is normal to receive an error when the maximum file allowed exceed but not coded like this and also in the front of the song name appears the letters  "fi"

![untitled](https://cloud.githubusercontent.com/assets/25679777/25773760/b0799934-3283-11e7-830b-1703115ff138.png)

What were you expecting to happen?
----------------------------------
…Have only the text error like "Invalid upload or file too large"

**Comment by GabryNet** [comment]
I don't know if i found the best title for this issue ... if someone has a better idea please change it !

**Comment by DonnaScriptTechs** [comment]
This might be resolved with this one https://github.com/SocialEngine/phpv4-issues/issues/539 but I'm checking.

**Comment by DonnaScriptTechs** [comment]
This will be fixed with the other linked bug is fixed as our resolution will encompass global uploads.
