### ISSUE TITLE
Rich Text Block not save link on image

### ISSUE THREAD

**Issue by GabryNet** [SocialEngine/phpv4-issues#731]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. …Go to Layout Editor
2. …Drag and "drop rich text block" on a new made page and insert an image
3. …Select the image and input a link on it thru the link button

What happens?
-------------
…After input the link and you press OK nothing happens ...is not saving and close the window.

What were you expecting to happen?
----------------------------------
…After press ok it has to save and close the window, and when you press the image on your website has to provide you the link from the image.

![untitled1](https://cloud.githubusercontent.com/assets/25679777/25779993/c95b738a-3320-11e7-8bcb-564dd9a4003a.png)

What versions of software are you using?
----------------------------------------
**Operating System:** …CENTOS 6.9 x86_64 virtuozzo – server  cPanel & WHM 64.0 (build 19) on PHP7

**SocialEngine PHP Version:** …4.9.1

**Comment by DonnaScriptTechs** [comment]
Thank you for your report. I've added it to our list to fix.

**Comment by DonnaScriptTechs** [comment]
We've added this to our list to fix . As this tracker is closing, we'll close this now. For new bugs, please post at our [new community](https://community.socialengine.com/forums/).
