### ISSUE TITLE
Post and comment detail page edit link is not working

### ISSUE THREAD

**Issue by kelltonravi** [SocialEngine/phpv4-issues#732]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. User1 comment on user2 posts after then a notification goes to user2 with post link.
2. Click on user2 Mini menu notification bar post link. It will redirect you on post details page.
3. Post detail page click on "Edit" link. It is not working.

What happens?
-------------
Individual post detail page edit link is not working. Once clicked on other action(e. g. like) it starts working but cancel link not works.

What were you expecting to happen?
----------------------------------
Edit link should work once user redirect to post detail page.

Any logs, error output, etc?
----------------------------

```
Paste Log Here
```

Any other comments?
-------------------
…

What versions of software are you using?
Social Engine 4.9.0
**Operating System:** Ubuntu

**SocialEngine PHP Version:** 5.6

**Comment by DonnaScriptTechs** [comment]
Thank you for your report. I've added it to our list to fix.

**Comment by kelltonravi** [comment]
As my production release is on 25th may 2017. Please suggest me whenever will you provide new release with this functionality.

**Comment by DonnaScriptTechs** [comment]
This is fixed for 4.9.2 when it is released. If you still have this issue after we release, please open a new bug report.
