### ISSUE TITLE
4.9.1 not working with php 7

### ISSUE THREAD

**Issue by maxx24** [SocialEngine/phpv4-issues#733]
Ever since I updated the version of php that I am using in my cpanel, I am experiencing some difficulties but only on certain computers. My website appears fine on one computer and my phone, but on another computer, I keep getting a message that you can find in the attached screenshots. The error code # changes every time I refresh the page.

So far, only one other person has experienced the same issue when visiting the site. I can see other people have been active on the site because they have posted. So I am not sure how many people this is affecting.

Myself and this other person have tried multiple browsers, same problem.

I updated the php prior to updating the version of socialengine I am using. When I first updated the php version, and before updating the socialengine, I noticed this problem. So I reverted the php back to the original version and the problem disappeared. I figured the problem would be resolved after I completed the socialengine upgrade, but it has not.

When I contacted my host, their response was:
_I have noticed the same issue as from your screenshot, however with different ID number. Thus, I have checked the SocialEngine main.log file for the ID, which appear on my end and I have noticed the following entry:
Error: Call to a member function getDecorator() on null in /home/mycoachb/public_html/application/modules/Honeypot/Form/Signup/Account.php:112_

![screen shot 2017-05-08 at 5 46 40 pm](https://cloud.githubusercontent.com/assets/12504720/25858948/1ada423c-34ab-11e7-99a3-547a9c977c8c.png)
![screen shot 2017-05-08 at 5 59 57 pm](https://cloud.githubusercontent.com/assets/12504720/25858947/1aae6518-34ab-11e7-9273-b5f9865d8e19.png)

**Comment by DonnaScriptTechs** [comment]
Do you have a third party product named "Honeypot" as the error you show above is coming from that. You would want to check with third party developers of the products you use before upgrading or before upgrading the PHP version as their products might not be updated yet.
