### ISSUE TITLE
Recent activity privacy missing phrase

### ISSUE THREAD

**Issue by GabryNet** [SocialEngine/phpv4-issues#735]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. …Go to Profile settings (My settings) and access Privacy page
2. …Scroll down to Recent Activity Privacy and you will see instead of the phrase  ...   {item:$subject} commented on {item:$owner}'s profile: {body:$body}

What were you expecting to happen?
----------------------------------
…It should be a phrase like " Comments on your profile "

This issue was tested also on official SE demo.

**SocialEngine PHP Version:** …4.9.1

![untitled1](https://cloud.githubusercontent.com/assets/25679777/26007177/afe24fa0-373f-11e7-985e-8bf333e42d58.png)

**Comment by DonnaScriptTechs** [comment]
Hi,

Thanks for your report. We've got this in our list to fix.

**Comment by gustavo40** [comment]
Hello because they do not give priority to those who have socialengine of pay, because it does not return the advanced comment box, would be great, since many people accustom, upload images using html code

**Comment by DonnaScriptTechs** [comment]
I'm not sure what you mean. Is your comment regarding this issue with these phrases?

**Comment by DonnaScriptTechs** [comment]
This is fixed for our 4.9.3 version when we release it.
