### ISSUE TITLE
Blocking countries from accessing the site except one

### ISSUE THREAD

**Issue by Mthorganby** [SocialEngine/phpv4-issues#736]
SE PHP 4.9.1

What and how is the best way to block entire countries but one?
I just want the UK only to have access to the site. 
Loads of so well called "companies" from middle Europe to Russia to China and Japan creating fake profiles and are writing spam in the forums and blogs.

The only way to get round it is start charging customers which I don't want.
I can not ban: *.gmail.* or *.hotmail.* as real users use them.

Is there a script or a setting(s) you can stop countries from accessing the site?

**Comment by DonnaScriptTechs** [comment]
The github issue tracker is only for bugs or feature requests. Please ask questions at our community.
