### ISSUE TITLE
CSS issue in private chat using Firefox

### ISSUE THREAD

**Issue by adira-g** [SocialEngine/phpv4-issues#737]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … use firefox browser
2. … start chatting to a friend
3. …

What happens?
-------------
… your text is partial hidden

What were you expecting to happen?
----------------------------------
… text should be completely visible

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```
![screenshot 2017-05-15 18 14 04](https://cloud.githubusercontent.com/assets/27999622/26067380/5580656c-399a-11e7-90eb-a10f21fe6693.jpg)

Any other comments?
-------------------
…
it appears on the SE demo site as well.

What versions of software are you using?
----------------------------------------
**Operating System:** …

**SocialEngine PHP Version:** 4.9.1

**Comment by DonnaScriptTechs** [comment]
Thank you for your report. I've added it to our list to fix.

**Comment by DonnaScriptTechs** [comment]
We've added this to our list to fix. As this tracker is closing, we'll close this now. For new bugs, please post at our [new community](https://community.socialengine.com/forums/).
