### ISSUE TITLE
Chat disappears when using the column width modifier widget

### ISSUE THREAD

**Issue by adira-g** [SocialEngine/phpv4-issues#739]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. …place the "column width modify" widget in layout editor somewhere (i.e. member browse page)
2. …open the page in frontend
3. …check the chat bar "online friends"

What happens?
-------------
…no friends appear online, eventually open chat windows disappear

What were you expecting to happen?
----------------------------------
…chat appears with friends online and all open chat windows stay open

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** …

**SocialEngine PHP Version:** …4.9.1

**Comment by DonnaScriptTechs** [comment]
I'm not able to reproduce this. I'm testing on chrome and firefox. I have set the width of the right column in member browse to 300 px. 

I then opened chat and see I have one friend online so I click to chat. My chat window stays open when browsing throughout the site, including on the member browse page. 

Is there something I've not done correctly in my testing? I will say I'm using 4.9.2 and 4.9.1 to test.

**Comment by adira-g** [comment]
Thank you @DonnaScriptTechs for checking. 

You did test correctly! With the same steps on my installation the chat with friends disappears and it shoes 0 friends online. I will check again on other pages and with 4.9.2 when it is released.

I will then eventually re-open this issue.

**Comment by DonnaScriptTechs** [comment]
Thank you!

**Comment by adira-g** [comment]
It happens on all my browsers (Safari, Firefox, Opera) and on other pages as well. For now I can't use the widget. However, I will wait for 4.9.2 and re-open it, if I will still face this issue.
