### ISSUE TITLE
Menu Limits

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#74]
We need the ability to customize what default items are in menus. We should be able to drag items from one menu to another, by simply adding the ability to have a menu by column page in which we select which menus we want to edit then they appear as a column. From there, we should be able to edit properties such as whether or not this is available to signed out users, available at all by simply removing it or can be added as a drop down or sub tab.

**Comment by shivani2910** [comment]
@Elshara As I've mentioned in a similar issue, you can go for 3rd party Advanced Menu system for such features. Thanks
