### ISSUE TITLE
SocialEngine PHP 4.9.1p4 issue with ELB config.. .

### ISSUE THREAD

**Issue by jskybeal** [SocialEngine/phpv4-issues#740]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

The Route 53 A Record for our root domain, giggate.us, points to a CloudFront Distribution where we have attached an AWS SSL Certificate to load the site in the HTTPS secure environment, and the site works fine at this point.

Another Route 53 A Record, CNAME origin.giggate.us (same name established under the CloudFront Distributions origins tab), points to an Elastic Load Balancer (ELB). The problem is here. 

Once I placed the Social Engine PHP 4.9 website in maintenance mode, and attempted to access the site by entering the access code (browsers Chrome, IE, Firefox), I received HTTP Error 503. To resolve this error, I changed the Route 53 A Record, CNAME origin.giggate.us, to point or route traffic to the value of IP. The site loaded in maintenance mode with 
value of IP, but not with ELB.

Question: Is there any explanation on why SocialEngine PHP 4.9 malfunctions with the ELB configuration.  Routing to the ELB also created a problem with downloading the latest 4.9.1p4.  The download kept asking for a username and password or the website, and would not accept the credentials when entered.  Once I removed the ELB config, the download worked.  

Our SEAO Tech Team has indicated that ELB should work with the SE PHP site and referred us to github.  

Thanks much for your direction on this.

-- J-Sky

**Comment by DonnaScriptTechs** [comment]
I talked to one of our core developers and he said this is not a bug but a configuration issue with your settings. You could post for tips from clients in our https://community.onsocialengine.com for free assistance or contact our support for basic tips but we don't assist in server setup so our tips would not include assisting in that, if you have paid support.
