### ISSUE TITLE
Link in admin panel opens inside the smoothbox

### ISSUE THREAD

**Issue by adira-g** [SocialEngine/phpv4-issues#741]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. …if doesn't exist: create a network and add a user to the network
2. …go to the network settings in admin panel
3. …click on member count
4. it opens a smoothbox -> click on the members name

What happens?
-------------
…the profile of the member opens inside the smoothbox

What were you expecting to happen?
----------------------------------
…it should open in a new tab

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** …

**SocialEngine PHP Version:** 4.9.1

**Comment by DonnaScriptTechs** [comment]
Thank you for posting this. We've added it to our list to fix.

**Comment by adira-g** [comment]
You're welcome. This is nothing serious and most people wouldn't even notice. However, I am happy to help – even with little things – to improve SE! Thank you very much for your good job!

**Comment by DonnaScriptTechs** [comment]
We appreciate the help a great deal! Thank you for the good job you do as well to support us. :) It makes a big difference when people contribute.

**Comment by DonnaScriptTechs** [comment]
We've added this to our list to fix . As this tracker is closing, we'll close this now. For new bugs, please post at our [new community](https://community.socialengine.com/forums/).
