### ISSUE TITLE
Google PageSpeed Optimization

### ISSUE THREAD

**Issue by SocialDancing** [SocialEngine/phpv4-issues#742]
What are the steps to reproduce this issue?
-------------------------------------------
1. Go to Google PageSpeed Test 
https://developers.google.com/speed/pagespeed/insights/?hl=en&url=https%3A%2F%2Fdemo.socialengine.com

What happens?
-------------
Google takes seriously PageSpeed when showing Search Engine results.
Having a 74/100 on Mobile and 72/100 on Desktop is a score that needs to improve.
By making this changes, all the Social Engine will get a speed and SEO boost.

**Comment by DonnaScriptTechs** [comment]
Hi! Thank you for posting this improvement request. Please post this in our [feature section](https://github.com/SocialEngine/phpv4-feature-requests) as this section is only for bugs.

**Comment by SocialDancing** [comment]
Good. I though to put it in the Feature Section too, but your support agent told me to put it here. 
That's why I did it this way!

**Comment by DonnaScriptTechs** [comment]
I think our agent didn't realize we have the feature section open already. Sorry for the confusion.
