### ISSUE TITLE
jsbin errors

### ISSUE THREAD

**Issue by SpiritWolfie** [SocialEngine/phpv4-issues#743]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. …Have users post allot of youtube links
2. …Right click a empty spot on your website and go to inspect then console
3. … See error - Uncaught TypeError: Cannot read property 'prototype' of undefined
    at Object.g.p (base.js:30)
    at remote.js:79
    at remote.js:163
g.p @ base.js:30
(anonymous) @ remote.js:79
(anonymous) @ remote.js:163
base.js:30 Uncaught TypeError: Cannot read property 'prototype' of undefined
    at Object.g.p (base.js:30)
    at remote.js:79
    at remote.js:163
g.p @ base.js:30
(anonymous) @ remote.js:79
(anonymous) @ remote.js:163

What happens?
-------------
… You are spammed with a error 
Uncaught TypeError: Cannot read property 'prototype' of undefined
    at Object.g.p (base.js:30)
    at remote.js:79
    at remote.js:163
g.p @ base.js:30
(anonymous) @ remote.js:79
(anonymous) @ remote.js:163
base.js:30 Uncaught TypeError: Cannot read property 'prototype' of undefined
    at Object.g.p (base.js:30)
    at remote.js:79
    at remote.js:163
g.p @ base.js:30
(anonymous) @ remote.js:79
(anonymous) @ remote.js:163

What were you expecting to happen?
----------------------------------
…To not be spammed with this undefined error.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
… Here's a video of it in action

https://youtu.be/RCFWKN0BBcc

What versions of software are you using?
----------------------------------------
**Operating System:** …

**SocialEngine PHP Version:** …
4.9.2

**Comment by DonnaScriptTechs** [comment]
What browser is that please? I don't have that in chrome or firefox, the error I mean. I tried the demo and my local. I don't have a ton of videos but had some I had just loaded.

<img width="1207" alt="video chromefeed" src="https://cloud.githubusercontent.com/assets/6908282/26254904/1a4f03e2-3c86-11e7-9849-a83e5ea70331.png">

**Comment by DonnaScriptTechs** [comment]
Are you testing with plugins disabled? I mean third party and with default feed?

**Comment by SpiritWolfie** [comment]
Chrome, latest version, I already put in a support ticket with SEAO and they say they don't use that kind of code/don't mess with that sorta stuff

but ya theirs a ton of videos being linked on my website and it only started happening recently, I check inspect like daily, according to the video I placed it seems to be related jsbin which seems to be the thing SE uses to load youtube videos.

**Comment by DonnaScriptTechs** [comment]
I'll test more when I work again on Monday. I'll try some shares in the feed. I had tested with them in the video section and not loading via the status share. Perhaps that's how your members are loading them.

**Comment by SpiritWolfie** [comment]
Well after updating SEAO plugins to the latest they just pushed out, I no longer see this issue, So I'm closing it as thirdparty, sorry for the report.

**Comment by DonnaScriptTechs** [comment]
Thank you for letting us know and for closing this. It's always better to report something you find and close it than not report it and a possible bug goes without fixing. :)

Have a good weekend!
