### ISSUE TITLE
Zend_Form_Exception: Form elements auth_view and auth_comment have the same order (999)

### ISSUE THREAD

**Issue by coder4web** [SocialEngine/phpv4-issues#745]
There is Zend_Form_Exception exception if both hidden fields (see description below) has 1 value only.

What are the steps to reproduce this issue?
-------------------------------------------
1. In admin area go to /admin/video/settings/level and set both "Video Privacy" and "Video Comment Options" checkboxes to 1 value only each.
2. Go to "Video Create" page /videos/create to add new video

What happens?
-------------
Zend_Form_Exception: Form elements auth_view and auth_comment have the same order (999)

What were you expecting to happen?
----------------------------------
Form for new video creation.

Any logs, error output, etc?
----------------------------
Dump from log/main.log:
> Zend_Form_Exception: Form elements auth_view and auth_comment have the same order (999) - this would result in only the last added element to be rendered in /srv/sites/php/ac/ac/application/libraries/Zend/Form.php:3426
> Stack trace:
> #0 /srv/sites/php/ac/ac/application/libraries/Zend/Form.php(3322): Zend_Form->_sort()
> #1 /srv/sites/php/ac/ac/application/libraries/Zend/Form/Decorator/FormElements.php(84): Zend_Form->rewind()
> #2 /srv/sites/php/ac/ac/application/libraries/Zend/Form.php(2994): Zend_Form_Decorator_FormElements->render('')
> #3 /srv/sites/php/ac/ac/application/modules/Video/views/scripts/index/create.tpl(215): Zend_Form->render(Object(Zend_View))
> #4 /srv/sites/php/ac/ac/application/libraries/Zend/View.php(157): include('/srv/sites/php/...')
> #5 /srv/sites/php/ac/ac/application/libraries/Zend/View/Abstract.php(888): Zend_View->_run('/srv/sites/php/...')
> #6 /srv/sites/php/ac/ac/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(912): Zend_View_Abstract->render()
> #7 /srv/sites/php/ac/ac/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(933): Zend_Controller_Action_Helper_ViewRenderer->renderScript('index/create.tp...', NULL)
> #8 /srv/sites/php/ac/ac/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(972): Zend_Controller_Action_Helper_ViewRenderer->render()
> #9 /srv/sites/php/ac/ac/application/libraries/Zend/Controller/Action/HelperBroker.php(277): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
> #10 /srv/sites/php/ac/ac/application/libraries/Zend/Controller/Action.php(527): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
> #11 /srv/sites/php/ac/ac/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('createAction')
> #12 /srv/sites/php/ac/ac/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
> #13 /srv/sites/php/ac/ac/application/modules/Core/Bootstrap.php(85): Zend_Controller_Front->dispatch()
> #14 /srv/sites/php/ac/ac/application/libraries/Engine/Application.php(160): Core_Bootstrap->run()
> #15 /srv/sites/php/ac/ac/application/index.php(219): Engine_Application->run()
> #16 /srv/sites/php/ac/se4_ac/index.php(11): include('/srv/sites/php/...')
> #17 {main}

What versions of software are you using?
----------------------------------------
**Operating System:** Doesn't matter.

**SocialEngine PHP Version:** Up to SE 4.9.2

**Comment by DonnaScriptTechs** [comment]
Thank you for your report. We've added it to our list to fix.

**Comment by DonnaScriptTechs** [comment]
We've got this fixed for 4.9.3 when it's released. If you need the fix sooner, please contact our support and we can patch it for you but you will need an active support plan if you don't have one.
