### ISSUE TITLE
Invite causes error for invited people in sign up process

### ISSUE THREAD

**Issue by adira-g** [SocialEngine/phpv4-issues#746]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. …invite someone with the invite feature (signup setting: without invite code)
2. …create an account with the email address of the invited person
3. …

What happens?
-------------
…system replies with an error; error log has an entry "duplicate email"

What were you expecting to happen?
----------------------------------
…sign-up without error

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
2017-05-21T23:01:19+00:00 CRIT (2): 
Error Code: 4e2a95
exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Duplicate entry 'my@email.com' for key 'EMAIL'' in /etc/nginx/html/example.com/application/libraries/Zend/Db/Statement/Mysqli.php:214
Stack trace:
#0 /etc/nginx/html/example.com/application/libraries/Zend/Db/Statement.php(303): Zend_Db_Statement_Mysqli->_execute(Array)
#1 /etc/nginx/html/example.com/application/libraries/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 /etc/nginx/html/example.com/application/libraries/Zend/Db/Adapter/Abstract.php(576): Zend_Db_Adapter_Abstract->query('INSERT INTO `en...', Array)
#3 /etc/nginx/html/example.com/application/libraries/Zend/Db/Table/Abstract.php(1076): Zend_Db_Adapter_Abstract->insert('engine4_users', Array)
#4 /etc/nginx/html/example.com/application/libraries/Engine/Db/Table.php(149): Zend_Db_Table_Abstract->insert(Array)
#5 /etc/nginx/html/example.com/application/libraries/Zend/Db/Table/Row/Abstract.php(467): Engine_Db_Table->insert(Array)
#6 /etc/nginx/html/example.com/application/libraries/Zend/Db/Table/Row/Abstract.php(438): Zend_Db_Table_Row_Abstract->_doInsert()
#7 /etc/nginx/html/example.com/application/modules/Core/Model/DbTable/Membership.php(236): Zend_Db_Table_Row_Abstract->save()
#8 /etc/nginx/html/example.com/application/modules/User/Model/DbTable/Membership.php(99): Core_Model_DbTable_Membership->setResourceApproved(Object(User_Model_User), Object(User_Model_User))
#9 [internal function]: User_Model_DbTable_Membership->setUserApproved(Object(User_Model_User), Object(User_Model_User))
#10 /etc/nginx/html/example.com/application/libraries/Engine/ProxyObject.php(65): ReflectionMethod->invokeArgs(Object(User_Model_DbTable_Membership), Array)
#11 /etc/nginx/html/example.com/application/modules/Invite/Plugin/Signup.php(100): Engine_ProxyObject->__call('setUserApproved', Array)
#12 /etc/nginx/html/example.com/application/modules/Invite/Plugin/Signup.php(100): Engine_ProxyObject->setUserApproved(Object(User_Model_User))
#13 /etc/nginx/html/example.com/application/libraries/Engine/Hooks/Dispatcher.php(224): Invite_Plugin_Signup->onUserCreateAfter(Object(Engine_Hooks_Event))
#14 /etc/nginx/html/example.com/application/modules/Core/Model/Item/Abstract.php(504): Engine_Hooks_Dispatcher->callEvent('onUserCreateAft...', Object(User_Model_User))
#15 /etc/nginx/html/example.com/application/modules/User/Model/User.php(319): Core_Model_Item_Abstract->_postInsert()
#16 /etc/nginx/html/example.com/application/libraries/Zend/Db/Table/Row/Abstract.php(492): User_Model_User->_postInsert()
#17 /etc/nginx/html/example.com/application/libraries/Zend/Db/Table/Row/Abstract.php(438): Zend_Db_Table_Row_Abstract->_doInsert()
#18 /etc/nginx/html/example.com/application/modules/User/Plugin/Signup/Account.php(154): Zend_Db_Table_Row_Abstract->save()
#19 /etc/nginx/html/example.com/application/modules/Core/Controller/Action/Helper/FormSequence.php(193): User_Plugin_Signup_Account->onProcess()
#20 /etc/nginx/html/example.com/application/modules/Core/Controller/Action/Helper/FormSequence.php(45): Core_Controller_Action_Helper_FormSequence->doProcess()
#21 [internal function]: Core_Controller_Action_Helper_FormSequence->direct()
#22 /etc/nginx/html/example.com/application/libraries/Zend/Controller/Action/HelperBroker.php(328): call_user_func_array(Array, Array)
#23 /etc/nginx/html/example.com/application/modules/User/controllers/SignupController.php(51): Zend_Controller_Action_HelperBroker->__call('formSequence', Array)
#24 /etc/nginx/html/example.com/application/modules/User/controllers/SignupController.php(51): Zend_Controller_Action_HelperBroker->formSequence()
#25 /etc/nginx/html/example.com/application/libraries/Zend/Controller/Action.php(516): User_SignupController->indexAction()
#26 /etc/nginx/html/example.com/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('indexAction')
#27 /etc/nginx/html/example.com/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#28 /etc/nginx/html/example.com/application/modules/Core/Bootstrap.php(84): Zend_Controller_Front->dispatch()
#29 /etc/nginx/html/example.com/application/libraries/Engine/Application.php(160): Core_Bootstrap->run()
#30 /etc/nginx/html/example.com/application/index.php(219): Engine_Application->run()
#31 /etc/nginx/html/example.com/index.php(24): include('/etc/nginx/html...')
#32 {main}
```

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** …Debian jessie php 5.6 nginx https

**SocialEngine PHP Version:** …SE 4.9.2

**Comment by DonnaScriptTechs** [comment]
I can't reproduce this but I'm not clear on the setting you chose for the invites as the wording confused me a tad. Would you please share a screenshot of the setting you chose? :) Thank you!

**Comment by adira-g** [comment]
Of course, here are the settings:

![screenshot 2017-05-22 15 49 18](https://cloud.githubusercontent.com/assets/27999622/26311958/54db31de-3f06-11e7-8ace-950456a42f46.jpg)

![screenshot 2017-05-22 15 49 07](https://cloud.githubusercontent.com/assets/27999622/26311963/5a5682da-3f06-11e7-9747-6ed6dc4ef391.jpg)

**Comment by DonnaScriptTechs** [comment]
I tried like that but forgot to enable https. I'll try with that enabled.

**Comment by DonnaScriptTechs** [comment]
I am not able to reproduce this on our testing site using https. You may need to have our support look at your site if you have a support plan active.

**Comment by adira-g** [comment]
Thank you @DonnaScriptTechs!

You can complete the sign-up process and a friend request is automatically sent, right? (as expected)

It seems I will have to dive a little deeper into it, to get more information. Eventually I will come back to your support, if it won't work out. For now I have disabled the invite feature.

**Comment by DonnaScriptTechs** [comment]
I will test again with the friend request checked. I think I missed that part.

**Comment by adira-g** [comment]
Okay, thank you, but I guess the issue must be something else. I just want to know, if you can successful sign up with the same email, the invite message was sent to. The primary key in the db- table "users" increases with every try to sign up, but there is no new users added. If I delete the row from the table "invite_invites", sign up is possible without issues.

**Comment by DonnaScriptTechs** [comment]
I am able to sign up with the email that the invite was sent to. After sign up, I get an email that I have a friend request and I also get a verification email. Using the verification email, after I verify the email, I can log in with that user and accept the friend request.

**Comment by adira-g** [comment]
Thank you very much Donna. It's something on my installation then. I have nginx running and I have secured the server, I am also using modified code, so there are many things that could cause this error.

**Comment by DonnaScriptTechs** [comment]
Not a problem! We appreciate you reporting things you find as it helps us to find issues when there are some. I'm sure you'll be very helpful when we add Nginx compatibility in a future version.

**Comment by adira-g** [comment]
I did exactly this: a complete fresh installation in a subfolder as sandbox / development site and indeed, it works without issue. So I cannot reproduce it on a fresh install either. But it works on Nginx, so that is good to know, it's not my server setup *phew*

I am closing this now.
