### ISSUE TITLE
formatting codes show as text in messages

### ISSUE THREAD

**Issue by BTessier** [SocialEngine/phpv4-issues#747]
What are the steps to reproduce this issue?
-------------------------------------------
1. Compose a message
2. use formatting in message 
3. using the Preview in TinyMCE, formatting is showing in the text as well as the resulting message sent to the user

What happens?
-------------
The message is sent with the formatting code showing up. 
What were you expecting to happen?
----------------------------------
to see the formatted text in the actual message, 

Any logs, error output, etc?
----------------------------

Paste Log Here
Screen capture with preview
![formatting in messages 3](https://cloud.githubusercontent.com/assets/23172530/26321950/f28355de-3ef6-11e7-82e2-cb391705990f.JPG)

Any other comments?
-------------------
Before 4.9.X, messages were sent formatted correctly.

What versions of software are you using?
----------------------------------------
**Operating System:** Windows 10 and Chrome as browser

**SocialEngine PHP Version:** 4.9.2

**Comment by Khushboo016** [comment]
Hi @BTessier, Thanks for bringing this issue in front of us! We've added this to our internal bug tracker and it will be fixed soon in near future releases.

Thanks & Regards!

**Comment by DonnaScriptTechs** [comment]
We've added this to our list to fix . As this tracker is closing, we'll close this now. For new bugs, please post at our [new community](https://community.socialengine.com/forums/).
