### ISSUE TITLE
OWN EVENT can not be deleted by admin - Permission Issue

### ISSUE THREAD

**Issue by Mthorganby** [SocialEngine/phpv4-issues#748]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. ... Login as admin
2. … Create a future event
3. … Go back to My Events
4. … Delete Event -> Error

What happens?
-------------
As admin you create an test event in the future say : 
start 2017-06-23 0:00 end 2017-06-23 17:00
Tick: People must be invited to RSVP for this event
All other settings "Everyone"
Save the event

Go to Event Menu again, goto My Events.
Try deleting the event with the link on the righthand side "Delete Event"

Now the error occurs:
• Private Page
• You do not have permission to view this private page.
• Go Back

It looks like you can not delete your own event in My Events, even as admin or owner of the event

----------------------------------
How to delete the event:
----------------------------------
Go into your created event's profile page
On the lefthand side from the event options. Click "Delete Event"
Result:
• Delete Event
• Are you sure you want to delete this event?
• [DELETE EVENT] or cancel

What versions of software are you using?
----------------------------------------
** SE PHP 4.9.2  - module-event 4.9.1

**Comment by DonnaScriptTechs** [comment]
Thank you for this report. I can confirm it and have added it to our list to fix.

**Comment by DonnaScriptTechs** [comment]
We've added this to our list to fix . As this tracker is closing, we'll close this now. For new bugs, please post at our [new community](https://community.socialengine.com/forums/).
