### ISSUE TITLE
How to get page info in code?

### ISSUE THREAD

**Issue by rkrathor** [SocialEngine/phpv4-issues#749]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. Create a page from admin panel using Layout editor.

What happens?
1- I just create a new page from admin panel.
2. Now when I checked the code , I didn't fine any source code for that 
3. If I have to add some extra text or something of have to write HTML for that.

What were you expecting to happen?
I should  a page to code in coding panel (where source code exist).

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
Screenshots attached for batter understanding.

What versions of software are you using?
----------------------------------------
**Operating System:** …Local system
**SocialEngine PHP Version:** 4.8.8

Screenshots
![code](https://cloud.githubusercontent.com/assets/10502380/26484731/5874365c-4211-11e7-931c-d0c3861ec8bf.png)
![new-page](https://cloud.githubusercontent.com/assets/10502380/26484730/5873b902-4211-11e7-9d4c-693f8ef4036f.png)

**Comment by DonnaScriptTechs** [comment]
Please use current version when posting bugs.

Please note our tutorial is here for making pages, http://support.socialengine.com/php/customer/en/portal/articles/1641056-creating-a-new-page?b_id=14386  and the tutorial for how widgets work for adding content to the page, http://support.socialengine.com/php/customer/en/portal/articles/1641082-admin-panel---layout-&gt;-layout-editor?b_id=14386 .  

The Github area is not for posting questions of how things work but for posting bugs when things don't work.

If you want a new feature, please post it in our feature tracker, https://github.com/SocialEngine/phpv4-feature-requests

**Comment by rkrathor** [comment]
Is it not a bug? I am not able to code. Its for every version.
If not sorry but I thought Its a big issue for every version of SE.

**Comment by DonnaScriptTechs** [comment]
Hi,

The html block widget is working fine in my tests so it doesn't seem a bug. Perhaps ask in our community if you need tips on creating pages. If you are trying to make a plugin, you can also ask in our expert community if you have an expert account.

**Comment by rkrathor** [comment]
I create a page and didn't find HTML block of that page.
that's why I asked here..
and for community, I am unable to login into community, It said please request an invitation to join our community.

**Comment by DonnaScriptTechs** [comment]
You might need an updated version if you don't see the html block in the layout editor. As for the community, you'll need to log into your client dashboard at https://socialengine.com and you can then log into the community.

**Comment by rkrathor** [comment]
![screenshot_2](https://cloud.githubusercontent.com/assets/10502380/26494449/6ae2d142-423c-11e7-8598-f7144c29e564.png)

**Comment by DonnaScriptTechs** [comment]
Whoops, I thought the redirect worked. We will get that fixed. https://www.socialengine.com/login

**Comment by rkrathor** [comment]
That is redirection problem I guess, .htaccess file have to be change for www and without www.
And thanks I am able to log into community.

**Comment by rkrathor** [comment]
![screenshot_2](https://cloud.githubusercontent.com/assets/10502380/26548266/f29a2ca6-4490-11e7-937c-1c4afa0209dc.png)
