### ISSUE TITLE
Content Permissions

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#75]
We need the ability to choose what content is visible to what permission group under member level settings, not under the general settings page. Similarly, we need the ability to generate content items specifically for pages with this same permission. It would be ideal if we could have duplicate modules for different user groups. A forum with its categories for people who are of a specific member level, then a forum with its categories for people who are of all levels, or any of the above not just for forums, but for any module.

**Comment by Elshara** [comment]
This could be done by introducing a user group permission system. We have this already but a user group would replace user levels which are already predefined options of what people can and cannot access.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#3

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
