### ISSUE TITLE
Uploading GIF's, long time or error on 4.9.2

### ISSUE THREAD

**Issue by GabryNet** [SocialEngine/phpv4-issues#750]
What are the steps to reproduce this issue?
-------------------------------------------
1. …Upload a GIF image thru Wall or Album plugin page
2. …
3. …

What happens?
-------------
…Upload takes a very long time for some GIF's around 30 sec.-3 mins . 
Sometimes some of the gif's are loading around 30 sec. , some of them are loading around 3 mins. , some of them just end in error saying Invalid Upload or Upload failed: timeout #0
I have test it on my website also on SE demo and the same problem on both.
When i tested first time with 4.9.0 was working very good.
NOTE THAT IS NOT HAPPENING FOR ALL THE GIF'S

![gif](https://cloud.githubusercontent.com/assets/25679777/26526778/00ca3e86-4385-11e7-9340-1bd221499a67.png)

What were you expecting to happen?
----------------------------------
…Upload success

What versions of software are you using?
----------------------------------------
**Operating System:** …CENTOS 6.9 x86_64 virtuozzo – server  cPanel & WHM 64.0 (build 24)

**SocialEngine PHP Version:** …4.9.2

**Comment by Khushboo016** [comment]
Hi @GabryNet, Please let us know if the .gif image with which this issue can be reproduced on the demo site of SocialEngine is of size less than 2M.

Thanks!

**Comment by GabryNet** [comment]
Hi @Khushboo016  ..yes you are right i forgot the limit on demo of 2Mb ... it works with less then 2 Mb ... maybe on my website can be the 3 mins. loading because i am also using SEAO Adv. Albums . Sorry for disturbing , thank you for your reply and please close this "issue" .
Have a good day !

**Comment by DonnaScriptTechs** [comment]
No problem :) Thank you for reporting issues when you find them. Even if they are found not to be issues, it's better to report if you think it's an issue.
