### ISSUE TITLE
Wrong email notification message when tagged in a photo

### ISSUE THREAD

**Issue by angelinfante** [SocialEngine/phpv4-issues#751]
What are the steps to reproduce this issue?
-------------------------------------------
The test has been done in a language different from english, that is the case I found. Don't know if it happens also in english.

1. Tag a member in a photo

What happens?
-------------
1. The email message says "Array" instead of photo.

> Te han etiquetado en Array. Haz clic en el siguiente enlace para verlo:
> 
> http://orientalisimo.com/albums/photos/view/748/3130

What were you expecting to happen?
----------------------------------
The notification in the website is correct but the email not, it should contain the name of the object type instead of "Array"

What versions of software are you using?
----------------------------------------
**Operating System:** Amazon Linux

**SocialEngine PHP Version:** 4.9.2p1

**Comment by DonnaScriptTechs** [comment]
Thank you for submitting this issue. I can reproduce it and added it in our list to fix.

**Comment by DonnaScriptTechs** [comment]
We've added this to our list to fix . As this tracker is closing, we'll close this now. For new bugs, please post at our [new community](https://community.socialengine.com/forums/).
