### ISSUE TITLE
User Profile - Settings - Privacy missing texts

### ISSUE THREAD

**Issue by rayaz88** [SocialEngine/phpv4-issues#752]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. Reuploaded language packs
2. Flushed Cache
3. Checked settings

What happens?
-------------
Producing this error in user privacy settings:
{item:$subject} commented on {item:$owner}'s profile: {body:$body}

What were you expecting to happen?
----------------------------------
To get fixed after reuploading language pack

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

{item:$subject} commented on {item:$owner}'s profile: {body:$body}

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** …

**SocialEngine PHP Version:** …
4.9.2

**Comment by DonnaScriptTechs** [comment]
Thank you for posting. We had already added this to our list to fix.

**Comment by DonnaScriptTechs** [comment]
This is fixed for our 4.9.3 version when we release it.
