### ISSUE TITLE
Main Photo Issue Delete to Critical Flaw

### ISSUE THREAD

**Issue by dreamgeekcoder** [SocialEngine/phpv4-issues#753]
What are the steps to reproduce this issue?
-------------------------------------------
1. …Upload more than one main user photo

What happens?
-------------
User is able to upload unlimited amount of photos to the server up to the "max upload" section.

A critical flaw will be displayed once the user passes the max uploaded space allowed for their user level

On very large sites this is a huge issue. Having a larger site means gigs of unseen and unused main photos left over on the server. With no way for the user to delete them.

What were you expecting to happen?
----------------------------------
…User should only be allowed to upload 1 photo if album photos plugin is not enabled. Previous main photos should be replaced and deleted or at minimum, the user should have a page that allows them to delete the previous uploaded main photos if the max file space for that user has been met. But since the user can only show one photo if album plugin is not there, these SHOULD be deleted and replace at each new upload.

**Comment by DonnaScriptTechs** [comment]
Marked a bug as we have no way to manage the image if the above scenario is tested. The error tells the member to delete their profile photos to manage space but gives them no way to manage the photos.

**Comment by DonnaScriptTechs** [comment]
We've added this to our list to fix. As this tracker is closing, we'll close this now. For new bugs, please post at our [new community](https://community.socialengine.com/forums/).
