### ISSUE TITLE
2checkout Gateway Error

### ISSUE THREAD

**Issue by Frankenfurt** [SocialEngine/phpv4-issues#757]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. …Create a 2checkout account, enter all api details.
2. …Enable 2checkout as a gateway on socialengine.  (At this point, 2checkout decided that my site did not qualify for their services and disabled my api.)
3. …Attempt to disable the 2checkout gateway on socialengine.  Receive an error API Error: [FORBIDDEN] Access denied. Account Closed.  Gateway is currently disabled.

What happens?
-------------
…We attempt to save the gateway as disabled.  We check the "no" box for "enabled"?  The error appears and will not disable the gateway.  If the gateway is not disabled, I cannot setup any paid packages from various plugins on my site.

What were you expecting to happen?
----------------------------------
…I expect the gateway to be disabled but it will not save.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

 API Error: [FORBIDDEN] Access denied. Account Closed.  Gateway is currently disabled.

```
Paste Log Here
```

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** …

**SocialEngine PHP Version:** …Most up to date.

**Comment by Khushboo016** [comment]
Hi @Frankenfurt, Yes, there has been found some issue with the disabling of 2Checkout in our core module, so, we have added this issue to our internal bug tracker and it'll be fixed soon in near future releases. But, if you want this issue to be fixed on your site now, so you can contact our support staff.

Thanks & Regards!

**Comment by DonnaScriptTechs** [comment]
This is fixed for our 4.9.3 version once we release it.
