### ISSUE TITLE
Video Thumbnails

### ISSUE THREAD

**Issue by ClubbinHeaven247** [SocialEngine/phpv4-issues#758]
Hi can someone tell me why my video thumbnails have stopped working for some reason since upgrading to 4.9.2

What happens?
I have blank video links with just a film reel on, it doesnt show the thumbnail of the videos as shown here
http://www.clubbinheaven247.com/videos

What were you expecting to happen?
----------------------------------
…

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
…

What versions of software are you using?
4.9.2
**Operating System:** …

**SocialEngine PHP Version:** …

**Comment by DonnaScriptTechs** [comment]
Hi,

Please contact our support and ask for Kyle. You can email us at support@socialengine.com so we can check the issue for you.

**Comment by DonnaScriptTechs** [comment]
I'm not able to reproduce this issue. It could be a site specific issue; upgrade issue; problem with a plugin that might not be updated or perhaps a folder permission issue. If you submitted a ticket, and have support, our technicians should be able to assist.

**Comment by DonnaScriptTechs** [comment]
We haven't been able to reproduce this. Were you able to contact support?
