### ISSUE TITLE
Pages Need Their Own Direct URL

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#76]
When a new page is added, it should have its own direct url rather than /pages/url.

**Comment by shivani2910** [comment]
@Elshara Could you please elaborate what kind of urls you want to have ?

**Comment by Elshara** [comment]
Urls that allow you to choose what base url either each page or the
pages module itself can be located. I'm not just talking pages, I'm
talking modules. What if someone wanted to create an about us page?
/pages/about-us doesn't seem ideal. Yoursite.com/about does. How about
members? Yoursite.com/members is cool, but if you wanted to change it
to yoursite.com/username, you'd have to go through /members url first.
I think it would give people more incentive to join if they had a
direct link to their profile page from the site home page.

**Comment by alimoosavi15** [comment]
This is technically not practical and since SocialEngine uses pretty URLs, SEO aspects are already covered and making such fundamental changes to simply make the URLs look cooler is not in priority for the development team.
