### ISSUE TITLE
Force users to flush their cache

### ISSUE THREAD

**Issue by poeticjustice** [SocialEngine/phpv4-issues#760]
Im official about to update live site after loads of testing.

One common thing that happened and seemed to happen on all staging servers was cache issues, loading up old data etc.

Even when i go into dev mode, flush the cache there, actual members still seem to see the issue, not everyone is savy enough to clear internet settings etc.

Is there a good way to force this, via htaccess or anything?

**Comment by DonnaScriptTechs** [comment]
Please ask questions at our community. The github is just for bugs with the script. Thank you!
