### ISSUE TITLE
Minor bug translation in chat plugin: the phrase "Toggle Notifications" can't be translated no matter what

### ISSUE THREAD

**Issue by Burno317** [SocialEngine/phpv4-issues#763]
Hello world, 

I came here to suggest two APIs but was not able the good section, so I am reporting a minor bug translation in chat plugin: the phrase "Toggle Notifications" can't be translated no matter what.

What are the steps to reproduce this issue?
-------------------------------------------
If you pass the mouse over on the footer chat bar the text will always remains in english.

In regards with API, as Social Networks are made also with images, it should be great to optimize them (in addtion of CDN), maybe you should consider implementing in SE the API of: https://kraken.io/ and https://tinypng.com/developers.

Have a great weekend.

Regards

What versions of software are you using?
----------------------------------------

**SocialEngine PHP Version:** 492p1

**Comment by Tomislav20** [comment]
Hi Burno317,

I was also trying to translate that phrase but couldn't find a way to do it.

Here is screenshot of bugged phrase.

![toggle notifications chat](https://user-images.githubusercontent.com/12753666/27234444-60b37442-52bd-11e7-806c-712ec1b3c147.jpg)

**Comment by DonnaScriptTechs** [comment]
Hi @Burno317 in regards to your feature request for images, please see our feature requests here https://github.com/SocialEngine/phpv4-feature-requests/issues and I think your request was submitted before already so you would want to search before submitting it.

In regards to the translation issue, we'll check it and see. Thank you for the report.

**Comment by DonnaScriptTechs** [comment]
We can reproduce the bug for the translation issue and have added it to our internal tracker to fix.

**Comment by Burno317** [comment]
Hello guys,

Thank you for your consideration and efforts about my humble request.

It seems to me that I reported it before but with the new version 492 the translation stopped working anymore.

Thank you again.

Regards

P.S. What about the image optimization? do you think it could be implemented any time soon?

**Comment by DonnaScriptTechs** [comment]
We've added this (the notification translation issue) to our list to fix and scheduled it for 4.9.3. As this tracker is closing, we'll close this now. For new bugs, please post at our [new community](https://community.socialengine.com/forums/).
