### ISSUE TITLE
Content URLs

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#77]
Instead of items having ids, they should have their own urls. If there is a conflict, ask the user to pick another url leaving the user to choose each content as its new url. For example, /music/rock-songs or /videos/some-other-title or /groups/social-engine-support etc. This should be available for all modules. It helps a lot with seo.

**Comment by shivani2910** [comment]
@Elshara Thanks for your suggestion. We're already having this feature added in our roadmap and will work on this in future.

**Comment by meetgerry** [comment]
Please make sure that they support Cyrillic characters or they are translated based on phonetics.

**Comment by smazurov** [comment]
consolidated this under #149 sorry for all close/open notifications.
