### ISSUE TITLE
Member Created Categories

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#79]
Instead of tags, members should be able to create and manage their own content categories for the things they post. The more they create, the more tags will reference this. For site categories, this will remain the same, however if members create their own categories, they can post in more than one category if the permission is there leaving tags open to a feature that just references existing post content through a built in site statistic that goes through all posts including comments to find relevant key words. Note, this is separate from sharing content items.

**Comment by shivani2910** [comment]
@Elshara, the current Tags system using which users can add tags during content creation is quite a simple and effective way. Adding User-driven categories will add complexity to the system. But if this is something you really need then you may get this customized on your installation. Thanks.

**Comment by meetgerry** [comment]
I happened to read something related to categories, I guess its high time for SE to have unlimited levels of sub-categories or atleast 4 levels down. SE being a social networking site, multiple levels of categories is a must to organize data. All your modules like Video, Groups, Polls, Music or anything you say does not have multiple level of categories.
