### ISSUE TITLE
Forum Improvements

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#80]
Currently forums are not designed well. You have categories and you have forums. Why not combine these two into forum lists people can subscribe to, or make their own while leaving the forums themselves one actual item. The idea with a forum is that it is category based. Having it user based means people can organize their topics into their own list leaving room for forums themselves to act as its own category. AS for forum categories itself, they will become user lists allowing participating members to be the basis for the list itself to actually grow. This way people get a much better statistic of what the forum is actually used for because it is a subscription based module, not just a place for people to post, that is what groups are. Group forums and event forums could be added into the main forum allowing people to choose what kind of forum they want. IF other modules could link to the forum, any post tagged elsewhere through out the site is not only based around a forum, but there is a forum that references a content per its tag, leaving the site more social and engaging.

**Comment by smazurov** [comment]
Since they're very different things conceptually, we have to keep them separate. This might change with next major version, but we have no immediate plans to do it currently.

**Comment by Elshara** [comment]
I know what you're getting at. This would be a very useful improvement
and would actually widen its original purpose. People could leave it
the same as it is or change it as they wish.
