### ISSUE TITLE
RSS

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#81]
Social Engine needs built in rss feeds of new items.

**Comment by smazurov** [comment]
There are 3rd party plugins that handle this, we currently don't have any plans to implement a built in solution.  Quite honestly, almost nobody requests this, so we much rather focus on bigger ticket items.

**Comment by Elshara** [comment]
Nobody's requested this?????
This is interesting!
I thought I could put an rss feed of site activity in another rss
page. I really really like the RSS widget and it would be much easier
to have built in feeds in this way forget third party feeds, rss site
content generation is one of my biggest dreams.
