### ISSUE TITLE
Module Display Improvements

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#82]
Currently social engine modules like newest members, popular groups, do not display a link to add more, or view my contributions, or view all. For accessibility reasons, they should, allowing people to add or view things right from where the block is positioned.

**Comment by smazurov** [comment]
Could you elaborate? Im not entirely certain on what you're trying to say.

**Comment by Elshara** [comment]
Sure.
When people put layout widgets on their home page or have specific
pages people put things like newest members, popular photos, new
events and so on, the way they display does not include a link to view
all. Now of course we have the link at the top in the menu, but it
would be nice for people to see what pages the updates come from so
they can view more of an item if they are scrolling past say 5 new
members on a page, a view more link or an invite link could appear at
the end of the widget. You know how in the rss feed widget there is a
link to view the feed? I'm saying the more link should be there for
all modules that display a feed with the ability to contribute or view
contributions.

**Comment by shivani2910** [comment]
Hi @Elshara,

Thanks for elaborating this. We've noted it down to our features list and forwarded it to our team for internal discussion.

Thanks

**Comment by DonnaScriptTechs** [comment]
This was implemented in 4.9.0 release.
