### ISSUE TITLE
Block Customization

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#83]
Currently there is no way for people to customize how a block looks in social engine. CSS may do the job, but it is very inconvenient. We need the ability to control the exact position or let it be fluid as an alternative of how blocks appear, and whether or not any content in them will auto scroll for new items if an exact number  isn't otherwise set.

**Comment by smazurov** [comment]
This is beyond the scope of our software at this time.

**Comment by Elshara** [comment]
Hmm. Dreamers can dream.
