### ISSUE TITLE
Editing Page Columns

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#84]
There should be a way for us to shape how things appear on pages. Columns are great, but they are a fixed with. Social Engine has an excellent page editor, however the ability to design how something is displayed would be an excellent way to position content per use.

**Comment by shivani2910** [comment]
@Elshara, not sure if that's what you're referring to but we already have a plan to provide a widget using which admin will be able to edit width of page columns. Thanks.

**Comment by Elshara** [comment]
God this ticket is years old. :)
Yes I see this will happen in 4.9 it's an interesting development. I
would've preferred the ability to make more than 3 columns but this
will do okay. I also wish we had horizontal as well as vertical
columns.
