### ISSUE TITLE
Replace Username With Display Name

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#86]
Usernames are a little hard to remember. It would be easier to cut that out entirely and instead put in a display name that can be changed from the edit settings page, not the profile page. Let that first name last name area be separate entirely or just replace it with other non id fields.

**Comment by shivani2910** [comment]
@Elshara username is something that has to be unique for any user so that we can use it in profile page url. We also use Display name (which gets formed by joining First and Last name entered by user) for display purposes.

**Comment by Elshara** [comment]
I understand. It's cool.
