### ISSUE TITLE
Featured Information On Members Page

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#87]
Remove the status field option to be replaced with profile information. Members should be able to have a customizable feature title referencing who they are, so a better members page can be truly customizable.

**Comment by shivani2910** [comment]
@Elshara There are multiple 3rd party Advanced Members plugins available in market which provide such features. You may want to check them: http://www.socialengine.com/customize/se4/plugins

Thanks

**Comment by Elshara** [comment]
Members still don't have an option of where their status messages are
displayed by default even if third party pages exist.
