### ISSUE TITLE
Chat Sucks

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#89]
The entire layout needs to be addressed better. People cannot see existing messages when they load a chat room. Sometimes chat rooms do not load at all. Instant Messages have a sound you cannot turn off. You can only chat with friends. You cannot moderate chat rooms. There is no customization options. People cannot create new chat rooms. When ever you refresh a page chat disappears. There is no way to save a conversation other than screen shot the page. Private Messages appear in a fixed location, you cannot combine the tabs between private messages and a chat room. You cannot block a user. You aren't able to open chat in a new window. No notifications of what others are chatting about. You cannot invite members to a chat room. Chat only appears on one page. Mobile users cannot chat or use the instant messenger at all unless you disable mobile plugin which you cannot from the package manager unless you type in manually the exact file name without the .tar extenssion you used to enable it and even then mobile doesn't uninstall properly, same goes for chat.

**Comment by smazurov** [comment]
Chat can be a business of itself.  We provide basic functionality but if you're looking for a better version of skype or slack, you will be disappointed.  Luckily its really easy to integrate your own and many have done so using 3rd party solutions.

**Comment by Elshara** [comment]
I know it's not a priority, but at least a working chat room would be
nice. The ability to see existing messages upon logging in to another
page even.
