### ISSUE TITLE
Feature Suggestion: Admin File & Media Manager Still Puts Files in Local System Storage

### ISSUE THREAD

**Issue by jonathanbloom** [SocialEngine/phpv4-issues#9]
I am on 4.8.7 and have my files hosted on the S3 Storage System with Local Storage deleted from my Storage Systems screen. The File & Media Manager in admin keeps uploading to local storage. Shouldn't it be uploading those to S3?

**Comment by jonathanbloom** [comment]
Whoops, it isn't a bug it seems. The KB shows that Storage System is for your user's files. Apologies, I thought it was a bug. Is there a place to submit Suggestions or Ideas like SE Cloud? This isn't a Support Issue.

**Comment by shivani2910** [comment]
Hi @jonathanbloom, 

Thanks for the suggestion. We'll forward your suggestion to our internal discussion tracker.
Please feel free to keep providing us your valuable feedback. This will help us improve.

Best Regards,
Shivani

**Comment by Elshara** [comment]
Great idea! Perhaps it would be useful to have storage place in both locations but have it by default served by cdn. That way if one location is down, it still exists on demand.

**Comment by DonnaScriptTechs** [comment]
This issue was moved to SocialEngine/phpv4-feature-requests#1

**Comment by DonnaScriptTechs** [comment]
In our efforts to streamline our processes for bug fixes and feature implementation, we are separating our issue tracker and feature request section. This has been moved to our feature area where you are subscribed automatically in order to get updates. Thank you for your contribution.
