### ISSUE TITLE
Customizable Post Information For All Content

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#90]
Social Engine has always had the ability to edit classified information and profile information extensively. The same should also be true for people creating new content such as groups, forum discussions, blogs, photos, music, videos and events. If this is done, this opens up much bigger avenues for people to post the information the site is built for, instead of just usually a title, description, a category and some keywords.

**Comment by shivani2910** [comment]
@Elshara Thanks for your feedback. That's something worth considering. We've added this to our features list. Thanks
