### ISSUE TITLE
Missing Widgets Cannot Be Removed From Page Layout

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#91]
IF you disable a plugin, which is impossible to do. You have to enter the exact url of the file you uploaded in the first place, it doesn't fully install. Page layouts don't get updated and the pages remain which cannot be deleted. They should be.

**Comment by shivani2910** [comment]
@Elshara, as we've mentioned in another issue that disabling a plugin in SocialEngine has never be a problem. If you're still having this issue, we suggest you to contact our support team along with the details of your installation to enable them look into it.

As far as removing the "Missing Widgets" is considered, you can simply drag them off the "Block Placement" area and click "Save Changes".
