### ISSUE TITLE
Package Manager Needs An Update

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#92]
Not all items have a disable link to remove them. If you install a plugin that badly effects your site, and you click on disable, it takes you to the wrong url of the plugin you want to disable. This is a serious bug.

**Comment by smazurov** [comment]
please provide more detail, we haven't had any reports of not being able to disable plugins.

**Comment by Elshara** [comment]
It's not that plugins cannot be disabled, its just that the only way
to do it is to use the url of the exact file you have uploaded to
disable it. The option doesn't appear on all products, and for third
party installations, if something needs to be removed, such as access
manager, friends inviter, updates, things like that, the actual
package manager doesn't reference when you click disable  the correct
url for the plugin. You have to browse to the exact file you uploaded
on your computer, then paste in the name of the file letter per letter
into the url box minus the .tar to disable a plugin. It won't
uninstall it, but it will prevent it from running.

**Comment by smazurov** [comment]
this isn't our experience, all 3rd party plugins are available and can be disabled in the plugin manager.  Feel free to open a support ticket or try installing SEPHP and install a single 3rd party plugin at a time, to find the offending one.
