### ISSUE TITLE
Customizing Member Notifications Page

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#93]
Members need an easier way to get to what is new if they have missed a lot of something they've subscribed to. Currently all member related items appear on the notification updates page. But members should be able to filter out what they want to look at for example requests, friend requests from group invites, group invites from event invites, event invites from content notifications, content notifications from subscribed content notifications, subscribed content notifications from recommendations. You get the picture.

**Comment by shivani2910** [comment]
@Elshara Thanks for your feedback. But we don't have any plan to implement such a feature. This is something that can easily be customized with the help of a developer. List of available 3rd party developers for SocialEngine PHP can be checked here: http://www.socialengine.com/customize/se4/developers

Thanks
