### ISSUE TITLE
More Settings For Groups And Events

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#94]
Groups need the ability to add blogs, music, videos and group based permissions. Groups also needs the ability to be notified when ever someone new posts in its activity feed. Same goes for events.

**Comment by shivani2910** [comment]
@Elshara, features that you've mentioned are available in 3rd party Advanced Groups and Events plugins. You may browse such modules here: http://www.socialengine.com/customize/se4/plugins
