### ISSUE TITLE
Member Admin Communications

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#95]
Currently only the super admin gets notified if someone reports a problem, signs up for the site, uses the contact form and no admins get notified if someone files an abuse report. Admins should be notified of the email and ip of who is reporting this, the link to the profile and the issue in the email. Every super admin should get these reports, not just the first one. Every report should contain email, ip, person with link to existing profile if available and full issue.

**Comment by shivani2910** [comment]
We've replied here https://github.com/SocialEngine/phpv4-issues/issues/121 for this.

**Comment by Elshara** [comment]
Okay thanks.
