### ISSUE TITLE
Email Updates

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#96]
When members receive emails, they never receive the text contained within the email about the update they have subscribed to. All they see is the link to view the update. Friend requests are really bad. It takes the user to their actual profile, if you have friend request approval turned on, which is the default, people don't realize they have to visit that persons profile just to click on add as friend to just be notified they have actually sent a friend request, then they must click confirm again to be presented with a question, are you sure you want to add as friend. Notifying people on what text is involved and how to respond to it per email is very important. It reduces the need to explain this in help files. Groups and events are real bad two. They never notify you at all if you are even invited, they just are there collecting dust. You cannot invite people on your friends list to events anyways, that's a bug. Back to the email topic, if someone posts a comment to something you didn't know you subscribed to, you don't even see the comment. For many reasons, emails need to be updated more, and stop with the "our social network administration" it looks bad. Admins don't even realize they have to change the default "to email address" of the site so it looks somewhat professional.

**Comment by smazurov** [comment]
All of those can be modified to your liking in Email Templates. If there is specific variables missing for desired functionality we'll consider adding them.

**Comment by Elshara** [comment]
I know. I'll probably end up doing that. The variable needed is
content text. So people know the text of the message rather than
always just being given a message saying sign in at this url to view
the post.

**Comment by jkwas** [comment]
I am having the exact same issue; it just looks so amateurish and unprofessional. People are just not interested and my members are always complaining about missed messages and emails because they can't even tell who or what the email notification is about. The email notifications desperately need a content text variable.

**Comment by Elshara** [comment]
Is there a content text variable as a description? Why isn't it
enabled by default if there is?
