### ISSUE TITLE
Search Block Cannot Be Moved In Mini Menu

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#97]
Search block cannot be moved in mini menu. I wish its location could be altered. IF you want to add things into the mini menu relating to member settings, you cannot, outside users will see the links.

**Comment by shivani2910** [comment]
@Elshara, regarding search bar, thanks for this suggestion. We've forwarded this one to our team for internal discussion and added it to our features list.

Regarding the ability to choose member level while adding a new menu item, there are multiple 3rd party Advanced Menu systems available for our software which can be used for such features.

Thanks

**Comment by Elshara** [comment]
:)
