### ISSUE TITLE
Footer Menu Appears On One Line

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#98]
The footer menu appears on one line and if you add a lot of links to it, it stretches across another. It doesn't even appear at the start of the new line, put the copyright above it or just let it be like every other menu. Speaking of copyright, you cannot seem to change what it says.

**Comment by smazurov** [comment]
You can change the copyright phrase in the Language Manager. On the links wrapping, you would need an unreasonable amount.  You can always add another menu to organize them better. Its also possible to fix this with CSS. As it stands, thats not a huge issue.  We do have plans to revamp the theme (see [4.9.0 milestone](https://github.com/SocialEngine/phpv4-issues/milestones/4.9.0))

**Comment by Elshara** [comment]
Thanks for the feedback.
