### ISSUE TITLE
All Menus Should Support Icons

### ISSUE THREAD

**Issue by Elshara** [SocialEngine/phpv4-issues#99]
All menus should support icons. Additionally, a favricon should be present under general settings, there isn't one.

**Comment by smazurov** [comment]
Which menus don't support icons that you feel should? favicon can be overwritten. [How to create and change your favicon](http://support.socialengine.com/php/customer/portal/articles/1636877) article explains the process.

**Comment by Elshara** [comment]
Main and mini menus specifically.
